### ISSUE TITLE
GOG Library does not show (Maybe due to 2FA?)

### ISSUE THREAD

**Issue by VortexAcherontic** [Heroic-Games-Launcher/HeroicGamesLauncher#1004]
### Describe the bug

I connected my GOG account with Heroic and noticed it does not list any of my GOG games.

From launcher like Minigalaxy and Lutris I know that I usually get a 2FA request to enter a 4 digit code I receive via email.  
As Heroic did not showed this my guess is it does not implement 2FA yet?

Edit: Not sure but I think this was already known?  #1001

### Add logs

(06:44:48) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(06:44:48) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
[27808:0224/064448.752964:ERROR:vaapi_wrapper.cc(1096)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[27808:0224/064448.753120:ERROR:vaapi_wrapper.cc(1043)] FillProfileInfo_Locked failed for va_profile VAProfileH264Main and entrypoint VAEntrypointVLD
[27808:0224/064448.753158:ERROR:vaapi_wrapper.cc(1096)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[27808:0224/064448.753186:ERROR:vaapi_wrapper.cc(1043)] FillProfileInfo_Locked failed for va_profile VAProfileH264High and entrypoint VAEntrypointVLD
(06:44:49) INFO:    [Backend]:         
  Heroic Version: 2.2.0 Rayleigh
  Legendary Version:  0.20.25 Our Benefactors
  OS: openSUSE Tumbleweed KERNEL: 5.16.8-1-default ARCH: x64
  CPU: AMD Ryzen 7 1800X Eight-Core Processor @3.6 GOVERNOR: schedutil
  RAM: Total: 16.7 GB Available: 10.2 GB
  GRAPHICS: GPU0: NVIDIA GeForce RTX 3080 VRAM: 10240MB DRIVER: 510.54 
  PROTOCOL: x11
  
(06:44:49) INFO:    [Gog]:             Getting data about the user
(06:44:49) WARNING: [Backend]:         Protocol already registered.
[27767:0224/064449.458909:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[27767:0224/064449.458988:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[27767:0224/064449.459054:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(06:44:49) INFO:    [Gog]:             Saved user data to config
(06:44:50) INFO:    [Frontend]:        Refreshing Library
(06:44:50) INFO:    [Gog]:             Getting GOG library
(06:44:50) INFO:    [Gog]:             Number of library pages: 1
(06:44:50) WARNING: [Gog]:             Unable to get covers from gamesdb for Wanderlust: Transsiberian. Trying to get it from api.gog.com
(06:44:51) WARNING: [Gog]:             Unable to get covers from gamesdb for Warhammer Skulls Digital Goodies. Trying to get it from api.gog.com
Error occurred in handler for 'refreshLibrary': TypeError: Cannot read properties of null (reading '_links')
    at GOGLibrary.gogToUnifiedInfo (/opt/Heroic/resources/app.asar/build/gog/library.js:263:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GOGLibrary.sync (/opt/Heroic/resources/app.asar/build/gog/library.js:81:33)
    at async /opt/Heroic/resources/app.asar/build/main.js:526:5
    at async node:electron/js2c/browser_init:193:563
(06:44:51) ERROR:   [Frontend]:        Error: Error invoking remote method 'refreshLibrary': TypeError: Cannot read properties of null (reading '_links')
(06:44:52) INFO:    [Legendary]:       Checking for game updates
(06:44:52) INFO:    [Legendary]:       Found 0 game(s) to update
(06:44:52) INFO:    [Gog]:             Found 0 game(s) to update
(06:44:54) INFO:    [Backend]:         checking for heroic updates

### Steps to reproduce

1. Have 2FA enabled in GOG
2. Connect GOG account
3. No games listed.

### Expected behavior

Heroic to list GOG games

### System Information

- OS [e. g. "Ubuntu"]: 
- Heroic Version [e. g. 2.1.1]:

**Comment by Phlebiac** [comment]
I have a similar problem, although the 2FA authentication worked fine here:

(23:53:19) INFO: [Frontend]: Refreshing Library

(23:53:19) INFO: [Gog]: Getting GOG library

(23:53:20) INFO: [Gog]: Number of library pages: 3

(23:53:20) INFO: [Gog]: Getting data for page 2

(23:53:20) INFO: [Gog]: Getting data for page 3

(23:53:21) WARNING: [Gog]: Unable to get covers from gamesdb for Cave Story®'s Secret Santa. Trying to get it from api.gog.com

(23:53:21) ERROR: [Frontend]: Error: Error invoking remote method 'refreshLibrary': TypeError: Cannot read properties of null (reading '_links')

**Comment by imLinguin** [comment]
Same error as #999
