### ISSUE TITLE
Heroic v2.2.5 javascript error

### ISSUE THREAD

**Issue by dancer69** [Heroic-Games-Launcher/HeroicGamesLauncher#1082]
### Describe the bug

I updated heroic to 2.2.5 today in archlinux and it doesn't start any more. I get the following error:
`heroic
(13:13:11) INFO:    [Legendary]:       Location: '/usr/bin/legendary'
(13:13:11) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, chdir '/home/archuser' -> ''/usr/bin'
    at process.wrappedChdir (node:internal/bootstrap/switches/does_own_process_state:112:14)
    at process.chdir (/opt/Heroic/resources/app.asar/node_modules/graceful-fs/polyfills.js:22:11)
    at Object.<anonymous> (/opt/Heroic/resources/app.asar/build/legendary/user.js:18:9)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)

(heroic:64970): Gtk-WARNING **: 13:13:12.003: Theme parsing error: gtk-contained-dark.css:201:243: 'none' is not a valid color name
[65020:0311/131312.227208:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
`
when I run it from terminal. It doesn't crash, still running, but its window doesn't appear.

### Add logs

No access to "Settings" tab -> "Log" tab " since application window doesn't appear.

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Heroic starts and main window shows up

### System Information

- OS [e. g. "Ubuntu"]: Arch Linux
- Heroic Version [e. g. 2.1.1]: 2.2.5

**Comment by flavioislima** [comment]
I am releasing a possible fix for it. lets hope

**Comment by flavioislima** [comment]
can you try now on 2.2.6?

**Comment by dancer69** [comment]
Yes, I just tried it and it works. Thanks.
