### ISSUE TITLE
I Can't Log In and Access the Library

### ISSUE THREAD

**Issue by ShibShib1** [Heroic-Games-Launcher/HeroicGamesLauncher#1135]
### Describe the bug

Whenever I click continue after logging in it just stays at a blank blue screen. After waiting for a while it stayed like this. If you could please help fix this bug! Or recommend a different launcher, but I trust Heroic will work amazing, 
Thanks, 
-------!

### Add logs

(16:40:52) INFO:    [Legendary]:       Location: C:\Users\---------\Desktop\Heroic\legendary.exe
(16:40:52) INFO:    [Gog]:             Location: C:\Users\\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl.exe
(16:41:03) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Microsoft Windows 10 Enterprise KERNEL: 10.0.19044 ARCH: x64
  CPU: Intel Pentium® Silver N5030 @1.1 
  RAM: Total: 8.4 GB Available: 4.02 GB
  GRAPHICS: GPU0: Intel(R) UHD Graphics 605 VRAM: 1024MB DRIVER:  
  
  
(16:41:03) INFO:    [Backend]:         User Not Found, removing it from Store
(16:41:03) WARNING: [Backend]:         Protocol already registered.
(16:41:09) INFO:    [Backend]:         checking for heroic updates
(16:43:36) INFO:    [Frontend]:        Refreshing Library
(16:43:36) INFO:    [Legendary]:       Refreshing library...
(16:43:36) INFO:    [Frontend]:        No cache found, getting data from legendary...
(16:43:36) INFO:    [Legendary]:       Refreshing library...
(16:45:41) INFO:    [Legendary]:       Logging with Legendary...
(16:45:41) INFO:    [Legendary]:       Logging with Legendary...
(16:45:44) INFO:    [Legendary]:       stderr: [cli] INFO: Testing existing login data if present...

(16:45:44) INFO:    [Legendary]:       stderr: [cli] INFO: Testing existing login data if present...

(16:45:44) INFO:    [Legendary]:       stderr: Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 700, in urlopen

(16:45:44) INFO:    [Legendary]:       stderr:   File "urllib3\connectionpool.py", line 994, in _prepare_proxy
  File "urllib3\connection.py", line 364, in connect
  File "urllib3\connection.py", line 501, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create

(16:45:44) INFO:    [Legendary]:       stderr:   File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.legendary.gl', port=443): Max retries exceeded with url: /v1/version.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "legendary\cli.py", line 3004, in <module>
  File "legendary\cli.py", line 2913, in main
  File "legendary\cli.py", line 92, in auth

(16:45:44) INFO:    [Legendary]:       stderr:   File "legendary\core.py", line 266, in check_for_updates
  File "legendary\api\lgd.py", line 21, in get_version_information
  File "requests\sessions.py", line 542, in get
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.legendary.gl', port=443): Max retries exceeded with url: /v1/version.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
[8552] Failed to execute script 'cli' due to unhandled exception!

(16:45:44) INFO:    [Legendary]:       stderr: Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 700, in urlopen

(16:45:44) INFO:    [Legendary]:       stderr:   File "urllib3\connectionpool.py", line 994, in _prepare_proxy
  File "urllib3\connection.py", line 364, in connect
  File "urllib3\connection.py", line 501, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket

(16:45:44) INFO:    [Legendary]:       stderr:   File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.legendary.gl', port=443): Max retries exceeded with url: /v1/version.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "legendary\cli.py", line 3004, in <module>
  File "legendary\cli.py", line 2913, in main

(16:45:44) INFO:    [Legendary]:       stderr:   File "legendary\cli.py", line 92, in auth
  File "legendary\core.py", line 266, in check_for_updates
  File "legendary\api\lgd.py", line 21, in get_version_information
  File "requests\sessions.py", line 542, in get
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.legendary.gl', port=443): Max retries exceeded with url: /v1/version.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
[13532] F
(16:45:44) INFO:    [Legendary]:       stderr: ailed to execute script 'cli' due to unhandled exception!

(16:45:44) INFO:    [Legendary]:       finished login
(16:45:44) INFO:    [Legendary]:       finished login
(16:45:46) INFO:    [Frontend]:        Refreshing Library
(16:45:46) INFO:    [Legendary]:       Refreshing library...
(16:45:46) INFO:    [Frontend]:        No cache found, getting data from legendary...
(16:45:46) INFO:    [Legendary]:       Refreshing library...

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

What I expect to happen is for the logging screen to load for a minute then refresh or have me restart, then the library will be open with the games.

### Screenshots

![Login Fail](https://user-images.githubusercontent.com/101903648/159083018-152a7419-d1f0-41b0-a800-10fe41fe3e79.PNG)

### System Information

- OS [e. g. "Ubuntu"]: 
- Heroic Version [e. g. 2.1.1]:

### Additional information

Nope, but I really need help

**Comment by flavioislima** [comment]
are you using an alternative legendary binary?
also, fill the OS info, I didn't know it was windows until I read the logs.

**Comment by arielj** [comment]
hey @ShibShib1 can you check if this is still an issue in Heroic 2.3.1? we made fixes in the login flow
