### ISSUE TITLE
The path of proton is not correctly

### ISSUE THREAD

**Issue by cathaysia** [Heroic-Games-Launcher/HeroicGamesLauncher#1147]
### Describe the bug

I create some symbol link to `.config/heroic/tools/wine/` :
```
cd .config/heroic/tools/wine/
ln -s /data/SteamLibrary/steamapps/common/Proton\ 7.0 .
```

Then try to start game, then a error happend:

```
Launch Command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Calluna --wine '/home/tea/.config/heroic/tools/wine/Proton - Experimental/bin/wine' --wine-prefix '/home/tea/.wine/Heroic/Prefixes/Control'
        System Info:
        
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Arch KERNEL: 5.16.15-arch1-1 ARCH: x64
  CPU: Intel Gen Intel® Core™ i7-11800H @2.3 GOVERNOR: powersave
  RAM: Total: 16.5 GB Available: 13.4 GB
  GRAPHICS: GPU0: TigerLake-H GT1 [UHD Graphics]  VRAM: 256MB DRIVER:  GPU1: NVIDIA GeForce RTX 3060 Laptop GPU VRAM: 6144MB DRIVER: 510.54 
  PROTOCOL: x11
  
        Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"autoSyncSaves": true,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"otherOptions": "",
	"savesPath": "/home/tea/.wine/Heroic/Prefixes/Control/drive_c/users/tea/Local Settings/Application Data/Remedy/Control/Default-Epic-User/",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/tea/.wine/Heroic/Prefixes/Control",
	"wineVersion": {
		"bin": "'/home/tea/.config/heroic/tools/wine/Proton - Experimental/bin/wine'",
		"name": "Wine - Proton - Experimental",
		"type": "wine",
		"wineserver": "",
		"wineboot": "'/home/tea/.config/heroic/tools/wine/Proton - Experimental/bin/wine' wineboot"
	},
	"useSteamRuntime": false
}

        Game Log:
        [cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Calluna...
Traceback (most recent call last):
  File "legendary/cli.py", line 3004, in <module>
  File "legendary/cli.py", line 2919, in main
  File "legendary/cli.py", line 685, in launch_game
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1704, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/tea/.config/heroic/tools/wine/Proton - Experimental/bin/wine'
[3535] Failed to execute script 'cli' due to unhandled exception!
```

Please notice this line:

```
		"wineboot": "'/home/tea/.config/heroic/tools/wine/Proton - Experimental/bin/wine' wineboot"
```

In fact, the layout of `/home/tea/.config/heroic/tools/wine/Proton - Experimental` is :

```
.
├── files
│   ├── bin
│   │   ├── msidb
│   │   ├── wine
│   │   ├── wine64
│   │   ├── wine64-preloader
│   │   ├── wine-preloader
│   │   └── wineserver
│   │   ├── gstreamer-1.0
│   │   ├── pkgconfig
│   │   ├── vkd3d
│   │   └── wine
│   │   ├── cmake
│   │   ├── gstreamer-1.0
│   │   ├── pkgconfig
│   │   ├── vkd3d
│   │   └── wine
│   ├── share
│   │   ├── default_pfx
│   │   ├── fonts
│   │   └── wine
│   └── steampipe_fixups_mtime
└── version
```

So, the true path is `/home/tea/.config/heroic/tools/wine/Proton - Experimental/files/bin/wine`

### Add logs

Launch Command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Calluna --wine '/home/tea/.config/heroic/tools/wine/Proton - Experimental/bin/wine' --wine-prefix '/home/tea/.wine/Heroic/Prefixes/Control'
        System Info:
        
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Arch KERNEL: 5.16.15-arch1-1 ARCH: x64
  CPU: Intel Gen Intel® Core™ i7-11800H @2.3 GOVERNOR: powersave
  RAM: Total: 16.5 GB Available: 13.4 GB
  GRAPHICS: GPU0: TigerLake-H GT1 [UHD Graphics]  VRAM: 256MB DRIVER:  GPU1: NVIDIA GeForce RTX 3060 Laptop GPU VRAM: 6144MB DRIVER: 510.54 
  PROTOCOL: x11
  
        Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"autoSyncSaves": true,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"otherOptions": "",
	"savesPath": "/home/tea/.wine/Heroic/Prefixes/Control/drive_c/users/tea/Local Settings/Application Data/Remedy/Control/Default-Epic-User/",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/tea/.wine/Heroic/Prefixes/Control",
	"wineVersion": {
		"bin": "'/home/tea/.config/heroic/tools/wine/Proton - Experimental/bin/wine'",
		"name": "Wine - Proton - Experimental",
		"type": "wine",
		"wineserver": "",
		"wineboot": "'/home/tea/.config/heroic/tools/wine/Proton - Experimental/bin/wine' wineboot"
	},
	"useSteamRuntime": false
}

        Game Log:
        [cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Calluna...
Traceback (most recent call last):
  File "legendary/cli.py", line 3004, in <module>
  File "legendary/cli.py", line 2919, in main
  File "legendary/cli.py", line 685, in launch_game
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1704, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/tea/.config/heroic/tools/wine/Proton - Experimental/bin/wine'
[3535] Failed to execute script 'cli' due to unhandled exception!

        

### Steps to reproduce

1. Start Game
2. Click on '...'
3. Scroll down to '...'

### Expected behavior

game start

### System Information

- OS [e. g. "archlinux"]:  archlinux
- Heroic Version :2.2.6

**Comment by cathaysia** [comment]
Thanks.   :)
________________________________
