### ISSUE TITLE
2.3.0-beta.2 Cannot start any Windows GOG game under Linux

### ISSUE THREAD

**Issue by flytrapdev** [Heroic-Games-Launcher/HeroicGamesLauncher#1286]
### Describe the bug

When attempting to start any GOG game with the new beta release, the game will not start.
The typical Wine configuration window appears, but then the game doesn't start.

The logs indicate that Wine couldn't be found in /usr/bin/wine, yet it is there.

I have tried installing another game to test, and using Proton instead of Wine, and the same thing happened.

I'm not sure this is related to Heroic itself, it seems like it could be a gogdl issue judging by the logs.

### Add logs

```
Launch Command: WINEPREFIX=/home/matthieu/Games/Heroic/Prefixes/PowerSlave Exhumed /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/home/matthieu/Games/Heroic/PowerSlave Exhumed" 1432253578 --wine '/usr/bin/wine' --wine-prefix "/home/matthieu/Games/Heroic/Prefixes/PowerSlave Exhumed" --os windows

System Info:

  Heroic Version: 2.3.0-beta.2 Caesar Clown
  Legendary Version:  0.20.25 Our Benefactors
  OS: Ubuntu KERNEL: 5.13.0-40-generic ARCH: x64
  CPU: AMD Ryzen 5 2600X Six-Core Processor @3.6 GOVERNOR: ondemand
  RAM: Total: 15.55 GiB Available: 13.1 GiB
  GRAPHICS: GPU0: NVIDIA GeForce GTX 1070 Ti VRAM: 8192MB DRIVER: 510.60.02 
  PROTOCOL: x11
  

Game Settings: {
	"audioFix": false,
	"autoInstallDxvk": true,
	"autoInstallVkd3d": false,
	"enableEsync": false,
	"enableFsync": false,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"offlineMode": false,
	"otherOptions": "",
	"savesPath": "",
	"showFps": false,
	"showMangohud": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/matthieu/Games/Heroic/Prefixes/PowerSlave Exhumed",
	"wineVersion": {
		"bin": "'/usr/bin/wine'",
		"name": "Wine Default - wine-7.0",
		"type": "wine",
		"wineserver": "'/usr/bin/wineserver'",
		"wineboot": "'/usr/bin/wineboot'"
	},
	"useSteamRuntime": false
}

Error Log:
Traceback (most recent call last):
  File "gogdl/cli.py", line 44, in <module>
  File "gogdl/cli.py", line 40, in main
File "gogdl/launch.py", line 78, in launch
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1821, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: "'/usr/bin/wine'"
[23418] Failed to execute script 'cli' due to unhandled exception!

Game Log:
Launch command: ["'/usr/bin/wine'", '/home/matthieu/Games/Heroic/PowerSlave Exhumed/anubis_x64.exe']
```

### Steps to reproduce

1. Install a GOG game
2. Click on "Play now"
3. Wine configuration window shows up
4. Window closes, game does not start.

### Expected behavior

The game should start as normal.

### System Information

- OS [e. g. "Ubuntu"]: Kubuntu 20.04
- Heroic Version [e. g. 2.1.1]: 2.3.0-beta.2

**Comment by flavioislima** [comment]
Try beta 3

**Comment by flytrapdev** [comment]
Beta 3 gave the same result :

```
Launch Command: WINEPREFIX=/home/matthieu/Games/Heroic/Prefixes/PowerSlave Exhumed /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/home/matthieu/Games/Heroic/PowerSlave Exhumed" 1432253578 --wine '/usr/bin/wine' --wine-prefix "/home/matthieu/Games/Heroic/Prefixes/PowerSlave Exhumed" --os windows

System Info:

  Heroic Version: 2.3.0-beta.3 Caesar Clown
  Legendary Version:  0.20.25 Our Benefactors
  OS: Ubuntu KERNEL: 5.13.0-41-generic ARCH: x64
  CPU: AMD Ryzen 5 2600X Six-Core Processor @3.6 GOVERNOR: ondemand
  RAM: Total: 15.55 GiB Available: 13.74 GiB
  GRAPHICS: GPU0: NVIDIA GeForce GTX 1070 Ti VRAM: 8192MB DRIVER: 510.60.02 
  PROTOCOL: x11
  

Game Settings: {
	"altLegendaryBin": "",
	"altGogdlBin": "",
	"addDesktopShortcuts": false,
	"addStartMenuShortcuts": false,
	"audioFix": false,
	"autoInstallDxvk": true,
	"autoInstallVkd3d": false,
	"customWinePaths": [],
	"darkTrayIcon": false,
	"defaultInstallPath": "/home/matthieu/Games/Heroic",
	"defaultWinePrefix": "/home/matthieu/Games/Heroic/Prefixes",
	"disableController": false,
	"discordRPC": false,
	"egsLinkedPath": "",
	"enableEsync": false,
	"enableFsync": false,
	"exitToTray": false,
	"language": "en",
	"maxRecentGames": 5,
	"maxWorkers": 0,
	"minimizeOnLaunch": false,
	"nvidiaPrime": false,
	"offlineMode": false,
	"otherOptions": "",
	"showFps": false,
	"showMangohud": false,
	"showUnrealMarket": false,
	"startInTray": false,
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/matthieu/Games/Heroic/Prefixes/PowerSlave Exhumed",
	"wineVersion": {
		"bin": "'/usr/bin/wine'",
		"name": "Wine Default - wine-7.0",
		"type": "wine",
		"wineserver": "'/usr/bin/wineserver'",
		"wineboot": "'/usr/bin/wineboot'"
	},
	"maxSharpness": 2,
	"savesPath": "",
	"targetExe": "",
	"useSteamRuntime": false
}

Error Log:
Traceback (most recent call last):
  File "gogdl/cli.py", line 44, in <module>
  File "gogdl/cli.py", line 40, in main
File "gogdl/launch.py", line 78, in launch
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1821, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: "'/usr/bin/wine'"
[27678] Failed to execute script 'cli' due to unhandled exception!

Game Log:
Launch command: ["'/usr/bin/wine'", '/home/matthieu/Games/Heroic/PowerSlave Exhumed/anubis_x64.exe']
```

**Comment by imLinguin** [comment]
These quotes again. 
Is that problem happening when you run this command manually?
`WINEPREFIX=/home/matthieu/Games/Heroic/Prefixes/PowerSlave Exhumed /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/home/matthieu/Games/Heroic/PowerSlave Exhumed" 1432253578 --wine '/usr/bin/wine' --wine-prefix "/home/matthieu/Games/Heroic/Prefixes/PowerSlave Exhumed" --os windows`

**Comment by flytrapdev** [comment]
That was the problem. I fixed it by changing back and forth between wine-lutris and wine 7.0
Thanks !
