### ISSUE TITLE
[Steamdeck] Installing Linux Native (GOG) game (Trüberbrook) fails (unhandled exception)

### ISSUE THREAD

**Issue by Qowy** [Heroic-Games-Launcher/HeroicGamesLauncher#1298]
### Describe the bug

Trying to Linux Native GOG game Trüberbrook fails on the steamdeck.

It tries to download, and then aborts.

I think it might be tripping up on the "ü"

Issue might be with gogdl

### Add logs

```
(12:04:11) INFO:    [Legendary]:       Location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(12:04:11) INFO:    [Gog]:             Location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(12:04:12) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.13.0-valve10.3-1-neptune-02176-g5fe416c4acd8 ARCH: x64
  CPU: AMD Custom APU 0405 @1.86 GOVERNOR: schedutil
  RAM: Total: 15.6 GB Available: 11.6 GB
  GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
  PROTOCOL: x11
  
(12:04:12) INFO:    [Gog]:             Getting data about the user
(12:04:12) ERROR:   [Backend]:         Failed to register protocol with OS.
(12:04:12) INFO:    [Gog]:             Saved user data to config
(12:04:13) INFO:    [Frontend]:        Refreshing Library
(12:04:13) INFO:    [Gog]:             Getting GOG library
(12:04:14) INFO:    [Gog]:             Number of library pages: 1
(12:04:14) INFO:    [Gog]:             Saved games data
(12:04:14) INFO:    [Legendary]:       Refreshing library...
(12:04:14) INFO:    [Legendary]:       Refreshing Epic Games...
(12:04:14) INFO:    [Legendary]:       Refreshing Epic Games...
(12:04:15) INFO:    [Legendary]:       [cli] INFO: Logging in...
(12:04:15) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(12:04:16) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(12:04:16) INFO:    [Legendary]:       Updating game list
(12:04:16) INFO:    [Legendary]:       Game List Updated
(12:04:18) INFO:    [Legendary]:       Checking for game updates
(12:04:18) INFO:    [Legendary]:       Found 0 game(s) to update
(12:04:18) INFO:    [Gog]:             Found 0 game(s) to update
(12:04:18) INFO:    [Backend]:         checking for heroic updates
(12:04:18) INFO:    [Backend]:         skipping heroic updates
(12:04:49) INFO:    [Gog]:             Installing 1289701346 with: "/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl" download 1289701346 --platform linux --path="/run/media/mmcblk0p1/Games" --skip-dlcs --lang="en"  |& tee "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/1289701346.log"
(12:04:50) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:04:51) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:04:53) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:04:54) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:04:56) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:04:57) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:04:59) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:00) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:02) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:03) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:05) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:06) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:08) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:09) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:11) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:12) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:14) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:15) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:17) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:18) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:20) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:21) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:23) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:24) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:26) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:27) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:29) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:30) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:32) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:33) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:35) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:36) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:38) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:39) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:41) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:42) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:44) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:45) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:47) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:48) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:50) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:51) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:53) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:54) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:56) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:57) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:05:59) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:06:00) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:06:02) INFO:    [Backend]:         Progress: 1289701346 /MiB/undefined
(12:06:03) INFO:    [Backend]:         finished installing
(12:06:03) INFO:    [Backend]:         operation interrupted
(12:06:03) INFO:    [Frontend]:        Refreshing Library
(12:06:03) INFO:    [Gog]:             Getting GOG library
(12:06:04) INFO:    [Gog]:             Number of library pages: 1
(12:06:04) INFO:    [Gog]:             Saved games data
(12:06:04) INFO:    [Legendary]:       Refreshing library...
(12:06:04) INFO:    [Legendary]:       Updating game list
(12:06:04) INFO:    [Legendary]:       Game List Updated

```
```
[API] INFO: Getting info from products endpoint for id: 1289701346
[LINUX] INFO: Getting folder name from windows manifest
[LINUX] INFO: Getting downlad info
[API] INFO: Getting info from products endpoint for id: 1289701346
[LINUX] INFO: Using existing file
[LINUX] INFO: Checking available disk space
warning [/home/deck/.var/app/com.heroicgameslauncher.hgl/cache/heroicGOGdl/tr_berbrook_1_6_31066.s]:  959462 extra bytes at beginning or within zipfile
  (attempting to process anyway)
[LINUX] INFO: Looks fine continuing
[LINUX] INFO: Unpacking game files
[LINUX] INFO: Unpacking installer using unzip
warning [/home/deck/.var/app/com.heroicgameslauncher.hgl/cache/heroicGOGdl/tr_berbrook_1_6_31066.s]:  959462 extra bytes at beginning or within zipfile
  (attempting to process anyway)
[LINUX] INFO: Moving game files
Traceback (most recent call last):
  File "gogdl/cli.py", line 44, in <module>
  File "gogdl/cli.py", line 41, in main
  File "gogdl/dl/manager.py", line 30, in download
  File "gogdl/dl/manager.py", line 97, in get_download_metadata
  File "gogdl/dl/linux_native.py", line 51, in download
  File "gogdl/dl/linux_native.py", line 120, in download_installer
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1754, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 125: ordinal not in range(128)
[225] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

Launch Heroic

Install Trüberbrook

### Expected behavior

Installing Game

### System Information

- OS SteamOS
- Heroic Version 2.2.6

**Comment by arielj** [comment]
I understand this is fixed in a GOGdl update? cc @imLinguin do you know if this is already part of the next release?

**Comment by imLinguin** [comment]
Yes, that's resolved
