### ISSUE TITLE
Wine prefix is not being generated for each game install causing failure to launch

### ISSUE THREAD

**Issue by kuynh** [Heroic-Games-Launcher/HeroicGamesLauncher#1345]
### Describe the bug

When installing any game from the epic games store, the wine prefix of the game is not created. I have tried proton-ge, proton 7.0, and proton experimental. This issue has only popped up recently and did not happen when I was playing about a few weeks ago.

### Add logs

Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH=/var/run/media/mmcblk0p1/heroic/prefix/AbsoluteDrift /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 19927295d6e3467887d4e830d8c85963 --no-wine --wrapper "'/home/deck/.steam/root/compatibilitytools.d/GE-Proton7-18/proton' run"

System Info:

  Heroic Version: 2.3.2 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.13.0-valve10.3-1-neptune-02176-g5fe416c4acd8 ARCH: x64
  CPU: AMD Custom APU 0405 @1.82 GOVERNOR: schedutil
  RAM: Total: 14.49 GiB Available: 12.13 GiB
  GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
  PROTOCOL: x11
  

Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"otherOptions": "",
	"savesPath": "",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/var/run/media/mmcblk0p1/heroic/prefix/AbsoluteDrift",
	"wineVersion": {
		"bin": "/home/deck/.steam/root/compatibilitytools.d/GE-Proton7-18/proton",
		"name": "Proton - GE-Proton7-18",
		"type": "proton"
	},
	"useSteamRuntime": false
}

Error Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 19927295d6e3467887d4e830d8c85963...
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton7-18/proton", line 1589, in <module>
g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton7-18/proton", line 1383, in init_session
g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton7-18/proton", line 710, in setup_prefix
with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-18/filelock.py", line 323, in __enter__
self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-18/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-18/filelock.py", line 384, in _acquire
fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/media/mmcblk0p1/heroic/prefix/AbsoluteDrift/pfx.lock'

### Steps to reproduce

1. Have heroic games launcher downloaded from flathub
2. Install game
3. Launch game 

### Expected behavior

The game launches.

### System Information

- OS [e. g. "Ubuntu"]: Steam OS
- Heroic Version [e. g. 2.1.1]: 2.3.2
- Flatpak

**Comment by lumingzh** [comment]
Create the prefix directory manually fix the problem.

**Comment by wolfy887** [comment]
I switched to lutris-7.2 which made the prefix then back to proton it might take a bit. but that's what worked for me

**Comment by flavioislima** [comment]
I am working on a fix for that

**Comment by willhowlett** [comment]
I'm still seeing this happen on v2.3.2

I can only get the prefix folder to generate by switching to wine and running the game once

```
Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH=/home/deck/Games/Heroic/Prefixes/SunlessSea /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 2420b50453144c07b3b847fff941275d --no-wine --wrapper "'/home/deck/.steam/steam/steamapps/common/Proton 7.0/proton' run"

System Info:

  Heroic Version: 2.3.2 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.13.0-valve10.3-1-neptune-02176-g5fe416c4acd8 ARCH: x64
  CPU: AMD Custom APU 0405 @1.81 GOVERNOR: schedutil
  RAM: Total: 14.49 GiB Available: 11.51 GiB
  GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
  PROTOCOL: x11
  

Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"otherOptions": "",
	"savesPath": "",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/deck/Games/Heroic/Prefixes/SunlessSea",
	"wineVersion": {
		"bin": "/home/deck/.steam/steam/steamapps/common/Proton 7.0/proton",
		"name": "Proton - Proton 7.0",
		"type": "proton"
	},
	"useSteamRuntime": false
}

Error Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 2420b50453144c07b3b847fff941275d...
Traceback (most recent call last):
  File "/home/deck/.steam/steam/steamapps/common/Proton 7.0/proton", line 1392, in <module>
g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/steam/steamapps/common/Proton 7.0/proton", line 1194, in init_session
g_compatdata.setup_prefix()
  File "/home/deck/.steam/steam/steamapps/common/Proton 7.0/proton", line 704, in setup_prefix
with self.prefix_lock:
  File "/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/filelock.py", line 323, in __enter__
self.acquire()
  File "/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/filelock.py", line 271, in acquire
self._acquire()
  File "/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/filelock.py", line 384, in _acquire
fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/Games/Heroic/Prefixes/SunlessSea/pfx.lock'

```

**Comment by flavioislima** [comment]
Yes it's fixed on 2.3.3.

**Comment by willhowlett** [comment]
Ah great thanks (I thought from the PR linked above you were saying it was fixed in 2.3.2)

**Comment by flavioislima** [comment]
Yes, my English is a bit rubbish sometimes.
The pr naming could be better 😅
