### ISSUE TITLE
Game importing validation bug

### ISSUE THREAD

**Issue by JordanPlayz158** [Heroic-Games-Launcher/HeroicGamesLauncher#1364]
### Describe the bug

When importing a game, whether or not the game is actually imported/the directory being proper. This is only for Epic/Legendary Games

Here is the log but as explained in discord, it doesn't give any meaningful issue because the way game importing is validated is a bit flawed: https://paste.jordanplayz158.xyz/?8bc5a65f02de52c3#ASQZu5iNiE4e4EhLzeZWmaXe8TzcJcTuhnqRyKkUGxqr (here is the start of the discord discussion: https://discord.com/channels/812703221789097985/812703452085223434/977591817220542514)

Here is a video on how to do it: https://dl.jordanplayz158.xyz/2022-05-22%2009-25-11.mp4

### Add logs

https://paste.jordanplayz158.xyz/?8bc5a65f02de52c3#ASQZu5iNiE4e4EhLzeZWmaXe8TzcJcTuhnqRyKkUGxqr

### Steps to reproduce

1. Go to the download button icon on any game in Epic Games section (must be not imported/installed to have the import option)
2. Go to any path and hit import (as long as it's not the game directory)
3. You will now get a Game Imported notification indicating success but the frontend will tell you it's not installed properly but the backend in the logs will say it imported successfully incorrectly

Watch the video or follow above: https://dl.jordanplayz158.xyz/2022-05-22%2009-25-11.mp4

### Expected behavior

Either no notification or Game Import Failure

### Screenshots

Even better than a screenshot: https://dl.jordanplayz158.xyz/2022-05-22%2009-25-11.mp4

### System Information

- OS [e. g. "Ubuntu"]: Manjaro Linux
- Heroic Version [e. g. 2.1.1]: v2.3.3

**Comment by krablord** [comment]
got same issue trying to import cyberpunk from downloading it before with heroic on different linux distro

**Comment by JordanPlayz158** [comment]
Issue is still present on Version 2.4.1

**Comment by flavioislima** [comment]
@JordanPlayz158 what happens if you try importing it directly with Legendary? It gives some error message?

**Comment by JordanPlayz158** [comment]
This is the output that occurs from incorrectly importing a game (importing a game with the wrong directory)
```legendary import Duckbill /mnt/HDD

[Core] INFO: Trying to re-use existing login session...
[Core] INFO: Downloading latest manifest for "Duckbill"
[Core] WARNING: Unable to download manifest from "download.epicgames.com" (status: 403), trying next URL...
[Core] WARNING: Unable to download manifest from "download2.epicgames.com" (status: 403), trying next URL...
[Core] WARNING: Unable to download manifest from "download3.epicgames.com" (status: 403), trying next URL...
[Core] WARNING: Unable to download manifest from "download4.epicgames.com" (status: 403), trying next URL...
[cli] ERROR: No files belonging to Game "Yooka-Laylee and the Impossible Lair" (Duckbill) found in the specified location, please verify that the path is correct.
[cli] INFO: Did you mean "/mnt/HDD/YookaLaylee"?```

**Comment by arielj** [comment]
fixed by https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/4667

**Comment by jtgans** [comment]
Looks like there was a regression. It's broken in 2.21.0:

```
(08:38:43) [INFO]:    [Gog]:             Importing 1711230643: GOGDL_CONFIG_PATH=/home/jtgans/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/jtgans/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json import /run/user/1000/doc/577e0d58/install
(08:38:43) [INFO]:    [Gog]:             Running command: GOGDL_CONFIG_PATH=/home/jtgans/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/jtgans/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(08:38:43) [INFO]:    [Gog]:             Got install info from cache for 1711230643 on windows platform
(08:38:43) [INFO]:    [Gog]:             Got install info from cache for 1711230643 on windows platform
libnotify-Message: 08:38:43.928: App Icon is not available when using Portal Notifications
(08:38:43) [ERROR]:   [Gog]:             Failed to import 1711230643: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Module.td [as importGame] (/app/bin/heroic/resources/app.asar/build/main/main.js:16:1985)
    at /app/bin/heroic/resources/app.asar/build/main/main.js:187:7249
    at Session.<anonymous> (node:electron/js2c/browser_init:2:116462)
(08:38:43) [INFO]:    [Backend]:         Writing config for 1711230643
(08:38:43) [INFO]:    [Backend]:         imported The Elder Scrolls V: Skyrim Special Edition
```
