### ISSUE TITLE
I created a bug....

### ISSUE THREAD

**Issue by finalfansty11** [Heroic-Games-Launcher/HeroicGamesLauncher#1371]
### Describe the bug

I returned a game on Epic. And when I open the heroic launcher, i still see that game exist, so I click it and try to delete. BUt the launcher turns black screen and cannt do anything. I try to install and uninstall it many times, when i open the heroic launcher, it just turn black screen....

### Add logs

react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'app_name')
    at index.tsx:211:54
    at Array.filter (<anonymous>)
    at index.tsx:210:25
    at Object.useMemo (react-dom.production.min.js:172:115)
    at t.useMemo (react.production.min.js:23:113)
    at Pi (index.tsx:190:25)
    at si (react-dom.production.min.js:157:137)
    at $s (react-dom.production.min.js:267:460)
    at Ll (react-dom.production.min.js:250:347)
    at Pl (react-dom.production.min.js:250:278)
scheduler.production.min.js:12 Uncaught TypeError: Cannot read properties of null (reading 'app_name')
    at index.tsx:211:54
    at Array.filter (<anonymous>)
    at index.tsx:210:25
    at Object.useMemo (react-dom.production.min.js:172:115)
    at t.useMemo (react.production.min.js:23:113)
    at Pi (index.tsx:190:25)
    at si (react-dom.production.min.js:157:137)
    at $s (react-dom.production.min.js:267:460)
    at Ll (react-dom.production.min.js:250:347)
    at Pl (react-dom.production.min.js:250:278)

### Steps to reproduce

1. Go to click the game 
2. See error

### Expected behavior

file:///app/bin/heroic/resources/app.asar/build/static/js/main.4aa8956c.js
this is the issue show me...

### System Information

- steam OS [e. g. "Ubuntu"]: 
- Heroic  newest Version :

**Comment by finalfansty11** [comment]
os Name is steamOS Holo
Os version is 3.2
