### ISSUE TITLE
[macOS] Games not installing in directory’s with spaces in them

### ISSUE THREAD

**Issue by duvbolone** [Heroic-Games-Launcher/HeroicGamesLauncher#1375]
### Describe the bug

Every time I try to install a game it stops immediately installing, the install was trying to get performed on an external disk.

Renaming the disk so that it hasn't a space fixes the bug and I can install perfectly

### Add logs

**log from settings**

```
(19:43:15) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(19:43:20) INFO:    [Legendary]:       Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(19:43:20) INFO:    [Gog]:             GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(19:43:20) INFO:    [Backend]:         
  Heroic Version: 2.3.3 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: macOS KERNEL: 21.3.0 ARCH: x64
  CPU: Apple M1 @2.4 
  RAM: Total: 8 GiB Available: 6.8 GiB
  GRAPHICS: GPU0: Apple M1 VRAM: nullMB DRIVER:  
  
  
(19:43:21) WARNING: [Backend]:         Protocol already registered.
(19:43:28) INFO:    [Frontend]:        Refreshing Library
(19:43:28) INFO:    [Legendary]:       Refreshing library...
(19:43:28) INFO:    [Legendary]:       Refreshing Epic Games...
(19:43:29) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list
(19:43:36) DEBUG:   [Legendary]:       Using cached install info
(19:43:36) DEBUG:   [Legendary]:       Using cached install info
(19:43:36) WARNING: [Backend]:         default is not writable
(19:43:37) WARNING: [Backend]:         /Users/duvbobruni/Games/Heroic is not writable
(19:43:37) INFO:    [Legendary]:       Updating game list
(19:43:37) INFO:    [Legendary]:       Game List Updated
(19:43:37) WARNING: [Backend]:         /Users/duvbobruni/Games/Heroic is not writable
(19:43:37) INFO:    [Legendary]:       Checking for game updates: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list-installed --check-updates --tsv
(19:43:37) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list-installed --check-updates --tsv
(19:43:45) INFO:    [Legendary]:       Found 0 game(s) to update
(19:43:45) INFO:    [Gog]:             Found 0 game(s) to update
(19:43:45) DEBUG:   [Legendary]:       Using cached install info
(19:43:45) INFO:    [Legendary]:       Installing 9d2d0eb64d5c44529cece33fe2a46482 with: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary install 9d2d0eb64d5c44529cece33fe2a46482 --platform Windows --base-path "/Volumes/MB DISK/GTAV_heroic_install" --skip-dlcs --skip-sdl -y
(19:43:45) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary install 9d2d0eb64d5c44529cece33fe2a46482 --platform Windows --base-path "/Volumes/MB DISK/GTAV_heroic_install" --skip-dlcs --skip-sdl -y
(19:43:45) DEBUG:   [Legendary]:       Logging to file "/Users/duvbobruni/Library/Application Support/heroic/GamesConfig/9d2d0eb64d5c44529cece33fe2a46482.log"
(19:43:52) INFO:    [Backend]:         finished installing
(19:43:52) INFO:    [Backend]:         operation interrupted
(19:43:52) INFO:    [Frontend]:        Refreshing Library
(19:43:52) INFO:    [Legendary]:       Refreshing library...
(19:43:52) INFO:    [Legendary]:       Updating game list
(19:43:52) INFO:    [Legendary]:       Game List Updated

```
**log from directory suggested by discord**

```
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Preparing download for "Grand Theft Auto V" (9d2d0eb64d5c44529cece33fe2a46482)...
[Core] INFO: Parsing game manifest...
[Core] INFO: "/Volumes/MB" does not exist, creating...
Traceback (most recent call last):
  File "legendary/cli.py", line 3004, in <module>
  File "legendary/cli.py", line 2921, in main
  File "legendary/cli.py", line 916, in install_game
  File "legendary/core.py", line 1345, in prepare_download
  File "os.py", line 223, in makedirs
PermissionError: [Errno 13] Permission denied: '/Volumes/MB'
[12592] Failed to execute script 'cli' due to unhandled exception!

```
### Steps to reproduce

1. Go to any uninstalled game in your library
2. Click install
3. Pick a directory with spaces in it
4. Try installing

### Expected behavior

Game begins installing or gives a clear error

### System Information

- OS: macOS
- Heroic Version: 2.3.3
- Model: MacBook Air late 2020
- CPU: M1
- GPU: M1(7 core)
- RAM: 8GB
- Internal Storage: 245GB SSD
- External Storage: 2TB usb HDD(Disk game was trying to be installed on)

**Comment by flavioislima** [comment]
@duvbolone Can you check on latest release. This should be fixed.

**Comment by duvbolone** [comment]
Uhm, how do I check in an easy way without downloading gta with 100 gigs all over again lol
