### ISSUE TITLE
Fortnite does not launch

### ISSUE THREAD

**Issue by AverytheFurry** [Heroic-Games-Launcher/HeroicGamesLauncher#1497]
### Describe the bug

I installed fortnite, along with save the world, and the launcher did not appear to download any binaries after looking through the files.

### Add logs

```
Launch Command: C:\Users\user\AppData\Local\Temp\2AcU8mOP8ty6cUDrUn8hwOjMSVl\resources\app.asar.unpacked\build\bin\win32\legendary launch Fortnite --language en

System Info:
Heroic Version: 2.4.0-beta Caesar Clown
Legendary Version:  0.20.26 Dark Energy
OS: Microsoft Windows 10 Pro KERNEL: 10.0.19043 ARCH: x64
CPU: AMD Ryzen 9 3900X 12-Core Processor @3.8 
RAM: Total: 15.91 GiB Available: 8.92 GiB
GRAPHICS: GPU0: NVIDIA GeForce GTX 1080 VRAM: 8192MB DRIVER: 472.12 


Game Settings: {
	"altLegendaryBin": "",
	"altGogdlBin": "",
	"addDesktopShortcuts": false,
	"addStartMenuShortcuts": false,
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"customWinePaths": [],
	"darkTrayIcon": true,
	"defaultInstallPath": "D:\\Heroic",
	"defaultWinePrefix": "C:\\Users\\user\\Games\\Heroic\\Prefixes",
	"disableController": false,
	"egsLinkedPath": "windows",
	"maxRecentGames": 5,
	"maxWorkers": 0,
	"minimizeOnLaunch": false,
	"nvidiaPrime": false,
	"otherOptions": "",
	"showFps": false,
	"showUnrealMarket": false,
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": {},
	"wineVersion": {}
}

Error Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Fortnite...
Traceback (most recent call last):
  File "legendary\cli.py", line 3016, in <module>
File "legendary\cli.py", line 2931, in main
File "legendary\cli.py", line 691, in launch_game
File "subprocess.py", line 951, in __init__
File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[7520] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Download
2. Launch
3. Observe nothing happening

### Expected behavior

I expected the game to launch

### System Information

- OS [e. g. "Windows 10"]: 
- Heroic Version [e. g. 2.4.0-beta]:

**Comment by Etaash-mathamsetty** [comment]
also having this issue

**Comment by arielj** [comment]
Use this portable build from this PR https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2505715711, it fixes the issue with fornite

**Comment by meanindra** [comment]
Same issue
I am using windows portable Beta v2.4.0-beta
```log
Launch Command: C:\Users\Anindra\AppData\Local\Temp\2AcU8mOP8ty6cUDrUn8hwOjMSVl\resources\app.asar.unpacked\build\bin\win32\legendary launch Fortnite --language en

System Info:
Heroic Version: 2.4.0-beta Caesar Clown
Legendary Version:  0.20.26 Dark Energy
OS: Microsoft Windows 10 Home Single Language KERNEL: 10.0.19044 ARCH: x64
CPU: Intel Core™ i7-10510U @1.8 
RAM: Total: 7.84 GiB Available: 3.92 GiB
GRAPHICS: GPU0: NVIDIA GeForce MX250 VRAM: 2048MB DRIVER: 516.59 GPU1: Intel(R) UHD Graphics VRAM: 1024MB DRIVER:  


Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"nvidiaPrime": false,
	"otherOptions": "",
	"showFps": false,
	"useGameMode": false,
	"winePrefix": "C:\\Users\\Anindra/.wine",
	"wineCrossoverBottle": "Heroic",
	"wineVersion": {},
	"language": ""
}

Error Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Fortnite...
Traceback (most recent call last):
  File "legendary\cli.py", line 3016, in <module>
  File "legendary\cli.py", line 2931, in main
  File "legendary\cli.py", line 691, in launch_game
File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[8784] Fa
iled to execute script 'cli' due to unhandled exception!
```

**Comment by Hatsune-Cthulhu** [comment]
This does not seem to be fixed, and even if installing a portable version made it work, it's not exactly a solution worthy of closing the issue.

**Comment by Etaash-mathamsetty** [comment]
> This does not seem to be fixed, and even if installing a portable version made it work, it's not exactly a solution worthy of closing the issue.

the issue SHOULD be closed, the bug fix has been merged into main and a release with the fix is coming soon

**Comment by Hatsune-Cthulhu** [comment]
> > This does not seem to be fixed, and even if installing a portable version made it work, it's not exactly a solution worthy of closing the issue.
> 
> the issue SHOULD be closed, the bug fix has been merged into main and a release with the fix is coming soon

I tested the beta release though and it wasn't fixed

**Comment by Nocccer** [comment]
> > > This does not seem to be fixed, and even if installing a portable version made it work, it's not exactly a solution worthy of closing the issue.
> > 
> > 
> > the issue SHOULD be closed, the bug fix has been merged into main and a release with the fix is coming soon
> 
> I tested the beta release though and it wasn't fixed

Because it was merged into main, but we didn't release anything new yet.
