### ISSUE TITLE
`Latest Log` in game's tools crashes the app

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1697]
### Describe the bug

The link to open the `Latest Log` in the Tools tab in the game's details makes the app go blank.

The `Log` link in the sidebar and the `Report a problem running this game` work with no issue.

### Add logs

```
index.tsx:228 Uncaught TypeError: Cannot read properties of undefined (reading 'cloud_save_enabled')
    at SidebarLinks (index.tsx:228:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateFunctionComponent (react-dom.development.js:17356:1)
    at beginWork (react-dom.development.js:19063:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
SidebarLinks @ index.tsx:228
renderWithHooks @ react-dom.development.js:14985
updateFunctionComponent @ react-dom.development.js:17356
beginWork @ react-dom.development.js:19063
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
(anonymous) @ index.tsx:83
Promise.then (async)
(anonymous) @ index.tsx:82
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
react_devtools_backend.js:4026 The above error occurred in the <SidebarLinks> component:

    at SidebarLinks (http://localhost:3000/static/js/bundle.js:3840:82)
    at aside
    at Sidebar (http://localhost:3000/static/js/bundle.js:4593:68)
    at Router (http://localhost:3000/static/js/bundle.js:102544:15)
    at HashRouter (http://localhost:3000/static/js/bundle.js:101388:5)
    at div
    at App (http://localhost:3000/static/js/bundle.js:407:56)
    at GlobalState (http://localhost:3000/static/js/bundle.js:19502:5)
    at I18nextWithTranslation (http://localhost:3000/static/js/bundle.js:100204:31)
    at Suspense
    at I18nextProvider (http://localhost:3000/static/js/bundle.js:99655:19)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
overrideMethod @ react_devtools_backend.js:4026
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
(anonymous) @ index.tsx:83
Promise.then (async)
(anonymous) @ index.tsx:82
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
index.tsx:228 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'cloud_save_enabled')
    at SidebarLinks (index.tsx:228:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateFunctionComponent (react-dom.development.js:17356:1)
    at beginWork (react-dom.development.js:19063:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
```

### Steps to reproduce

1. Click a game card
2. Click Tools
3. Click Latest Log

### Expected behavior

It should show the logs like the other 2 buttons

### System Information

- Heroic Version [e. g. 2.1.1]: beta branch

**Comment by Nocccer** [comment]
Maybe this bug was introduced by https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1646

**Comment by flavioislima** [comment]
Are you sure you are on the latest commit? I saw this one but fixed it already with other fixes.

**Comment by flavioislima** [comment]
Ah ok, it is the link we have on the tools. Do we need that link? Since there is already the one in the sidebar and on the game page. I believe we can remove it and make the list of tools cleaner.
