### ISSUE TITLE
Javascript error when opening the Wine Manager for the first time

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1699]
### Describe the bug

When starting Heroic, the first time the Wine Manager screen is used, there's an error in the browser console while it's fetching the data. It only happens the first time.

### Add logs

```
react_devtools_backend.js:4026 MUI: The `value` provided to the Tabs component is invalid.
The Tab with this `value` ("Wine-GE") is not part of the document layout.
Make sure the tab item is present in the document or that it's not `display: none`. 
    at Tabs (http://localhost:3000/static/js/bundle.js:51446:83)
    at div
    at WineManager (http://localhost:3000/static/js/bundle.js:19155:68)
    at Routes (http://localhost:3000/static/js/bundle.js:102611:5)
    at main
    at Router (http://localhost:3000/static/js/bundle.js:102544:15)
    at HashRouter (http://localhost:3000/static/js/bundle.js:101388:5)
    at div
    at App (http://localhost:3000/static/js/bundle.js:407:56)
    at GlobalState (http://localhost:3000/static/js/bundle.js:19502:5)
    at I18nextWithTranslation (http://localhost:3000/static/js/bundle.js:100204:31)
    at Suspense
    at I18nextProvider (http://localhost:3000/static/js/bundle.js:99655:19)
```

### Steps to reproduce

1. Open Heroic
2. Open DevTools if not already opened
3. Click Wine Manager
4. Check DevTools console

### Expected behavior

It shouldn't show any error.

### System Information

- Heroic Version [e. g. 2.1.1]: beta branch

### Additional information

this is not critical at all, the wine manager works just fine, but that error is a sign that something is not completely right

**Comment by Nocccer** [comment]
Seems some frontend problem. Maybe you can fix it? I am not good at frontend :D

**Comment by flavioislima** [comment]
this is happening because we are using `Wine-GE` as a value for the component but it is not correct. Should be `winege` or maybe `wine-ge`.

**Comment by flavioislima** [comment]
Fixed
