### ISSUE TITLE
WINE prefix being created for some native Linux games on first launch

### ISSUE THREAD

**Issue by eunichron** [Heroic-Games-Launcher/HeroicGamesLauncher#1913]
### Describe the bug

Launcher creates a WINE prefix for some Linux native games when launching the game for the first time.

### Add logs

[Uploading heroic-2022-10-16T00_36_27.040Z.log…]()

### Steps to reproduce

1. Click on "Library"
2. Filter by GOG titles
3. Filter by Linux platform
4. Select title to install
5. Launch game when it is finished installing

### Expected behavior

Native Linux game will launch without creating a WINE prefix.

### System Information

`Operating System: Arch Linux
KDE Plasma Version: 5.26.0
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 6.0.1-arch2-1 (64-bit)
Graphics Platform: Wayland
Processors: 24 × AMD Ryzen 9 5900X 12-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6900 XT
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B550M AORUS PRO-P`
- Heroic Version 2.4.3

### Additional information

I have only confirmed this with BATTLETECH and Stellaris from GOG. I have also installed Shadowrun Returns, which did not create a WINE prefix when I first launched it.

**Comment by arielj** [comment]
One question, can you provide a clean log with only the game that presented the issue? because you mention installing games but I see a lot of imports too and logs for multiple games.

Could it be that for the games with the issue you initially imported them and then installed them? because I see the imports say `--platform windows` (which I think it's an known issue, that it imports games as windows even if they are not) and if you uninstall and then installed the native version the configuration might be a mix of the old one with wine stuff and the new one that shouldn't have wine stuff.

Would be useful to have only the log from installing Battletech for example.

**Comment by eunichron** [comment]
I did not import any of them. I did previously have those games installed through Lutris, but I went through a fresh download and install process for each one when switching to Heroic. I have never installed Windows versions of those games on my Linux partition with Lutris or otherwise.

I went ahead and wiped Battletech and did another fresh install. It did it again, creating another WINE prefix when launching the first time. Here is the log from that session:

```
(22:15:38) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(22:15:39) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(22:15:39) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(22:15:39) INFO:    [Backend]:         

Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Arch KERNEL: 6.0.1-arch2-1 ARCH: x64
CPU: AMD Ryzen 9 5900X 12-Core Processor @3.7 GOVERNOR: schedutil
RAM: Total: 31.25 GiB Available: 26.95 GiB
GRAPHICS: GPU0: Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] VRAM: 1MB DRIVER:  
PROTOCOL: wayland

(22:15:39) INFO:    [Gog]:             Getting data about the user
(22:15:39) WARNING: [Backend]:         Protocol already registered.
(22:15:39) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(22:15:39) INFO:    [Gog]:             Saved user data to config
(22:15:39) INFO:    [Backend]:         Checking for new Heroic Updates
(22:15:39) INFO:    [Frontend]:        Refreshing Library
(22:15:39) INFO:    [Legendary]:       Refreshing library...
(22:15:39) INFO:    [Legendary]:       Refreshing Epic Games...
(22:15:39) INFO:    [Gog]:             Getting GOG library
(22:15:40) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(22:15:40) INFO:    [Gog]:             Number of library pages: 2
(22:15:40) INFO:    [Gog]:             Getting data for page 2
(22:15:40) INFO:    [Legendary]:       Updating game list
(22:15:40) INFO:    [Legendary]:       Game List Updated
(22:15:41) INFO:    [Gog]:             Saved games data
(22:15:41) INFO:    [Gog]:             Getting game metadata.
(22:15:41) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1482783682 --token <redacted> --lang=en-US --os windows
(22:15:41) INFO:    [Gog]:             Getting game metadata.
(22:15:41) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1482783682 --token <redacted> --lang=en-US --os windows
(22:15:41) DEBUG:   [Backend]:         {"free":631358476288,"diskSize":1000203091968,"message":"588 GiB / 931.51 GiB","validPath":true}
(22:15:41) DEBUG:   [Backend]:         {"free":631358476288,"diskSize":1000203091968,"message":"588 GiB / 931.51 GiB","validPath":true}
(22:15:41) INFO:    [Backend]:         Downloaded Winetricks
(22:15:42) INFO:    [Legendary]:       Checking for game updates.
(22:15:42) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(22:15:42) INFO:    [Legendary]:       Found 0 game(s) to update
(22:15:42) INFO:    [Gog]:             Found 0 game(s) to update
(22:15:44) INFO:    [Gog]:             Getting game metadata.
(22:15:44) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1482783682 --token <redacted> --lang=en-US --os windows
(22:15:44) DEBUG:   [Backend]:         {"free":631358476288,"diskSize":1000203091968,"message":"588 GiB / 931.51 GiB","validPath":true}
(22:15:49) INFO:    [Backend]:         Writing config for 1482783682
(22:15:49) INFO:    [Backend]:         {
  "autoInstallDxvk": false,
  "autoInstallVkd3d": false,
  "preferSystemLibs": false,
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "showFps": false,
  "useGameMode": false,
  "language": "",
  "wineVersion": {
    "bin": "/usr/bin/wine",
    "name": "Wine Default - wine-7.18 (Staging)",
    "type": "wine",
    "wineserver": "/usr/bin/wineserver",
    "wineboot": "/usr/bin/wineboot"
  },
  "winePrefix": "/home/ryan/Games/Heroic/Prefixes/BATTLETECH"
}
(22:15:49) INFO:    [Backend]:         Preventing machine to sleep
(22:15:50) INFO:    [Gog]:             Installing 1482783682: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl download 1482783682 --platform linux --path=/home/ryan/Games/Heroic --token <redacted> --skip-dlcs --lang=en
(22:15:50) DEBUG:   [Gog]:             Logging to file "/home/ryan/.config/heroic/GamesConfig/1482783682.log"
(22:15:52) INFO:    [Gog]:             Progress for 1482783682: 0%/0.00MiB/00:00:00
...
(22:28:43) INFO:    [Gog]:             Progress for 1482783682: 99.9%/14198.43MiB/00:00:50
(22:29:04) INFO:    [Gog]:             Getting game metadata.
(22:29:04) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1482783682 --token <redacted> --lang=en-US --os windows
(22:34:30) INFO:    [Gog]:             Getting game metadata.
(22:34:30) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1482783682 --token <redacted> --lang=en-US --os windows
(22:35:45) INFO:    [Gog]:             Getting game metadata.
(22:35:45) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1482783682 --token <redacted> --lang=en-US --os windows
(22:35:45) INFO:    [Backend]:         operation interrupted
(22:35:52) INFO:    [Backend]:         finished installing
(22:35:53) INFO:    [Frontend]:        Refreshing Library
(22:35:53) INFO:    [Gog]:             Getting GOG library
(22:35:53) INFO:    [Gog]:             Getting game metadata.
(22:35:53) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1482783682 --token <redacted> --lang=en-US --os windows
(22:35:53) INFO:    [Gog]:             Getting game metadata.
(22:35:53) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1482783682 --token <redacted> --lang=en-US --os windows
(22:35:53) INFO:    [Gog]:             Number of library pages: 2
(22:35:53) INFO:    [Gog]:             Getting data for page 2
(22:35:54) INFO:    [Gog]:             Saved games data
(22:35:56) INFO:    [Gog]:             Found 0 game(s) to update
(22:35:57) INFO:    [Gog]:             Getting game metadata.
(22:35:57) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1482783682 --token <redacted> --lang=en-US --os windows
(22:36:01) INFO:    [Backend]:         Launching BATTLETECH (1482783682)
(22:36:01) INFO:    [Backend]:         Preventing display from sleep
(22:36:01) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(22:36:01) ERROR:   Couldn't find all library folders of Wine Default - wine-7.18 (Staging)!
Missing undefined or undefined!
Falling back to system libraries!
(22:36:01) DEBUG:   [Legendary]:       Running Wine command: "/usr/bin/wine" wineboot --init && "/usr/bin/wineserver" --wait
(22:36:13) DEBUG:   [Legendary]:       Ran Wine command: "/usr/bin/wine" wineboot --init && "/usr/bin/wineserver" --wait
(22:36:13) INFO:    [Backend]:         Created/Updated Wineprefix at /home/ryan/Games/Heroic/Prefixes/BATTLETECH
(22:36:13) ERROR:   [Backend]:         Error: Request failed with status code 404
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
(22:36:13) INFO:    [Backend]:         Stopping Display Power Saver Blocker
(22:36:13) INFO:    [Frontend]:        Refreshing Library
(22:36:13) INFO:    [Gog]:             Getting GOG library
(22:36:14) INFO:    [Gog]:             Number of library pages: 2
(22:36:14) INFO:    [Gog]:             Getting data for page 2
(22:36:15) INFO:    [Gog]:             Saved games data
(22:36:16) INFO:    [Gog]:             Found 0 game(s) to update
(22:36:37) INFO:    [Backend]:         Launching BATTLETECH (1482783682)
(22:36:37) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(22:36:38) INFO:    [Gog]:             Launching BATTLETECH: LD_PRELOAD= /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch /home/ryan/Games/Heroic/BATTLETECH 1482783682 --platform linux
(22:37:00) INFO:    [Backend]:         Stopping Display Power Saver Blocker
(22:37:00) INFO:    [Frontend]:        Refreshing Library
(22:37:00) INFO:    [Gog]:             Getting GOG library
(22:37:01) INFO:    [Gog]:             Number of library pages: 2
(22:37:01) INFO:    [Gog]:             Getting data for page 2
(22:37:02) INFO:    [Gog]:             Saved games data
(22:37:08) INFO:    [Gog]:             Found 0 game(s) to update

```

I've also attached a screenshot of the game folder just as confirmation that I do have the Linux version installed.
![Screenshot_20221015_224009](https://user-images.githubusercontent.com/5695721/196016825-4cc1d486-0583-4993-acf8-58e1da98ceb4.png)

**Comment by arielj** [comment]
Hmmm weird, then Heroic is definitely doing something weird, in the first log I see:

```
(19:36:48) INFO: [Gog]: Importing 1482783682: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl import /home/ryan/Games/Heroic/BATTLETECH
...
(19:36:51) INFO: [Backend]: imported BATTLETECH
```

**Comment by eunichron** [comment]
I've noticed a lot of odd quirky behavior with Heroic on desktop Linux, I'm just not sure how much of it is due to the app itself or my own config.

**Comment by flavioislima** [comment]
@eunichron can you reproduce the issue on the beta? I actually cannot reproduce it either on beta or stable.

**Comment by eunichron** [comment]
> @eunichron can you reproduce the issue on the beta? I actually cannot reproduce it either on beta or stable.

I tried it again on a fresh system install, and the issue was recreated on 2.4.3 while installing Stellaris from GOG.

I uninstalled Stellaris and Heroic 2.4.3, and installed the 2.5.0 beta directly from the git. I was not able to recreate the issue on the beta.

**Comment by redromnon** [comment]
@eunichron This should be fixed in the stable 2.5.0 release.
