### ISSUE TITLE
Warning: path might not be writable

### ISSUE THREAD

**Issue by JakobDev** [Heroic-Games-Launcher/HeroicGamesLauncher#2072]
### Describe the bug

I use a folder on my second internal hard drive (ext4) to install Games with Heroic, so this folder is preselected in the install dialog. If I want to install a Game, this directory is preselected with the message "Warning: path might not be writable.". However, this not is not true. The path is fully writeable. If I click on the Browse button and select the same directory, the message is gone and I can install the Game. It happens on both, GOG and Epic.

It also happens on the latest Beta, but the Button shows no "Force Install" instead of being disabled, what makes this a lot better.

### Add logs
```
(19:56:06) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(19:56:06) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(19:56:06) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(19:56:06) INFO:    [Backend]:         

Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: ManjaroLinux KERNEL: 5.15.78-1-MANJARO ARCH: x64
CPU: AMD Ryzen 5 2600 Six-Core Processor @3.4 GOVERNOR: schedutil
RAM: Total: 15.57 GiB Available: 654.56 MiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 2060 SUPER VRAM: 8192MB DRIVER: 520.56.06 
PROTOCOL: x11

(19:56:06) INFO:    [Gog]:             Getting data about the user
(19:56:07) WARNING: [Backend]:         Protocol already registered.
(19:56:07) INFO:    [Gog]:             Saved user data to config
(19:56:07) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(19:56:08) INFO:    [Backend]:         Checking for new Heroic Updates
(19:56:08) INFO:    [Frontend]:        Refreshing Library
(19:56:08) INFO:    [Legendary]:       Refreshing library...
(19:56:08) INFO:    [Legendary]:       Refreshing Epic Games...
(19:56:08) INFO:    [Gog]:             Getting GOG library
(19:56:08) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(19:56:08) INFO:    [Gog]:             Number of library pages: 1
(19:56:09) INFO:    [Gog]:             Saved games data
(19:56:09) INFO:    [DXVKInstaller]:   Updating vkd3d to: vkd3d-proton-2.7.tar.xz
(19:56:09) INFO:    [Legendary]:       Updating game list
(19:56:09) INFO:    [Legendary]:       Game List Updated
(19:56:09) INFO:    [Backend]:         Downloaded Winetricks
(19:56:10) INFO:    [Legendary]:       Checking for game updates.
(19:56:10) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(19:56:10) INFO:    [DXVKInstaller]:   downloaded vkd3d
(19:56:10) INFO:    [DXVKInstaller]:   extracting vkd3d
(19:56:10) INFO:    [DXVKInstaller]:   extracting vkd3d updated!
(19:56:11) INFO:    [Legendary]:       Found 4 game(s) to update
(19:56:12) INFO:    [Gog]:             Found 0 game(s) to update
(19:56:15) INFO:    [Gog]:             Getting game metadata.
(19:56:15) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1440426004 --token <redacted> --lang=en-US --os windows
(19:56:19) INFO:    [Gog]:             Getting game metadata.
(19:56:19) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1440426004 --token <redacted> --lang=en-US --os windows
(19:56:19) INFO:    [Gog]:             Getting game metadata.
(19:56:19) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1440426004 --token <redacted> --lang=en-US --os windows
(19:56:19) ERROR:   [Backend]:         Failed to check disk space for "'/run/media/jakob/Datenplatte/Heroic'": InvalidPathError: The following path is invalid (should start by /): '/run/media/jakob/Datenplatte/Heroic'
    at /opt/Heroic/resources/app.asar/node_modules/check-disk-space/dist/check-disk-space.cjs:176:24
    at new Promise (<anonymous>)
    at checkUnix (/opt/Heroic/resources/app.asar/node_modules/check-disk-space/dist/check-disk-space.cjs:175:20)
    at checkDiskSpace (/opt/Heroic/resources/app.asar/node_modules/check-disk-space/dist/check-disk-space.cjs:196:12)
    at /opt/Heroic/resources/app.asar/build/main.js:405:83
    at FSReqCallback.oncomplete (node:fs:188:23)
(19:56:19) WARNING: [Backend]:         Cannot write to "'/run/media/jakob/Datenplatte/Heroic'": Error: ENOENT: no such file or directory, access ''
(19:56:19) DEBUG:   [Backend]:         {"free":0,"diskSize":0,"message":"0 B / 0 B","validPath":false}
(19:56:19) ERROR:   [Backend]:         Failed to check disk space for "'/run/media/jakob/Datenplatte/Heroic'": InvalidPathError: The following path is invalid (should start by /): '/run/media/jakob/Datenplatte/Heroic'
    at /opt/Heroic/resources/app.asar/node_modules/check-disk-space/dist/check-disk-space.cjs:176:24
    at new Promise (<anonymous>)
    at checkUnix (/opt/Heroic/resources/app.asar/node_modules/check-disk-space/dist/check-disk-space.cjs:175:20)
    at checkDiskSpace (/opt/Heroic/resources/app.asar/node_modules/check-disk-space/dist/check-disk-space.cjs:196:12)
    at /opt/Heroic/resources/app.asar/build/main.js:405:83
    at FSReqCallback.oncomplete (node:fs:188:23)
(19:56:19) WARNING: [Backend]:         Cannot write to "'/run/media/jakob/Datenplatte/Heroic'": Error: ENOENT: no such file or directory, access ''
(19:56:19) DEBUG:   [Backend]:         {"free":0,"diskSize":0,"message":"0 B / 0 B","validPath":false}
(19:56:20) ERROR:   [Backend]:         Failed to check disk space for "'/run/media/jakob/Datenplatte/Heroic'": InvalidPathError: The following path is invalid (should start by /): '/run/media/jakob/Datenplatte/Heroic'
    at /opt/Heroic/resources/app.asar/node_modules/check-disk-space/dist/check-disk-space.cjs:176:24
    at new Promise (<anonymous>)
    at checkUnix (/opt/Heroic/resources/app.asar/node_modules/check-disk-space/dist/check-disk-space.cjs:175:20)
    at checkDiskSpace (/opt/Heroic/resources/app.asar/node_modules/check-disk-space/dist/check-disk-space.cjs:196:12)
    at /opt/Heroic/resources/app.asar/build/main.js:405:83
    at FSReqCallback.oncomplete (node:fs:188:23)
(19:56:20) WARNING: [Backend]:         Cannot write to "'/run/media/jakob/Datenplatte/Heroic'": Error: ENOENT: no such file or directory, access ''
(19:56:20) DEBUG:   [Backend]:         {"free":0,"diskSize":0,"message":"0 B / 0 B","validPath":false}
(19:56:49) DEBUG:   [Backend]:         {"free":102735347712,"diskSize":983347249152,"message":"95.68 GiB / 915.81 GiB","validPath":true}
```

### Steps to reproduce

Don't know how to reproduce it on other PCs

### Expected behavior

It should not show this error/warning when the Path is writeable

### Screenshots

Stable:
![grafik](https://user-images.githubusercontent.com/15185051/204105206-1a6ea81e-519b-4f60-b68b-ca1ce70d7675.png)

Beta:
![grafik](https://user-images.githubusercontent.com/15185051/204105296-3c622908-f53a-44bb-813e-65dcc2e4f0b5.png)

### System Information

OS: Manjaro
Heroic Version: 2.4.3
Install method: AUR

**Comment by flavioislima** [comment]
This happens because it checks up to two levels of the path, so if Heroic folder does not exists it might show this because jakob is not writable, At least you can continue installing.

**Comment by JakobDev** [comment]
> so if Heroic folder does not exists it might show this

The folder exists and already contains some Games
