### ISSUE TITLE
error at startup

### ISSUE THREAD

**Issue by Ochinchin-san** [Heroic-Games-Launcher/HeroicGamesLauncher#2074]
### Describe the bug

when running the desktop application nothing happens, heroic does not open. when running in terminal gives an error.

### Add logs

[Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
[2893:1126/225816.882322:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882402:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882445:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882484:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882522:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882559:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882595:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882635:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882681:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882717:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882752:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882787:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882823:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882858:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882893:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882928:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.882966:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883006:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883043:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883078:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883113:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883148:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883181:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883215:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883255:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883291:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883330:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883363:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883398:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883432:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883465:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883503:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883538:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883571:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883609:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883644:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883677:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883712:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883746:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[2893:1126/225816.883781:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
(node:2861) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at getLegendaryVersion (/opt/Heroic/resources/app.asar/build/utils.js:186:9)
    at async getSystemInfo (/opt/Heroic/resources/app.asar/build/utils.js:247:30)
    at async /opt/Heroic/resources/app.asar/build/main.js:241:28
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:2861) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

### Steps to reproduce

execute heroic in terminal
see error

### Expected behavior

the execution of the application.

### System Information

Arch
Heroic 2.4.3-2

**Comment by flavioislima** [comment]
Which Arch Linux is that? we currently support only Manjaro and Garuda.
Try to get more help on our discord where we have people that use all kinds of distros and setup.
