### ISSUE TITLE
Cannot install some games due to getInstallInfo issue

### ISSUE THREAD

**Issue by mario039** [Heroic-Games-Launcher/HeroicGamesLauncher#2080]
### Describe the bug

So my problem is a week ago I had downloaded 5 games after the update none of these games started so I decided to delete them and download them again but even if I see them gray in the library so not downloaded every time I try to download them again I get "select exe to run" with no error log even though there is obviously no exe

### Add logs

```text
(17:06:53) INFO:    [Connection]:       Connectivity: check-online
(17:06:53) INFO:    [Connection]:       Pinging external endpoints
(17:06:53) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(17:06:53) INFO:    [Legendary]:        Legendary location: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(17:06:53) INFO:    [Gog]:              GOGDL location: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(17:06:53) WARNING: [Backend]:          Protocol already registered.
(17:06:54) INFO:    [Connection]:       Connectivity: online
(17:06:54) INFO:    [Backend]:          User Not Found, removing it from Store
(17:06:54) INFO:    [Gog]:              Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(17:06:54) INFO:    [Backend]:          VCRuntime is installed
(17:06:54) INFO:    [Backend]:          Checking for new Heroic Updates
(17:06:58) INFO:    [Backend]:          

Heroic Version: 2.5.0-beta.3 Caesar Clown
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: Microsoft Windows 11 Home Insider Preview KERNEL: 10.0.25247 ARCH: x64
CPU: AMD Ryzen 5 3600X 6-Core Processor @3.8 
RAM: Total: 31.95 GiB Available: 18.45 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 2060 SUPER VRAM: 8192MB DRIVER: 526.98 


(17:07:05) INFO:    [Frontend]:         Refreshing Library
(17:07:05) INFO:    [Legendary]:        Refreshing library...
(17:07:05) INFO:    [Frontend]:         No cache found, getting data from legendary...
(17:07:05) INFO:    [Legendary]:        Refreshing library...
(17:07:05) INFO:    [Gog]:              Found 0 game(s) to update
(17:08:17) INFO:    [Legendary]:        Logging in: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary auth --code <redacted>
(17:08:18) INFO:    [Frontend]:         Refreshing Library
(17:08:18) INFO:    [Legendary]:        Refreshing library...
(17:08:18) INFO:    [Legendary]:        Refreshing Epic Games...
(17:08:18) INFO:    [Legendary]:        Game list updated, got 300 games & DLCs
(17:08:18) INFO:    [Frontend]:         No cache found, getting data from legendary...
(17:08:18) INFO:    [Legendary]:        Refreshing library...
(17:08:18) INFO:    [Legendary]:        Game list updated, got 300 games & DLCs
(17:08:18) INFO:    [Frontend]:         Force Update
(17:08:18) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list
(17:08:20) INFO:    [Frontend]:         Refreshing Library
(17:08:20) INFO:    [Legendary]:        Refreshing library...
(17:08:20) INFO:    [Legendary]:        Refreshing Epic Games...
(17:08:21) INFO:    [Legendary]:        Game list updated, got 300 games & DLCs
(17:08:21) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:08:21) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:08:21) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:08:21) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:08:21) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:08:21) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:08:21) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:08:21) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary info Finch --platform Windows --json
(17:08:21) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list
(17:08:21) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary info 923130ebb546417b9d3115507f752d34 --platform Windows --json
(17:08:21) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary info e8964b869b6849bea41eefec766cd665 --platform Windows --json
(17:08:21) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary info f4f0d39fbb4640e0be62aa91d9eca87d --platform Windows --json
(17:08:21) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary info 0afb9d54dd3743a582b48b506466d3f8 --platform Windows --json
(17:08:21) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary info 5c147002780d4e6eb292f54edfe73fda --platform Windows --json
(17:08:21) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary info Nautilus --platform Windows --json
(17:08:21) ERROR:   [Legendary]:        Error Getting Info from Epic API
(17:08:21) INFO:    [Legendary]:        Getting Info from Epic API
(17:08:21) INFO:    [Legendary]:        Getting Info from Epic API
(17:08:21) INFO:    [Legendary]:        Getting Info from Epic API
(17:08:22) INFO:    [Legendary]:        Getting Info from Epic API
(17:08:22) INFO:    [Legendary]:        Getting Info from Epic API
(17:08:22) ERROR:   [Legendary]:        Error Getting Info from Epic API
(17:08:23) ERROR:   [Legendary]:        Error: Failed to parse install info for Finch with: SyntaxError: Unexpected end of JSON input
    at T.getInstallInfo (C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:34:8846)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:109:6563
    at async node:electron/js2c/browser_init:193:551
(17:08:23) ERROR:   [Legendary]:        Error: Failed to parse install info for 923130ebb546417b9d3115507f752d34 with: SyntaxError: Unexpected end of JSON input
    at T.getInstallInfo (C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:34:8846)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:109:6563
    at async node:electron/js2c/browser_init:193:551
(17:08:23) ERROR:   [Legendary]:        Error: Failed to parse install info for f4f0d39fbb4640e0be62aa91d9eca87d with: SyntaxError: Unexpected end of JSON input
    at T.getInstallInfo (C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:34:8846)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:109:6563
    at async node:electron/js2c/browser_init:193:551
(17:08:23) ERROR:   [Legendary]:        Error: Failed to parse install info for 0afb9d54dd3743a582b48b506466d3f8 with: SyntaxError: Unexpected end of JSON input
    at T.getInstallInfo (C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:34:8846)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:109:6563
    at async node:electron/js2c/browser_init:193:551
(17:08:23) ERROR:   [Legendary]:        Error: Failed to parse install info for Nautilus with: SyntaxError: Unexpected end of JSON input
    at T.getInstallInfo (C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:34:8846)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:109:6563
    at async node:electron/js2c/browser_init:193:551
(17:08:23) ERROR:   [Legendary]:        Error: Failed to parse install info for e8964b869b6849bea41eefec766cd665 with: SyntaxError: Unexpected end of JSON input
    at T.getInstallInfo (C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:34:8846)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:109:6563
    at async node:electron/js2c/browser_init:193:551
(17:08:23) ERROR:   [Legendary]:        Error: Failed to parse install info for 5c147002780d4e6eb292f54edfe73fda with: SyntaxError: Unexpected end of JSON input
    at T.getInstallInfo (C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:34:8846)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:109:6563
    at async node:electron/js2c/browser_init:193:551
(17:08:31) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:08:31) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:08:32) INFO:    [Frontend]:         Refreshing Library
(17:08:32) INFO:    [Legendary]:        Refreshing library...
(17:08:32) INFO:    [Legendary]:        Refreshing Epic Games...
(17:08:32) INFO:    [Legendary]:        Game list updated, got 300 games & DLCs
(17:08:32) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary info Nautilus --platform Windows --json
(17:08:32) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary info Nautilus --platform Windows --json
(17:08:32) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list
(17:08:32) DEBUG:   [Backend]:          {"free":237960896512,"diskSize":2000396742656,"message":"221.62 GiB / 1.82 TiB","validPath":true}
(17:08:33) ERROR:   [Legendary]:        Error: Failed to parse install info for Nautilus with: SyntaxError: Unexpected end of JSON input
    at T.getInstallInfo (C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:34:8846)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:109:6563
    at async node:electron/js2c/browser_init:193:551
(17:08:33) ERROR:   [Legendary]:        Error: Failed to parse install info for Nautilus with: SyntaxError: Unexpected end of JSON input
    at T.getInstallInfo (C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:34:8846)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:109:6563
    at async node:electron/js2c/browser_init:193:551
(17:21:36) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:21:36) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:21:37) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary info 923130ebb546417b9d3115507f752d34 --platform Windows --json
(17:21:37) DEBUG:   [Backend]:          {"free":237960896512,"diskSize":2000396742656,"message":"221.62 GiB / 1.82 TiB","validPath":true}
(17:21:37) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary info 923130ebb546417b9d3115507f752d34 --platform Windows --json
(17:21:38) ERROR:   [Legendary]:        Error: Failed to parse install info for 923130ebb546417b9d3115507f752d34 with: SyntaxError: Unexpected end of JSON input
    at T.getInstallInfo (C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:34:8846)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:109:6563
    at async node:electron/js2c/browser_init:193:551
(17:21:38) ERROR:   [Legendary]:        Error: Failed to parse install info for 923130ebb546417b9d3115507f752d34 with: SyntaxError: Unexpected end of JSON input
    at T.getInstallInfo (C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:34:8846)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:109:6563
    at async node:electron/js2c/browser_init:193:551
(17:23:51) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:23:51) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:23:51) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary info 923130ebb546417b9d3115507f752d34 --platform Windows --json
(17:23:51) DEBUG:   [Backend]:          {"free":237960896512,"diskSize":2000396742656,"message":"221.62 GiB / 1.82 TiB","validPath":true}
(17:23:52) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary info 923130ebb546417b9d3115507f752d34 --platform Windows --json
(17:23:53) ERROR:   [Legendary]:        Error: Failed to parse install info for 923130ebb546417b9d3115507f752d34 with: SyntaxError: Unexpected end of JSON input
    at T.getInstallInfo (C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:34:8846)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:109:6563
    at async node:electron/js2c/browser_init:193:551
(17:23:54) ERROR:   [Legendary]:        Error: Failed to parse install info for 923130ebb546417b9d3115507f752d34 with: SyntaxError: Unexpected end of JSON input
    at T.getInstallInfo (C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:34:8846)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:109:6563
    at async node:electron/js2c/browser_init:193:551
(17:25:00) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:25:00) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:25:01) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary info 923130ebb546417b9d3115507f752d34 --platform Windows --json
(17:25:01) DEBUG:   [Backend]:          {"free":237960896512,"diskSize":2000396742656,"message":"221.62 GiB / 1.82 TiB","validPath":true}
(17:25:01) INFO:    [Legendary]:        Running command: C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary info 923130ebb546417b9d3115507f752d34 --platform Windows --json
(17:25:02) ERROR:   [Legendary]:        Error: Failed to parse install info for 923130ebb546417b9d3115507f752d34 with: SyntaxError: Unexpected end of JSON input
    at T.getInstallInfo (C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:34:8846)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:109:6563
    at async node:electron/js2c/browser_init:193:551
(17:25:02) ERROR:   [Legendary]:        Error: Failed to parse install info for 923130ebb546417b9d3115507f752d34 with: SyntaxError: Unexpected end of JSON input
    at T.getInstallInfo (C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:34:8846)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\mario\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.1e86465e.js:109:6563
    at async node:electron/js2c/browser_init:193:551
```

### Steps to reproduce

1. Go to 'Library'
2. Click on 'one of the five games I've deleted'
3. A game weight loading appears but then the error appears

### Expected behavior

Simply that the game starts

### Screenshots

![Screenshot (31)](https://user-images.githubusercontent.com/30559958/204148636-a0f708c8-124c-4a17-b887-cdbc23188910.png)

### System Information

- OS ["Windows 11"]: 
- Heroic Version [2.5.0-beta.3]:

**Comment by flavioislima** [comment]
Yes, I came across the same issue. Can you try downloading the windows build from this PR to see if it is fixed?
For me it is on macOS and Linux:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/suites/9526054196/artifacts/452570036

**Comment by mario039** [comment]
So now the situation has changed I see the games that didn't start but with "game not available" and I can't start or delete them
![Screenshot (32)](https://user-images.githubusercontent.com/30559958/204150082-c064f2d2-90e5-4859-96b1-a985c6e38cde.png)

**Comment by flavioislima** [comment]
@mario039 when clicking launch the game, it should show an option to uninstall it.

**Comment by flavioislima** [comment]
Something like this
![image](https://user-images.githubusercontent.com/26871415/204150260-9bf258fe-53a3-4d1f-91df-9d74ed479ddf.png)

**Comment by mario039** [comment]
Unfortunately nothing appears when I click to start the game

**Comment by flavioislima** [comment]
You have manually deleted the game folders or have uninstalled them?

**Comment by flavioislima** [comment]
So, for Epic Games, you can manually delete the entries on:
`users\yourusername\.config\legendary\installed.json`

Before that you can also try to reset Heroic, it won't delete games or log you out of any accounts, will only delete configs and cache.

**Comment by mario039** [comment]
Thanks bro you saved me
