### ISSUE TITLE
[Heroic version 2.5.0] Games do not start on game titles with single quote

### ISSUE THREAD

**Issue by Markvis** [Heroic-Games-Launcher/HeroicGamesLauncher#2143]
### Describe the bug

Game fails to launch when game name has a single quote such as `No Man's Sky`
Prefix folder/file is created with game name but the launcher is looking for `No Mans Sky`

work around : rename the prefix folder name after being created from `No Man's Sky` to `No Mans Sky`

### Add logs

```text
System Info:
Heroic Version: 2.5.0 Yamato
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: Freedesktop SDK KERNEL: 5.13.0-valve21.3-1-neptune ARCH: x64
CPU: AMD Custom APU 0405 @1.9 GOVERNOR: schedutil
RAM: Total: 11.54 GiB Available: 8.36 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB  
PROTOCOL: x11

Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"preferSystemLibs": false,
	"autoSyncSaves": false,
	"enableFSR": false,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"offlineMode": false,
	"enviromentOptions": [
		{
			"key": "DXVK_ASYNC",
			"value": "1"
		}
	],
	"wrapperOptions": [],
	"savesPath": "",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"useSteamRuntime": false,
	"language": "",
	"wineVersion": {
		"bin": "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-42/proton",
		"name": "Proton - GE-Proton7-42",
		"type": "proton"
	},
	"winePrefix": "/home/deck/Games/Heroic/Prefixes/No Man's Sky",
	"eacRuntime": false,
	"battlEyeRuntime": false,
	"gogSaves": [
		{
			"name": "saves",
			"location": "/home/deck/Games/Heroic/Prefixes/No Man's Sky/pfx/drive_c/users/steamuser/AppData/Roaming/HelloGames/NMS"
		}
	]
}

Game launched at: Mon Dec 05 2022 14:10:15 GMT-0800 (Pacific Standard Time)

An exception occurred when launching the game:
Error: Command failed: STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/deck/.steam/steam" STEAM_COMPAT_DATA_PATH='/home/deck/Games/Heroic/Prefixes/No Mans Sky' /home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-42/proton run reg /?
Traceback (most recent call last):
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-42/proton", line 1808, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-42/proton", line 1591, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-42/proton", line 777, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-42/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-42/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-42/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/Games/Heroic/Prefixes/No Mans Sky/pfx.lock'

    at ChildProcess.exithandler (node:child_process:407:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
```

### Steps to reproduce

1. Run a game with `'` on its name ex. `No Man's Sky`
2. Game does not start

### Expected behavior

Game starts

### System Information

- OS [e. g. "Ubuntu"]: Steam OS (Steam deck)
- Heroic Version [e. g. 2.1.1]: 2.5.0

**Comment by arielj** [comment]
is this still an issue in Heroic 2.7?

**Comment by Etaash-mathamsetty** [comment]
Doesn't seem to be, all these characters are filtered out now, but only OP can confirm this

**Comment by arielj** [comment]
closing, we can reopen if it still happens in 2.8.0
