### ISSUE TITLE
Heroic tries to create a save directory on root when launching Anno 1404 after updating from 2.4.3

### ISSUE THREAD

**Issue by Colseph** [Heroic-Games-Launcher/HeroicGamesLauncher#2169]
### Describe the bug

When opening Anno 1404 after updating Heroic to 2.5.0 or 2.5.1, it tries to create the save directory on root.

I've never done much more than scripting, so I may be wrong, ~~but I think the issue is a missing `%` here: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/06e70fca29a6bfc65be88ea1a64412183db56391/src/backend/save_sync.ts#L146 introduced in 9b29065d7fa771e766db5af0efa20a21d07e3d24~~

### Add logs

```text
(22:01:05) INFO:    [Backend]:          Launching Anno 1404: Gold Edition (1440426004)

(22:01:05) WARNING: [Backend]:          You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games

(22:01:05) DEBUG:   [Backend]:          Running Wine command: run wineboot --init

(22:01:07) INFO:    [Backend]:          Created/Updated Wineprefix at /home/xu_ai/games/heroic/prefixes/Anno 1404 Gold Edition

(22:01:07) WARNING: [Gog]:              Running setup instructions, if you notice issues with launching a game, please report it on our Discord server

(22:01:08) ERROR:   [Gog]:              Setup: Looks like you have found new setup instruction, please report it on our Discord or GitHub appName: 1440426004, action: savePath

(22:01:08) ERROR:   [Gog]:              Setup: Looks like you have found new setup instruction, please report it on our Discord or GitHub appName: 1440426004, action: savePath

(22:01:08) ERROR:   [Gog]:              Setup: Looks like you have found new setup instruction, please report it on our Discord or GitHub appName: 1440426004, action: savePath

(22:01:08) ERROR:   [Gog]:              Setup: Looks like you have found new setup instruction, please report it on our Discord or GitHub appName: 1440426004, action: savePath

(22:01:08) ERROR:   [Gog]:              Setup: Looks like you have found new setup instruction, please report it on our Discord or GitHub appName: 1440426004, action: savePath

(22:01:08) ERROR:   [Gog]:              Setup: Looks like you have found new setup instruction, please report it on our Discord or GitHub appName: 1440426004, action: savePath

(22:01:08) ERROR:   [Gog]:              Setup: Looks like you have found new setup instruction, please report it on our Discord or GitHub appName: 1440426004, action: savePath

(22:01:08) ERROR:   [Gog]:              Setup: Looks like you have found new setup instruction, please report it on our Discord or GitHub appName: 1440426004, action: savePath

(22:01:08) ERROR:   [Gog]:              Setup: Looks like you have found new setup instruction, please report it on our Discord or GitHub appName: 1440426004, action: savePath

(22:01:08) INFO:    [Gog]:              Setup: Creating directory /Ubisoft/Anno1404/Config

(22:01:08) ERROR:   [Backend]:          Error: EACCES: permission denied, mkdir '/Ubisoft/Anno1404/Config'

    at Object.mkdirSync (node:fs:1349:3)

    at setup (/opt/heroic/resources/app.asar/build/electron/main.d61a4184.js:6:3350)

    at async prepareWineLaunch (/opt/heroic/resources/app.asar/build/electron/main.d61a4184.js:7:1234)

    at async W.launch (/opt/heroic/resources/app.asar/build/electron/main.d61a4184.js:32:6383)

    at async /opt/heroic/resources/app.asar/build/electron/main.d61a4184.js:119:12

    at async node:electron/js2c/browser_init:193:551
```

### Steps to reproduce

1. Launch Anno 1404
2. Nothing happens
3. Open logs

### Expected behavior

The game should launch fine as nothing has changed aside from updating Heroic

### System Information

- OS [e. g. "Ubuntu"]: Arch Linux
- Heroic Version [e. g. 2.1.1]: 2.5.1

**Comment by Colseph** [comment]
after digging in some, it seems like the work needed to fix is _a lot_ more that I thought.

again I may be totally off, but it looks like the real fix is adding a proper `userappdata` Map to `pathsValues` in [/src/backend/gog/setup.ts](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/8795a06c24098c4199df81d1cc373290a344ca39/src/backend/gog/setup.ts).

The issue there is I'm not sure of any way to reliably get the wine prefix user's appdata path. Generally we should be able to say if wine version type is  proton, then its under 'steamuser' otherwise the system username is used. Even then there could be instances where this isnt the case, so it wouldn't be a perfect solution.

I've not seen or heard of any instances of this issue other than mine, but if for those that do run into it- launching the game manually from the terminal works fine, or if you've got root access you can create the required folder manually and continue to launch from Heroic.

I apologize probably wont be of much more help, I appreciate all the time you give to this project.

**Comment by imLinguin** [comment]
Could you share the goggame-SOMEID.script file you can find in game directory?

**Comment by Colseph** [comment]
of course
`goggame-1440426004.script`:
```
{
    "actions": [
        {
            "install": {
                "action": "savePath",
                "arguments": {
                    "savePath": "{userdocs}/Anno 1404",
                    "type": "folder"
                }
            },
            "languages": [
                "*"
            ],
            "name": "saveFolders"
        },
        {
            "install": {
                "action": "savePath",
                "arguments": {
                    "savePath": "{userdocs}/ANNO 1404 Venice",
                    "type": "folder"
                }
            },
            "languages": [
                "*"
            ],
            "name": "saveFolders2"
        },
        {
            "install": {
                "action": "savePath",
                "arguments": {
                    "savePath": "{userdocs}/ANNO 1404 Venecia",
                    "type": "folder"
                }
            },
            "languages": [
                "*"
            ],
            "name": "saveFolders2ES"
        },
        {
            "install": {
                "action": "savePath",
                "arguments": {
                    "savePath": "{userdocs}/ANNO 1404 Venise",
                    "type": "folder"
                }
            },
            "languages": [
                "*"
            ],
            "name": "saveFolders2FR"
        },
        {
            "install": {
                "action": "savePath",
                "arguments": {
                    "savePath": "{userdocs}/ANNO 1404 Venedig",
                    "type": "folder"
                }
            },
            "languages": [
                "*"
            ],
            "name": "saveFolders2DE"
        },
        {
            "install": {
                "action": "savePath",
                "arguments": {
                    "savePath": "{userdocs}/ANNO 1404 Venezia",
                    "type": "folder"
                }
            },
            "languages": [
                "*"
            ],
            "name": "saveFolders2IT"
        },
        {
            "install": {
                "action": "savePath",
                "arguments": {
                    "savePath": "{userdocs}/ANNO 1404 Wenecja",
                    "type": "folder"
                }
            },
            "languages": [
                "*"
            ],
            "name": "saveFolders2PL"
        },
        {
            "install": {
                "action": "savePath",
                "arguments": {
                    "savePath": "{userappdata}/Ubisoft/Anno1404",
                    "type": "folder"
                }
            },
            "languages": [
                "*"
            ],
            "name": "saveFolders3"
        },
        {
            "install": {
                "action": "savePath",
                "arguments": {
                    "savePath": "{userappdata}/Ubisoft/Anno1404Addon",
                    "type": "folder"
                }
            },
            "languages": [
                "*"
            ],
            "name": "saveFolders4"
        },
        {
            "install": {
                "action": "supportData",
                "arguments": {
                    "target": "{userappdata}/Ubisoft/Anno1404/Config",
                    "type": "folder"
                }
            },
            "languages": [
                "*"
            ],
            "name": "createFolder1"
        },
        {
            "install": {
                "action": "supportData",
                "arguments": {
                    "target": "{userappdata}/Ubisoft/Anno1404Addon/Config",
                    "type": "folder"
                }
            },
            "languages": [
                "*"
            ],
            "name": "createFolder2"
        },
        {
            "install": {
                "action": "supportData",
                "arguments": {
                    "overwrite": false,
                    "saveGameData": true,
                    "source": "{supportDir}/add/Engine.ini",
                    "target": "{userappdata}/Ubisoft/Anno1404/Config/Engine.ini",
                    "type": "file"
                }
            },
            "languages": [
                "*"
            ],
            "name": "copyConfig1"
        },
        {
            "install": {
                "action": "supportData",
                "arguments": {
                    "overwrite": false,
                    "saveGameData": true,
                    "source": "{supportDir}/add/Engine.ini",
                    "target": "{userappdata}/Ubisoft/Anno1404Addon/Config/Engine.ini",
                    "type": "file"
                }
            },
            "languages": [
                "*"
            ],
            "name": "copyConfig2"
        },
        {
            "install": {
                "action": "Execute",
                "arguments": {
                    "argument": "eng",
                    "conditions": [
                        "onLanguageChange"
                    ],
                    "executable": "{app}/tools/anno1404_lang_switch.exe",
                    "runAsAdmin": true,
                    "workingDir": "{app}/tools"
                }
            },
            "languages": [
                "en-US"
            ],
            "name": "swap_lang"
        }
    ],
    "productId": "1440426004"
}
```

**Comment by deeply-cynical** [comment]
Same happens when Launching the GOG version of Venetica in 2.5.2. 
It tries to `mkdir /Venetica` and gets a permission error,

Error message is identical to the OP. 
I even tried to change the {userdocs} string to $HOME in the goggame.script. (Don't laugh, I'm a Linux noob with no programming skills)

**Comment by imLinguin** [comment]
This is fixed on main and will be available in next release

**Comment by Colseph** [comment]
I've tested Anno 1404 and another game that had the issue(daggerfall unity) for good measure.
I can confirm the setup/launch of both worked perfectly, so I think this issue can be closed.

Thanks loads.
