### ISSUE TITLE
“Cannot Get Game Info” Again

### ISSUE THREAD

**Issue by Marevilioso** [Heroic-Games-Launcher/HeroicGamesLauncher#2197]
### Describe the bug

Just yesterday I was playing rocket league (only game I play rn) and when I open the game menu or try to click play, heroic pops up “cannot get game info”. I have downloaded all of the latest updates and such, but this issue has resurfaced for me. Can anyone help?

### Add logs

```text
(13:17:54) INFO:    [Connection]:       Pinging external endpoints
(13:17:54) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(13:17:55) INFO:    [Legendary]:        Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(13:17:55) INFO:    [Gog]:              GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(13:17:55) WARNING: [Backend]:          Protocol already registered.
(13:17:56) INFO:    [Connection]:       Connectivity: online
(13:17:58) INFO:    [Gog]:              Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --version
(13:17:59) INFO:    [Backend]:          Checking for new Heroic Updates
(13:17:59) INFO:    [Frontend]:         Refreshing Library
(13:17:59) INFO:    [Legendary]:        Refreshing library...
(13:17:59) INFO:    [Legendary]:        Refreshing Epic Games...
(13:17:59) INFO:    [Legendary]:        Game list updated, got 2 games & DLCs
(13:17:59) INFO:    [Backend]:          Frontend Ready
(13:17:59) INFO:    [Backend]:          Checking for current version changelog
(13:18:00) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
(13:18:01) INFO:    [Backend]:          

Heroic Version: 2.5.2 Yamato
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: macOS Big Sur 11.6.8 KERNEL: 20.6.0 ARCH: x64
CPU: Apple M1 @2.4 
RAM: Total: 8 GiB Available: 4.94 GiB
GRAPHICS: GPU0: Apple M1   


(13:18:04) INFO:    [Backend]:          Starting the Download Queue
(13:18:59) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary eos-overlay info
(13:18:59) INFO:    [Backend]:          Using cached HowLongToBeat data for Rocket League 
(13:18:59) INFO:    [Legendary]:        Getting more details with 'legendary info'
(13:18:59) INFO:    [Legendary]:        Getting more details with 'legendary info'
(13:18:59) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info Sugar --platform linux --json
(13:18:59) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info Sugar --platform linux --json
(13:19:00) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(13:19:00) INFO:    [Backend]:          Preventing display from sleep
(13:19:00) INFO:    [Legendary]:        Getting more details with 'legendary info'
(13:19:00) INFO:    [Legendary]:        Getting more details with 'legendary info'
(13:19:00) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info Sugar --platform linux --json
(13:19:00) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary launch Sugar --json --offline
(13:19:00) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info Sugar --platform linux --json
(13:19:09) ERROR:   [Legendary]:        Error: Failed to parse install info for Sugar with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(13:19:09) ERROR:   [Frontend]:         Cannot get game info
(13:19:09) ERROR:   [Frontend]:         Cannot get game info
(13:19:10) ERROR:   [Legendary]:        Error: Failed to parse install info for Sugar with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(13:19:10) ERROR:   [Frontend]:         Cannot get game info
(13:19:10) ERROR:   [Frontend]:         Cannot get game info
(13:19:11) ERROR:   [Legendary]:        Error: Failed to parse install info for Sugar with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(13:19:11) ERROR:   [Frontend]:         Cannot get game info
(13:19:11) ERROR:   [Frontend]:         Cannot get game info
(13:19:11) INFO:    [Legendary]:        Launching Rocket League®: LD_PRELOAD= CX_BOTTLE=Heroic DXVK_HUD=fps /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary launch Sugar --language en --wine /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wine
(13:19:11) ERROR:   [Legendary]:        Error: Failed to parse install info for Sugar with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(13:19:11) ERROR:   [Frontend]:         Cannot get game info
(13:19:11) ERROR:   [Frontend]:         Cannot get game info
(13:19:15) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(13:19:15) INFO:    [Frontend]:         Refreshing Library
(13:19:15) INFO:    [Legendary]:        Refreshing library...
(13:19:15) INFO:    [Legendary]:        Game list updated, got 2 games & DLCs
```

### Steps to reproduce

1. Go to 'Library'
2. Click on 'Rocket League'
3. OPTIONAL: click ‘play now’

### Expected behavior

I expected it to launch the game, but it can’t and refuses to do so. 

### System Information

- OS [e. g. "Big Sur", version 11.6.8]: 
- Heroic Version [e. g. 2.5.2]:

**Comment by flavioislima** [comment]
can you try to go to Advanced > Settings > Clear cache.
If doesn't work maybe try RESET HEROIC on the same page.

**Comment by Marevilioso** [comment]
Yes I updated heroic, then cleared cache, didn’t work. Then I reset heroic, also didn’t work. Then I deleted heroic and downloaded heroic again. Also didn’t work 🤣😞

**Comment by flavioislima** [comment]
You have also logged out and in again on epic games?

**Comment by Marevilioso** [comment]
Actually no, I have not tried that. Let me try that I guess…

**Comment by Marevilioso** [comment]
> You have also logged out and in again on epic games?

OMFG that actually worked! Thank you for that. I didn’t think that would be the problem. 😎❤️🔥

**Comment by Marevilioso** [comment]
Issue resolved 😎

**Comment by FrancoisSchnell** [comment]
> You have also logged out and in again on epic games?

When I realize The IT Crowd IS the master class of comptuer sciences.

I just logged off Epic games website and it solved the "Cannot get game info" on Heroic. Thanks!

**Comment by natefabian18** [comment]
Had a similar issue that resetting the clearing didn't fix. Noticed that it was only epic games giving the error. Went to epics site and it asked for my age then re-logged me in and everything seems to work again. Figured I would leave a crumb for the next person.

**Comment by bb115** [comment]
> You have also logged out and in again on epic games?

this worked for me thanks

**Comment by MarcoCuel** [comment]
I have the same problem, I'm trying to download Dead Island 2, I can download other games normally except Dead Island 2, I've already cleared cache, restarted, reset and relogged again in Epic using the normal method and the alternative method, but the error remains.
