### ISSUE TITLE
Epic "Cannot get game info"

### ISSUE THREAD

**Issue by jonathan-gomes** [Heroic-Games-Launcher/HeroicGamesLauncher#2273]
### Describe the bug

I've been trying to download any game from my Epic Games account and I get the error `Cannot get game info`.
I'm using the Heroic Launcher on a SteamOS installation on SteamDeck

I suspect there's something wrong with the Epic certificates, as in they are not accepted by the system.
Example: the Epic Launcher installer URL was not accessible through Chrome until I used Firefox to download and install the host certificate:
![image](https://user-images.githubusercontent.com/10462756/209706011-9d9e02a7-ae20-403e-bd54-5929916d8b93.png)

### Add logs

```text
(13:09:42) INFO:    [Connection]:       Connectivity: check-online
(13:09:42) INFO:    [Connection]:       Pinging external endpoints
(13:09:42) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(13:09:42) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(13:09:42) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(13:09:42) WARNING: [Backend]:          Failed to register protocol with OS.
(13:09:42) INFO:    [Connection]:       Connectivity: online
(13:09:42) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(13:09:42) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(13:09:43) INFO:    [Backend]:          

Heroic Version: 2.5.2 Yamato
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: Freedesktop SDK KERNEL: 5.13.0-valve36-1-neptune ARCH: x64
CPU: AMD Custom APU 0405 @2.94 GOVERNOR: performance
RAM: Total: 11.52 GiB Available: 7.36 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB  
PROTOCOL: x11

(13:09:43) INFO:    [Backend]:          Checking for current version changelog
(13:09:43) INFO:    [Frontend]:         Refreshing Library
(13:09:43) INFO:    [Legendary]:        Refreshing library...
(13:09:43) INFO:    [Legendary]:        Refreshing Epic Games...
(13:09:43) INFO:    [Legendary]:        Game list updated, got 25 games & DLCs
(13:09:43) INFO:    [Backend]:          Frontend Ready
(13:09:44) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(13:09:44) INFO:    [Winetricks]:       Downloading Winetricks
(13:09:44) INFO:    [Backend]:          Using cached HowLongToBeat data for Assassins Creed Syndicate 
(13:09:44) INFO:    [Legendary]:        Getting more details with 'legendary info'
(13:09:44) INFO:    [Legendary]:        Getting more details with 'legendary info'
(13:09:45) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Albacore --platform Windows --json
(13:09:45) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Albacore --platform Windows --json
(13:09:47) INFO:    [Legendary]:        Getting more details with 'legendary info'
(13:09:47) DEBUG:   [Backend]:          {"free":359926517760,"diskSize":503312080896,"message":"335.21 GiB / 468.75 GiB","validPath":true}
(13:09:47) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Albacore --platform Windows --json
(13:09:48) INFO:    [Backend]:          Starting the Download Queue
(13:09:48) ERROR:   [Legendary]:        Error: Failed to parse install info for Albacore with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(13:09:48) ERROR:   [Frontend]:         Cannot get game info
(13:09:48) ERROR:   [Frontend]:         Cannot get game info
(13:09:48) ERROR:   [Legendary]:        Error: Failed to parse install info for Albacore with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(13:09:48) ERROR:   [Frontend]:         Cannot get game info
(13:09:48) ERROR:   [Frontend]:         Cannot get game info
(13:09:50) ERROR:   [Legendary]:        Error: Failed to parse install info for Albacore with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(13:10:25) INFO:    [Backend]:          Checking for current version changelog
(14:13:38) INFO:    [Legendary]:        Getting more details with 'legendary info'
(14:13:38) DEBUG:   [Backend]:          {"free":359749664768,"diskSize":503312080896,"message":"335.04 GiB / 468.75 GiB","validPath":true}
(14:13:39) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json
(14:13:43) ERROR:   [Legendary]:        Error: Failed to parse install info for Godwit with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(14:16:22) INFO:    [Backend]:          Getting HowLongToBeat data for Batman Arkham Asylum Game of the Year Edition
(14:16:22) INFO:    [Legendary]:        Getting more details with 'legendary info'
(14:16:22) INFO:    [Legendary]:        Getting more details with 'legendary info'
(14:16:23) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json
(14:16:23) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json
(14:16:23) INFO:    [Legendary]:        Getting more details with 'legendary info'
(14:16:23) DEBUG:   [Backend]:          {"free":359749599232,"diskSize":503312080896,"message":"335.04 GiB / 468.75 GiB","validPath":true}
(14:16:24) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json
(14:16:26) ERROR:   [Legendary]:        Error: Failed to parse install info for Godwit with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(14:16:26) ERROR:   [Frontend]:         Cannot get game info
(14:16:26) ERROR:   [Frontend]:         Cannot get game info
(14:16:26) ERROR:   [Legendary]:        Error: Failed to parse install info for Godwit with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(14:16:26) ERROR:   [Frontend]:         Cannot get game info
(14:16:26) ERROR:   [Frontend]:         Cannot get game info
(14:16:26) ERROR:   [Legendary]:        Error: Failed to parse install info for Godwit with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(14:23:04) INFO:    [Backend]:          Getting HowLongToBeat data for Batman Arkham Asylum Game of the Year Edition
(14:23:04) INFO:    [Legendary]:        Getting more details with 'legendary info'
(14:23:04) INFO:    [Legendary]:        Getting more details with 'legendary info'
(14:23:04) INFO:    [Legendary]:        Getting more details with 'legendary info'
(14:23:04) DEBUG:   [Backend]:          {"free":359748792320,"diskSize":503312080896,"message":"335.04 GiB / 468.75 GiB","validPath":true}
(14:23:05) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json
(14:23:05) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json
(14:23:05) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json
(14:23:08) ERROR:   [Legendary]:        Error: Failed to parse install info for Godwit with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(14:23:08) ERROR:   [Legendary]:        Error: Failed to parse install info for Godwit with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(14:23:08) ERROR:   [Frontend]:         Cannot get game info
(14:23:08) ERROR:   [Frontend]:         Cannot get game info
(14:23:08) ERROR:   [Frontend]:         Cannot get game info
(14:23:08) ERROR:   [Legendary]:        Error: Failed to parse install info for Godwit with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(14:58:52) INFO:    [Legendary]:        Getting more details with 'legendary info'
(14:58:52) DEBUG:   [Backend]:          {"free":359641886720,"diskSize":503312080896,"message":"334.94 GiB / 468.75 GiB","validPath":true}
(14:58:53) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json
(14:58:56) INFO:    [Backend]:          Getting HowLongToBeat data for Batman Arkham Asylum Game of the Year Edition
(14:58:56) INFO:    [Legendary]:        Getting more details with 'legendary info'
(14:58:56) INFO:    [Legendary]:        Getting more details with 'legendary info'
(14:58:56) INFO:    [Legendary]:        Getting more details with 'legendary info'
(14:58:56) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json
(14:58:57) DEBUG:   [Backend]:          {"free":359641886720,"diskSize":503312080896,"message":"334.94 GiB / 468.75 GiB","validPath":true}
(14:58:57) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json
(14:58:57) ERROR:   [Legendary]:        Error: Failed to parse install info for Godwit with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(14:58:57) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json
(14:58:59) ERROR:   [Legendary]:        Error: Failed to parse install info for Godwit with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(14:58:59) ERROR:   [Legendary]:        Error: Failed to parse install info for Godwit with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
(14:58:59) ERROR:   [Frontend]:         Cannot get game info
(14:58:59) ERROR:   [Frontend]:         Cannot get game info
(14:58:59) ERROR:   [Frontend]:         Cannot get game info
(14:59:00) ERROR:   [Legendary]:        Error: Failed to parse install info for Godwit with: SyntaxError: Unexpected end of JSON input
    at R.getInstallInfo (/app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:57:8862)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f5946442.js:134:6572
    at async node:electron/js2c/browser_init:193:551
```

### Steps to reproduce

1. With Epic account connected, go to 'library'
2. Click on install on any game
3. See error

### Expected behavior

Being able to install a game from Epic

### Screenshots

![image](https://user-images.githubusercontent.com/10462756/209706314-e5782ac0-4003-4377-8df2-29cb4cfc1307.png)
![image](https://user-images.githubusercontent.com/10462756/209706011-9d9e02a7-ae20-403e-bd54-5929916d8b93.png)

### Heroic Version

Latest Stable

### System Information

- OS:  SteamOS

**Comment by arielj** [comment]
Run this manually in the console `/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json`, you'll have a better error message

**Comment by jonathan-gomes** [comment]
> Run this manually in the console `/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json`, you'll have a better error message

I think heroic is not installed in this path?

```
(deck@steamdeck ~)$ /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json
bash: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary: No such file or directory
```

**Comment by jonathan-gomes** [comment]
> Run this manually in the console `/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json`, you'll have a better error message

Ok, I think I found the path to the resource: `/var/lib/flatpak/app/com.heroicgameslauncher.hgl/x86_64/stable/53c7cc3bc9cfec16e6d6d75fa65ae40fab99a399d2cc89b0282866cd6ccfd03f/files/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary`

```
(deck@steamdeck ~)$ /var/lib/flatpak/app/com.heroicgameslauncher.hgl/x86_64/stable/53c7cc3bc9cfec16e6d6d75fa65ae40fab99a399d2cc89b0282866cd6ccfd03f/files/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Godwit --platform Windows --json
{"game": null, "install": null, "manifest": null}
```
Not very helpful output

**Comment by flavioislima** [comment]
@jonathan-gomes I just had this issue, logging out and in again with my epic accounts solved the issue. Can you try it as well?

**Comment by jonathan-gomes** [comment]
> @jonathan-gomes I just had this issue, logging out and in again with my epic accounts solved the issue. Can you try it as well?

Thanks for the reply. I've tried all the resets and logging out and in again. I'm aware there's people who had the "cannot get game info" and sort it out by logging out and in again, but I don't think it's the same issue as mine. I can't use Lutris to download any game as well, I think it's something to do with the epic certificates not being accepted on my steam os installation for some reason

**Comment by arielj** [comment]
hey @jonathan-gomes , can you confirm if this is still an issue in Heroic 2.6.2?

**Comment by TornadoRadon** [comment]
> hey @jonathan-gomes , can you confirm if this is still an issue in Heroic 2.6.2?

Yes, it's still there.

**Comment by arielj** [comment]
Is this still happening with Heroic 2.10.0?

**Comment by arielj** [comment]
Closing this since there's no answer since november. We can reopen if it happens again.
