### ISSUE TITLE
Can't launch games or edit settings when not connected any network.

### ISSUE THREAD

**Issue by CronyAkatsuki** [Heroic-Games-Launcher/HeroicGamesLauncher#229]
Since I use a laptop I'm without any internet connection most of the time. About a week ago I opened Heroic without any internet connection and tried to start a singleplayer game. I would see the gamemode start notification, but not even a second after it says gamemode ended. I also recently found out that I also can't open settings without any connection, it just loads forever.

To reproduce this disconnect from any network, launch Heroic and try to run any singleplayer game, or try to open game settings.

I only expect to be able to launch my game without any connection to play something or edit game settings while I can't watch youtube.

Instead of screenshots I will add a couple of logs.

**Alan Wake's American Nightmare**

`[cli] INFO: Logging in...
[Core] INFO: Logging in...
Traceback (most recent call last):
  File "urllib3/connection.py", line 156, in _new_conn
  File "urllib3/util/connection.py", line 61, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 665, in urlopen
  File "urllib3/connectionpool.py", line 376, in _make_request
  File "urllib3/connectionpool.py", line 994, in _validate_conn
  File "urllib3/connection.py", line 300, in connect
  File "urllib3/connection.py", line 168, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f4fa2279c10>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 719, in urlopen
  File "urllib3/util/retry.py", line 436, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='account-public-service-prod03.ol.epicgames.com', port=443): Max retries exceeded with url: /account/api/oauth/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4fa2279c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "legendary/cli.py", line 1375, in <module>
  File "legendary/cli.py", line 1341, in main
  File "legendary/cli.py", line 457, in launch_game
  File "legendary/core.py", line 177, in login
  File "legendary/api/egs.py", line 67, in start_session
  File "requests/sessions.py", line 578, in post
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='account-public-service-prod03.ol.epicgames.com', port=443): Max retries exceeded with url: /account/api/oauth/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4fa2279c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[9533] Failed to execute script cli
`

**Bad North Jotunn Edition**

`[cli] INFO: Logging in...
[Core] INFO: Logging in...
Traceback (most recent call last):
  File "urllib3/connection.py", line 156, in _new_conn
  File "urllib3/util/connection.py", line 61, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 665, in urlopen
  File "urllib3/connectionpool.py", line 376, in _make_request
  File "urllib3/connectionpool.py", line 994, in _validate_conn
  File "urllib3/connection.py", line 300, in connect
  File "urllib3/connection.py", line 168, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f25b0d2bc10>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 719, in urlopen
  File "urllib3/util/retry.py", line 436, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='account-public-service-prod03.ol.epicgames.com', port=443): Max retries exceeded with url: /account/api/oauth/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f25b0d2bc10>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "legendary/cli.py", line 1375, in <module>
  File "legendary/cli.py", line 1341, in main
  File "legendary/cli.py", line 457, in launch_game
  File "legendary/core.py", line 177, in login
  File "legendary/api/egs.py", line 67, in start_session
  File "requests/sessions.py", line 578, in post
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='account-public-service-prod03.ol.epicgames.com', port=443): Max retries exceeded with url: /account/api/oauth/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f25b0d2bc10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[9578] Failed to execute script cli
`

**Desktop (please complete the following information):**
 - OS: Manjaro testing branch
 - Version: Testing branch
-  Game: All games
-  Wine/Proton version: Proton-ge and proton experimental

From what I can see from the logs and my knowledge of legendary, you can you --offline flag to bypass this issue when running offiline. For the options menu I really don't know.

**Comment by flavioislima** [comment]
Hi!

Looking at the logs, it looks like a legendary issue.
I tried running a game using o my legendary, without heroic, and it shows the same error message. 

Unfortunately this is something that we cannot do anything about. 

Maybe opening a ticket on the legendary repo maybe they have a better idea about it.

**Comment by CronyAkatsuki** [comment]
I said at the end of the report that you can use the --offline tag at the end of the command and you can run the games offline. The only thing that needs to be done here is add support for the enable of the --offline option. For example:

`legendary launch Chives`

shows the error while offline, but

`legendary launch Chives --offline`

launches the game just fine. This is the reason why I opened this issue so that it doesn't seem like a issue with legendary, but just not knowing of the option. I just wanted to show you the command so that later on it doesn't become a problem.

**Comment by flavioislima** [comment]
You're right I totally forgot this option. 🤦🏽 
Anyway. There is an option on heroic to add game arguments. Those arguments go just after the launch command. Can you try it?

But I'm checking the other things like the settings page that you said is not working offline.

**Comment by CronyAkatsuki** [comment]
Sure I can check it right away.

**Comment by CronyAkatsuki** [comment]
Yes adding the --offline in the game arguments allows games to be run offline.

**Comment by flavioislima** [comment]
> Yes adding the --offline in the game arguments allows games to be run offline.

Nice. But then now we'll just need to handle the requests. 👍🏽

**Comment by adityaruplaha** [comment]
Working on a fix, should be relatively simple.

**Comment by CronyAkatsuki** [comment]
That is great to hear.
