### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '{UserDir}'

### ISSUE THREAD

**Issue by marmalodak** [Heroic-Games-Launcher/HeroicGamesLauncher#2320]
### Describe the bug

Launching Borderlands 3 or Tiny Tina's Wonderlands stops during syncing with error messages.

### Add logs

```text
(22:02:26) INFO:    [Connection]:       Connectivity: check-online
(22:02:26) INFO:    [Connection]:       Pinging external endpoints
(22:02:26) INFO:    [Legendary]:        Running command: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary --version
(22:02:26) INFO:    [Legendary]:        Legendary location: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary
(22:02:26) INFO:    [Gog]:              GOGDL location: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/gogdl
(22:02:27) WARNING: [Backend]:          Protocol already registered.
(22:02:27) INFO:    [Gog]:              Running command: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(22:02:27) INFO:    [Connection]:       Connectivity: online
(22:02:27) INFO:    [Backend]:          User Not Found, removing it from Store
(22:02:27) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(22:02:27) INFO:    [Backend]:          

Heroic Version: 2.5.2 Yamato
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: Fedora Linux KERNEL: 6.0.15-200.fc36.x86_64 ARCH: x64
CPU: Intel Gen Intel® Core™ i7-12700K @3.35 GOVERNOR: performance
RAM: Total: 62.56 GiB Available: 58.4 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 3060 Ti VRAM: 8192MB DRIVER: 525.60.11 
PROTOCOL: x11

(22:02:27) INFO:    [Backend]:          Checking for new Heroic Updates
(22:02:27) INFO:    [Backend]:          Frontend Ready
(22:02:27) INFO:    [Backend]:          Checking for current version changelog
(22:02:27) INFO:    [Frontend]:         Updated to a new version, cleaaning up the cache.
(22:02:27) INFO:    [Legendary]:        Running command: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary cleanup
(22:02:29) INFO:    [Winetricks]:       Downloading Winetricks
(22:02:29) WARNING: [Winetricks]:       Error Downloading Winetricks Error: ENOENT: no such file or directory, open '/home/john/.config/heroic/tools/winetricks'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
    at Object.writeFileSync (node:fs:2170:35)
    at Object.download (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.f5946442.js:5:2425)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(22:02:29) INFO:    [DXVKInstaller]:    Updating dxvk to: dxvk-2.0
(22:02:29) INFO:    [DXVKInstaller]:    Updating vkd3d to: vkd3d-proton-2.7
(22:02:30) WARNING: [DXVKInstaller]:    Error when downloading dxvk Error: Command failed: curl -L https://github.com/doitsujin/dxvk/releases/download/v2.0/dxvk-2.0.tar.gz -o '/home/john/.config/heroic/tools/dxvk/dxvk-2.0.tar.gz' --create-dirs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (6) Could not resolve host: objects.githubusercontent.com

    at ChildProcess.exithandler (node:child_process:407:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
(22:02:30) WARNING: [DXVKInstaller]:    Error when downloading vkd3d Error: Command failed: curl -L https://github.com/bottlesdevs/vkd3d-proton/releases/download/vkd3d-proton-2.7/vkd3d-proton-2.7.tar.xz -o '/home/john/.config/heroic/tools/vkd3d/vkd3d-proton-2.7.tar.xz' --create-dirs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (6) Could not resolve host: objects.githubusercontent.com

    at ChildProcess.exithandler (node:child_process:407:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
(22:02:32) INFO:    [Backend]:          Starting the Download Queue
(22:06:07) INFO:    [Legendary]:        Logging in: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(22:06:08) INFO:    [Frontend]:         Refreshing Library
(22:06:08) INFO:    [Legendary]:        Refreshing library...
(22:06:08) INFO:    [Legendary]:        Refreshing Epic Games...
(22:06:08) INFO:    [Legendary]:        Game list updated, got 0 games & DLCs
(22:06:08) INFO:    [Frontend]:         No cache found, getting data from legendary...
(22:06:08) INFO:    [Legendary]:        Refreshing library...
(22:06:08) INFO:    [Legendary]:        Game list updated, got 0 games & DLCs
(22:06:08) INFO:    [Legendary]:        Running command: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party

...

(07:04:49) INFO:    [Backend]:          Adding shortcuts for Tiny Tina's Wonderlands
(07:07:14) INFO:    [DownloadManager]:  Finished installing of eb6ddfb245f647e2bb6902f52f38a535
(07:07:14) INFO:    [DownloadManager]:  eb6ddfb245f647e2bb6902f52f38a535 added to download manager finished.
(07:07:14) INFO:    [DownloadManager]:  eb6ddfb245f647e2bb6902f52f38a535 removed from download manager.
(07:07:14) INFO:    [Frontend]:         Refreshing Library
(07:07:14) INFO:    [Legendary]:        Refreshing library...
(07:07:14) INFO:    [Legendary]:        Game list updated, got 142 games & DLCs
(15:04:05) INFO:    [Backend]:          Launching Tiny Tina's Wonderlands (eb6ddfb245f647e2bb6902f52f38a535)
(15:04:05) INFO:    [Backend]:          Preventing display from sleep
(15:04:05) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-7.22 (Staging)!
Missing undefined and/or undefined!
Falling back to system libraries!
(15:04:05) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(15:04:41) INFO:    [Backend]:          Created/Updated Wineprefix at /home/john/Games/Heroic/Prefixes/Tiny Tinas Wonderlands
(15:04:41) WARNING: [DXVKInstaller]:    dxvk not found!
(15:04:41) ERROR:   [Backend]:          Error: ENOENT: no such file or directory, open '/home/john/.config/heroic/tools/dxvk/latest_dxvk'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
    at Object.readFileSync (node:fs:453:35)
    at e.readFileSync (node:electron/js2c/asar_bundle:5:9156)
    at Object.installRemove (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.f5946442.js:3:1520)
    at async prepareWineLaunch (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.f5946442.js:7:1307)
    at async N.launch (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.f5946442.js:57:23267)
    at async /usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.f5946442.js:141:12
    at async node:electron/js2c/browser_init:193:551
(15:04:41) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(15:04:41) INFO:    [DXVKInstaller]:    Updating vkd3d to: vkd3d-proton-2.7
(15:04:41) INFO:    [DXVKInstaller]:    Updating dxvk to: dxvk-2.0
(15:04:43) INFO:    [DXVKInstaller]:    downloaded vkd3d
(15:04:43) INFO:    [DXVKInstaller]:    extracting vkd3d
(15:04:43) INFO:    [DXVKInstaller]:    vkd3d updated!
(15:04:44) INFO:    [DXVKInstaller]:    downloaded dxvk
(15:04:44) INFO:    [DXVKInstaller]:    extracting dxvk
(15:04:44) INFO:    [DXVKInstaller]:    dxvk updated!
(15:05:20) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-7.22 (Staging)!
Missing undefined and/or undefined!
Falling back to system libraries!
(15:05:20) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(15:05:25) INFO:    [Legendary]:        Computing default save path for eb6ddfb245f647e2bb6902f52f38a535
(15:05:25) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-7.22 (Staging)!
Missing undefined and/or undefined!
Falling back to system libraries!
(15:05:25) INFO:    [Legendary]:        Getting default save path: WINEPREFIX="/home/john/Games/Heroic/Prefixes/Tiny Tinas Wonderlands" ORIG_LD_LIBRARY_PATH= /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary sync-saves eb6ddfb245f647e2bb6902f52f38a535 --skip-upload --skip-download --accept-path
(15:05:26) ERROR:   [Legendary]:        Unable to compute default save path for eb6ddfb245f647e2bb6902f52f38a535
(15:05:26) INFO:    [Backend]:          Writing config for eb6ddfb245f647e2bb6902f52f38a535
(15:05:26) INFO:    [Backend]:          Changed config: savesPath from undefined to {UserDir}/My Games/Tiny Tina's Wonderlands/Saved/SaveGames/{EpicID}/
(15:06:31) INFO:    [Backend]:          Launching Borderlands 3 (Catnip)
(15:06:32) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-7.22 (Staging)!
Missing undefined and/or undefined!
Falling back to system libraries!
(15:06:32) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(15:06:44) INFO:    [Backend]:          Created/Updated Wineprefix at /home/john/Games/Heroic/Prefixes/Borderlands 3
(15:06:44) INFO:    [DXVKInstaller]:    installing dxvk on... /home/john/Games/Heroic/Prefixes/Borderlands 3
(15:06:44) INFO:    [DXVKInstaller]:    installing vkd3d on... /home/john/Games/Heroic/Prefixes/Borderlands 3
(15:06:44) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-7.22 (Staging)!
Missing undefined and/or undefined!
Falling back to system libraries!
(15:06:44) INFO:    [Legendary]:        Running command: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary launch Catnip --json --offline
(15:06:44) INFO:    [Legendary]:        Launching Borderlands 3: LD_PRELOAD= WINEPREFIX="/home/john/Games/Heroic/Prefixes/Borderlands 3" ORIG_LD_LIBRARY_PATH= /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary launch Catnip --language en --wine /usr/bin/wine
(15:06:47) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(15:07:16) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-7.22 (Staging)!
Missing undefined and/or undefined!
Falling back to system libraries!
(15:07:16) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(15:07:21) INFO:    [Legendary]:        Computing default save path for Catnip
(15:07:21) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-7.22 (Staging)!
Missing undefined and/or undefined!
Falling back to system libraries!
(15:07:21) INFO:    [Legendary]:        Getting default save path: WINEPREFIX="/home/john/Games/Heroic/Prefixes/Borderlands 3" ORIG_LD_LIBRARY_PATH= /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary sync-saves Catnip --skip-upload --skip-download --accept-path
(15:07:22) ERROR:   [Legendary]:        Unable to compute default save path for Catnip
(15:07:22) INFO:    [Backend]:          Writing config for Catnip
(15:07:22) INFO:    [Backend]:          Changed config: savesPath from undefined to {UserDir}/My Games/Borderlands 3/Saved/SaveGames/{EpicID}/
(15:07:48) INFO:    [Legendary]:        Syncing saves for Catnip: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary sync-saves --skip-upload --save-path "{UserDir}/My Games/Borderlands 3/Saved/SaveGames/{EpicID}/" Catnip -y
(15:07:52) INFO:    [Backend]:          [Core] INFO: Trying to re-use existing login session...
[cli] INFO: Got 3 remote save game(s)
[cli] INFO: Checking "Borderlands 3" (Catnip)
[cli] INFO: Overriding save path with "{UserDir}/My Games/Borderlands 3/Saved/SaveGames/{EpicID}/"...
[cli] INFO: Cloud save for "Borderlands 3" is newer:
[cli] INFO: - Cloud save date: 2023-01-06 05:05:46
[cli] INFO: - Local save date: N/A
[cli] INFO: Downloading remote savegame...
[Core] INFO: Deleting old save files...
[Core] INFO: Downloading "Catnip/manifests/2023.01.06-05.05.46.manifest"...
Traceback (most recent call last):
  File "legendary/cli.py", line 3061, in <module>
  File "legendary/cli.py", line 2988, in main
  File "legendary/cli.py", line 537, in sync_saves
  File "legendary/core.py", line 1065, in download_saves
  File "os.py", line 215, in makedirs
  File "os.py", line 215, in makedirs
  File "os.py", line 215, in makedirs
  [Previous line repeated 2 more times]
  File "os.py", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '{UserDir}'
[132181] Failed to execute script 'cli' due to unhandled exception!

(15:08:22) INFO:    [Legendary]:        Syncing saves for Catnip: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary sync-saves --skip-upload --save-path "{UserDir}/My Games/Borderlands 3/Saved/SaveGames/{EpicID}/" Catnip -y
(15:08:26) INFO:    [Backend]:          [Core] INFO: Trying to re-use existing login session...
[cli] INFO: Got 3 remote save game(s)
[cli] INFO: Checking "Borderlands 3" (Catnip)
[cli] INFO: Overriding save path with "{UserDir}/My Games/Borderlands 3/Saved/SaveGames/{EpicID}/"...
[cli] INFO: Cloud save for "Borderlands 3" is newer:
[cli] INFO: - Cloud save date: 2023-01-06 05:05:46
[cli] INFO: - Local save date: N/A
[cli] INFO: Downloading remote savegame...
[Core] INFO: Deleting old save files...
[Core] INFO: Downloading "Catnip/manifests/2023.01.06-05.05.46.manifest"...
Traceback (most recent call last):
  File "legendary/cli.py", line 3061, in <module>
  File "legendary/cli.py", line 2988, in main
  File "legendary/cli.py", line 537, in sync_saves
  File "legendary/core.py", line 1065, in download_saves
  File "os.py", line 215, in makedirs
  File "os.py", line 215, in makedirs
  File "os.py", line 215, in makedirs
  [Previous line repeated 2 more times]
  File "os.py", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '{UserDir}'
[132248] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Click on the "Play Now" button
2. Click on the gear icon
3. Under "Game Settings" click on "Save-Sync"
4. The dropdown menu is set to "Download"; click the "SYNC" button
5. A dialog box with an error message occurs.

All the directories are owned be the same user as the user launching heroic.

    ❯ ls -al Documents/My\ Games/Borderlands\ 3/Saved/SaveGames/2203f1fa1c46440e93b86c5a791ed694
    total 0
    drwxr-xr-x. 2 john john  6 Jan  6 15:07 .
    drwxr-xr-x. 3 john john 46 Jan  6 15:07 ..

### Expected behavior

I expected my cloud saves to be downloaded.

### Heroic Version

Latest Stable

### System Information

Fedora 36
heroic-games-launcher-bin-2.5.2-1.fc36.x86_64

### Additional information

Issue #1375 seems similar.

**Comment by asc82** [comment]
I have the same issue and it is very likely due to the error "PermissionError: [Errno 13] Permission denied: '{UserDir}'" from what I understand.
When I set the path manualy and do not use the "{UserDir}", but an absolute path instead, it works.
So it must have to do with the '{UserDir}' and '{AppData}' etc. aliases.

**Comment by flavioislima** [comment]
@marmalodak I think your issue is that your use cannot write on .config folder. Check the permission to it because Heroic, for the logs, cannot even download dxvk, vkd3d, winetricks, anything. So something is wrong on your end.
