### ISSUE TITLE
2.6.2 Still not downloading from GOG

### ISSUE THREAD

**Issue by Texashuman** [Heroic-Games-Launcher/HeroicGamesLauncher#2428]
### Describe the bug

Open the launcher
select a game from Gog
Observe that it doesn't display file size or download size
Click install
Observe that it doesn't install

### Add logs

```text
I got the release and still cannot get my games. (13:29:54) INFO: [Connection]: Connectivity: check-online
(13:29:54) INFO: [Connection]: Pinging external endpoints
(13:29:54) INFO: [Legendary]: Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(13:29:54) INFO: [Legendary]: Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(13:29:54) INFO: [Gog]: GOGDL location: /home/daviwaynedisney/gogdl
(13:29:54) INFO: [Gog]: GOGDL location: /home/daviwaynedisney/gogdl
(13:29:54) WARNING: [Backend]: Protocol already registered.
(13:29:54) INFO: [Gog]: Running command: /home/daviwaynedisney/gogdl --version
(13:29:54) INFO: [Connection]: Connectivity: online
(13:29:54) INFO: [Gog]: Getting data about the user
(13:29:54) INFO: [Backend]:

Heroic Version: 2.6.2 Trafalgar Law
Legendary Version: 0.20.32 Dark Energy (hotfix #6)
GOGdl Version:

Electron Version: 22.2.0
Chrome Version: 108.0.5359.215
NodeJS Version: 16.17.1

OS: Debian GNU/Linux KERNEL: 5.10.153-20434-g98da1eb2cf9d ARCH: x64
CPU: Intel Gen Intel® Core™ i5-1235U @2.5
RAM: Total: 6.35 GiB Available: 5.64 GiB
GRAPHICS:
PROTOCOL:

(13:29:54) INFO: [Backend]: Loading Screen Ready
(13:29:54) INFO: [Frontend]: Refreshing Library
(13:29:54) INFO: [Legendary]: Refreshing library...
(13:29:54) INFO: [Legendary]: Refreshing Epic Games...
(13:29:54) INFO: [Legendary]: Game list updated, got 4 games & DLCs
(13:29:54) INFO: [Gog]: Getting GOG library
(13:29:54) INFO: [Backend]: Frontend Ready
(13:29:54) INFO: [Backend]: Checking for new Heroic Updates
(13:29:54) INFO: [Backend]: Checking for current version changelog
(13:29:55) INFO: [Backend]: AreWeAntiCheatYet data downloaded
(13:29:55) INFO: [Gog]: Saved user data to config
(13:29:55) INFO: [Gog]: Number of library pages: 1
(13:29:55) INFO: [Legendary]: Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(13:29:56) INFO: [Gog]: Saved games data
(13:29:56) INFO: [Legendary]: Checking for game updates: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(13:29:56) INFO: [Winetricks]: Downloading Winetricks
(13:29:57) WARNING: [Legendary]: Failed to parse games from /home/daviwaynedisney/.config/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/home/daviwaynedisney/.config/legendary/installed.json'
at Object.openSync (node:fs:594:3)
at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
at Object.readFileSync (node:fs:462:35)
at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
at R.listUpdateableGames (/opt/Heroic/resources/app.asar/build/electron/main.6ace4a2c.js:56:9290)
at async /opt/Heroic/resources/app.asar/build/electron/main.6ace4a2c.js:184:3970

at async node:electron/js2c/browser_init:2:97553
(13:29:57) INFO: [Legendary]: Found 0 games to update
(13:29:57) INFO: [Gog]: Found 0 game(s) to update
(13:29:59) INFO: [Backend]: Starting the Download Queue
(13:30:01) INFO: [ExtraGameInfo]: Using cached ExtraGameInfo data for Master of Orion 2
(13:30:01) INFO: [Gog]: Getting game metadata: /home/daviwaynedisney/gogdl info 1207661633 --token --lang=en-US --os windows
(13:30:01) INFO: [Gog]: Getting game metadata: /home/daviwaynedisney/gogdl info 1207661633 --token --lang=en-US --os windows
(13:30:01) INFO: [Gog]: Getting game metadata: /home/daviwaynedisney/gogdl info 1207661633 --token --lang=en-US --os windows
(13:30:01) INFO: [Gog]: Getting game metadata: /home/daviwaynedisney/gogdl info 1207661633 --token --lang=en-US --os windows
(13:30:01) WARNING: [Gog]: Failed to get Install Info for 1207661633 using windows as platform, returning empty object
(13:30:01) WARNING: [Gog]: Failed to get Install Info for 1207661633 using windows as platform, returning empty object
(13:30:01) WARNING: [Gog]: Failed to get Install Info for 1207661633 using windows as platform, returning empty object
(13:30:01) WARNING: [Gog]: Failed to get Install Info for 1207661633 using windows as platform, returning empty object
(13:30:06) INFO: [Gog]: Getting game metadata: /home/daviwaynedisney/gogdl info 1207661633 --token --lang=en-US --os windows
(13:30:06) DEBUG: [Backend]: {"free":32585953280,"diskSize":42949672960,"message":"30.35 GiB / 40 GiB","validPath":true}
(13:30:06) WARNING: [Gog]: Failed to get Install Info for 1207661633 using windows as platform, returning empty object
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Open the launch
Go to my library
select a GOG game
See the files and download size
Click install and game installs

### Heroic Version

Latest Stable

### System Information

Electron Version: 22.2.0
Chrome Version: 108.0.5359.215
NodeJS Version: 16.17.1

OS: Debian GNU/Linux KERNEL: 5.10.153-20434-g98da1eb2cf9d ARCH: x64

**Comment by lgcavalheiro** [comment]
For me it doesn't even show my GOG games on the library, also running v2.6.2, it used to show the games and install them some time ago.

**Comment by flavioislima** [comment]
@Texashuman we can see by the logs that you are using an alternative gogdl binary. You need to remove it from the settings.

@lgcavalheiro we would need logs to know what is your problem.

**Comment by Texashuman** [comment]
I got rid of the alternative gogdl binary and the launcher now downloads
games from GOG.
Now I am trying to, deal with GOG, though it may be a DosBox issue
regarding getting the games into full screen.
Thanks to all for the assist on getting Gog to download.

**Comment by flavioislima** [comment]
OK, closing this one since it was solved.

@lgcavalheiro you can open another issue, make sure that you are using a supported distro and add the logs.

**Comment by lgcavalheiro** [comment]
I know this one got closed already, but just a follow-up on my last comment: i managed to get the GOG games working again by disconnecting and then reconnecting my account, but before that axios was raising an error:
``` bash
(21:19:08) ERROR:   [Gog]:              Error getting user Data Error: Request failed with status code 401
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
(21:19:08) ERROR:   [Gog]:              There was an error getting games library data Request failed with status code 401
(21:19:08) ERROR:   [Gog]:              There was an error Loading games library
```
I'll observe my heroic installation for some time to see if this error shows up again, and if so i'll open a new issue.
Unless you guys prefer to have a look at this more closely anyway, then i'll open the issue now anyway, let me know if that is the case! :+1:
