### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'Language')

### ISSUE THREAD

**Issue by matchuek** [Heroic-Games-Launcher/HeroicGamesLauncher#2458]
### Describe the bug

Unable to start GOG Alien Breed 2: Assault, please see attached log.

### Add logs

```text
System Info:
Heroic Version: 2.6.2 Trafalgar Law
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.6

Electron Version: 22.2.0
Chrome Version: 108.0.5359.215
NodeJS Version: 16.17.1

OS: Ubuntu KERNEL: 5.15.0-58-generic ARCH: x64
CPU: Intel Core™ i5-6300U @2.4 GOVERNOR: powersave
RAM: Total: 15.41 GiB Available: 12.66 GiB
GRAPHICS: GPU0: Skylake GT2 [HD Graphics 520]  VRAM: 512MB  
PROTOCOL: x11

Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"preferSystemLibs": false,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"useGameMode": false,
	"language": "",
	"wineVersion": {
		"bin": "/home/matchi/.config/heroic/tools/wine/Wine-7.0-GE-4-LoL/bin/wine",
		"name": "Wine - Wine-7.0-GE-4-LoL",
		"type": "wine",
		"lib": "/home/matchi/.config/heroic/tools/wine/Wine-7.0-GE-4-LoL/lib64",
		"lib32": "/home/matchi/.config/heroic/tools/wine/Wine-7.0-GE-4-LoL/lib",
		"wineserver": "/home/matchi/.config/heroic/tools/wine/Wine-7.0-GE-4-LoL/bin/wineserver",
		"wineboot": "/home/matchi/.config/heroic/tools/wine/Wine-7.0-GE-4-LoL/bin/wineboot"
	},
	"winePrefix": "/home/matchi/Games/Heroic/Prefixes/Alien Breed 2 Assault",
	"wineCrossoverBottle": ""
}

Game launched at: Thu Feb 16 2023 14:27:17 GMT+0100 (Mitteleuropäische Normalzeit)

An exception occurred when launching the game:
TypeError: Cannot set properties of undefined (setting 'Language')
    at setup (/tmp/.mount_HeroicRzEe1v/resources/app.asar/build/electron/main.6ace4a2c.js:6:5339)
    at async prepareWineLaunch (/tmp/.mount_HeroicRzEe1v/resources/app.asar/build/electron/main.6ace4a2c.js:7:1318)
    at async W.launch (/tmp/.mount_HeroicRzEe1v/resources/app.asar/build/electron/main.6ace4a2c.js:53:6135)
    at async /tmp/.mount_HeroicRzEe1v/resources/app.asar/build/electron/main.6ace4a2c.js:191:273
    at async node:electron/js2c/browser_init:2:97553
```

### Steps to reproduce

1. Install "GOG - Alien Breed 2: Assault"
2. Click on "Start Game"
3. See error

### Expected behavior

Game starts

### Heroic Version

Latest Stable

### System Information

please see attached log

**Comment by arielj** [comment]
If you run the game again that error is gone, I already submitted a fix for that problem and it's merged in the main branch, so it's going to be fixed in the next release, but you should be able to run the game anyway after that error (you have to install physx using winetricks for those games to work)

**Comment by arielj** [comment]
This is PR that fixes that error for reference https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2455
