### ISSUE TITLE
Games do not select the Default Installation Path when clicking Install

### ISSUE THREAD

**Issue by Alzarath** [Heroic-Games-Launcher/HeroicGamesLauncher#2484]
### Describe the bug

When clicking on Install on a game from either Epic or GOG, the Install Path is set to the usual `$HOME/Games/Heroic` rather than the Default Installation Path value specified in Settings.

### Add logs

```text
(08:40:34) INFO:    [Connection]:       Connectivity: check-online

(08:40:34) INFO:    [Connection]:       Pinging external endpoints

(08:40:35) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version

(08:40:35) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary

(08:40:35) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl

(08:40:35) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl

(08:40:35) WARNING: [Backend]:          Protocol already registered.

(08:40:35) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version

(08:40:35) INFO:    [Backend]:          Loading Screen Ready

(08:40:35) INFO:    [Backend]:          

Heroic Version: 2.6.2 Trafalgar Law

Legendary Version:  0.20.32 Dark Energy (hotfix #6)

GOGdl Version: 0.6

Electron Version: 22.2.0

Chrome Version: 108.0.5359.215

NodeJS Version: 16.17.1

OS: Arch KERNEL: 6.1.12-arch1-1 ARCH: x64

CPU: Intel Core™ i7-8700K @3.7 GOVERNOR: powersave

RAM: Total: 31.3 GiB Available: 11.32 GiB

GRAPHICS: GPU0: NVIDIA GeForce RTX 2070 SUPER VRAM: 8192MB DRIVER: 525.89.02 

PROTOCOL: x11

(08:40:35) INFO:    [Frontend]:         Refreshing Library

(08:40:35) INFO:    [Legendary]:        Refreshing library...

(08:40:35) INFO:    [Legendary]:        Refreshing Epic Games...

(08:40:35) INFO:    [Legendary]:        Game list updated, got 43 games & DLCs

(08:40:35) INFO:    [Backend]:          Frontend Ready

(08:40:35) INFO:    [Backend]:          Checking for new Heroic Updates

(08:40:35) INFO:    [Backend]:          Checking for current version changelog

(08:40:35) INFO:    [Frontend]:         Force Update

(08:40:36) INFO:    [Connection]:       Connectivity: online

(08:40:36) INFO:    [Gog]:              Getting data about the user

(08:40:37) INFO:    [Winetricks]:       Downloading Winetricks

(08:40:38) INFO:    [Gog]:              Saved user data to config

(08:40:39) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party

(08:40:39) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded

(08:40:40) INFO:    [Backend]:          Starting the Download Queue

(08:40:46) WARNING: [Winetricks]:       Error Downloading Winetricks Error: error request aborted

    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)

    at IncomingMessage.handlerStreamAborted (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:301:18)

    at IncomingMessage.emit (node:events:513:28)

    at IncomingMessage._destroy (node:_http_incoming:224:10)

    at _destroy (node:internal/streams/destroy:102:25)

    at IncomingMessage.destroy (node:internal/streams/destroy:64:5)

    at TLSSocket.socketCloseListener (node:_http_client:441:11)

    at TLSSocket.emit (node:events:525:35)

    at node:net:757:14

    at TCP.done (node:_tls_wrap:584:7)

(08:40:51) DEBUG:   [Legendary]:        Using cached install info

(08:40:51) DEBUG:   [Backend]:          {"free":990715105280,"diskSize":1959390953472,"message":"922.68 GiB / 1.78 TiB","validPath":true}

(08:40:51) DEBUG:   [Backend]:          {"free":990715105280,"diskSize":1959390953472,"message":"922.68 GiB / 1.78 TiB","validPath":true}
```

### Steps to reproduce

1. Go to Settings
2. Set the Default Installation Path to something different from the default value.
3. Go to your library
4. Attempt to install a game.

### Expected behavior

The initial value should be set to the one specified in the Default Installation Path under Settings.

### Heroic Version

Latest Stable

### System Information

- Arch Linux x86_64

**Comment by szszoke** [comment]
I have the same problem. Running Heroic 2.6.2.

**Comment by Etaash-mathamsetty** [comment]
works for me

**Comment by flavioislima** [comment]
This bug was fixed already, will be fixed in the next release.

**Comment by arielj** [comment]
@Alzarath @szszoke can you confirm this is working for you with the new 2.7 release?

**Comment by Alzarath** [comment]
Yes, but only after selecting a **different** directory in the Settings (then setting it back), it appears to select the correct directory.

**Comment by flavioislima** [comment]
> Yes, but only after selecting a **different** directory in the Settings (then setting it back), it appears to select the correct directory. Edit: For clarity, it's also fixed between sessions, it only needed updated from the value that was previously set when it was broken.

Yes, that is expected because the issue was that Heroic was not storing the setting correctly so after the update you will need to do that to proper update the settings file 👍🏽
