### ISSUE TITLE
Cannot download anything

### ISSUE THREAD

**Issue by Subtixx** [Heroic-Games-Launcher/HeroicGamesLauncher#2505]
### Describe the bug

It says it downloads but downloads with 0kbs. Even though steam downloads work fine through steam for example.

### Add logs

```text
(11:58:38) INFO:    [Connection]:       Connectivity: check-online
(11:58:38) INFO:    [Connection]:       Pinging external endpoints
(11:58:38) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(11:58:38) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(11:58:38) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(11:58:38) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(11:58:38) WARNING: [Backend]:          Protocol already registered.
(11:58:38) INFO:    [Connection]:       Connectivity: online
(11:58:38) INFO:    [Gog]:              Getting data about the user
(11:58:38) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(11:58:38) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(11:58:38) INFO:    [Backend]:          Loading Screen Ready
(11:58:38) INFO:    [Gog]:              Saved user data to config
(11:58:39) INFO:    [Frontend]:         Refreshing Library
(11:58:39) INFO:    [Legendary]:        Refreshing library...
(11:58:39) INFO:    [Legendary]:        Refreshing Epic Games...
(11:58:39) INFO:    [Legendary]:        Game list updated, got 222 games & DLCs
(11:58:39) INFO:    [Gog]:              Getting GOG library
(11:58:39) INFO:    [Backend]:          Frontend Ready
(11:58:39) INFO:    [Backend]:          

Heroic Version: 2.6.2 Trafalgar Law
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.6

Electron Version: 22.2.0
Chrome Version: 108.0.5359.215
NodeJS Version: 16.17.1

OS: EndeavourOS KERNEL: 6.1.12-arch1-1 ARCH: x64
CPU: AMD Ryzen 9 3900X 12-Core Processor @3.8 GOVERNOR: schedutil
RAM: Total: 46.95 GiB Available: 39.6 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 2060 SUPER VRAM: 8192MB DRIVER: 525.89.02 
PROTOCOL: x11

(11:58:39) INFO:    [Backend]:          Checking for new Heroic Updates
(11:58:39) INFO:    [Backend]:          Checking for current version changelog
(11:58:39) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(11:58:39) INFO:    [Gog]:              Number of library pages: 1
(11:58:39) INFO:    [Gog]:              Saved games data
(11:58:40) INFO:    [Legendary]:        Checking for game updates: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(11:58:40) INFO:    [Winetricks]:       Downloading Winetricks
(11:58:44) INFO:    [Backend]:          Starting the Download Queue
(11:58:44) INFO:    [Gog]:              Installing 1207664643: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl download 1207664643 --platform windows --path=/mnt/Games/GOG --token <redacted> --with-dlcs --lang=de-DE
(11:58:44) DEBUG:   [Gog]:              Logging to file "/home/subtixx/.config/heroic/GamesConfig/1207664643.log"
(11:58:44) INFO:    [Backend]:          Preventing machine to sleep
(11:58:47) WARNING: [Legendary]:        Failed to parse games from /home/subtixx/.config/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/home/subtixx/.config/legendary/installed.json'
    at Object.openSync (node:fs:594:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:462:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at R.listUpdateableGames (/opt/Heroic/resources/app.asar/build/electron/main.6ace4a2c.js:56:9290)
    at async /opt/Heroic/resources/app.asar/build/electron/main.6ace4a2c.js:184:3970
    at async node:electron/js2c/browser_init:2:97553
(11:58:47) INFO:    [Legendary]:        Found 0 games to update
(11:58:47) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:58:48) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:58:48) INFO:    [Gog]:              Found 0 game(s) to update
(11:58:49) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:58:50) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:58:51) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:58:52) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:58:53) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:58:54) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:58:55) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:58:56) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:58:57) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:58:58) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:58:59) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:59:00) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:59:01) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:59:02) INFO:    [Backend]:          Trying to kill 1207664643
(11:59:02) INFO:    [Backend]:          Killed 1207664643
(11:59:02) INFO:    [Gog]:              Abort command "/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl download 1207664643 --platform windows --path=/mnt/Games/GOG --token <redacted> --with-dlcs --lang=de-DE"
(11:59:02) WARNING: [DownloadManager]:  Installing of 1207664643 aborted!
(11:59:02) INFO:    [DownloadManager]:  1207664643 added to download manager finished.
(11:59:02) INFO:    [DownloadManager]:  1207664643 removed from download manager.
(11:59:02) INFO:    [Frontend]:         Refreshing Library
(11:59:02) INFO:    [Gog]:              Getting GOG library
(11:59:02) INFO:    [Gog]:              Number of library pages: 1
(11:59:03) INFO:    [Gog]:              Saved games data
(11:59:04) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for The Witcher 3 Wild Hunt
(11:59:04) INFO:    [Gog]:              Got install info from cache for 1207664643 on windows platform
(11:59:04) INFO:    [Gog]:              Got install info from cache for 1207664643 on windows platform
(11:59:04) INFO:    [Gog]:              Got install info from cache for 1207664643 on windows platform
(11:59:04) INFO:    [Gog]:              Got install info from cache for 1207664643 on windows platform
(11:59:05) INFO:    [Gog]:              Got install info from cache for 1207664643 on windows platform
(11:59:05) DEBUG:   [Backend]:          {"free":3262521606144,"diskSize":3936860798976,"message":"2.97 TiB / 3.58 TiB","validPath":true}
(11:59:05) DEBUG:   [Backend]:          {"free":3262521606144,"diskSize":3936860798976,"message":"2.97 TiB / 3.58 TiB","validPath":true}
(11:59:17) INFO:    [Backend]:          Writing config for 1207664643
(11:59:17) INFO:    [Gog]:              Got install info from cache for 1207664643 on windows platform
(11:59:18) INFO:    [DownloadManager]:  The Witcher 3: Wild Hunt  was added to the download queue.
(11:59:18) INFO:    [Gog]:              Installing 1207664643: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl download 1207664643 --platform windows --path=/mnt/Games/GOG --token <redacted> --skip-dlcs --lang=de-DE
(11:59:18) DEBUG:   [Gog]:              Logging to file "/home/subtixx/.config/heroic/GamesConfig/1207664643.log"
(11:59:18) INFO:    [Backend]:          Preventing machine to sleep
(11:59:18) INFO:    [Gog]:              Got install info from cache for 1207664643 on windows platform
(11:59:18) INFO:    [Gog]:              Got install info from cache for 1207664643 on windows platform
(11:59:21) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:59:22) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:59:23) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:59:24) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:59:25) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:59:26) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:59:27) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:59:28) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:59:29) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(11:59:30) INFO:    [Gog]:              Progress for The Witcher 3: Wild Hunt: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
```

### Steps to reproduce

1. Try to start a download..
2. Download starts but shows 0mb/s

### Expected behavior

That the download gets any progress.

### Heroic Version

Latest Stable

### System Information

- OS: EndevaourOS

### Additional information

Ok, after debugging gogdl and trying to manually download it using gogdl it showed me: 

```
invalid secure link response: 403 {
    "error": "invalid_licence",
    "error_description": "User #*********** does not have the license for product #1207664643."
}
```

However why did it then show up in my games list??

**Comment by arielj** [comment]
Can you try the app image from here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/4518735588? we have a lot of fixes for GOG installations pending for the next release, maybe that fixes your problem

**Comment by arielj** [comment]
Closing as it's stale with no response. Please comment again if this is still an issue
