### ISSUE TITLE
Frequent uncaught exceptions

### ISSUE THREAD

**Issue by aurumvorax** [Heroic-Games-Launcher/HeroicGamesLauncher#2522]
### Describe the bug

When taking basically any action, such as opening heroic, trying to launch a game, opening wine manager, etc, there is an error message:

A uncaught exception occured:
Error: write EPIPE
Report the exception on our Github repository.

### Add logs

```text
(16:24:16) INFO:    [Connection]:       Connectivity: check-online
(16:24:16) INFO:    [Connection]:       Pinging external endpoints
(16:24:16) INFO:    [Legendary]:        Running command: /tmp/.mount_Heroic22RyjS/resources/app.asar.unpacked/build/bin/linux/legendary --version
(16:24:16) INFO:    [Legendary]:        Legendary location: /tmp/.mount_Heroic22RyjS/resources/app.asar.unpacked/build/bin/linux/legendary
(16:24:16) INFO:    [Gog]:              GOGDL location: /tmp/.mount_Heroic22RyjS/resources/app.asar.unpacked/build/bin/linux/gogdl
(16:24:16) INFO:    [Gog]:              GOGDL location: /tmp/.mount_Heroic22RyjS/resources/app.asar.unpacked/build/bin/linux/gogdl
(16:24:16) WARNING: [Backend]:          Failed to register protocol with OS.
(16:24:16) ERROR:   [Backend]:          Error: write EPIPE
(16:24:16) INFO:    [Gog]:              Running command: /tmp/.mount_Heroic22RyjS/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(16:24:16) ERROR:   [Backend]:          Error: write EPIPE
(16:24:16) INFO:    [Connection]:       Connectivity: online
(16:24:16) INFO:    [Backend]:          User Not Found, removing it from Store
(16:24:16) ERROR:   [Backend]:          Error: write EPIPE
(16:24:17) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(16:24:17) ERROR:   [Backend]:          Error: write EPIPE
(16:24:17) INFO:    [Backend]:          

Heroic Version: 2.6.2 Trafalgar Law
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.6

Electron Version: 22.2.0
Chrome Version: 108.0.5359.215
NodeJS Version: 16.17.1

OS: Ubuntu KERNEL: 5.19.0-31-generic ARCH: x64
CPU: Intel Gen Intel® Core™ i9-12900H @3.08 GOVERNOR: powersave
RAM: Total: 15.33 GiB Available: 8.8 GiB
GRAPHICS: GPU0: Alder Lake-P Integrated Graphics Controller  VRAM: 256MB  GPU1: NVIDIA GeForce RTX 3070 Ti Laptop GPU VRAM: 8192MB DRIVER: 515.86.01 
PROTOCOL: x11

(16:24:17) ERROR:   [Backend]:          Error: write EPIPE
(16:24:17) INFO:    [Backend]:          Loading Screen Ready
(16:24:17) ERROR:   [Backend]:          Error: write EPIPE
(16:24:17) INFO:    [Backend]:          Frontend Ready
(16:24:17) ERROR:   [Backend]:          Error: write EPIPE
(16:24:17) INFO:    [Backend]:          Checking for new Heroic Updates
(16:24:17) ERROR:   [Backend]:          Error: write EPIPE
(16:24:17) INFO:    [Backend]:          Checking for current version changelog
(16:24:17) ERROR:   [Backend]:          Error: write EPIPE
(16:24:18) ERROR:   [Backend]:          Error: write EPIPE
(16:24:18) INFO:    [Winetricks]:       Downloading Winetricks
(16:24:18) ERROR:   [Backend]:          Error: write EPIPE
(16:24:19) WARNING: [Winetricks]:       Error Downloading Winetricks Error: timeout of 1000ms exceeded
    at createError (/tmp/.mount_Heroic22RyjS/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/tmp/.mount_Heroic22RyjS/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/tmp/.mount_Heroic22RyjS/resources/app.asar/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
(16:24:22) INFO:    [Backend]:          Starting the Download Queue
(16:24:22) ERROR:   [Backend]:          Error: write EPIPE
(16:24:33) ERROR:   [Backend]:          Error when checking for current Heroic changelog
(16:24:33) ERROR:   [Backend]:          Error when checking for Heroic updates Error: getaddrinfo EAI_AGAIN api.github.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
(16:26:10) INFO:    [Frontend]:         Refreshing wine downloader releases
(16:26:10) ERROR:   [Backend]:          Error: write EPIPE
(16:26:10) INFO:    [WineDownloader]:   Updating wine versions info
(16:26:10) INFO:    [WineDownloader]:   Fetching upstream information...
(16:26:10) ERROR:   [Backend]:          Error: write EPIPE
(16:26:13) INFO:    [WineDownloader]:   wine versions updated
(16:26:13) ERROR:   [Backend]:          Error: write EPIPE
(16:26:29) INFO:    [WineDownloader]:   Start installation of wine version Proton-GE-Proton7-24
(16:26:29) ERROR:   [Backend]:          Error: write EPIPE
(16:27:34) INFO:    [WineDownloader]:   Finished installation of wine version Proton-GE-Proton7-24
(16:27:34) ERROR:   [Backend]:          Error: write EPIPE
```

### Steps to reproduce

Open Heroic Launcher.

### Expected behavior

Well, I'm assuming uncaught exceptions shouldn't be happening.

### Heroic Version

Latest Stable

### System Information

Ubuntu 22.10 with KDE Plasma 5.25.5

**Comment by aurumvorax** [comment]
Forgot to mention, this is on the AppImage version.

**Comment by aurumvorax** [comment]
I fixed the winetricks issue(reinstalled WINE), no network issues at all.
This issue persisted. I can't think of anything besides basic permissions
that would prevent Heroic from writing logs, I'm opening the appimage from
within my home directory, and I haven't changed any permissions there.  The
fact that it's failing to write to log narrows it down a lot though, I'll
keep playing with it.  I really want Heroic to work, 2077 really does not
like lutris :(

Thanks

**Comment by CommandMC** [comment]
> no network issues at all

The 2nd error message I've posted is a network error (your DNS server does not know where `api.github.com` goes to, essentially). Perhaps you are behind a proxy/VPN?

**Comment by aurumvorax** [comment]
Nope, no proxy, no VPN

**Comment by aurumvorax** [comment]
Reinstalling wine fixed the network issues, but not the logging exception

**Comment by joshlangley** [comment]
I am experiencing the same error using the Flatpak version. I have WINE and winetricks installed. This dialog is making the app very annoying to try to use.

![Screenshot_20230605_133822](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/39417713/ed90de65-49ee-46a3-adcc-72895f0b1584)

Moreover, my internet works fine. I can ping `api.github.com`, but it does behave weirdly. (Good ping times, randomly dropping packets, each ping takes a while to come in.) I also have no VPN and no proxy.

I'm using KDE Plasma 5.27.5 on Archlinux (fully up to date).

Here's a copy of the relevant log files from `$HOME/.var/app/com.heroicgameslauncher.hgl/config/heroic/logs`, with my home directory redacted to `$HOME`:
[logs.tar.gz](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/11657132/logs.tar.gz)

I'm also not sure why nonfatal errors (the app seems to work as expected still) are so obnoxious. When a download is running I literally can't do anything since a new one of these dialogs pops up as soon as I close it. Perhaps it would be worth reconsidering how error dialogs are handled?

**Comment by bruno-fs** [comment]
I'm also experiencing constant uncaught exceptions with the flatpak version

Sharing the logs in case they help (meanwhile I'm gonna try the rpm version): [heroic-2023-09-23T18_46_36.684Z.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/12707134/heroic-2023-09-23T18_46_36.684Z.log)

**Comment by CommandMC** [comment]
@joshlangley @bruno-fs You're piping Heroic's `stdout` into a closed pipe. Not quite sure why/how you're doing that though

In case anyone else wishes to reproduce this issue, piping Heroic to `head` (`heroic | head` / `flatpak run com.heroicgameslauncher.hgl | head`) will also lead to those exceptions

**Comment by joshlangley** [comment]
> You're piping Heroic's `stdout` into a closed pipe. Not quite sure why/how you're doing that though

I cannot find any pipes anywhere. The .desktop file runs the command `run --branch=stable --arch=x86_64 --command=heroic-run --file-forwarding com.heroicgameslauncher.hgl @@u %u @@`. I certainly wasn't piping anything myself since I was using the .desktop launcher in my desktop, not the terminal. Perhaps this is some internal Flatpak thing?

I'm actually not sure how the pipeline could cause such issues in the first place since it's just redirecting terminal output. However, if this was duplicated then maybe there's something to it?

However, I can say I'm not experiencing this issue anymore. I'm not sure how or when it was fixed since I don't use Heroic much, but it's gone now. All that changed was that I routinely run updates.

**Comment by joshlangley** [comment]
Did some testing running from the terminal and I can confirm that piping to head does reproduce this: `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=heroic-run --file-forwarding com.heroicgameslauncher.hgl @@u %u @@ | head`. However, piping to cat or a file doesn't: `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=heroic-run --file-forwarding com.heroicgameslauncher.hgl @@u %u @@ | cat`.
Interestingly, increasing the number of entries head dumps makes the app last longer without throwing the error: `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=heroic-run --file-forwarding com.heroicgameslauncher.hgl @@u %u @@ | head --lines=75`

I didn't know there was a difference, perhaps the `stdout` file is closed by the system after head closes it or is done with it? That would make sense actually. I definitely learned something new today.

**Comment by CommandMC** [comment]
The last paragraph there is correct. `head` closes the pipe once it received as much text as it'll print out (and that's why I suggested it to reproduce the issue)
I'm however also not sure *why* this happened in regular use, or what changed now to make it no longer happen

On Heroic's side of things, we can at least make this a little less annoying to deal with (which is exactly what the PR I linked does). Since writing to stdout/stderr is not a core component of Heroic, we can just acknowledge that the error happened & carry on, without spamming out endless exception messages

**Comment by bruno-fs** [comment]
I forgot to mention I'm using Wayland. I just noticed another application is having a similar issue which I fixed by disabling socket=wayland and enabling socket=x11 on flatseal.

I wonder if it is related

**Comment by officiallymarky** [comment]
I am also seeing the EPIPE error spamming in Heroic.  I am using a new install of Pikaos, and installed Heroic, it worked great no issues.  The next day I opened Heroic, and it started to throw this error over and over making using Heroic impossible unless you go in, start a game really quick and close it.  I am using KDE 5.27.8 and wayland.
