### ISSUE TITLE
Failed to execute script 'cli' due to unhandled exception!

### ISSUE THREAD

**Issue by bearcatjamboree** [Heroic-Games-Launcher/HeroicGamesLauncher#2543]
### Describe the bug

I can install Heroic with the latest wine release and successfully play Rocket League but when I try other games they fail on start up.  This is the common error I see in the logs from the few I tried:

Traceback (most recent call last):
  File "legendary/cli.py", line 3061, in <module>
  File "legendary/cli.py", line 2976, in main
  File "legendary/cli.py", line 608, in launch_game
  File "legendary/core.py", line 701, in get_launch_parameters
  File "legendary/core.py", line 633, in get_app_launch_command
IndexError: list index out of range
[53759] Failed to execute script 'cli' due to unhandled exception!

### Add logs

```text
(21:40:38) INFO:    [Connection]:       Connectivity: check-online
(21:40:38) INFO:    [Connection]:       Pinging external endpoints
(21:40:38) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(21:40:38) INFO:    [Legendary]:        Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(21:40:38) INFO:    [Gog]:              GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(21:40:38) INFO:    [Gog]:              GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(21:40:38) WARNING: [Backend]:          Protocol already registered.
(21:40:39) INFO:    [Connection]:       Connectivity: online
(21:40:39) INFO:    [Backend]:          Loading Screen Ready
(21:40:39) INFO:    [Frontend]:         Refreshing Library
(21:40:39) INFO:    [Legendary]:        Refreshing library...
(21:40:39) INFO:    [Legendary]:        Refreshing Epic Games...
(21:40:39) INFO:    [Legendary]:        Game list updated, got 22 games & DLCs
(21:40:39) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(21:40:39) INFO:    [Backend]:          Frontend Ready
(21:40:39) INFO:    [Backend]:          Checking for new Heroic Updates
(21:40:39) INFO:    [Backend]:          Checking for current version changelog
(21:40:39) INFO:    [Legendary]:        Checking for game updates: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
(21:40:39) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
(21:40:44) INFO:    [Backend]:          Starting the Download Queue
(21:40:47) INFO:    [Gog]:              Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --version
(21:40:52) INFO:    [Legendary]:        Found 0 games to update
(21:40:52) INFO:    [Gog]:              Found 0 game(s) to update
(21:40:52) INFO:    [Backend]:          

Heroic Version: 2.6.2 Trafalgar Law
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.6

Electron Version: 22.2.0
Chrome Version: 108.0.5359.215
NodeJS Version: 16.17.1

OS: macOS Ventura 13.1 KERNEL: 22.2.0 ARCH: arm64
CPU: Apple M1 @2.4 
RAM: Total: 8 GiB Available: 5.73 GiB
GRAPHICS: GPU0: Apple M1   


(21:48:50) INFO:    [Backend]:          Launching Roller Champions (540f935fa0ad4bd498177ee5ad3b54e4)
(21:48:50) INFO:    [Backend]:          Preventing display from sleep
(21:48:50) INFO:    [Backend]:          Checking if wine version exists: Wine Staging - 8.3
(21:48:51) INFO:    [Backend]:          Checking if wine version exists: Wine Staging - 8.3
(21:48:51) INFO:    [Backend]:          Checking if wine version exists: Wine Staging - 8.3
(21:48:51) INFO:    [Backend]:          Checking if wine version exists: Wine Staging - 8.3
(21:48:51) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(21:48:52) INFO:    [Backend]:          Launching Knockout City (90f9ff166b404502a939ae217ff5109e)
(21:48:52) INFO:    [Backend]:          Preventing display from sleep
(21:48:52) INFO:    [Backend]:          Checking if wine version exists: Wine Staging - 8.3
(21:48:53) INFO:    [Backend]:          Checking if wine version exists: Wine Staging - 8.3
(21:48:53) INFO:    [Backend]:          Checking if wine version exists: Wine Staging - 8.3
(21:48:53) INFO:    [Backend]:          Checking if wine version exists: Wine Staging - 8.3
(21:48:53) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(21:48:54) INFO:    [Backend]:          Launching Fall Guys (0a2d9f6403244d12969e11da6713137b)
(21:48:54) INFO:    [Backend]:          Checking if wine version exists: Wine Staging - 8.3
(21:48:54) INFO:    [Backend]:          Checking if wine version exists: Wine Staging - 8.3
(21:48:54) INFO:    [Backend]:          Checking if wine version exists: Wine Staging - 8.3
(21:48:54) INFO:    [Backend]:          Checking if wine version exists: Wine Staging - 8.3
(21:48:54) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(21:48:59) INFO:    [DXVKInstaller]:    installing dxvk-macOS on... /Users/cboxgo/Games/Heroic/Prefixes/Roller Champions
(21:48:59) INFO:    [DXVKInstaller]:    dxvk-macOS already installed!
(21:48:59) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary launch 540f935fa0ad4bd498177ee5ad3b54e4 --json --offline
(21:49:01) INFO:    [DXVKInstaller]:    installing dxvk-macOS on... /Users/cboxgo/Games/Heroic/Prefixes/Knockout City
(21:49:01) INFO:    [DXVKInstaller]:    dxvk-macOS already installed!
(21:49:01) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary launch 90f9ff166b404502a939ae217ff5109e --json --offline
(21:49:02) INFO:    [DXVKInstaller]:    installing dxvk-macOS on... /Users/cboxgo/Games/Heroic/Prefixes/Fall Guys
(21:49:02) INFO:    [DXVKInstaller]:    dxvk-macOS already installed!
(21:49:02) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary launch 0a2d9f6403244d12969e11da6713137b --json --offline
(21:49:09) INFO:    [Legendary]:        Launching Roller Champions: LD_PRELOAD= WINEPREFIX="/Users/cboxgo/Games/Heroic/Prefixes/Roller Champions" WINEDLLOVERRIDES=winemenubuilder= ORIG_LD_LIBRARY_PATH= LD_LIBRARY_PATH="/Users/cboxgo/Library/Application Support/heroic/tools/wine/Wine-8.3/Contents/Resources/wine/lib:/Users/cboxgo/Library/Application Support/heroic/tools/wine/Wine-8.3/Contents/Resources/wine/lib" WINEDLLPATH="/Users/cboxgo/Library/Application Support/heroic/tools/wine/Wine-8.3/Contents/Resources/wine/lib/wine:/Users/cboxgo/Library/Application Support/heroic/tools/wine/Wine-8.3/Contents/Resources/wine/lib/wine" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary launch 540f935fa0ad4bd498177ee5ad3b54e4 --language en --wine "/Users/cboxgo/Library/Application Support/heroic/tools/wine/Wine-8.3/Contents/Resources/wine/bin/wine64"
(21:49:10) INFO:    [Legendary]:        Launching Knockout City: LD_PRELOAD= WINEPREFIX="/Users/cboxgo/Games/Heroic/Prefixes/Knockout City" WINEDLLOVERRIDES=winemenubuilder= ORIG_LD_LIBRARY_PATH= LD_LIBRARY_PATH="/Users/cboxgo/Library/Application Support/heroic/tools/wine/Wine-8.3/Contents/Resources/wine/lib:/Users/cboxgo/Library/Application Support/heroic/tools/wine/Wine-8.3/Contents/Resources/wine/lib" WINEDLLPATH="/Users/cboxgo/Library/Application Support/heroic/tools/wine/Wine-8.3/Contents/Resources/wine/lib/wine:/Users/cboxgo/Library/Application Support/heroic/tools/wine/Wine-8.3/Contents/Resources/wine/lib/wine" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary launch 90f9ff166b404502a939ae217ff5109e --language en --wine "/Users/cboxgo/Library/Application Support/heroic/tools/wine/Wine-8.3/Contents/Resources/wine/bin/wine64"
(21:49:11) INFO:    [Legendary]:        Launching Fall Guys: LD_PRELOAD= WINEPREFIX="/Users/cboxgo/Games/Heroic/Prefixes/Fall Guys" WINEDLLOVERRIDES=winemenubuilder= ORIG_LD_LIBRARY_PATH= LD_LIBRARY_PATH="/Users/cboxgo/Library/Application Support/heroic/tools/wine/Wine-8.3/Contents/Resources/wine/lib:/Users/cboxgo/Library/Application Support/heroic/tools/wine/Wine-8.3/Contents/Resources/wine/lib" WINEDLLPATH="/Users/cboxgo/Library/Application Support/heroic/tools/wine/Wine-8.3/Contents/Resources/wine/lib/wine:/Users/cboxgo/Library/Application Support/heroic/tools/wine/Wine-8.3/Contents/Resources/wine/lib/wine" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary launch 0a2d9f6403244d12969e11da6713137b --language en --wine "/Users/cboxgo/Library/Application Support/heroic/tools/wine/Wine-8.3/Contents/Resources/wine/bin/wine64"
(21:49:22) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(21:49:22) INFO:    [Frontend]:         Refreshing Library
(21:49:22) INFO:    [Legendary]:        Refreshing library...
(21:49:22) INFO:    [Legendary]:        Game list updated, got 22 games & DLCs
(21:49:23) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(21:49:23) INFO:    [Frontend]:         Refreshing Library
(21:49:23) INFO:    [Legendary]:        Refreshing library...
(21:49:23) INFO:    [Legendary]:        Game list updated, got 22 games & DLCs
```

### Steps to reproduce

1. Install Heroic
2. Install Wine Staging - 8.3
3. Launch one of the following: Fall Guys, Knockout City, or Roller Champions

### Expected behavior

Loaded and playable game

### Screenshots

None because game crashes

### Heroic Version

Latest Stable

### System Information

Mac OS 13.1 (22C65)

**Comment by Nocccer** [comment]
First of all Fall guys ist not working on mac os, because of anticheat. 

How does wine staging work on mac os? I thought they dropped mac support long time ago.  What people use is crossover or some wine builds which you can download from our wine manager.

**Comment by bearcatjamboree** [comment]
According to https://areweanticheatyet.com it's in "Running" status

The wine version I'm using is available in the Heroic Game Launcher app so I don't know why that would be discontinued on Mac.  In fact, it worked for launching Rocket League but Crossover wouldn't

**Comment by Nocccer** [comment]
No it has something todo with launch arguments. You should provide full game log in discord and maybe people see mistakes like miss configuration of the game or paths with not supported characters. The trace does not tell anything without the whole game log.

**Comment by bearcatjamboree** [comment]
I followed the steps here for copying and providing the log.

**Comment by Nocccer** [comment]
Feel free to ping me on discord in your support channel post so we can figure it out there.

**Comment by Nocccer** [comment]
I don't see that the trace happens in the general log so i assume it happens in game log:
![image](https://user-images.githubusercontent.com/61798668/225645190-f3f033c9-4588-483f-87b8-5721455f0b77.png)

**Comment by bearcatjamboree** [comment]
Also, i think the CLI error is because of the arguments being generated like this:

WINEDLLOVERRIDES=winemenubuilder=

I don't think that's the problem though.

**Comment by bearcatjamboree** [comment]
No, everything under OTHER in the game settings is empty.

**Comment by bearcatjamboree** [comment]
I think the reason the game isn't loading is because it uses DirectX 12.  Thanks for checking though...
