### ISSUE TITLE
Heroic Reset Breaks Game Defaults Prefix

### ISSUE THREAD

**Issue by KenJyn76** [Heroic-Games-Launcher/HeroicGamesLauncher#2574]
### Describe the bug

Resetting Heroic changes the Default Wine Prefix for games to $HOME/.wine. I don't believe this is reflected in logs, but it means I have to manually set every prefix myself.

### Add logs

```text
(15:01:03) INFO:    [Connection]:       Connectivity: check-online
(15:01:03) INFO:    [Connection]:       Pinging external endpoints
(15:01:03) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:01:03) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(15:01:03) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:01:03) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:01:03) WARNING: [Backend]:          Protocol already registered.
(15:01:03) INFO:    [Connection]:       Connectivity: online
(15:01:03) INFO:    [Gog]:              Getting data about the user
(15:01:03) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(15:01:03) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(15:01:03) INFO:    [Backend]:          Loading Screen Ready
(15:01:03) INFO:    [Frontend]:         Refreshing Library
(15:01:03) INFO:    [Legendary]:        Refreshing library...
(15:01:03) INFO:    [Legendary]:        Refreshing Epic Games...
(15:01:03) INFO:    [Legendary]:        Game list updated, got 53 games & DLCs
(15:01:03) INFO:    [Gog]:              Getting GOG library
(15:01:03) INFO:    [Backend]:          Frontend Ready
(15:01:03) INFO:    [Backend]:          Checking for new Heroic Updates
(15:01:03) INFO:    [Backend]:          Checking for current version changelog
(15:01:03) INFO:    [Backend]:          

Heroic Version: 2.6.2 Trafalgar Law
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.6

Electron Version: 22.2.0
Chrome Version: 108.0.5359.215
NodeJS Version: 16.17.1

OS: EndeavourOS KERNEL: 6.3.0-rc3-273-tkg-cfs ARCH: x64
CPU: AMD Ryzen 7 5800X 8-Core Processor @3.8 GOVERNOR: powersave
RAM: Total: 31.27 GiB Available: 26.53 GiB
GRAPHICS: GPU0: Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] VRAM: 512MB  
PROTOCOL: wayland

(15:01:03) ERROR:   [Backend]:          Error when checking for Heroic updates Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
(15:01:03) ERROR:   [Backend]:          Error when checking for current Heroic changelog
(15:01:03) INFO:    [Gog]:              Saved user data to config
(15:01:04) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:01:04) INFO:    [Gog]:              Number of library pages: 1
(15:01:04) INFO:    [Gog]:              Saved games data
(15:01:04) INFO:    [Legendary]:        Checking for game updates: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:01:05) WARNING: [Legendary]:        Failed to parse games from /home/liam/.config/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/home/liam/.config/legendary/installed.json'
    at Object.openSync (node:fs:594:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:462:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at R.listUpdateableGames (/opt/Heroic/resources/app.asar/build/electron/main.6ace4a2c.js:56:9290)
    at async /opt/Heroic/resources/app.asar/build/electron/main.6ace4a2c.js:184:3970
    at async node:electron/js2c/browser_init:2:97553
(15:01:05) INFO:    [Legendary]:        Found 0 games to update
(15:01:05) INFO:    [Winetricks]:       Downloading Winetricks
(15:01:06) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:01:06) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(15:01:08) INFO:    [Backend]:          Starting the Download Queue
(15:01:08) INFO:    [Gog]:              Found 1 game(s) to update
```

### Steps to reproduce

1. Go to Settings > Advanced
2. Click on Reset Heroic
3. Go to Settings > Game Defaults
4. See it is set to $HOME/.wine

### Expected behavior

Prefixes should be separated, in the $HOME/Games/Heroic/Prefixes folder

### Screenshots

![image](https://user-images.githubusercontent.com/12451581/227800071-ee43b780-ff09-4b4b-986c-fac34e61f89a.png)

### Heroic Version

Latest Stable

### System Information

Arch Linux (Converted from EndeavourOS)

**Comment by KenJyn76** [comment]
This seems to have been my own fault -- I'm using a shared NTFS3 drive, and had "nocase" and "windows_names" enabled as mount options. Removing them both fixed the behavior, and my games are now defaulted to the Prefixes folder, even though the Game Defaults menu still shows .wine as the default prefix.

**Comment by KenJyn76** [comment]
I thought I had fixed this, but the issue persists.

**Comment by KenJyn76** [comment]
For anybody else who runs into this, if it's not reproducible on other machines:

The best way I could find to fix this was to delete your $HOME/.config/heroic folder, then relaunch and log back in with GOG. Every game that was installed when I hit Reset Heroic had their wine prefixes set to $HOME/.wine because it's the Game Defaults setting, but importing them after clearing the config folder gave them the correct prefix.

**Comment by KenJyn76** [comment]
For anybody else who runs into this, if it's not reproducible on other machines:

The best way I could find to fix this was to delete your $HOME/.config/heroic folder, then relaunch and log back in with GOG. Every game that was installed when I hit Reset Heroic had their wine prefixes set to $HOME/.wine because it's the Game Defaults setting, but importing them after clearing the config folder gave them the correct prefix.

**Comment by flavioislima** [comment]
The default prefix was changed sometime about this was fixed.
