### ISSUE TITLE
Heroic for Flatpak and deb (2.7.0) file loads game file size & information slowly

### ISSUE THREAD

**Issue by dtantono** [Heroic-Games-Launcher/HeroicGamesLauncher#2600]
### Describe the bug

Unlike version v 2.6.2 on this version. it can fetch download & install size slower and when I open the game page, it loads slower than usual. So, I need to wait a long time just wait for install a game. 

### Add logs

```text
(23:03:30) INFO:    [Connection]:       Connectivity: check-online
(23:03:30) INFO:    [Connection]:       Pinging external endpoints
(23:03:30) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(23:03:30) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(23:03:30) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(23:03:30) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(23:03:30) WARNING: [Backend]:          Failed to register protocol with OS.
(23:03:30) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(23:03:30) INFO:    [Connection]:       Connectivity: online
(23:03:30) INFO:    [Backend]:          User Not Found, removing it from Store
(23:03:30) INFO:    [Backend]:          Loading Screen Ready
(23:03:31) INFO:    [Backend]:          Frontend Ready
(23:03:31) INFO:    [Backend]:          

Heroic Version: 2.7.0 Eustass Kid
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.1

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: Freedesktop SDK KERNEL: 5.15.0-69-generic ARCH: x64
CPU: AMD Ryzen 9 5900HX with Radeon Graphics @3.48 GOVERNOR: performance
RAM: Total: 62.18 GiB Available: 46.62 GiB
GRAPHICS: GPU0: GA104M [GeForce RTX 3070 Mobile / Max-Q]  VRAM: 32MB GPU1: Cezanne VRAM: 512MB 
PROTOCOL: x11

(23:03:31) INFO:    [Backend]:          Checking for current version changelog
(23:03:31) INFO:    [Frontend]:         Updated to a new version, cleaaning up the cache.
(23:03:31) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary cleanup
(23:03:31) WARNING: [Backend]:          Failed download of AreWeAntiCheatYet data: Error: connect ECONNREFUSED 2606:50c0:8003::154:443
(23:03:32) INFO:    [Winetricks]:       Downloading Winetricks
(23:03:33) INFO:    [DXVKInstaller]:    Updating vkd3d to: vkd3d-proton-2.8-git
(23:03:33) INFO:    [DXVKInstaller]:    Updating dxvk to: dxvk-2.1
(23:03:33) WARNING: [Winetricks]:       Error Downloading Winetricks Error: timeout of 1000ms exceeded
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/app/bin/heroic/resources/app.asar/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
(23:03:36) INFO:    [Backend]:          Starting the Download Queue
(23:03:36) INFO:    [DXVKInstaller]:    downloaded dxvk
(23:03:36) INFO:    [DXVKInstaller]:    extracting dxvk
(23:03:36) INFO:    [DXVKInstaller]:    dxvk updated!
(23:03:36) INFO:    [DXVKInstaller]:    downloaded vkd3d
(23:03:36) INFO:    [DXVKInstaller]:    extracting vkd3d
(23:03:37) INFO:    [DXVKInstaller]:    vkd3d updated!
(23:03:42) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(23:03:42) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(23:04:15) INFO:    [Gog]:              Logging using GOG credentials
(23:04:15) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth --code <redacted>
(23:04:17) INFO:    [Gog]:              Login Successful
(23:04:17) INFO:    [Gog]:              Getting data about the user
(23:04:17) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(23:04:18) INFO:    [Gog]:              Saved user data to config
(23:04:18) INFO:    [Frontend]:         Refreshing Library
(23:04:18) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(23:04:18) INFO:    [Gog]:              Getting GOG library
(23:04:19) INFO:    [Gog]:              Number of library pages: 4
(23:04:19) INFO:    [Gog]:              Getting data for page 2
(23:04:21) INFO:    [Gog]:              Getting data for page 3
(23:04:22) INFO:    [Gog]:              Getting data for page 4
(23:04:23) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(23:04:25) INFO:    [Gog]:              Getting data for page 2
(23:04:27) INFO:    [Gog]:              Getting data for page 3
(23:04:28) INFO:    [Gog]:              Saved games data
(23:04:28) INFO:    [Frontend]:         No cache found, getting data from legendary...
(23:04:28) INFO:    [Legendary]:        Refreshing library...
(23:04:54) INFO:    [Legendary]:        Logging in: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(23:04:59) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1549831584
(23:05:00) INFO:    [Frontend]:         Refreshing Library
(23:05:00) INFO:    [Legendary]:        Refreshing library...
(23:05:00) INFO:    [Legendary]:        Refreshing Epic Games...
(23:05:00) INFO:    [Legendary]:        Game list updated, got 0 games & DLCs
(23:05:00) INFO:    [Frontend]:         Called Login
(23:05:00) INFO:    [Frontend]:         No cache found, getting data from legendary...
(23:05:00) INFO:    [Legendary]:        Refreshing library...
(23:05:00) INFO:    [Legendary]:        Game list updated, got 0 games & DLCs
(23:05:02) INFO:    [Frontend]:         Refreshing Library
(23:05:02) INFO:    [Legendary]:        Refreshing library...
(23:05:02) INFO:    [Legendary]:        Refreshing Epic Games...
(23:05:02) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(23:05:02) INFO:    [Legendary]:        Game list updated, got 0 games & DLCs
(23:05:02) INFO:    [Gog]:              Getting GOG library
(23:05:02) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(23:05:03) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(23:05:06) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(23:05:06) DEBUG:   [Backend]:          {"free":484216123392,"diskSize":1963908841472,"message":"450.96 GiB / 1.79 TiB","validPath":true}
(23:05:06) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 2147483059 --lang=en-US --os windows
(23:05:12) INFO:    [Gog]:              Number of library pages: 4
(23:05:12) INFO:    [Gog]:              Getting data for page 2
(23:05:23) WARNING: [Gog]:              Failed to get Install Info for 2147483059 using windows as platform, returning empty object
(23:05:27) INFO:    [Gog]:              Getting data for page 3
(23:05:36) INFO:    [Backend]:          Heroic: Setting autoUpdateGames to true
(23:05:38) INFO:    [Gog]:              Getting data for page 4
(23:05:43) INFO:    [Backend]:          Heroic: Setting libraryTopSection to "recently_played_installed"
(23:05:56) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(23:05:58) INFO:    [Gog]:              Getting data for page 2
(23:05:59) INFO:    [Gog]:              Getting data for page 3
(23:06:01) INFO:    [Gog]:              Saved games data
(23:06:01) INFO:    [Frontend]:         No cache found, getting data from legendary...
(23:06:01) INFO:    [Legendary]:        Refreshing library...
(23:06:01) INFO:    [Legendary]:        Game list updated, got 82 games & DLCs
(23:06:01) INFO:    [Frontend]:         Force Update
(23:06:03) ERROR:   [Runtime]:          Failed to download runtime eac_runtime: Error: connect ECONNREFUSED 2606:4700:3033::6815:2930:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
(23:06:05) INFO:    [Backend]:          Heroic: Setting useGameMode to true
(23:06:06) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1549831584
(23:06:07) ERROR:   [Runtime]:          Failed to download runtime battleye_runtime: Error: connect ECONNREFUSED 2606:4700:3034::ac43:9ff8:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
(23:06:08) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1138308214
(23:06:10) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1159146122
(23:06:11) ERROR:   [Runtime]:          Failed to download runtime battleye_runtime: Error: connect ECONNREFUSED 2606:4700:3033::6815:2930:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
(23:06:21) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(23:06:22) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(23:06:30) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(23:06:30) DEBUG:   [Backend]:          {"free":484208726016,"diskSize":1963908841472,"message":"450.95 GiB / 1.79 TiB","validPath":true}
(23:06:30) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1460447406 --lang=en-US --os windows
(23:06:39) WARNING: [Gog]:              Failed to get Install Info for 1460447406 using windows as platform, returning empty object
(23:07:00) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1138308214
(23:07:08) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1159146122
(23:08:34) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Act of War High Treason
(23:08:34) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Act of War High Treason
(23:08:34) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Act of War High Treason
(23:08:34) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Act of War High Treason
(23:08:34) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(23:08:34) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Act of War High Treason
(23:08:34) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Act of War High Treason
(23:08:34) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Act of War High Treason
(23:08:34) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Act of War High Treason
(23:08:34) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(23:08:34) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(23:08:34) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(23:08:35) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1427704705 --lang=en-US --os windows
(23:08:35) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1427704705 --lang=en-US --os windows
(23:08:35) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1427704705 --lang=en-US --os windows
(23:08:35) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1427704705 --lang=en-US --os windows
(23:08:36) ERROR:   [ExtraGameInfo]:    Was not able to get PCGamingWiki data for Act of War High Treason Error: connect ECONNREFUSED 2606:4700:3032::6815:1b2:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
(23:08:36) ERROR:   [ExtraGameInfo]:    Was not able to get PCGamingWiki data for Act of War High Treason Error: connect ECONNREFUSED 2606:4700:3032::6815:1b2:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
(23:08:48) WARNING: [Gog]:              Failed to get Install Info for 1427704705 using windows as platform, returning empty object
(23:08:48) WARNING: [Gog]:              Failed to get Install Info for 1427704705 using windows as platform, returning empty object
(23:08:50) WARNING: [Gog]:              Failed to get Install Info for 1427704705 using windows as platform, returning empty object
(23:09:43) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Agarest Generations of War Zero
(23:09:43) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Agarest Generations of War Zero
(23:09:43) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Agarest Generations of War Zero
(23:09:43) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Agarest Generations of War Zero
(23:09:43) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(23:09:43) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Agarest Generations of War Zero
(23:09:43) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Agarest Generations of War Zero
(23:09:43) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Agarest Generations of War Zero
(23:09:43) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Agarest Generations of War Zero
(23:09:43) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(23:09:43) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(23:09:43) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(23:09:44) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1426762679 --lang=en-US --os windows
(23:09:44) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1426762679 --lang=en-US --os windows
(23:09:44) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1426762679 --lang=en-US --os windows
(23:09:44) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1426762679 --lang=en-US --os windows
(23:09:44) ERROR:   [ExtraGameInfo]:    Was not able to get PCGamingWiki data for Agarest Generations of War Zero Error: connect ECONNREFUSED 2606:4700:3033::ac43:81ae:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
(23:09:44) ERROR:   [ExtraGameInfo]:    Was not able to get PCGamingWiki data for Agarest Generations of War Zero Error: connect ECONNREFUSED 2606:4700:3032::6815:1b2:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
(23:09:48) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1334130696
(23:09:57) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1674992368
(23:09:59) WARNING: [Gog]:              Failed to get Install Info for 1426762679 using windows as platform, returning empty object
```

### Steps to reproduce

1. Go to 'Library
2. Double click on the game you want
3. just wait for long time

### Expected behavior

on previous version. it loads pretty fast especially on homepage and game page. But, I know you changed lots of things on GOG side. So, I hope it can be resolved

### Heroic Version

Latest Stable

### System Information

- OS: SteamOS & ubuntu

### Additional information

thanks to this bug, I need to downgrade the app with flatpak mask. I hope it will be resolved soon. 
BTW, I haven't checked on Windows/macOS. But, I think there are some impacts on other OSes.

**Comment by Nocccer** [comment]
Looks like something with extragameinfo.
Will look at it at the weekend

Btw be more friendly, we do this without getting paid and in our freetime. I also would not blame you if you give me free cake which taste terrible.

**Comment by Nocccer** [comment]
Something with your connection is wrong:
`connect ECONNREFUSED 2606:4700:3032::6815:1b2:443`somehow your ip address is refused. Could be firewall or because you using ipv6.

**Comment by dtantono** [comment]
I have no firewall at all

**Comment by flavioislima** [comment]
Closing due to inactivity
