### ISSUE TITLE
Display/machine goes to sleep on KDE Plasma while playing a game

### ISSUE THREAD

**Issue by Yasand123** [Heroic-Games-Launcher/HeroicGamesLauncher#2644]
### Describe the bug

This feature has never worked for me at all. I've followed the development on it and I've been testing as new versions get released but so far it has not worked for me. I always need to manually block sleep and screenlocking on KDE Plasma.

This isn't a version specific issue afaik, it's always been like this.

### Add logs

```text
(00:34:10) INFO:    [Connection]:       Connectivity: check-online
(00:34:10) INFO:    [Connection]:       Pinging external endpoints
(00:34:10) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(00:34:10) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(00:34:10) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(00:34:10) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(00:34:10) WARNING: [Backend]:          Protocol already registered.
(00:34:10) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jina/.config/heroic/gog_store/auth.json --version
(00:34:11) INFO:    [Backend]:          Loading Screen Ready
(00:34:11) INFO:    [Frontend]:         Refreshing Library
(00:34:11) INFO:    [Legendary]:        Refreshing library...
(00:34:11) INFO:    [Legendary]:        Found 0 games to update
(00:34:11) INFO:    [Backend]:          Frontend Ready
(00:34:11) INFO:    [Backend]:          Checking for new Heroic Updates
(00:34:11) INFO:    [Backend]:          Checking for current version changelog
(00:34:11) INFO:    [Backend]:          

Heroic Version: 2.7.0 Eustass Kid
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.1

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: Arch KERNEL: 6.2.10-arch1-1 ARCH: x64
CPU: AMD Ryzen 7 3700X 8-Core Processor @3.6 GOVERNOR: performance
RAM: Total: 15.53 GiB Available: 8.92 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 2060 SUPER VRAM: 7966MB DRIVER: 530.41.03
PROTOCOL: x11

(00:34:12) INFO:    [Connection]:       Connectivity: online
(00:34:12) INFO:    [Gog]:              Getting data about the user
(00:34:12) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jina/.config/heroic/gog_store/auth.json auth
(00:34:13) INFO:    [Winetricks]:       Downloading Winetricks
(00:34:14) WARNING: [Winetricks]:       Error Downloading Winetricks Error: timeout of 1000ms exceeded
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/opt/Heroic/resources/app.asar/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
(00:34:16) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(00:34:16) INFO:    [Backend]:          Starting the Download Queue
(00:34:16) INFO:    [Gog]:              Saved user data to config
(00:34:17) INFO:    [Backend]:          Launching Kingdom Hearts III (reDuh1DEPNo6n1YTdTi1Uv)
(00:34:17) INFO:    [Backend]:          Preventing display from sleep
(00:34:17) INFO:    [Backend]:          Checking if wine version exists: Proton - GE-Proton7-50
(00:34:17) INFO:    [Backend]:          Preventing machine to sleep
(00:34:24) INFO:    [Backend]:          launching non-native sideloaded: /home/jina/.games/Kingdom Hearts III and Re-Mind/KINGDOM HEARTS III/Binaries/Win64/KINGDOM HEARTS III.exe}
(00:34:24) INFO:    [Backend]:          Checking if wine version exists: Proton - GE-Proton7-50
(00:34:24) DEBUG:   [Backend]:          Running Wine command: run /home/jina/.games/Kingdom Hearts III and Re-Mind/KINGDOM HEARTS III/Binaries/Win64/KINGDOM HEARTS III.exe 
(00:34:24) DEBUG:   [Backend]:          Logging to file "/home/jina/.config/heroic/GamesConfig/reDuh1DEPNo6n1YTdTi1Uv-lastPlay.log"
(00:34:24) INFO:    [Backend]:          Stopping Power Saver Blocker
(00:35:11) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(00:35:11) INFO:    [Frontend]:         Refreshing Library
(00:35:11) INFO:    [Legendary]:        Refreshing library...
(00:35:11) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jina/.config/heroic/gog_store/auth.json auth
(00:35:11) INFO:    [Legendary]:        Game list updated, got 149 games & DLCs
(00:35:11) INFO:    [Gog]:              Getting GOG library
(00:35:15) INFO:    [Gog]:              Number of library pages: 1
(00:35:15) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jina/.config/heroic/gog_store/auth.json auth
(00:35:16) INFO:    [Gog]:              Saved games data
(00:35:17) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1980301910
```

### Steps to reproduce

1. Open launcher
2. Run a game
3. Wait for 5 minutes
4. Display goes to sleep

### Expected behavior

Should stay awake during gameplay

### Heroic Version

Latest Stable

### System Information

- OS: Linux ArchLinux 6.2.10-arch1-1

**Comment by msdobrescu** [comment]
I have the same issue. As a note, playing with the keyboard will keep the system in "activity mode", but using a console will let it go in sleep or, at least, power save, which turns off the monitor. I have a Logitech controller.

**Comment by aprice-dev** [comment]
I've been experiencing this same issue on KDE X11 using the Flatpak version of Heroic and playing with a controller. Sounds like it's been an outstanding bug in KDE since 2013 so I wouldn't hold my breath on it getting fixed from that end.

[KDE Bug 328987](https://bugs.kde.org/show_bug.cgi?id=328987)

Some comments on the KDE bug ticket mention using the `gamemoderun` wrapper as a workaround. Not sure if it's viable in Flatpak or for Heroic, but it would be great to see a workaround for this.

**Comment by thingsiplay** [comment]
Endeavour OS. Plasma 6 on Wayland (AMD+AMD hardware). Native Steam.

I'm here after PC going to sleep while I was playing Resident Evil 2. After coming back ingame controller was not working anymore and fps was down to 15 (from 120) and I died. 

Strange enough I played Zelda for 130 hours since months on an emulator and this never happened once, but as soon as I played RE2 on Steam, this happened after an hour or so (Sleep after period of inactivity). Maybe an issue with Steam and not KDE?

**Comment by Bobthesuperman296** [comment]
Every time I try to open fall guys it gives me an error that says "Game folder appears to be deleted, do you want to remove the game from the installed list?" I say yes and nothing happens. Then I try uninstalling it and nothing happens, please fix it/help me.

**Comment by thingsiplay** [comment]
@Bobthesuperman296 Please create a new issue. This has nothing todo with the issue in this thread.

**Comment by Bobthesuperman296** [comment]
sry
