### ISSUE TITLE
Rocket League not launching after update

### ISSUE THREAD

**Issue by jake4jake4** [Heroic-Games-Launcher/HeroicGamesLauncher#2652]
### Describe the bug

Not getting a response on discord (apologies). RL wont launch after update - any help is appreciated.

### Add logs

```text
(19:31:33) INFO:    [Connection]:       Connectivity: check-online
(19:31:33) INFO:    [Connection]:       Pinging external endpoints
(19:31:33) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(19:31:33) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(19:31:33) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(19:31:33) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(19:31:33) WARNING: [Backend]:          Failed to register protocol with OS.
(19:31:33) INFO:    [Connection]:       Connectivity: online
(19:31:33) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(19:31:34) INFO:    [Backend]:          Loading Screen Ready
(19:31:34) INFO:    [Frontend]:         Refreshing Library
(19:31:34) INFO:    [Legendary]:        Refreshing library...
(19:31:34) INFO:    [Legendary]:        Refreshing Epic Games...
(19:31:34) DEBUG:   [Legendary]:        Update is available for Fortnite: ++Fortnite+Release-24.20-CL-25058254-Windows != ++Fortnite+Release-24.20-CL-25156858-Windows
(19:31:34) INFO:    [Legendary]:        Found 1 game to update
(19:31:34) INFO:    [Legendary]:        Game list updated, got 4 games & DLCs
(19:31:34) INFO:    [Gog]:              Found 0 game(s) to update
(19:31:34) INFO:    [Backend]:          Frontend Ready
(19:31:34) INFO:    [Backend]:          

Heroic Version: 2.7.0 Eustass Kid
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.1

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: Freedesktop SDK KERNEL: 5.13.0-valve36-1-neptune ARCH: x64
CPU: AMD Custom APU 0405 @2.15 GOVERNOR: schedutil
RAM: Total: 14.47 GiB Available: 11.81 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB 
PROTOCOL: x11

(19:31:34) INFO:    [Backend]:          Checking for current version changelog
(19:31:34) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(19:31:35) INFO:    [Winetricks]:       Downloading Winetricks
(19:31:36) WARNING: [Winetricks]:       Error Downloading Winetricks Error: timeout of 1000ms exceeded
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/app/bin/heroic/resources/app.asar/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
(19:31:37) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/home/deck/Games/Heroic/Prefixes/Rocket League/pfx"
(19:31:37) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Rocket League
(19:31:37) DEBUG:   [Legendary]:        Using cached install info
(19:31:37) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Rocket League
(19:31:37) DEBUG:   [Legendary]:        Using cached install info
(19:31:37) DEBUG:   [Legendary]:        Using cached install info
(19:31:37) INFO:    [Legendary]:        Abort command "/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/home/deck/Games/Heroic/Prefixes/Rocket League/pfx""
(19:31:39) INFO:    [Backend]:          Starting the Download Queue
(19:31:40) DEBUG:   [Legendary]:        Using cached install info
(19:32:56) DEBUG:   [Legendary]:        Using cached install info
(19:33:42) WARNING: [Backend]:          Failed download of AreWeAntiCheatYet data: Error: connect ETIMEDOUT 2606:50c0:8001::154:443
(19:33:48) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:33:48) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:33:48) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:33:48) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:35:59) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(19:35:59) INFO:    [Backend]:          Preventing display from sleep
(19:35:59) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(19:35:59) INFO:    [Backend]:          Preventing machine to sleep
(19:35:59) DEBUG:   [Legendary]:        Using cached install info
(19:35:59) DEBUG:   [Legendary]:        Using cached install info
(19:36:00) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(19:36:00) WARNING: [Backend]:          You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(19:36:00) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(19:36:00) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(19:36:00) DEBUG:   [Backend]:          Running Wine command: run wineboot --init
(19:36:02) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --json --offline
(19:36:02) INFO:    [Backend]:          Stopping Power Saver Blocker
(19:36:02) DEBUG:   [Legendary]:        Using cached install info
(19:36:02) DEBUG:   [Legendary]:        Using cached install info
(19:36:02) INFO:    [Legendary]:        Launching Rocket League®: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH="/home/deck/Games/Heroic/Prefixes/Rocket League" PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-rocketleague PROTON_LOG_DIR=/home/deck/.var/app/com.heroicgameslauncher.hgl /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --language en --no-wine --wrapper "'/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton' run"
(19:36:07) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(19:36:07) INFO:    [Frontend]:         Refreshing Library
(19:36:07) INFO:    [Legendary]:        Refreshing library...
(19:36:07) INFO:    [Legendary]:        Game list updated, got 4 games & DLCs
(19:36:07) DEBUG:   [Legendary]:        Using cached install info
(19:36:07) DEBUG:   [Legendary]:        Using cached install info
(19:36:53) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(19:36:53) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(19:38:11) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:38:11) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:38:13) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:38:13) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:38:20) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:38:20) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:43:58) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/home/deck/Games/Heroic/Prefixes/Rocket League/pfx"
(19:43:58) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Rocket League
(19:43:58) DEBUG:   [Legendary]:        Using cached install info
(19:43:58) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Rocket League
(19:43:58) DEBUG:   [Legendary]:        Using cached install info
(19:43:58) DEBUG:   [Legendary]:        Using cached install info
(19:43:59) INFO:    [Legendary]:        Abort command "/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/home/deck/Games/Heroic/Prefixes/Rocket League/pfx""
(19:44:00) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(19:44:00) INFO:    [Backend]:          Preventing display from sleep
(19:44:00) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(19:44:00) DEBUG:   [Legendary]:        Using cached install info
(19:44:00) DEBUG:   [Legendary]:        Using cached install info
(19:44:00) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(19:44:00) WARNING: [Backend]:          You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(19:44:00) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(19:44:00) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(19:44:00) DEBUG:   [Backend]:          Running Wine command: run wineboot --init
(19:44:02) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --json --offline
(19:44:03) INFO:    [Backend]:          Stopping Power Saver Blocker
(19:44:03) DEBUG:   [Legendary]:        Using cached install info
(19:44:03) DEBUG:   [Legendary]:        Using cached install info
(19:44:03) INFO:    [Legendary]:        Launching Rocket League®: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH="/home/deck/Games/Heroic/Prefixes/Rocket League" PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-rocketleague PROTON_LOG_DIR=/home/deck/.var/app/com.heroicgameslauncher.hgl /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --language en --no-wine --wrapper "'/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton' run"
(19:44:08) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(19:44:08) INFO:    [Frontend]:         Refreshing Library
(19:44:08) INFO:    [Legendary]:        Refreshing library...
(19:44:08) INFO:    [Legendary]:        Game list updated, got 4 games & DLCs
(19:44:08) DEBUG:   [Legendary]:        Using cached install info
(19:44:08) DEBUG:   [Legendary]:        Using cached install info
(19:44:08) DEBUG:   [Legendary]:        Using cached install info
(19:44:08) DEBUG:   [Legendary]:        Using cached install info
(19:46:10) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:46:10) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:46:10) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:46:10) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:46:12) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:46:12) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:46:14) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:46:14) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:46:19) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:46:19) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:46:19) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:46:19) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:47:17) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/home/deck/Games/Heroic/Prefixes/Rocket League/pfx"
(19:47:17) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Rocket League
(19:47:17) DEBUG:   [Legendary]:        Using cached install info
(19:47:17) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Rocket League
(19:47:17) DEBUG:   [Legendary]:        Using cached install info
(19:47:17) DEBUG:   [Legendary]:        Using cached install info
(19:47:17) INFO:    [Legendary]:        Abort command "/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/home/deck/Games/Heroic/Prefixes/Rocket League/pfx""
(19:47:18) INFO:    [Backend]:          Launching Rocket League® (Sugar)
(19:47:18) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(19:47:18) DEBUG:   [Legendary]:        Using cached install info
(19:47:18) DEBUG:   [Legendary]:        Using cached install info
(19:47:18) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(19:47:18) WARNING: [Backend]:          You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(19:47:18) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(19:47:18) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(19:47:18) DEBUG:   [Backend]:          Running Wine command: run wineboot --init
(19:47:20) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --json --offline
(19:47:20) INFO:    [Backend]:          Stopping Power Saver Blocker
(19:47:20) DEBUG:   [Legendary]:        Using cached install info
(19:47:20) DEBUG:   [Legendary]:        Using cached install info
(19:47:21) INFO:    [Legendary]:        Launching Rocket League®: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH="/home/deck/Games/Heroic/Prefixes/Rocket League" PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-rocketleague PROTON_LOG_DIR=/home/deck/.var/app/com.heroicgameslauncher.hgl /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --language en --no-wine --wrapper "'/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton' run"
(19:47:25) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(19:47:25) INFO:    [Frontend]:         Refreshing Library
(19:47:25) INFO:    [Legendary]:        Refreshing library...
(19:47:25) INFO:    [Legendary]:        Game list updated, got 4 games & DLCs
(19:47:25) DEBUG:   [Legendary]:        Using cached install info
(19:47:25) DEBUG:   [Legendary]:        Using cached install info
(19:47:25) DEBUG:   [Legendary]:        Using cached install info
(19:47:25) DEBUG:   [Legendary]:        Using cached install info
(19:49:28) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:49:28) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:49:29) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:49:29) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:49:29) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:49:29) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:49:32) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:49:32) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:49:37) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:49:37) ERROR:   [Legendary]:        Error Getting Info from Epic API
(19:49:37) ERROR:   [Legendary]:        TypeError: Cannot read properties of null (reading 'windows')
    at LegendaryGame.getExtraFromGraphql (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:263)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LegendaryGame.getExtraInfo (/app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:78:857)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.a23a7115.js:191:6905
    at async node:electron/js2c/browser_init:2:97893
(19:49:37) ERROR:   [Legendary]:        Error Getting Info from Epic API
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Game to launch

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]:

**Comment by flavioislima** [comment]
For help with games now working go to our Discord instead since it is easier to debug there 👍🏽
