### ISSUE TITLE
Legendary (Epic Games) Account Login bug

### ISSUE THREAD

**Issue by ghost** [Heroic-Games-Launcher/HeroicGamesLauncher#2707]
### Describe the bug

An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Logging in...
Traceback (most recent call last):File "legendary\cli.py", line 3069, in <module>
File "legendary\cli.py", line 2984, in main
File "legendary\cli.py", line 600, in launch_game
File "legendary\core.py", line 187, in login
ValueError: No saved credentials
[12000] Failed to execute script 'cli' due to unhandled exception!

Cannot launch the game and have to relogin everyday, the account is logged in in the `Stores` tab.

### Add logs

```text
(18:31:05) INFO:    [Legendary]:        Refreshing library...
(18:31:05) INFO:    [Legendary]:        Refreshing Epic Games...
(18:31:05) INFO:    [Connection]:       Connectivity: check-online
(18:31:05) INFO:    [Connection]:       Pinging external endpoints
(18:31:05) INFO:    [Legendary]:        Running command: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(18:31:05) INFO:    [Legendary]:        Legendary location: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(18:31:05) INFO:    [Gog]:              GOGDL location: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(18:31:05) INFO:    [Gog]:              GOGDL location: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(18:31:05) INFO:    [Legendary]:        Game list updated, got 140 games & DLCs
(18:31:05) WARNING: [Backend]:          Protocol already registered.
(18:31:06) INFO:    [Connection]:       Connectivity: online
(18:31:06) INFO:    [Gog]:              Running command: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\Soulmare\AppData\Roaming\heroic\gog_store\auth.json --version
(18:31:06) INFO:    [Legendary]:        Running command: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(18:31:06) INFO:    [Backend]:          Loading Screen Ready
(18:31:06) INFO:    [Frontend]:         Refreshing Library
(18:31:06) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(18:31:06) INFO:    [Gog]:              Found 0 game(s) to update
(18:31:06) INFO:    [Backend]:          Frontend Ready
(18:31:06) INFO:    [Legendary]:        Checking for game updates: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(18:31:07) INFO:    [Legendary]:        Found 0 games to update
(18:31:08) INFO:    [Backend]:          VCRuntime is installed
(18:31:10) WARNING: [Backend]:          Could not determine System Info
(18:31:11) INFO:    [Backend]:          Starting the Download Queue
(18:32:14) INFO:    [Backend]:          Launching Europa Universalis IV (da0103e959e54d139d0c109ded3b3672)
(18:32:14) INFO:    [Backend]:          Preventing display from sleep
(18:32:14) INFO:    [Legendary]:        Running command: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(18:32:14) INFO:    [Backend]:          Preventing machine to sleep
(18:32:14) INFO:    [Backend]:          Stopping Power Saver Blocker
(18:32:14) INFO:    [Gog]:              Running command: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\Soulmare\AppData\Roaming\heroic\gog_store\auth.json --version
(18:32:14) INFO:    [Backend]:          Started Discord Rich Presence
(18:32:14) INFO:    [Legendary]:        Running command: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch da0103e959e54d139d0c109ded3b3672 --json --offline
(18:32:14) INFO:    [Legendary]:        Launching Europa Universalis IV: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch da0103e959e54d139d0c109ded3b3672 --language en
(18:32:15) INFO:    [Backend]:          Stopped Discord Rich Presence
(18:32:15) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(18:32:15) INFO:    [Frontend]:         Refreshing Library
(18:32:15) INFO:    [Legendary]:        Refreshing library...
(18:32:19) WARNING: [Backend]:          Could not determine System Info
(18:32:23) INFO:    [Frontend]:         Refreshing Library
(18:32:23) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(18:32:23) INFO:    [Legendary]:        Refreshing library...
(18:32:24) INFO:    [Backend]:          Launching Europa Universalis IV (da0103e959e54d139d0c109ded3b3672)
(18:32:24) INFO:    [Backend]:          Preventing display from sleep
(18:32:24) INFO:    [Legendary]:        Running command: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(18:32:24) INFO:    [Backend]:          Stopping Power Saver Blocker
(18:32:24) INFO:    [Gog]:              Running command: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\Soulmare\AppData\Roaming\heroic\gog_store\auth.json --version
(18:32:24) INFO:    [Backend]:          Started Discord Rich Presence
(18:32:24) INFO:    [Legendary]:        Running command: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch da0103e959e54d139d0c109ded3b3672 --json --offline
(18:32:25) INFO:    [Legendary]:        Launching Europa Universalis IV: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch da0103e959e54d139d0c109ded3b3672 --language en
(18:32:25) INFO:    [Backend]:          Stopped Discord Rich Presence
(18:32:25) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(18:32:25) INFO:    [Frontend]:         Refreshing Library
(18:32:25) INFO:    [Legendary]:        Refreshing library...
(18:32:29) WARNING: [Backend]:          Could not determine System Info
(18:33:02) INFO:    [Backend]:          Launching Europa Universalis IV (da0103e959e54d139d0c109ded3b3672)
(18:33:02) INFO:    [Legendary]:        Running command: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(18:33:02) INFO:    [Backend]:          Stopping Power Saver Blocker
(18:33:03) INFO:    [Gog]:              Running command: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\Soulmare\AppData\Roaming\heroic\gog_store\auth.json --version
(18:33:03) INFO:    [Backend]:          Started Discord Rich Presence
(18:33:03) INFO:    [Legendary]:        Running command: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch da0103e959e54d139d0c109ded3b3672 --json --offline
(18:33:03) INFO:    [Legendary]:        Launching Europa Universalis IV: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch da0103e959e54d139d0c109ded3b3672 --language en
(18:33:03) INFO:    [Backend]:          Stopped Discord Rich Presence
(18:33:03) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(18:33:03) INFO:    [Frontend]:         Refreshing Library
(18:33:03) INFO:    [Legendary]:        Refreshing library...
(18:33:07) WARNING: [Backend]:          Could not determine System Info
(18:33:30) INFO:    [Backend]:          Launching Europa Universalis IV (da0103e959e54d139d0c109ded3b3672)
(18:33:30) INFO:    [Legendary]:        Running command: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(18:33:30) INFO:    [Backend]:          Stopping Power Saver Blocker
(18:33:30) INFO:    [Gog]:              Running command: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\Soulmare\AppData\Roaming\heroic\gog_store\auth.json --version
(18:33:30) INFO:    [Backend]:          Started Discord Rich Presence
(18:33:30) INFO:    [Legendary]:        Running command: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch da0103e959e54d139d0c109ded3b3672 --json --offline
(18:33:30) INFO:    [Legendary]:        Launching Europa Universalis IV: C:\Users\Soulmare\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch da0103e959e54d139d0c109ded3b3672 --language en
(18:33:31) INFO:    [Backend]:          Stopped Discord Rich Presence
(18:33:31) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(18:33:31) INFO:    [Frontend]:         Refreshing Library
(18:33:31) INFO:    [Legendary]:        Refreshing library...
(18:33:35) WARNING: [Backend]:          Could not determine System Info
```

### Steps to reproduce

1. Go to Library
2. Click on Launch game
3. Wait for error contents

### Expected behavior

Launch properly without having account bugs

### Screenshots

![Ovvqlz27](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/127675679/877851ed-8475-4727-9c7e-d3ddf4b52838)

### Heroic Version

Latest Stable

### System Information

- OS Windows

**Comment by ms178** [comment]
I also see this issue. I've found two workarounds so far: 1) re-compiling and re-installing my heroic PKGBUILD and 2) logging out of my EPIC account and re-add it. Both workarounds are not a permanent solution, after a day or so, the problem re-surfaces.

**Comment by sleeplessKomodo** [comment]
Also seeing this issue on 2.7.1 on linux (Fedora)

**Comment by Shished** [comment]
For me relogging fixes the problem until the next reboot.

**Comment by LithRakoon** [comment]
this bug is making heroic unusable for me, its super annoying to keep relogging eevery time i restart

**Comment by butterbutts** [comment]
I can't even get it to work by logging out and back in. I can't download or update any games at all.

**Comment by anat0lius** [comment]
Same bug in Linux

**Comment by Shished** [comment]
I think it also causes Heroic to generate multi-gigabyte log files. Check your installations, I found 5 and 15GB logs inside, they were generated within the last week.

**Comment by raifcoonjah** [comment]
> 

Can confirm, generated about 9.2GB here.

**Comment by MehdiLgithub** [comment]
am having the same problem on fedora 38 using the flatpak and the problem happens every time i open the app 
after logging out and back in it works until the system is shutdown then it happens the next time i boot the system

**Comment by arielj** [comment]
Is this still an issue with Heroic 2.11.0?

**Comment by arielj** [comment]
Closing as the last comment was mine in december last year and no new updates. I'll assume this got fixed.

We can reopen if not

**Comment by nidal-nijm-games** [comment]
I am on 2025 using my steam deck and this problem of the login still persists. I did even a factory reset on my steam deck and reinstalled heroic game launcher but still this login error and I can not install any games form my epic games store account. I am logged in.
