### ISSUE TITLE
Error regardling log in sessions occur when logging in to an Epic account.

### ISSUE THREAD

**Issue by daikaiser** [Heroic-Games-Launcher/HeroicGamesLauncher#2729]
### Describe the bug

Getting an error each time I launch the the Heroic Launcher, access my library or refresh my game list. The issue also occurs each time a game is launched.

### Add logs

```text
An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "legendary\cli.py", line 3069, in <module>File "legendary\cli.py", line 2980, in main
File "legendary\cli.py", line 206, in list_games
File "legendary\core.py", line 521, in get_non_asset_library_items
File "legendary\lfs\lgndry.py", line 232, in set_game_metaOSError: [Errno 22] Invalid argument: 'C:\\Users\\UrbanMech OS/.config/legendary\\metadata\\562d4a2c1b3147b089a7c453e3ddbcbe\t.json'
[4612] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Launch the Heroic Launcher
2. Log in to an Epic account
3. See error

### Expected behavior

Error does not occur

### Screenshots

![Untitled](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/9091604/45b9ec10-ef37-4592-9421-4594bd0a341d)

### Heroic Version

Latest Stable

### System Information

- OS : Windows 10

### Additional information

Logging out and then logging back in does not resolve the iisue.

**Comment by daikaiser** [comment]
Seems this a duplicate. Closing.
