### ISSUE TITLE
Heroic logs me out after every restart of the PC

### ISSUE THREAD

**Issue by Alikaname** [Heroic-Games-Launcher/HeroicGamesLauncher#2753]
### Describe the bug

error thrown by heroic when I click at an installed game to play:
```
An error has occurred! Try to Logout and Login on your Epic account.
Traceback (most recent call last):
File "legendary/cli.py", line 3061, in <module>File "legendary/cli.py", line 3000, in main
File "legendary/cli.py", line 1587, in info
File "legendary/api/egs.py", line 190, in get_user_entitlements
AttributeError: 'NoneType' object has no attribute 'get'
[2460] Failed to execute script 'cli' due to unhandled exception!
```

### Add logs

```text
(10:15:51) INFO:    [Legendary]:        Refreshing library...
(10:15:51) INFO:    [Legendary]:        Refreshing Epic Games...
(10:15:52) INFO:    [Connection]:       Connectivity: check-online
(10:15:52) INFO:    [Connection]:       Pinging external endpoints
(10:15:52) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(10:15:52) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(10:15:52) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(10:15:52) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(10:15:52) INFO:    [Legendary]:        Game list updated, got 303 games & DLCs
(10:15:52) WARNING: [Backend]:          Protocol already registered.
(10:15:52) INFO:    [Connection]:       Connectivity: online
(10:15:52) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/ali/.config/heroic/gog_store/auth.json --version
(10:15:52) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(10:15:52) INFO:    [Backend]:          

Heroic Version: 2.8.0 Nico Robin
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.2

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: EndeavourOS KERNEL: 6.3.5-arch1-1 ARCH: x64
CPU: AMD Ryzen 5 5600 6-Core Processor @3.68 GOVERNOR: schedutil
RAM: Total: 15.54 GiB Available: 12.83 GiB
GRAPHICS: GPU0: Navi 23 [Radeon RX 6600/6600 XT/6600M] VRAM: 1MB 
PROTOCOL: x11

(10:15:52) INFO:    [Backend]:          Loading Screen Ready
(10:15:52) INFO:    [Frontend]:         Refreshing undefined Library
(10:15:52) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(10:15:52) INFO:    [Gog]:              Found 0 game(s) to update
(10:15:52) INFO:    [Backend]:          Frontend Ready
(10:15:52) INFO:    [Backend]:          Checking for new Heroic Updates
(10:15:52) INFO:    [Backend]:          Checking for current version changelog
(10:15:52) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(10:15:52) INFO:    [Legendary]:        Checking for game updates: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(10:15:53) INFO:    [Legendary]:        Found 0 games to update
(10:15:54) INFO:    [Winetricks]:       Downloading Winetricks
(10:15:54) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Rising Storm 2 Vietnam
(10:15:54) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Rising Storm 2 Vietnam
(10:15:54) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Rising Storm 2 Vietnam
(10:15:54) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Rising Storm 2 Vietnam
(10:15:54) INFO:    [Legendary]:        Getting more details with 'legendary info'
(10:15:54) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Rising Storm 2 Vietnam
(10:15:54) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Rising Storm 2 Vietnam
(10:15:54) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Rising Storm 2 Vietnam
(10:15:54) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Rising Storm 2 Vietnam
(10:15:54) INFO:    [Legendary]:        Getting more details with 'legendary info'
(10:15:54) INFO:    [Legendary]:        Getting more details with 'legendary info'
(10:15:54) INFO:    [Legendary]:        Getting more details with 'legendary info'
(10:15:55) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Tern --platform Windows --json
(10:15:55) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Tern --platform Windows --json
(10:15:55) ERROR:   [Legendary]:        Error: Failed to parse install info for Tern with: SyntaxError: Unexpected end of JSON input
    at Module.getInstallInfo (/opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:98:3698)
    at async /opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:191:6407
    at async node:electron/js2c/browser_init:2:97893
(10:15:55) ERROR:   [Frontend]:         Cannot get game info
(10:15:55) ERROR:   [Frontend]:         Cannot get game info
(10:15:55) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Tern --platform Windows --json
(10:15:55) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Tern --platform Windows --json
(10:15:55) ERROR:   [Legendary]:        Error: Failed to parse install info for Tern with: SyntaxError: Unexpected end of JSON input
    at Module.getInstallInfo (/opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:98:3698)
    at async /opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:191:6407
    at async node:electron/js2c/browser_init:2:97893
(10:15:55) ERROR:   [Frontend]:         Cannot get game info
(10:15:55) ERROR:   [Frontend]:         Cannot get game info
(10:15:55) ERROR:   [Frontend]:         Cannot get game info
(10:15:55) ERROR:   [Frontend]:         Cannot get game info
(10:15:55) ERROR:   [Legendary]:        Error: Failed to parse install info for Tern with: SyntaxError: Unexpected end of JSON input
    at Module.getInstallInfo (/opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:98:3698)
    at async /opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:191:6407
    at async node:electron/js2c/browser_init:2:97893
(10:15:55) ERROR:   [Frontend]:         Cannot get game info
(10:15:55) ERROR:   [Frontend]:         Cannot get game info
(10:15:55) ERROR:   [Frontend]:         Cannot get game info
(10:15:55) ERROR:   [Legendary]:        Error: Failed to parse install info for Tern with: SyntaxError: Unexpected end of JSON input
    at Module.getInstallInfo (/opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:98:3698)
    at async /opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:191:6407
    at async node:electron/js2c/browser_init:2:97893
(10:15:55) ERROR:   [Frontend]:         Cannot get game info
(10:15:55) ERROR:   [Frontend]:         Cannot get game info
(10:15:55) ERROR:   [Frontend]:         Cannot get game info
(10:15:56) INFO:    [Legendary]:        Getting Info from Epic API
(10:15:56) ERROR:   [Frontend]:         Cannot get game info
(10:15:56) INFO:    [Legendary]:        Getting Info from Epic API
(10:15:56) ERROR:   [Frontend]:         Cannot get game info
(10:15:57) INFO:    [Backend]:          Starting the Download Queue
(10:15:58) ERROR:   [Frontend]:         Cannot get game info
(10:16:01) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix /home/ali/Games/Heroic/Prefixes/default
(10:16:01) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Batman Arkham City - Game of the Year Edition
(10:16:01) INFO:    [Legendary]:        Getting more details with 'legendary info'
(10:16:01) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Batman Arkham City - Game of the Year Edition
(10:16:01) INFO:    [Legendary]:        Getting more details with 'legendary info'
(10:16:01) INFO:    [Legendary]:        Getting more details with 'legendary info'
(10:16:01) INFO:    [Legendary]:        Abort command "/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix /home/ali/Games/Heroic/Prefixes/default"
(10:16:01) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Egret --platform Windows --json
(10:16:01) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Egret --platform Windows --json
(10:16:01) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Egret --platform Windows --json
(10:16:01) ERROR:   [Legendary]:        Error: Failed to parse install info for Egret with: SyntaxError: Unexpected end of JSON input
    at Module.getInstallInfo (/opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:98:3698)
    at async /opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:191:6407
    at async node:electron/js2c/browser_init:2:97893
(10:16:01) ERROR:   [Legendary]:        Error: Failed to parse install info for Egret with: SyntaxError: Unexpected end of JSON input
    at Module.getInstallInfo (/opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:98:3698)
    at async /opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:191:6407
    at async node:electron/js2c/browser_init:2:97893
(10:16:01) ERROR:   [Frontend]:         Cannot get game info
(10:16:01) ERROR:   [Frontend]:         Cannot get game info
(10:16:01) ERROR:   [Frontend]:         Cannot get game info
(10:16:01) ERROR:   [Legendary]:        Error: Failed to parse install info for Egret with: SyntaxError: Unexpected end of JSON input
    at Module.getInstallInfo (/opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:98:3698)
    at async /opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:191:6407
    at async node:electron/js2c/browser_init:2:97893
(10:16:01) ERROR:   [Frontend]:         Cannot get game info
(10:16:01) ERROR:   [Frontend]:         Cannot get game info
(10:16:01) ERROR:   [Frontend]:         Cannot get game info
(10:16:01) INFO:    [Legendary]:        Getting Info from Epic API
(10:16:02) ERROR:   [Frontend]:         Cannot get game info
(10:16:02) INFO:    [Legendary]:        Getting Info from Epic API
(10:16:02) ERROR:   [Frontend]:         Cannot get game info
(10:18:44) ERROR:   [Frontend]:         Cannot get game info
```

### Steps to reproduce

- open heroic after turning the PC
- click on a game
- see the error

### Expected behavior

this only happened recently, it used to work great without any issues

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/72041734/b4c0e005-de3f-4a35-846a-ad8e49888120)

### Heroic Version

Latest Stable

### System Information

- OS: EndeavourOS
- Heroic version : 2.8.0 (from the AUR)

**Comment by davidmartos96** [comment]
I'm also experiencing this issue, but for me it's been doing it for several months. 
I open the app and I get that error, so I need to sign in again. I'm using Google auth for Epic.

**Comment by 200433zc** [comment]
I've been having this problem since an update a few months ago
