### ISSUE TITLE
Can't update Proton-GE-latest due to permission issue

### ISSUE THREAD

**Issue by Jorma17** [Heroic-Games-Launcher/HeroicGamesLauncher#2784]
### Describe the bug

I use Proton-GE-latest to play games on Heroic. The version I was using was 8.3, but now 8.4 has come out. When I tried to update, the new Proton-GE version got downloaded properly, but then I got a notification that said "Installation failed!". I opened the app from the terminal to see the log and it seems like the file can't be unzipped to the correct location due to a permission issue. It says it has no access to the text file `~/.config/heroic/tools/proton/Proton-GE-latest/files/lib64/wine/nvapi/version` but it does have write access to it.

### Add logs

```text
DevTools listening on ws://127.0.0.1:9222/devtools/browser/f8ccfda2-d0d6-4659-952a-bfa8ad4b17de
(19:48:49) INFO:    [Legendary]:        Refreshing library...
(19:48:49) INFO:    [Legendary]:        Refreshing Epic Games...
(19:48:49) INFO:    [Connection]:       Connectivity: check-online
(19:48:49) INFO:    [Connection]:       Pinging external endpoints
ac_compute_device_uuid's output is based on invalid pci bus info.
(19:48:49) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(19:48:49) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(19:48:49) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(19:48:49) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(19:48:49) INFO:    [Legendary]:        Game list updated, got 1 games & DLCs
APPIMAGE env is not defined, current application is not an AppImage
(19:48:49) WARNING: [Backend]:          Protocol already registered.
(19:48:49) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/juuso/.config/heroic/gog_store/auth.json --version
(19:48:49) INFO:    [Connection]:       Connectivity: online
(19:48:49) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(19:48:49) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(19:48:50) INFO:    [Backend]:          

Heroic Version: 2.8.0 Nico Robin
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.2

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: EndeavourOS KERNEL: 6.3.6-arch1-1 ARCH: x64
CPU: Intel Core™ i5-3350P @3.1 GOVERNOR: schedutil
RAM: Total: 15.56 GiB Available: 13.6 GiB
GRAPHICS: GPU0: Cape Verde XT [Radeon HD 7770/8760 / R7 250X] VRAM: 256MB 
PROTOCOL: wayland

(19:48:50) INFO:    [Backend]:          Loading Screen Ready
(19:48:50) INFO:    [Frontend]:         Refreshing undefined Library
(19:48:50) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(19:48:50) INFO:    [Gog]:              Found 0 game(s) to update
(19:48:50) INFO:    [Backend]:          Frontend Ready
(19:48:50) INFO:    [Backend]:          Checking for new Heroic Updates
(19:48:50) INFO:    [Backend]:          Checking for current version changelog
(19:48:50) INFO:    [Legendary]:        Checking for game updates: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(19:48:51) INFO:    [Winetricks]:       Downloading Winetricks
(19:48:52) INFO:    [Legendary]:        Found 0 games to update
(19:48:55) INFO:    [Backend]:          Starting the Download Queue
[8322:0607/194920.156826:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[8322:0607/194928.538911:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[8322:0607/194931.334536:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
(19:49:33) INFO:    [WineDownloader]:   Start update of wine version Proton-GE-latest
(19:50:29) ERROR:   [WineDownloader]:   Error: Unzip of GE-Proton8-4.tar.gz failed with:
 Unzip of /home/juuso/.config/heroic/tools/proton/GE-Proton8-4.tar.gz failed with:
 tar: files/lib64/wine/nvapi/version: Cannot open: Permission denied
!
    at /opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:114:195
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installVersion (/opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:114:16)
    at async installWineVersion (/opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:115:1796)
    at async /opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:187:17426
    at async node:electron/js2c/browser_init:2:97893
^C(19:50:35) ERROR:   [Backend]:          TypeError: Object has been destroyed
(19:50:35) WARNING: [Backend]:          showDialogBoxModalAuto: TypeError: Object has been destroyed
    at sendFrontendMessage (/opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:1:3477)
    at showDialogBoxModalAuto (/opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:1:4352)
    at process.<anonymous> (/opt/Heroic/resources/app.asar/build/electron/main.53359e47.js:190:2697)
    at process.emit (node:events:525:35)
    at process._fatalException (node:internal/process/execution:149:25)
```

### Steps to reproduce

1. Open Heroic
2. Go to Wine manager and select the Proton-GE tab
3. Click the icon to update Proton-GE-latest
4. Wait for download
5. A notification pops up that says "Installation failed!"

### Expected behavior

1. Open Heroic
2. Go to Wine manager and select the Proton-GE tab
3. Click the icon to update Proton-GE-latest
4. Wait for download
5. After download, Proton-GE-latest will get unzipped and installed

### Heroic Version

Latest Stable

### System Information

- OS: EndeavourOS (KDE Plasma)
- Heroic version: stable (`heroic-games-launcher-bin` from the AUR)

**Comment by Nocccer** [comment]
What Happens If you so the unzip process manually outside of heroic?

**Comment by Jorma17** [comment]
Manually extracting the zip file seems to work. I also re-installed Proton-GE-latest and now it seems to work.

**Comment by Nocccer** [comment]
> Manually extracting the zip file seems to work. I also re-installed Proton-GE-latest and now it seems to work.

Year makes sense. Probably adding the `-p` to tar command coule fix this

**Comment by utajum** [comment]
had the same issue so i did `sudo chown myuser:myuser ~/.config/heroic/tools` and it got fixed
