### ISSUE TITLE
[Bug]: "Game not available" while trying to install a title from GOG

### ISSUE THREAD

**Issue by cl0ck-byte** [Heroic-Games-Launcher/HeroicGamesLauncher#2818]
### Describe the bug

If you try to install a game from GOG, it will stop installation at 0% with error message "Game not available", yet the play button appears as normal.

Upon clicking Play, this message appears:

> Game folder appears to be deleted, do you want to remove the game from the installed list?

### Add logs

```text
(15:34:02) INFO:    [Legendary]:        Refreshing library...
(15:34:02) INFO:    [Connection]:       Connectivity: check-online
(15:34:02) INFO:    [Connection]:       Pinging external endpoints
(15:34:02) INFO:    [Legendary]:        Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(15:34:03) INFO:    [Legendary]:        Legendary location: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(15:34:03) INFO:    [Gog]:              GOGDL location: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(15:34:03) INFO:    [Gog]:              GOGDL location: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(15:34:03) WARNING: [Backend]:          Protocol already registered.
(15:34:04) INFO:    [Connection]:       Connectivity: online
(15:34:04) INFO:    [Backend]:          User Not Found, removing it from Store
(15:34:04) INFO:    [Gog]:              Checking if login is valid
(15:34:04) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:34:04) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json --version
(15:34:05) INFO:    [Backend]:          VCRuntime is installed
(15:34:05) INFO:    [Backend]:          Loading Screen Ready
(15:34:05) INFO:    [Frontend]:         Refreshing undefined Library
(15:34:05) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:34:05) INFO:    [Gog]:              Found 0 game(s) to update
(15:34:05) INFO:    [Backend]:          Frontend Ready
(15:34:05) INFO:    [Backend]:          Checking for new Heroic Updates
(15:34:05) INFO:    [Backend]:          Checking for current version changelog
(15:34:05) INFO:    [Gog]:              Saved username to config file
(15:34:07) WARNING: [Backend]:          Could not determine System Info
(15:34:10) INFO:    [Backend]:          Starting the Download Queue
(15:34:15) INFO:    [Frontend]:         Refreshing all Library
(15:34:15) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:34:15) INFO:    [Gog]:              Found 0 game(s) to update
(15:34:21) INFO:    [Frontend]:         Refreshing all Library
(15:34:21) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:34:21) INFO:    [Gog]:              Found 0 game(s) to update
(15:34:54) INFO:    [Frontend]:         Refreshing all Library
(15:34:54) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:34:54) INFO:    [Gog]:              Found 0 game(s) to update
(15:35:03) INFO:    [Gog]:              Logging user out
(15:35:03) INFO:    [Backend]:          Checking for new Heroic Updates
(15:35:04) INFO:    [Backend]:          Checking for current version changelog
(15:36:13) INFO:    [Gog]:              Logging using GOG credentials
(15:36:13) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth --code <redacted>
(15:36:13) INFO:    [Gog]:              Login Successful
(15:36:13) INFO:    [Gog]:              Checking if login is valid
(15:36:13) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:36:14) INFO:    [Gog]:              Saved username to config file
(15:36:14) INFO:    [Frontend]:         Refreshing gog Library
(15:36:14) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:36:14) INFO:    [Gog]:              Getting GOG library
(15:36:15) INFO:    [Gog]:              Number of library pages: 1
(15:36:15) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:36:15) INFO:    [Gog]:              Saved games data
(15:36:15) INFO:    [Frontend]:         No cache found, getting data from gog...
(15:36:15) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:36:16) INFO:    [Gog]:              Getting GOG library
(15:36:16) INFO:    [Gog]:              Number of library pages: 1
(15:36:16) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:36:16) INFO:    [Gog]:              Saved games data
(15:36:20) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Prey
(15:36:20) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Prey
(15:36:20) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Prey
(15:36:20) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Prey
(15:36:20) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:36:20) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Prey
(15:36:20) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Prey
(15:36:20) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Prey
(15:36:20) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Prey
(15:36:20) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:36:20) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:36:20) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:36:21) ERROR:   [ExtraGameInfo]:    Was not able to get HowLongToBeat data for Prey Error: Error: Request failed with status code 403
    at HltbSearch.<anonymous> (C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(15:36:21) ERROR:   [ExtraGameInfo]:    Was not able to get HowLongToBeat data for Prey Error: Error: Request failed with status code 403
    at HltbSearch.<anonymous> (C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(15:36:21) INFO:    [Gog]:              Getting game metadata: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json info 1158493447 --token <redacted> --lang=en-US --os windows
(15:36:21) INFO:    [Gog]:              Getting game metadata: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json info 1158493447 --token <redacted> --lang=en-US --os windows
(15:36:21) INFO:    [Gog]:              Getting game metadata: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json info 1158493447 --token <redacted> --lang=en-US --os windows
(15:36:21) INFO:    [Gog]:              Getting game metadata: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json info 1158493447 --token <redacted> --lang=en-US --os windows
(15:36:22) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:36:22) INFO:    [Gog]:              Getting game metadata: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json info 1158493447 --token <redacted> --lang=en-US --os windows
(15:36:23) DEBUG:   [Backend]:          {"free":156754612224,"diskSize":899516723200,"message":"145.99 GiB / 837.74 GiB","validPath":true}
(15:36:25) DEBUG:   [Backend]:          {"free":156829601792,"diskSize":899516723200,"message":"146.06 GiB / 837.74 GiB","validPath":true}
(15:36:28) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:28) INFO:    [DownloadManager]:  Prey  was added to the download queue.
(15:36:28) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:36:28) INFO:    [Backend]:          Preventing machine to sleep
(15:36:28) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:28) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:28) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:28) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:29) INFO:    [Gog]:              Installing 1158493447: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json download 1158493447 --platform windows --path=C:\Users\Games\Heroic --token <redacted> --skip-dlcs --lang=en-US
(15:36:29) DEBUG:   [Gog]:              Logging to file "C:\Users\John\AppData\Roaming\heroic\GamesConfig\1158493447.log"
(15:36:30) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:30) INFO:    [Gog]:              Windows os, running setup instructions on install
(15:36:30) INFO:    [Backend]:          operation interrupted
(15:36:30) INFO:    [Gog]:              Setup: No instructions
(15:36:30) INFO:    [Backend]:          Adding shortcuts for Prey
(15:36:30) INFO:    [DownloadManager]:  Finished Installation of 1158493447
(15:36:30) INFO:    [DownloadManager]:  1158493447 added to download manager finished.
(15:36:30) INFO:    [DownloadManager]:  1158493447 removed from download manager.
(15:36:30) INFO:    [Frontend]:         Refreshing gog Library
(15:36:30) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:36:30) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:30) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:31) INFO:    [Gog]:              Getting GOG library
(15:36:31) INFO:    [Gog]:              Number of library pages: 1
(15:36:31) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:36:31) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Prey
(15:36:31) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:31) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Prey
(15:36:31) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:31) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:32) INFO:    [Gog]:              Saved games data
(15:36:32) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:32) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:32) INFO:    [Backend]:          Launching Prey (1158493447)
(15:36:32) INFO:    [Backend]:          Preventing display from sleep
(15:36:32) INFO:    [Legendary]:        Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(15:36:32) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(15:36:32) INFO:    [Backend]:          Preventing machine to sleep
(15:36:32) INFO:    [Backend]:          Stopping Power Saver Blocker
(15:36:32) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:32) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:32) INFO:    [Frontend]:         Refreshing gog Library
(15:36:32) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:36:32) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:32) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:32) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:32) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:33) INFO:    [Gog]:              Getting GOG library
(15:36:33) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json --version
(15:36:33) INFO:    [Gog]:              Number of library pages: 1
(15:36:33) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:36:35) INFO:    [Gog]:              Saved games data
(15:36:35) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:36:35) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:11) INFO:    [Backend]:          Launching Prey (1158493447)
(15:37:11) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(15:37:11) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:11) INFO:    [Backend]:          Stopping Power Saver Blocker
(15:37:11) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:11) INFO:    [Frontend]:         Refreshing gog Library
(15:37:11) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:37:11) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:11) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:11) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:11) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:11) INFO:    [Gog]:              Getting GOG library
(15:37:11) INFO:    [Gog]:              Number of library pages: 1
(15:37:11) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:37:12) INFO:    [Gog]:              Saved games data
(15:37:12) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:12) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:15) INFO:    [Backend]:          Launching Prey (1158493447)
(15:37:15) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(15:37:15) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:15) INFO:    [Backend]:          Stopping Power Saver Blocker
(15:37:15) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:15) INFO:    [Frontend]:         Refreshing gog Library
(15:37:15) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:37:15) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:15) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:15) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:15) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:16) INFO:    [Gog]:              Getting GOG library
(15:37:16) INFO:    [Gog]:              Number of library pages: 1
(15:37:16) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:37:17) INFO:    [Gog]:              Saved games data
(15:37:17) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:17) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:17) INFO:    [Backend]:          Launching Prey (1158493447)
(15:37:17) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(15:37:17) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:17) INFO:    [Backend]:          Stopping Power Saver Blocker
(15:37:17) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:17) INFO:    [Frontend]:         Refreshing gog Library
(15:37:17) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:37:17) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:17) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:17) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:17) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:18) INFO:    [Gog]:              Getting GOG library
(15:37:18) INFO:    [Backend]:          Launching Prey (1158493447)
(15:37:18) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(15:37:18) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:18) INFO:    [Backend]:          Stopping Power Saver Blocker
(15:37:18) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:18) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:18) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:18) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:18) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:18) INFO:    [Gog]:              Number of library pages: 1
(15:37:18) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:37:19) INFO:    [Gog]:              Saved games data
(15:37:19) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:19) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:19) INFO:    [Frontend]:         Refreshing gog Library
(15:37:19) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:37:19) INFO:    [Gog]:              Getting GOG library
(15:37:19) INFO:    [Gog]:              Number of library pages: 1
(15:37:19) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:37:20) INFO:    [Backend]:          Launching Prey (1158493447)
(15:37:20) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(15:37:20) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:20) INFO:    [Backend]:          Stopping Power Saver Blocker
(15:37:20) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:20) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:20) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:20) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:20) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:21) INFO:    [Gog]:              Saved games data
(15:37:21) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:21) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:21) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:21) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:22) DEBUG:   [Backend]:          {"free":156831940608,"diskSize":899516723200,"message":"146.06 GiB / 837.74 GiB","validPath":true}
(15:37:22) DEBUG:   [Backend]:          {"free":156832096256,"diskSize":899516723200,"message":"146.06 GiB / 837.74 GiB","validPath":true}
(15:37:29) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:29) INFO:    [DownloadManager]:  Prey  was added to the download queue.
(15:37:30) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:37:30) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:30) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:30) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:30) DEBUG:   [Backend]:          {"free":156816863232,"diskSize":899516723200,"message":"146.05 GiB / 837.74 GiB","validPath":true}
(15:37:30) INFO:    [Gog]:              Installing 1158493447: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json download 1158493447 --platform windows --path=C:\Users\Games\Prey --token <redacted> --skip-dlcs --lang=en-US
(15:37:30) DEBUG:   [Gog]:              Logging to file "C:\Users\John\AppData\Roaming\heroic\GamesConfig\1158493447.log"
(15:37:31) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:31) INFO:    [Gog]:              Windows os, running setup instructions on install
(15:37:31) INFO:    [Backend]:          operation interrupted
(15:37:31) INFO:    [Gog]:              Setup: No instructions
(15:37:31) INFO:    [Backend]:          Adding shortcuts for Prey
(15:37:31) INFO:    [DownloadManager]:  Finished Installation of 1158493447
(15:37:31) INFO:    [DownloadManager]:  1158493447 added to download manager finished.
(15:37:31) INFO:    [DownloadManager]:  1158493447 removed from download manager.
(15:37:31) INFO:    [Frontend]:         Refreshing gog Library
(15:37:31) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:37:32) INFO:    [Backend]:          Stopping Power Saver Blocker
(15:37:32) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:32) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:32) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:32) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:32) INFO:    [Gog]:              Getting GOG library
(15:37:32) INFO:    [Gog]:              Number of library pages: 1
(15:37:32) INFO:    [Gog]:              Running command: C:\Users\John\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\John\AppData\Roaming\heroic\gog_store\auth.json auth
(15:37:33) INFO:    [Gog]:              Saved games data
(15:37:33) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
(15:37:33) INFO:    [Gog]:              Got install info from cache for 1158493447 on windows platform
```

### Steps to reproduce

1. Launch Heroic
2. Go to your GOG library
3. Try installing any game
4. Launcher fails to do so

### Expected behavior

Game should be installed as normal.

### Heroic Version

Latest Stable

### System Information

- OS: Windows 10 22H2

**Comment by waltercool** [comment]
I can confirm this issue on Linux as well, all my GOG games have now a tag saying "Game is NOT installable"

**Comment by imLinguin** [comment]
@waltercool this seems unrelated to this issue

**Comment by arielj** [comment]
Closing, there's no activity since aug 2023. If it still happens we can reopen
