### ISSUE TITLE
All DOSbox games with a Linux installer fails to run

### ISSUE THREAD

**Issue by NightSprinter** [Heroic-Games-Launcher/HeroicGamesLauncher#2837]
### Describe the bug

Any DOSbox game from GoG that has a native Linux installer fails to run.

### Add logs

```text
Running Epic Pinball: The Complete Collection
Starting DOSBox
/home/deck/Games/Heroic/Epic Pinball/dosbox/dosbox_x86_64: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory
Done.
```

### Steps to reproduce

1. Go to game directory in terminal
2. CRun "sh start.sh
3. See error

### Expected behavior

Game runs

### Heroic Version

Latest Stable

### System Information

SteamOS 3.4.8/HoloISO

### Additional information

Removing the library export seems to fix this? need to install libpng12 on HoloISO

**Comment by mamama1** [comment]
err.. same here. even the same library?

**Comment by solomani** [comment]
Ditto.

**Comment by Lariaa** [comment]
We support native Dosbox with the next release https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3797
Does this fix your problem?

**Comment by Ulugbeg** [comment]
I run archlinux, I have updated to 2.15.1, and have dosbox installed. I tested 2 games, Bio Menace and Battle Chess, installed both as windows, but neither launches, both with the following error:

/home/redacted/Games/Heroic/Battle Chess/dosbox/dosbox_x86_64: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory

/home/redacted/Games/Heroic/Bio Menace/dosbox/dosbox_x86_64: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory

Would it be better if I file a different bug for this?

**Comment by imLinguin** [comment]
Currently it's best to run Windows versions of those games. With 2.15.0 you can have native dosbox staging installed on your machine and that will be used instead of Proton

**Comment by imLinguin** [comment]
Whole feature is now described on the Wiki https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/How-To:-DOSBOX-and-SCUMMVM

**Comment by mosteo** [comment]
Encountered this one with Sid Meier's Cover Action. The libs are there in `./dosbox/libs` though.

**Comment by lukebarone** [comment]
I'm encountering this with Bio Menace on elementaryOS. When I run the `./start.sh` script, the same output as above. I tried copying the library from a Snap app, and it lets the game launch through the script from the terminal, but not from the launcher.

**Comment by hifron** [comment]
With **native windows platform games**, dosbox.exe with entire DOSBOX dir missing IF NOT USING HEROIC FLATPAK, but other versions of HEROIC. Not good option to run installer and missing dosbox(exe) install with not runable game.

Linux installer is option, but often outdated and broken. Windows version is safe harbour. But not here(without flatpak repo).

```
apt-file search libFLAC.so
libflac-dev: /usr/lib/x86_64-linux-gnu/libFLAC.so
libflac12t64: /usr/lib/x86_64-linux-gnu/libFLAC.so.12
libflac12t64: /usr/lib/x86_64-linux-gnu/libFLAC.so.12.1.0

```
libFLAC.so.8 missing in **apt-file** look inside packages content...

something else https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4774

**Comment by hifron** [comment]
[1] Some games also requires .NET 4.8, but this problem sometime show up 

[2] after offline GOG game installer run with desktop shortcut windows link, but GOG has own dosbox config game runtime which should be run, but game exe missing(except shortcut), this is part of GOG dosbox scripts

[3] In offline installer there is not empty DOSBOX windows directory,

[1] but maybe another .NET 4.8 problem occurs(_not sure if this is GOG Redistribute installer because this is also [4]part of Windows UI,_ but probably not DOSBOX reqs but [5]game itself if this the problem thereafter)
__
summary is, that Heroic launcher miss installer part of DOSBOX directory inside game which then should make the game run if not shows then .NET 4.8 problem.

**Comment by hifron** [comment]
some of the windows problem gone by GOG updates, linux installer itself is more complicated as Steam shows, but Heroic now open possibility to game run and since GOG Publishing has not so high opinion on linux version of games, it is on opinion if this bug should be closed and how to approach Linux installers, but it should be GOG things also to consider and fix.... Now works for me for my problem, this bug not fully tested, it is also issuer thing to do close this if think so or how to approach Heroic integration with DOSBOX...

**Comment by DarthJMG2003** [comment]
I've managed to resolve this...

sudo apt install libflac8

even if it is installed, once you manage to execute, this should allow you to run your game with out no problem, at least for me it doesnt, i dont know if there are side effects.

Running on ubuntu 24.04.3 LTS which doesnt run out of the box my linux version of M1 Tank Platoon but should work with other games, I'm testing if this is the solution for more games that has dosbox for linux...

Also, I'm not using heroic, just executing the sh file installer as a program, then running the game and have the error the OP reported...

**Comment by ell1e** [comment]
For some reason, I can't run the Windows version of them either anymore, it complains DOSBOX is missing:

```
(02:45:58) [INFO]:    Game Output:

Traceback (most recent call last):

  File "<frozen runpy>", line 203, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/./gogdl/__main__.py", line 30, in <module>

    gogdl.cli.main()

    ~~~~~~~~~~~~~~^^

  File "/app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/./gogdl/gogdl/cli.py", line 70, in main

    function(arguments, unknown_args)

    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/./gogdl/gogdl/launch.py", line 108, in launch

    os.chdir(working_dir)

    ~~~~~~~~^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Games/Heroic/Lands Of Lore/DOSBOX'
```
I wonder if that's related or not?

**Comment by 4thguy** [comment]
The way to fix this natively is to locate the libFLAC.so itself on your system and symlink it inside the dosbox directory of the game installation in Heroic.

It's a bug with the GOG installers themselves in this case

**Comment by ell1e** [comment]
In case this was a response to my comment: are you saying it's trying to launch the Linux version in Proton while I'm launching the Windows install? If it wasn't a response to my comment then please ignore this question.

**Comment by 4thguy** [comment]
No, not  a reply to the your question. Just a (hopefully) helpful observation. Sorry about that.

In your case, are you sure that the filenames haven't changed or the files moved for some reason?

**Comment by imLinguin** [comment]
We noticed that some builds pre-dating GOG Galaxy 2.0 are not downloading dependencies properly. 
The solution will be to introduce proper v1 dependencies resolving in `heroic-gogdl`. It's planned for the next milestone
