### ISSUE TITLE
taiwanese error

### ISSUE THREAD

**Issue by endcommunist** [Heroic-Games-Launcher/HeroicGamesLauncher#2860]
### Describe the bug

taiwanese gbk'  cannot recognize illegal multibyte sequence

### Add logs

```text
An error has occurred! Try to Logout and Login on your Epic account.
Available games:
* Beyond Blue (App name: 3a0cae9455844390ad00505a704d641e | Version: 1.7.17766)
* Brave (App name: 4d44fcda3adf45baa6bbd818839ce4b7 | Version: brave-epic-5)
* Breathedge (App name: 0a20ccd3f1b3464da750a4dbf8c80d7c | Version: 1.0.1.1)
* Call of the Sea (App name: 6278dd278d714aeb88239a423fa0f8be | Version: 1.5.4.10)
* Century: Age of Ashes (App name: c40939566ad44585bde9302bdbe82734 | Version: 1.0.68595)
* Chess Ultra (App name: fc0b13b7b17b4a46933756fb2786cdc4 | Version: MWLocal_13)
* Death Stranding (App name: Boga | Version: 2742586.206.1)
* Death Stranding Content (App name: 5bf67f3153364181b54cb9e40ca7fa82 | Version: 1.01)
+ DEATH STRANDING DIGITAL SOUNDTRACK (App name: 84067e3ec8f149b2bbf2342d7a136065 | Version: 1.02)
+ HD Wallpaper (App name: f8bf1e29bbef480a9b28115ad0d644a0 | Version: 1.02)
+ SELECTIONS OF TITAN ART BOOK (App name: c311b22f878749449886949eeb588999 | Version: 1.01)
* Destiny 2 (App name: 592c359fb0e0413fb46dee2d24448eb4 | Version: 8547512)
* Diabotical (App name: Honeycreeper | Version: 0.20.471j)[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "legendary\cli.py", line 3069, in <module>
File "legendary\cli.py", line 2980, in main
File "legendary\cli.py", line 239, in list_games
UnicodeEncodeError: 'gbk' codec can't encode character '\xae' in position 13: illegal multibyte sequence
[11876] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. sign in a on a locale is taiwanese computer
2. go to library
3. wait

### Expected behavior

no error

### Heroic Version

Latest Stable

### System Information

- OS "win10"]:

### Additional information

no

**Comment by shadowoliver** [comment]
its 2.8.0

**Comment by shadowoliver** [comment]
![擷取](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/136224357/80b9f51f-e6e4-409b-b006-5b336e38e01d)

**Comment by arielj** [comment]
Is this still happening with Heroic 2.11.0? if so I'd suggest reporting the issue in Legendary's repo https://github.com/derrod/legendary since this has to be fixed in that project and not in Heroic.
