### ISSUE TITLE
`EOS Overlay` won't install on Windows 10 in version `2.9.1` of the `Heroic Games Launcher`.

### ISSUE THREAD

**Issue by Zliced13** [Heroic-Games-Launcher/HeroicGamesLauncher#2905]
### Describe the bug

When I try to install **EOS Overlay** via the **Heroic Games Launcher**, I always get the following error as seen in this log.

```log
An error has occurred! Try to Logout and Login on your Epic account.
Do you want to install the overlay? [Y/n]:[cli] INFO: Preparing to start overlay install...[Core] WARNING: Unable to download manifest from "download.epicgames.com" (status: 403), trying next URL...[Core] WARNING: Unable to download manifest from "download2.epicgames.com" (status: 403), trying next URL...[Core] WARNING: Unable to download manifest from "download3.epicgames.com" (status: 403), trying next URL...[Core] WARNING: Unable to download manifest from "download4.epicgames.com" (status: 403), trying next URL...[cli] INFO: Install directory: C:\Users\USER\AppData\Roaming\heroic\tools\eos_overlay
[cli] INFO: Install size: 330.82 MiB
[cli] INFO: Download size: 141.52 MiBTraceback (most recent call last):
File "legendary\cli.py", line 3069, in <module>File "legendary\cli.py", line 3018, in main
File "legendary\cli.py", line 2268, in manage_eos_overlay
File "legendary\utils\cli.py", line 4, in get_boolean_choice
EOFError: EOF when reading a line
[16356] Failed to execute script 'cli' due to unhandled exception!
```

### Add logs

```text
(20:25:00) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary --version
(20:25:00) INFO:    [Legendary]:        Legendary location: C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary
(20:25:00) INFO:    [Gog]:              GOGDL location: C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\gogdl
(20:25:00) INFO:    [Connection]:       Connectivity: check-online
(20:25:00) INFO:    [Connection]:       Pinging external endpoints
(20:25:00) INFO:    [Backend]:          DRM module staus {
  "neifaoindggfcjicffkgpmnlppeffabd": {
    "name": "Google Widevine Windows CDM",
    "status": "new",
    "version": "1.0.2512.0"
  },
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(20:25:00) WARNING: [Backend]:          Protocol already registered.
(20:25:00) INFO:    [Connection]:       Connectivity: online
(20:25:00) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(20:25:00) INFO:    [Gog]:              Running command: C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\USER\AppData\Roaming\heroic\gog_store\auth.json --version
(20:25:00) INFO:    [Backend]:          Loading Screen Ready
(20:25:00) INFO:    [Frontend]:         Refreshing undefined Library
(20:25:00) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(20:25:00) INFO:    [Legendary]:        Refreshing library...
(20:25:00) INFO:    [Legendary]:        Refreshing Epic Games...
(20:25:00) INFO:    [Legendary]:        Game list updated, got 20 games & DLCs
(20:25:00) INFO:    [Backend]:          Frontend Ready
(20:25:00) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(20:25:00) INFO:    [Gog]:              Found 0 game(s) to update
(20:25:00) INFO:    [Backend]:          Checking for new Heroic Updates
(20:25:00) INFO:    [Backend]:          Checking for current version changelog
(20:25:00) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\nile_config C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\nile --version
(20:25:00) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(20:25:00) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(20:25:02) INFO:    [Legendary]:        Found 0 games to update
(20:25:02) INFO:    [Backend]:          VCRuntime is installed
(20:25:05) WARNING: [Backend]:          Could not determine System Info
(20:25:05) INFO:    [Backend]:          Starting the Download Queue
(20:27:14) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary --version
(20:27:14) INFO:    [Gog]:              Running command: C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\USER\AppData\Roaming\heroic\gog_store\auth.json --version
(20:27:14) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\nile_config C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\nile --version
(20:27:14) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(20:27:15) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(20:27:17) INFO:    [Legendary]:        Getting EOS Overlay install size: XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay install --path C:\Users\USER\AppData\Roaming\heroic\tools\eos_overlay
(20:27:17) INFO:    [Backend]:          Preventing machine to sleep
(20:27:18) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay install --path C:\Users\USER\AppData\Roaming\heroic\tools\eos_overlay"
(20:35:50) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary --version
(20:35:50) INFO:    [Gog]:              Running command: C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\USER\AppData\Roaming\heroic\gog_store\auth.json --version
(20:35:50) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\nile_config C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\nile --version
(20:35:50) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(20:35:51) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(20:38:13) ERROR:   [Backend]:          Aborting not possible. Could not find a matching abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(20:38:15) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary --version
(20:38:15) INFO:    [Gog]:              Running command: C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\USER\AppData\Roaming\heroic\gog_store\auth.json --version
(20:38:15) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\nile_config C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\nile --version
(20:38:15) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(20:38:16) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(20:38:16) ERROR:   [Backend]:          Aborting not possible. Could not find a matching abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(20:38:16) ERROR:   [Backend]:          Aborting not possible. Could not find a matching abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(20:38:16) ERROR:   [Backend]:          Aborting not possible. Could not find a matching abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(20:38:16) ERROR:   [Backend]:          Aborting not possible. Could not find a matching abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(20:38:16) ERROR:   [Backend]:          Aborting not possible. Could not find a matching abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(20:38:17) ERROR:   [Backend]:          Aborting not possible. Could not find a matching abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(20:38:17) ERROR:   [Backend]:          Aborting not possible. Could not find a matching abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(20:38:17) ERROR:   [Backend]:          Aborting not possible. Could not find a matching abort controller for 98bc04bc842e4906993fd6d6644ffb8d
```

### Steps to reproduce

1. Open the Heroic Games Launcher
2. Click on the tab titled _**Settings**_
3. Under _**Settings**_ tab, click the sub-tab titled **_Advanced_**
4. Go to the section called **EOS Overlay**
5. Click the UI button titled, _Install_
6. Get an error log like the following below:

```log
An error has occurred! Try to Logout and Login on your Epic account.
Do you want to install the overlay? [Y/n]:[cli] INFO: Preparing to start overlay install...[Core] WARNING: Unable to download manifest from "download.epicgames.com" (status: 403), trying next URL...[Core] WARNING: Unable to download manifest from "download2.epicgames.com" (status: 403), trying next URL...[Core] WARNING: Unable to download manifest from "download3.epicgames.com" (status: 403), trying next URL...[Core] WARNING: Unable to download manifest from "download4.epicgames.com" (status: 403), trying next URL...[cli] INFO: Install directory: C:\Users\USER\AppData\Roaming\heroic\tools\eos_overlay
[cli] INFO: Install size: 330.82 MiB
[cli] INFO: Download size: 141.52 MiBTraceback (most recent call last):
File "legendary\cli.py", line 3069, in <module>File "legendary\cli.py", line 3018, in main
File "legendary\cli.py", line 2268, in manage_eos_overlay
File "legendary\utils\cli.py", line 4, in get_boolean_choice
EOFError: EOF when reading a line
[16356] Failed to execute script 'cli' due to unhandled exception!
```

### Expected behavior

**EOS Overlay** should've installed with little to no errors during the **EOS Overlay** installation process.

### Screenshots

![image_6](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/101912712/563bbb67-d0a1-469b-b40e-6da254223ba9)

### Heroic Version

Latest Stable

### System Information

```txt
USER@DESKTOP-101010
---------------------
OS: Windows 10 Home [64-bit]
Host: Micro-Star International Co., Ltd. MS-7D15
Kernel: 10.0.19045.0
Motherboard: Micro-Star International Co., Ltd. MAG B560 TORPEDO (MS-7D15)
Uptime: 50 minutes
Packages: 208 (scoop)
Shell: PowerShell v7.3.6
Resolution: 1920x1080
Terminal: Windows Terminal
CPU: 11th Gen Intel(R) Core(TM) i5-11600K @ 3.912GHz
GPU: NVIDIA GeForce GTX 1660
Memory: 8.94 GiB / 15.88 GiB (56%)
Disk (C:): 121 GiB / 232 GiB (52%)
```

**Comment by Zliced13** [comment]
Update, the problem persists even after updating to version `2.9.1`.

Error Log 1:
```log
Do you want to install the overlay? [Y/n]:[cli] INFO: Preparing to start overlay install...[Core] WARNING: Unable to download manifest from "download.epicgames.com" (status: 403), trying next URL...[Core] WARNING: Unable to download manifest from "download2.epicgames.com" (status: 403), trying next URL...[Core] WARNING: Unable to download manifest from "download3.epicgames.com" (status: 403), trying next URL...[Core] WARNING: Unable to download manifest from "download4.epicgames.com" (status: 403), trying next URL...[DLM] INFO: Found 0 missing files.[cli] INFO: Install directory: C:\Users\krist\AppData\Roaming\heroic\tools\eos_overlay
[cli] INFO: Install size: 330.82 MiB
[cli] INFO: Download size: 141.52 MiBTraceback (most recent call last):
File "legendary\cli.py", line 3137, in <module>File "legendary\cli.py", line 3086, in main
File "legendary\cli.py", line 2325, in manage_eos_overlayFile "legendary\utils\cli.py", line 4, in get_boolean_choice
EOFError: EOF when reading a line
[14456] Failed to execute script 'cli' due to unhandled exception!
```

Error Log 2:
```log
An error has occurred! Try to Logout and Login on your Epic account.
Do you want to install the overlay? [Y/n]:[cli] INFO: Preparing to start overlay install...[Core] WARNING: Unable to download manifest from "download.epicgames.com" (status: 403), trying next URL...[Core] WARNING: Unable to download manifest from "download2.epicgames.com" (status: 403), trying next URL...[Core] WARNING: Unable to download manifest from "download3.epicgames.com" (status: 403), trying next URL...[Core] WARNING: Unable to download manifest from "download4.epicgames.com" (status: 403), trying next URL...[DLM] INFO: Found 0 missing files.[cli] INFO: Install directory: C:\Users\krist\AppData\Roaming\heroic\tools\eos_overlay
[cli] INFO: Install size: 330.82 MiB
[cli] INFO: Download size: 141.52 MiBTraceback (most recent call last):
File "legendary\cli.py", line 3137, in <module>File "legendary\cli.py", line 3086, in main
File "legendary\cli.py", line 2325, in manage_eos_overlay
File "legendary\utils\cli.py", line 4, in get_boolean_choiceEOFError: EOF when reading a line
[9604] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by arielj** [comment]
what happens if you try to use legendary directly? from the error it looks like the urls where legendary is trying to download the installer are not working

**Comment by arielj** [comment]
I created a PR to fix this, as a workaround, until that's released, you can open a terminal and run `XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay install --path C:\Users\USER\AppData\Roaming\heroic\tools\eos_overlay`

**Comment by Zliced13** [comment]
@arielj Thank you responding to my issue.

**Comment by ThomasHineXYZ** [comment]
> you can open a terminal and run

Command Prompt:
```
'XDG_CONFIG_HOME' is not recognized as an internal or external command,
operable program or batch file.
```

Powershell Terminal:
```ps
XDG_CONFIG_HOME=C:\Users\thomas\AppData\Roaming\heroic\legendaryConfig : The term
'XDG_CONFIG_HOME=C:\Users\thomas\AppData\Roaming\heroic\legendaryConfig' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ XDG_CONFIG_HOME=C:\Users\thomas\AppData\Roaming\heroic\legendaryConfi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (XDG_CONFIG_HOME...legendaryConfig:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by Etaash-mathamsetty** [comment]
> I created a PR to fix this, as a workaround, until that's released, you can open a terminal and run `XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig C:\Users\USER\scoop\apps\heroic-games-launcher\2.8.0\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay install --path C:\Users\USER\AppData\Roaming\heroic\tools\eos_overlay`

that's not how you set environment variables on windows, and in fact there's no easy way to do it without adding it globally, which is pretty stupid

**Comment by Zliced13** [comment]
You can create an environmental variable using this PowerShell script:
```powershell
# If you want to set an environmental variable machine wide
[Environment]::SetEnvironmentVariable('<YOUR_VARIABLE>', "<A_VALUE>", [System.EnvironmentVariableTarget]::Machine)
```

```powershell
# If you want to set an environmental variable machine wide
[Environment]::SetEnvironmentVariable('<YOUR_VARIABLE>', "<A_VALUE>", [System.EnvironmentVariableTarget]::User)
```

**Comment by Etaash-mathamsetty** [comment]
> You can create an environmental variable using these PowerShell scripts:
> 
> ```powershell
> # If you want to set an environmental variable machine wide
> [Environment]::SetEnvironmentVariable('<YOUR_VARIABLE>', "<A_VALUE>", [System.EnvironmentVariableTarget]::Machine)
> ```
> 
> ```powershell
> # If you want to set an environmental variable for the current user
> [Environment]::SetEnvironmentVariable('<YOUR_VARIABLE>', "<A_VALUE>", [System.EnvironmentVariableTarget]::User)
> ```
> 
> @Etaash-mathamsetty

wow that's a pretty terrible way to implemen it, but thanks

**Comment by Zliced13** [comment]
Are you a Linux or macOS user?

**Comment by Zliced13** [comment]
Are Linux or macOS users also facing the same problem?

**Comment by Etaash-mathamsetty** [comment]
> Are you a Linux or macOS user?

yes


> Are Linux or macOS users also facing the same problem?

also yes

**Comment by ThomasHineXYZ** [comment]
> Are you a Linux or macOS user?

Also yes

> Are Linux or macOS users also facing the same problem?

and also yes.

I try to run software parity between OS's, so I am using Heroic on Windows. _Plus it makes it easy to do Amazon games on both Windows and Linux now that they added support for it_.

**Comment by mirobartovic** [comment]
I don't have any "scoop" folder and I couldn't find Legendary anywhere, so I just downloaded it from their GitHub, set the env. variable "XDG_CONFIG_HOME=C:\Users\USER\AppData\Roaming\heroic\legendaryConfig" (this can be done also in Advanced System Settings) and ran the "legendary eos-overlay install --path C:\Users\USER\AppData\Roaming\heroic\tools\eos_overlay" command. Of course I changed "USER" to my Windows username.

**Comment by ThomasHineXYZ** [comment]
Is there an approximate timeline of when this issue will be merged in, built, and released to users?

**Comment by felipecrs** [comment]
I am using Heroic 2.10 and I am facing the same problem:

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/29582865/f637d435-35ca-4a5c-a170-cb2cc103c700)

**Comment by felipecrs** [comment]
Please let me know if I should fill a separate issue.

**Comment by felipecrs** [comment]
Running from Powershell works fine though:

```
~ ❯ & "C:\Users\felip\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary.exe" eos-overlay install -y   21:05:27
[cli] INFO: Preparing to start overlay install...
[DLM] INFO: Found 0 missing files.
[cli] INFO: Install directory: C:\Users\felip\AppData\Roaming\heroic\tools\eos_overlay
[cli] INFO: Install size: 330.82 MiB
[cli] INFO: Download size: 141.52 MiB
[DLManager] INFO: Download Manager running with process-id: 15864
[DLManager] INFO: Starting download workers...
[DLManager] INFO: Starting file writing worker...
[DLManager] INFO: = Progress: 0.33% (13/3945), Running for 00:00:01, ETA: 00:05:06
[DLManager] INFO:  - Downloaded: 30.34 MiB, Written: 13.00 MiB
[DLManager] INFO:  - Cache usage: 91.00 MiB, active tasks: 32
[DLManager] INFO:  + Download   - 30.05 MiB/s (raw) / 71.31 MiB/s (decompressed)
[DLManager] INFO:  + Disk       - 12.88 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 8.97% (354/3945), Running for 00:00:02, ETA: 00:00:20
[DLManager] INFO:  - Downloaded: 80.02 MiB, Written: 21.55 MiB
[DLManager] INFO:  - Cache usage: 196.00 MiB, active tasks: 32
[DLManager] INFO:  + Download   - 49.27 MiB/s (raw) / 112.08 MiB/s (decompressed)
[DLManager] INFO:  + Disk       - 8.48 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 36.02% (1421/3945), Running for 00:00:03, ETA: 00:00:05
[DLManager] INFO:  - Downloaded: 128.32 MiB, Written: 25.26 MiB
[DLManager] INFO:  - Cache usage: 301.00 MiB, active tasks: 32
[DLManager] INFO:  + Download   - 47.94 MiB/s (raw) / 108.17 MiB/s (decompressed)
[DLManager] INFO:  + Disk       - 3.68 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 65.60% (2588/3945), Running for 00:00:04, ETA: 00:00:02
[DLManager] INFO:  - Downloaded: 141.52 MiB, Written: 31.01 MiB
[DLManager] INFO:  - Cache usage: 301.00 MiB, active tasks: 0
[DLManager] INFO:  + Download   - 13.09 MiB/s (raw) / 37.69 MiB/s (decompressed)
[DLManager] INFO:  + Disk       - 5.70 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 95.29% (3759/3945), Running for 00:00:05, ETA: 00:00:00
[DLManager] INFO:  - Downloaded: 141.52 MiB, Written: 211.10 MiB
[DLManager] INFO:  - Cache usage: 120.00 MiB, active tasks: 0
[DLManager] INFO:  + Download   - 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[DLManager] INFO:  + Disk       - 178.71 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 100.00% (3945/3945), Running for 00:00:06, ETA: 00:00:00
[DLManager] INFO:  - Downloaded: 141.52 MiB, Written: 330.82 MiB
[DLManager] INFO:  - Cache usage: 0.00 MiB, active tasks: 0
[DLManager] INFO:  + Download   - 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[DLManager] INFO:  + Disk       - 118.77 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: Waiting for installation to finish...
[DLManager] INFO: All done! Download manager quitting...
[cli] INFO: Finished downloading, setting up overlay...
[cli] INFO: Done.
```
