### ISSUE TITLE
opens with error installingdxvk and unable to login on heroic snap

### ISSUE THREAD

**Issue by exy11** [Heroic-Games-Launcher/HeroicGamesLauncher#2908]
### Describe the bug

ubuntu 22.04 lts fresh install
heroic snap
application opens with a dialog window stating 'error installing dxvk/vkd3d! please check your connection!'
then i am unable to login to my gog and epic accounts

### Add logs

```text
(13:38:01) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/henryd/snap/heroic/143/.config/heroic/legendaryConfig /snap/heroic/143/resources/app.asar.unpacked/build/bin/linux/legendary --version
(13:38:01) INFO:    [Legendary]:        Legendary location: /snap/heroic/143/resources/app.asar.unpacked/build/bin/linux/legendary
(13:38:01) INFO:    [Gog]:              GOGDL location: /snap/heroic/143/resources/app.asar.unpacked/build/bin/linux/gogdl
(13:38:01) INFO:    [Connection]:       Connectivity: check-online
(13:38:01) INFO:    [Connection]:       Pinging external endpoints
(13:38:01) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(13:38:02) WARNING: [Backend]:          Protocol already registered.
(13:38:02) INFO:    [Gog]:              Running command: /snap/heroic/143/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/henryd/snap/heroic/143/.config/heroic/gog_store/auth.json --version
(13:38:02) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/henryd/snap/heroic/143/.config/heroic/nile_config /snap/heroic/143/resources/app.asar.unpacked/build/bin/linux/nile --version
(13:38:02) INFO:    [Backend]:          

Heroic Version: 2.9.0 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 
Nile Version: 

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Ubuntu Core KERNEL: 5.19.0-50-generic ARCH: x64
CPU: Intel Core™ i5-1035G1 @1 GOVERNOR: powersave
RAM: Total: 11.24 GiB Available: 7.18 GiB
GRAPHICS: 
PROTOCOL: wayland

(13:38:02) INFO:    [Backend]:          Loading Screen Ready
(13:38:02) INFO:    [Backend]:          Frontend Ready
(13:38:02) INFO:    [Backend]:          Checking for new Heroic Updates
(13:38:02) INFO:    [Backend]:          Checking for current version changelog
(13:38:04) INFO:    [Connection]:       Connectivity: online
(13:38:04) INFO:    [Backend]:          User Not Found, removing it from Store
(13:38:04) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(13:38:04) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(13:38:04) WARNING: [DXVKInstaller]:    No GPU with Vulkan 1.1 support found, DXVK will not work
(13:38:04) INFO:    [Winetricks]:       Downloading Winetricks
(13:38:04) INFO:    [WineDownloader]:   Updating wine versions info
(13:38:04) INFO:    [WineDownloader]:   Fetching upstream information...
(13:38:05) WARNING: [Winetricks]:       Error Downloading Winetricks Error: timeout of 1000ms exceeded
    at createError (/snap/heroic/143/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/snap/heroic/143/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/snap/heroic/143/resources/app.asar/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
(13:38:07) INFO:    [Backend]:          Starting the Download Queue
(13:38:09) INFO:    [DXVKInstaller]:    Updating dxvk to: dxvk-2.2
(13:38:09) WARNING: [DXVKInstaller]:    Error when downloading dxvk Error: Command failed: curl -L https://github.com/doitsujin/dxvk/releases/download/v2.2/dxvk-2.2.tar.gz -o '/home/henryd/snap/heroic/143/.config/heroic/tools/dxvk/dxvk-2.2.tar.gz' --create-dirs
/bin/sh: 1: curl: not found

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12)
(13:38:09) INFO:    [DXVKInstaller]:    Updating vkd3d to: vkd3d-proton-2.9
(13:38:09) WARNING: [DXVKInstaller]:    Error when downloading vkd3d Error: Command failed: curl -L https://github.com/Heroic-Games-Launcher/vkd3d-proton/releases/download/v2.9/vkd3d-proton-2.9.tar.xz -o '/home/henryd/snap/heroic/143/.config/heroic/tools/vkd3d/vkd3d-proton-2.9.tar.xz' --create-dirs
/bin/sh: 1: curl: not found

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12)
(13:38:11) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(13:38:20) INFO:    [Gog]:              Logging using GOG credentials
(13:38:20) INFO:    [Gog]:              Running command: /snap/heroic/143/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/henryd/snap/heroic/143/.config/heroic/gog_store/auth.json auth --code <redacted>
(13:38:21) ERROR:   [Gog]:              GOG login failed to parse std output from gogdl. stdout: 
(13:38:25) INFO:    [Frontend]:         Refreshing undefined Library
(13:38:25) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(13:38:25) INFO:    [Legendary]:        Refreshing library...
(13:38:40) INFO:    [WineDownloader]:   wine versions updated
(13:38:40) INFO:    [WineDownloader]:   Start installation of wine version Wine-GE-Proton8-12
(13:38:42) INFO:    [Legendary]:        Logging in: XDG_CONFIG_HOME=/home/henryd/snap/heroic/143/.config/heroic/legendaryConfig /snap/heroic/143/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(13:38:42) INFO:    [Frontend]:         Refreshing legendary Library
(13:38:42) INFO:    [Legendary]:        Refreshing library...
(13:38:48) ERROR:   [WineDownloader]:   Error: Download of Wine-GE-Proton8-12 failed with:
 Download of https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-12/wine-lutris-GE-Proton8-12-x86_64.tar.xz failed with:
 spawn curl ENOENT!
    at /snap/heroic/143/resources/app.asar/build/electron/main.5229c6d1.js:116:326
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installVersion (/snap/heroic/143/resources/app.asar/build/electron/main.5229c6d1.js:116:166)
    at async installWineVersion (/snap/heroic/143/resources/app.asar/build/electron/main.5229c6d1.js:119:1796)
    at async downloadDefaultWine (/snap/heroic/143/resources/app.asar/build/electron/main.5229c6d1.js:141:461)
(13:40:02) INFO:    [Legendary]:        Logging in: XDG_CONFIG_HOME=/home/henryd/snap/heroic/143/.config/heroic/legendaryConfig /snap/heroic/143/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(13:40:02) INFO:    [Frontend]:         Refreshing legendary Library
(13:40:02) INFO:    [Legendary]:        Refreshing library...
```

### Steps to reproduce

install heroic snap onto a fresh install of ubuntu and try to login.

### Expected behavior

that dialog window does not appear and i am able to log into gog and epic properly.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]:ubuntu 22.04 lts

**Comment by imLinguin** [comment]
duplicate #2573
