### ISSUE TITLE
Nile thinks that installed.json is corrupt if no games installed

### ISSUE THREAD

**Issue by Dandraghas** [Heroic-Games-Launcher/HeroicGamesLauncher#2910]
### Describe the bug

if just login to amazon store account without games, and no games installed on machine, when restarting heroic it will try to read installed.json, but installed.json content is litterary:
```
null
```

legendary seems to have a protection from it, but nile not

i know it's just an error in logs it doesn't affect functionality, but still Nile should not handle games like that

also it seems like nile corretcly handling library.json it issue only with installed.json instead of writting empty json array it writes 'null'

### Add logs

```text
DevTools listening on ws://127.0.0.1:9222/devtools/browser/f06a2d56-35f6-40c4-92d8-32f736920af5
(18:27:46) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/Dandraghas/.config/heroic/legendaryConfig /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary --version
(18:27:46) INFO:    [Legendary]:        Legendary location: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary
(18:27:46) INFO:    [Gog]:              GOGDL location: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:27:46) INFO:    [Connection]:       Connectivity: check-online
(18:27:46) INFO:    [Connection]:       Pinging external endpoints
(18:27:47) INFO:    [Nile]:             Refreshing library...
(18:27:47) INFO:    [Nile]:             Refreshing Amazon Games...
(18:27:47) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/Dandraghas/.config/heroic/nile_config /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/nile library sync
(18:27:47) ERROR:   [Nile]:             Corrupted installed.json file, cannot load installed games TypeError: Cannot read properties of null (reading 'forEach')
    at refreshInstalled$1 (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.58df6dd8.js:91:6915)
    at refresh$2 (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.58df6dd8.js:91:7249)
    at initNileLibraryManager (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.58df6dd8.js:91:4454)
    at initStoreManagers (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.58df6dd8.js:94:12399)
(18:27:47) INFO:    [Nile]:             Game list updated, got 0 games
(18:27:47) INFO:    [Backend]:          DRM module staus {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2557.0'
  }
}
APPIMAGE env is not defined, current application is not an AppImage
(18:27:47) WARNING: [Backend]:          Protocol already registered.
(18:27:47) INFO:    [Gog]:              Running command: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/Dandraghas/.config/heroic/gog_store/auth.json --version
(18:27:47) INFO:    [Connection]:       Connectivity: online
(18:27:47) INFO:    [Gog]:              Checking if login is valid
(18:27:47) INFO:    [Gog]:              Running command: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/Dandraghas/.config/heroic/gog_store/auth.json auth
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
(18:27:47) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/Dandraghas/.config/heroic/nile_config /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/nile --version
(18:27:47) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(18:27:48) INFO:    [Backend]:          Loading Screen Ready
(18:27:48) INFO:    [Nile]:             Saved user data to config file
(18:27:48) INFO:    [Frontend]:         Refreshing undefined Library
(18:27:48) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(18:27:48) INFO:    [Gog]:              Running command: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/Dandraghas/.config/heroic/gog_store/auth.json auth
(18:27:48) INFO:    [Legendary]:        Refreshing library...
(18:27:48) INFO:    [Legendary]:        Refreshing Epic Games...
(18:27:48) INFO:    [Nile]:             Refreshing library...
(18:27:48) INFO:    [Nile]:             Refreshing Amazon Games...
(18:27:48) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/Dandraghas/.config/heroic/nile_config /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/nile library sync
(18:27:48) ERROR:   [Nile]:             Corrupted installed.json file, cannot load installed games TypeError: Cannot read properties of null (reading 'forEach')
    at refreshInstalled$1 (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.58df6dd8.js:91:6915)
    at Module.refresh$2 [as refresh] (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.58df6dd8.js:91:7249)
    at /usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.58df6dd8.js:191:9734
    at node:electron/js2c/browser_init:2:98410
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81923)
    at EventEmitter.emit (node:events:513:28)
(18:27:48) INFO:    [Nile]:             Game list updated, got 0 games
(18:27:48) INFO:    [Legendary]:        Game list updated, got 46 games & DLCs
(18:27:48) INFO:    [Backend]:          Frontend Ready
(18:27:48) INFO:    [Backend]:          Checking for new Heroic Updates
(18:27:48) INFO:    [Backend]:          Checking for current version changelog
(18:27:48) INFO:    [Gog]:              Getting GOG library
(18:27:48) INFO:    [Gog]:              Running command: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/Dandraghas/.config/heroic/gog_store/auth.json auth
(18:27:49) INFO:    [Gog]:              Saved username to config file
(18:27:49) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/Dandraghas/.config/heroic/legendaryConfig /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(18:27:49) INFO:    [Backend]:          

Heroic Version: 2.9.0 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Fedora Linux KERNEL: 6.4.4-200.fc38.x86_64 ARCH: x64
CPU: Intel Core™ i3-10100F @3.6 GOVERNOR: schedutil
RAM: Total: 15.52 GiB Available: 7.07 GiB
GRAPHICS: GPU0: NVIDIA GeForce GTX 1050 Ti VRAM: 4030MB DRIVER: 535.54.03
PROTOCOL: x11

(18:27:49) INFO:    [Gog]:              Saved games data
(18:27:49) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(18:27:49) INFO:    [Gog]:              Found 0 game(s) to update
(18:27:51) INFO:    [Winetricks]:       Downloading Winetricks
(18:27:51) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=/home/Dandraghas/.config/heroic/legendaryConfig /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(18:27:53) WARNING: [Legendary]:        Game with AppName 0a2d9f6403244d12969e11da6713137b is installed but was not found on account
(18:27:53) WARNING: [Legendary]:        Game with AppName 592c359fb0e0413fb46dee2d24448eb4 is installed but was not found on account
(18:27:53) WARNING: [Legendary]:        Game with AppName 963137e4c29d4c79a81323b8fab03a40 is installed but was not found on account
(18:27:53) DEBUG:   [Legendary]:        Update is available for Fortnite: ++Fortnite+Release-23.30-CL-23901854-Windows != ++Fortnite+Release-25.20-CL-26474516-Windows
(18:27:53) WARNING: [Legendary]:        Game with AppName Sugar is installed but was not found on account
(18:27:53) WARNING: [Legendary]:        Game with AppName Turtle is installed but was not found on account
(18:27:53) WARNING: [Legendary]:        Game with AppName a1e2ce30defe4a9187ebc14fc9d2bd8b is installed but was not found on account
(18:27:53) WARNING: [Legendary]:        Game with AppName a99769d95d8f400baad1f67ab5dfe508 is installed but was not found on account
(18:27:53) DEBUG:   [Legendary]:        Update is available for aafc587fbf654758802c8e41e4fb3255: 357.9.win != 358.7.win
(18:27:53) DEBUG:   [Legendary]:        Update is available for bcbc03d8812a44c18f41cf7d5f849265: 1.16.1-f3 != 1.17.1-f4-fixed
(18:27:53) INFO:    [Legendary]:        Found 3 games to update
(18:27:53) INFO:    [Nile]:             Looking for updates...
(18:27:53) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/Dandraghas/.config/heroic/nile_config /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json
(18:27:53) INFO:    [Backend]:          Starting the Download Queue
Error occurred in handler for 'checkGameUpdates': SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Module.listUpdateableGames$2 [as listUpdateableGames] (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.58df6dd8.js:91:6099)
    at async /usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.58df6dd8.js:191:3990
    at async node:electron/js2c/browser_init:2:98394
(18:27:53) ERROR:   [Frontend]:         Error: Error invoking remote method 'checkGameUpdates': SyntaxError: Unexpected end of JSON input
(18:27:53) INFO:    [Frontend]:         No cache found, getting data from nile...
(18:27:53) INFO:    [Nile]:             Refreshing library...
(18:27:53) INFO:    [Nile]:             Refreshing Amazon Games...
(18:27:53) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/Dandraghas/.config/heroic/nile_config /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/nile library sync
(18:27:53) ERROR:   [Nile]:             Corrupted installed.json file, cannot load installed games TypeError: Cannot read properties of null (reading 'forEach')
    at refreshInstalled$1 (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.58df6dd8.js:91:6915)
    at Module.refresh$2 [as refresh] (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.58df6dd8.js:91:7249)
    at /usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/electron/main.58df6dd8.js:191:9647
    at node:electron/js2c/browser_init:2:98410
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81923)
    at EventEmitter.emit (node:events:513:28)
(18:27:53) INFO:    [Nile]:             Game list updated, got 0 games
```

### Steps to reproduce

1. Login to amazon store account
2. Restart heroic
3. See that nile throws an error

### Expected behavior

Nile corretcly handle installed.json if no games installed

### Heroic Version

Latest Stable

### System Information

- OS Fedora

**Comment by imLinguin** [comment]
Fixed in 2.9.1 hotfix
