### ISSUE TITLE
Three dot menu issue

### ISSUE THREAD

**Issue by Francehelder** [Heroic-Games-Launcher/HeroicGamesLauncher#2915]
### Describe the bug

Three dot menu disappear most time a try click on Check Compatibility. 
It disappears even when the cursor is still over the menu.
It has necessary try many times to get this.
Move cursor on slow down to do this.

### Add logs

```text
(18:22:34) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary --version
(18:22:34) INFO:    [Legendary]:        Legendary location: /home/francehelder/Downloads/legendary
(18:22:34) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:22:34) INFO:    [Connection]:       Connectivity: check-online
(18:22:34) INFO:    [Connection]:       Pinging external endpoints
(18:22:34) INFO:    [Nile]:             Refreshing library...
(18:22:34) INFO:    [Nile]:             Refreshing Amazon Games...
(18:22:34) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(18:22:35) INFO:    [Nile]:             Game list updated, got 52 games
(18:22:35) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(18:22:37) WARNING: [Backend]:          Protocol already registered.
(18:22:38) INFO:    [Connection]:       Connectivity: online
(18:22:38) INFO:    [Gog]:              Checking if login is valid
(18:22:38) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:22:38) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json --version
(18:22:38) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(18:22:39) WARNING: [Backend]:          Could not determine System Info
(18:22:39) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(18:22:44) INFO:    [Winetricks]:       Downloading Winetricks
(18:22:45) INFO:    [Gog]:              Saved username to config file
(18:22:47) INFO:    [Backend]:          Loading Screen Ready
(18:22:48) INFO:    [Nile]:             Saved user data to config file
(18:22:48) INFO:    [Backend]:          Checking for new Heroic Updates
(18:22:49) INFO:    [Frontend]:         Refreshing undefined Library
(18:22:49) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(18:22:49) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:22:49) INFO:    [Legendary]:        Refreshing library...
(18:22:49) INFO:    [Legendary]:        Refreshing Epic Games...
(18:22:52) INFO:    [Nile]:             Refreshing library...
(18:22:52) INFO:    [Nile]:             Refreshing Amazon Games...
(18:22:52) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(18:22:53) INFO:    [Nile]:             Game list updated, got 52 games
(18:22:54) INFO:    [Legendary]:        Game list updated, got 243 games & DLCs
(18:22:54) INFO:    [Gog]:              Getting GOG library
(18:22:54) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:22:54) INFO:    [Backend]:          Frontend Ready
(18:22:54) INFO:    [Backend]:          Checking for current version changelog
(18:22:54) INFO:    [Frontend]:         Updated to a new version, cleaaning up the cache.
(18:22:55) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary cleanup
(18:22:59) INFO:    [Backend]:          Starting the Download Queue
(18:22:59) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary list --third-party
(18:25:10) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1396087560 undefined
(18:25:10) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1609928180 undefined
(18:25:14) INFO:    [Gog]:              Saved games data
(18:25:14) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(18:25:16) INFO:    [Gog]:              Found 0 game(s) to update
(18:25:16) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary list --third-party
(18:25:20) INFO:    [Legendary]:        Found 0 games to update
(18:25:20) INFO:    [Nile]:             Looking for updates...
(18:25:20) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json
(18:25:22) INFO:    [Frontend]:         No cache found, getting data from legendary...
(18:25:22) INFO:    [Legendary]:        Refreshing library...
(18:25:22) INFO:    [Legendary]:        Refreshing Epic Games...
(18:25:23) INFO:    [Legendary]:        Game list updated, got 243 games & DLCs
(18:25:23) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary list --third-party
(18:25:23) INFO:    [Frontend]:         No cache found, getting data from nile...
(18:25:23) INFO:    [Nile]:             Refreshing library...
(18:25:23) INFO:    [Nile]:             Refreshing Amazon Games...
(18:25:23) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(18:25:24) INFO:    [Nile]:             Game list updated, got 52 games
(18:31:11) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dont Starve
(18:31:11) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:31:11) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:31:11) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dont Starve
(18:31:11) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:31:11) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:31:12) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json info 1207659210 --token <redacted> --lang=en-US --os windows
(18:31:12) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json info 1207659210 --token <redacted> --lang=en-US --os windows
(18:31:12) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json info 1207659210 --token <redacted> --lang=en-US --os windows
(18:31:32) INFO:    [Backend]:          Changing Language to: en
(18:31:37) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dont Starve
(18:31:37) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:31:37) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:31:37) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dont Starve
(18:31:37) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:31:37) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:36:35) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Ascendant
(18:36:35) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:36:35) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:36:35) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Ascendant
(18:36:35) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:36:35) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:36:36) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json info 1207664543 --token <redacted> --lang=en-US --os windows
(18:36:36) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json info 1207664543 --token <redacted> --lang=en-US --os windows
(18:36:36) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json info 1207664543 --token <redacted> --lang=en-US --os windows
(18:36:57) INFO:    [Backend]:          Changing Language to: pt_BR
(18:37:10) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dont Starve
(18:37:10) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:37:10) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:37:10) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dont Starve
(18:37:10) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:37:10) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:37:10) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:37:26) INFO:    [Backend]:          Launching The Elder Scrolls Online (4d0ff75b922447649057c237c0bd1545)
(18:37:26) INFO:    [Backend]:          Preventing display from sleep
(18:37:26) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary --version
(18:37:26) INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-Proton8-12
(18:37:26) INFO:    [Backend]:          Preventing machine to sleep
(18:37:26) INFO:    [Backend]:          Started Discord Rich Presence
(18:37:26) INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-Proton8-12
(18:37:26) INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-Proton8-12
(18:37:26) INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-Proton8-12
(18:37:26) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(18:37:26) INFO:    [Backend]:          Stopping Power Saver Blocker
(18:37:28) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json --version
(18:37:28) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(18:37:31) WARNING: [Backend]:          Could not determine System Info
(18:37:31) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary eos-overlay info --prefix "/home/francehelder/Games/Heroic/Prefixes/The Elder Scrolls Online"
(18:37:31) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for The Elder Scrolls Online
(18:37:31) INFO:    [Legendary]:        Getting more details with 'legendary info'
(18:37:31) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for The Elder Scrolls Online
(18:37:31) INFO:    [Legendary]:        Getting more details with 'legendary info'
(18:37:31) INFO:    [Legendary]:        Getting more details with 'legendary info'
(18:37:31) INFO:    [Legendary]:        Getting more details with 'legendary info'
(18:37:31) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary info 4d0ff75b922447649057c237c0bd1545 --platform Windows --json
(18:37:31) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary info 4d0ff75b922447649057c237c0bd1545 --platform Windows --json
(18:37:31) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary info 4d0ff75b922447649057c237c0bd1545 --platform Windows --json
(18:37:32) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary info 4d0ff75b922447649057c237c0bd1545 --platform Windows --json
(18:37:32) INFO:    [Legendary]:        Getting Info from Epic API
(18:37:33) INFO:    [Legendary]:        Getting Info from Epic API
(18:37:35) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary eos-overlay info --prefix "/home/francehelder/Games/Heroic/Prefixes/The Elder Scrolls Online""
(18:37:47) INFO:    [DXVKInstaller]:    installing dxvk on... /home/francehelder/Games/Heroic/Prefixes/The Elder Scrolls Online
(18:37:47) INFO:    [DXVKInstaller]:    dxvk already installed!
(18:37:47) INFO:    [DXVKInstaller]:    installing vkd3d on... /home/francehelder/Games/Heroic/Prefixes/The Elder Scrolls Online
(18:37:47) INFO:    [DXVKInstaller]:    vkd3d already installed!
(18:37:47) INFO:    [Legendary]:        Launching The Elder Scrolls Online: LD_PRELOAD= WINEPREFIX="/home/francehelder/Games/Heroic/Prefixes/The Elder Scrolls Online" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= LD_LIBRARY_PATH=/home/francehelder/.config/heroic/tools/wine/Wine-GE-Proton8-12/lib64:/home/francehelder/.config/heroic/tools/wine/Wine-GE-Proton8-12/lib GST_PLUGIN_SYSTEM_PATH_1_0=/home/francehelder/.config/heroic/tools/wine/Wine-GE-Proton8-12/lib64/gstreamer-1.0:/home/francehelder/.config/heroic/tools/wine/Wine-GE-Proton8-12/lib/gstreamer-1.0 WINEDLLPATH=/home/francehelder/.config/heroic/tools/wine/Wine-GE-Proton8-12/lib64/wine:/home/francehelder/.config/heroic/tools/wine/Wine-GE-Proton8-12/lib/wine XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary launch 4d0ff75b922447649057c237c0bd1545 --language pt_BR --wine /home/francehelder/.config/heroic/tools/wine/Wine-GE-Proton8-12/bin/wine
(18:39:05) INFO:    [Backend]:          Stopped Discord Rich Presence
(18:39:05) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(18:39:06) INFO:    [Frontend]:         Refreshing legendary Library
(18:39:06) INFO:    [Legendary]:        Refreshing library...
(18:39:06) INFO:    [Legendary]:        Refreshing Epic Games...
(18:39:07) INFO:    [Legendary]:        Game list updated, got 243 games & DLCs
(18:39:07) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary list --third-party
(18:39:08) DEBUG:   [Legendary]:        Using cached install info
(18:39:08) DEBUG:   [Legendary]:        Using cached install info
(18:40:06) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dont Starve
(18:40:06) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:40:06) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:40:06) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dont Starve
(18:40:06) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:40:06) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:40:51) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary eos-overlay info --prefix "/home/francehelder/Games/Heroic/Prefixes/Dandara Trials of Fear Edition/pfx"
(18:40:51) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dandara Trials of Fear Edition
(18:40:51) INFO:    [ExtraGameInfo]:    Cached ExtraGameInfo data for Dandara Trials of Fear Edition outdated.
(18:40:51) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Dandara Trials of Fear Edition
(18:40:51) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Dandara Trials of Fear Edition
(18:40:51) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Dandara Trials of Fear Edition
(18:40:51) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Dandara Trials of Fear Edition
(18:40:51) INFO:    [Legendary]:        Getting more details with 'legendary info'
(18:40:51) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dandara Trials of Fear Edition
(18:40:51) INFO:    [ExtraGameInfo]:    Cached ExtraGameInfo data for Dandara Trials of Fear Edition outdated.
(18:40:51) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Dandara Trials of Fear Edition
(18:40:51) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Dandara Trials of Fear Edition
(18:40:51) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Dandara Trials of Fear Edition
(18:40:51) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Dandara Trials of Fear Edition
(18:40:51) INFO:    [Legendary]:        Getting more details with 'legendary info'
(18:40:51) INFO:    [Legendary]:        Getting more details with 'legendary info'
(18:40:51) ERROR:   [ExtraGameInfo]:    Was not able to get HowLongToBeat data for Dandara Trials of Fear Edition Error: Error: Request failed with status code 403
    at HltbSearch.<anonymous> (/opt/Heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (/opt/Heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(18:40:51) ERROR:   [ExtraGameInfo]:    Was not able to get HowLongToBeat data for Dandara Trials of Fear Edition Error: Error: Request failed with status code 403
    at HltbSearch.<anonymous> (/opt/Heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (/opt/Heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(18:40:51) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary info c35b9699c4e24c56976b5bd8eceba464 --platform Windows --json
(18:40:51) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary info c35b9699c4e24c56976b5bd8eceba464 --platform Windows --json
(18:40:51) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary info c35b9699c4e24c56976b5bd8eceba464 --platform Windows --json
(18:40:52) DEBUG:   [Backend]:          No SteamID, not getting ProtonDB info
(18:40:52) DEBUG:   [Backend]:          No SteamID, not getting Stem Deck info
(18:40:52) DEBUG:   [Backend]:          No SteamID, not getting ProtonDB info
(18:40:52) DEBUG:   [Backend]:          No SteamID, not getting Stem Deck info
(18:40:53) INFO:    [Legendary]:        Getting Info from Epic API
(18:40:53) INFO:    [Legendary]:        Getting Info from Epic API
(18:43:21) INFO:    [Backend]:          Changing Language to: en
(18:43:25) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=/home/francehelder/.config/heroic/legendaryConfig /home/francehelder/Downloads/legendary eos-overlay info --prefix "/home/francehelder/Games/Heroic/Prefixes/Dandara Trials of Fear Edition/pfx"
(18:43:25) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dandara Trials of Fear Edition
(18:43:25) DEBUG:   [Legendary]:        Using cached install info
(18:43:25) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dandara Trials of Fear Edition
(18:43:25) DEBUG:   [Legendary]:        Using cached install info
(18:43:25) DEBUG:   [Legendary]:        Using cached install info
(18:43:26) INFO:    [Legendary]:        Getting Info from Epic API
(18:43:27) INFO:    [Legendary]:        Getting Info from Epic API
(18:46:31) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dont Starve
(18:46:31) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:46:32) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:46:32) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dont Starve
(18:46:32) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:46:32) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:46:32) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:52:54) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dont Starve
(18:52:55) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/francehelder/.config/heroic/gog_store/auth.json auth
(18:52:55) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:52:55) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dont Starve
(18:52:55) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
(18:52:55) INFO:    [Gog]:              Got install info from cache for 1207659210 on windows platform
```

### Steps to reproduce

1. Go to a game page of a installed game
2. Click on three dots
3. Try to click on Check Compatibility 
4. Menu usually disappear before it get clicked the two last options.

### Expected behavior

The menu is shown until the mouse cursor is moved out of the menu

### Screenshots

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/14970431/9eef293e-7b21-4233-b7ec-ece21569c476

### Heroic Version

Latest Stable

### System Information

Endeavour OS with kernel 6.1.39-1-lts
MATE Desktop environment
 

### Additional information

Usually i use Portuguese language on Heroic

**Comment by flavioislima** [comment]
What happens if you click on the three dots?

**Comment by arielj** [comment]
A workaround mentioned by flavio is to click the three dots button and it will keep it open.

I've seen that issue before and it's caused by the elements behind it (installed information / game scores / etc) that for some reason are rendered on top of the menu.

I'll try to fix it
