### ISSUE TITLE
When GOG game installation fails, it's handled as a successful installation

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2942]
### Describe the bug

I tried to install a game, I got the notification saying it was installed and added to steam. Then in the library it shows as not available.

I looked for the folder and it doesn't exist, then I see there's an error in the logs during the installation.

### Add logs

```text
# general logs

(20:19:07) INFO:    [Gog]:              Installing 1906330252: /home/ariel/dev/oss/HeroicGamesLauncher/public/bin/linux/gogdl --auth-config-path /home/ariel/.config/heroic/gog_store/auth.json download 1906330252 --platform windows --path=/home/ariel/Games/Heroic --token <redacted> --skip-dlcs --lang=en
(20:19:07) DEBUG:   [Gog]:              Logging to file "/home/ariel/.config/heroic/GamesConfig/1906330252.log"
(20:19:07) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/ariel/.config/heroic/legendaryConfig /home/ariel/dev/oss/HeroicGamesLauncher/public/bin/linux/legendary list --third-party
(20:19:09) INFO:    [Gog]:              Got install info from cache for 1906330252 on windows platform
(20:19:09) INFO:    [Backend]:          Adding shortcuts for Haven Park
(20:19:09) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Haven Park
(20:19:09) INFO:    [DownloadManager]:  Finished Installation of 1906330252
(20:19:09) INFO:    [DownloadManager]:  1906330252 added to download manager finished.
(20:19:09) INFO:    [DownloadManager]:  1906330252 removed from download manager.
(20:19:09) INFO:    [Frontend]:         Refreshing gog Library


# GamesConfig/....log file

[API] INFO: Getting info from products endpoint for id: 1906330252
[DOWNLOAD_MANAGER] INFO: Checking compatibility of Haven Park with windows
[DOWNLOAD_MANAGER] INFO: Game is compatible
[DOWNLOAD_MANAGER] INFO: Depot version: 2
[DOWNLOAD_MANAGER] INFO: Getting Meta data
[API] INFO: Getting Dependencies repository
[API] INFO: Getting repository manifest
[DOWNLOAD_MANAGER] INFO: Calculating download size
[DOWNLOAD_MANAGER] INFO: Download size: 0B
[DOWNLOAD_MANAGER] INFO: Size on disk: 0B
[DOWNLOAD_MANAGER] INFO: Checking free disk space
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "gogdl/dl/progressbar.py", line 33, in print_progressbar
ZeroDivisionError: division by zero
[DOWNLOAD_MANAGER] INFO: Done
```

### Steps to reproduce

I'm not sure exactly how to reproduce it since it depends on the installation failing (and I don't know if all failures produce the same issue).

### Expected behavior

If there's an exception, the game should not be installed and the error should be printed in the logs.

### Heroic Version

Latest Stable

### System Information

Linux Mint (but I imagine it happens in any system anyway)

**Comment by connercsbn** [comment]
I noticed that this happens when you try to force install a game without having enough disk space. The spawned process exits almost immediately with an error code, but [it's treated as a successful install.](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/src/backend/launcher.ts#L970-L986) 

My best guess as to the reason this might be a GOG-specific problem is that when a GOG game finishes installing, it also [adds the game](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/src/backend/storeManagers/gog/games.ts#L359) to GOG's `installedGamesStore`, which the Legendary install function doesn't seem to do.

One solution would be to rej() when there's a nonzero exit code. Another possibility could be checking stderr [like this](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/src/backend/storeManagers/legendary/games.ts#L602)
