### ISSUE TITLE
Game page for GOG games: "Cannot get game info" due to ReadTimeoutError on GOG CDN 

### ISSUE THREAD

**Issue by tomfitzhenry** [Heroic-Games-Launcher/HeroicGamesLauncher#2953]
### Describe the bug

When I click on a GOG game in my library, to get to that game's game page, "Cannot get game info" is displayed.

This stops the ability to download the game.

### Add logs

```text
Here are the heroic and gogdl logs.

$ cat heroic*log
(17:22:18) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(17:22:18) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(17:22:18) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:22:18) INFO:    [Connection]:       Connectivity: check-online
(17:22:18) INFO:    [Connection]:       Pinging external endpoints
(17:22:18) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(17:22:18) WARNING: [Backend]:          Failed to register protocol with OS.
(17:22:18) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(17:22:19) INFO:    [Connection]:       Connectivity: online
(17:22:19) INFO:    [Backend]:          User Not Found, removing it from Store
(17:22:19) INFO:    [Gog]:              Checking if login is valid
(17:22:19) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(17:22:19) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(17:22:19) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(17:22:19) INFO:    [Backend]:          Loading Screen Ready
(17:22:19) INFO:    [Frontend]:         Refreshing undefined Library
(17:22:19) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(17:22:19) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(17:22:19) INFO:    [Legendary]:        Refreshing library...
(17:22:19) INFO:    [Backend]:          Frontend Ready
(17:22:19) INFO:    [Gog]:              Getting GOG library
(17:22:19) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(17:22:20) INFO:    [Backend]:          

Heroic Version: 2.9.1 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Freedesktop SDK KERNEL: 5.13.0-valve36-1-neptune ARCH: x64
CPU: AMD Custom APU 0405 @2.48 GOVERNOR: schedutil
RAM: Total: 14.47 GiB Available: 11.61 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB 
PROTOCOL: x11

(17:22:20) INFO:    [Gog]:              Saved username to config file
(17:22:21) INFO:    [Winetricks]:       Downloading Winetricks
(17:22:22) INFO:    [Gog]:              Saved games data
(17:22:22) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(17:22:22) INFO:    [Gog]:              Found 0 game(s) to update
(17:22:24) INFO:    [Backend]:          Starting the Download Queue
(17:22:32) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Disco Elysium - The Final Cut
(17:22:32) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(17:22:32) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(17:22:32) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Disco Elysium - The Final Cut
(17:22:32) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(17:22:32) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(17:22:32) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(17:22:33) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1771589310 --token <redacted> --lang=en-US --os windows
(17:22:33) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1771589310 --token <redacted> --lang=en-US --os windows
(17:22:33) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1771589310 --token <redacted> --lang=en-US --os windows
(17:22:33) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1771589310 --token <redacted> --lang=en-US --os windows
(17:22:34) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(17:22:34) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(17:22:34) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(17:22:34) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(17:22:34) ERROR:   [Frontend]:         Cannot get game info
(17:22:34) ERROR:   [Frontend]:         Cannot get game info
(17:22:34) ERROR:   [Frontend]:         Cannot get game info
(17:22:34) ERROR:   [Frontend]:         Cannot get game info
(17:22:34) ERROR:   [Frontend]:         Cannot get game info

$ cat gogdl*log
[8/4/2023, 5:22:18 PM] /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
[8/4/2023, 5:22:19 PM] /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
0.7.3
[8/4/2023, 5:22:19 PM] /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
{"access_token": "[redacted]", "expires_in": 3600, "token_type": "bearer", "scope": "", "session_id": "[redacted]", "refresh_token": "[redacted]", "user_id": "[redacted]", "loginTime": [redacted]}
[8/4/2023, 5:22:19 PM] /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
{"access_token": "[redacted]", "expires_in": 3600, "token_type": "bearer", "scope": "", "session_id": "[redacted]", "refresh_token": "[redacted]", "user_id": "[redacted]", "loginTime": [redacted]}
[8/4/2023, 5:22:32 PM] /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
[8/4/2023, 5:22:32 PM] /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
[8/4/2023, 5:22:32 PM] /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
[8/4/2023, 5:22:32 PM] /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
[8/4/2023, 5:22:32 PM] /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
{"access_token": "[redacted]", "expires_in": 3600, "token_type": "bearer", "scope": "", "session_id": "[redacted]", "refresh_token": "[redacted]", "user_id": "[redacted]", "loginTime": [redacted]}
[8/4/2023, 5:22:33 PM] /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1771589310 --token <redacted> --lang=en-US --os windows
[8/4/2023, 5:22:33 PM] /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1771589310 --token <redacted> --lang=en-US --os windows
[8/4/2023, 5:22:33 PM] /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1771589310 --token <redacted> --lang=en-US --os windows
[8/4/2023, 5:22:33 PM] /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1771589310 --token <redacted> --lang=en-US --os windows
[API] INFO: Getting info from products endpoint for id: 1771589310
[DOWNLOAD_MANAGER] INFO: Checking compatibility of Disco Elysium - The Final Cut with windows
[DOWNLOAD_MANAGER] INFO: Game is compatible
[DOWNLOAD_MANAGER] INFO: Depot version: 2
[DOWNLOAD_MANAGER] INFO: Getting Meta data
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 536, in _make_request
  File "urllib3/connection.py", line 461, in getresponse
  File "http/client.py", line 1377, in getresponse
  File "http/client.py", line 320, in begin
  File "http/client.py", line 281, in _read_status
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1242, in recv_into
  File "ssl.py", line 1100, in read
socket.timeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 486, in send
  File "urllib3/connectionpool.py", line 844, in urlopen
  File "urllib3/util/retry.py", line 470, in increment
  File "urllib3/util/util.py", line 39, in reraise
  File "urllib3/connectionpool.py", line 790, in urlopen
  File "urllib3/connectionpool.py", line 538, in _make_request
  File "urllib3/connectionpool.py", line 370, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='gog-cdn-lumen.secure2.footprint.net', port=443): Read timed out. (read timeout=1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gogdl/cli.py", line 51, in <module>
  File "gogdl/cli.py", line 47, in main
  File "gogdl/dl/manager.py", line 36, in calculate_download_size
  File "gogdl/dl/manager.py", line 136, in get_download_metadata
  File "gogdl/dl/dl_utils.py", line 21, in get_zlib_encoded
  File "requests/api.py", line 73, in get
  File "requests/api.py", line 59, in request
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 532, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='gog-cdn-lumen.secure2.footprint.net', port=443): Read timed out. (read timeout=1)
[215] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Open Heroic launcher.
2. Click on a GOG game in your library
3. Momentarily see the game page for that game
4. Game page displays "Cannot get game info", making the game uninstallable.

### Expected behavior

I expect the game page to remain, with the ability to install the game.

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS [e. g. "Ubuntu"]: Steam Deck, Arch
- Heroic: 2.9.1

**Comment by imLinguin** [comment]
Yes the merged PR on gogdl fixes it, you can try it out by downloading gogdl build from latest commit.

**Comment by rauldipeas** [comment]
> > Yes the merged PR on gogdl fixes it, you can try it out by downloading gogdl build from latest commit.
> 
> Thanks!
> 
> Confirmed this works for me:
> 
>     1. Download `gogdl-Linux` from https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/5755947689
> 
>     2. Extract the zip file and make the `gogdl` file executable (chmod +x gogdl)
> 
>     3. In `Heroic -> Settings -> Advanced -> Choose an Alternative GOGDL Binary to use` set this to the `gogdl` that you just extracted
> 
> 
> Should this issue be kept open to:
> 
>     * track the issue (until https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/public/bin/linux/gogdl is updated)
> 
>     * allows other impacted by this issue to find this workaround
> 
> 
> ?

I've tried this but some GOG games it's presenting the same error, it cannot get the game info and the game cannot be imported back.

**Comment by rauldipeas** [comment]
I've downloaded the latest `gogdl` from heroic-gogdl actions and everything back to works fine again, but my past log is the same of the OP.
