### ISSUE TITLE
Cannot install Pathfinder: WoTR from GOG, getInstallInfo fails

### ISSUE THREAD

**Issue by elendil95** [Heroic-Games-Launcher/HeroicGamesLauncher#2958]
### Describe the bug

When trying to install Pathfinder: Wrath of the Righteous, heroic cannot get the game size once you click on the game, and thus the game cannot be installed.
Other games in my library seem to work just fine, but i have not tested them all since i have ~200

### Add logs

```text
(10:19:41) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/elendil/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(10:19:41) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(10:19:41) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(10:19:41) INFO:    [Connection]:       Connectivity: check-online
(10:19:41) INFO:    [Connection]:       Pinging external endpoints
(10:19:41) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(10:19:41) WARNING: [Backend]:          Protocol already registered.
(10:19:41) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/elendil/.config/heroic/gog_store/auth.json --version
(10:19:41) INFO:    [Connection]:       Connectivity: online
(10:19:41) INFO:    [Backend]:          User Not Found, removing it from Store
(10:19:41) INFO:    [Gog]:              Checking if login is valid
(10:19:41) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/elendil/.config/heroic/gog_store/auth.json auth
(10:19:41) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/elendil/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(10:19:41) INFO:    [Backend]:          Loading Screen Ready
(10:19:41) INFO:    [Frontend]:         Refreshing undefined Library
(10:19:41) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(10:19:42) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/elendil/.config/heroic/gog_store/auth.json auth
(10:19:42) INFO:    [Legendary]:        Refreshing library...
(10:19:42) INFO:    [Backend]:          Frontend Ready
(10:19:42) INFO:    [Backend]:          Checking for new Heroic Updates
(10:19:42) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(10:19:42) INFO:    [Backend]:          Checking for current version changelog
(10:19:42) INFO:    [Gog]:              Getting GOG library
(10:19:42) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/elendil/.config/heroic/gog_store/auth.json auth
(10:19:42) INFO:    [Gog]:              Saved username to config file
(10:19:42) INFO:    [Backend]:          

Heroic Version: 2.9.1 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Arch KERNEL: 6.4.7-arch1-3 ARCH: x64
CPU: AMD Ryzen 7 3800X 8-Core Processor @3.9 GOVERNOR: schedutil
RAM: Total: 46.97 GiB Available: 10.28 GiB
GRAPHICS: GPU0: NVIDIA GeForce GTX 960 VRAM: 2048MB DRIVER: 535.86.05GPU1: GP104 [GeForce GTX 1070]  VRAM: 32MB 
PROTOCOL: x11

(10:19:44) INFO:    [Winetricks]:       Downloading Winetricks
(10:19:45) WARNING: [Winetricks]:       Error Downloading Winetricks Error: timeout of 1000ms exceeded
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/opt/Heroic/resources/app.asar/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
(10:19:45) INFO:    [Gog]:              Saved games data
(10:19:45) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(10:19:46) INFO:    [Gog]:              Found 0 game(s) to update
(10:19:47) INFO:    [Backend]:          Starting the Download Queue
(10:19:53) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Pathfinder Wrath of the Righteous
(10:19:53) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/elendil/.config/heroic/gog_store/auth.json auth
(10:19:53) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/elendil/.config/heroic/gog_store/auth.json auth
(10:19:53) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Pathfinder Wrath of the Righteous
(10:19:53) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/elendil/.config/heroic/gog_store/auth.json auth
(10:19:53) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/elendil/.config/heroic/gog_store/auth.json auth
(10:19:53) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/elendil/.config/heroic/gog_store/auth.json auth
(10:19:53) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/elendil/.config/heroic/gog_store/auth.json info 1207187357 --token <redacted> --lang=en-US --os windows
(10:19:53) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/elendil/.config/heroic/gog_store/auth.json info 1207187357 --token <redacted> --lang=en-US --os windows
(10:19:53) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/elendil/.config/heroic/gog_store/auth.json info 1207187357 --token <redacted> --lang=en-US --os windows
(10:19:53) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/elendil/.config/heroic/gog_store/auth.json info 1207187357 --token <redacted> --lang=en-US --os windows
(10:19:55) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(10:19:55) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(10:19:55) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(10:19:55) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(10:19:55) ERROR:   [Frontend]:         Cannot get game info
(10:19:55) ERROR:   [Frontend]:         Cannot get game info
(10:19:55) ERROR:   [Frontend]:         Cannot get game info
(10:19:55) ERROR:   [Frontend]:         Cannot get game info
(10:19:55) ERROR:   [Frontend]:         Cannot get game info
```

### Steps to reproduce

1. Open Heroic and go to Library. 
Pathfinder: PotW must not be installed
2. navigate to Pathfinder: Path of the Righteous 
3. Click on the game to open the page
4. after 1-2 seconds the error occours, an error message is shown saying "Cannot get game info"

### Expected behavior

Heroic succeeds in querying game info, so user can start the installation.

### Heroic Version

Latest Stable

### System Information

- Arch Linux
- Latest Heroic stable version was installed by using the official AUR build.

### Additional information

It seems this bug is caused by an error in gogdl.
I tried running the command that failed in a terminal (using a fresh access token) and got the following output: 
```
[API] INFO: Getting info from products endpoint for id: 1207187357
[DOWNLOAD_MANAGER] INFO: Checking compatibility of Pathfinder: Wrath of the Righteous with windows
[DOWNLOAD_MANAGER] INFO: Game is compatible
[DOWNLOAD_MANAGER] INFO: Depot version: 2
[DOWNLOAD_MANAGER] INFO: Getting Meta data
[API] INFO: Getting Dependencies repository
[API] INFO: Getting repository manifest
[DOWNLOAD_MANAGER] INFO: zlib response != 200
Traceback (most recent call last):
  File "gogdl/cli.py", line 51, in <module>
  File "gogdl/cli.py", line 47, in main
  File "gogdl/dl/manager.py", line 40, in calculate_download_size
  File "gogdl/dl/manager.py", line 194, in collect_depots
TypeError: 'NoneType' object is not subscriptable
[35363] Failed to execute script 'cli' due to unhandled exception!

```

**Comment by youkaicountry** [comment]
I can verify this also happens to me on 2.9.1, Ubuntu 22.04. It also happens with a few other games, such as `AI War 2`.

```
(14:08:32) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(14:08:32) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(14:08:32) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(14:08:32) INFO:    [Connection]:       Connectivity: check-online
(14:08:32) INFO:    [Connection]:       Pinging external endpoints
(14:08:32) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(14:08:32) WARNING: [Backend]:          Failed to register protocol with OS.
(14:08:32) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(14:08:32) INFO:    [Connection]:       Connectivity: online
(14:08:32) INFO:    [Backend]:          User Not Found, removing it from Store
(14:08:32) INFO:    [Gog]:              Checking if login is valid
(14:08:32) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:08:32) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(14:08:33) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(14:08:33) INFO:    [Backend]:          Loading Screen Ready
(14:08:33) INFO:    [Frontend]:         Refreshing undefined Library
(14:08:33) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(14:08:33) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:08:33) INFO:    [Legendary]:        Refreshing library...
(14:08:33) INFO:    [Backend]:          Frontend Ready
(14:08:33) INFO:    [Backend]:          Checking for current version changelog
(14:08:33) INFO:    [Gog]:              Saved username to config file
(14:08:34) INFO:    [Gog]:              Getting GOG library
(14:08:34) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:08:34) INFO:    [Backend]:          

Heroic Version: 2.9.1 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Freedesktop SDK KERNEL: 5.19.0-50-generic ARCH: x64
CPU: Intel Pentium® G4560 @3.5 GOVERNOR: powersave
RAM: Total: 31.3 GiB Available: 16.72 GiB
GRAPHICS: GPU0: TU104 [GeForce RTX 2080 Rev. A]  VRAM: 32MB 
PROTOCOL: x11

(14:08:34) INFO:    [Winetricks]:       Downloading Winetricks
(14:08:36) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:08:37) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:08:38) INFO:    [Backend]:          Starting the Download Queue
(14:08:38) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:08:40) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:08:41) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:08:42) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:08:43) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:08:45) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:08:46) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:10:28) WARNING: [Backend]:          No clientId in goggame-1400302682.info file. Cannot resolve save path
(14:10:32) WARNING: [Backend]:          No clientId in goggame-1660194629.info file. Cannot resolve save path
(14:10:32) WARNING: [Backend]:          No clientId in goggame-2139401243.info file. Cannot resolve save path
(14:10:44) WARNING: [Backend]:          No clientId in goggame-1584560456.info file. Cannot resolve save path
(14:10:53) WARNING: [Backend]:          No clientId in goggame-1420630484.info file. Cannot resolve save path
(14:10:57) WARNING: [Backend]:          No clientId in goggame-2129139688.info file. Cannot resolve save path
(14:11:01) WARNING: [Backend]:          No clientId in goggame-1449651388.info file. Cannot resolve save path
(14:11:05) WARNING: [Backend]:          No clientId in goggame-1440420772.info file. Cannot resolve save path
(14:11:09) WARNING: [Backend]:          No clientId in goggame-1207666523.info file. Cannot resolve save path
(14:11:14) WARNING: [Backend]:          No clientId in goggame-1472214470.info file. Cannot resolve save path
(14:11:26) WARNING: [Backend]:          No clientId in goggame-1643259651.info file. Cannot resolve save path
(14:11:51) WARNING: [Backend]:          No clientId in goggame-1539401055.info file. Cannot resolve save path
(14:11:52) INFO:    [Gog]:              Saved games data
(14:11:52) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(14:12:06) INFO:    [Gog]:              Found 2 game(s) to update
(14:12:16) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Pathfinder Wrath of the Righteous
(14:12:16) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:12:16) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:12:16) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Pathfinder Wrath of the Righteous
(14:12:16) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:12:16) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:12:16) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(14:12:16) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1207187357 --token <redacted> --lang=en-US --os windows
(14:12:16) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1207187357 --token <redacted> --lang=en-US --os windows
(14:12:16) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1207187357 --token <redacted> --lang=en-US --os windows
(14:12:16) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1207187357 --token <redacted> --lang=en-US --os windows
(14:12:19) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(14:12:19) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(14:12:19) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(14:12:19) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(14:12:19) ERROR:   [Frontend]:         Cannot get game info
(14:12:19) ERROR:   [Frontend]:         Cannot get game info
(14:12:19) ERROR:   [Frontend]:         Cannot get game info
(14:12:19) ERROR:   [Frontend]:         Cannot get game info
(14:12:19) ERROR:   [Frontend]:         Cannot get game info
```

**Comment by imLinguin** [comment]
Try this solution: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2953#issuecomment-1665236330

**Comment by youkaicountry** [comment]
That workaround fixed it for me, thank you.

**Comment by elendil95** [comment]
Apologies, i figured this out by myself but forgot to update/close the issue
Can confirm that using the latest gogdl in Heroic fixes it.
Feel free to close this issue.
