### ISSUE TITLE
X4 Foundations - Cannot get game info

### ISSUE THREAD

**Issue by NBirkenstock** [Heroic-Games-Launcher/HeroicGamesLauncher#2971]
### Describe the bug

When I'm trying to install X4 Foundations from GOG, Heroic is not able to receive the estimated sizes (download and installed) and it ends with the error "Cannot get game info".

### Add logs

```text
(21:27:40) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(21:27:40) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(21:27:40) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(21:27:40) INFO:    [Connection]:       Connectivity: check-online
(21:27:40) INFO:    [Connection]:       Pinging external endpoints
(21:27:40) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(21:27:40) WARNING: [Backend]:          Failed to register protocol with OS.
(21:27:41) INFO:    [Connection]:       Connectivity: online
(21:27:41) INFO:    [Gog]:              Checking if login is valid
(21:27:41) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:27:41) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(21:27:41) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(21:27:41) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(21:27:42) INFO:    [Gog]:              Saved username to config file
(21:27:42) INFO:    [Backend]:          Loading Screen Ready
(21:27:42) INFO:    [Frontend]:         Refreshing undefined Library
(21:27:42) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(21:27:42) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:27:42) INFO:    [Legendary]:        Refreshing library...
(21:27:42) INFO:    [Legendary]:        Refreshing Epic Games...
(21:27:43) INFO:    [Legendary]:        Game list updated, got 386 games & DLCs
(21:27:43) INFO:    [Backend]:          Frontend Ready
(21:27:43) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(21:27:43) INFO:    [Winetricks]:       Downloading Winetricks
(21:27:43) INFO:    [Gog]:              Getting GOG library
(21:27:43) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:27:44) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(21:27:44) INFO:    [Backend]:          Checking for current version changelog
(21:27:44) INFO:    [Backend]:          

Heroic Version: 2.9.1 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Freedesktop SDK KERNEL: 6.4.7-1.surface.fc38.x86_64 ARCH: x64
CPU: Intel Core™ m3-6Y30 @0.9 GOVERNOR: powersave
RAM: Total: 3.73 GiB Available: 1.37 GiB
GRAPHICS: GPU0: HD Graphics 515  VRAM: 256MB 
PROTOCOL: wayland

(21:27:45) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:27:47) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:27:48) INFO:    [Backend]:          Starting the Download Queue
(21:27:48) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:27:53) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for X4 Foundations
(21:27:53) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:27:53) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:27:53) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for X4 Foundations
(21:27:53) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:27:53) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:27:53) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:27:54) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1588366064 --token <redacted> --lang=en-US --os windows
(21:27:54) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1588366064 --token <redacted> --lang=en-US --os windows
(21:27:54) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1588366064 --token <redacted> --lang=en-US --os windows
(21:27:54) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1588366064 --token <redacted> --lang=en-US --os windows
(21:28:01) INFO:    [Gog]:              Saved games data
(21:28:01) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:28:01) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:28:01) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:28:01) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:28:01) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(21:28:01) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:28:01) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:28:01) INFO:    [Gog]:              Found 0 game(s) to update
(21:28:01) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=/home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(21:28:02) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1588366064 --token <redacted> --lang=en-US --os windows
(21:28:02) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1588366064 --token <redacted> --lang=en-US --os windows
(21:28:02) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1588366064 --token <redacted> --lang=en-US --os windows
(21:28:02) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1588366064 --token <redacted> --lang=en-US --os windows
(21:28:02) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1588366064 --token <redacted> --lang=en-US --os windows
(21:28:02) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1588366064 --token <redacted> --lang=en-US --os windows
(21:28:03) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:28:03) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:28:03) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:28:03) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:28:03) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:28:03) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:28:03) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:28:03) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:28:03) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:28:03) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:28:03) ERROR:   [Frontend]:         Cannot get game info
(21:28:03) ERROR:   [Frontend]:         Cannot get game info
(21:28:03) ERROR:   [Frontend]:         Cannot get game info
(21:28:03) ERROR:   [Frontend]:         Cannot get game info
(21:28:03) ERROR:   [Frontend]:         Cannot get game info
(21:28:03) ERROR:   [Frontend]:         Cannot get game info
(21:28:03) ERROR:   [Frontend]:         Cannot get game info
(21:28:03) ERROR:   [Frontend]:         Cannot get game info
(21:28:03) ERROR:   [Frontend]:         Cannot get game info
(21:28:03) ERROR:   [Frontend]:         Cannot get game info
(21:28:03) ERROR:   [Frontend]:         Cannot get game info
(21:28:04) WARNING: [Legendary]:        Failed to parse games from /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:468:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at Module.listUpdateableGames (/app/bin/heroic/resources/app.asar/build/electron/main.f23c4159.js:102:4644)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f23c4159.js:191:3990
    at async node:electron/js2c/browser_init:2:98394
(21:28:04) INFO:    [Legendary]:        Found 0 games to update
(21:28:05) ERROR:   [Frontend]:         Cannot get game info
(21:28:05) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:28:05) ERROR:   [Frontend]:         Cannot get game info
(21:28:05) ERROR:   [Frontend]:         Cannot get game info
(21:28:05) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:28:05) ERROR:   [Frontend]:         Cannot get game info
(21:28:05) ERROR:   [Frontend]:         Cannot get game info
(21:28:05) ERROR:   [Frontend]:         Cannot get game info
(21:28:05) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1588366064 --token <redacted> --lang=en-US --os windows
(21:28:05) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/creech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1588366064 --token <redacted> --lang=en-US --os windows
(21:28:08) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:28:08) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:28:08) ERROR:   [Frontend]:         Cannot get game info
(21:28:08) ERROR:   [Frontend]:         Cannot get game info
(21:28:08) ERROR:   [Frontend]:         Cannot get game info
```

### Steps to reproduce

1. Click on X4: Foundations
2. Wait
3. See error

### Expected behavior

I hoped to see a "Install" button so I could install X4 with all purchased DLCs.

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS: Fedora 38 Workstation (x64)
- Tested on my Desktop and Surface Pro - same result

### Additional information

I have purchased all 4 Add-ons and a few Soundtracks, so heroic has to download and calculate a lot.
So far X4 is my only problem. I downloaded 4 or 5 other games from gog without any hassle.
Lutris is able to download X4 from gog.

**Comment by imLinguin** [comment]
Solved like #2953
