### ISSUE TITLE
EAC Runtime fails to Install

### ISSUE THREAD

**Issue by MattheDev53** [Heroic-Games-Launcher/HeroicGamesLauncher#2982]
### Describe the bug

EAC Runtime on Fall Guys fails to be enabled/installed after checking the specified box, prompting an error in fall guys reading "Anti-Cheat is not initialized"

### Add logs

```text
(11:18:00) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/magames/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(11:18:00) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(11:18:00) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(11:18:00) INFO:    [Connection]:       Connectivity: check-online
(11:18:00) INFO:    [Connection]:       Pinging external endpoints
(11:18:00) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(11:18:00) WARNING: [Backend]:          Failed to register protocol with OS.
(11:18:00) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/magames/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(11:18:01) INFO:    [Connection]:       Connectivity: online
(11:18:01) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(11:18:01) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/magames/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(11:18:01) INFO:    [Backend]:          Loading Screen Ready
(11:18:01) INFO:    [Frontend]:         Refreshing undefined Library
(11:18:01) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(11:18:01) INFO:    [Legendary]:        Refreshing library...
(11:18:01) INFO:    [Legendary]:        Refreshing Epic Games...
(11:18:01) INFO:    [Legendary]:        Game list updated, got 8 games & DLCs
(11:18:01) INFO:    [Backend]:          Frontend Ready
(11:18:01) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(11:18:01) INFO:    [Gog]:              Found 0 game(s) to update
(11:18:01) INFO:    [Backend]:          Checking for current version changelog
(11:18:01) INFO:    [Backend]:          

Heroic Version: 2.9.1 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Freedesktop SDK KERNEL: 6.2.6-76060206-generic ARCH: x64
CPU: AMD Ryzen 7 5700G with Radeon Graphics @4.09 GOVERNOR: schedutil
RAM: Total: 15.48 GiB Available: 7.52 GiB
GRAPHICS: GPU0: GA104 [GeForce RTX 3060 Ti Lite Hash Rate]  VRAM: 32MB 
PROTOCOL: x11

(11:18:01) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=/home/magames/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(11:18:01) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/magames/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(11:18:02) INFO:    [Legendary]:        Found 0 games to update
(11:18:03) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(11:18:03) INFO:    [Winetricks]:       Downloading Winetricks
(11:18:04) WARNING: [Winetricks]:       Error Downloading Winetricks Error: timeout of 1000ms exceeded
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/app/bin/heroic/resources/app.asar/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
(11:18:06) INFO:    [Backend]:          Starting the Download Queue
(11:18:19) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(11:20:12) WARNING: [Backend]:          Failed download of AreWeAntiCheatYet data: Error: connect ETIMEDOUT 2606:50c0:8003::154:443
(11:20:32) ERROR:   [Runtime]:          Failed to download runtime eac_runtime: Error: connect ETIMEDOUT 2606:4700:3033::6815:2930:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
```

### Steps to reproduce

1. Get Fall Guys
2. Go to Fall Guys Game Settings
3. Click on EasyAntiCheat Runtime
4. Watch it install
5. Doesn't install

### Expected behavior

The EAC Runtime gets enabled, and Fall Guys works normally

### Screenshots

![Screenshot from 2023-08-12 11-25-53](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/110939089/bc795738-bb8d-4e72-9598-79e32f5a3016)

### Heroic Version

Latest Stable (Flatpak)

### System Information

Pop!_OS 22.04 LTS

### Additional information

I followed the steps described at the link below to install EAC Manually and it did not work
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1513#issuecomment-1183075040

**Comment by arielj** [comment]
is this still happening? sounds like a connectivity issue.

it's failing to download winetricks, the areweanticheatyet info, etc, like everything is failing to connect, not just the EAC download

**Comment by arielj** [comment]
Closing since there's no activity, please comment again if it's still happening

**Comment by DINKIN** [comment]
I am experiencing this same exact issue

however, i am also experiencing something strange additionally with the HGL

whenever i go into 

Fall Guys (settings)
I am unable to tick or untick the check boxes next to:
EasyAntiCheat Runtime

the only thing that happens is that i get a little dialog with a rotating arrow that indicates:
installing EAC runtime
but it just goes on forever and doesn't do anything
no matter how long i let it run or how many times i click the tick box

**Comment by DINKIN** [comment]
@arielj arielj 

I'm still encountering this issue

please advise

**Comment by arielj** [comment]
@DINKIN is there any error in the logs when you try to enable it?
