### ISSUE TITLE
Detect "EGS ProgramData path does not exist" error and disable egl-sync automatically

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2985]
### Problem description

For some users, they experience this error when launching a game:

```
An error has occurred! Try to Logout and Login on your Epic account.
[Core] INFO: Synced app "7179f095efcc4f92a950a6d9dbd9c602" is no longer in the EGL manifest list.[Core] INFO: Game files exist, assuming game is still installed, re-exporting to EGL...Traceback (most recent call last):
File "legendary\cli.py", line 3069, in <module>File "legendary\cli.py", line 2984, in main
File "legendary\cli.py", line 578, in launch_game
File "legendary\core.py", line 566, in get_installed_game
File "legendary\core.py", line 1861, in egl_sync
File "legendary\core.py", line 1847, in egl_restore_or_uninstall
File "legendary\core.py", line 1824, in egl_exportFile "legendary\lfs\egl.py", line 85, in set_manifest
ValueError: EGS ProgramData path does not exist
[13764] Failed to execute script 'cli' due to unhandled exception!
```

Seems to be caused by Epic being uninstalled after it was configured to auto-sync in Legendary.

The solution in general is to disable the egl-sync with `legendary egl-sync --disable-sync`

### Feature description

Currently, the game would fail to run and this error shows up in logs.

We could disable the sync and then re-try running the game so it's transparent for the user.

### Alternatives

Don't do it automatically and instead show a confirmation dialog for the user to confirm they want to disable the synchronization.

**Comment by arielj** [comment]
Closing, this was addressed in https://github.com/Heroic-Games-Launcher/legendary/pull/5
