### ISSUE TITLE
Native GOG Linux games simply will not launch

### ISSUE THREAD

**Issue by youkaicountry** [Heroic-Games-Launcher/HeroicGamesLauncher#2986]
### Describe the bug

I have installed Heroic 2.9.1 from the flatpak, on Ubuntu 22.04. I am having bizarre issues launching native linux games from heroic. Windows games using wine/proton work just fine, but native linux games will not launch. Most simply give no feedback whatsoever. I click play, and nothing seems to happen.
However if I navigate to the installed game directory, and run the start.sh script, the game runs and I can play it just fine. 

Torchlight 2, for example, when I launch it from Heroic, I see the splash screen very briefly, and then nothing.

Several other games I have tried do this. Interestingly and sadly, if I install the Windows version, they run just fine using wine. I would definitely prefer to play native where possible.

Airships 2 givers, perhaps, a clue. When running from Heroic, it tells me this:

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/838544/36d7af9f-79a9-40a3-b116-6bbf5333ba71)

But when running from `start.sh` in the installed directory, I see:

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/838544/c8a4c9ec-f6aa-475c-9910-b43afcce3d30)

And I can set my options and proceed to actually play.

So, my question is, what is going wrong where I cannot launch games from Heroic, but can from a terminal? I don't believe I have any bizarre system configuration, it's a fairly vanilla 22.04 installation, and a direct flatpak install of Heroic.

### Add logs

```text
Here is a log when trying to run Torchlight 2:


(05:57:59) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(05:57:59) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(05:57:59) INFO:    [Gog]:              GOGDL location: /run/user/1000/doc/2365306e/gogdl
(05:57:59) INFO:    [Connection]:       Connectivity: check-online
(05:57:59) INFO:    [Connection]:       Pinging external endpoints
(05:57:59) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(05:57:59) WARNING: [Backend]:          Failed to register protocol with OS.
(05:57:59) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(05:57:59) INFO:    [Connection]:       Connectivity: online
(05:57:59) INFO:    [Backend]:          User Not Found, removing it from Store
(05:57:59) INFO:    [Gog]:              Checking if login is valid
(05:57:59) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(05:57:59) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(05:58:00) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(05:58:00) INFO:    [Backend]:          Loading Screen Ready
(05:58:00) INFO:    [Frontend]:         Refreshing undefined Library
(05:58:00) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(05:58:00) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(05:58:00) INFO:    [Legendary]:        Refreshing library...
(05:58:00) INFO:    [Backend]:          Frontend Ready
(05:58:00) INFO:    [Backend]:          Checking for current version changelog
(05:58:01) INFO:    [Gog]:              Saved username to config file
(05:58:01) INFO:    [Backend]:          

Heroic Version: 2.9.1 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Freedesktop SDK KERNEL: 6.2.0-26-generic ARCH: x64
CPU: Intel Pentium® G4560 @3.5 GOVERNOR: powersave
RAM: Total: 31.29 GiB Available: 18.17 GiB
GRAPHICS: GPU0: TU104 [GeForce RTX 2080 Rev. A]  VRAM: 32MB 
PROTOCOL: x11

(05:58:01) INFO:    [Gog]:              Getting GOG library
(05:58:01) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(05:58:01) WARNING: [DXVKInstaller]:    No GPU with Vulkan 1.1 support found, DXVK will not work
(05:58:01) INFO:    [Winetricks]:       Downloading Winetricks
(05:58:02) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(05:58:04) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(05:58:05) INFO:    [Backend]:          Starting the Download Queue
(05:58:05) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(05:58:07) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(05:58:08) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(05:58:15) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(05:58:16) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(05:58:23) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(05:58:25) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(05:58:29) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1501803768 Release with per platform id: gog_1501803768 not found
(05:58:49) WARNING: [Backend]:          No clientId in goggame-1584560456.info file. Cannot resolve save path
(05:59:59) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1501803768 Release with per platform id: gog_1501803768 not found
(06:00:02) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1501803768 Release with per platform id: gog_1501803768 not found
(06:00:04) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1501803768 Release with per platform id: gog_1501803768 not found
(06:00:06) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1501803768 Release with per platform id: gog_1501803768 not found
(06:00:09) INFO:    [Gog]:              Saved games data
(06:00:09) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(06:00:24) INFO:    [Gog]:              Found 11 game(s) to update
(06:04:30) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Torchlight II
(06:04:30) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(06:04:30) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:30) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Torchlight II
(06:04:30) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:30) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:32) INFO:    [Backend]:          Launching Torchlight II (1958228073)
(06:04:32) INFO:    [Backend]:          Preventing display from sleep
(06:04:32) INFO:    [Backend]:          Preventing machine to sleep
(06:04:32) INFO:    [Backend]:          Stopping Power Saver Blocker
(06:04:32) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:32) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:32) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:32) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:32) INFO:    [Gog]:              Launching Torchlight II: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json launch "/home/momo/Games/Heroic/Torchlight 2" 1958228073 --platform linux
(06:04:34) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(06:04:34) INFO:    [Frontend]:         Refreshing gog Library
(06:04:34) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(06:04:34) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:34) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:34) INFO:    [Gog]:              Getting GOG library
(06:04:34) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(06:04:36) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(06:04:38) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(06:04:39) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(06:04:40) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(06:04:42) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(06:04:43) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(06:04:45) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(06:04:46) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(06:04:48) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(06:04:52) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1501803768 Release with per platform id: gog_1501803768 not found
(06:04:52) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:52) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:52) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:52) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:52) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:52) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:52) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:52) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:52) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:52) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:52) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:52) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:52) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:53) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:53) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:53) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:04:53) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:05:09) WARNING: [Backend]:          No clientId in goggame-1584560456.info file. Cannot resolve save path
(06:05:20) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Torchlight II
(06:05:20) INFO:    [Gog]:              Running command: /run/user/1000/doc/2365306e/gogdl --auth-config-path /home/momo/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(06:05:20) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:05:20) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Torchlight II
(06:05:20) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:05:20) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:05:20) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:05:27) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:05:31) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:10) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:10) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:10) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:10) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:10) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:10) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:10) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:10) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:10) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:10) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:11) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:11) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:11) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:11) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:11) WARNING: [Gog]:              Failed attempt to get playtime of 1958228073 {
  "message": "Request failed with status code 401",
  "name": "Error",
  "stack": "Error: Request failed with status code 401\n    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Authorization": "Bearer nMTtD6apsijLZwLieEMKi4dDIsdAi-51kkYsT1pRKxL2JksjUJu-nlcsy8pXWSbtPMxSYtDrxCnQUzAGVpx74N8oFBJ0yxTjWsAcmat1M-m-ZKH0C6QAjM9_6teT4kkuUy36UEM3pc-8ms9VzUVTTnWN09mLUMHVaSbB2pVmQTij3PrPoaMiG3z-y-Mc_1EH",
      "User-Agent": "axios/0.26.1"
    },
    "method": "get",
    "url": "https://gameplay.gog.com/games/1958228073/users/46988909235965615/sessions"
  },
  "status": 401
}
(06:06:11) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:11) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:12) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1501803768 Release with per platform id: gog_1501803768 not found
(06:06:15) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1501803768 Release with per platform id: gog_1501803768 not found
(06:06:17) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1501803768 Release with per platform id: gog_1501803768 not found
(06:06:19) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1501803768 Release with per platform id: gog_1501803768 not found
(06:06:22) INFO:    [Gog]:              Saved games data
(06:06:22) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:22) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:22) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:22) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:22) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
(06:06:22) INFO:    [Gog]:              Got install info from cache for 1958228073 on windows platform
```
```


### Steps to reproduce

1. Install a native linux game, say Torchlight 2
2. Play it

### Expected behavior

The game runs.

### Screenshots

_No response_

### Heroic Version

Latest Stable

### System Information

Ubuntu 22.04
GeForce RTX 2080
Pentium G4560
32 GB RAM


### Additional information

_No response_

**Comment by lapastillaroja** [comment]
I'm having the same problem as OP with a clean install with Indiana Jones and the Fate of Atlantis

Log after some retries
```
(08:58:36) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(08:58:36) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(08:58:36) INFO:    [Connection]:       Connectivity: check-online
(08:58:36) INFO:    [Connection]:       Pinging external endpoints
(08:58:36) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(08:58:36) WARNING: [Backend]:          Failed to register protocol with OS.
(08:58:36) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(08:58:36) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(08:58:36) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(08:58:36) INFO:    [Connection]:       Connectivity: online
(08:58:36) INFO:    [Backend]:          User Not Found, removing it from Store
(08:58:36) INFO:    [Gog]:              Checking if login is valid
(08:58:36) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(08:58:36) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(08:58:36) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 7 3700X 8-Core Processor
Memory: 16.65 GB (used: 3.77 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB]
    IDs: D=1c03 V=10de SD=3281 SV=1462
    Driver: nvidia
OS: Freedesktop SDK 23.08 (Flatpak runtime) (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.9.2 Boa Hancock
  Legendary: 0.20.32 Dark Energy (hotfix #6)
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(08:58:36) INFO:    [Backend]:          Loading Screen Ready
(08:58:36) INFO:    [Frontend]:         Refreshing undefined Library
(08:58:36) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(08:58:36) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(08:58:36) INFO:    [Legendary]:        Refreshing library...
(08:58:36) INFO:    [Backend]:          Frontend Ready
(08:58:36) INFO:    [Backend]:          Checking for current version changelog
(08:58:36) INFO:    [Gog]:              Getting GOG library
(08:58:36) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(08:58:38) INFO:    [Gog]:              Saved username to config file
(08:58:38) INFO:    [Winetricks]:       Downloading Winetricks
(08:58:39) WARNING: [Winetricks]:       Error Downloading Winetricks Error: timeout of 1000ms exceeded
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/app/bin/heroic/resources/app.asar/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
(08:58:41) INFO:    [Backend]:          Starting the Download Queue
(08:59:47) INFO:    [Gog]:              Saved games data
(08:59:47) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(08:59:50) INFO:    [Gog]:              Found 0 game(s) to update
(08:59:55) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Indiana Jones and the Fate of Atlantis
(08:59:55) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(08:59:55) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Indiana Jones and the Fate of Atlantis
(08:59:55) INFO:    [Gog]:              Got install info from cache for 1207666293 on windows platform
(08:59:57) INFO:    [Backend]:          Launching Indiana Jones® and the Fate of Atlantis™ (1207666293)
(08:59:57) INFO:    [Backend]:          Preventing display from sleep
(08:59:57) INFO:    [Backend]:          Preventing machine to sleep
(08:59:57) INFO:    [Backend]:          Stopping Power Saver Blocker
(08:59:57) INFO:    [Gog]:              Got install info from cache for 1207666293 on windows platform
(08:59:57) INFO:    [Gog]:              Launching Indiana Jones® and the Fate of Atlantis™: HEROIC_APP_NAME=1207666293 HEROIC_APP_RUNNER=gog HEROIC_APP_SOURCE=gog /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json launch "/home/xxx/Games/Heroic/Indiana Jones and the Fate of Atlantis" 1207666293 --platform linux
(08:59:58) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(08:59:58) INFO:    [Frontend]:         Refreshing gog Library
(08:59:58) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(08:59:58) INFO:    [Gog]:              Got install info from cache for 1207666293 on windows platform
(08:59:58) INFO:    [Gog]:              Getting GOG library
(08:59:58) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(08:59:59) INFO:    [Gog]:              Got install info from cache for 1207666293 on windows platform
(09:00:19) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(09:00:19) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(09:00:19) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(09:00:31) INFO:    [Gog]:              Saved games data
(09:01:14) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Indiana Jones and the Fate of Atlantis
(09:01:14) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(09:01:14) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Indiana Jones and the Fate of Atlantis
(09:01:14) INFO:    [Gog]:              Got install info from cache for 1207666293 on windows platform
(09:01:17) INFO:    [Backend]:          Launching Indiana Jones® and the Fate of Atlantis™ (1207666293)
(09:01:17) INFO:    [Backend]:          Preventing display from sleep
(09:01:17) INFO:    [Backend]:          Stopping Power Saver Blocker
(09:01:17) INFO:    [Gog]:              Launching Indiana Jones® and the Fate of Atlantis™: HEROIC_APP_NAME=1207666293 HEROIC_APP_RUNNER=gog HEROIC_APP_SOURCE=gog /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json launch "/home/xxx/Games/Heroic/Indiana Jones and the Fate of Atlantis" 1207666293 --platform linux
(09:01:17) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(09:01:17) INFO:    [Frontend]:         Refreshing gog Library
(09:01:17) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(09:01:17) INFO:    [Gog]:              Got install info from cache for 1207666293 on windows platform
(09:01:17) INFO:    [Gog]:              Got install info from cache for 1207666293 on windows platform
(09:01:17) INFO:    [Gog]:              Getting GOG library
(09:01:17) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/xxx/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(09:01:20) INFO:    [Gog]:              Got install info from cache for 1207666293 on windows platform
(09:01:20) INFO:    [Gog]:              Got install info from cache for 1207666293 on windows platform
(09:01:50) INFO:    [Gog]:              Saved games data
(09:34:00) INFO:    [Connection]:       Connectivity: offline
(16:40:45) INFO:    [Connection]:       Connectivity: check-online
(16:40:45) INFO:    [Connection]:       Pinging external endpoints
(16:40:45) INFO:    [Connection]:       Connectivity: online
```

**Comment by arielj** [comment]
I imagine the issue is that flatpak is isolated from the system by default and some libraries that the native game expects cannot be accessed.

I imagine the game log (not heroic's general log) should have some errors about libraries not found.

I'm not sure if changing permissions of Heroic's flatpak using Flatseal can help with that.

**Comment by boltronics** [comment]
It's a similar deal with Ion Fury from GOG. Heroic installed via Flatpak on Arch. Requires libFLAC.so.8 which is missing on the system by default, so it had to be installed via "flac1.3" from AUR. This enabled the game to launch fine by manually running the start.sh script, but not from Heroic.

As a work-around, I copied `/usr/lib/libFLAC.so.8` into the `Ion Fury/game` folder.

I believe that this library is normally included by the Steam runtime, but the option to use that is unavailable on my system (Steam runtime not found) — possibly because I have Steam installed in an alternate location using firejail (which basically makes my Steam location appear to be installed directly in my home directory when it's actually not), which confuses Heroic and prevents that option from working, even when I manually specify the correct path — but that's a different issue (and not strictly Heroic's fault to being with).

**Comment by n3tn0de** [comment]
> It's a similar deal with Ion Fury from GOG. Heroic installed via Flatpak on Arch. Requires libFLAC.so.8 which is missing on the system by default, so it had to be installed via "flac1.3" from AUR. This enabled the game to launch fine by manually running the start.sh script, but not from Heroic.
> 
> As a work-around, I copied `/usr/lib/libFLAC.so.8` into the `Ion Fury/game` folder.
> 
> I believe that this library is normally included by the Steam runtime, but the option to use that is unavailable on my system (Steam runtime not found) — possibly because I have Steam installed in an alternate location using firejail (which basically makes my Steam location appear to be installed directly in my home directory when it's actually not), which confuses Heroic and prevents that option from working, even when I manually specify the correct path — but that's a different issue (and not strictly Heroic's fault to being with).

Also works with newer `libFLAC.so.12` which is shipped with Steam OS 3.6.8.
Just rename the lib to `Ion Fury/game/libFLAC.so.8`

**Comment by arielj** [comment]
Closing this as there's not that much we can do about it due to either flatpak's limitations or old system packages (in general, it's a good idea to use the Use Steam Runtime for linux native games to workaround this problem and maybe in the future umu can also be used).

In the meantime, for running specific games that don't work when enabling the `Use Steam Runtime` feature, it should be asked over Discord instead.
