### ISSUE TITLE
Unable to login via Amazon.

### ISSUE THREAD

**Issue by rokejulianlockhart** [Heroic-Games-Launcher/HeroicGamesLauncher#2989]
### Describe the bug

When I authenticate, I'm just brought to the store page.

### Add logs

```text
(20:35:28) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(20:35:28) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(20:35:28) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(20:35:28) INFO:    [Connection]:       Connectivity: check-online
(20:35:28) INFO:    [Connection]:       Pinging external endpoints
(20:35:29) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(20:35:29) INFO:    [Connection]:       Connectivity: online
(20:35:29) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(20:35:29) INFO:    [Backend]:          

Heroic Version: 2.9.1 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Freedesktop SDK KERNEL: 6.4.9-1-default ARCH: x64
CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: schedutil
RAM: Total: 31.23 GiB Available: 18.42 GiB
GRAPHICS: GPU0: Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] VRAM: 512MB 
PROTOCOL: x11

(20:35:31) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "updated",
    "version": "4.10.2557.0"
  }
}
(20:35:31) INFO:    [Backend]:          User Not Found, removing it from Store
(20:35:31) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(20:35:31) WARNING: [Backend]:          Failed to register protocol with OS.
(20:35:31) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(20:35:32) INFO:    [Backend]:          Loading Screen Ready
(20:35:32) INFO:    [Backend]:          Frontend Ready
(20:35:32) INFO:    [Backend]:          Checking for current version changelog
(20:35:32) INFO:    [Frontend]:         Updated to a new version, cleaaning up the cache.
(20:35:32) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary cleanup
(20:35:32) INFO:    [Frontend]:         Refreshing undefined Library
(20:35:32) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(20:35:32) INFO:    [Legendary]:        Refreshing library...
(20:35:34) INFO:    [Winetricks]:       Downloading Winetricks
(20:35:34) INFO:    [DXVKInstaller]:    Updating vkd3d to: vkd3d-proton-2.9
(20:35:34) INFO:    [DXVKInstaller]:    Updating dxvk to: dxvk-2.2
(20:35:35) INFO:    [DXVKInstaller]:    downloaded vkd3d
(20:35:35) INFO:    [DXVKInstaller]:    extracting vkd3d
(20:35:35) INFO:    [DXVKInstaller]:    vkd3d updated!
(20:35:36) INFO:    [DXVKInstaller]:    downloaded dxvk
(20:35:36) INFO:    [DXVKInstaller]:    extracting dxvk
(20:35:36) INFO:    [DXVKInstaller]:    dxvk updated!
(20:35:37) INFO:    [Backend]:          Starting the Download Queue
(20:37:49) INFO:    [Legendary]:        Logging in: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(20:37:50) INFO:    [Frontend]:         Refreshing legendary Library
(20:37:50) INFO:    [Legendary]:        Refreshing library...
(20:37:50) INFO:    [Legendary]:        Refreshing Epic Games...
(20:37:50) INFO:    [Legendary]:        Game list updated, got 0 games & DLCs
(20:37:50) INFO:    [Frontend]:         No cache found, getting data from legendary...
(20:37:50) INFO:    [Legendary]:        Refreshing library...
(20:37:50) INFO:    [Legendary]:        Refreshing Epic Games...
(20:37:50) INFO:    [Legendary]:        Game list updated, got 0 games & DLCs
(20:37:50) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(20:37:50) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(20:38:00) INFO:    [Frontend]:         Refreshing wine downloader releases
(20:38:00) INFO:    [WineDownloader]:   Updating wine versions info
(20:38:00) INFO:    [WineDownloader]:   Fetching upstream information...
(20:38:01) INFO:    [WineDownloader]:   wine versions updated
(20:38:08) INFO:    [Frontend]:         Refreshing undefined Library
(20:38:08) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(20:38:08) INFO:    [Legendary]:        Refreshing library...
(20:38:08) INFO:    [Legendary]:        Refreshing Epic Games...
(20:38:08) INFO:    [Legendary]:        Game list updated, got 17 games & DLCs
(20:38:08) INFO:    [Frontend]:         No cache found, getting data from legendary...
(20:38:08) INFO:    [Legendary]:        Refreshing library...
(20:38:08) INFO:    [Legendary]:        Refreshing Epic Games...
(20:38:08) INFO:    [Legendary]:        Game list updated, got 17 games & DLCs
(20:38:08) INFO:    [Frontend]:         Force Update
(20:38:08) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(20:38:08) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(20:38:09) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for VALORANT
(20:38:09) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for VALORANT
(20:38:09) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for VALORANT
(20:38:09) INFO:    [ExtraGameInfo]:    Getting GamesDB data for VALORANT
(20:38:09) INFO:    [Legendary]:        Getting more details with 'legendary info'
(20:38:09) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for VALORANT
(20:38:09) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for VALORANT
(20:38:09) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for VALORANT
(20:38:09) INFO:    [ExtraGameInfo]:    Getting GamesDB data for VALORANT
(20:38:09) INFO:    [Legendary]:        Getting more details with 'legendary info'
(20:38:09) INFO:    [Legendary]:        Getting more details with 'legendary info'
(20:38:09) INFO:    [Legendary]:        Getting more details with 'legendary info'
(20:38:09) ERROR:   [ExtraGameInfo]:    Was not able to get HowLongToBeat data for VALORANT Error: Error: Request failed with status code 403
    at HltbSearch.<anonymous> (/app/bin/heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (/app/bin/heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(20:38:09) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info 602eb4abc8764c87b7f2607a1ef8c18e --platform Windows --json
(20:38:09) ERROR:   [ExtraGameInfo]:    Was not able to get HowLongToBeat data for VALORANT Error: Error: Request failed with status code 403
    at HltbSearch.<anonymous> (/app/bin/heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (/app/bin/heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(20:38:09) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info 602eb4abc8764c87b7f2607a1ef8c18e --platform Windows --json
(20:38:09) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info 602eb4abc8764c87b7f2607a1ef8c18e --platform Windows --json
(20:38:09) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info 602eb4abc8764c87b7f2607a1ef8c18e --platform Windows --json
(20:38:10) DEBUG:   [Backend]:          No SteamID, not getting ProtonDB info
(20:38:10) DEBUG:   [Backend]:          No SteamID, not getting Stem Deck info
(20:38:10) DEBUG:   [Backend]:          No SteamID, not getting ProtonDB info
(20:38:10) DEBUG:   [Backend]:          No SteamID, not getting Stem Deck info
(20:38:10) INFO:    [Legendary]:        Getting Info from Epic API
(20:38:10) INFO:    [Legendary]:        Getting Info from Epic API
(20:38:13) DEBUG:   [Legendary]:        Using cached install info
(20:38:13) DEBUG:   [Backend]:          {"free":31268294656,"diskSize":215971004416,"message":"29.12 GiB / 201.14 GiB","validPath":true}
(20:38:13) DEBUG:   [Backend]:          {"free":31268294656,"diskSize":215971004416,"message":"29.12 GiB / 201.14 GiB","validPath":true}
(20:41:50) INFO:    [Backend]:          Writing config for 602eb4abc8764c87b7f2607a1ef8c18e
(20:41:50) INFO:    [Backend]:          Changed config: winePrefix from /home/rokejulianlockhart/Games/Heroic/Prefixes/default to /home/rokejulianlockhart/Games/Heroic/Prefixes/default/VALORANT
(20:41:50) INFO:    [Backend]:          Changed config: wineCrossoverBottle from undefined to Heroic
(20:41:50) DEBUG:   [Legendary]:        Using cached install info
(20:41:50) INFO:    [DownloadManager]:  VALORANT  was added to the download queue.
(20:41:50) INFO:    [Backend]:          Preventing machine to sleep
(20:41:50) DEBUG:   [Legendary]:        Using cached install info
(20:41:50) DEBUG:   [Legendary]:        Using cached install info
(20:41:50) DEBUG:   [Legendary]:        Using cached install info
(20:41:50) INFO:    [Legendary]:        Installing 602eb4abc8764c87b7f2607a1ef8c18e: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary install 602eb4abc8764c87b7f2607a1ef8c18e --platform Windows --base-path /home/rokejulianlockhart/Games/Heroic --skip-dlcs --skip-sdl -y
(20:41:50) DEBUG:   [Legendary]:        Logging to file "/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/602eb4abc8764c87b7f2607a1ef8c18e.log"
(20:41:50) DEBUG:   [Legendary]:        Using cached install info
(20:41:50) DEBUG:   [Legendary]:        Using cached install info
(20:41:52) INFO:    [Legendary]:        Progress for VALORANT: 0%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(20:41:53) INFO:    [Legendary]:        Progress for VALORANT: 1.58%/0.98MB/00:00:00 Down: 0.98MB/s / Disk: 0MB/s
(20:41:54) INFO:    [Legendary]:        Progress for VALORANT: 8.85%/5.49MB/00:00:00 Down: 4.51MB/s / Disk: 0MB/s
(20:41:55) INFO:    [Legendary]:        Progress for VALORANT: 20.05%/12.44MB/00:00:30 Down: 6.94MB/s / Disk: 5.99MB/s
(20:41:56) INFO:    [Legendary]:        Progress for VALORANT: 26.5%/16.44MB/00:00:40 Down: 4MB/s / Disk: 0MB/s
(20:41:57) INFO:    [Legendary]:        Progress for VALORANT: 39.38%/24.43MB/00:00:50 Down: 7.99MB/s / Disk: 0MB/s
(20:41:58) INFO:    [Legendary]:        Progress for VALORANT: 51.77%/32.11MB/00:00:10 Down: 7.67MB/s / Disk: 17.99MB/s
(20:41:59) INFO:    [Legendary]:        Progress for VALORANT: 59.83%/37.11MB/00:00:07 Down: 4.99MB/s / Disk: 7.99MB/s
(20:42:00) INFO:    [Legendary]:        Progress for VALORANT: 72.72%/45.11MB/00:00:05 Down: 8MB/s / Disk: 7MB/s
(20:42:01) INFO:    [Legendary]:        Progress for VALORANT: 80.78%/50.11MB/00:00:06 Down: 4.99MB/s / Disk: 0MB/s
(20:42:02) INFO:    [Legendary]:        Progress for VALORANT: 98.39%/61.03MB/00:00:00 Down: 10.91MB/s / Disk: 23.97MB/s
(20:42:03) INFO:    [Legendary]:        Progress for VALORANT: 100%/62.03MB/00:00:00 Down: 1MB/s / Disk: 2.83MB/s
(20:42:04) INFO:    [Backend]:          Adding shortcuts for VALORANT
(20:42:04) INFO:    [DownloadManager]:  Finished Installation of 602eb4abc8764c87b7f2607a1ef8c18e
(20:42:04) INFO:    [DownloadManager]:  602eb4abc8764c87b7f2607a1ef8c18e added to download manager finished.
(20:42:04) INFO:    [DownloadManager]:  602eb4abc8764c87b7f2607a1ef8c18e removed from download manager.
(20:42:04) INFO:    [Frontend]:         Refreshing legendary Library
(20:42:04) INFO:    [Legendary]:        Refreshing library...
(20:42:04) INFO:    [Legendary]:        Refreshing Epic Games...
(20:42:04) INFO:    [Legendary]:        Game list updated, got 17 games & DLCs
(20:42:04) DEBUG:   [Legendary]:        Using cached install info
(20:42:04) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix /home/rokejulianlockhart/Games/Heroic/Prefixes/default/VALORANT
(20:42:04) DEBUG:   [Legendary]:        Using cached install info
(20:42:04) DEBUG:   [Legendary]:        Using cached install info
(20:42:04) DEBUG:   [Legendary]:        Using cached install info
(20:42:04) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(20:42:09) INFO:    [Backend]:          Launching VALORANT (602eb4abc8764c87b7f2607a1ef8c18e)
(20:42:09) INFO:    [Backend]:          Preventing display from sleep
(20:42:09) INFO:    [Backend]:          Checking if wine version exists: Default Wine - Not Found
(20:42:09) ERROR:   [Backend]:          Wine version Default Wine - Not Found is not valid, trying another one.
(20:42:09) INFO:    [Backend]:          Checking if wine version exists: Default Wine - Not Found
(20:42:09) INFO:    [Backend]:          Checking if wine version exists: Wine - lutris-GE-Proton8-13-x86_64
(20:42:09) INFO:    [Backend]:          Preventing machine to sleep
(20:42:09) DEBUG:   [Legendary]:        Using cached install info
(20:42:09) DEBUG:   [Legendary]:        Using cached install info
(20:42:15) INFO:    [Backend]:          Changing wine version to Wine - lutris-GE-Proton8-13-x86_64
(20:42:15) INFO:    [Backend]:          602eb4abc8764c87b7f2607a1ef8c18e: Setting wineVersion to {"bin":"/home/rokejulianlockhart/.local/share/lutris/runners/wine/lutris-GE-Proton8-13-x86_64/bin/wine","name":"Wine - lutris-GE-Proton8-13-x86_64","type":"wine","lib":"/home/rokejulianlockhart/.local/share/lutris/runners/wine/lutris-GE-Proton8-13-x86_64/lib64","lib32":"/home/rokejulianlockhart/.local/share/lutris/runners/wine/lutris-GE-Proton8-13-x86_64/lib","wineserver":"/home/rokejulianlockhart/.local/share/lutris/runners/wine/lutris-GE-Proton8-13-x86_64/bin/wineserver"}
(20:42:15) INFO:    [Backend]:          Stopping Power Saver Blocker
(20:42:15) DEBUG:   [Legendary]:        Using cached install info
(20:42:15) DEBUG:   [Legendary]:        Using cached install info
(20:42:15) INFO:    [Backend]:          Checking if wine version exists: Wine - lutris-GE-Proton8-13-x86_64
(20:42:15) INFO:    [Backend]:          Checking if wine version exists: Wine - lutris-GE-Proton8-13-x86_64
(20:42:15) INFO:    [Backend]:          Checking if wine version exists: Wine - lutris-GE-Proton8-13-x86_64
(20:42:15) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(20:42:57) INFO:    [Backend]:          Created/Updated Wineprefix at /home/rokejulianlockhart/Games/Heroic/Prefixes/default/VALORANT
(20:42:57) INFO:    [DXVKInstaller]:    installing dxvk on... /home/rokejulianlockhart/Games/Heroic/Prefixes/default/VALORANT
(20:42:57) INFO:    [Backend]:          Checking if wine version exists: Wine - lutris-GE-Proton8-13-x86_64
(20:42:57) INFO:    [Backend]:          Checking if wine version exists: Wine - lutris-GE-Proton8-13-x86_64
(20:42:57) INFO:    [Backend]:          Checking if wine version exists: Wine - lutris-GE-Proton8-13-x86_64
(20:42:57) INFO:    [Backend]:          Checking if wine version exists: Wine - lutris-GE-Proton8-13-x86_64
(20:42:57) DEBUG:   [Backend]:          Running Wine command: reg add HKEY_CURRENT_USER\Software\Wine\DllOverrides /v d3d10core /d native,builtin /f
(20:42:57) DEBUG:   [Backend]:          Running Wine command: reg add HKEY_CURRENT_USER\Software\Wine\DllOverrides /v d3d11 /d native,builtin /f
(20:42:57) DEBUG:   [Backend]:          Running Wine command: reg add HKEY_CURRENT_USER\Software\Wine\DllOverrides /v d3d9 /d native,builtin /f
(20:42:57) DEBUG:   [Backend]:          Running Wine command: reg add HKEY_CURRENT_USER\Software\Wine\DllOverrides /v dxgi /d native,builtin /f
(20:42:57) INFO:    [DXVKInstaller]:    installing vkd3d on... /home/rokejulianlockhart/Games/Heroic/Prefixes/default/VALORANT
(20:42:57) INFO:    [Backend]:          Checking if wine version exists: Wine - lutris-GE-Proton8-13-x86_64
(20:42:57) INFO:    [Backend]:          Checking if wine version exists: Wine - lutris-GE-Proton8-13-x86_64
(20:42:57) DEBUG:   [Backend]:          Running Wine command: reg add HKEY_CURRENT_USER\Software\Wine\DllOverrides /v d3d12 /d native,builtin /f
(20:42:57) DEBUG:   [Backend]:          Running Wine command: reg add HKEY_CURRENT_USER\Software\Wine\DllOverrides /v d3d12core /d native,builtin /f
(20:42:57) INFO:    [Legendary]:        Launching VALORANT: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig LD_LIBRARY_PATH=/home/rokejulianlockhart/.local/share/lutris/runners/wine/lutris-GE-Proton8-13-x86_64/lib64:/home/rokejulianlockhart/.local/share/lutris/runners/wine/lutris-GE-Proton8-13-x86_64/lib WINEPREFIX=/home/rokejulianlockhart/Games/Heroic/Prefixes/default/VALORANT WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= GST_PLUGIN_SYSTEM_PATH_1_0=/home/rokejulianlockhart/.local/share/lutris/runners/wine/lutris-GE-Proton8-13-x86_64/lib64/gstreamer-1.0:/home/rokejulianlockhart/.local/share/lutris/runners/wine/lutris-GE-Proton8-13-x86_64/lib/gstreamer-1.0 WINEDLLPATH=/home/rokejulianlockhart/.local/share/lutris/runners/wine/lutris-GE-Proton8-13-x86_64/lib64/wine:/home/rokejulianlockhart/.local/share/lutris/runners/wine/lutris-GE-Proton8-13-x86_64/lib/wine /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 602eb4abc8764c87b7f2607a1ef8c18e --language en --wine /home/rokejulianlockhart/.local/share/lutris/runners/wine/lutris-GE-Proton8-13-x86_64/bin/wine
(20:44:44) DEBUG:   [Legendary]:        Using cached install info
(20:44:54) DEBUG:   [Legendary]:        Using cached install info
(20:45:20) DEBUG:   [Nile]:             Getting login data from Nile
(20:45:20) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile auth --login --non-interactive
(20:45:20) INFO:    [Nile]:             Register data is: {
  "client_id": "3139463737313836334144423131454538313439463032463734323335354546234132554d56484f58375550345637",
  "code_verifier": "oI4ucmtiqMHRwDhpbOirCswn2-H_QKgqKAmueVcRWfU",
  "serial": "19F771863ADB11EE8149F02F742355EF",
  "url": "https://amazon.com/ap/signin?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.oa2.scope=device_auth_access&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.response_type=code&openid.oa2.code_challenge_method=S256&openid.oa2.client_id=device%3A3139463737313836334144423131454538313439463032463734323335354546234132554d56484f58375550345637&language=en_US&marketPlaceId=ATVPDKIKX0DER&openid.return_to=https%3A%2F%2Fwww.amazon.com&openid.pape.max_auth_age=0&openid.assoc_handle=amzn_sonic_games_launcher&pageId=amzn_sonic_games_launcher&openid.oa2.code_challenge=oRFJ3OAhpAZkep0Wb5XtXuIrpYOYLhgs0lvUXarubzg"
}
(20:45:52) DEBUG:   [Nile]:             Getting login data from Nile
(20:45:52) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/rokejulianlockhart/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile auth --login --non-interactive
(20:45:52) INFO:    [Nile]:             Register data is: {
  "client_id": "3244323530383545334144423131454539323141463032463734323335354546234132554d56484f58375550345637",
  "code_verifier": "EenNHNyYvvN6yQONX-k9hNp8PD3Teh4LPlJd9jlA3yA",
  "serial": "2D25085E3ADB11EE921AF02F742355EF",
  "url": "https://amazon.com/ap/signin?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.oa2.scope=device_auth_access&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.response_type=code&openid.oa2.code_challenge_method=S256&openid.oa2.client_id=device%3A3244323530383545334144423131454539323141463032463734323335354546234132554d56484f58375550345637&language=en_US&marketPlaceId=ATVPDKIKX0DER&openid.return_to=https%3A%2F%2Fwww.amazon.com&openid.pape.max_auth_age=0&openid.assoc_handle=amzn_sonic_games_launcher&pageId=amzn_sonic_games_launcher&openid.oa2.code_challenge=RU-2d6DsSwWXMMifioOdnOJi7bJ-RywORXYipK_E-Fg"
}
(23:36:31) INFO:    [Backend]:          Heroic: Setting autoUpdateGames to true (previous value: false)
(23:36:37) INFO:    [Backend]:          Heroic: Setting addStartMenuShortcuts to true (previous value: false)
(23:36:39) INFO:    [Backend]:          Heroic: Setting addSteamShortcuts to true (previous value: false)
(23:36:40) INFO:    [Backend]:          Heroic: Setting discordRPC to true (previous value: undefined)
(23:36:44) INFO:    [Backend]:          Heroic: Setting libraryTopSection to "favourites" (previous value: "disabled")
```

### Steps to reproduce

0.	Invoke launcher.
	![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/42837531/96493fac-9f41-4cb9-9669-d16d44a20d32)
0.	Connect with Amazon.
	![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/42837531/47125326-e9b1-4968-8053-a0a4f9d4376c)
0.	Authenticate.

### Expected behavior

It should authenticate.

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS: cpe:/o:opensuse:tumbleweed:20230811

**Comment by rokejulianlockhart** [comment]
Huh. It worked the second time.
