### ISSUE TITLE
Cannot install Fallout 4 from GoG on Linux

### ISSUE THREAD

**Issue by Legoalda** [Heroic-Games-Launcher/HeroicGamesLauncher#2995]
### Describe the bug

When I try to install Fallout 4 "Fallout 4: Game of the Year Edition" there is this following message: "Cannot get game info"

### Add logs

```text
(21:09:06) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(21:09:06) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(21:09:06) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(21:09:06) INFO:    [Connection]:       Connectivity: check-online
(21:09:06) INFO:    [Connection]:       Pinging external endpoints
(21:09:06) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(21:09:06) WARNING: [Backend]:          Failed to register protocol with OS.
(21:09:06) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(21:09:06) INFO:    [Connection]:       Connectivity: online
(21:09:06) INFO:    [Gog]:              Checking if login is valid
(21:09:06) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:09:07) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(21:09:07) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(21:09:07) INFO:    [Gog]:              Saved username to config file
(21:09:07) INFO:    [Backend]:          

Heroic Version: 2.9.1 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Freedesktop SDK KERNEL: 6.4.10-arch1-1 ARCH: x64
CPU: AMD Ryzen 7 5800H with Radeon Graphics @3.38 GOVERNOR: schedutil
RAM: Total: 30.76 GiB Available: 24.28 GiB
GRAPHICS: GPU0: GA104M [GeForce RTX 3070 Mobile / Max-Q]  VRAM: 32MB GPU1: Cezanne VRAM: 512MB 
PROTOCOL: wayland

(21:09:08) INFO:    [Backend]:          Loading Screen Ready
(21:09:08) INFO:    [Frontend]:         Refreshing undefined Library
(21:09:08) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(21:09:08) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:09:08) INFO:    [Legendary]:        Refreshing library...
(21:09:08) INFO:    [Legendary]:        Refreshing Epic Games...
(21:09:08) INFO:    [Legendary]:        Game list updated, got 176 games & DLCs
(21:09:08) INFO:    [Backend]:          Frontend Ready
(21:09:08) INFO:    [Backend]:          Checking for current version changelog
(21:09:08) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(21:09:08) INFO:    [Gog]:              Getting GOG library
(21:09:08) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:09:09) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(21:09:09) INFO:    [Winetricks]:       Downloading Winetricks
(21:09:10) INFO:    [Gog]:              Saved games data
(21:09:10) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(21:09:13) INFO:    [Backend]:          Starting the Download Queue
(21:09:15) INFO:    [Gog]:              Found 2 game(s) to update
(21:09:15) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(21:09:16) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Fallout 4 Game of the Year Edition
(21:09:16) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:09:16) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:09:16) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Fallout 4 Game of the Year Edition
(21:09:16) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:09:16) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:09:16) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:09:16) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info <redacted> --token <redacted> --lang=en-US --os windows
(21:09:16) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info <redacted> --token <redacted> --lang=en-US --os windows
(21:09:16) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info <redacted> --token <redacted> --lang=en-US --os windows
(21:09:16) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info <redacted> --token <redacted> --lang=en-US --os windows
(21:09:16) WARNING: [Legendary]:        Failed to parse games from /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:468:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at Module.listUpdateableGames (/app/bin/heroic/resources/app.asar/build/electron/main.f23c4159.js:102:4644)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.f23c4159.js:191:3990
    at async node:electron/js2c/browser_init:2:98394
(21:09:16) INFO:    [Legendary]:        Found 0 games to update
(21:09:17) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:09:17) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:09:17) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info <redacted> --token <redacted> --lang=en-US --os windows
(21:09:17) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info <redacted> --token <redacted> --lang=en-US --os windows
(21:09:17) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:09:17) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(21:09:17) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info <redacted> --token <redacted> --lang=en-US --os windows
(21:09:18) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:09:18) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:09:18) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:09:18) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:09:18) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:09:18) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:09:18) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:09:18) ERROR:   [Frontend]:         Cannot get game info
(21:09:18) ERROR:   [Frontend]:         Cannot get game info
(21:09:18) ERROR:   [Frontend]:         Cannot get game info
(21:09:18) ERROR:   [Frontend]:         Cannot get game info
(21:09:18) ERROR:   [Frontend]:         Cannot get game info
(21:09:18) ERROR:   [Frontend]:         Cannot get game info
(21:09:18) ERROR:   [Frontend]:         Cannot get game info
```

### Steps to reproduce

1. Go to 'Library'
2. Click on 'Fallout 4: Game of the Year Edition'

### Expected behavior

The download and install of the game should start.

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/90921811/e2f8c93d-180d-4cb6-a5f2-1ec486804735)

### Heroic Version

Latest Stable

### System Information

- OS: Arch Linux x86_64 
- Kernel: 6.4.10-arch1-1 
- DE: Plasma 5.27.7
- CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 3.200GHz
- GPU: NVIDIA GeForce RTX 3070 Mobile / Max-Q
- RAM: 32GB

**Comment by imLinguin** [comment]
Could you try the workaround showcased in #2953 or try AppImage build from Heroic main branch, to see if this is the same issue?

**Comment by jkaart** [comment]
I have same problem with latest 2.9.1 version Heroic Launcher. I installed .deb package version in Ubuntu 22.04.
All other GOG games (what I own) loads just fine, but Fallout 4 GOTY do not.

**Comment by Etaash-mathamsetty** [comment]
> I have same problem with latest 2.9.1 version Heroic Launcher. I installed .deb package version in Ubuntu 22.04. All other GOG games (what I own) loads just fine, but Fallout 4 GOTY do not. Edit: and latest appimage ([this](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.9.1/Heroic-2.9.1.AppImage) one) does also same.

try this appimage: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/5833246055/job/15820247834

**Comment by jkaart** [comment]
> > I have same problem with latest 2.9.1 version Heroic Launcher. I installed .deb package version in Ubuntu 22.04. All other GOG games (what I own) loads just fine, but Fallout 4 GOTY do not. Edit: and latest appimage ([this](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.9.1/Heroic-2.9.1.AppImage) one) does also same.
> 
> try this appimage: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/5833246055/job/15820247834

This one works!

**Comment by Etaash-mathamsetty** [comment]
so that means the issue is already fixed and will be available next release :)

**Comment by Legoalda** [comment]
> > I have same problem with latest 2.9.1 version Heroic Launcher. I installed .deb package version in Ubuntu 22.04. All other GOG games (what I own) loads just fine, but Fallout 4 GOTY do not. Edit: and latest appimage ([this](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.9.1/Heroic-2.9.1.AppImage) one) does also same.
> 
> try this appimage: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/5833246055/job/15820247834

This AppImage is also working on my side :)

**Comment by Legoalda** [comment]
Upgraded to 2.9.2, this issue is fixed. Thanks :)
