### ISSUE TITLE
Cannot download Warhammer 40k: Rogue Trader

### ISSUE THREAD

**Issue by moose769** [Heroic-Games-Launcher/HeroicGamesLauncher#2998]
### Describe the bug

Trying install game but it only gives error "not installable", i had this game installed june but then i uninstalled and now i wanted to re-install it gives error message

### Add logs

```text
(15:55:58) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:55:58) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(15:55:58) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:55:58) INFO:    [Connection]:       Connectivity: check-online
(15:55:58) INFO:    [Connection]:       Pinging external endpoints
(15:55:58) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(15:55:58) WARNING: [Backend]:          Failed to register protocol with OS.
(15:55:58) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(15:55:58) INFO:    [Connection]:       Connectivity: online
(15:55:58) INFO:    [Backend]:          User Not Found, removing it from Store
(15:55:58) INFO:    [Gog]:              Checking if login is valid
(15:55:58) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:55:58) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(15:55:58) INFO:    [Backend]:          Loading Screen Ready
(15:55:58) INFO:    [Frontend]:         Refreshing undefined Library
(15:55:58) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(15:55:58) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:55:58) INFO:    [Legendary]:        Refreshing library...
(15:55:58) INFO:    [Backend]:          Frontend Ready
(15:55:58) INFO:    [Backend]:          Checking for current version changelog
(15:55:58) INFO:    [Gog]:              Getting GOG library
(15:55:58) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:55:59) INFO:    [Backend]:          

Heroic Version: 2.9.1 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Freedesktop SDK KERNEL: 6.2.0-26-generic ARCH: x64
CPU: Intel Gen Intel® Core™ i5-12600K @4.22 GOVERNOR: powersave
RAM: Total: 31.11 GiB Available: 26.25 GiB
GRAPHICS: GPU0: AlderLake-S GT1  VRAM: 256MB GPU1: GP102 [GeForce GTX 1080 Ti]  VRAM: 32MB 
PROTOCOL: x11

(15:55:59) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(15:55:59) INFO:    [Gog]:              Saved username to config file
(15:55:59) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:56:00) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Warhammer 40,000 Rogue Trader
(15:56:00) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Warhammer 40,000 Rogue Trader
(15:56:01) INFO:    [Winetricks]:       Downloading Winetricks
(15:56:02) WARNING: [Winetricks]:       Error Downloading Winetricks Error: timeout of 1000ms exceeded
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/app/bin/heroic/resources/app.asar/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
(15:56:03) INFO:    [Backend]:          Starting the Download Queue
(15:56:16) INFO:    [Gog]:              Saved games data
(15:56:16) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:56:16) INFO:    [Gog]:              Found 0 game(s) to update
```

### Steps to reproduce

1. Go to '...'Open Heroic
2. Click on '...'WH40k: Rogue Trader
3. Scroll down to '...'
4. See error Not installable

### Expected behavior

Nothing happens

### Screenshots

![Screenshot_20230814_112021](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/139578041/02d0441f-dddb-4798-bcdf-b0449e71e99d)

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]:KDE Neon latest

**Comment by imLinguin** [comment]
The game isn't out yet https://www.gog.com/pl/game/warhammer_40000_rogue_trader

**Comment by moose769** [comment]
I bought the beta release, it is out

**Comment by imLinguin** [comment]
Could you confirm this is also downloadable in GOG Galaxy?

**Comment by moose769** [comment]
It Was when i bought it, redeem code and then download, now it is not because i cannot redeem same code twice, this was not issue before, i have downloaded this couple of times before when i have try out different Linux distros this summer

**Comment by moose769** [comment]
Got  working it with Heroic 2.8, but not on 2.9 or 2.91
