### ISSUE TITLE
Error during installation of EOS Overlay

### ISSUE THREAD

**Issue by PaffcioStudio** [Heroic-Games-Launcher/HeroicGamesLauncher#3019]
### Describe the bug

I tried several times to log out and log back in to EPIC. Nothing helps. Downloading games from EPIC works fine, launching and installing also. Only I have a problem with the overlay.

`An error has occurred! Try logging out and logging into your Epic account.
Do you want to install the overlay? [T/n]:[cli] INFO: Preparing to start installing the overlay...[cli] INFO: Installation directory: C:\nAppData\nRoaming\nHeroic\nTools_overlay.
[INFO: Installation size: 330.82 MB
[cli] INFO: Download size: 141.52 MiBTraceback (most recent call last):
File "legendarycli.py", line 3069, in <module>.
File "legendary\cli.py", line 3018, in main
File "legendarycli.py", line 2268, in manage_eos_overlay
File "legendary\cli.py", line 4, in get_boolean_choice
EOFError: EOF when reading a line
[4300] Failed to execute 'cli' script due to unhandled exception!`

### Add logs

```text
(07:26:59) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(07:26:59) INFO:    [Legendary]:        Legendary location: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(07:26:59) INFO:    [Gog]:              GOGDL location: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(07:26:59) INFO:    [Connection]:       Connectivity: check-online
(07:26:59) INFO:    [Connection]:       Pinging external endpoints
(07:26:59) INFO:    [Nile]:             Refreshing library...
(07:26:59) INFO:    [Nile]:             Refreshing Amazon Games...
(07:26:59) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\nile_config C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile library sync
(07:26:59) INFO:    [Nile]:             Game list updated, got 35 games
(07:26:59) INFO:    [Backend]:          DRM module staus {
  "neifaoindggfcjicffkgpmnlppeffabd": {
    "name": "Google Widevine Windows CDM",
    "status": "new",
    "version": "1.0.2512.1"
  },
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(07:27:00) WARNING: [Backend]:          Protocol already registered.
(07:27:00) INFO:    [Connection]:       Connectivity: online
(07:27:00) INFO:    [Gog]:              Checking if login is valid
(07:27:00) INFO:    [Gog]:              Running command: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\aspir\AppData\Roaming\heroic\gog_store\auth.json auth
(07:27:05) INFO:    [Gog]:              Running command: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\aspir\AppData\Roaming\heroic\gog_store\auth.json --version
(07:27:05) WARNING: [Backend]:          Could not determine System Info
(07:27:06) INFO:    [Backend]:          Loading Screen Ready
(07:27:06) INFO:    [Nile]:             Saved user data to config file
(07:27:06) INFO:    [Frontend]:         Refreshing undefined Library
(07:27:06) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(07:27:06) INFO:    [Gog]:              Running command: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\aspir\AppData\Roaming\heroic\gog_store\auth.json auth
(07:27:06) INFO:    [Legendary]:        Refreshing library...
(07:27:06) INFO:    [Legendary]:        Refreshing Epic Games...
(07:27:07) INFO:    [Nile]:             Refreshing library...
(07:27:07) INFO:    [Nile]:             Refreshing Amazon Games...
(07:27:07) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\nile_config C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile library sync
(07:27:07) INFO:    [Nile]:             Game list updated, got 35 games
(07:27:08) INFO:    [Legendary]:        Game list updated, got 380 games & DLCs
(07:27:08) INFO:    [Backend]:          Frontend Ready
(07:27:08) INFO:    [Gog]:              Getting GOG library
(07:27:08) INFO:    [Gog]:              Running command: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\aspir\AppData\Roaming\heroic\gog_store\auth.json auth
(07:27:09) INFO:    [Backend]:          Checking for new Heroic Updates
(07:27:09) INFO:    [Backend]:          Checking for current version changelog
(07:27:09) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(07:27:09) INFO:    [Gog]:              Saved username to config file
(07:27:11) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\nile_config C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile --version
(07:27:13) INFO:    [Backend]:          Starting the Download Queue
(07:27:16) INFO:    [Gog]:              Running command: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\aspir\AppData\Roaming\heroic\gog_store\auth.json auth
(07:27:20) INFO:    [Gog]:              Running command: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\aspir\AppData\Roaming\heroic\gog_store\auth.json auth
(07:27:23) INFO:    [Backend]:          VCRuntime is installed
(07:27:25) INFO:    [Gog]:              Saved games data
(07:27:25) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(07:27:27) INFO:    [Gog]:              Found 2 game(s) to update
(07:27:28) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(07:27:35) INFO:    [Legendary]:        Found 0 games to update
(07:27:35) INFO:    [Nile]:             Looking for updates...
(07:27:35) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\nile_config C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile list-updates --json
(07:32:08) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(07:32:08) INFO:    [Gog]:              Running command: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\aspir\AppData\Roaming\heroic\gog_store\auth.json --version
(07:32:08) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\nile_config C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile --version
(07:32:08) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(07:32:09) INFO:    [Legendary]:        Getting EOS Overlay install size: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay install --path C:\Users\aspir\AppData\Roaming\heroic\tools\eos_overlay
(07:32:09) INFO:    [Backend]:          Preventing machine to sleep
(07:32:12) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay install --path C:\Users\aspir\AppData\Roaming\heroic\tools\eos_overlay"
(07:32:12) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(07:32:14) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(07:32:14) ERROR:   [Backend]:          Aborting not possible. Could not find a matching abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(07:35:57) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(07:35:57) INFO:    [Gog]:              Running command: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\aspir\AppData\Roaming\heroic\gog_store\auth.json --version
(07:35:58) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\nile_config C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile --version
(07:36:00) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(07:36:01) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(07:36:06) INFO:    [Backend]:          Exitting to tray instead of quitting
(07:41:05) INFO:    [Legendary]:        Logging out: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary auth --delete
(07:41:07) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary cleanup
(07:41:07) INFO:    [Nile]:             Saved user data to config file
(07:41:07) INFO:    [Frontend]:         Refreshing undefined Library
(07:41:07) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(07:41:07) INFO:    [Gog]:              Running command: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\aspir\AppData\Roaming\heroic\gog_store\auth.json auth
(07:41:07) INFO:    [Legendary]:        Refreshing library...
(07:41:07) INFO:    [Nile]:             Refreshing library...
(07:41:07) INFO:    [Nile]:             Refreshing Amazon Games...
(07:41:07) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\nile_config C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile library sync
(07:41:07) INFO:    [Nile]:             Game list updated, got 35 games
(07:41:07) INFO:    [Backend]:          Checking for new Heroic Updates
(07:41:07) INFO:    [Backend]:          Checking for current version changelog
(07:41:08) INFO:    [Gog]:              Getting GOG library
(07:41:08) INFO:    [Gog]:              Running command: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\aspir\AppData\Roaming\heroic\gog_store\auth.json auth
(07:41:10) INFO:    [Gog]:              Running command: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\aspir\AppData\Roaming\heroic\gog_store\auth.json auth
(07:41:11) INFO:    [Gog]:              Running command: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\aspir\AppData\Roaming\heroic\gog_store\auth.json auth
(07:41:14) INFO:    [Gog]:              Saved games data
(07:41:14) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(07:41:14) INFO:    [Gog]:              Found 2 game(s) to update
(07:41:14) INFO:    [Nile]:             Looking for updates...
(07:41:14) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\nile_config C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile list-updates --json
(07:42:26) INFO:    [Legendary]:        Logging in: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary auth --code <redacted>
(07:42:28) INFO:    [Frontend]:         Refreshing legendary Library
(07:42:28) INFO:    [Legendary]:        Refreshing library...
(07:42:28) INFO:    [Legendary]:        Refreshing Epic Games...
(07:42:29) ERROR:   [Legendary]:        Failed to parse bobcat.json
(07:42:29) ERROR:   [Legendary]:        Failed to parse huddle.json
(07:42:29) ERROR:   [Legendary]:        Failed to parse UnrealTournamentDev.json
(07:42:29) INFO:    [Legendary]:        Game list updated, got 380 games & DLCs
(07:42:29) INFO:    [Frontend]:         No cache found, getting data from legendary...
(07:42:29) INFO:    [Legendary]:        Refreshing library...
(07:42:29) INFO:    [Legendary]:        Refreshing Epic Games...
(07:42:29) ERROR:   [Legendary]:        Failed to parse bobcat.json
(07:42:29) ERROR:   [Legendary]:        Failed to parse huddle.json
(07:42:29) ERROR:   [Legendary]:        Failed to parse UnrealTournamentDev.json
(07:42:29) INFO:    [Legendary]:        Game list updated, got 380 games & DLCs
(07:42:29) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(07:42:29) INFO:    [Frontend]:         Force Update
(07:42:29) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(07:42:33) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(07:42:33) INFO:    [Gog]:              Running command: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\aspir\AppData\Roaming\heroic\gog_store\auth.json --version
(07:42:33) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\nile_config C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile --version
(07:42:33) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(07:42:35) INFO:    [Legendary]:        Getting EOS Overlay install size: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay install --path C:\Users\aspir\AppData\Roaming\heroic\tools\eos_overlay
(07:42:35) INFO:    [Backend]:          Preventing machine to sleep
(07:42:36) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay install --path C:\Users\aspir\AppData\Roaming\heroic\tools\eos_overlay"
(07:42:36) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(07:42:37) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(07:42:38) ERROR:   [Backend]:          Aborting not possible. Could not find a matching abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(07:45:04) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(07:45:04) INFO:    [Gog]:              Running command: C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\aspir\AppData\Roaming\heroic\gog_store\auth.json --version
(07:45:04) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\nile_config C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile --version
(07:45:04) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(07:45:05) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=C:\Users\aspir\AppData\Roaming\heroic\legendaryConfig C:\Users\aspir\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
```

### Steps to reproduce

1. I go into settings and log out of Epic Games.
2. Closing the Heroic program
3. I launch Heroic, log back into Epic using two-step verification (OK!).
4. Every attempt to install the overlay ends with an error.

### Expected behavior

I just expected the overlay to install ;C

### Heroic Version

Latest Stable

### System Information

- Windows 11 Pro x64

**Comment by arielj** [comment]
Check https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2905, it's a known issue. It was fixed in the development branch and will be included in a future release.

Read that other issue for the workaround that you can use in the meantime.

Closing this as duplicated
