### ISSUE TITLE
Heroic white screens seconds after launch

### ISSUE THREAD

**Issue by GetPsyched** [Heroic-Games-Launcher/HeroicGamesLauncher#3032]
### Describe the bug

When I open Heroic, it installs `winetricks` but right before the next log entry, it white screens.
```
(13:36:21) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(13:36:23) WARNING: [DXVKInstaller]:    No GPU with Vulkan 1.1 support found, DXVK will not work
(13:36:23) INFO:    [Winetricks]:       Downloading Winetricks
(13:36:26) INFO:    [Backend]:          Starting the Download Queue
```

I have captured a warning that is through right after the winetricks download. I have put it in logs.

### Add logs

```text
(13:35:45) WARNING: [Winetricks]:       Error Downloading Winetricks Error: error request aborted
    at createError (/nix/store/jlrqmih3jj1i48lv04sjz6vdszk822jm-heroic-unwrapped-2.9.1/share/heroic/node_modules/axios/lib/core/createError.js:16:15)
    at IncomingMessage.handlerStreamAborted (/nix/store/jlrqmih3jj1i48lv04sjz6vdszk822jm-heroic-unwrapped-2.9.1/share/heroic/node_modules/axios/lib/adapters/http.js:301:18)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage._destroy (node:_http_incoming:224:10)
    at _destroy (node:internal/streams/destroy:109:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:71:5)
    at TLSSocket.socketCloseListener (node:_http_client:462:11)
    at TLSSocket.emit (node:events:525:35)
    at node:net:322:12
    at TCP.done (node:_tls_wrap:588:7) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 1000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.26.1'
    },
    method: 'get',
    url: 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks',
    data: undefined
  },
  code: 'ERR_REQUEST_ABORTED',
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'raw.githubusercontent.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 11,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'raw.githubusercontent.com',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      timeout: 1000,
      [Symbol(res)]: null,
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 1814,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 3472,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: true,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 1826,
        [Symbol(triggerId)]: 1817
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 733051,
      [Symbol(kBytesWritten)]: 182,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'GET /Winetricks/winetricks/master/src/winetricks HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/0.26.1\r\n' +
      'Host: raw.githubusercontent.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/Winetricks/winetricks/master/src/winetricks',
    _ended: false,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: false,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: true,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 200,
      statusMessage: 'OK',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 48,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'raw.githubusercontent.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks',
      _timeout: null,
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kUniqueHeaders)]: null
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

### Steps to reproduce

1. Install heroic on NixOS
2. Run heroic
3. See error

### Expected behavior

Don't white screen

### Heroic Version

Latest Stable

### System Information

- OS: NixOS 23.11.20230830.e7f38be (Tapir) x86_64
- Host: TGL Scala_TLS
- Kernel: 6.1.49
- Packages: 1245 (nix-system), 1474 (nix-user)
- Shell: bash 5.2.15
- Resolution: 1920x1080
- DE: none+i3
- WM: i3
- CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz
- GPU: NVIDIA GeForce RTX 3050 Ti Mobile
- GPU: Intel TigerLake-H GT1 [UHD Graphics]
- Memory: 3755MiB / 15784MiB

### Additional information

I suspect this issue is with `i3`, my tiling window manager, as I get this output in `stalone` when I close heroic:
```
X11 error: BadWindow (invalid Window parameter) (request: X_ConfigureWindow, resource 0xc)
X11 error: BadWindow (invalid Window parameter) (request: X_MapWindow, resource 0x8)
X11 error: BadWindow (invalid Window parameter) (request: X_GetWindowAttributes, resource 0x3)
X11 error 3 detected at debug.c:156:print_icon_data
X11 error: BadWindow (invalid Window parameter) (request: X_ChangeWindowAttributes, resource 0x2)
X11 error: BadWindow (invalid Window parameter) (request: X_UnmapWindow, resource 0xa)
X11 error: BadWindow (invalid Window parameter) (request: X_ReparentWindow, resource 0x7)
X11 error: BadWindow (invalid Window parameter) (request: X_ConfigureWindow, resource 0xc)
X11 error: BadWindow (invalid Window parameter) (request: X_MapWindow, resource 0x8)
X11 error 3 detected at xutils.c:115:x11_get_server_timestamp
X11 error: BadWindow (invalid Window parameter) (request: X_SendEvent, resource 0x19)
X11 error 3 detected at xutils.c:260:x11_get_window_size
```

**Comment by nicomem** [comment]
Heroic also blanks out for me after a few seconds. I am also on NixOS but use KDE Plasma as a window manager

Operating System: NixOS 23.11
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.5.1 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800X3D 8-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: AMD Radeon RX 6950 XT

**Comment by Nocccer** [comment]
Has nothing todo with winetricks. Has more todo with nixos and maybe missing configs/libs

**Comment by GetPsyched** [comment]
I had used heroic from [nixpkgs](https://github.com/NixOS/nixpkgs/)

Seems like installing the AppImage works just fine. Likely an issue with the Nix expression which I will file an issue for. Thanks for the help.
