### ISSUE TITLE
Changing game executable location results in error in handler for 'launch'

### ISSUE THREAD

**Issue by Dandraghas** [Heroic-Games-Launcher/HeroicGamesLauncher#3049]
### Describe the bug

When i change executable location and then trying to launch game it will be stuck at 'Launching':
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/91272905/301e82e1-7975-412d-b5fe-28bb3e435bfe)

and this error occurs:
```
Error occurred in handler for 'launch': TypeError: Cannot read properties of undefined (reading 'name')
    at checkWineBeforeLaunch (/opt/Heroic/resources/app.asar/build/electron/main.c2fc9376.js:123:1076)
    at async /opt/Heroic/resources/app.asar/build/electron/main.c2fc9376.js:198:151
    at async node:electron/js2c/browser_init:2:98394
```

the only way to fix this is to relaunch heroic

### Add logs

```text
(15:41:54) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(15:41:54) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:41:54) INFO:    [Connection]:       Connectivity: check-online
(15:41:54) INFO:    [Connection]:       Pinging external endpoints
(15:41:54) INFO:    [Nile]:             Refreshing library...
(15:41:54) INFO:    [Nile]:             Refreshing Amazon Games...
(15:41:54) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/dandraghas/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(15:41:54) INFO:    [Nile]:             Game list updated, got 0 games
(15:41:54) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(15:41:55) WARNING: [Backend]:          Protocol already registered.
(15:41:55) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/dandraghas/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:41:55) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/dandraghas/.config/heroic/gog_store/auth.json --version
(15:41:55) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/dandraghas/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(15:41:55) INFO:    [Connection]:       Connectivity: online
(15:41:55) INFO:    [Gog]:              Checking if login is valid
(15:41:55) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/dandraghas/.config/heroic/gog_store/auth.json auth
(15:41:55) INFO:    [Backend]:          
System Information:
CPU: 8x Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz
Memory: 16.68 GB (used: 8.9 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti]
    IDs: D=1c82 V=10de SD=3764 SV=1458
    Driver: nvidia
OS: Arch Linux 6.5.2-zen1-1-zen (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.9.2 Boa Hancock
  Legendary: 0.20.32 Dark Energy (hotfix #6)
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(15:41:55) INFO:    [Backend]:          Loading Screen Ready
(15:41:55) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(15:41:55) INFO:    [Nile]:             Saved user data to config file
(15:41:55) INFO:    [Frontend]:         Refreshing undefined Library
(15:41:55) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(15:41:55) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/dandraghas/.config/heroic/gog_store/auth.json auth
(15:41:55) INFO:    [Legendary]:        Refreshing library...
(15:41:55) INFO:    [Legendary]:        Refreshing Epic Games...
(15:41:55) INFO:    [Nile]:             Refreshing library...
(15:41:55) INFO:    [Nile]:             Refreshing Amazon Games...
(15:41:55) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/dandraghas/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(15:41:55) INFO:    [Nile]:             Game list updated, got 0 games
(15:41:55) INFO:    [Legendary]:        Game list updated, got 46 games & DLCs
(15:41:55) INFO:    [Backend]:          Frontend Ready
(15:41:55) INFO:    [Backend]:          Checking for new Heroic Updates
(15:41:55) INFO:    [Backend]:          Checking for current version changelog
(15:41:55) INFO:    [Gog]:              Getting GOG library
(15:41:55) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/dandraghas/.config/heroic/gog_store/auth.json auth
(15:41:55) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/dandraghas/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:41:55) INFO:    [Gog]:              Saved username to config file
(15:41:56) INFO:    [Gog]:              Saved games data
(15:41:56) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:41:56) INFO:    [Gog]:              Found 0 game(s) to update
(15:41:56) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=/home/dandraghas/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:41:57) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(15:41:57) INFO:    [Winetricks]:       Downloading Winetricks
(15:41:57) WARNING: [Legendary]:        Game with AppName 0a2d9f6403244d12969e11da6713137b is installed but was not found on account
(15:41:57) WARNING: [Legendary]:        Game with AppName 592c359fb0e0413fb46dee2d24448eb4 is installed but was not found on account
(15:41:57) WARNING: [Legendary]:        Game with AppName 963137e4c29d4c79a81323b8fab03a40 is installed but was not found on account
(15:41:57) WARNING: [Legendary]:        Game with AppName Sugar is installed but was not found on account
(15:41:57) WARNING: [Legendary]:        Game with AppName Turtle is installed but was not found on account
(15:41:57) WARNING: [Legendary]:        Game with AppName a1e2ce30defe4a9187ebc14fc9d2bd8b is installed but was not found on account
(15:41:57) WARNING: [Legendary]:        Game with AppName a99769d95d8f400baad1f67ab5dfe508 is installed but was not found on account
(15:41:57) DEBUG:   [Legendary]:        Update is available for aafc587fbf654758802c8e41e4fb3255: 357.9.win != 358.7.win
(15:41:57) DEBUG:   [Legendary]:        Update is available for bcbc03d8812a44c18f41cf7d5f849265: 1.16.1-f3 != 1.17.1-f4-fixed
(15:41:57) INFO:    [Legendary]:        Found 3 games to update
(15:41:57) INFO:    [Nile]:             Looking for updates...
(15:41:57) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/dandraghas/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json
(15:41:57) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for [REDACTED]
(15:41:57) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for [REDACTED]
(15:41:57) WARNING: [Backend]:          getExtraInfo not implemented on Sideload Game Manager. called for appName = 3CJknwDWcficSTYTxFFGhf
(15:41:58) INFO:    [Frontend]:         No cache found, getting data from nile...
(15:41:58) INFO:    [Nile]:             Refreshing library...
(15:41:58) INFO:    [Nile]:             Refreshing Amazon Games...
(15:41:58) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/dandraghas/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(15:41:58) INFO:    [Nile]:             Game list updated, got 0 games
(15:41:58) WARNING: [Backend]:          getExtraInfo not implemented on Sideload Game Manager. called for appName = 3CJknwDWcficSTYTxFFGhf
(15:41:59) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(15:42:00) INFO:    [Backend]:          Starting the Download Queue
(15:42:01) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(15:42:07) INFO:    [Backend]:          3CJknwDWcficSTYTxFFGhf: Setting wineVersion to {"bin":"/home/dandraghas/.config/heroic/tools/wine/Wine-GE-Proton8-14/bin/wine","name":"Wine - Wine-GE-Proton8-14","type":"wine","lib":"/home/dandraghas/.config/heroic/tools/wine/Wine-GE-Proton8-14/lib64","lib32":"/home/dandraghas/.config/heroic/tools/wine/Wine-GE-Proton8-14/lib","wineserver":"/home/dandraghas/.config/heroic/tools/wine/Wine-GE-Proton8-14/bin/wineserver"}
(15:42:08) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(15:42:15) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(15:42:39) INFO:    [Backend]:          Writing config for 3CJknwDWcficSTYTxFFGhf
(15:42:39) INFO:    [Backend]:          Changed config: wineVersion from {"bin":"/home/dandraghas/.config/heroic/tools/wine/Wine-GE-Proton8-14/bin/wine","name":"Wine - Wine-GE-Proton8-14","type":"wine","lib":"/home/dandraghas/.config/heroic/tools/wine/Wine-GE-Proton8-14/lib64","lib32":"/home/dandraghas/.config/heroic/tools/wine/Wine-GE-Proton8-14/lib","wineserver":"/home/dandraghas/.config/heroic/tools/wine/Wine-GE-Proton8-14/bin/wineserver"} to undefined
(15:42:39) INFO:    [Frontend]:         Refreshing undefined Library
(15:42:39) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(15:42:39) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/dandraghas/.config/heroic/gog_store/auth.json auth
(15:42:39) INFO:    [Legendary]:        Refreshing library...
(15:42:39) INFO:    [Legendary]:        Refreshing Epic Games...
(15:42:39) INFO:    [Nile]:             Refreshing library...
(15:42:39) INFO:    [Nile]:             Refreshing Amazon Games...
(15:42:39) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/dandraghas/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(15:42:39) INFO:    [Nile]:             Game list updated, got 0 games
(15:42:39) INFO:    [Legendary]:        Game list updated, got 46 games & DLCs
(15:42:39) INFO:    [Gog]:              Getting GOG library
(15:42:39) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/dandraghas/.config/heroic/gog_store/auth.json auth
(15:42:39) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/dandraghas/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:42:40) INFO:    [Gog]:              Saved games data
(15:42:40) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:42:40) INFO:    [Gog]:              Found 0 game(s) to update
(15:42:40) WARNING: [Backend]:          getExtraInfo not implemented on Sideload Game Manager. called for appName = 3CJknwDWcficSTYTxFFGhf
(15:42:40) WARNING: [Backend]:          getExtraInfo not implemented on Sideload Game Manager. called for appName = 3CJknwDWcficSTYTxFFGhf
(15:42:40) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=/home/dandraghas/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:42:41) WARNING: [Legendary]:        Game with AppName 0a2d9f6403244d12969e11da6713137b is installed but was not found on account
(15:42:41) WARNING: [Legendary]:        Game with AppName 592c359fb0e0413fb46dee2d24448eb4 is installed but was not found on account
(15:42:41) WARNING: [Legendary]:        Game with AppName 963137e4c29d4c79a81323b8fab03a40 is installed but was not found on account
(15:42:41) WARNING: [Legendary]:        Game with AppName Sugar is installed but was not found on account
(15:42:41) WARNING: [Legendary]:        Game with AppName Turtle is installed but was not found on account
(15:42:41) WARNING: [Legendary]:        Game with AppName a1e2ce30defe4a9187ebc14fc9d2bd8b is installed but was not found on account
(15:42:41) WARNING: [Legendary]:        Game with AppName a99769d95d8f400baad1f67ab5dfe508 is installed but was not found on account
(15:42:41) DEBUG:   [Legendary]:        Update is available for aafc587fbf654758802c8e41e4fb3255: 357.9.win != 358.7.win
(15:42:41) DEBUG:   [Legendary]:        Update is available for bcbc03d8812a44c18f41cf7d5f849265: 1.16.1-f3 != 1.17.1-f4-fixed
(15:42:41) INFO:    [Legendary]:        Found 3 games to update
(15:42:41) INFO:    [Nile]:             Looking for updates...
(15:42:41) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/dandraghas/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json
(15:42:41) INFO:    [Frontend]:         No cache found, getting data from nile...
(15:42:41) INFO:    [Nile]:             Refreshing library...
(15:42:41) INFO:    [Nile]:             Refreshing Amazon Games...
(15:42:41) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/dandraghas/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(15:42:41) INFO:    [Nile]:             Game list updated, got 0 games
(15:42:41) WARNING: [Backend]:          getExtraInfo not implemented on Sideload Game Manager. called for appName = 3CJknwDWcficSTYTxFFGhf
(15:42:52) INFO:    [Backend]:          Launching [REDACTED] (3CJknwDWcficSTYTxFFGhf)
(15:42:52) INFO:    [Backend]:          Preventing display from sleep
(15:42:53) INFO:    [Backend]:          Preventing machine to sleep
(15:42:53) WARNING: [Backend]:          getExtraInfo not implemented on Sideload Game Manager. called for appName = 3CJknwDWcficSTYTxFFGhf
```

### Steps to reproduce

1. Go to sideloaded game page
2. Press 'Edit App/Game'
3. Specify location for executable
4. Try to launch game
5. See error

### Expected behavior

changing executable location dont cause error

### Heroic Version

Latest Stable

### System Information

- OS Arch Linux

### Additional information

heroic can't capture this error for some reason, it's not even written to log file, i got this error from terminal. Also when i change location of executable wine version will reset to system

**Comment by arielj** [comment]
Is this still an issue in Heroic 2.11.0? if it is please share a game log, not heroic's general log

**Comment by arielj** [comment]
closing as there's been no follow up after my question in 2023
