### ISSUE TITLE
HowLongToBeat integration doesn't work

### ISSUE THREAD

**Issue by Spynacz** [Heroic-Games-Launcher/HeroicGamesLauncher#3069]
### Describe the bug

HowLongToBeat menu doesn't appear for any game. Request fails with error 403.

### Add logs

```text
(15:04:50) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(15:04:50) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:04:50) INFO:    [Connection]:       Connectivity: check-online
(15:04:50) INFO:    [Connection]:       Pinging external endpoints
(15:04:50) INFO:    [Nile]:             Refreshing library...
(15:04:50) INFO:    [Nile]:             Refreshing Amazon Games...
(15:04:50) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/mateusz/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(15:04:50) INFO:    [Nile]:             Game list updated, got 41 games
(15:04:50) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(15:04:50) WARNING: [Backend]:          Protocol already registered.
(15:04:50) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/mateusz/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:04:50) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mateusz/.config/heroic/gog_store/auth.json --version
(15:04:50) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/mateusz/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(15:04:50) INFO:    [Connection]:       Connectivity: online
(15:04:50) INFO:    [Gog]:              Checking if login is valid
(15:04:50) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mateusz/.config/heroic/gog_store/auth.json auth
(15:04:50) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(15:04:50) INFO:    [Backend]:          
System Information:
CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
Memory: 8.28 GB (used: 3.34 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GM204 [GeForce GTX 970]
    IDs: D=13c2 V=10de SD=3160 SV=1462
    Driver: nvidia
OS: EndeavourOS 6.5.3-arch1-1 (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.9.2 Boa Hancock
  Legendary: 0.20.32 Dark Energy (hotfix #6)
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(15:04:50) INFO:    [Backend]:          Loading Screen Ready
(15:04:50) INFO:    [Nile]:             Saved user data to config file
(15:04:50) INFO:    [Frontend]:         Refreshing undefined Library
(15:04:50) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(15:04:50) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mateusz/.config/heroic/gog_store/auth.json auth
(15:04:50) INFO:    [Legendary]:        Refreshing library...
(15:04:50) INFO:    [Legendary]:        Refreshing Epic Games...
(15:04:50) INFO:    [Nile]:             Refreshing library...
(15:04:50) INFO:    [Nile]:             Refreshing Amazon Games...
(15:04:50) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/mateusz/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(15:04:50) INFO:    [Nile]:             Game list updated, got 41 games
(15:04:51) INFO:    [Legendary]:        Game list updated, got 356 games & DLCs
(15:04:51) INFO:    [Backend]:          Frontend Ready
(15:04:51) INFO:    [Gog]:              Saved username to config file
(15:04:51) INFO:    [Backend]:          Checking for new Heroic Updates
(15:04:51) INFO:    [Gog]:              Getting GOG library
(15:04:51) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mateusz/.config/heroic/gog_store/auth.json auth
(15:04:51) INFO:    [Backend]:          Checking for current version changelog
(15:04:51) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/mateusz/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:04:51) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mateusz/.config/heroic/gog_store/auth.json auth
(15:04:52) INFO:    [Winetricks]:       Downloading Winetricks
(15:04:52) INFO:    [Gog]:              Saved games data
(15:04:53) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:04:53) INFO:    [Gog]:              Found 0 game(s) to update
(15:04:53) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=/home/mateusz/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:04:53) DEBUG:   [Legendary]:        Update is available for Sugar: BC2_Update44+427398 != BC2_Update45+430366
(15:04:53) INFO:    [Legendary]:        Found 1 game to update
(15:04:53) INFO:    [Nile]:             Looking for updates...
(15:04:53) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/mateusz/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json
(15:04:56) INFO:    [Backend]:          Starting the Download Queue
(15:04:57) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for BioShock Infinite Complete Edition
(15:04:57) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for BioShock Infinite Complete Edition
(15:04:57) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for BioShock Infinite Complete Edition
(15:04:57) INFO:    [ExtraGameInfo]:    Getting GamesDB data for BioShock Infinite Complete Edition
(15:04:57) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for BioShock Infinite Complete Edition
(15:04:57) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for BioShock Infinite Complete Edition
(15:04:57) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for BioShock Infinite Complete Edition
(15:04:57) INFO:    [ExtraGameInfo]:    Getting GamesDB data for BioShock Infinite Complete Edition
(15:04:57) INFO:    [Legendary]:        Getting more details with 'legendary info'
(15:04:57) INFO:    [Legendary]:        Getting more details with 'legendary info'
(15:04:57) ERROR:   [ExtraGameInfo]:    Was not able to get HowLongToBeat data for BioShock Infinite Complete Edition Error: Error: Request failed with status code 403
    at HltbSearch.<anonymous> (/opt/Heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (/opt/Heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(15:04:57) ERROR:   [ExtraGameInfo]:    Was not able to get HowLongToBeat data for BioShock Infinite Complete Edition Error: Error: Request failed with status code 403
    at HltbSearch.<anonymous> (/opt/Heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (/opt/Heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(15:04:57) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/mateusz/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info f9d6f0530ea140909f8e8a997a7532d7 --json --platform Windows
(15:04:57) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/mateusz/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info f9d6f0530ea140909f8e8a997a7532d7 --json --platform Windows
(15:04:58) DEBUG:   [Backend]:          ProtonDB data for 8870 {"bestReportedTier":"platinum","confidence":"strong","score":0.6,"tier":"gold","total":93,"trendingTier":"gold"}
(15:04:58) DEBUG:   [Backend]:          ProtonDB data for 8870 {"bestReportedTier":"platinum","confidence":"strong","score":0.6,"tier":"gold","total":93,"trendingTier":"gold"}
(15:04:58) DEBUG:   [Backend]:          SteamDeck data for 8870 {"success":1,"results":{"appid":8870,"resolved_category":2,"resolved_items":[{"display_type":3,"loc_token":"#SteamDeckVerified_TestResult_TextInputDoesNotAutomaticallyInvokesKeyboard"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultControllerConfigFullyFunctional"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_ControllerGlyphsMatchDeckDevice"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_InterfaceTextIsLegible"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultConfigurationIsPerformant"},{"display_type":1,"loc_token":"#SteamDeckVerified_TestResult_ExternalControllersNotSupportedPrimaryPlayer"}],"steam_deck_blog_url":"","search_id":null}}
(15:04:58) DEBUG:   [Backend]:          SteamDeck data for 8870 {"success":1,"results":{"appid":8870,"resolved_category":2,"resolved_items":[{"display_type":3,"loc_token":"#SteamDeckVerified_TestResult_TextInputDoesNotAutomaticallyInvokesKeyboard"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultControllerConfigFullyFunctional"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_ControllerGlyphsMatchDeckDevice"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_InterfaceTextIsLegible"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultConfigurationIsPerformant"},{"display_type":1,"loc_token":"#SteamDeckVerified_TestResult_ExternalControllersNotSupportedPrimaryPlayer"}],"steam_deck_blog_url":"","search_id":null}}
(15:04:58) INFO:    [Legendary]:        Getting Info from Epic API
```

### Steps to reproduce

1. Go to any game
2. There's no HowLongToBeat section

### Expected behavior

HowLongToBeat menu shows up.

### Heroic Version

Latest Stable

### System Information

- OS: EndeavourOS 6.5.3-arch1-1
- Heroic from AUR (heroic-games-launcher-bin 2.9.2-2)

**Comment by arielj** [comment]
HLTB integration is currently broken because they changed their API, we'll probably remove the future until a workaround is found.
