### ISSUE TITLE
Unable to log into an Epic account using both the naive and alternative method

### ISSUE THREAD

**Issue by Plexprofile** [Heroic-Games-Launcher/HeroicGamesLauncher#3080]
### Describe the bug

An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Testing existing login data if present...Traceback (most recent call last):
File "urllib3\connectionpool.py", line 700, in urlopen
File "urllib3\connectionpool.py", line 994, in _prepare_proxyFile "urllib3\connection.py", line 364, in connect
File "urllib3\connection.py", line 501, in _connect_tls_proxy
File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
File "ssl.py", line 500, in wrap_socket
File "ssl.py", line 1040, in _createFile "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "requests\adapters.py", line 489, in send
File "urllib3\connectionpool.py", line 785, in urlopen
File "urllib3\util\retry.py", line 592, in incrementurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.legendary.gl', port=443): Max retries exceeded with url: /v1/version.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "legendary\cli.py", line 3069, in <module>
File "legendary\cli.py", line 2978, in main
File "legendary\cli.py", line 92, in authFile "legendary\core.py", line 265, in check_for_updates
File "legendary\api\lgd.py", line 21, in get_version_information
File "requests\sessions.py", line 600, in getFile "requests\sessions.py", line 587, in request
File "requests\sessions.py", line 701, in send
File "requests\adapters.py", line 563, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.legendary.gl', port=443): Max retries exceeded with url: /v1/version.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))[5520] Failed to execute script 'cli' due to unhandled exception!

### Add logs

```text
.
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

.

### Heroic Version

Latest Stable

### System Information

Windows 10 22H2 LTSC

**Comment by arielj** [comment]
This seems to be a connectivity issue. Is this still happening in Heroic 2.11.0?

I'd suggest trying with a VPN or setting google's DNS servers.

We can reopen the issue if this is still happening after trying those things, closing it for now.

**Comment by karaushu** [comment]
Also have SSL error, can confirm - VPN helps, seems to be a connectivity issue ( 2.11.0).
