### ISSUE TITLE
Not being able to update Fortnite

### ISSUE THREAD

**Issue by MarwanMahboub** [Heroic-Games-Launcher/HeroicGamesLauncher#3083]
### Describe the bug

Error on updating fortnite because of additional assets

I think the issue is that it requires you to input a choice to install additional assets like hd_textures etc so when legendary uses the install/update command and gets no response it stops it (maybe add a function to press enter or to have a pop-up to choose what do you want to install).

### Add logs

```text
Error:
An error has occurred! Try to Logout and Login on your Epic account.
You are about to install Fortnite, this application supports selective downloads.
The following optional packs are available (tag - name):
* dx12 - DirectX 12 Shaders
* hd_textures - High Resolution Textures
* lang_cn -[Core] INFO: Trying to re-use existing login session...Traceback (most recent call last):
File "legendary\cli.py", line 3069, in <module>File "legendary\cli.py", line 2986, in main
File "legendary\cli.py", line 923, in install_game
File "legendary\utils\cli.py", line 56, in sdl_prompt
File "encodings\cp1252.py", line 19, in encodeUnicodeEncodeError: 'charmap' codec can't encode characters in position 16-21: character maps to <undefined>
[2112] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1.open heroic
2.oh games got an update
3.oh it shows this error message and can't update
4.cry and install epic games launcher again
5.not being able to import my game and having to install it again with my slow internet
6.cry and copy it again from a friend 
7.uses epic games launcher and keeps waiting for the lord to fix heroic so i don't use this bloated mess
8.sleep

### Expected behavior

To update and never use epic games launcher again :( 

### Heroic Version

Latest Stable

### System Information

- OS Windows 10 (i don't use arch yet)

### Additional information

Please fix or else i will have to use epic games launcher again.

**Comment by Leclowndu93150** [comment]
same

**Comment by viasux** [comment]
same
