### ISSUE TITLE
Can't launch any game from Epic Games Store or GOG.

### ISSUE THREAD

**Issue by Stepan-Savchuk** [Heroic-Games-Launcher/HeroicGamesLauncher#3145]
### Describe the bug

I cannot launch any game from Heroic. Doesn't matter which Wine/Proton I use or what game I am trying to launch, it just keeps hanging without any visible progress. There is no such problems with Steam or Lutris.
Thanks and good luck.

### Add logs

```text
Launching of GTAV from EGS:
 
─λ heroic

DevTools listening on ws://127.0.0.1:9222/devtools/browser/92cbd780-7ea8-4df4-ba4b-5a75609e4b0e
(15:28:16) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(15:28:16) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:28:16) INFO:    [Connection]:       Connectivity: check-online
(15:28:16) INFO:    [Connection]:       Pinging external endpoints
(15:28:16) INFO:    [Backend]:          DRM module staus {
oimompecagnajdejgnnjijobebaeigek: {
name: 'Widevine Content Decryption Module',
status: 'new',
version: '4.10.2710.0'
}
}
APPIMAGE env is not defined, current application is not an AppImage
(15:28:17) WARNING: [Backend]:          Protocol already registered.
(15:28:17) INFO:    [Connection]:       Connectivity: online
(15:28:17) INFO:    [Gog]:              Checking if login is valid
(15:28:17) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/s_savchuk/.config/heroic/gog_store/auth.json auth
(15:28:17) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(15:28:17) INFO:    [Backend]:          Loading Screen Ready
(15:28:17) INFO:    [Frontend]:         Refreshing undefined Library
(15:28:17) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(15:28:17) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/s_savchuk/.config/heroic/gog_store/auth.json auth
(15:28:17) INFO:    [Legendary]:        Refreshing library...
(15:28:17) INFO:    [Legendary]:        Refreshing Epic Games...
(15:28:17) INFO:    [Legendary]:        Game list updated, got 253 games & DLCs
(15:28:17) INFO:    [Backend]:          Frontend Ready
(15:28:17) INFO:    [Backend]:          Checking for new Heroic Updates
(15:28:17) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/s_savchuk/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:28:17) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/s_savchuk/.config/heroic/gog_store/auth.json --version
(15:28:17) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/s_savchuk/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(15:28:17) INFO:    [Backend]:          Checking for current version changelog
(15:28:17) INFO:    [Gog]:              Getting GOG library
(15:28:17) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/s_savchuk/.config/heroic/gog_store/auth.json auth
(15:28:17) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/s_savchuk/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:28:17) INFO:    [Gog]:              Saved username to config file
(node:828838) UnhandledPromiseRejectionWarning: TypeError: Invalid number
at filesize (/opt/Heroic/resources/app.asar/build/electron/main.c2fc9376.js:108:1282)
at getSystemInfo (/opt/Heroic/resources/app.asar/build/electron/main.c2fc9376.js:125:3270)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:828838) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(15:28:19) INFO:    [Gog]:              Saved games data
(15:28:19) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:28:19) INFO:    [Gog]:              Found 0 game(s) to update
(15:28:19) INFO:    [Winetricks]:       Downloading Winetricks
(15:28:19) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=/home/s_savchuk/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:28:20) INFO:    [Legendary]:        Found 0 games to update
(15:28:22) INFO:    [Backend]:          Starting the Download Queue
(15:28:57) INFO:    [Backend]:          Launching Grand Theft Auto V (9d2d0eb64d5c44529cece33fe2a46482)
(15:28:57) INFO:    [Backend]:          Preventing display from sleep
(15:28:58) INFO:    [Backend]:          Preventing machine to sleep
(15:28:58) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/s_savchuk/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:28:58) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/s_savchuk/.config/heroic/gog_store/auth.json --version
(15:28:58) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/s_savchuk/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
Error occurred in handler for 'launch': TypeError: Invalid number
at filesize (/opt/Heroic/resources/app.asar/build/electron/main.c2fc9376.js:108:1282)
at getSystemInfo (/opt/Heroic/resources/app.asar/build/electron/main.c2fc9376.js:125:3270)
at async /opt/Heroic/resources/app.asar/build/electron/main.c2fc9376.js:191:10841
at async node:electron/js2c/browser_init:2:98394


Launching of Ultima VI from GOG:
heroic

DevTools listening on ws://127.0.0.1:9222/devtools/browser/5728544b-90fd-4676-be38-991a13077e4c
(15:29:57) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(15:29:57) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:29:57) INFO:    [Connection]:       Connectivity: check-online
(15:29:57) INFO:    [Connection]:       Pinging external endpoints
(15:29:58) INFO:    [Backend]:          DRM module staus {
oimompecagnajdejgnnjijobebaeigek: {
name: 'Widevine Content Decryption Module',
status: 'new',
version: '4.10.2710.0'
}
}
APPIMAGE env is not defined, current application is not an AppImage
(15:29:58) WARNING: [Backend]:          Protocol already registered.
(15:29:58) INFO:    [Connection]:       Connectivity: online
(15:29:58) INFO:    [Gog]:              Checking if login is valid
(15:29:58) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/s_savchuk/.config/heroic/gog_store/auth.json auth
(15:29:58) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(15:29:58) INFO:    [Backend]:          Loading Screen Ready
(15:29:58) INFO:    [Frontend]:         Refreshing undefined Library
(15:29:58) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(15:29:58) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/s_savchuk/.config/heroic/gog_store/auth.json auth
(15:29:58) INFO:    [Legendary]:        Refreshing library...
(15:29:58) INFO:    [Legendary]:        Refreshing Epic Games...
(15:29:58) INFO:    [Legendary]:        Game list updated, got 253 games & DLCs
(15:29:58) INFO:    [Backend]:          Frontend Ready
(15:29:58) INFO:    [Backend]:          Checking for new Heroic Updates
(15:29:58) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/s_savchuk/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:29:58) INFO:    [Backend]:          Checking for current version changelog
(15:29:58) INFO:    [Gog]:              Getting GOG library
(15:29:58) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/s_savchuk/.config/heroic/gog_store/auth.json auth
(15:29:58) INFO:    [Gog]:              Saved username to config file
(15:29:58) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/s_savchuk/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:29:58) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/s_savchuk/.config/heroic/gog_store/auth.json --version
(15:29:58) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/s_savchuk/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(node:829347) UnhandledPromiseRejectionWarning: TypeError: Invalid number
at filesize (/opt/Heroic/resources/app.asar/build/electron/main.c2fc9376.js:108:1282)
at getSystemInfo (/opt/Heroic/resources/app.asar/build/electron/main.c2fc9376.js:125:3270)
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:829347) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(15:30:00) INFO:    [Gog]:              Saved games data
(15:30:00) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:30:00) INFO:    [Gog]:              Found 0 game(s) to update
(15:30:00) INFO:    [Winetricks]:       Downloading Winetricks
(15:30:00) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=/home/s_savchuk/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:30:00) INFO:    [Legendary]:        Found 0 games to update
(15:30:02) INFO:    [Backend]:          Launching Ultima VI™  (1207662453)
(15:30:02) INFO:    [Backend]:          Preventing display from sleep
(15:30:02) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/s_savchuk/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:30:02) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/s_savchuk/.config/heroic/gog_store/auth.json --version
(15:30:02) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/s_savchuk/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(15:30:02) INFO:    [Backend]:          Preventing machine to sleep
Error occurred in handler for 'launch': TypeError: Invalid number
at filesize (/opt/Heroic/resources/app.asar/build/electron/main.c2fc9376.js:108:1282)
at getSystemInfo (/opt/Heroic/resources/app.asar/build/electron/main.c2fc9376.js:125:3270)
at async /opt/Heroic/resources/app.asar/build/electron/main.c2fc9376.js:191:10841
at async node:electron/js2c/browser_init:2:98394
```

### Steps to reproduce

1. Open Heroic Games Launcher.
2. Click "Launch" icon on any installed game.
3. Wait, until Second Coming.

### Expected behavior

I expected at least wine error message or smthing.

### Heroic Version

Latest Stable

### System Information

- OS : Garuda Linux.
- PC : HP Victus 16 with AMD Ryzen 5 and NVIDIA Geforce RTX 3050Ti

**Comment by imLinguin** [comment]
Same issue as #3051
