### ISSUE TITLE
Linux app fails to launch any installed Epic game, wine prefix folder is always empty

### ISSUE THREAD

**Issue by TheBlueQuasar** [Heroic-Games-Launcher/HeroicGamesLauncher#3146]
### Describe the bug

When trying to launch any installed game from Epic Games, the game won't launch and always a similar error is shown:

`An error has occurred! Try to Logout and Login on your Epic account. [cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Checking for updates...[Core] INFO: Getting authentication token...[cli] INFO: Launching 01f1e8046e9e433db190a611a0411579...Traceback (most recent call last): File "legendary/cli.py", line 3061, in File "legendary/cli.py", line 2976, in main File "legendary/cli.py", line 697, in launch_game File "subprocess.py", line 951, in init File "subprocess.py", line 1821, in _execute_childFileNotFoundError: [Errno 2] No such file or directory: '/home/myusername/.config/heroic/tools/wine/Wine-GE-Proton8-19/bin/wine' [57065] Failed to execute script 'cli' due to unhandled exception!`

 The wine prefix folder which the game is supposed to run in is also completely empty. I have tried with many versions of wine - both wine-ge from Heroic wine manager and external wine versions from other sources - but the result has been the same. The wine versions tested were all correctly installed, so it's strange the error shows "no such file or directory" about the wine executable.
 And I have tried logging out and then back in to my Epic account several times, since the error prompt suggested it, but that didn't change the outcome.
 I also tested the installed game executables by running them outside Heroic in a wine prefix, and the games launch and work as expected. So game files aren't causing this issue.
  I attached the log when trying to open a game - Rogue Legacy - from my Epic library.
 Hope this information gives you enough to investigate, but I'm not sure how reproducible this bug could be. Please let me know if I can provide more data that might be useful.

### Add logs

```text
System Info:
CPU: 4x Intel(R) Core(TM) i3-3227U CPU @ 1.90GHz
Memory: 3.97 GB (used: 1.41 GB)
GPUs:
  GPU 0:
    Name: Intel Corporation undefined
    IDs: D=166 V=8086 SD=90a8 SV=104d
    Driver: i915
OS: KDE neon 5.27 (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.9.2 Boa Hancock
  Legendary: 0.20.32 Dark Energy (hotfix #6)
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": false,
	"preferSystemLibs": false,
	"enableEsync": false,
	"enableFSR": false,
	"enableFsync": false,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"useGameMode": false,
	"language": "",
	"wineVersion": {
		"bin": "/home/myusername/.config/heroic/tools/wine/Wine-GE-Proton8-19/bin/wine",
		"name": "Wine - Wine-GE-Proton8-19",
		"type": "wine",
		"lib": "/home/myusername/.config/heroic/tools/wine/Wine-GE-Proton8-19/lib64",
		"lib32": "/home/myusername/.config/heroic/tools/wine/Wine-GE-Proton8-19/lib",
		"wineserver": "/home/myusername/.config/heroic/tools/wine/Wine-GE-Proton8-19/bin/wineserver"
	},
	"winePrefix": "/media/myusername/Games/Heroic/Prefixes/Default/Rogue Legacy",
	"wineCrossoverBottle": "",
	"ignoreGameUpdates": true
}

Game launched at: Fri Oct 20 2023 19:26:26 GMT+0330 (Iran Standard Time)

Launch Command: LD_LIBRARY_PATH=/home/myusername/.config/heroic/tools/wine/Wine-GE-Proton8-19/lib64:/home/myusername/.config/heroic/tools/wine/Wine-GE-Proton8-19/lib:/tmp/.mount_Heroicgusz0p/usr/lib: HEROIC_APP_NAME=01f1e8046e9e433db190a611a0411579 HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= WINEPREFIX="/media/myusername/Games/Heroic/Prefixes/Default/Rogue Legacy" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 ORIG_LD_LIBRARY_PATH=/tmp/.mount_Heroicgusz0p/usr/lib: GST_PLUGIN_SYSTEM_PATH_1_0=/home/myusername/.config/heroic/tools/wine/Wine-GE-Proton8-19/lib64/gstreamer-1.0:/home/myusername/.config/heroic/tools/wine/Wine-GE-Proton8-19/lib/gstreamer-1.0 WINEDLLPATH=/home/myusername/.config/heroic/tools/wine/Wine-GE-Proton8-19/lib64/wine:/home/myusername/.config/heroic/tools/wine/Wine-GE-Proton8-19/lib/wine /tmp/.mount_Heroicgusz0p/resources/app.asar.unpacked/build/bin/linux/legendary launch 01f1e8046e9e433db190a611a0411579 --wine /home/myusername/.config/heroic/tools/wine/Wine-GE-Proton8-19/bin/wine --language en

Game Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 01f1e8046e9e433db190a611a0411579...
Traceback (most recent call last):
  File "legendary/cli.py", line 3061, in <module>
  File "legendary/cli.py", line 2976, in main
  File "legendary/cli.py", line 697, in launch_game
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1821, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/myusername/.config/heroic/tools/wine/Wine-GE-Proton8-19/bin/wine'
[57217] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Go to Epic games library
2. Check a game for wine runner and wine prefix folder to see if chosen values are correct and usable
3. Then launch the game
4. See the error similar to the one attached in the bug description
5. Check the game prefix directory, it is empty

### Expected behavior

Heroic should successfully create a wine prefix for any downloaded Windows game and run a game inside that prefix.

### Heroic Version

Latest Stable

### System Information

OS: Linux, Ubuntu 22.04 based (KDE Neon)
Kernel Version: 6.2.0-35-generic (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i3-3227U CPU @ 1.90GHz
Memory: 3.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 4000
Heroic version: Tried both latest (2.9.2) appimage and native (.deb) version with identical results

### Additional information

I've set Heroic to create wine prefixes on an external drive, as you can see in the log. I'm not sure if that can have any impact since I did change that to my home directory, but that didn't make any difference.

**Comment by arielj** [comment]
This seems to be the old missing wine dependencies error.

There's been a lot of changes since the moment of this report and using GE-Proton + umu should solve this and it's the current default.
