### ISSUE TITLE
Heroic Launcher will only show five games from EPIC

### ISSUE THREAD

**Issue by pikestriker** [Heroic-Games-Launcher/HeroicGamesLauncher#3167]
### Describe the bug

Heroic Launcher will only show 5 of the EPIC game (the same five), never more and never less.  It seems to be fine with the GOG account though.

Here are some of the things that I tried:
- Working on the steamdeck, updated to the latest version of Heroic (v2.9.2)
- Updated to the latest version of steamdeck firmware as well
- Unable to see the EPIC games except for five titles
- The five games that I can see "Black Book", "Borderlands 3", "Dodo Peak", "Europa IV", "Orwell: Keeping an Eye on you"
- Started occurring after claiming the Evil Within free game
- Checked reddit posts and clicked on the view hidden games button, view favorite games button, logged out of my account, cleared the cache, reset heroic to no avail
- Rolled back the version to 2.8.0 and 2.7.2 and they still aren't showing up
- Downloaded and installed Heroic Launcher for Windows (v2.9.2) and still have the same issue

### Add logs

```text
These are the windows logs, will see if I can update this after with the steamdeck logs.

(22:45:17) INFO:    [Legendary]:        Legendary location: C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(22:45:17) INFO:    [Gog]:              GOGDL location: C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(22:45:17) INFO:    [Connection]:       Connectivity: check-online
(22:45:17) INFO:    [Connection]:       Pinging external endpoints
(22:45:18) INFO:    [Connection]:       Connectivity: online
(22:45:19) INFO:    [Backend]:          DRM module staus {
  "neifaoindggfcjicffkgpmnlppeffabd": {
    "name": "Google Widevine Windows CDM",
    "status": "updated",
    "version": "1.0.2512.1"
  },
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "updated",
    "version": "4.10.2710.0"
  }
}
(22:45:19) INFO:    [Backend]:          User Not Found, removing it from Store
(22:45:19) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(22:45:19) INFO:    [Backend]:          Registered protocol with OS.
(22:45:20) INFO:    [Backend]:          Loading Screen Ready
(22:45:20) INFO:    [Backend]:          Frontend Ready
(22:45:21) INFO:    [Backend]:          Checking for new Heroic Updates
(22:45:21) INFO:    [Backend]:          Checking for current version changelog
(22:45:21) INFO:    [Frontend]:         Updated to a new version, cleaaning up the cache.
(22:45:21) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary cleanup
(22:45:21) INFO:    [Backend]:          VCRuntime is installed
(22:45:21) INFO:    [Frontend]:         Refreshing undefined Library
(22:45:21) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(22:45:21) INFO:    [Legendary]:        Refreshing library...
(22:45:24) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(22:45:24) INFO:    [Gog]:              Running command: C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\dicke\AppData\Roaming\heroic\gog_store\auth.json --version
(22:45:24) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\nile_config C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile --version
(22:45:25) INFO:    [Backend]:          
System Information:
CPU: 8x Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Memory: 17.09 GB (used: 7.76 GB)
GPUs:
  GPU 0:
    Name: Intel Corporation UHD Graphics 620
    IDs: D=5917 V=8086 SD=0027 SV=1414
    Driver: 30.0.101.1339
  GPU 1:
    Name: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile]
    IDs: D=1c8d V=10de SD=0024 SV=1414
    Driver: 527.56
OS: Microsoft Windows 11 Pro 10.0.22621 (win32)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.9.2 Boa Hancock
  Legendary: 0.20.32 Dark Energy (hotfix #6)
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(22:45:25) INFO:    [Backend]:          Starting the Download Queue
(22:46:00) INFO:    [Legendary]:        Logging in: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary auth --code <redacted>
(22:46:01) INFO:    [Frontend]:         Refreshing legendary Library
(22:46:01) INFO:    [Legendary]:        Refreshing library...
(22:46:01) INFO:    [Legendary]:        Refreshing Epic Games...
(22:46:01) INFO:    [Legendary]:        Game list updated, got 0 games & DLCs
(22:46:01) INFO:    [Frontend]:         No cache found, getting data from legendary...
(22:46:01) INFO:    [Legendary]:        Refreshing library...
(22:46:01) INFO:    [Legendary]:        Refreshing Epic Games...
(22:46:01) INFO:    [Legendary]:        Game list updated, got 0 games & DLCs
(22:46:02) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(22:46:02) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(22:46:04) INFO:    [Frontend]:         Refreshing undefined Library
(22:46:04) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(22:46:04) INFO:    [Legendary]:        Refreshing library...
(22:46:04) INFO:    [Legendary]:        Refreshing Epic Games...
(22:46:04) INFO:    [Legendary]:        Game list updated, got 5 games & DLCs
(22:46:04) INFO:    [Frontend]:         No cache found, getting data from legendary...
(22:46:04) INFO:    [Legendary]:        Refreshing library...
(22:46:04) INFO:    [Legendary]:        Refreshing Epic Games...
(22:46:04) INFO:    [Legendary]:        Game list updated, got 5 games & DLCs
(22:46:04) INFO:    [Frontend]:         Force Update
(22:46:04) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(22:46:04) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(22:46:07) INFO:    [Frontend]:         Refreshing all Library
(22:46:07) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(22:46:07) INFO:    [Legendary]:        Refreshing library...
(22:46:07) INFO:    [Legendary]:        Refreshing Epic Games...
(22:46:07) INFO:    [Legendary]:        Game list updated, got 5 games & DLCs
(22:46:07) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(22:46:07) INFO:    [Gog]:              Found 0 game(s) to update
(22:46:07) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(22:46:07) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(22:46:09) WARNING: [Legendary]:        Failed to parse games from C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig\legendary\installed.json with: Error: ENOENT: no such file or directory, open 'C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig\legendary\installed.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1861)
    at Object.readFileSync (node:fs:468:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9204)
    at Module.listUpdateableGames (C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.c2fc9376.js:102:4774)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.c2fc9376.js:191:3962
    at async node:electron/js2c/browser_init:2:100305
(22:46:09) INFO:    [Legendary]:        Found 0 games to update
(22:46:13) INFO:    [Backend]:          Checking for current version changelog
(09:59:57) INFO:    [Frontend]:         Refreshing all Library
(09:59:57) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(09:59:57) INFO:    [Legendary]:        Refreshing library...
(09:59:57) INFO:    [Legendary]:        Refreshing Epic Games...
(09:59:57) INFO:    [Legendary]:        Game list updated, got 5 games & DLCs
(09:59:57) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(09:59:57) INFO:    [Gog]:              Found 0 game(s) to update
(09:59:57) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(09:59:57) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(09:59:59) WARNING: [Legendary]:        Failed to parse games from C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig\legendary\installed.json with: Error: ENOENT: no such file or directory, open 'C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig\legendary\installed.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1861)
    at Object.readFileSync (node:fs:468:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9204)
    at Module.listUpdateableGames (C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.c2fc9376.js:102:4774)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.c2fc9376.js:191:3962
    at async node:electron/js2c/browser_init:2:100305
(09:59:59) INFO:    [Legendary]:        Found 0 games to update
(11:10:15) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(11:10:15) INFO:    [Gog]:              Running command: C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\dicke\AppData\Roaming\heroic\gog_store\auth.json --version
(11:10:15) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\nile_config C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile --version
(11:10:16) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(11:10:17) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(11:10:17) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(11:10:18) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(11:14:07) INFO:    [Frontend]:         Refreshing all Library
(11:14:07) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(11:14:07) INFO:    [Legendary]:        Refreshing library...
(11:14:07) INFO:    [Legendary]:        Refreshing Epic Games...
(11:14:07) INFO:    [Legendary]:        Game list updated, got 5 games & DLCs
(11:14:07) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(11:14:07) INFO:    [Gog]:              Found 0 game(s) to update
(11:14:07) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(11:14:07) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(11:14:09) WARNING: [Legendary]:        Failed to parse games from C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig\legendary\installed.json with: Error: ENOENT: no such file or directory, open 'C:\Users\dicke\AppData\Roaming\heroic\legendaryConfig\legendary\installed.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1861)
    at Object.readFileSync (node:fs:468:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9204)
    at Module.listUpdateableGames (C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.c2fc9376.js:102:4774)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\dicke\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.c2fc9376.js:191:3962
    at async node:electron/js2c/browser_init:2:100305
(11:14:09) INFO:    [Legendary]:        Found 0 games to update
```

### Steps to reproduce

1. Login to EPIC account via regular login (not the alternate login, although it is the same result)
2. Go to the library to see the files

### Expected behavior

See all of the EPIC games

### Heroic Version

Latest Stable

### System Information

Steamdeck version 3.4.11 build 20231005.1
Windows 11 Version	10.0.22621 Build 22621

**Comment by arielj** [comment]
can you check if legendary lists all the games? https://github.com/derrod/legendary

because if legendary fails then it's an issue to report there instead

**Comment by pikestriker** [comment]
> can you check if legendary lists all the games? https://github.com/derrod/legendary
> 
> because if legendary fails then it's an issue to report there instead

You are correct, I can only see those five games using legendary.  Thanks for pointing me to the correct place, I didn't know if this belonged here or not.

**Comment by arielj** [comment]
closing this then since it seems to be a problem with legendary
