### ISSUE TITLE
Not enough available disk space - Mac OS

### ISSUE THREAD

**Issue by piotrekjeremicz** [Heroic-Games-Launcher/HeroicGamesLauncher#3178]
### Describe the bug

I am trying to install GTA V. I currently have over 350 GB of disk space available. GTA requires less than 220 GB. When trying to install even before the download starts, I get an error: "Not enough available disk space"

### Add logs

```text
(22:08:37) INFO:    [Legendary]:        Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(22:08:37) INFO:    [Gog]:              GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(22:08:37) INFO:    [Connection]:       Connectivity: check-online
(22:08:37) INFO:    [Connection]:       Pinging external endpoints
(22:08:37) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(22:08:37) WARNING: [Backend]:          Protocol already registered.
(22:08:37) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(22:08:37) INFO:    [Gog]:              Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/piotrek/Library/Application Support/heroic/gog_store/auth.json" --version
(22:08:37) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/nile_config" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/nile --version
(22:08:37) INFO:    [Connection]:       Connectivity: online
(22:08:37) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(22:08:37) INFO:    [Backend]:          Loading Screen Ready
(22:08:37) INFO:    [Frontend]:         Refreshing undefined Library
(22:08:37) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(22:08:37) INFO:    [Legendary]:        Refreshing library...
(22:08:37) INFO:    [Legendary]:        Refreshing Epic Games...
(22:08:37) INFO:    [Legendary]:        Game list updated, got 45 games & DLCs
(22:08:37) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(22:08:37) INFO:    [Backend]:          Frontend Ready
(22:08:37) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(22:08:37) INFO:    [Gog]:              Found 0 game(s) to update
(22:08:37) INFO:    [Backend]:          Checking for new Heroic Updates
(22:08:37) INFO:    [Backend]:          Checking for current version changelog
(22:08:37) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
(22:08:37) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
(22:08:39) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Grand Theft Auto V
(22:08:39) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Grand Theft Auto V
(22:08:39) DEBUG:   [Legendary]:        Using cached install info
(22:08:39) DEBUG:   [Legendary]:        Using cached install info
(22:08:39) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine
(22:08:39) INFO:    [Winetricks]:       Downloading Winetricks
(22:08:41) DEBUG:   [Legendary]:        Using cached install info
(22:08:41) DEBUG:   [Backend]:          {"free":64925794304,"diskSize":994662584320,"message":"60.47 GiB / 926.35 GiB","validPath":true}
(22:08:41) DEBUG:   [Backend]:          {"free":64925794304,"diskSize":994662584320,"message":"60.47 GiB / 926.35 GiB","validPath":true}
(22:08:41) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine
(22:08:42) INFO:    [Backend]:          Starting the Download Queue
(22:08:51) INFO:    [Backend]:          
System Information:
CPU: 12x Apple M2 Pro
Memory: 17.18 GB (used: 8.93 GB)
GPUs:

OS:  14.0.0 (darwin)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.9.2 Boa Hancock
  Legendary: 0.20.32 Dark Energy (hotfix #6)
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(22:08:53) WARNING: [Legendary]:        Failed to parse games from /Users/piotrek/Library/Application Support/heroic/legendaryConfig/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/Users/piotrek/Library/Application Support/heroic/legendaryConfig/legendary/installed.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:468:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at Module.listUpdateableGames (/Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.c2fc9376.js:102:4774)
    at async /Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.c2fc9376.js:191:3962
    at async node:electron/js2c/browser_init:2:98394
(22:08:53) INFO:    [Legendary]:        Found 0 games to update
(22:08:53) DEBUG:   [Legendary]:        Using cached install info
(22:08:53) DEBUG:   [Legendary]:        Using cached install info
(22:13:31) INFO:    [Backend]:          Writing config for 9d2d0eb64d5c44529cece33fe2a46482
(22:13:31) INFO:    [Backend]:          Changed config: wineCrossoverBottle from  to Heroic
(22:13:31) INFO:    [Backend]:          Changed config: winePrefix from /Users/piotrek/Games/Heroic/Prefixes/default/Grand Theft Auto V to /Users/piotrek/Games/Heroic/Prefixes/default
(22:13:31) DEBUG:   [Legendary]:        Using cached install info
(22:13:31) INFO:    [DownloadManager]:  Grand Theft Auto V  was added to the download queue.
(22:13:31) INFO:    [Backend]:          Preventing machine to sleep
(22:13:31) DEBUG:   [Legendary]:        Using cached install info
(22:13:31) DEBUG:   [Legendary]:        Using cached install info
(22:13:31) DEBUG:   [Legendary]:        Using cached install info
(22:13:31) INFO:    [Legendary]:        Installing 9d2d0eb64d5c44529cece33fe2a46482: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary install 9d2d0eb64d5c44529cece33fe2a46482 --platform Windows --base-path /Users/piotrek/Games/Heroic --skip-dlcs -y --skip-sdl
(22:13:31) DEBUG:   [Legendary]:        Logging to file "/Users/piotrek/Library/Application Support/heroic/GamesConfig/9d2d0eb64d5c44529cece33fe2a46482.log"
(22:13:31) DEBUG:   [Legendary]:        Using cached install info
(22:13:31) DEBUG:   [Legendary]:        Using cached install info
(22:13:39) INFO:    [Backend]:          Checking for current version changelog
(22:13:43) INFO:    [Backend]:          Adding shortcuts for Grand Theft Auto V
(22:13:43) INFO:    [DownloadManager]:  Finished Installation of 9d2d0eb64d5c44529cece33fe2a46482
(22:13:43) INFO:    [DownloadManager]:  9d2d0eb64d5c44529cece33fe2a46482 added to download manager finished.
(22:13:43) INFO:    [DownloadManager]:  9d2d0eb64d5c44529cece33fe2a46482 removed from download manager.
(22:13:43) INFO:    [Frontend]:         Refreshing legendary Library
(22:13:43) INFO:    [Legendary]:        Refreshing library...
(22:13:43) INFO:    [Legendary]:        Refreshing Epic Games...
(22:13:43) INFO:    [Legendary]:        Game list updated, got 45 games & DLCs
(22:13:43) DEBUG:   [Legendary]:        Using cached install info
(22:13:43) ERROR:   [Backend]:          Not enough available disk space
(22:13:43) DEBUG:   [Legendary]:        Using cached install info
(22:13:43) DEBUG:   [Legendary]:        Using cached install info
(22:13:43) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
(22:13:48) DEBUG:   [Legendary]:        Using cached install info
(22:13:48) DEBUG:   [Backend]:          {"free":64855080960,"diskSize":994662584320,"message":"60.4 GiB / 926.35 GiB","validPath":true}
(22:13:48) DEBUG:   [Backend]:          {"free":64855080960,"diskSize":994662584320,"message":"60.4 GiB / 926.35 GiB","validPath":true}
(22:13:48) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine
(22:13:55) INFO:    [Backend]:          Writing config for 9d2d0eb64d5c44529cece33fe2a46482
(22:13:55) INFO:    [Backend]:          Changed config: wineCrossoverBottle from Heroic to 
(22:13:55) INFO:    [Backend]:          Changed config: winePrefix from /Users/piotrek/Games/Heroic/Prefixes/default to /Users/piotrek/Games/Heroic/Prefixes/default/Grand Theft Auto V
(22:13:55) DEBUG:   [Legendary]:        Using cached install info
(22:13:55) INFO:    [DownloadManager]:  Grand Theft Auto V  was added to the download queue.
(22:13:55) INFO:    [Backend]:          Preventing machine to sleep
(22:13:55) DEBUG:   [Legendary]:        Using cached install info
(22:13:55) DEBUG:   [Legendary]:        Using cached install info
(22:13:55) DEBUG:   [Legendary]:        Using cached install info
(22:13:55) INFO:    [Legendary]:        Installing 9d2d0eb64d5c44529cece33fe2a46482: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary install 9d2d0eb64d5c44529cece33fe2a46482 --platform Windows --base-path /Users/piotrek/Games/Heroic --skip-dlcs -y --skip-sdl
(22:13:55) DEBUG:   [Legendary]:        Logging to file "/Users/piotrek/Library/Application Support/heroic/GamesConfig/9d2d0eb64d5c44529cece33fe2a46482.log"
(22:13:55) DEBUG:   [Legendary]:        Using cached install info
(22:13:55) DEBUG:   [Legendary]:        Using cached install info
(22:14:02) INFO:    [Backend]:          Adding shortcuts for Grand Theft Auto V
(22:14:02) INFO:    [DownloadManager]:  Finished Installation of 9d2d0eb64d5c44529cece33fe2a46482
(22:14:02) INFO:    [DownloadManager]:  9d2d0eb64d5c44529cece33fe2a46482 added to download manager finished.
(22:14:02) INFO:    [DownloadManager]:  9d2d0eb64d5c44529cece33fe2a46482 removed from download manager.
(22:14:02) INFO:    [Frontend]:         Refreshing legendary Library
(22:14:02) INFO:    [Legendary]:        Refreshing library...
(22:14:02) INFO:    [Legendary]:        Refreshing Epic Games...
(22:14:02) INFO:    [Legendary]:        Game list updated, got 45 games & DLCs
(22:14:02) INFO:    [Backend]:          Stopping Power Saver Blocker
(22:14:02) DEBUG:   [Legendary]:        Using cached install info
(22:14:02) ERROR:   [Backend]:          Not enough available disk space
(22:14:02) DEBUG:   [Legendary]:        Using cached install info
(22:14:02) DEBUG:   [Legendary]:        Using cached install info
(22:14:02) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
(22:16:56) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(22:16:56) INFO:    [Gog]:              Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/piotrek/Library/Application Support/heroic/gog_store/auth.json" --version
(22:16:56) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/nile_config" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/nile --version
(22:16:59) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary cleanup
(22:16:59) INFO:    [Frontend]:         Refreshing undefined Library
(22:16:59) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(22:16:59) INFO:    [Legendary]:        Refreshing library...
(22:16:59) INFO:    [Legendary]:        Refreshing Epic Games...
(22:16:59) INFO:    [Legendary]:        Game list updated, got 45 games & DLCs
(22:17:00) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
(22:17:08) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Grand Theft Auto V
(22:17:08) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Grand Theft Auto V
(22:17:08) INFO:    [Legendary]:        Getting more details with 'legendary info'
(22:17:08) INFO:    [Legendary]:        Getting more details with 'legendary info'
(22:17:08) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info 9d2d0eb64d5c44529cece33fe2a46482 --json --platform Windows
(22:17:08) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info 9d2d0eb64d5c44529cece33fe2a46482 --json --platform Windows
(22:17:08) INFO:    [Legendary]:        Getting more details with 'legendary info'
(22:17:08) DEBUG:   [Backend]:          {"free":64450699264,"diskSize":994662584320,"message":"60.02 GiB / 926.35 GiB","validPath":true}
(22:17:09) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine
(22:17:09) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info 9d2d0eb64d5c44529cece33fe2a46482 --json --platform Windows
(22:17:09) INFO:    [Legendary]:        Getting Info from Epic API
(22:17:20) DEBUG:   [Backend]:          {"free":64472805376,"diskSize":994662584320,"message":"60.04 GiB / 926.35 GiB","validPath":true}
(22:17:40) INFO:    [Backend]:          Writing config for 9d2d0eb64d5c44529cece33fe2a46482
(22:17:40) INFO:    [Backend]:          Changed config: wineCrossoverBottle from  to Heroic
(22:17:40) INFO:    [Backend]:          Changed config: winePrefix from /Users/piotrek/Games/Heroic/Prefixes/default/Grand Theft Auto V to /Users/piotrek/Games/Heroic/Prefixes/default
(22:17:40) DEBUG:   [Legendary]:        Using cached install info
(22:17:40) INFO:    [DownloadManager]:  Grand Theft Auto V  was added to the download queue.
(22:17:40) DEBUG:   [Legendary]:        Using cached install info
(22:17:40) DEBUG:   [Legendary]:        Using cached install info
(22:17:40) DEBUG:   [Legendary]:        Using cached install info
(22:17:40) INFO:    [Legendary]:        Installing 9d2d0eb64d5c44529cece33fe2a46482: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary install 9d2d0eb64d5c44529cece33fe2a46482 --platform Windows --base-path /Users/piotrek/Games/Heroic --skip-dlcs -y --skip-sdl
(22:17:40) DEBUG:   [Legendary]:        Logging to file "/Users/piotrek/Library/Application Support/heroic/GamesConfig/9d2d0eb64d5c44529cece33fe2a46482.log"
(22:17:40) DEBUG:   [Legendary]:        Using cached install info
(22:17:40) DEBUG:   [Legendary]:        Using cached install info
(22:17:51) INFO:    [Backend]:          Adding shortcuts for Grand Theft Auto V
(22:17:51) INFO:    [DownloadManager]:  Finished Installation of 9d2d0eb64d5c44529cece33fe2a46482
(22:17:51) INFO:    [DownloadManager]:  9d2d0eb64d5c44529cece33fe2a46482 added to download manager finished.
(22:17:51) INFO:    [DownloadManager]:  9d2d0eb64d5c44529cece33fe2a46482 removed from download manager.
(22:17:51) INFO:    [Frontend]:         Refreshing legendary Library
(22:17:51) INFO:    [Legendary]:        Refreshing library...
(22:17:51) INFO:    [Legendary]:        Refreshing Epic Games...
(22:17:51) INFO:    [Legendary]:        Game list updated, got 45 games & DLCs
(22:17:51) INFO:    [Backend]:          Stopping Power Saver Blocker
(22:17:51) DEBUG:   [Legendary]:        Using cached install info
(22:17:51) ERROR:   [Backend]:          Not enough available disk space
(22:17:51) DEBUG:   [Legendary]:        Using cached install info
(22:17:51) DEBUG:   [Legendary]:        Using cached install info
(22:17:51) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/piotrek/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
```

### Steps to reproduce

1. Go to Library
2. Click on GTA V
3. Scroll down to Install Button
4. Click install
5. See error

### Expected behavior

GTA V should be downloaded and installed

### Screenshots

<img width="1312" alt="Screenshot 2023-10-30 at 22 18 36" src="https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/32737430/a6fa1f77-d2f3-417f-9a0c-db9db0ef00ef">
<img width="471" alt="Screenshot 2023-10-30 at 22 18 34" src="https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/32737430/0c64ca0f-a0d0-4fd0-92af-c15f560ab362">

### Heroic Version

Latest Stable

### System Information

- OS: Mac OS Sonoma 14.0

**Comment by arielj** [comment]
Can you share the output of this command?

```
df -H -- /Users/piotrek/Games/Heroic
```

(`df` is a unix command to get the disk space information, `-H` is to display the information in GB instead if bytes, and then the `-- /Users....` tells that tool to check the directory were we install games)


we use this tool https://www.npmjs.com/package/check-disk-space to get the available space and it uses that command https://github.com/Alex-D/check-disk-space/blob/main/src/index.ts#L151

maybe you have available space but `df` can't see that?

**Comment by piotrekjeremicz** [comment]
Being a power user, it always seemed to me that I understand macOS, but this time it surprised me! 😅

It seems to me that the system shows a completely different value due to not counting temporary cache files. I don't know why there was such a big difference. Perhaps macOS frees up slower resources due to the optimization of SSD work. Overwriting and deleting are, after all, similar operations, and done alone saves us the life of the hard drive.

The question is if there is a method to force recalculate free space in that case.

<img width="1217" alt="Screenshot 2023-11-01 at 11 15 12" src="https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/32737430/b2f92df1-f6bc-4181-9419-4a3a94ef58f6">

**Comment by arielj** [comment]
> The question is if there is a method to force recalculate free space in that case.

Do you mean if heroic can recalculate the free space or if mac os can recalculate the size?

I think we call `df` every time, no cache or anything, so it should re-calculate it already.

From your screenshot it seems like it's working now?

**Comment by arielj** [comment]
@piotrekjeremicz I understand the issue was Mac not reporting the correct size in the disk utility, can we close this issue then?

**Comment by piotrekjeremicz** [comment]
The problem is solved but it could be presented in other cases. Please check this thread:
https://unix.stackexchange.com/questions/348850/why-df-and-finder-shows-different-available-disk-space

So, the case is appearing if somebody use Time Machine. This is my case. I think there should be some information how to deal with that kind of error.

**Comment by Emulord** [comment]
I had the exact same issue with MacOS showing 370GB of free space, but Heroic only 95GB, blocking GTA V install. 
The solution also applied to my case, and I'm also a Time Machine user.

Thank you very much !

**Comment by arielj** [comment]
Closing this since I don't think we can do much from Heroic itself. The conversation in this issue is probably the best source for people having this problem or maybe we can add some FAQs or something in the wiki in the future if this keeps happening.
