### ISSUE TITLE
Laucher crashes on startup

### ISSUE THREAD

**Issue by FRANEKbinbanek** [Heroic-Games-Launcher/HeroicGamesLauncher#3199]
### Describe the bug

When I was opening the launcher it open for a second or did not post at all. I tried to reinstall and nothing. Then I runned flatpak run command and I've got these logs.

### Add logs

```text
[13 zypak-helper] Wait found events, but sd-event found none
[13:1104/221403.438264:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Nie ma takiego pliku ani katalogu
[13:1104/221407.579317:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Nie ma takiego pliku ani katalogu
[13:1104/221407.579422:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Nie ma takiego pliku ani katalogu
which: no wine in (/app/bin:/app/bin:/app/utils/bin:/usr/bin:/usr/lib/extensions/vulkan/MangoHud/bin:/usr/lib/extensions/vulkan/gamescope/bin:/usr/lib/extensions/vulkan/OBSVkCapture/bin:/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux)
(22:14:08) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(22:14:08) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(22:14:08) INFO:    [Connection]:       Connectivity: check-online
(22:14:08) INFO:    [Connection]:       Pinging external endpoints
(22:14:08) INFO:    [Connection]:       Connectivity: online
libva error: /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so init failed
(22:14:09) ERROR:   [Backend]:          Failed to fetch system information TypeError: e.split is not a function or its return value is not iterable
    at getPicIds (/app/bin/heroic/resources/app.asar/build/electron/main.9bb8a6b7.js:127:7894)
    at async populateDeviceAndVendorName (/app/bin/heroic/resources/app.asar/build/electron/main.9bb8a6b7.js:128:560)
    at async getSystemInfo (/app/bin/heroic/resources/app.asar/build/electron/main.9bb8a6b7.js:128:2907)
```

### Steps to reproduce

How to get these logs:
1 Install App
2 use "flatpak run com.heroicgameslauncher.hgl" command

### Expected behavior

You'll get these logs and laucher will not open

### Heroic Version

Latest Stable

### System Information

- OS Fedora 38
- DE Plasma KDE (Wihout mods)

**Comment by arielj** [comment]
Looks like there was some issue downloading this file https://pci-ids.ucw.cz/v2.2/pci.ids and it's not handled properly by heroic.

Try downloading that file and put it in `~/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools` and then try to start heroic again, that will put the file in the right place

**Comment by FRANEKbinbanek** [comment]
There was no tools folder, but still after creating it and droppi g files it was not opening

**Comment by FRANEKbinbanek** [comment]
Okay I just reinstalled the OS and it's working fine
