### ISSUE TITLE
Cannot compile on arm64

### ISSUE THREAD

**Issue by mobilegmYT** [Heroic-Games-Launcher/HeroicGamesLauncher#320]
**Describe the bug**
When compiling on a arm64 system, I get this error:

```
  ⨯ exec: "opj_decompress": executable file not found in $PATH
github.com/develar/app-builder/pkg/icons.ConvertIcnsToPngUsingOpenJpeg
	/Volumes/data/Documents/app-builder/pkg/icons/icnsToPngUsingOpenJpeg.go:158
github.com/develar/app-builder/pkg/icons.ConvertIcnsToPng
	/Volumes/data/Documents/app-builder/pkg/icons/icns-to-png.go:47
github.com/develar/app-builder/pkg/icons.doConvertIcon
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:226
github.com/develar/app-builder/pkg/icons.ConvertIcon
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:56
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:33
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	/Volumes/data/Documents/app-builder/main.go:90
runtime.main
	/usr/local/Cellar/go/1.14.5/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go/1.14.5/libexec/src/runtime/asm_arm64.s:1148  
  ⨯ /home/pi/Downloads/HeroicGamesLauncher/node_modules/app-builder-bin/linux/arm64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                        Error: /home/pi/Downloads/HeroicGamesLauncher/node_modules/app-builder-bin/linux/arm64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                            at ChildProcess.<anonymous> (/home/pi/Downloads/HeroicGamesLauncher/node_modules/builder-util/src/util.ts:243:14)
                                                                                                                                                            at Object.onceWrapper (events.js:422:26)
                                                                                                                                                            at ChildProcess.emit (events.js:315:20)
                                                                                                                                                            at maybeClose (internal/child_process.js:1048:16)
                                                                                                                                                            at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**

1. Git clone the repo, cd into it, and build for arm64 with `--arm64`
2. See error

**Expected behavior**
The app to compile successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/44128563/115492950-0c109a80-a220-11eb-9322-35a78236ef6e.png)

**Desktop (please complete the following information):**

- OS: Debian
- Version Buster
- Game: N/A
- Wine/Proton version: N/A

**Additional context**
I'm using a 64-bit container/chroot on a 32-bit arm Raspberry Pi host OS.

**Comment by flavioislima** [comment]
Sorry but we have no way of supporting arm right now. Also, we dont know if Legendary runs on arm so you will need to check it first and if you want to develop a Heroic version of ARM, be welcome but right now our team have no way of doing this.

**Comment by mobilegmYT** [comment]
> Sorry but we have no way of supporting arm right now. Also, we dont know if Legendary runs on arm so you will need to check it first and if you want to develop a Heroic version of ARM, be welcome but right now our team have no way of doing this.

I did check, and legendary works on ARM perfectly with some tweaks to use python 3.8. Heroic looks like a electron/yarn app, which means it should compile without many issues, but it looks like the icon builder stuff is messing with it.
