### ISSUE TITLE
Heroic launcher crash at startup.

### ISSUE THREAD

**Issue by Aspromayros** [Heroic-Games-Launcher/HeroicGamesLauncher#3272]
### Describe the bug

When I open the launcher it crashes after 2-3 seconds. (Flatpak)

### Add logs

```text
which: no wine in (/app/bin:/app/bin:/app/utils/bin:/usr/bin:/usr/lib/extensions/vulkan/MangoHud/bin:/usr/lib/extensions/vulkan/gamescope/bin:/usr/lib/extensions/vulkan/OBSVkCapture/bin:/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux)
(08:56:06) INFO:    [Winetricks]:       Downloading Winetricks
(node:13) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'url_format')
    at gogToUnifiedInfo (/app/bin/heroic/resources/app.asar/build/electron/main.9bb8a6b7.js:3:10588)
    at /app/bin/heroic/resources/app.asar/build/electron/main.9bb8a6b7.js:3:4357
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:13) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 6)
(08:56:06) INFO:    [Gog]:              Saved games data
(08:56:06) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(08:56:06) INFO:    [Gog]:              Found 0 game(s) to update
(08:56:06) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/nikitas/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
```

### Steps to reproduce

1. Open the flatpak version of heroic launcher.

### Expected behavior

To stay open and without crash.

### Screenshots

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/50244573/fdd59a10-2fcd-43ae-81bd-91beb566c795

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS  openSUSE Tumbleweed
- DE KDE Plasma
- CPU 3600x
- GPU 6700xt

**Comment by flavioislima** [comment]
it seems to be that you have some item on your library that Heroic doesn't know how to handle. Maybe @imLinguin might have a better opinion on that.

**Comment by imLinguin** [comment]
Some game might be missing image data, like background etc...
I just pushed the change to #3020 that should address it

**Comment by flavioislima** [comment]
> Some game might be missing image data, like background etc... I just pushed the change to #3020 that should address it

`url_format`?
`TypeError: Cannot read properties of undefined (reading 'url_format')`

**Comment by imLinguin** [comment]
Yes, we were not checking if vertical_image or the background is undefined
