### ISSUE TITLE
Heroic doesn't open

### ISSUE THREAD

**Issue by nyugdijhunter** [Heroic-Games-Launcher/HeroicGamesLauncher#3314]
### Describe the bug

On fresh install on Artix Linux from the AUR binary package, launcher starts but hangs on the following:

### Add logs

```text
(17:12:57) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(17:12:57) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:12:57) INFO:    [Connection]:       Connectivity: check-online
(17:12:57) INFO:    [Connection]:       Pinging external endpoints
(17:12:58) INFO:    [Connection]:       Connectivity: online
(17:13:09) ERROR:   [Backend]:          Failed to fetch system information TypeError: e.split is not a function or its return value is not iterable
    at getPicIds (/opt/Heroic/resources/app.asar/build/electron/main.52896897.js:127:5232)
    at async populateDeviceAndVendorName (/opt/Heroic/resources/app.asar/build/electron/main.52896897.js:128:560)
    at async getSystemInfo (/opt/Heroic/resources/app.asar/build/electron/main.52896897.js:128:3074)
```

### Steps to reproduce

1. Install the AUR binary package heroic-games-launcher-bin
2. Launch Heroic

### Expected behavior

It should start up normally.

### Heroic Version

Latest Stable

### System Information

- OS: Artix Linux

**Comment by nyugdijhunter** [comment]
Nevermind, waiting a bit it proceeds as usual, rookie mistake on my part
