### ISSUE TITLE
Rocket League doesn't start on heroicGL

### ISSUE THREAD

**Issue by KubAlmas** [Heroic-Games-Launcher/HeroicGamesLauncher#3343]
### Describe the bug

I just installed Rocket League on Heroic Game Launcher and it doesn't run because of he can't find something or like that

### Add logs

```text
System Info:
CPU: 16x AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
Memory: 32.82 GB (used: 1.95 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1
    IDs: D=15bf V=1002 SD=0031 SV=1f66
    Driver: amdgpu
OS: Ubuntu 22.04.3 LTS (Jammy Jellyfish) (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.11.0 Kumachi
  Legendary: 0.20.33 Undue Alarm
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableFsync": true,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"showMangohud": false,
	"useGameMode": true,
	"language": "",
	"wineVersion": {
		"bin": "/home/alm/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-27-LoL/bin/wine",
		"name": "Wine - Wine-GE-Proton8-27-LoL",
		"type": "wine",
		"lib": "/home/alm/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-27-LoL/lib64",
		"lib32": "/home/alm/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-27-LoL/lib",
		"wineserver": "/home/alm/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-27-LoL/bin/wineserver"
	},
	"winePrefix": "/home/alm/Games/Heroic/Prefixes/default/Rocket League",
	"wineCrossoverBottle": "",
	"autoInstallDxvkNvapi": true
}

Game launched at: Fri Dec 22 2023 09:06:42 GMT+0600 (East Kazakhstan Time)

An exception occurred when launching the game:
Error: ENOENT: no such file or directory, scandir '/home/alm/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/dxvk-nvapi/dxvk-nvapi-v0.6.4/x32'
    at Object.readdirSync (node:fs:1527:3)
    at Object.readdirSync (node:electron/js2c/asar_bundle:2:10980)
    at Object.installRemove (/app/bin/heroic/resources/app.asar/build/electron/main.52896897.js:87:68)
    at prepareWineLaunch (/app/bin/heroic/resources/app.asar/build/electron/main.52896897.js:91:1575)
    at async runWineCommandOnGame$1 (/app/bin/heroic/resources/app.asar/build/electron/main.52896897.js:81:1410)
    at async legendarySetup (/app/bin/heroic/resources/app.asar/build/electron/main.52896897.js:90:2497)
    at async prepareWineLaunch (/app/bin/heroic/resources/app.asar/build/electron/main.52896897.js:91:1422)
    at async Module.launch$1 [as launch] (/app/bin/heroic/resources/app.asar/build/electron/main.52896897.js:78:7684)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.52896897.js:202:450
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:88992)
```

### Steps to reproduce

1. Install the game
2. Click on play button
3. See error (doesn't start)

### Expected behavior

Start the game

### Screenshots

![Screenshot from 2023-12-22 09-21-46](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/66943552/5f8e76f7-92f8-4711-b8c0-b8d2462f65c5)

Ubuntu 22.04.3 LTS (Jammy Jellyfish) (linux)

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS [e. g. "Ubuntu"]  
CPU: 16x AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
Memory: 32.82 GB (used: 1.95 GB)

### Additional information

No response

**Comment by arielj** [comment]
Try this:
- Use Wine-GE-Proton that doesn't end with `-LoL` (that's for League of Legends)
- Disable the option that installs `DXVK-NVAPI`
- Delete `/home/alm/Games/Heroic/Prefixes/default/Rocket League`
- Run the game again

if you still have issues, please report this on our Discord server in the `#support` area which is the best place to get support with specific games
