### ISSUE TITLE
[Core] INFO: Synced app "Jackal" is no longer in the EGL manifest list.

### ISSUE THREAD

**Issue by khewweifeng** [Heroic-Games-Launcher/HeroicGamesLauncher#3442]
### Describe the bug

- Tried logout and login epic account = does not fix the issue 
- Reset Heroic = does not fix the issue

Below are the error message when I try to launch dauntless from Heroic 

```
Legendary (Epic Games)
Error:
An error has occurred! Try to Logout and Login on your Epic account.
[Core] INFO: Trying to re-use existing login session...[Core] INFO: Synced app "Jackal" is no longer in the EGL manifest list.[Core] INFO: Game files exist, assuming game is still installed, re-exporting to EGL...Traceback (most recent call last):
File "legendary\cli.py", line 3149, in <module>File "legendary\cli.py", line 3088, in main
File "legendary\cli.py", line 1622, in info
File "legendary\core.py", line 1192, in is_installed
File "legendary\core.py", line 583, in get_installed_game
File "legendary\core.py", line 1908, in egl_sync
File "legendary\core.py", line 1890, in egl_restore_or_uninstall
File "legendary\core.py", line 1867, in egl_export
File "legendary\lfs\egl.py", line 85, in set_manifestValueError: EGS ProgramData path does not exist
[18032] Failed to execute script 'cli' due to unhandled exception!
```

### Add logs

```text
(22:40:32) INFO:    [Legendary]:        Legendary location: C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(22:40:32) INFO:    [Gog]:              GOGDL location: C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(22:40:32) INFO:    [Connection]:       Connectivity: check-online
(22:40:32) INFO:    [Connection]:       Pinging external endpoints
(22:40:32) INFO:    [Backend]:          DRM module staus {
  "neifaoindggfcjicffkgpmnlppeffabd": {
    "name": "Google Widevine Windows CDM",
    "status": "new",
    "version": "1.0.2738.0"
  },
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(22:40:33) WARNING: [Backend]:          Protocol already registered.
(22:40:33) INFO:    [Connection]:       Connectivity: online
(22:40:33) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(22:40:33) INFO:    [Backend]:          VCRuntime is installed
(22:40:33) INFO:    [Frontend]:         Refreshing undefined Library
(22:40:33) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(22:40:33) INFO:    [Legendary]:        Refreshing library...
(22:40:33) INFO:    [Legendary]:        Refreshing Epic Games...
(22:40:33) INFO:    [Legendary]:        Game list updated, got 296 games & DLCs
(22:40:33) INFO:    [Backend]:          Frontend Ready
(22:40:33) INFO:    [ProtocolHandler]:  received 'heroic://launch/legendary/Jackal'
(22:40:33) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(22:40:33) INFO:    [Gog]:              Found 0 game(s) to update
(22:40:33) INFO:    [Backend]:          Launching Dauntless (Jackal)
(22:40:33) INFO:    [Backend]:          Preventing display from sleep
(22:40:33) INFO:    [Backend]:          Preventing machine to sleep
(22:40:33) INFO:    [Backend]:          Checking for new Heroic Updates
(22:40:33) INFO:    [Backend]:          Checking for current version changelog
(22:40:34) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\kheww\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(22:40:34) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=C:\Users\kheww\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(22:40:34) INFO:    [Legendary]:        Launching Dauntless: HEROIC_APP_NAME=Jackal HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LEGENDARY_CONFIG_PATH=C:\Users\kheww\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch Jackal --language en
(22:40:34) INFO:    [Backend]:          Stopping Power Saver Blocker
(22:40:34) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(22:40:35) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\kheww\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(22:40:35) INFO:    [Gog]:              Running command: C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\kheww\AppData\Roaming\heroic\gog_store\auth.json --version
(22:40:35) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\kheww\AppData\Roaming\heroic\nile_config C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile --version
(22:40:35) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\kheww\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(22:40:35) INFO:    [Gog]:              Running command: C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\kheww\AppData\Roaming\heroic\gog_store\auth.json --version
(22:40:35) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\kheww\AppData\Roaming\heroic\nile_config C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile --version
(22:40:35) INFO:    [WineDownloader]:   Updating wine versions info
(22:40:35) INFO:    [WineDownloader]:   Fetching upstream information...
(22:40:35) INFO:    [Backend]:          
System Information:
CPU: 12x Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz
Memory: 16.96 GB (used: 9.31 GB)
GPUs:
  GPU 0:
    Name: Intel Corporation CometLake-H GT2 [UHD Graphics]
    IDs: D=9bc4 V=8086 SD=50f3 SV=1558
    Driver: 30.0.101.1340
  GPU 1:
    Name: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q]
    IDs: D=2520 V=10de SD=50f3 SV=1558
    Driver: 546.33
OS: Microsoft Windows 11 Home Single Language 10.0.22631 (win32)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.12.0 Vegapunk
  Legendary: 0.20.34 Direct Intervention
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(22:40:36) INFO:    [WineDownloader]:   wine versions updated
(22:40:36) ERROR:   [Backend]:          Could not find default wine version
(22:40:38) INFO:    [Legendary]:        Found 0 games to update
(22:40:38) INFO:    [Backend]:          Starting the Download Queue
(22:43:02) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\kheww\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(22:43:02) INFO:    [Gog]:              Running command: C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\kheww\AppData\Roaming\heroic\gog_store\auth.json --version
(22:43:02) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\kheww\AppData\Roaming\heroic\nile_config C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile --version
(22:43:02) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: LEGENDARY_CONFIG_PATH=C:\Users\kheww\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(22:43:03) INFO:    [Legendary]:        Abort command "LEGENDARY_CONFIG_PATH=C:\Users\kheww\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(22:43:04) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\kheww\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(22:43:04) INFO:    [Gog]:              Running command: C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\kheww\AppData\Roaming\heroic\gog_store\auth.json --version
(22:43:04) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\kheww\AppData\Roaming\heroic\nile_config C:\Users\kheww\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile --version
```

### Steps to reproduce

1. Launch dauntless from HGL 
2. See error

### Expected behavior

Able to launch dauntless from HGL 

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/54496743/0b48ed64-2725-4ed9-9331-6f7146b75f26)

### Heroic Version

Latest Stable

### System Information

Edition	Windows 11 Home Single Language
Version	23H2
Installed on	‎22/‎9/‎2022
OS build	22631.3007
Experience	Windows Feature Experience Pack 1000.22681.1000.0

**Comment by khewweifeng** [comment]
> Seems like you have the EGL sync enabled, did you uninstall Epic recently?

Yes I do uninstalled epic recently.  May I know what should I do to solve this?

**Comment by khewweifeng** [comment]
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/54496743/3834b4fb-e1ab-4ef6-ac88-669abc3231f2)

It seems fixed after I enabled this.

**Comment by CommandMC** [comment]
I would've assumed that *dis*abling that option would fix your issue; still, I assume this is resolved then? Feel free to re-open if it isn't
