### ISSUE TITLE
Unable to reach GOG login page through launcher

### ISSUE THREAD

**Issue by MathMage** [Heroic-Games-Launcher/HeroicGamesLauncher#3468]
### Describe the bug

Clicking 'GOG Login' from the Manage Accounts page takes me to a black screen with black text which, if I highlight it, says '503 Service Temporarily Unavailable'.
The URL that opens: https://auth.gog.com/auth?client_id=46899977096215655&redirect_uri=https%3A%2F%2Fembed.gog.com%2Fon_login_success%3Forigin%3Dclient&response_type=code&layout=galaxy

### Add logs

```text
(22:40:41) INFO:    [Legendary]:        Legendary location: C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(22:40:41) INFO:    [Gog]:              GOGDL location: C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(22:40:41) INFO:    [Connection]:       Connectivity: check-online
(22:40:41) INFO:    [Connection]:       Pinging external endpoints
(22:40:41) INFO:    [Nile]:             Refreshing library...
(22:40:41) INFO:    [Nile]:             Refreshing Amazon Games...
(22:40:41) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\mathm\AppData\Roaming\heroic\nile_config C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile library sync
(22:40:41) INFO:    [Nile]:             Game list updated, got 50 games
(22:40:41) INFO:    [Backend]:          DRM module staus {
  "neifaoindggfcjicffkgpmnlppeffabd": {
    "name": "Google Widevine Windows CDM",
    "status": "new",
    "version": "1.0.2738.0"
  },
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(22:40:41) WARNING: [Backend]:          Protocol already registered.
(22:40:41) INFO:    [Connection]:       Connectivity: online
(22:40:41) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(22:40:42) INFO:    [Backend]:          VCRuntime is installed
(22:40:42) INFO:    [Nile]:             Saved user data to config file
(22:40:42) INFO:    [Frontend]:         Refreshing undefined Library
(22:40:42) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(22:40:42) INFO:    [Legendary]:        Refreshing library...
(22:40:42) INFO:    [Legendary]:        Refreshing Epic Games...
(22:40:42) INFO:    [Nile]:             Refreshing library...
(22:40:42) INFO:    [Nile]:             Refreshing Amazon Games...
(22:40:42) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\mathm\AppData\Roaming\heroic\nile_config C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile library sync
(22:40:42) INFO:    [Nile]:             Game list updated, got 50 games
(22:40:42) INFO:    [Legendary]:        Game list updated, got 130 games & DLCs
(22:40:42) INFO:    [Backend]:          Frontend Ready
(22:40:42) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(22:40:42) INFO:    [Gog]:              Found 0 game(s) to update
(22:40:43) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\mathm\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(22:40:43) INFO:    [Backend]:          Checking for new Heroic Updates
(22:40:43) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=C:\Users\mathm\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(22:40:43) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\mathm\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(22:40:43) INFO:    [Gog]:              Running command: C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\mathm\AppData\Roaming\heroic\gog_store\auth.json --version
(22:40:43) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\mathm\AppData\Roaming\heroic\nile_config C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile --version
(22:40:43) INFO:    [Backend]:          Checking for current version changelog
(22:40:44) INFO:    [Backend]:          
System Information:
CPU: 4x Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
Memory: 8.46 GB (used: 6.03 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GM107M [GeForce GTX 960M]
    IDs: D=139b V=10de SD=1420 SV=1043
    Driver: 536.40
  GPU 1:
    Name: Intel Corporation HD Graphics 530
    IDs: D=191b V=8086 SD=1420 SV=1043
    Driver: 21.20.16.4550
OS: Microsoft Windows 10 Home 10.0.19045 (win32)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.12.0 Vegapunk
  Legendary: 0.20.34 Direct Intervention
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(22:40:45) WARNING: [Legendary]:        Failed to parse games from C:\Users\mathm\AppData\Roaming\heroic\legendaryConfig\legendary\installed.json with: Error: ENOENT: no such file or directory, open 'C:\Users\mathm\AppData\Roaming\heroic\legendaryConfig\legendary\installed.json'
    at Object.openSync (node:fs:603:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:2170)
    at Object.readFileSync (node:fs:471:35)
    at Object.readFileSync (node:electron/js2c/asar_bundle:2:9501)
    at Module.listUpdateableGames (C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.6a14cd2b.js:99:4625)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.6a14cd2b.js:219:3655
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:90734)
(22:40:45) INFO:    [Legendary]:        Found 0 games to update
(22:40:45) INFO:    [Nile]:             Looking for updates...
(22:40:45) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\mathm\AppData\Roaming\heroic\nile_config C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile list-updates --json
(22:40:47) INFO:    [Frontend]:         Refreshing undefined Library
(22:40:47) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(22:40:47) INFO:    [Legendary]:        Refreshing library...
(22:40:47) INFO:    [Legendary]:        Refreshing Epic Games...
(22:40:47) INFO:    [Nile]:             Refreshing library...
(22:40:47) INFO:    [Nile]:             Refreshing Amazon Games...
(22:40:47) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\mathm\AppData\Roaming\heroic\nile_config C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile library sync
(22:40:47) INFO:    [Nile]:             Game list updated, got 50 games
(22:40:47) INFO:    [Legendary]:        Game list updated, got 130 games & DLCs
(22:40:47) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(22:40:47) INFO:    [Gog]:              Found 0 game(s) to update
(22:40:47) INFO:    [Backend]:          Starting the Download Queue
(22:40:48) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\mathm\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(22:40:48) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=C:\Users\mathm\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(22:40:49) WARNING: [Legendary]:        Failed to parse games from C:\Users\mathm\AppData\Roaming\heroic\legendaryConfig\legendary\installed.json with: Error: ENOENT: no such file or directory, open 'C:\Users\mathm\AppData\Roaming\heroic\legendaryConfig\legendary\installed.json'
    at Object.openSync (node:fs:603:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:2170)
    at Object.readFileSync (node:fs:471:35)
    at Object.readFileSync (node:electron/js2c/asar_bundle:2:9501)
    at Module.listUpdateableGames (C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.6a14cd2b.js:99:4625)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.6a14cd2b.js:219:3655
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:90734)
(22:40:49) INFO:    [Legendary]:        Found 0 games to update
(22:40:49) INFO:    [Nile]:             Looking for updates...
(22:40:49) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\mathm\AppData\Roaming\heroic\nile_config C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile list-updates --json


[1/23/2024, 10:40:43 PM] C:\Users\mathm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\mathm\AppData\Roaming\heroic\gog_store\auth.json --version
0.7.3
```

### Steps to reproduce

1. Go to 'Manage Accounts'
2. Log out of GOG if logged in
2. Click on 'GOG Login'

Alternatively:
1. Go to 'Stores'
2. Go to 'GOG Store' if not already selected
3. When prompted with the 'You are NOT logged in' warning, click 'LOG IN'

### Expected behavior

Clicking on 'GOG Login' should take me to the login page.

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/8551285/8da1ea31-73fd-4680-bf3d-4f29ec80d0bf)
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/8551285/6020dea0-63d1-4a2a-a849-8bd3b0b78faf)

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Windows 10 Home

**Comment by imLinguin** [comment]
GOG is having server issues now, try again later
