### ISSUE TITLE
Progress is not showing in Window Icon

### ISSUE THREAD

**Issue by JakobDev** [Heroic-Games-Launcher/HeroicGamesLauncher#3478]
### Describe the bug

The [latest update](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.12.0) added the following:

> [UI] Show a progress bar in the task bar for various app activity 

This is not working on my System (Manjaro KDE).

### Add logs

```text
(17:44:20) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(17:44:20) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:44:20) INFO:    [Connection]:       Connectivity: check-online
(17:44:20) INFO:    [Connection]:       Pinging external endpoints
(17:44:20) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(17:44:20) WARNING: [Backend]:          Protocol already registered.
(17:44:20) INFO:    [Connection]:       Connectivity: online
(17:44:20) INFO:    [Backend]:          User Not Found, removing it from Store
(17:44:20) INFO:    [Gog]:              Checking if login is valid
(17:44:20) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jakob/.config/heroic/gog_store/auth.json auth
(17:44:20) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(17:44:21) INFO:    [Frontend]:         Refreshing undefined Library
(17:44:21) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(17:44:21) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jakob/.config/heroic/gog_store/auth.json auth
(17:44:21) INFO:    [Legendary]:        Refreshing library...
(17:44:21) INFO:    [Backend]:          Frontend Ready
(17:44:21) INFO:    [Gog]:              Saved username to config file
(17:44:21) INFO:    [Backend]:          Checking for new Heroic Updates
(17:44:21) INFO:    [Backend]:          Checking for current version changelog
(17:44:21) INFO:    [Gog]:              Getting GOG library
(17:44:21) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jakob/.config/heroic/gog_store/auth.json auth
(17:44:22) WARNING: [Backend]:          No clientId in goggame-1438074791.info file. Cannot resolve save path
(17:44:22) INFO:    [Gog]:              Saved games data
(17:44:22) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(17:44:22) INFO:    [Gog]:              Found 4 game(s) to update
(17:44:23) INFO:    [Winetricks]:       Downloading Winetricks
(17:44:25) INFO:    [WineDownloader]:   Updating wine versions info
(17:44:25) INFO:    [WineDownloader]:   Fetching upstream information...
(17:44:25) INFO:    [WineDownloader]:   wine versions updated
(17:44:26) INFO:    [Backend]:          Starting the Download Queue
(17:44:27) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for The Settlers 4 Gold Edition
(17:44:27) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jakob/.config/heroic/gog_store/auth.json auth
(17:44:27) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for The Settlers 4 Gold Edition
(17:44:27) INFO:    [Gog]:              Got install info from cache for 1207659254 on windows platform
(17:44:27) INFO:    [Gog]:              Got install info from cache for 1207659254 on windows platform
(17:44:28) INFO:    [Gog]:              Got install info from cache for 1207659254 on windows platform
(17:44:28) ERROR:   [Backend]:          Failed to check disk space for "'/run/media/jakob/Datenplatte/Heroic'": InvalidPathError: The following path is invalid (should start by /): '/run/media/jakob/Datenplatte/Heroic'
    at /opt/Heroic/resources/app.asar/node_modules/check-disk-space/dist/check-disk-space.cjs:176:24
    at new Promise (<anonymous>)
    at checkUnix (/opt/Heroic/resources/app.asar/node_modules/check-disk-space/dist/check-disk-space.cjs:175:20)
    at Object.checkDiskSpace [as default] (/opt/Heroic/resources/app.asar/node_modules/check-disk-space/dist/check-disk-space.cjs:196:12)
    at /opt/Heroic/resources/app.asar/build/electron/main.85aacd75.js:219:806
    at FSReqCallback.oncomplete (node:fs:200:23)
(17:44:28) WARNING: [Backend]:          Cannot write to "'/run/media/jakob/Datenplatte/Heroic'": Error: ENOENT: no such file or directory, access ''
(17:44:28) DEBUG:   [Backend]:          {"free":0,"diskSize":0,"message":"0 B / 0 B","validPath":false,"validFlatpakPath":true}
(17:44:28) ERROR:   [Backend]:          Failed to check disk space for "'/run/media/jakob/Datenplatte/Heroic'": InvalidPathError: The following path is invalid (should start by /): '/run/media/jakob/Datenplatte/Heroic'
    at /opt/Heroic/resources/app.asar/node_modules/check-disk-space/dist/check-disk-space.cjs:176:24
    at new Promise (<anonymous>)
    at checkUnix (/opt/Heroic/resources/app.asar/node_modules/check-disk-space/dist/check-disk-space.cjs:175:20)
    at Object.checkDiskSpace [as default] (/opt/Heroic/resources/app.asar/node_modules/check-disk-space/dist/check-disk-space.cjs:196:12)
    at /opt/Heroic/resources/app.asar/build/electron/main.85aacd75.js:219:806
    at FSReqCallback.oncomplete (node:fs:200:23)
(17:44:28) WARNING: [Backend]:          Cannot write to "'/run/media/jakob/Datenplatte/Heroic'": Error: ENOENT: no such file or directory, access ''
(17:44:28) DEBUG:   [Backend]:          {"free":0,"diskSize":0,"message":"0 B / 0 B","validPath":false,"validFlatpakPath":true}
(17:44:31) INFO:    [Backend]:          Writing config for 1207659254
(17:44:31) INFO:    [Gog]:              Got install info from cache for 1207659254 on windows platform
(17:44:31) INFO:    [DownloadManager]:  The Settlers® 4: Gold Edition  was added to the download queue.
(17:44:31) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jakob/.config/heroic/gog_store/auth.json auth
(17:44:31) INFO:    [Backend]:          Preventing machine to sleep
(17:44:31) INFO:    [Gog]:              Got install info from cache for 1207659254 on windows platform
(17:44:31) INFO:    [Gog]:              Got install info from cache for 1207659254 on windows platform
(17:44:31) INFO:    [Gog]:              Got install info from cache for 1207659254 on windows platform
(17:44:31) INFO:    [Gog]:              Got install info from cache for 1207659254 on windows platform
(17:44:31) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://raw.githubusercontent.com/Heroic-Games-Launcher/known-fixes/main/1207659254-gog.json. 
Error: Error: Request failed with status code 404
(17:44:31) INFO:    [Gog]:              Installing 1207659254: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jakob/.config/heroic/gog_store/auth.json download 1207659254 --platform windows --path=/run/media/jakob/Datenplatte/Heroic --token <redacted> --skip-dlcs --lang=en-US
(17:44:31) DEBUG:   [Gog]:              Logging to file "/home/jakob/.config/heroic/GamesConfig/1207659254.log"
(17:44:35) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 0.03%/0.00MB/00:00:00 Down: 0.2MB/s / Disk: 0.62MB/s
(17:44:36) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 0.9%/5.65MB/00:05:29 Down: 5.45MB/s / Disk: 9.45MB/s
(17:44:37) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 2.21%/13.81MB/00:02:57 Down: 8.14MB/s / Disk: 15.07MB/s
(17:44:38) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 3.09%/27.72MB/00:02:37 Down: 5.5MB/s / Disk: 9.39MB/s
(17:44:39) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 4.43%/35.08MB/00:02:09 Down: 7.36MB/s / Disk: 21.23MB/s
(17:44:40) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 5.61%/40.60MB/00:01:57 Down: 5.51MB/s / Disk: 9.38MB/s
(17:44:41) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 6.49%/48.62MB/00:01:55 Down: 8.01MB/s / Disk: 55.27MB/s
(17:44:42) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 7.78%/53.70MB/00:01:46 Down: 5.07MB/s / Disk: 8.22MB/s
(17:44:43) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 8.59%/61.07MB/00:01:46 Down: 7.37MB/s / Disk: 7.37MB/s
(17:44:44) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 9.77%/69.93MB/00:01:41 Down: 8.86MB/s / Disk: 13.82MB/s
(17:44:45) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 11.19%/73.23MB/00:01:35 Down: 3.29MB/s / Disk: 6.79MB/s
(17:44:46) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 11.71%/82.61MB/00:01:38 Down: 9.37MB/s / Disk: 56.22MB/s
(17:44:47) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 13.21%/89.22MB/00:01:32 Down: 6.6MB/s / Disk: 16.57MB/s
(17:44:48) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 14.27%/95.45MB/00:01:30 Down: 6.23MB/s / Disk: 11.2MB/s
(17:44:49) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 15.27%/102.46MB/00:01:28 Down: 7MB/s / Disk: 9.51MB/s
(17:44:50) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 16.39%/109.68MB/00:01:26 Down: 7.21MB/s / Disk: 27.17MB/s
(17:44:51) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 17.54%/116.95MB/00:01:24 Down: 7.27MB/s / Disk: 31.26MB/s
(17:44:52) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 18.71%/123.91MB/00:01:22 Down: 6.95MB/s / Disk: 19.95MB/s
(17:44:53) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 19.82%/130.43MB/00:01:21 Down: 6.51MB/s / Disk: 6.51MB/s
(17:44:54) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 20.86%/135.43MB/00:01:19 Down: 4.99MB/s / Disk: 4.99MB/s
(17:44:55) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 21.66%/144.25MB/00:01:19 Down: 8.81MB/s / Disk: 10.67MB/s
(17:44:56) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 23.07%/150.83MB/00:01:16 Down: 6.57MB/s / Disk: 26.05MB/s
(17:44:57) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 24.12%/156.54MB/00:01:15 Down: 5.7MB/s / Disk: 17.7MB/s
(17:44:58) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 25.04%/164.03MB/00:01:14 Down: 7.48MB/s / Disk: 11.1MB/s
(17:44:59) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 26.24%/171.53MB/00:01:13 Down: 7.49MB/s / Disk: 26.93MB/s
(17:45:00) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/jakob/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(17:45:00) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jakob/.config/heroic/gog_store/auth.json --version
(17:45:00) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/jakob/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(17:45:00) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 27.43%/179.07MB/00:01:11 Down: 7.54MB/s / Disk: 14.16MB/s
(17:45:00) INFO:    [Backend]:          
System Information:
CPU: 12x AMD Ryzen 5 2600 Six-Core Processor
Memory: 16.72 GB (used: 7.14 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation TU106 [GeForce RTX 2060 SUPER]
    IDs: D=1f06 V=10de SD=13a3 SV=10de
    Driver: nvidia
OS: Manjaro Linux 6.1.71-1-MANJARO (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.12.0 Vegapunk
  Legendary: 0.20.34 Direct Intervention
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(17:45:01) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 28.64%/185.40MB/00:01:09 Down: 6.33MB/s / Disk: 15.72MB/s
(17:45:02) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 29.65%/190.40MB/00:01:08 Down: 4.99MB/s / Disk: 7.53MB/s
(17:45:03) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 30.45%/199.57MB/00:01:08 Down: 9.16MB/s / Disk: 20.58MB/s
(17:45:04) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 31.92%/205.37MB/00:01:06 Down: 5.79MB/s / Disk: 11.68MB/s
(17:45:05) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 32.85%/212.95MB/00:01:05 Down: 7.58MB/s / Disk: 29.88MB/s
(17:45:06) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 34.06%/218.99MB/00:01:03 Down: 6.04MB/s / Disk: 32.26MB/s
(17:45:07) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 35.03%/226.52MB/00:01:03 Down: 7.52MB/s / Disk: 22.19MB/s
(17:45:08) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 36.23%/231.92MB/00:01:01 Down: 5.4MB/s / Disk: 9.9MB/s
(17:45:09) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 37.09%/241.07MB/00:01:01 Down: 9.15MB/s / Disk: 15.45MB/s
(17:45:10) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 38.56%/248.01MB/00:00:59 Down: 6.93MB/s / Disk: 18.17MB/s
(17:45:11) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 39.67%/255.42MB/00:00:57 Down: 7.41MB/s / Disk: 17.14MB/s
(17:45:12) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 40.85%/261.88MB/00:00:56 Down: 6.45MB/s / Disk: 17.36MB/s
(17:45:13) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 41.89%/269.34MB/00:00:55 Down: 7.45MB/s / Disk: 15.32MB/s
(17:45:14) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 43.08%/275.11MB/00:00:54 Down: 5.77MB/s / Disk: 11.92MB/s
(17:45:15) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 44%/283.38MB/00:00:53 Down: 8.27MB/s / Disk: 13.82MB/s
(17:45:16) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 45.33%/288.99MB/00:00:51 Down: 5.6MB/s / Disk: 12.65MB/s
(17:45:17) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 46.22%/298.15MB/00:00:51 Down: 9.15MB/s / Disk: 21.84MB/s
(17:45:18) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 47.69%/302.93MB/00:00:49 Down: 4.77MB/s / Disk: 11.91MB/s
(17:45:19) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 48.45%/311.10MB/00:00:49 Down: 8.16MB/s / Disk: 15.75MB/s
(17:45:20) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 49.76%/318.96MB/00:00:47 Down: 7.85MB/s / Disk: 23.46MB/s
(17:45:21) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 51.01%/324.58MB/00:00:46 Down: 5.62MB/s / Disk: 13.9MB/s
(17:45:22) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 51.91%/332.04MB/00:00:45 Down: 7.45MB/s / Disk: 14.3MB/s
(17:45:23) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 53.11%/338.66MB/00:00:44 Down: 6.61MB/s / Disk: 14.75MB/s
(17:45:24) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 54.17%/346.99MB/00:00:43 Down: 8.33MB/s / Disk: 17.26MB/s
(17:45:25) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 55.5%/351.65MB/00:00:41 Down: 4.66MB/s / Disk: 9.71MB/s
(17:45:26) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 56.24%/359.21MB/00:00:41 Down: 7.55MB/s / Disk: 15.71MB/s
(17:45:27) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 57.45%/366.05MB/00:00:40 Down: 6.84MB/s / Disk: 14.18MB/s
(17:45:28) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 58.55%/373.25MB/00:00:38 Down: 7.19MB/s / Disk: 14.95MB/s
(17:45:29) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 59.7%/381.74MB/00:00:37 Down: 8.48MB/s / Disk: 16.52MB/s
(17:45:30) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 61.06%/386.85MB/00:00:36 Down: 5.11MB/s / Disk: 11.6MB/s
(17:45:31) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 61.87%/395.76MB/00:00:35 Down: 8.9MB/s / Disk: 19.71MB/s
(17:45:32) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 63.3%/398.08MB/00:00:34 Down: 2.32MB/s / Disk: 5.68MB/s
(17:45:33) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 63.67%/406.92MB/00:00:34 Down: 8.84MB/s / Disk: 12.78MB/s
(17:45:34) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 65.08%/411.51MB/00:00:32 Down: 4.59MB/s / Disk: 6.28MB/s
(17:45:35) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 65.82%/422.01MB/00:00:32 Down: 10.49MB/s / Disk: 13.16MB/s
(17:45:36) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 67.5%/427.57MB/00:00:30 Down: 5.55MB/s / Disk: 9.22MB/s
(17:45:37) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 68.39%/432.53MB/00:00:29 Down: 4.96MB/s / Disk: 5.99MB/s
(17:45:38) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 69.18%/441.34MB/00:00:28 Down: 8.8MB/s / Disk: 12.69MB/s
(17:45:39) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 70.59%/446.48MB/00:00:27 Down: 5.13MB/s / Disk: 8.35MB/s
(17:45:40) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 71.41%/455.55MB/00:00:26 Down: 9.07MB/s / Disk: 12.2MB/s
(17:45:41) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 72.86%/460.46MB/00:00:25 Down: 4.9MB/s / Disk: 6.91MB/s
(17:45:42) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 73.65%/470.09MB/00:00:24 Down: 9.63MB/s / Disk: 17.74MB/s
(17:45:43) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 75.19%/474.11MB/00:00:23 Down: 4.01MB/s / Disk: 8.89MB/s
(17:45:44) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 75.83%/481.59MB/00:00:22 Down: 7.48MB/s / Disk: 10.08MB/s
(17:45:45) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 77.03%/490.86MB/00:00:21 Down: 9.25MB/s / Disk: 13.97MB/s
(17:45:46) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 78.51%/496.05MB/00:00:20 Down: 5.19MB/s / Disk: 7.4MB/s
(17:45:47) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 79.34%/502.30MB/00:00:19 Down: 6.25MB/s / Disk: 8.51MB/s
(17:45:48) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 80.34%/510.11MB/00:00:18 Down: 7.8MB/s / Disk: 9.67MB/s
(17:45:49) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 81.59%/516.28MB/00:00:17 Down: 6.17MB/s / Disk: 11.35MB/s
(17:45:50) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 82.58%/522.89MB/00:00:16 Down: 6.6MB/s / Disk: 9.22MB/s
(17:45:51) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 83.63%/530.49MB/00:00:15 Down: 7.59MB/s / Disk: 33.42MB/s
(17:45:52) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 84.85%/536.50MB/00:00:14 Down: 6MB/s / Disk: 9MB/s
(17:45:53) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 85.81%/545.20MB/00:00:13 Down: 8.7MB/s / Disk: 12.43MB/s
(17:45:54) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 87.2%/549.83MB/00:00:11 Down: 4.62MB/s / Disk: 24.45MB/s
(17:45:55) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 87.94%/557.85MB/00:00:11 Down: 8.01MB/s / Disk: 15.04MB/s
(17:45:56) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 89.22%/565.14MB/00:00:10 Down: 7.28MB/s / Disk: 39.82MB/s
(17:45:57) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 90.39%/572.43MB/00:00:08 Down: 7.28MB/s / Disk: 15.66MB/s
(17:45:58) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 91.56%/576.82MB/00:00:07 Down: 4.39MB/s / Disk: 5.78MB/s
(17:45:59) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 92.26%/583.86MB/00:00:07 Down: 7.04MB/s / Disk: 16.11MB/s
(17:46:00) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 93.38%/592.72MB/00:00:06 Down: 8.85MB/s / Disk: 16.09MB/s
(17:46:01) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 94.8%/599.66MB/00:00:04 Down: 6.93MB/s / Disk: 12.9MB/s
(17:46:02) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 95.91%/604.65MB/00:00:03 Down: 4.98MB/s / Disk: 8.98MB/s
(17:46:03) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 96.71%/612.68MB/00:00:03 Down: 8.03MB/s / Disk: 20.09MB/s
(17:46:04) INFO:    [Gog]:              Progress for The Settlers® 4: Gold Edition: 97.99%/621.73MB/00:00:01 Down: 9.05MB/s / Disk: 16.13MB/s
(17:46:05) INFO:    [Gog]:              Got install info from cache for 1207659254 on windows platform
(17:46:05) INFO:    [Backend]:          Adding shortcuts for The Settlers® 4: Gold Edition
(17:46:05) INFO:    [DownloadManager]:  Finished Installation of 1207659254
(17:46:05) INFO:    [DownloadManager]:  1207659254 added to download manager finished.
(17:46:05) INFO:    [DownloadManager]:  1207659254 removed from download manager.
(17:46:05) INFO:    [Frontend]:         Refreshing gog Library
(17:46:05) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jakob/.config/heroic/gog_store/auth.json auth
(17:46:05) INFO:    [Gog]:              Getting GOG library
(17:46:05) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jakob/.config/heroic/gog_store/auth.json auth
(17:46:06) WARNING: [Backend]:          No clientId in goggame-1438074791.info file. Cannot resolve save path
(17:46:06) INFO:    [Gog]:              Saved games data
```

### Steps to reproduce

Just download a Game

### Expected behavior

The download Progress in shown in the Window Icon

### Heroic Version

Latest Stable

### System Information

- OS: Manjaro KDE with all Updates
- Heroic is installed from the AUR

### Additional information

If I run
```
gdbus emit --session -o / -s com.canonical.Unity.LauncherEntry.Update  "application://heroic.desktop" "{'progress':<0.5>,'progress-visible':<true>}"
```
to call the API directly, the Progress is correctly shown in the Icon:
![grafik](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/15185051/fab0b77f-a3ef-4234-91be-0a39ed9232d3)

So this is definitely supported in KDE and the Issue is on the side of Heroic.

**Comment by arielj** [comment]
This is a limitation of Electron, we use the setProgressBar method that only works on Unity desktop on linux: https://www.electronjs.org/docs/latest/api/browser-window#winsetprogressbarprogress-options

```
On Linux platform, only supports Unity desktop environment, you need to specify the *.desktop file name to desktopName field in package.json. By default, it will assume {app.name}.desktop.
```

While I guess we could try to find other ways of do that without using Electron's features, I think it's better to request this in Electron's repo so they fix that there to improve the compatibility instead.

**Comment by JakobDev** [comment]
The Electron documentation is a bit misleading. The standard was originally made for Unity, but is also supported n other Desktops such as KDE nowadays. KDE is providing [exact the same API](https://wiki.ubuntu.com/Unity/LauncherAPI#Low_level_DBus_API:_com.canonical.Unity.LauncherEntry), so everything working on the (no longer existing) Unity also works on KDE. I can take a look at Electron itself, but I'm not a Electron developer.

**Comment by imLinguin** [comment]
Electron uses `libunity` for that and not DBus (unless libunity wraps arround DBus interface too). I believe this is related to the warning in the wiki you linked.
> While the libunity API is stable, the DBus protocol underneath is not. We strongly discourage anyone from relying on it

**Comment by JakobDev** [comment]
I have now installed libunity from the AUR. It's now working. Maybe you could add libunity to the dependencies.

> (unless libunity wraps arround DBus interface too)

It does exactly that.

> I believe this is related to the warning in the wiki you linked.

You can ignore that warning. This Interface was created around 10 years ago. It had never changed. There are a lot of programs who call this API directly. Unity no longe exists and this Interface is also supported by other Desktops too, so it will never change. Maybe we get some Day a more official Way as part of the xdg-desktop-portals, but the current Interface will stay. I will create a Issue at Electron to emit the DBus Signal directly.

libunity could also be included in The Flatpak, but the Flatpak has another problem: The Interface needs the desktop filename to work, but in the Flatpak the desktop file is `com.heroicgameslauncher.hgl.desktop` while it's `heroic.desktop` in the native packges. I think we should change it to `com.heroicgameslauncher.hgl.desktop` in the native packages too.
