### ISSUE TITLE
electron.napi.node not found in resources

### ISSUE THREAD

**Issue by darkwolf1000** [Heroic-Games-Launcher/HeroicGamesLauncher#3504]
### Describe the bug

I want to open the launcher noting opens so I tried the CLI and got this
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT, node_modules/lzma-native/prebuilds/linux-x64/electron.napi.node not found in /opt/Heroic/resources/app.asar
    at createError (node:electron/js2c/asar_bundle:2:1574)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2293)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at load (/opt/Heroic/resources/app.asar/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at /opt/Heroic/resources/app.asar/node_modules/lzma-native/index.js:9:39
    at Object.<anonymous> (/opt/Heroic/resources/app.asar/node_modules/lzma-native/index.js:595:3)
```

### Add logs

```text
in ./config/heroic/Crashpad
efe5e42e-11d4-421c-9fa9-04a511b363fd
```

### Steps to reproduce

1. Install heroic-games-launcher-bin from AUR
2. Open Launcher
3. See nothing
4. Open in terminal 
5. See Error 

### Expected behavior

Launcher starts and you can manage and play your games

### Screenshots

![Screenshot_20240202_020156](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/76166024/10ea5194-1202-426d-91bc-b285b3645816)

### Heroic Version

Latest Stable

### System Information

- OS Arch
- Source AUR/heroic-games-launcher-bin 2.12.1-1
- Kernel 6.6.14-201.fsync.fc39.x86_64

**Comment by arielj** [comment]
closing since this is really old (heroic 2.12.1-1) and we are in 2.15.2 already

if it's still a problem we can reopen it
