### ISSUE TITLE
Unable to launch GOG games when GOG servers are down?

### ISSUE THREAD

**Issue by Nocifer** [Heroic-Games-Launcher/HeroicGamesLauncher#3538]
### Describe the bug

GOG have just gone into maintenance mode for the next few hours and it seems I can't launch any GOG games due to the servers being offline, due to the error displayed in the log below.

So apparently Heroic Launcher can't fail gracefully and enter offline mode when local connectivity exists but the remote servers are down for some reason?

### Add logs

```text
Launching "Cyberpunk 2077" (gog)
...

Game launched at: Thu Feb 08 2024 18:08:48 GMT+0200 (Eastern European Standard Time)

Launch Command: HEROIC_APP_NAME=1423049311 HEROIC_APP_RUNNER=gog HEROIC_APP_SOURCE=gog LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= DOTNET_ROOT= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/nocifer/.local/share/.steam/steam STEAM_COMPAT_DATA_PATH="/home/nocifer/Games/.wine/Cyberpunk 2077" STEAM_COMPAT_INSTALL_PATH="/home/nocifer/Games/Cyberpunk 2077" WINE_FULLSCREEN_FSR=1 WINE_FULLSCREEN_FSR_STRENGTH=2 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId="heroic-Cyberpunk 2077" PROTON_LOG_DIR=/home/nocifer/.local/share /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/home/nocifer/Games/Cyberpunk 2077" 1423049311 --no-wine --wrapper "/usr/bin/mangohud --dlsym /home/nocifer/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/run '--filesystem=/home/nocifer/Games/Cyberpunk 2077' -- '/usr/share/steam/compatibilitytools.d/proton-ge-custom/proton' run" --platform windows

Game Log:
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 536, in _make_request
  File "urllib3/connection.py", line 461, in getresponse
  File "http/client.py", line 1377, in getresponse
  File "http/client.py", line 320, in begin
  File "http/client.py", line 281, in _read_status
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1242, in recv_into
  File "ssl.py", line 1100, in read
socket.timeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 486, in send
  File "urllib3/connectionpool.py", line 844, in urlopen
  File "urllib3/util/retry.py", line 470, in increment
  File "urllib3/util/util.py", line 39, in reraise
  File "urllib3/connectionpool.py", line 790, in urlopen
  File "urllib3/connectionpool.py", line 538, in _make_request
  File "urllib3/connectionpool.py", line 370, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='auth.gog.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gogdl/cli.py", line 51, in <module>
  File "gogdl/cli.py", line 30, in main
  File "gogdl/api.py", line 21, in __init__
  File "gogdl/auth.py", line 59, in get_credentials
  File "gogdl/auth.py", line 106, in refresh_credentials
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 532, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='auth.gog.com', port=443): Read timed out. (read timeout=10)
[17417] Failed to execute script 'cli' due to unhandled exception!
============= End of game logs =============
```

### Steps to reproduce

1. Hack GOG's servers and disable them (or just wait for GOG to go into maintenance).
2. Launch a GOG game.
3. Fail to launch said GOG game.

### Expected behavior

The GOG game is launched.

### Heroic Version

Latest Stable

### System Information

OS: Arch Linux

### Additional information

Perhaps this could be a good opportunity to also think about introducing a manual toggle for offline mode in the UI.

**Comment by imLinguin** [comment]
Could you check if the issue happens on main branch? It's possible that this has been fixed during the refactor

**Comment by Nocifer** [comment]
I just built the AUR package (can't build directly from the repo atm but it's practically the same thing) and it also fails with the same error.

**Comment by MinaOnMars** [comment]
I can confirm that the same error occurs on Fedora 39 with the flatpak version of Heroic (v2.12.1)

I had been using the autosave beta with GOG games. I tried with that on and off, neither option let me launch the game, however it being "off" is what let me see this error. Otherwise, it didn't even get this far into launching. The log file with autosave on was overwritten, and I do not remember the location of the cloud save folder to set it up manually. If I find that I will try to recreate that error log if requested.

From my logs (autosave off):
Launching "Control Ultimate Edition" (gog)
...
OS: Fedora Linux 39 (Workstation Edition) (linux)
...
Game Log:
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 536, in _make_request
  File "urllib3/connection.py", line 461, in getresponse
  File "http/client.py", line 1377, in getresponse
  File "http/client.py", line 320, in begin
  File "http/client.py", line 281, in _read_status
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1242, in recv_into
  File "ssl.py", line 1100, in read
socket.timeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 486, in send
  File "urllib3/connectionpool.py", line 844, in urlopen
  File "urllib3/util/retry.py", line 470, in increment
  File "urllib3/util/util.py", line 39, in reraise
  File "urllib3/connectionpool.py", line 790, in urlopen
  File "urllib3/connectionpool.py", line 538, in _make_request
  File "urllib3/connectionpool.py", line 370, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='auth.gog.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gogdl/cli.py", line 51, in <module>
  File "gogdl/cli.py", line 30, in main
  File "gogdl/api.py", line 21, in __init__
  File "gogdl/auth.py", line 59, in get_credentials
  File "gogdl/auth.py", line 106, in refresh_credentials
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 532, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='auth.gog.com', port=443): Read timed out. (read timeout=10)
[1101] Failed to execute script 'cli' due to unhandled exception!
============= End of game logs =============

**Comment by Nocifer** [comment]
Yup, I guess it just checks for local connectivity and if that fails goes into offline mode, but if it succeeds then it just assumes everything is dandy and doesn't know how to handle a timeout on the remote server's part, i.e. it treats it as always online.

To be honest this is the first time I can remember GOG being down for any amount of extensive (not to mention preplanned) time, so it's not exactly implausible that this scenario simply never occurred to the developers :P

**Comment by imLinguin** [comment]
I just pushed a patch for gogdl (to be used only with main branch). That should cover the issue

**Comment by sluedecke** [comment]
How can I best test this?

I pulled from main and set this in my `/etc/hosts`:

```shell
127.0.0.1       gog.com
127.0.0.1       embed.gog.com
127.0.0.1       gamesdb.gog.com
127.0.0.1       galaxy-library.gog.com
127.0.0.1       content-system.gog.com
127.0.0.1       remote-config.gog.com
127.0.0.1       af.gog.com
127.0.0.1       auth.gog.com
127.0.0.1       images.gog.com
127.0.0.1       api.gog.com
127.0.0.1       gameplay.gog.com
```

If set,  game detail pages quickly switch to "Cannot get game info" (same with 1.12.1).

**Comment by roland-5** [comment]
I log out and log in again and everything is now OK.

**Comment by hardpenguin** [comment]
> I log out and log in again and everything is now OK.

I tried that, getting error: 504 Gateway Time-out :(

**Comment by hardpenguin** [comment]
Looks like the error was on GOG side? I was not able to log in in the web browser as well. Now everything works OK, I logged in within Heroic and I am able to retrieve game data and install games.

**Comment by imLinguin** [comment]
Yes, GOG is slowly going back online after yesterday's maintenance. Downloading games may still be affected, please be patient.

**Comment by arielj** [comment]
Closing this, GOG is working fine now and the latest 2.13.0 release has some measure to prevent this problem when it's down
