### ISSUE TITLE
Cannot login to GoG

### ISSUE THREAD

**Issue by Roman19S** [Heroic-Games-Launcher/HeroicGamesLauncher#3539]
### Describe the bug

Trying to login to GoG will cause the in app browser to load for a bit and then say "An error occurred while processing your request."

### Add logs

```text
(13:07:52) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(13:07:52) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(13:07:52) INFO:    [Connection]:       Connectivity: check-online
(13:07:52) INFO:    [Connection]:       Pinging external endpoints
(13:07:52) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(13:07:52) WARNING: [Backend]:          Failed to register protocol with OS.
(13:07:52) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/sebi/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(13:07:52) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/sebi/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(13:07:52) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/sebi/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(13:07:52) INFO:    [Connection]:       Connectivity: online
(13:07:52) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(13:07:52) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(13:07:52) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 7 5800X 8-Core Processor
Memory: 67.32 GB (used: 7.93 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 32 [Radeon RX 7700 XT / 7800 XT]
    IDs: D=747e V=1002 SD=5326 SV=1849
    Driver: amdgpu
  GPU 1:
    Name: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti]
    IDs: D=1c82 V=10de SD=3351 SV=1462
    Driver: nouveau
OS: openSUSE Tumbleweed 6.7.2-1-default (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.12.1 Vegapunk
  Legendary: 0.20.34 Direct Intervention
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(13:07:52) INFO:    [Frontend]:         Refreshing undefined Library
(13:07:52) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(13:07:52) INFO:    [Legendary]:        Refreshing library...
(13:07:52) INFO:    [Legendary]:        Refreshing Epic Games...
(13:07:52) INFO:    [Legendary]:        Game list updated, got 385 games & DLCs
(13:07:52) INFO:    [Backend]:          Frontend Ready
(13:07:52) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(13:07:52) INFO:    [Gog]:              Found 0 game(s) to update
(13:07:52) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/sebi/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(13:07:52) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/sebi/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(13:07:52) INFO:    [Backend]:          Checking for current version changelog
(13:07:54) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(13:07:54) INFO:    [Winetricks]:       Downloading Winetricks
(13:07:54) WARNING: [Legendary]:        Failed to parse games from /home/sebi/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/home/sebi/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json'
    at Object.openSync (node:fs:603:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:2131)
    at Object.readFileSync (node:fs:471:35)
    at Object.readFileSync (node:electron/js2c/asar_bundle:2:9462)
    at Module.listUpdateableGames (/app/bin/heroic/resources/app.asar/build/electron/main.b338ec9c.js:99:4625)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.b338ec9c.js:219:3655
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:88992)
(13:07:54) INFO:    [Legendary]:        Found 0 games to update
(13:07:57) INFO:    [WineDownloader]:   Updating wine versions info
(13:07:57) INFO:    [WineDownloader]:   Fetching upstream information...
(13:07:57) INFO:    [WineDownloader]:   wine versions updated
(13:07:57) INFO:    [Backend]:          Starting the Download Queue
```

### Steps to reproduce

1. Open Heroic
2. Click on "Manage Accounts"
3. Click on "GOG LOGIN"

### Expected behavior

I expect the GoG login screen to appear

### Screenshots

![Screenshot_20240208_130502](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/30319719/6b7e58f9-53fd-4bc8-9428-747d3fb79f40)

### Heroic Version

Latest Stable (Flatpak)

### System Information

![Screenshot_20240208_130705](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/30319719/e569cc7b-e85d-4ea9-afcf-920f51e91d88)
![Screenshot_20240208_131041](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/30319719/99b1373b-da25-4f46-9e55-9d9553ef1ea6)

**Comment by imLinguin** [comment]
GOG is in the process of rebooting their infrastructure. You can follow their status on [X](https://x.com/GOGcom)
