### ISSUE TITLE
Unable to get game info from gog on macOS

### ISSUE THREAD

**Issue by lukehaas** [Heroic-Games-Launcher/HeroicGamesLauncher#3580]
### Describe the bug

Attempting to install a game from GoG, but it fails due to an error retrieving the game info.

### Add logs

```text
(12:42:31) INFO:    [Legendary]:        Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(12:42:31) INFO:    [Gog]:              GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(12:42:31) INFO:    [Connection]:       Connectivity: check-online
(12:42:31) INFO:    [Connection]:       Pinging external endpoints
(12:42:31) INFO:    [Gog]:              Checking for existing gog manifests
(12:42:31) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(12:42:31) WARNING: [Backend]:          Protocol already registered.
(12:42:31) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(12:42:31) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" --version
(12:42:31) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/nile_config" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/nile --version
(12:42:31) INFO:    [Connection]:       Connectivity: online
(12:42:31) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
(12:42:31) INFO:    [Backend]:          User Not Found, removing it from Store
(12:42:31) INFO:    [Gog]:              Checking if login is valid
(12:42:31) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
(12:42:32) INFO:    [Frontend]:         Refreshing undefined Library
(12:42:32) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(12:42:32) INFO:    [Legendary]:        Refreshing library...
(12:42:32) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
(12:42:32) INFO:    [Backend]:          Frontend Ready
(12:42:32) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(12:42:32) INFO:    [Backend]:          Checking for new Heroic Updates
(12:42:32) INFO:    [Backend]:          Checking for current version changelog
(12:42:34) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine
(12:42:34) INFO:    [Winetricks]:       Downloading Winetricks
(12:42:35) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for SimCity 3000 Unlimited
(12:42:35) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for SimCity 3000 Unlimited
(12:42:35) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for SimCity 3000 Unlimited
(12:42:35) INFO:    [ExtraGameInfo]:    Getting GamesDB data for SimCity 3000 Unlimited
(12:42:35) INFO:    [ExtraGameInfo]:    Getting AppleGamingWiki data for SimCity 3000 Unlimited
(12:42:35) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
(12:42:35) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for SimCity 3000 Unlimited
(12:42:35) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for SimCity 3000 Unlimited
(12:42:35) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for SimCity 3000 Unlimited
(12:42:35) INFO:    [ExtraGameInfo]:    Getting GamesDB data for SimCity 3000 Unlimited
(12:42:35) INFO:    [ExtraGameInfo]:    Getting AppleGamingWiki data for SimCity 3000 Unlimited
(12:42:35) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
(12:42:35) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
(12:42:36) INFO:    [WineDownloader]:   Updating wine versions info
(12:42:36) INFO:    [WineDownloader]:   Fetching upstream information...
(12:42:37) INFO:    [Backend]:          Starting the Download Queue
(12:42:37) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
(12:42:37) DEBUG:   [Backend]:          {"free":355843276800,"diskSize":994662584320,"message":"331.4 GiB / 926.35 GiB","validPath":true,"validFlatpakPath":true}
(12:42:37) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine
(12:42:37) INFO:    [WineDownloader]:   wine versions updated
(12:42:42) INFO:    [Gog]:              Getting GOG library
(12:42:42) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
(12:42:42) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" info 2086050016 --os windows
(12:42:42) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" info 2086050016 --os windows
(12:42:42) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" info 2086050016 --os windows
(12:42:43) INFO:    [Gog]:              Saved username to config file
(12:42:46) INFO:    [Backend]:          
System Information:
CPU: 10x Apple M1 Max
Memory: 68.72 GB (used: 26.35 GB)
GPUs:

OS:  14.2.0 (darwin)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.13.0 Dorry & Broggy
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.0
  Nile: 1.0.1 Jonathan Joestar

(12:42:48) INFO:    [Gog]:              Saved games data
(12:42:48) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
(12:42:48) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(12:42:48) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
(12:42:48) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
(12:42:48) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(12:42:48) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(12:42:48) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(12:42:48) ERROR:   [Frontend]:         Cannot get game info
(12:42:48) ERROR:   [Frontend]:         Cannot get game info
(12:42:48) ERROR:   [Frontend]:         Cannot get game info
(12:42:53) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" info 2086050016 --os windows
(12:42:53) INFO:    [Gog]:              Found 0 game(s) to update
(12:42:53) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" info 2086050016 --os windows
(12:42:53) ERROR:   [Frontend]:         Cannot get game info
(12:42:53) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
(12:42:53) ERROR:   [Frontend]:         Cannot get game info
(12:42:53) ERROR:   [Frontend]:         Cannot get game info
(12:42:53) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
(12:42:53) ERROR:   [Frontend]:         Cannot get game info
(12:42:53) ERROR:   [Frontend]:         Cannot get game info
(12:42:53) ERROR:   [Frontend]:         Cannot get game info
(12:42:53) ERROR:   [Frontend]:         Cannot get game info
(12:42:57) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" info 2086050016 --os windows
(12:42:57) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" info 2086050016 --os windows
(12:42:58) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(12:42:58) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(12:42:58) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(12:42:58) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(12:42:58) ERROR:   [Frontend]:         Cannot get game info
(12:42:58) ERROR:   [Frontend]:         Cannot get game info
(12:42:58) ERROR:   [Frontend]:         Cannot get game info
(12:42:58) ERROR:   [Frontend]:         Cannot get game info
(12:42:58) ERROR:   [Frontend]:         Cannot get game info


-----

[2/18/2024, 12:42:31 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" --version
[2/18/2024, 12:42:31 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
[2/18/2024, 12:42:31 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
[2/18/2024, 12:42:32 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
[2/18/2024, 12:42:35 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
[2/18/2024, 12:42:35 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
[2/18/2024, 12:42:35 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
[2/18/2024, 12:42:37 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
1.0.0
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1708258348.056471}
[2/18/2024, 12:42:42 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
[2/18/2024, 12:42:42 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" info 2086050016 --os windows
[2/18/2024, 12:42:42 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" info 2086050016 --os windows
[2/18/2024, 12:42:42 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" info 2086050016 --os windows
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1708258348.056471}
[2/18/2024, 12:42:48 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
[GENERIC DOWNLOAD_MANAGER] INFO: Depot version: 2
[V2] INFO: Initialized V2 Download Manager
[2/18/2024, 12:42:48 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
[2/18/2024, 12:42:48 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
[API] INFO: Getting Dependencies repository
Traceback (most recent call last):
  File "gogdl/cli.py", line 67, in <module>
  File "gogdl/cli.py", line 62, in main
  File "gogdl/dl/managers/manager.py", line 58, in calculate_download_size
  File "gogdl/dl/managers/v2.py", line 67, in get_download_size
KeyError: '*'
[5349] Failed to execute script 'cli' due to unhandled exception!
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1708258348.056471}
[2/18/2024, 12:42:53 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" info 2086050016 --os windows
[2/18/2024, 12:42:53 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" info 2086050016 --os windows
[2/18/2024, 12:42:53 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
[2/18/2024, 12:42:53 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" auth
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1708258348.056471}
[2/18/2024, 12:42:57 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" info 2086050016 --os windows
[2/18/2024, 12:42:57 PM] GOGDL_CONFIG_PATH="/Users/lukehaas/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/lukehaas/Library/Application Support/heroic/gog_store/auth.json" info 2086050016 --os windows
[GENERIC DOWNLOAD_MANAGER] INFO: Depot version: 2
[V2] INFO: Initialized V2 Download Manager
[API] INFO: Getting Dependencies repository
Traceback (most recent call last):
  File "gogdl/cli.py", line 67, in <module>
  File "gogdl/cli.py", line 62, in main
  File "gogdl/dl/managers/manager.py", line 58, in calculate_download_size
  File "gogdl/dl/managers/v2.py", line 67, in get_download_size
KeyError: '*'
[5496] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Go to Library
2. Click on Install (game)

### Expected behavior

Expected game to install without issues.

### Screenshots

![Screenshot 2024-02-18 at 12 42 55](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/741344/d72e9ca0-46a8-4a29-83ed-7170445cf3c1)

### Heroic Version

Latest Stable

### System Information

- OS: macOS 14.2

**Comment by imLinguin** [comment]
Same issue as #3572
