### ISSUE TITLE
Superhot

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Heroic-Games-Launcher/HeroicGamesLauncher#3586]
### Describe the bug

I try doing the exe path but it doesn't launch. Just loads with yellow x for a bit and then green arrow. I've tried SH.exe but that didn't work. I tried SH.app also

### Add logs

```text
(01:22:51) INFO:    [Legendary]:        Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(01:22:51) INFO:    [Gog]:              GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(01:22:51) INFO:    [Connection]:       Connectivity: check-online
(01:22:51) INFO:    [Connection]:       Pinging external endpoints
(01:22:51) INFO:    [Gog]:              Checking for existing gog manifests
(01:22:51) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(01:22:51) WARNING: [Backend]:          Protocol already registered.
(01:22:51) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/********/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(01:22:51) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" --version
(01:22:51) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="/Users/********/Library/Application Support/heroic/nile_config" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/nile --version
(01:22:51) INFO:    [Connection]:       Connectivity: online
(01:22:51) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" auth
(01:22:51) INFO:    [Gog]:              Checking if login is valid
(01:22:51) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" auth
(01:22:51) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(01:22:51) INFO:    [Frontend]:         Refreshing undefined Library
(01:22:51) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(01:22:51) INFO:    [Legendary]:        Refreshing library...
(01:22:51) INFO:    [Legendary]:        Refreshing Epic Games...
(01:22:51) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" auth
(01:22:51) INFO:    [Backend]:          Frontend Ready
(01:22:51) INFO:    [Backend]:          Checking for new Heroic Updates
(01:22:51) INFO:    [Backend]:          Checking for current version changelog
(01:22:52) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/********/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
(01:22:53) INFO:    [Backend]:          Launching SUPERHOT (1456141688)
(01:22:53) INFO:    [Backend]:          Preventing display from sleep
(01:22:53) INFO:    [Backend]:          Preventing machine to sleep
(01:22:53) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/********/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(01:22:53) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" --version
(01:22:53) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="/Users/********/Library/Application Support/heroic/nile_config" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/nile --version
(01:22:53) INFO:    [Backend]:          Started Discord Rich Presence
(01:22:53) INFO:    [Gog]:              Launching SUPERHOT: MTL_HUD_ENABLED=1 HEROIC_APP_NAME=1456141688 HEROIC_APP_RUNNER=gog HEROIC_APP_SOURCE=gog LD_PRELOAD= GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" launch "/Volumes/T7 Shield JW Gaming/Games/Heroic/SUPERHOT.app" --override-exe "/Volumes/T7 Shield JW Gaming/Games/Heroic/SUPERHOT.app/Contents/MacOS/SUPERHOT.app" 1456141688 --platform osx
(01:22:53) INFO:    [Backend]:          Stopping Power Saver Blocker
(01:22:54) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine
(01:22:54) INFO:    [Winetricks]:       Downloading Winetricks
(01:22:56) INFO:    [WineDownloader]:   Updating wine versions info
(01:22:56) INFO:    [WineDownloader]:   Fetching upstream information...
(01:22:56) INFO:    [Backend]:          Starting the Download Queue
(01:22:57) INFO:    [WineDownloader]:   wine versions updated
(01:23:00) INFO:    [Gog]:              Getting GOG library
(01:23:00) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" auth
(01:23:00) INFO:    [Gog]:              Saved username to config file
(01:23:02) INFO:    [Backend]:          Stopped Discord Rich Presence
(01:23:02) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(01:23:03) INFO:    [Backend]:          
System Information:
CPU: 10x Apple M1 Pro
Memory: 17.18 GB (used: 7.29 GB)
GPUs:

OS:  12.7.3 (darwin)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.13.0 Dorry & Broggy
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.0
  Nile: 1.0.1 Jonathan Joestar

(01:23:05) INFO:    [Legendary]:        Game list updated, got 3 games & DLCs
(01:23:06) INFO:    [Gog]:              Saved games data
(01:23:06) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(01:23:06) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" auth
(01:23:09) INFO:    [Gog]:              Found 0 game(s) to update
(01:23:09) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH="/Users/********/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
(01:23:15) WARNING: [Legendary]:        Failed to parse games from /Users/********/Library/Application Support/heroic/legendaryConfig/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/Users/********/Library/Application Support/heroic/legendaryConfig/legendary/installed.json'
    at Object.openSync (node:fs:603:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:2131)
    at Object.readFileSync (node:fs:471:35)
    at Object.readFileSync (node:electron/js2c/asar_bundle:2:9462)
    at Module.listUpdateableGames (/Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.ac42ed07.js:112:5070)
    at async /Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.ac42ed07.js:231:3633
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:88992)
(01:23:15) INFO:    [Legendary]:        Found 0 games to update
(01:24:02) INFO:    [Backend]:          1456141688: Setting targetExe to ""
(01:24:07) INFO:    [Backend]:          1456141688: Setting targetExe to "SH.exe"
(01:24:08) INFO:    [Backend]:          Launching SUPERHOT (1456141688)
(01:24:08) INFO:    [Backend]:          Preventing display from sleep
(01:24:08) INFO:    [Backend]:          Started Discord Rich Presence
(01:24:08) INFO:    [Gog]:              Launching SUPERHOT: MTL_HUD_ENABLED=1 HEROIC_APP_NAME=1456141688 HEROIC_APP_RUNNER=gog HEROIC_APP_SOURCE=gog LD_PRELOAD= GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" launch "/Volumes/T7 Shield JW Gaming/Games/Heroic/SUPERHOT.app" --override-exe SH.exe 1456141688 --platform osx
(01:24:08) INFO:    [Backend]:          Stopping Power Saver Blocker
(01:24:52) INFO:    [Gog]:              Abort command "MTL_HUD_ENABLED=1 HEROIC_APP_NAME=1456141688 HEROIC_APP_RUNNER=gog HEROIC_APP_SOURCE=gog LD_PRELOAD= GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" launch "/Volumes/T7 Shield JW Gaming/Games/Heroic/SUPERHOT.app" --override-exe SH.exe 1456141688 --platform osx"
(01:24:52) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(01:24:52) INFO:    [Frontend]:         Refreshing gog Library
(01:24:52) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" auth
(01:24:55) INFO:    [Gog]:              Getting GOG library
(01:24:55) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" auth
(01:24:58) INFO:    [Gog]:              Saved games data
(01:25:01) INFO:    [Backend]:          1456141688: Setting targetExe to "SH.app"
(01:25:02) INFO:    [Backend]:          Launching SUPERHOT (1456141688)
(01:25:02) INFO:    [Backend]:          Started Discord Rich Presence
(01:25:02) INFO:    [Gog]:              Launching SUPERHOT: MTL_HUD_ENABLED=1 HEROIC_APP_NAME=1456141688 HEROIC_APP_RUNNER=gog HEROIC_APP_SOURCE=gog LD_PRELOAD= GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" launch "/Volumes/T7 Shield JW Gaming/Games/Heroic/SUPERHOT.app" --override-exe SH.app 1456141688 --platform osx
(01:25:02) INFO:    [Backend]:          Stopping Power Saver Blocker
(01:25:41) INFO:    [Gog]:              Abort command "MTL_HUD_ENABLED=1 HEROIC_APP_NAME=1456141688 HEROIC_APP_RUNNER=gog HEROIC_APP_SOURCE=gog LD_PRELOAD= GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" launch "/Volumes/T7 Shield JW Gaming/Games/Heroic/SUPERHOT.app" --override-exe SH.app 1456141688 --platform osx"
(01:25:41) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(01:25:41) INFO:    [Frontend]:         Refreshing gog Library
(01:25:41) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" auth
(01:25:44) INFO:    [Gog]:              Getting GOG library
(01:25:44) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" auth
(01:25:46) INFO:    [Backend]:          1456141688: Setting targetExe to ""
(01:25:48) INFO:    [Gog]:              Saved games data
(01:25:52) INFO:    [Backend]:          1456141688: Setting targetExe to "/Volumes/T7 Shield JW Gaming/Games/Heroic/SUPERHOT.app/Contents/MacOS/SUPERHOT.app"
(01:25:55) INFO:    [Backend]:          Launching SUPERHOT (1456141688)
(01:25:55) INFO:    [Backend]:          Started Discord Rich Presence
(01:25:55) INFO:    [Gog]:              Launching SUPERHOT: MTL_HUD_ENABLED=1 HEROIC_APP_NAME=1456141688 HEROIC_APP_RUNNER=gog HEROIC_APP_SOURCE=gog LD_PRELOAD= GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" launch "/Volumes/T7 Shield JW Gaming/Games/Heroic/SUPERHOT.app" --override-exe "/Volumes/T7 Shield JW Gaming/Games/Heroic/SUPERHOT.app/Contents/MacOS/SUPERHOT.app" 1456141688 --platform osx
(01:25:55) INFO:    [Backend]:          Stopping Power Saver Blocker
(01:25:57) INFO:    [Backend]:          Stopped Discord Rich Presence
(01:25:57) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(01:25:57) INFO:    [Frontend]:         Refreshing gog Library
(01:25:57) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" auth
(01:26:00) INFO:    [Gog]:              Getting GOG library
(01:26:00) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/********/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/********/Library/Application Support/heroic/gog_store/auth.json" auth
(01:26:00) INFO:    [Backend]:          1456141688: Setting targetExe to ""
(01:26:03) INFO:    [Gog]:              Saved games data
```

### Steps to reproduce

1. Go to settings
2. Click on `Select an alternative EXE to run`
3. type in file path
4. No load

### Expected behavior

expect for the game to load with workaround

### Heroic Version

Latest Stable

### System Information

- OS :macOS

**Comment by Aces-and-Jacks** [comment]
Figured it out. Luckily I've had a similar issue somewhere else. I just had to open the app contents multiple times and direct to the executable
