### ISSUE TITLE
SHA512 checksum of the AppImage build of 2.13.0 does not match

### ISSUE THREAD

**Issue by koniiiik** [Heroic-Games-Launcher/HeroicGamesLauncher#3612]
### Describe the bug

The expected checksum of the AppImage build listed in latest-linux.yml is `fePyWySEBOLDfxIqJwNaAmVdunJDfWpYBn3BmVul2NS3bMaIXKZ2vvtgP/tFF8d43ZO3QkLDFNRwwSGwqC7Y7w==` (or `7de3f25b248404e2c37f122a27035a02655dba72437d6a58067dc1995ba5d8d4b76cc6885ca676befb603ffb4517c778dd93b74242c314d470c121b0a82ed8ef` in hex), whereas the binary in the release has a checksum of `YEpmRCon8kBHRY6IXRz7LnO4RNdu28ynsfWomiORElFUsnlLUK/8bVx68CRVbnSyM+4R4ysiHZUr2imzadN0Lg==` (or `604a66442a27f24047458e885d1cfb2e73b844d76edbcca7b1f5a89a2391125154b2794b50affc6d5c7af024556e74b233ee11e32b221d952bda29b369d3742e` in hex).

This prevents autoupdate from working, for example.

### Add logs

```text
(16:22:10) INFO:    [Legendary]:        Legendary location: /tmp/.mount_Heroic21k0BG/resources/app.asar.unpacked/build/bin/linux/legendary
(16:22:10) INFO:    [Gog]:              GOGDL location: /tmp/.mount_Heroic21k0BG/resources/app.asar.unpacked/build/bin/linux/gogdl
(16:22:10) INFO:    [Connection]:       Connectivity: check-online
(16:22:10) INFO:    [Connection]:       Pinging external endpoints
(16:22:10) INFO:    [Backend]:          DRM module staus {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2710.0'
  }
}
Checking for update
(16:22:10) WARNING: [Backend]:          Failed to register protocol with OS.
[2407059:0303/162210.951920:ERROR:browser_main_loop.cc(275)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2407059:0303/162210.951959:ERROR:browser_main_loop.cc(275)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2407059:0303/162210.951985:ERROR:browser_main_loop.cc(275)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(16:22:11) INFO:    [Connection]:       Connectivity: online
(16:22:11) INFO:    [Gog]:              Checking if login is valid
(16:22:11) INFO:    [Gog]:              Running command: /tmp/.mount_Heroic21k0BG/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/koniiiik/.config/heroic/gog_store/auth.json auth
(16:22:11) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/koniiiik/.config/heroic/legendaryConfig/legendary /tmp/.mount_Heroic21k0BG/resources/app.asar.unpacked/build/bin/linux/legendary --version
(16:22:11) INFO:    [Gog]:              Running command: /tmp/.mount_Heroic21k0BG/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/koniiiik/.config/heroic/gog_store/auth.json --version
(16:22:11) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/koniiiik/.config/heroic/nile_config /tmp/.mount_Heroic21k0BG/resources/app.asar.unpacked/build/bin/linux/nile --version
(16:22:11) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(16:22:11) INFO:    [Backend]:          
System Information:
CPU: 32x AMD Ryzen 9 5950X 16-Core Processor
Memory: 67.32 GB (used: 15.66 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Speedster MERC 319 AMD Radeon RX 6900 XT Black
    IDs: D=73bf V=1002 SD=6901 SV=1eae
    Driver: amdgpu
OS: Gentoo 6.6.13-gentoo-dist (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.12.1 Vegapunk
  Legendary: 0.20.34 Direct Intervention
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(16:22:11) INFO:    [Frontend]:         Refreshing undefined Library
(16:22:11) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(16:22:11) INFO:    [Gog]:              Running command: /tmp/.mount_Heroic21k0BG/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/koniiiik/.config/heroic/gog_store/auth.json auth
(16:22:11) INFO:    [Legendary]:        Refreshing library...
(16:22:11) INFO:    [Legendary]:        Refreshing Epic Games...
(16:22:11) INFO:    [Legendary]:        Game list updated, got 248 games & DLCs
(16:22:11) INFO:    [Backend]:          Frontend Ready
(16:22:11) INFO:    [Gog]:              Getting GOG library
(16:22:11) INFO:    [Gog]:              Running command: /tmp/.mount_Heroic21k0BG/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/koniiiik/.config/heroic/gog_store/auth.json auth
(16:22:11) INFO:    [Backend]:          Checking for new Heroic Updates
(16:22:11) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/koniiiik/.config/heroic/legendaryConfig/legendary /tmp/.mount_Heroic21k0BG/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(16:22:12) INFO:    [Gog]:              Saved username to config file
(16:22:12) INFO:    [Gog]:              Saved games data
(16:22:12) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(16:22:12) INFO:    [Gog]:              Found 0 game(s) to update
(16:22:12) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/koniiiik/.config/heroic/legendaryConfig/legendary /tmp/.mount_Heroic21k0BG/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(16:22:13) INFO:    [Winetricks]:       Downloading Winetricks
Found version 2.13.0 (url: Heroic-2.13.0.AppImage, heroic_2.13.0_amd64.deb, heroic-2.13.0.x86_64.rpm)
(16:22:13) INFO:    [Legendary]:        Found 0 games to update
(16:22:13) INFO:    [Frontend]:         Force Update
(16:22:15) INFO:    [WineDownloader]:   Updating wine versions info
(16:22:15) INFO:    [WineDownloader]:   Fetching upstream information...
Downloading update from Heroic-2.13.0.AppImage, heroic_2.13.0_amd64.deb, heroic-2.13.0.x86_64.rpm
updater cache dir: /home/koniiiik/.cache/heroic-updater
(16:22:16) INFO:    [Backend]:          Starting the Download Queue
(16:22:17) INFO:    [WineDownloader]:   wine versions updated
Cannot download differentially, fallback to full download: Error: Received data length 13350 is not equal to expected 160658
    at FileWithEmbeddedBlockMapDifferentialDownloader.readRemoteBytes (/tmp/.mount_Heroic21k0BG/resources/app.asar/node_modules/electron-updater/out/differentialDownloader/DifferentialDownloader.js:234:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FileWithEmbeddedBlockMapDifferentialDownloader.download (/tmp/.mount_Heroic21k0BG/resources/app.asar/node_modules/electron-updater/out/differentialDownloader/FileWithEmbeddedBlockMapDifferentialDownloader.js:12:35)
    at async Object.task (/tmp/.mount_Heroic21k0BG/resources/app.asar/node_modules/electron-updater/out/AppImageUpdater.js:56:21)
    at async AppImageUpdater.executeDownload (/tmp/.mount_Heroic21k0BG/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:524:13)
Error: Error: sha512 checksum mismatch, expected fePyWySEBOLDfxIqJwNaAmVdunJDfWpYBn3BmVul2NS3bMaIXKZ2vvtgP/tFF8d43ZO3QkLDFNRwwSGwqC7Y7w==, got YEpmRCon8kBHRY6IXRz7LnO4RNdu28ynsfWomiORElFUsnlLUK/8bVx68CRVbnSyM+4R4ysiHZUr2imzadN0Lg==
    at Object.newError (/tmp/.mount_Heroic21k0BG/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:47:19)
    at DigestTransform.validate (/tmp/.mount_Heroic21k0BG/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:352:27)
    at DigestTransform._flush (/tmp/.mount_Heroic21k0BG/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:338:22)
    at DigestTransform.final [as _final] (node:internal/streams/transform:132:10)
    at callFinal (node:internal/streams/writable:698:12)
    at prefinish (node:internal/streams/writable:710:7)
    at finishMaybe (node:internal/streams/writable:720:5)
    at DigestTransform.end (node:internal/streams/writable:634:5)
    at IncomingMessage.onend (node:internal/streams/readable:705:10)
    at Object.onceWrapper (node:events:628:28)
(16:22:25) ERROR:   [Backend]:          failed to update Error: sha512 checksum mismatch, expected fePyWySEBOLDfxIqJwNaAmVdunJDfWpYBn3BmVul2NS3bMaIXKZ2vvtgP/tFF8d43ZO3QkLDFNRwwSGwqC7Y7w==, got YEpmRCon8kBHRY6IXRz7LnO4RNdu28ynsfWomiORElFUsnlLUK/8bVx68CRVbnSyM+4R4ysiHZUr2imzadN0Lg==
    at Object.newError (/tmp/.mount_Heroic21k0BG/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:47:19)
    at DigestTransform.validate (/tmp/.mount_Heroic21k0BG/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:352:27)
    at DigestTransform._flush (/tmp/.mount_Heroic21k0BG/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:338:22)
    at DigestTransform.final [as _final] (node:internal/streams/transform:132:10)
    at callFinal (node:internal/streams/writable:698:12)
    at prefinish (node:internal/streams/writable:710:7)
    at finishMaybe (node:internal/streams/writable:720:5)
    at DigestTransform.end (node:internal/streams/writable:634:5)
    at IncomingMessage.onend (node:internal/streams/readable:705:10)
    at Object.onceWrapper (node:events:628:28) {
  code: 'ERR_CHECKSUM_MISMATCH'
}
(node:2407059) UnhandledPromiseRejectionWarning: Error: sha512 checksum mismatch, expected fePyWySEBOLDfxIqJwNaAmVdunJDfWpYBn3BmVul2NS3bMaIXKZ2vvtgP/tFF8d43ZO3QkLDFNRwwSGwqC7Y7w==, got YEpmRCon8kBHRY6IXRz7LnO4RNdu28ynsfWomiORElFUsnlLUK/8bVx68CRVbnSyM+4R4ysiHZUr2imzadN0Lg==
    at Object.newError (/tmp/.mount_Heroic21k0BG/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:47:19)
    at DigestTransform.validate (/tmp/.mount_Heroic21k0BG/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:352:27)
    at DigestTransform._flush (/tmp/.mount_Heroic21k0BG/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:338:22)
    at DigestTransform.final [as _final] (node:internal/streams/transform:132:10)
    at callFinal (node:internal/streams/writable:698:12)
    at prefinish (node:internal/streams/writable:710:7)
    at finishMaybe (node:internal/streams/writable:720:5)
    at DigestTransform.end (node:internal/streams/writable:634:5)
    at IncomingMessage.onend (node:internal/streams/readable:705:10)
    at Object.onceWrapper (node:events:628:28)
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:2407059) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

### Steps to reproduce

Two possibilities:
- launch an older version of Heroic, get prompt about an update
- confirm update
- get an error message “Something went wrong with the update, please check the logs or try again later!”

Another option:
- `wget 'https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.13.0/Heroic-2.13.0.AppImage' 'https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.13.0/latest-linux.yml'`
- calculate the base64-encoded hash of `Heroic-2.13.0.AppImage` with `python3 -c 'import binascii, pathlib, hashlib; print(binascii.b2a_base64(hashlib.file_digest(pathlib.Path("Heroic-2.13.0.AppImage").open("rb"), "sha512").digest()).decode())'`
- compare the output to the hash in `latest-linux.yml`

### Expected behavior

Autoupdate should work. Also, the hash of the file should match the one listed in the checksum file.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Gentoo (not that this has any impact)

### Additional information

I have tried to raise this on discord, but have not received any responses: https://discord.com/channels/812703221789097985/1206581385297399948/1206581385297399948

**Comment by arielj** [comment]
closing as this refers to an old version

feel free to comment if the issue still happens in the latest 2.15.0 release and we can reopen this
