### ISSUE TITLE
Heroic Launcher has issues with RimWorld Linux

### ISSUE THREAD

**Issue by Aldran** [Heroic-Games-Launcher/HeroicGamesLauncher#3631]
### Describe the bug

Unable to access RimWorld's game profile or install it if it is the Linux version. This is through GoG. Windows version seems to behave normally. If I try to install the game, it is unable to calculate the game size. If I access the game profile, it loads for a few seconds and the errors out with "Cannot get game info". Based on the log both these issues are caused by the launcher not being able to calculate the game size. Log provided in this report.
Refreshing the library, cleaning the cache, and resetting heroic did not work. Importing the game does allow it to run, but the game profile still errors out. 

### Add logs

```text
[3/15/2024, 11:30:40 AM] GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
1.0.0
[3/15/2024, 11:30:41 AM] GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
[3/15/2024, 11:30:41 AM] GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1710516391.4828236}
[3/15/2024, 11:30:48 AM] GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
[3/15/2024, 11:30:48 AM] GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
[3/15/2024, 11:30:48 AM] GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1710516391.4828236}
[3/15/2024, 11:30:48 AM] GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1094900565 --os linux
[3/15/2024, 11:30:48 AM] GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1094900565 --os linux
[GENERIC DOWNLOAD_MANAGER] INFO: Platform is Linux, redirecting download to Linux Native installer manager
[LINUX] INFO: Initialized Linux Download Manager
[API] INFO: Getting info from products endpoint for id: 1094900565
Traceback (most recent call last):
  File "gogdl/cli.py", line 67, in <module>
  File "gogdl/cli.py", line 62, in main
  File "gogdl/dl/managers/manager.py", line 58, in calculate_download_size
  File "gogdl/dl/managers/linux.py", line 158, in get_download_size
  File "gogdl/dl/managers/linux.py", line 135, in calculate_download_sizes
AttributeError: 'InstallerHandler' object has no attribute 'central_directory'
[171] Failed to execute script 'cli' due to unhandled exception!
[3/15/2024, 11:31:18 AM] GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
1.0.0
```

### Steps to reproduce

1. Go to Library
2. Click on RimWorld (switch to Linux version if using Windows)
3. Wait for a few seconds

### Expected behavior

Game should install like other Linux games on GoG. Game profile should launch and display the usual info without breaking with a "Cannot get game info" error.

### Heroic Version

Latest Stable (Flatpak)

### System Information

- SteamOS on the latest stable version

**Comment by imLinguin** [comment]
Same issue as #3607 
will be resolved in future release, in the meantime you can get latest gogdl build to workaround the issue

**Comment by nyabinary** [comment]
> Same issue as #3607 will be resolved in future release, in the meantime you can get latest gogdl build to workaround the issue

2.14.1 and same issue still.
