### ISSUE TITLE
Cant download stardew valley: "💔 Cannot get game info"

### ISSUE THREAD

**Issue by ValonInc** [Heroic-Games-Launcher/HeroicGamesLauncher#3640]
### Describe the bug

I cant open the page for Stardew valley (Gog).
shortly after clicking on it, it says "Cannot get game info". neiter clearing my heroic cache or resetting heroic fixed it.

### Add logs

```text
==================
===== Heroic =====
==================
(21:25:13) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(21:25:13) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(21:25:13) INFO:    [Connection]:       Connectivity: check-online
(21:25:13) INFO:    [Connection]:       Pinging external endpoints
(21:25:13) INFO:    [Gog]:              Checking for existing gog manifests
(21:25:13) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(21:25:13) WARNING: [Backend]:          Protocol already registered.
(21:25:13) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/valon/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(21:25:13) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json --version
(21:25:13) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/valon/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(21:25:13) INFO:    [Backend]:          
System Information:
CPU: 32x AMD Ryzen 9 7950X3D 16-Core Processor
Memory: 32.71 GB (used: 3.67 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Raphael
    IDs: D=164e V=1002 SD=164e SV=1002
    Driver: amdgpu
  GPU 1:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M]
    IDs: D=744c V=1002 SD=5304 SV=1849
    Driver: amdgpu
OS: Ubuntu 23.10 (Mantic Minotaur) (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.13.0 Dorry & Broggy
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.0
  Nile: 1.0.1 Jonathan Joestar

(21:25:14) INFO:    [Connection]:       Connectivity: online
(21:25:14) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
(21:25:14) INFO:    [Gog]:              Checking if login is valid
(21:25:14) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
(21:25:14) INFO:    [Frontend]:         Refreshing undefined Library
(21:25:14) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(21:25:14) INFO:    [Legendary]:        Refreshing library...
(21:25:14) INFO:    [Legendary]:        Refreshing Epic Games...
(21:25:14) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
(21:25:14) INFO:    [Backend]:          Frontend Ready
(21:25:14) INFO:    [Backend]:          Checking for new Heroic Updates
(21:25:14) INFO:    [Backend]:          Checking for current version changelog
(21:25:14) INFO:    [Frontend]:         Updated to a new version, cleaaning up the cache.
(21:25:14) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/valon/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary cleanup
(21:25:14) INFO:    [Gog]:              Getting GOG library
(21:25:14) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
(21:25:14) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/valon/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(21:25:14) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(21:25:14) INFO:    [Gog]:              Saved username to config file
(21:25:15) INFO:    [Gog]:              Saved games data
(21:25:16) INFO:    [Winetricks]:       Downloading Winetricks
(21:25:17) INFO:    [Legendary]:        Game list updated, got 225 games & DLCs
(21:25:17) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(21:25:17) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
(21:25:18) INFO:    [Gog]:              Found 1 game(s) to update
(21:25:18) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/valon/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(21:25:18) INFO:    [WineDownloader]:   Updating wine versions info
(21:25:18) INFO:    [WineDownloader]:   Fetching upstream information...
(21:25:19) INFO:    [Backend]:          Starting the Download Queue
(21:25:20) INFO:    [WineDownloader]:   wine versions updated
(21:25:21) INFO:    [Legendary]:        Found 0 games to update
(21:25:29) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Stardew Valley
(21:25:29) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Stardew Valley
(21:25:29) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Stardew Valley
(21:25:29) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Stardew Valley
(21:25:29) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
(21:25:29) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Stardew Valley
(21:25:29) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Stardew Valley
(21:25:29) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Stardew Valley
(21:25:29) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Stardew Valley
(21:25:29) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
(21:25:29) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
(21:25:29) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json info 1453375253 --os linux
(21:25:29) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json info 1453375253 --os linux
(21:25:30) DEBUG:   [Backend]:          ProtonDB data for 413150 {"bestReportedTier":"platinum","confidence":"strong","score":0.9,"tier":"platinum","total":109,"trendingTier":"platinum"}
(21:25:30) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:25:30) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(21:25:30) ERROR:   [Frontend]:         Cannot get game info
(21:25:30) ERROR:   [Frontend]:         Cannot get game info
(21:25:30) ERROR:   [Frontend]:         Cannot get game info
(21:25:30) DEBUG:   [Backend]:          SteamDeck data for 413150 {"success":1,"results":{"appid":413150,"resolved_category":3,"resolved_items":[{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultControllerConfigFullyFunctional"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_ControllerGlyphsMatchDeckDevice"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_InterfaceTextIsLegible"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultConfigurationIsPerformant"}],"steam_deck_blog_url":"","search_id":null}}
(21:25:30) ERROR:   [Frontend]:         Cannot get game info
(21:25:30) DEBUG:   [Backend]:          ProtonDB data for 413150 {"bestReportedTier":"platinum","confidence":"strong","score":0.9,"tier":"platinum","total":109,"trendingTier":"platinum"}
(21:25:31) DEBUG:   [Backend]:          SteamDeck data for 413150 {"success":1,"results":{"appid":413150,"resolved_category":3,"resolved_items":[{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultControllerConfigFullyFunctional"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_ControllerGlyphsMatchDeckDevice"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_InterfaceTextIsLegible"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultConfigurationIsPerformant"}],"steam_deck_blog_url":"","search_id":null}}



===============
===== GOG =====
===============
[3/19/2024, 9:25:13 PM] GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json --version
1.0.0
[3/19/2024, 9:25:14 PM] GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
[3/19/2024, 9:25:14 PM] GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
[3/19/2024, 9:25:14 PM] GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1710878336.041933}
[3/19/2024, 9:25:14 PM] GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1710878336.041933}
[3/19/2024, 9:25:17 PM] GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1710878336.041933}
[3/19/2024, 9:25:29 PM] GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
[3/19/2024, 9:25:29 PM] GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
[3/19/2024, 9:25:29 PM] GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json auth
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1710878336.041933}
[3/19/2024, 9:25:29 PM] GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json info 1453375253 --os linux
[3/19/2024, 9:25:29 PM] GOGDL_CONFIG_PATH=/home/valon/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/valon/.config/heroic/gog_store/auth.json info 1453375253 --os linux
[GENERIC DOWNLOAD_MANAGER] INFO: Platform is Linux, redirecting download to Linux Native installer manager
[LINUX] INFO: Initialized Linux Download Manager
[API] INFO: Getting info from products endpoint for id: 1453375253
Traceback (most recent call last):
  File "gogdl/cli.py", line 67, in <module>
  File "gogdl/cli.py", line 62, in main
  File "gogdl/dl/managers/manager.py", line 58, in calculate_download_size
  File "gogdl/dl/managers/linux.py", line 154, in get_download_size
  File "gogdl/dl/managers/linux.py", line 101, in setup
TypeError: 'NoneType' object is not subscriptable
[9620] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Go to 'Library'
2. Click on 'Stardew valley'
4. See error :,(

### Expected behavior

I should the the game page and be able to download* it

### Heroic Version

Latest Stable

### System Information

- OS Ubuntu 23

### Additional information

Happends on 2.13

* this error didnt happen on 2.12 and 2.11 HOWEVER
on those version the game didnt download correctly. It downloaded instantly and gave a error when starting (this could still be happening after fixing this bug... tell me of you need the logs for this).
* neither the page bug or the download bug happens with railway empire (also throug Gog)

**Comment by arielj** [comment]
can you check if this works for you too? https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3635#issuecomment-2002540007

**Comment by ValonInc** [comment]
Sorry for my late response.

Yep, https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3635#issuecomment-2002540007 works. Thanks @arielj .
