### ISSUE TITLE
Unable to log out Epic Games to refresh session information

### ISSUE THREAD

**Issue by fluteds** [Heroic-Games-Launcher/HeroicGamesLauncher#3652]
### Describe the bug

- Users are unable to log out of Epic Games in Heroic even on a fresh install.
- Games that use the EG login/library information to load the game crash.

### Add logs

```text
(21:50:12) INFO:    [Legendary]:        Legendary location: C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(21:50:12) INFO:    [Gog]:              GOGDL location: C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(21:50:12) INFO:    [Connection]:       Connectivity: check-online
(21:50:12) INFO:    [Connection]:       Pinging external endpoints
(21:50:12) INFO:    [Gog]:              Checking for existing gog manifests
(21:50:12) INFO:    [Nile]:             Refreshing library...
(21:50:12) INFO:    [Nile]:             Refreshing Amazon Games...
(21:50:12) INFO:    [Nile]:             Game list updated, got 353 games
(21:50:12) INFO:    [Backend]:          DRM module staus {
  "neifaoindggfcjicffkgpmnlppeffabd": {
    "name": "Google Widevine Windows CDM",
    "status": "new",
    "version": "1.0.2738.0"
  },
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(21:50:12) WARNING: [Backend]:          Protocol already registered.
(21:50:12) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\nile_config powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile`"" -Wait -ArgumentList "`"library`"","`"sync`"" -NoNewWindow
(21:50:12) INFO:    [Connection]:       Connectivity: online
(21:50:12) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -ArgumentList "`"--auth-config-path`"","`"C:\Users\user\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`"" -NoNewWindow
(21:50:12) INFO:    [Gog]:              Checking if login is valid
(21:50:12) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -ArgumentList "`"--auth-config-path`"","`"C:\Users\user\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`"" -NoNewWindow
(21:50:13) INFO:    [Nile]:             Saved user data to config file
(21:50:13) INFO:    [Frontend]:         Refreshing undefined Library
(21:50:13) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(21:50:13) INFO:    [Legendary]:        Refreshing library...
(21:50:13) INFO:    [Legendary]:        Refreshing Epic Games...
(21:50:13) INFO:    [Nile]:             Refreshing library...
(21:50:13) INFO:    [Nile]:             Refreshing Amazon Games...
(21:50:13) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\nile_config powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile`"" -Wait -ArgumentList "`"library`"","`"sync`"" -NoNewWindow
(21:50:13) INFO:    [Nile]:             Game list updated, got 353 games
(21:50:13) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -ArgumentList "`"--auth-config-path`"","`"C:\Users\user\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`"" -NoNewWindow
(21:50:13) INFO:    [Backend]:          Frontend Ready
(21:50:13) INFO:    [Backend]:          Checking for new Heroic Updates
(21:50:13) INFO:    [Backend]:          Checking for current version changelog
(21:50:13) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"list`"","`"--third-party`"" -NoNewWindow
(21:50:15) INFO:    [WineDownloader]:   Updating wine versions info
(21:50:15) INFO:    [WineDownloader]:   Fetching upstream information...
(21:50:15) INFO:    [Gog]:              Getting GOG library
(21:50:15) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -ArgumentList "`"--auth-config-path`"","`"C:\Users\user\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`"" -NoNewWindow
(21:50:15) INFO:    [Gog]:              Saved username to config file
(21:50:16) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"--version`"" -NoNewWindow
(21:50:16) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -ArgumentList "`"--auth-config-path`"","`"C:\Users\user\AppData\Roaming\heroic\gog_store\auth.json`"","`"--version`"" -NoNewWindow
(21:50:16) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\nile_config powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile`"" -Wait -ArgumentList "`"--version`"" -NoNewWindow
(21:50:16) INFO:    [Backend]:          VCRuntime is installed
(21:50:16) INFO:    [WineDownloader]:   wine versions updated
(21:50:16) ERROR:   [Backend]:          Could not find default wine version
(21:50:18) INFO:    [Legendary]:        Game list updated, got 419 games & DLCs
(21:50:18) INFO:    [Backend]:          Starting the Download Queue
(21:50:18) INFO:    [Backend]:          
System Information:
CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Memory: 68.65 GB (used: 20.49 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation TU102 [GeForce RTX 2080 Ti Rev. A]
    IDs: D=1e07 V=10de SD=3711 SV=1462
    Driver: 537.13
OS: Microsoft Windows 10 Home 10.0.19045 (win32)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.13.0 Dorry & Broggy
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.0
  Nile: 1.0.1 Jonathan Joestar

(21:50:18) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -ArgumentList "`"--auth-config-path`"","`"C:\Users\user\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`"" -NoNewWindow
(21:50:21) INFO:    [Gog]:              Saved games data
(21:50:21) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(21:50:21) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -ArgumentList "`"--auth-config-path`"","`"C:\Users\user\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`"" -NoNewWindow
(21:50:23) INFO:    [Gog]:              Found 0 game(s) to update
(21:50:23) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"list`"","`"--third-party`"" -NoNewWindow
(21:50:28) INFO:    [Legendary]:        Found 0 games to update
(21:50:28) INFO:    [Nile]:             Looking for updates...
(21:50:28) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\nile_config powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile`"" -Wait -ArgumentList "`"list-updates`"","`"--json`"" -NoNewWindow
(21:50:28) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"--version`"" -NoNewWindow
(21:50:28) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -ArgumentList "`"--auth-config-path`"","`"C:\Users\user\AppData\Roaming\heroic\gog_store\auth.json`"","`"--version`"" -NoNewWindow
(21:50:28) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\nile_config powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile`"" -Wait -ArgumentList "`"--version`"" -NoNewWindow
(21:50:28) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"eos-overlay`"","`"info`"" -NoNewWindow
(21:50:30) INFO:    [Legendary]:        Updating EOS Overlay information: LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"status`"" -NoNewWindow
(21:50:31) INFO:    [Legendary]:        Abort command "LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"status`"" -NoNewWindow"
(21:50:33) INFO:    [Backend]:          Heroic: Setting experimentalFeatures to {"enableNewDesign":true,"enableHelp":false,"automaticWinetricksFixes":true} (previous value: undefined)
(21:50:38) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"cleanup`"" -NoNewWindow
(21:50:38) INFO:    [Frontend]:         Refreshing undefined Library
(21:50:38) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(21:50:38) INFO:    [Legendary]:        Refreshing library...
(21:50:38) INFO:    [Legendary]:        Refreshing Epic Games...
(21:50:38) INFO:    [Nile]:             Refreshing library...
(21:50:38) INFO:    [Nile]:             Refreshing Amazon Games...
(21:50:38) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\nile_config powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile`"" -Wait -ArgumentList "`"library`"","`"sync`"" -NoNewWindow
(21:50:38) INFO:    [Nile]:             Game list updated, got 353 games
(21:50:38) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -ArgumentList "`"--auth-config-path`"","`"C:\Users\user\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`"" -NoNewWindow
(21:50:39) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"list`"","`"--third-party`"" -NoNewWindow
(21:50:41) INFO:    [Gog]:              Getting GOG library
(21:50:41) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -ArgumentList "`"--auth-config-path`"","`"C:\Users\user\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`"" -NoNewWindow
(21:50:44) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -ArgumentList "`"--auth-config-path`"","`"C:\Users\user\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`"" -NoNewWindow
(21:50:45) INFO:    [Legendary]:        Game list updated, got 419 games & DLCs
(21:50:47) INFO:    [Gog]:              Saved games data
(21:53:28) INFO:    [Legendary]:        Logging out: LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"auth`"","`"--delete`"" -NoNewWindow
(21:53:31) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"cleanup`"" -NoNewWindow
(21:54:37) INFO:    [Frontend]:         Called Epic Login
(21:54:37) INFO:    [Legendary]:        Logging in: LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"auth`"","`"--code`"","`"REDACTEDAUTHCODEXXXX`"" -NoNewWindow
(21:54:40) INFO:    [Frontend]:         Refreshing legendary Library
(21:54:40) INFO:    [Legendary]:        Refreshing library...
(21:54:40) INFO:    [Legendary]:        Refreshing Epic Games...
(21:54:40) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"list`"","`"--third-party`"" -NoNewWindow
(21:54:45) INFO:    [Legendary]:        Game list updated, got 419 games & DLCs
(21:54:46) INFO:    [Frontend]:         No cache found, getting data from legendary...
(21:54:46) INFO:    [Legendary]:        Refreshing library...
(21:54:46) INFO:    [Legendary]:        Refreshing Epic Games...
(21:54:46) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"list`"","`"--third-party`"" -NoNewWindow
(21:54:50) INFO:    [Legendary]:        Game list updated, got 419 games & DLCs
(21:54:50) INFO:    [Frontend]:         Force Update

################################
## EPIC GAMES / LEGENDARY LOG ##
################################

[27/03/2024, 21:59:59] LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"list`"","`"--third-party`"" -NoNewWindow

[27/03/2024, 22:00:01] LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"--version`"" -NoNewWindow

[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Getting game list... (this may take a while)

Traceback (most recent call last):

  File "legendary\cli.py", line 3149, in <module>

  File "legendary\cli.py", line 3060, in main

  File "legendary\cli.py", line 207, in list_games

  File "legendary\core.py", line 529, in get_non_asset_library_items

KeyError: 'appName'

[11124] Failed to execute script 'cli' due to unhandled exception!

legendary version "0.20.34", codename "Direct Intervention"

[27/03/2024, 22:00:09] LEGENDARY_CONFIG_PATH=C:\Users\user\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\user\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -ArgumentList "`"list`"","`"--third-party`"" -NoNewWindow

[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Getting game list... (this may take a while)

Traceback (most recent call last):

  File "legendary\cli.py", line 3149, in <module>

  File "legendary\cli.py", line 3060, in main

  File "legendary\cli.py", line 207, in list_games

  File "legendary\core.py", line 529, in get_non_asset_library_items

KeyError: 'appName'

[21632] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Open Heroic
2. Log into or try to log out of Epic Games or open Heroic and wait
3. Observe the error message pop up

### Expected behavior

I expect no errors when I open Heroic and the game to launch without any issues.
Signing in and out should be smooth and able to work.

### Screenshots

![Heroic_6JmDsM2w0X](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/34608301/296c7aa1-e76d-435f-aa94-b479ed40da81)
Error Message after attempting to log out of Epic Games to refresh the login data.

![Heroic_2iNusyIPph](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/34608301/48e95f62-09b8-40fa-935d-4ede547b5035)
Error shown in Heroic after initially opening and/or launching a game.

### Heroic Version

Latest Stable

### System Information

- CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
- GPU: NVIDIA Corporation TU102 [GeForce RTX 2080 Ti Rev. A]
- OS: Microsoft Windows 10 Home 10.0.19045 (win32)

### Additional information

The error happened out of the blue. I cannot exactly pinpoint what it is that caused it.

- Some games will launch and load but crash whenever login information needs to be verified.
- Heroic cannot find certain files related to login information when signing out.
- This is also happening on a fresh install of Heroic.

Troubleshooting attempts.

- Clearing `.config/heroic` and  `.config/legendary` also provides the same results. 
- Both methods of logging in cause the same results.
- Using a different version of Legendary provides the same results.

**Comment by CommandMC** [comment]
This should be resolved with the Legendary binary from [derrod/legendary#649](<https://github.com/derrod/legendary/pull/649>)

**Comment by barbarbar338** [comment]
Getting the same error with BazziteOS and Heroic 2.13

**Comment by barbarbar338** [comment]
Forked the legendary repo and applied @CommandMC's fixes. If you guys need then you can build your own binaries from here: https://github.com/derrod/legendary/compare/master...barbarbar338:legendary:master

Just follow the workflow file for build instructions.

Also if you want you can download the pre-built linux bin here: https://worker.338.rocks/storage/uploads/others/legendary

**Comment by CommandMC** [comment]
@barbarbar338 Please do not link to private Legendary forks here. We do not have the time to audit these versions.

If you want to link to a repo with that change, link to [mine](<https://github.com/CommandMC/legendary/tree/fix/no-appname-skip>) instead. Binaries are also available [here](<https://github.com/derrod/legendary/actions/runs/8465207140>).
