### ISSUE TITLE
MangoHUD doesn't show up in game

### ISSUE THREAD

**Issue by Madame-Louise** [Heroic-Games-Launcher/HeroicGamesLauncher#3666]
### Describe the bug

Even though the mangohud option is enabled and the right version of mangohud is installed as a flatpak, nothing shows up in any game.  It works well on Bottles so I think it's not a MangoHud problem.

### Add logs

```text
(15:51:57) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(15:51:57) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:51:57) INFO:    [Connection]:       Connectivity: check-online
(15:51:57) INFO:    [Connection]:       Pinging external endpoints
(15:51:57) INFO:    [Gog]:              Checking for existing gog manifests
(15:51:58) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(15:51:58) WARNING: [Backend]:          Failed to register protocol with OS.
(15:51:58) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:51:58) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(15:51:58) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(15:51:58) INFO:    [Connection]:       Connectivity: online
(15:51:58) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:51:58) INFO:    [Gog]:              Checking if login is valid
(15:51:58) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:51:58) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(15:51:58) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 9 5900HX with Radeon Graphics
Memory: 16.13 GB (used: 5.65 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series]
    IDs: D=1638 V=1002 SD=186c SV=1043
    Driver: amdgpu
  GPU 1:
    Name: NVIDIA Corporation GA107M [GeForce RTX 3050 Mobile]
    IDs: D=25a2 V=10de SD=186c SV=1043
    Driver: nvidia
OS: Ubuntu 23.10 (Mantic Minotaur) (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.13.0 Dorry & Broggy
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.0
  Nile: 1.0.1 Jonathan Joestar

(15:51:58) INFO:    [Frontend]:         Refreshing undefined Library
(15:51:58) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(15:51:58) INFO:    [Legendary]:        Refreshing library...
(15:51:58) INFO:    [Legendary]:        Refreshing Epic Games...
(15:51:58) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:51:58) INFO:    [Backend]:          Frontend Ready
(15:51:58) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:51:58) INFO:    [Backend]:          Checking for current version changelog
(15:51:58) ERROR:   [Backend]:          Error when checking for current Heroic changelog
(15:51:58) INFO:    [Gog]:              Saved username to config file
(15:51:58) INFO:    [Gog]:              Getting GOG library
(15:51:58) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:51:59) INFO:    [Gog]:              Saved games data
(15:52:00) INFO:    [Legendary]:        Game list updated, got 56 games & DLCs
(15:52:00) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:52:00) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:52:00) INFO:    [Gog]:              Found 0 game(s) to update
(15:52:00) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:52:00) INFO:    [Winetricks]:       Downloading Winetricks
(15:52:01) INFO:    [Legendary]:        Found 0 games to update
(15:52:03) INFO:    [WineDownloader]:   Updating wine versions info
(15:52:03) INFO:    [WineDownloader]:   Fetching upstream information...
(15:52:03) ERROR:   [WineDownloader]:   Error: Could not fetch available releases from https://api.github.com/repos/GloriousEggroll/wine-ge-custom/releases with error:
 Error: Request failed with status code 403
    at /app/bin/heroic/resources/app.asar/build/electron/main.ac42ed07.js:118:4201
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(15:52:03) INFO:    [Backend]:          Launching DEATH STRANDING DIRECTOR'S CUT (c38f51843fdf4db0b24fc907b8d78221)
(15:52:03) INFO:    [Backend]:          Preventing display from sleep
(15:52:03) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton - Experimental
(15:52:03) INFO:    [Backend]:          Preventing machine to sleep
(15:52:03) ERROR:   [WineDownloader]:   Error: Could not fetch available releases from https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases with error:
 Error: Request failed with status code 403
    at /app/bin/heroic/resources/app.asar/build/electron/main.ac42ed07.js:118:4201
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(15:52:03) INFO:    [WineDownloader]:   wine versions updated
(15:52:03) INFO:    [Backend]:          Started Discord Rich Presence
(15:52:03) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton - Experimental
(15:52:03) WARNING: [Backend]:          You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(15:52:03) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton - Experimental
(15:52:03) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton - Experimental
(15:52:03) DEBUG:   [Backend]:          Running Wine command: run wineboot --init
(15:52:03) INFO:    [Backend]:          Starting the Download Queue
(15:52:04) INFO:    [Legendary]:        Launching DEATH STRANDING DIRECTOR'S CUT: HEROIC_APP_NAME=c38f51843fdf4db0b24fc907b8d78221 HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia STEAM_COMPAT_INSTALL_PATH=/home/loic/Jeux/Heroic/DeathStrandingDC LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= DOTNET_ROOT= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH="/home/loic/Jeux/Heroic/Prefixes/DEATH STRANDING DIRECTORS CUT" WINE_FULLSCREEN_FSR=0 PROTON_ENABLE_NVAPI=1 DXVK_NVAPI_ALLOW_OTHER_DRIVERS=1 PROTON_EAC_RUNTIME=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/eac_runtime PROTON_BATTLEYE_RUNTIME=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/battleye_runtime STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-DeathStrandingDC PROTON_LOG_DIR=/home/loic/.var/app/com.heroicgameslauncher.hgl LEGENDARY_CONFIG_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch c38f51843fdf4db0b24fc907b8d78221 --no-wine --wrapper "/usr/lib/extensions/vulkan/MangoHud/bin/mangohud --dlsym /app/bin/gamemoderun /home/loic/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point -- '/home/loic/.local/share/Steam/steamapps/common/Proton - Experimental/proton' run" --language fr
(15:52:04) INFO:    [Backend]:          Stopping Power Saver Blocker
(15:52:34) INFO:    [Backend]:          Stopped Discord Rich Presence
(15:52:34) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(15:52:34) INFO:    [Frontend]:         Refreshing legendary Library
(15:52:34) INFO:    [Legendary]:        Refreshing library...
(15:52:34) INFO:    [Legendary]:        Refreshing Epic Games...
(15:52:34) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:52:36) INFO:    [Legendary]:        Game list updated, got 56 games & DLCs
(15:52:38) INFO:    [Backend]:          Launching The Witcher 3: Wild Hunt (1207664643)
(15:52:38) INFO:    [Backend]:          Preventing display from sleep
(15:52:38) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton - Experimental
(15:52:38) INFO:    [Backend]:          Started Discord Rich Presence
(15:52:38) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton - Experimental
(15:52:38) WARNING: [Backend]:          You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(15:52:38) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton - Experimental
(15:52:38) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton - Experimental
(15:52:38) DEBUG:   [Backend]:          Running Wine command: run wineboot --init
(15:52:39) INFO:    [Gog]:              Launching The Witcher 3: Wild Hunt: HEROIC_APP_NAME=1207664643 HEROIC_APP_RUNNER=gog HEROIC_APP_SOURCE=gog DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia STEAM_COMPAT_INSTALL_PATH="/home/loic/Jeux/Heroic/The Witcher 3 Wild Hunt" MangoHud=MANGOHUD=1 LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= DOTNET_ROOT= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH="/home/loic/Jeux/Heroic/Prefixes/The Witcher 3 Wild Hunt" WINE_FULLSCREEN_FSR=0 PROTON_ENABLE_NVAPI=1 DXVK_NVAPI_ALLOW_OTHER_DRIVERS=1 PROTON_EAC_RUNTIME=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/eac_runtime PROTON_BATTLEYE_RUNTIME=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/battleye_runtime STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId="heroic-The Witcher 3 Wild Hunt" PROTON_LOG_DIR=/home/loic/.var/app/com.heroicgameslauncher.hgl GOGDL_CONFIG_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json launch "/home/loic/Jeux/Heroic/The Witcher 3 Wild Hunt" 1207664643 --no-wine --wrapper "/app/bin/gamemoderun /home/loic/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point -- '/home/loic/.local/share/Steam/steamapps/common/Proton - Experimental/proton' run" --platform windows mangohud
(15:52:39) INFO:    [Backend]:          Stopping Power Saver Blocker
(15:53:02) INFO:    [Backend]:          Stopped Discord Rich Presence
(15:53:02) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(15:53:02) INFO:    [Frontend]:         Refreshing gog Library
(15:53:02) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:53:02) INFO:    [Gog]:              Getting GOG library
(15:53:02) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/loic/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:53:02) INFO:    [Gog]:              Saved games data
```

### Steps to reproduce

1. Download the latest mangohud flatpak pakage
2. Enable mangohud in heroic
3. launch any game

### Expected behavior

Game launches and mangohud appears on the top left corner.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Ubuntu 23.10

**Comment by Madame-Louise** [comment]
I updated to version 2.14.0 yesterday and now games won't launch if MangoHud is enabled, but no error message is shown (like the one were MangoHud isn't on PATH).

**Comment by fallenexistence0** [comment]
I am on arch but I've had the same problem, on both heroic and lutris as well, whenever I set mangoHud to run when I start a game, the game doesn't launch or immediatly closes after launching, I have found two solutions that seems to work for me, either I download from the arch user repository or I install from their github release: https://github.com/flightlessmango/MangoHud?tab=readme-ov-file#github-releases, there is also the option of building from source: https://github.com/flightlessmango/MangoHud?tab=readme-ov-file#installation---build-from-source, but downloading and installing from the github page should fix things for you, also don't forget to remove mangoHud before reinstalling.

**Comment by fallenexistence0** [comment]
Yes, you can do easily, this may be different for you but the command is something like this: 
1- Go to the directory where the mangoHud excecutable is.
2- Run the following command ( replace the path with where the deb file is)
> export PATH=$PATH:/path/to/mangohud/directory
3- Run mangoHud from heroic.
4- You will then have to make it permanent by adding the command to your shell's configuration file. (~/.bashrc on ubuntu according to this: https://effective-shell.com/part-5-building-your-toolkit/configuring-the-shell/)

Although when I had the error, it was due to a conflict of files, I installed mangoHud from the offcial repository and from flatpack (and from God knows where else lol), the only solution might be to purge mangoHud from your system before trying to installing it again, from their github.

**Comment by Madame-Louise** [comment]
Well it seems that the problem came from me using proton experimental. Mangohud apparently doens't work when using anything other than wine-ge. I thought it worked fine in the past, but I must've been wrong. Would be great if it did though !

**Comment by fallenexistence0** [comment]
I'm glad you were able to find a solution, happy gaming!

**Comment by Madame-Louise** [comment]
Me too, thanks for your help !
