### ISSUE TITLE
Downloading Games from Epic

### ISSUE THREAD

**Issue by ani9730** [Heroic-Games-Launcher/HeroicGamesLauncher#3667]
### Describe the bug

I am facing this bug from last update and what happens is if you change the drive for downloading the resources, it shows an error.
Can someone explain the error to me?
The error is as follows:
An error has occurred! Try to Logout and Login on your Epic account.
[Core] INFO: Trying to re-use existing login session...[cli] INFO: Preparing download for "Grand Theft Auto V" (9d2d0eb64d5c44529cece33fe2a46482)...[Core] INFO: Parsing game manifest...[Core] INFO: "D:" --skip-dlcs -y --skip-sdl " does not exist, creating...
Traceback (most recent call last):
File "legendary\cli.py", line 3161, in <module>File "legendary\cli.py", line 3078, in main
File "legendary\cli.py", line 962, in install_game
File "legendary\core.py", line 1411, in prepare_download
File "os.py", line 225, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:" --skip-dlcs -y --skip-sdl '
[6884] Failed to execute script 'cli' due to unhandled exception!

### Add logs

```text
(21:19:40) INFO:    [Legendary]:        Legendary location: C:\Users\deshm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(21:19:40) INFO:    [Gog]:              GOGDL location: C:\Users\deshm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(21:19:40) INFO:    [Connection]:       Connectivity: check-online
(21:19:40) INFO:    [Connection]:       Pinging external endpoints
(21:19:40) INFO:    [Gog]:              Checking for existing gog manifests
(21:19:40) INFO:    [Backend]:          DRM module staus {
  "neifaoindggfcjicffkgpmnlppeffabd": {
    "status": "new",
    "title": "Google Widevine Windows CDM",
    "version": "1.0.2738.0"
  },
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(21:19:40) WARNING: [Backend]:          Protocol already registered.
(21:19:40) INFO:    [Connection]:       Connectivity: online
(21:19:40) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(21:19:40) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\deshm\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\deshm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\Users\deshm\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`""
(21:19:40) INFO:    [Frontend]:         Refreshing undefined Library
(21:19:40) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(21:19:40) INFO:    [Legendary]:        Refreshing library...
(21:19:40) INFO:    [Legendary]:        Refreshing Epic Games...
(21:19:40) INFO:    [Backend]:          Frontend Ready
(21:19:40) INFO:    [Backend]:          Checking for new Heroic Updates
(21:19:40) INFO:    [Backend]:          Checking for current version changelog
(21:19:41) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\deshm\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\deshm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"list`"","`"--third-party`""
(21:19:41) INFO:    [Backend]:          VCRuntime is installed
(21:19:42) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(21:19:42) INFO:    [WineDownloader]:   Updating wine versions info
(21:19:42) INFO:    [WineDownloader]:   Fetching upstream information...
(21:19:42) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\deshm\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\deshm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"--version`""
(21:19:42) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\deshm\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\deshm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\Users\deshm\AppData\Roaming\heroic\gog_store\auth.json`"","`"--version`""
(21:19:42) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\deshm\AppData\Roaming\heroic\nile_config powershell Start-Process "`"C:\Users\deshm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"--version`""
(21:19:43) INFO:    [WineDownloader]:   wine versions updated
(21:19:43) ERROR:   [Backend]:          Could not find default wine version
(21:19:44) DEBUG:   [Legendary]:        Using cached install info
(21:19:44) INFO:    [Backend]:          
System Information:
CPU: 24x 13th Gen Intel(R) Core(TM) i7-13700HX
Memory: 16.89 GB (used: 5.59 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation AD107M [GeForce RTX 4060 Max-Q / Mobile]
    IDs: D=28e0 V=10de SD=170f SV=1025
    Driver: 551.86
OS: Microsoft Windows 11 Home 10.0.22631 (win32)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.0 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(21:19:44) INFO:    [Legendary]:        Game list updated, got 25 games & DLCs
(21:19:44) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(21:19:45) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=C:\Users\deshm\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\deshm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"list`"","`"--third-party`""
(21:19:45) INFO:    [Backend]:          Starting the Download Queue
(21:19:49) WARNING: [Legendary]:        Failed to parse games from C:\Users\deshm\AppData\Roaming\heroic\legendaryConfig\legendary\installed.json with: Error: ENOENT: no such file or directory, open 'C:\Users\deshm\AppData\Roaming\heroic\legendaryConfig\legendary\installed.json'
    at Object.readFileUtf8 (node:internal/fs/sync:25:18)
    at Object.readFileSync (node:fs:441:19)
    at t.readFileSync (node:electron/js2c/node_init:2:9784)
    at Module.listUpdateableGames (C:\Users\deshm\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.e5c6248b.js:114:4090)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\deshm\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.e5c6248b.js:235:3193
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:81094)
(21:19:49) INFO:    [Legendary]:        Found 0 games to update
(21:19:51) DEBUG:   [Legendary]:        Using cached install info
(21:19:51) INFO:    [DownloadManager]:  Grand Theft Auto V  was added to the download queue.
(21:19:51) INFO:    [Backend]:          Preventing machine to sleep
(21:19:51) DEBUG:   [Legendary]:        Using cached install info
(21:19:51) INFO:    [Legendary]:        Installing 9d2d0eb64d5c44529cece33fe2a46482: LEGENDARY_CONFIG_PATH=C:\Users\deshm\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\deshm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"install`"","`"9d2d0eb64d5c44529cece33fe2a46482`"","`"--platform`"","`"Windows`"","`"--base-path`"","`"D:\`"","`"--skip-dlcs`"","`"-y`"","`"--skip-sdl`""
(21:19:51) DEBUG:   [Legendary]:        Logging to file "C:\Users\deshm\AppData\Roaming\heroic\GamesConfig\9d2d0eb64d5c44529cece33fe2a46482.log"
(21:19:57) INFO:    [Backend]:          Adding shortcuts for Grand Theft Auto V
(21:19:57) INFO:    [DownloadManager]:  Finished Installation of 9d2d0eb64d5c44529cece33fe2a46482
(21:19:57) INFO:    [DownloadManager]:  9d2d0eb64d5c44529cece33fe2a46482 added to download manager finished.
(21:19:57) INFO:    [DownloadManager]:  9d2d0eb64d5c44529cece33fe2a46482 removed from download manager.
(21:19:57) INFO:    [Frontend]:         Refreshing legendary Library
(21:19:57) INFO:    [Legendary]:        Refreshing library...
(21:19:57) INFO:    [Legendary]:        Refreshing Epic Games...
(21:19:57) INFO:    [Backend]:          operation interrupted
(21:19:57) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\deshm\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\deshm\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"list`"","`"--third-party`""
(21:20:01) INFO:    [Legendary]:        Game list updated, got 25 games & DLCs
```

### Steps to reproduce

1. Go to 'Library'
2. Click on Any Game
3. Change the Drive
4. Click on install
5. See error

### Expected behavior

It should have started downloading the game in that particular disc.

### Screenshots

![Screenshot 2024-04-01 211453](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/120796659/033011a3-a928-4851-a2cd-a5942bb1815c)

### Heroic Version

Latest Stable

### System Information

Windows 11 version 23H2(OS build 22631.3374)

**Comment by arielj** [comment]
can you try selecting a folder inside the D drive instead of the D drive's root?

I understand this should have been fixed though

**Comment by ani9730** [comment]
> can you try selecting a folder inside the D drive instead of the D drive's root?
> 
> I understand this should have been fixed though

Yes, its working but what exactly has changed? In version 2.12, it is working fine even if we select the drive. Also, please check the issue that is mentioned in #3643 . Even if i download the game, the epic games redirect doesn't work.

**Comment by ani9730** [comment]
> > > can you try selecting a folder inside the D drive instead of the D drive's root?
> > > I understand this should have been fixed though
> > 
> > 
> > Yes, its working but what exactly has changed? In version 2.12, it is working fine even if we select the drive.
> 
> that issue was happening to users before the 2.14 release (you mention you where using 2.12, so I imagine the problem started in 2.13 if you were not using that version)
> 
> I see the fix #3658 didn't get into the release though
> 
> I don't know exactly what changed (I don't even have windows) but you should do that workaround (selecting a folder and not the root drive) until a release with that fix is done

Thanks

**Comment by arielj** [comment]
Closing. The fix mentioned above is already present in the last release
