### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by Jocc01** [Heroic-Games-Launcher/HeroicGamesLauncher#3675]
### Describe the bug

So exactly I dunno its a bug or not Im a new Linux user (Ubuntu). I tried play league of legends in ubuntu with heroic launcher but not everything work fine. Is there a permission denied and I dunno whats the solution. I've search some page yt videos but no one helped me yet. I tried to log out and log in like the error said up there but nothing happened.

### Add logs

```text
Legendary (Epic Games)
Error:
An error has occurred! Try to Logout and Login on your Epic account.
Traceback (most recent call last):
File "legendary/cli.py", line 3149, in <module>
File "legendary/cli.py", line 3033, in main
File "legendary/cli.py", line 48, in setup_threaded_logging
File "multiprocessing/context.py", line 103, in Queue
File "multiprocessing/queues.py", line 43, in __init__
File "multiprocessing/context.py", line 68, in Lock
File "multiprocessing/synchronize.py", line 162, in __init__
File "multiprocessing/synchronize.py", line 57, in __init__PermissionError: [Errno 13] Permission denied
[11273] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

An error has occurred! Try to Logout and Login on your Epic account.
Traceback (most recent call last):
File "legendary/cli.py", line 3149, in <module>
File "legendary/cli.py", line 3033, in main
File "legendary/cli.py", line 48, in setup_threaded_logging
File "multiprocessing/context.py", line 103, in Queue
File "multiprocessing/queues.py", line 43, in __init__
File "multiprocessing/context.py", line 68, in Lock
File "multiprocessing/synchronize.py", line 162, in __init__
File "multiprocessing/synchronize.py", line 57, in __init__PermissionError: [Errno 13] Permission denied
[11273] Failed to execute script 'cli' due to unhandled exception!

### Screenshots

![Screenshot from 2024-04-04 14-06-25](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/166019542/f5ec696a-ab68-4e4e-ab04-5357f1d0a38e)

### Heroic Version

Latest Stable

### System Information

-OS Ubuntu

**Comment by Jocc01** [comment]
> Which WINE version are you using? For league of legends it should be WIne-GE-Proton8-27-LoL, you can find this in the wine manager tabs under Downloads.

The latest WineGE LoL version whoch is the  WIne-GE-Proton8-27-Lo yeh

**Comment by Karan1000** [comment]
First, install Flatpak by running the following command:

sudo apt install flatpak

Add the Flathub repository to your system by executing:

flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

Restart your computer to ensure the changes take effect.

Install Heroic using Flatpak from the Flathub repository with this command:

flatpak install flathub com.heroicgameslauncher.hgl

Once installed, launch Heroic using Flatpak by running:

flatpak run com.heroicgameslauncher.hgl

Log in using your Epic Games account, and you should be able to play without encountering the previous error.

**Comment by arielj** [comment]
Closing, LoL stopped working on linux many months ago.

If this is still an issue with other games it can be reopened
