### ISSUE TITLE
Celeste from Epic Games creashes after exiting

### ISSUE THREAD

**Issue by Nikitf777** [Heroic-Games-Launcher/HeroicGamesLauncher#3706]
### Describe the bug

[Salt-lastPlay.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/15044189/Salt-lastPlay.log)

When I click "Exit" button in the game, the screen becomes dark and then the following error occurs (I've got this error message only once, after enabling cloud saved, in other cases there weren't any error messages, just crash):

An error has occurred! Try to Logout and Login on your Epic account.
[Core] INFO: Trying to re-use existing login session...Traceback (most recent call last):
File "urllib3/connection.py", line 198, in _new_connFile "urllib3/util/connection.py", line 60, in create_connection
File "socket.py", line 954, in getaddrinfosocket.gaierror: [Errno -2] Name or service not known
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "urllib3/connectionpool.py", line 793, in urlopenFile "urllib3/connectionpool.py", line 491, in _make_requestFile "urllib3/connectionpool.py", line 467, in _make_requestFile "urllib3/connectionpool.py", line 1099, in _validate_connFile "urllib3/connection.py", line 616, in connectFile "urllib3/connection.py", line 205, in _new_connurllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x756d2f1594c0>: Failed to resolve 'datastorage-public-service-liveegs.live.use1a.on.epicgames.com' ([Errno -2] Name or service not known)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "requests/adapters.py", line 486, in sendFile "urllib3/connectionpool.py", line 847, in urlopenFile "urllib3/util/retry.py", line 515, in incrementurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='datastorage-public-service-liveegs.live.use1a.on.epicgames.com', port=443): Max retries exceeded with url: /api/v1/access/egstore/savesync/bf79acee2d3d4f6f8589b7cb55b8c19b/Salt/manifests/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x756d2f1594c0>: Failed to resolve 'datastorage-public-service-liveegs.live.use1a.on.epicgames.com' ([Errno -2] Name or service not known)"))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "legendary/cli.py", line 3161, in <module>
File "legendary/cli.py", line 3088, in main
File "legendary/cli.py", line 459, in sync_savesFile "legendary/core.py", line 812, in get_save_gamesFile "legendary/api/egs.py", line 267, in get_user_cloud_savesFile "requests/sessions.py", line 602, in getFile "requests/sessions.py", line 589, in requestFile "requests/sessions.py", line 703, in sendFile "requests/adapters.py", line 519, in sendrequests.exceptions.ConnectionError: HTTPSConnectionPool(host='datastorage-public-service-liveegs.live.use1a.on.epicgames.com', port=443): Max retries exceeded with url: /api/v1/access/egstore/savesync/bf79acee2d3d4f6f8589b7cb55b8c19b/Salt/manifests/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x756d2f1594c0>: Failed to resolve 'datastorage-public-service-liveegs.live.use1a.on.epicgames.com' ([Errno -2] Name or service not known)"))
[857] Failed to execute script 'cli' due to unhandled exception!

### Add logs

```text
I added logs as file because of the issue length limit
```

### Steps to reproduce

1. Launch game
2. Click "Exit" in the main menu
3. Game crashes

### Expected behavior

The game should close without any crashes

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/127026067/73c38540-75bf-4953-b635-33c366db2fcb)

### Heroic Version

Latest Stable

### System Information

Ubuntu 23.10
See logs

**Comment by arielj** [comment]
Can you access this url? https://datastorage-public-service-liveegs.live.use1a.on.epicgames.com

the error says it can't connect to that, maybe you have a firewall or something blocking that url?

**Comment by arielj** [comment]
closing as there's been no answer since april
