### ISSUE TITLE
The Medium wont install

### ISSUE THREAD

**Issue by beastschiss** [Heroic-Games-Launcher/HeroicGamesLauncher#3734]
### Describe the bug

the medium wont install. Im on 2.14.1 linux version

### Add logs

```text
(00:00:44) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(00:00:44) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(00:00:44) INFO:    [Connection]:       Connectivity: check-online
(00:00:44) INFO:    [Connection]:       Pinging external endpoints
(00:00:44) INFO:    [Gog]:              Checking for existing gog manifests
(00:00:44) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(00:00:44) WARNING: [Backend]:          Protocol already registered.
(00:00:44) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(00:00:44) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/jenny/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jenny/.config/heroic/gog_store/auth.json --version
(00:00:44) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/jenny/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(00:00:45) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 7 5800X 8-Core Processor
Memory: 33.57 GB (used: 5.4 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M]
    IDs: D=744c V=1002 SD=790a SV=1eae
    Driver: amdgpu
OS: EndeavourOS 6.8.9-zen1-1-zen (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(00:00:45) INFO:    [Connection]:       Connectivity: online
(00:00:45) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/jenny/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jenny/.config/heroic/gog_store/auth.json auth
(00:00:45) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(00:00:45) INFO:    [Frontend]:         Refreshing undefined Library
(00:00:45) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(00:00:45) INFO:    [Legendary]:        Refreshing library...
(00:00:45) INFO:    [Legendary]:        Refreshing Epic Games...
(00:00:45) INFO:    [Backend]:          Frontend Ready
(00:00:45) INFO:    [Backend]:          Checking for new Heroic Updates
(00:00:45) INFO:    [Backend]:          Checking for current version changelog
(00:00:45) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(00:00:45) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(00:00:47) INFO:    [Legendary]:        Game list updated, got 94 games & DLCs
(00:00:47) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(00:00:47) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(00:00:47) INFO:    [Winetricks]:       Downloading Winetricks
(00:00:48) INFO:    [Legendary]:        Found 0 games to update
(00:00:49) INFO:    [WineDownloader]:   Updating wine versions info
(00:00:49) INFO:    [WineDownloader]:   Fetching upstream information...
(00:00:50) INFO:    [Backend]:          Starting the Download Queue
(00:00:50) DEBUG:   [Legendary]:        Using cached install info
(00:00:50) INFO:    [WineDownloader]:   wine versions updated
(00:00:54) INFO:    [Backend]:          Writing config for bc72e23dc6494fb584a254ada099b362
(00:00:54) DEBUG:   [Legendary]:        Using cached install info
(00:00:54) INFO:    [DownloadManager]:  The Medium  was added to the download queue.
(00:00:54) INFO:    [Backend]:          Preventing machine to sleep
(00:00:54) DEBUG:   [Legendary]:        Using cached install info
(00:00:54) INFO:    [Legendary]:        Installing bc72e23dc6494fb584a254ada099b362: LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary install bc72e23dc6494fb584a254ada099b362 --platform Windows --base-path /run/media/jenny/GamesII_1TB/Epic --skip-dlcs -y --skip-sdl
(00:00:54) DEBUG:   [Legendary]:        Logging to file "/home/jenny/.config/heroic/GamesConfig/bc72e23dc6494fb584a254ada099b362.log"
(00:00:55) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://raw.githubusercontent.com/Heroic-Games-Launcher/known-fixes/main/epic/bc72e23dc6494fb584a254ada099b362-epic.json. 
Error: Error: Request failed with status code 404
(00:00:56) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary install bc72e23dc6494fb584a254ada099b362 --platform Windows --base-path /run/media/jenny/GamesII_1TB/Epic --skip-dlcs -y --skip-sdl --max-shared-memory 5000
(00:00:56) DEBUG:   [Legendary]:        Logging to file "/home/jenny/.config/heroic/GamesConfig/bc72e23dc6494fb584a254ada099b362.log"
(00:00:58) INFO:    [Backend]:          Adding shortcuts for The Medium
(00:00:58) INFO:    [DownloadManager]:  Finished Installation of bc72e23dc6494fb584a254ada099b362
(00:00:58) INFO:    [DownloadManager]:  bc72e23dc6494fb584a254ada099b362 added to download manager finished.
(00:00:58) INFO:    [DownloadManager]:  bc72e23dc6494fb584a254ada099b362 removed from download manager.
(00:00:58) INFO:    [Frontend]:         Refreshing legendary Library
(00:00:58) INFO:    [Legendary]:        Refreshing library...
(00:00:58) INFO:    [Legendary]:        Refreshing Epic Games...
(00:00:58) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(00:01:00) INFO:    [Legendary]:        Game list updated, got 94 games & DLCs
```

### Steps to reproduce

klick on install

### Expected behavior

download should start

### Heroic Version

Latest Stable

### System Information

Operating System: EndeavourOS 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Kernel Version: 6.8.9-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 7900 GRE
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C56
System Version: 1.0

**Comment by arielj** [comment]
please share the legendary logs (settings > logs > epic/legendary) after the install fails

**Comment by beastschiss** [comment]
`(10:07:57) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(10:07:57) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(10:07:57) INFO:    [Connection]:       Connectivity: check-online
(10:07:57) INFO:    [Connection]:       Pinging external endpoints
(10:07:57) INFO:    [Gog]:              Checking for existing gog manifests
(10:07:57) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(10:07:57) WARNING: [Backend]:          Protocol already registered.
(10:07:57) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(10:07:57) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/jenny/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jenny/.config/heroic/gog_store/auth.json --version
(10:07:57) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/jenny/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(10:07:57) INFO:    [Connection]:       Connectivity: online
(10:07:57) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/jenny/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jenny/.config/heroic/gog_store/auth.json auth
(10:07:57) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(10:07:57) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(10:07:57) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 7 5800X 8-Core Processor
Memory: 33.58 GB (used: 2.18 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M]
    IDs: D=744c V=1002 SD=790a SV=1eae
    Driver: amdgpu
OS: EndeavourOS 6.9.1-zen1-1-zen (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(10:07:57) INFO:    [Frontend]:         Refreshing undefined Library
(10:07:57) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(10:07:57) INFO:    [Legendary]:        Refreshing library...
(10:07:57) INFO:    [Legendary]:        Refreshing Epic Games...
(10:07:57) INFO:    [Backend]:          Frontend Ready
(10:07:57) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(10:07:57) INFO:    [Backend]:          Checking for new Heroic Updates
(10:07:57) INFO:    [Backend]:          Checking for current version changelog
(10:07:59) INFO:    [Winetricks]:       Downloading Winetricks
(10:08:00) INFO:    [Legendary]:        Game list updated, got 95 games & DLCs
(10:08:00) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(10:08:00) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(10:08:01) INFO:    [Legendary]:        Found 0 games to update
(10:08:01) INFO:    [Frontend]:         Force Update
(10:08:02) INFO:    [WineDownloader]:   Updating wine versions info
(10:08:02) INFO:    [WineDownloader]:   Fetching upstream information...
(10:08:02) INFO:    [Backend]:          Starting the Download Queue
(10:08:03) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for The Medium
(10:08:03) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for The Medium
(10:08:03) INFO:    [Legendary]:        Getting more details with 'legendary info'
(10:08:03) INFO:    [Legendary]:        Getting more details with 'legendary info'
(10:08:03) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info bc72e23dc6494fb584a254ada099b362 --json --platform Windows
(10:08:03) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info bc72e23dc6494fb584a254ada099b362 --json --platform Windows
(10:08:03) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(10:08:03) INFO:    [WineDownloader]:   wine versions updated
(10:08:03) INFO:    [Legendary]:        Getting Info from Epic API
(10:08:04) INFO:    [Legendary]:        Getting more details with 'legendary info'
(10:08:05) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info bc72e23dc6494fb584a254ada099b362 --json --platform Windows
(10:08:13) INFO:    [Backend]:          Writing config for bc72e23dc6494fb584a254ada099b362
(10:08:13) DEBUG:   [Legendary]:        Using cached install info
(10:08:13) INFO:    [DownloadManager]:  The Medium  was added to the download queue.
(10:08:13) INFO:    [Backend]:          Preventing machine to sleep
(10:08:13) DEBUG:   [Legendary]:        Using cached install info
(10:08:13) DEBUG:   [Legendary]:        Using cached install info
(10:08:14) DEBUG:   [Legendary]:        Using cached install info
(10:08:14) INFO:    [Legendary]:        Installing bc72e23dc6494fb584a254ada099b362: LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary install bc72e23dc6494fb584a254ada099b362 --platform Windows --base-path /run/media/jenny/GamesII_1TB/Epic --skip-dlcs -y --skip-sdl
(10:08:14) DEBUG:   [Legendary]:        Logging to file "/home/jenny/.config/heroic/GamesConfig/bc72e23dc6494fb584a254ada099b362.log"
(10:08:14) DEBUG:   [Legendary]:        Using cached install info
(10:08:14) DEBUG:   [Legendary]:        Using cached install info
(10:08:14) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://raw.githubusercontent.com/Heroic-Games-Launcher/known-fixes/main/epic/bc72e23dc6494fb584a254ada099b362-epic.json. 
Error: Error: Request failed with status code 404
(10:08:15) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary install bc72e23dc6494fb584a254ada099b362 --platform Windows --base-path /run/media/jenny/GamesII_1TB/Epic --skip-dlcs -y --skip-sdl --max-shared-memory 5000
(10:08:15) DEBUG:   [Legendary]:        Logging to file "/home/jenny/.config/heroic/GamesConfig/bc72e23dc6494fb584a254ada099b362.log"
(10:08:17) INFO:    [Backend]:          Adding shortcuts for The Medium
(10:08:17) INFO:    [DownloadManager]:  Finished Installation of bc72e23dc6494fb584a254ada099b362
(10:08:17) INFO:    [DownloadManager]:  bc72e23dc6494fb584a254ada099b362 added to download manager finished.
(10:08:17) INFO:    [DownloadManager]:  bc72e23dc6494fb584a254ada099b362 removed from download manager.
(10:08:17) INFO:    [Frontend]:         Refreshing legendary Library
(10:08:17) INFO:    [Legendary]:        Refreshing library...
(10:08:17) INFO:    [Legendary]:        Refreshing Epic Games...
(10:08:17) DEBUG:   [Legendary]:        Using cached install info
(10:08:17) DEBUG:   [Legendary]:        Using cached install info
(10:08:17) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(10:08:19) INFO:    [Legendary]:        Game list updated, got 95 games & DLCs
(10:08:19) DEBUG:   [Legendary]:        Using cached install info
(10:08:19) DEBUG:   [Legendary]:        Using cached install info
`

**Comment by beastschiss** [comment]
[2024-05-22T07_57_15-heroic.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/15400189/2024-05-22T07_57_15-heroic.log)
[2024-05-22T08_07_57-legendary.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/15400196/2024-05-22T08_07_57-legendary.log)

**Comment by arielj** [comment]
Try running the install command manually in a terminal with increased shared memory

```
LEGENDARY_CONFIG_PATH=/home/jenny/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary install bc72e23dc6494fb584a254ada099b362 --platform Windows --base-path /run/media/jenny/GamesII_1TB/Epic --skip-dlcs -y --skip-sdl --max-shared-memory 8000
```

**Comment by beastschiss** [comment]
working

**Comment by arielj** [comment]
closing as it seems to have been fixed from the previous comment
