### ISSUE TITLE
Shortcuts has wrong icons

### ISSUE THREAD

**Issue by OlegAckbar** [Heroic-Games-Launcher/HeroicGamesLauncher#3735]
### Describe the bug

Some games like Borderlands 3 has wrong icon in their shortcut. It uses vertical banner for the icon 
![изображение](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/9915567/5174bf6b-9c5d-414d-91f6-22792647cc33)
When it should be something like icon from executable
![изображение](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/9915567/bb1a2214-f7ce-4a3e-9dc3-f3a9a3f9625b)

### Add logs

```text
(18:08:37) INFO:    [Legendary]:        Legendary location: /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(18:08:37) INFO:    [Gog]:              GOGDL location: /opt/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:08:37) INFO:    [Connection]:       Connectivity: check-online
(18:08:37) INFO:    [Connection]:       Pinging external endpoints
(18:08:37) INFO:    [Gog]:              Checking for existing gog manifests
(18:08:37) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(18:08:37) WARNING: [Backend]:          Protocol already registered.
(18:08:37) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/oleg/.config/heroic/legendaryConfig/legendary /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(18:08:37) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/oleg/.config/heroic/gogdlConfig /opt/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/oleg/.config/heroic/gog_store/auth.json --version
(18:08:37) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/oleg/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(18:08:37) INFO:    [Connection]:       Connectivity: online
(18:08:37) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/oleg/.config/heroic/gogdlConfig /opt/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/oleg/.config/heroic/gog_store/auth.json auth
(18:08:37) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(18:08:37) INFO:    [Backend]:          
System Information:
CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Memory: 16.71 GB (used: 5.01 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT]
    IDs: D=73df V=1002 SD=3982 SV=1462
    Driver: amdgpu
OS: Arch Linux 6.8.8-2-cachyos (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(18:08:37) INFO:    [Frontend]:         Refreshing undefined Library
(18:08:37) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(18:08:37) INFO:    [Legendary]:        Refreshing library...
(18:08:37) INFO:    [Legendary]:        Refreshing Epic Games...
(18:08:37) INFO:    [Backend]:          Frontend Ready
(18:08:38) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(18:08:38) INFO:    [Backend]:          Checking for new Heroic Updates
(18:08:38) INFO:    [Backend]:          Checking for current version changelog
(18:08:38) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/oleg/.config/heroic/legendaryConfig/legendary /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(18:08:40) INFO:    [Winetricks]:       Downloading Winetricks
(18:08:41) INFO:    [Legendary]:        Game list updated, got 26 games & DLCs
(18:08:41) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(18:08:41) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/oleg/.config/heroic/legendaryConfig/legendary /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(18:08:42) INFO:    [WineDownloader]:   Updating wine versions info
(18:08:42) INFO:    [WineDownloader]:   Fetching upstream information...
(18:08:42) INFO:    [Backend]:          Starting the Download Queue
(18:08:43) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: LEGENDARY_CONFIG_PATH=/home/oleg/.config/heroic/legendaryConfig/legendary /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/home/oleg/Games/Heroic/Prefixes/default/Borderlands 3/pfx"
(18:08:43) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Borderlands 3
(18:08:43) INFO:    [Legendary]:        Getting more details with 'legendary info'
(18:08:43) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Borderlands 3
(18:08:43) INFO:    [Legendary]:        Getting more details with 'legendary info'
(18:08:43) INFO:    [Legendary]:        Getting more details with 'legendary info'
(18:08:43) INFO:    [Legendary]:        Found 0 games to update
(18:08:43) INFO:    [Legendary]:        Getting more details with 'legendary info'
(18:08:43) INFO:    [Legendary]:        Getting more details with 'legendary info'
(18:08:43) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/oleg/.config/heroic/legendaryConfig/legendary /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Catnip --json --platform Windows
(18:08:43) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/oleg/.config/heroic/legendaryConfig/legendary /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Catnip --json --platform Windows
(18:08:43) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(18:08:43) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/oleg/.config/heroic/legendaryConfig/legendary /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Catnip --json --platform Windows
(18:08:43) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/oleg/.config/heroic/legendaryConfig/legendary /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Catnip --json --platform Windows
(18:08:43) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(18:08:43) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/oleg/.config/heroic/legendaryConfig/legendary /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Catnip --json --platform Windows
(18:08:43) INFO:    [Legendary]:        Abort command "LEGENDARY_CONFIG_PATH=/home/oleg/.config/heroic/legendaryConfig/legendary /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/home/oleg/Games/Heroic/Prefixes/default/Borderlands 3/pfx""
(18:08:43) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(18:08:43) ERROR:   [Legendary]:        Error Getting Info from Epic API
(18:08:43) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(18:08:43) ERROR:   [Legendary]:        Error Getting Info from Epic API
(18:08:43) INFO:    [WineDownloader]:   wine versions updated
(18:08:47) INFO:    [Backend]:          Desktop shortcut removed
(18:08:47) INFO:    [Backend]:          Applications shortcut removed
(18:08:50) INFO:    [Backend]:          Adding shortcuts for Borderlands 3
(18:08:50) INFO:    [Backend]:          Shortcut saved on /home/oleg/Рабочий стол/Borderlands 3.desktop
(18:08:50) INFO:    [Backend]:          Shortcut saved on /home/oleg/.local/share/applications/Borderlands 3.desktop
```

### Steps to reproduce

1. Make a shortcut for Borderlands 3 through Heroic
2. Observe wrong icon

### Expected behavior

A shortcut with an proper icon. Here I replaced icon for the shortcut with the one extracted from the executable.
![изображение](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/9915567/174826fc-371b-4d1f-b3bf-fa4525885fae)

### Heroic Version

Latest Stable

### System Information

Operating System: Arch Linux 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Kernel Version: 6.8.8-2-cachyos (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 15.6 ГиБ of RAM
Graphics Processor: AMD Radeon RX 6700 XT

**Comment by DenysMb** [comment]
Q4Wine has an option called "Extract images from PE files", that extract the icon from the .exe file. We can check how this is done and then think in a way to, instead of use the vertical banner as an option, extract the image from the .exe file pointed as the one to run the game, save the image somewhere and use it as shortcut.

Another option would be to give us the option to have 2 icons (the vertical banner and a square one, like Lutris, that have three, but only two is enough).

**Comment by matteobtt** [comment]
`wrestool` can be used to extract the .ico file from the .exe file and `icotool` can be used to convert the .ico file into a bunch of PNG icons of various sizes. These tools are provided by [icoutils](https://www.nongnu.org/icoutils/), [even Q4Wine uses them](https://github.com/brezerk/q4wine/blob/82ced8eaa14ac1b705ec71404155bf6cf03e8657/src/q4wine-gui/mainwindow.cpp#L822).

**Comment by SlimJim192** [comment]
+1 my biggest gripe of heroic is the use of covers on shortcuts rather than the original icons.

**Comment by sgghostrider** [comment]
Actually using the "game banner"s as icons it's not only bad(both because it looks bad and also because it doesn't always work because of several bugs in the code), but also could "lockout" your PC if using KDE/dolphin, even "soft brick it" if not familiar with linux. I just had a REALLY bad experience with this "feature". I had to add a custom banner for a game because it's just a random indie game from itch.io, so it's not listed in steamgriddb, but shortly after adding the game it started an "sudden and rapid memory leak" in plasmashell freezing it and then crashing it after 5 seconds in loops as it restarted on it's own every time until i killed it from the terminal.

Only reason i found out it was an Heroic created icon was because it was freezing and crashing Dolphin too, and it did it only when i was trying to open the "`~/Desktop/ `" directory, where the icon was, and the only way of fixing it was deleting the image from "`~/.config/heroic/icons/`" and restarting plasmashell...

When i looked it on google it seems the reason of the memory leak is something about how kde renders icons and using images of big dimensions as icons triggers it... in my case a 1400p banner... so yea, it would be really great if the launcher just extracted the icons from the executables, which can be done with just the basic 7zip library and getting the heaviest file from "/.rsrc/ICON/"...
