### ISSUE TITLE
[Bug] Wrong Game File Download

### ISSUE THREAD

**Issue by ArthurLobopro** [Heroic-Games-Launcher/HeroicGamesLauncher#3762]
### Describe the bug

Epic Games is giving this week the game Dragon Age: Inquisition – Game of the Year Edition, but the launcher can't install the game because the launcher is downloading the wrong installer file.

### Add logs

```text
(09:26:24) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(09:26:24) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(09:26:24) INFO:    [Connection]:       Connectivity: check-online
(09:26:24) INFO:    [Connection]:       Pinging external endpoints
(09:26:24) INFO:    [Gog]:              Checking for existing gog manifests
(09:26:24) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(09:26:24) WARNING: [Backend]:          Protocol already registered.
(09:26:24) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/arthur/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(09:26:24) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/arthur/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/arthur/.config/heroic/gog_store/auth.json --version
(09:26:24) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/arthur/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(09:26:24) INFO:    [Connection]:       Connectivity: online
(09:26:24) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/arthur/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/arthur/.config/heroic/gog_store/auth.json auth
(09:26:24) INFO:    [Gog]:              Checking if login is valid
(09:26:24) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/arthur/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/arthur/.config/heroic/gog_store/auth.json auth
(09:26:25) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(09:26:25) INFO:    [Backend]:          
System Information:
CPU: 4x Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
Memory: 16.73 GB (used: 5.9 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GK208B [GeForce GT 710]
    IDs: D=128b V=10de SD=8c93 SV=1462
    Driver: nvidia
OS: BigLinux based in Manjaro Linux 6.1.90-1-MANJARO (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(09:26:25) INFO:    [Frontend]:         Refreshing undefined Library
(09:26:25) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(09:26:25) INFO:    [Legendary]:        Refreshing library...
(09:26:25) INFO:    [Legendary]:        Refreshing Epic Games...
(09:26:25) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/arthur/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/arthur/.config/heroic/gog_store/auth.json auth
(09:26:25) INFO:    [Backend]:          Frontend Ready
(09:26:25) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/arthur/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(09:26:25) INFO:    [Backend]:          Checking for new Heroic Updates
(09:26:26) INFO:    [Gog]:              Getting GOG library
(09:26:26) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/arthur/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/arthur/.config/heroic/gog_store/auth.json auth
(09:26:26) INFO:    [Backend]:          Checking for current version changelog
(09:26:26) INFO:    [Gog]:              Saved username to config file
(09:26:27) INFO:    [DXVKInstaller]:    The GPU(s) in this system only support Vulkan 1.1/1.2, falling back to VKD3D 2.6
(09:26:27) INFO:    [DXVKInstaller]:    The GPU(s) in this system only support Vulkan 1.1/1.2, falling back to DXVK 1.10.3
(09:26:27) INFO:    [Winetricks]:       Downloading Winetricks
(09:26:28) INFO:    [Legendary]:        Game list updated, got 96 games & DLCs
(09:26:28) INFO:    [Gog]:              Saved games data
(09:26:28) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(09:26:28) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/arthur/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/arthur/.config/heroic/gog_store/auth.json auth
(09:26:29) INFO:    [WineDownloader]:   Updating wine versions info
(09:26:29) INFO:    [WineDownloader]:   Fetching upstream information...
(09:26:30) INFO:    [Gog]:              Found 0 game(s) to update
(09:26:30) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/arthur/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(09:26:30) INFO:    [Backend]:          Starting the Download Queue
(09:26:30) INFO:    [WineDownloader]:   wine versions updated
(09:26:32) INFO:    [Legendary]:        Found 0 games to update
(09:26:48) INFO:    [Legendary]:        Getting more details with 'legendary info'
(09:26:48) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/arthur/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info verdi --json --platform Windows
(09:32:10) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dragon Age Inquisition – Edição Game of the Year
(09:32:10) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dragon Age Inquisition – Edição Game of the Year
(09:32:10) DEBUG:   [Legendary]:        Using cached install info
(09:32:10) DEBUG:   [Legendary]:        Using cached install info
(09:32:10) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(09:32:10) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(09:32:10) ERROR:   [Legendary]:        Error Getting Info from Epic API
(09:32:11) DEBUG:   [Legendary]:        Using cached install info
(09:32:13) INFO:    [Backend]:          Writing config for verdi
(09:32:13) DEBUG:   [Legendary]:        Using cached install info
(09:32:13) INFO:    [DownloadManager]:  Dragon Age: Inquisition – Edição Game of the Year  was added to the download queue.
(09:32:13) INFO:    [Backend]:          Preventing machine to sleep
(09:32:13) DEBUG:   [Legendary]:        Using cached install info
(09:32:13) DEBUG:   [Legendary]:        Using cached install info
(09:32:13) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(09:32:13) DEBUG:   [Legendary]:        Using cached install info
(09:32:13) INFO:    [Legendary]:        Installing verdi: LEGENDARY_CONFIG_PATH=/home/arthur/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary install verdi --platform Windows --base-path /home/arthur/Games/Heroic --skip-dlcs -y --skip-sdl
(09:32:13) DEBUG:   [Legendary]:        Logging to file "/home/arthur/.config/heroic/GamesConfig/verdi.log"
(09:32:13) DEBUG:   [Legendary]:        Using cached install info
(09:32:13) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(09:32:13) ERROR:   [Legendary]:        Error Getting Info from Epic API
(09:32:13) DEBUG:   [Legendary]:        Using cached install info
(09:32:13) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(09:32:13) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(09:32:13) ERROR:   [Legendary]:        Error Getting Info from Epic API
(09:32:13) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://raw.githubusercontent.com/Heroic-Games-Launcher/known-fixes/main/epic/verdi-epic.json. 
Error: Error: Request failed with status code 404
(09:32:14) INFO:    [Backend]:          Adding shortcuts for Dragon Age: Inquisition – Edição Game of the Year
(09:32:14) INFO:    [DownloadManager]:  Finished Installation of verdi
(09:32:14) INFO:    [DownloadManager]:  verdi added to download manager finished.
(09:32:14) INFO:    [DownloadManager]:  verdi removed from download manager.
(09:32:14) INFO:    [Frontend]:         Refreshing legendary Library
(09:32:14) INFO:    [Legendary]:        Refreshing library...
(09:32:14) INFO:    [Legendary]:        Refreshing Epic Games...
(09:32:14) DEBUG:   [Legendary]:        Using cached install info
(09:32:14) INFO:    [Backend]:          Shortcut saved on /home/arthur/.local/share/applications/Dragon Age Inquisition – Edição Game of the Year.desktop
(09:32:14) DEBUG:   [Legendary]:        Using cached install info
(09:32:14) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/arthur/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(09:32:15) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(09:32:15) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(09:32:15) ERROR:   [Legendary]:        Error Getting Info from Epic API
(09:32:17) INFO:    [Legendary]:        Game list updated, got 96 games & DLCs
(09:32:17) DEBUG:   [Legendary]:        Using cached install info
(09:32:17) DEBUG:   [Legendary]:        Using cached install info
(09:32:17) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(09:32:17) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(09:32:17) ERROR:   [Legendary]:        Error Getting Info from Epic API
```

### Steps to reproduce

1. Get the free game on (expires on 05/23/2024)
2. Try to install by Heroic Games Launcher
3. See the error

### Expected behavior

The game should download the right files and install

### Screenshots

The Launcher Shows a 1kb file download:

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/64273139/1fcb142a-283a-4846-93b9-f155c3bd6c68)

And Shows the game is installed, but obviously it isn't

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/64273139/b5ba7d5c-21f3-4efb-886a-27a805a9e946)

### Heroic Version

Latest Stable

### System Information

- OS Big Linux (Manjaro based)

**Comment by bfalese** [comment]
same here
`(14:42:29) DEBUG:   [Legendary]:        Using cached install info

(14:42:29) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/bernardo/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party

(14:42:29) ERROR:   [Legendary]:        Error: Request failed with status code 403

    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)

    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)

    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)

    at IncomingMessage.emit (node:events:526:35)

    at endReadableNT (node:internal/streams/readable:1408:12)

    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

(14:42:30) ERROR:   [Legendary]:        Error: Request failed with status code 403

    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)

    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)

    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)

    at IncomingMessage.emit (node:events:526:35)

    at endReadableNT (node:internal/streams/readable:1408:12)

    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

(14:42:30) ERROR:   [Legendary]:        Error Getting Info from Epic API

(14:42:32) INFO:    [Legendary]:        Game list updated, got 199 games & DLCs

(14:42:32) DEBUG:   [Legendary]:        Using cached install info

(14:42:32) DEBUG:   [Legendary]:        Using cached install info

(14:42:32) ERROR:   [Legendary]:        Error: Request failed with status code 403

    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)

    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)

    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)

    at IncomingMessage.emit (node:events:526:35)

    at endReadableNT (node:internal/streams/readable:1408:12)

    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

(14:42:33) ERROR:   [Legendary]:        Error: Request failed with status code 403

    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)

    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)

    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)

    at IncomingMessage.emit (node:events:526:35)

    at endReadableNT (node:internal/streams/readable:1408:12)

    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

(14:42:33) ERROR:   [Legendary]:        Error Getting Info from Epic API`

**Comment by imLinguin** [comment]
This is EA game, they aren't supported yet #3763 aims to fix that

**Comment by arielj** [comment]
should work fine in the latest 2.15.0 release, closing
