### ISSUE TITLE
cannot connect to my account

### ISSUE THREAD

**Issue by Rux-Lsr** [Heroic-Games-Launcher/HeroicGamesLauncher#3766]
### Describe the bug

when trying to connect on Epic game account

### Add logs

```text
(22:28:30) INFO:    [Legendary]:        Legendary location: /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary
(22:28:30) INFO:    [Gog]:              GOGDL location: /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/gogdl
(22:28:30) INFO:    [Connection]:       Connectivity: check-online
(22:28:30) INFO:    [Connection]:       Pinging external endpoints
(22:28:30) ERROR:   [Backend]:          Error: spawn free EACCES
(22:28:30) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(22:28:31) WARNING: [Backend]:          Failed to register protocol with OS.
(22:28:31) INFO:    [Connection]:       Connectivity: online
(22:28:31) INFO:    [Backend]:          User Not Found, removing it from Store
(22:28:31) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(22:28:32) INFO:    [Backend]:          Frontend Ready
(22:28:32) INFO:    [Backend]:          Checking for new Heroic Updates
(22:28:33) INFO:    [Backend]:          Checking for current version changelog
(22:28:33) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(22:28:33) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(22:28:33) WARNING: [DXVKInstaller]:    No GPU with Vulkan 1.1 support found, VKD3D will not work
(22:28:33) WARNING: [DXVKInstaller]:    No GPU with Vulkan 1.1 support found, DXVK will not work
(22:28:33) INFO:    [Winetricks]:       Downloading Winetricks
(22:28:34) WARNING: [Winetricks]:       Error Downloading Winetricks Error: timeout of 1000ms exceeded
    at createError (/snap/heroic/357/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/snap/heroic/357/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:514:28)
    at Timeout.<anonymous> (/snap/heroic/357/resources/app.asar/node_modules/follow-redirects/index.js:179:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
(22:28:35) INFO:    [DXVKInstaller]:    Updating dxvk to: dxvk-2.3.1
(22:28:36) INFO:    [WineDownloader]:   Updating wine versions info
(22:28:36) INFO:    [WineDownloader]:   Fetching upstream information...
(22:28:37) INFO:    [Backend]:          Starting the Download Queue
(22:28:46) INFO:    [WineDownloader]:   wine versions updated
(22:29:03) ERROR:   [Backend]:          Error: spawn free EACCES
(22:29:05) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/doitsujin/dxvk/releases/download/v2.3.1/dxvk-2.3.1.tar.gz
(22:29:05) INFO:    [DXVKInstaller]:    Downloaded dxvk, extracting...
(22:29:05) INFO:    [Backend]:          Extracting /home/ruxlsr/snap/heroic/357/.config/heroic/tools/dxvk/dxvk-2.3.1.tar.gz to /home/ruxlsr/snap/heroic/357/.config/heroic/tools/dxvk/dxvk-2.3.1 using decompress
(22:29:05) INFO:    [DXVKInstaller]:    dxvk updated!
(22:35:26) INFO:    [Legendary]:        Logging in: /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(22:35:26) INFO:    [Frontend]:         Refreshing legendary Library
(22:35:26) INFO:    [Legendary]:        Refreshing library...
(22:35:26) ERROR:   [Backend]:          Error: spawn free EACCES
(22:35:45) INFO:    [Legendary]:        Logging in: /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(22:35:45) INFO:    [Frontend]:         Refreshing legendary Library
(22:35:45) INFO:    [Legendary]:        Refreshing library...
(22:35:45) ERROR:   [Backend]:          Error: spawn free EACCES
(22:36:10) INFO:    [Legendary]:        Logging in: /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(22:36:10) INFO:    [Frontend]:         Refreshing legendary Library
(22:36:10) INFO:    [Legendary]:        Refreshing library...
(22:36:11) ERROR:   [Backend]:          Error: spawn free EACCES
(22:40:34) INFO:    [Legendary]:        Logging in: /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(22:40:34) INFO:    [Frontend]:         Refreshing legendary Library
(22:40:34) INFO:    [Legendary]:        Refreshing library...
(22:40:34) ERROR:   [Backend]:          Error: spawn free EACCES
(22:42:31) INFO:    [Backend]:          Changing Language to: en
```

### Steps to reproduce

1. Go to 'Log in'
2. Click on 'epic game login'

### Expected behavior

I want to connect to my epic game account

### Screenshots

![Screenshot from 2024-05-18 22-40-50](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/146411759/110a93c2-4f58-49bf-80c0-ea7b102a3272)

### Heroic Version

Latest Stable

### System Information

- OS ["Ubuntu"]:

**Comment by arielj** [comment]
do not use the Snap package from the ubuntu store, it's broken

use either .deb, or flatpak, or appImage

**Comment by Rux-Lsr** [comment]
👌
