### ISSUE TITLE
[2.14.1] Witcher3/gogdl update failure + Heck of a memory leak

### ISSUE THREAD

**Issue by Mistakesos** [Heroic-Games-Launcher/HeroicGamesLauncher#3778]
### Describe the bug

That problem(#3617) appeared again, but this time it was Witcher3, with a serious memory leak until the memory was fully occupied.
The reproduction process is the same as # 3617, and you can directly refer to the reproduction process of #3617 。

### Add logs

```text
[2024/5/22 22:40:08] GOGDL_CONFIG_PATH=/home/nobody/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/nobody/.config/heroic/gog_store/auth.json --version
1.0.1
[2024/5/22 22:40:09] GOGDL_CONFIG_PATH=/home/nobody/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/nobody/.config/heroic/gog_store/auth.json auth
[2024/5/22 22:40:09] GOGDL_CONFIG_PATH=/home/nobody/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/nobody/.config/heroic/gog_store/auth.json auth
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1716387844.4952009}
[2024/5/22 22:40:12] GOGDL_CONFIG_PATH=/home/nobody/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/nobody/.config/heroic/gog_store/auth.json auth
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1716387844.4952009}
[2024/5/22 22:40:13] GOGDL_CONFIG_PATH=/home/nobody/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/nobody/.config/heroic/gog_store/auth.json auth
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1716387844.4952009}
[2024/5/22 22:40:13] GOGDL_CONFIG_PATH=/home/nobody/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/nobody/.config/heroic/gog_store/auth.json update 1495134320 --platform windows --path "/home/nobody/Games/Heroic/The Witcher 3 Wild Hunt GOTY" --support /home/nobody/.config/heroic/gogdlConfig/heroic_gogdl/gog-support/1495134320 --skip-dlcs --lang zh-Hans
[GENERIC DOWNLOAD_MANAGER] INFO: Depot version: 2
[V2] INFO: Initialized V2 Download Manager
[V2] INFO: Creating Manifest instance from existing manifest
[V2] INFO: Deleted: 0 New: 0 Changed: 406
[API] INFO: Getting Dependencies repository
[TASK_EXEC] INFO: Attempting to continue the download
(2.9850348150357604, 'GB') 3205156727
(8.229460813105106, 'GB') 8836316264
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:35, ETA: 12073:53:46
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:36, ETA: 12109:55:56
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:37, ETA: 12145:58:13
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:38, ETA: 12182:00:14
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:39, ETA: 12218:02:28
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:40, ETA: 12254:04:47
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:41, ETA: 12290:07:09
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:42, ETA: 12326:09:33
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:43, ETA: 12362:11:52
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:44, ETA: 12398:14:19
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:45, ETA: 12434:16:28
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:46, ETA: 12470:18:49
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:47, ETA: 12506:21:14
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:48, ETA: 12542:23:40
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:49, ETA: 12578:26:23
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:50, ETA: 12614:29:44
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:51, ETA: 12650:32:09
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:52, ETA: 12686:34:41
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[2024/5/22 22:46:24] GOGDL_CONFIG_PATH=/home/nobody/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/nobody/.config/heroic/gog_store/auth.json auth
[PROGRESS] INFO: = Progress: 0.00 464455/60162081906, Running for: 00:05:53, ETA: 12715:25:54
[PROGRESS] INFO: = Downloaded: 1.45 MiB, Written: 0.44 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1716387844.4952009}
[2024/5/22 22:46:24] GOGDL_CONFIG_PATH=/home/nobody/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/nobody/.config/heroic/gog_store/auth.json auth
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1716387844.4952009}
[2024/5/22 22:46:29] GOGDL_CONFIG_PATH=/home/nobody/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/nobody/.config/heroic/gog_store/auth.json auth
{"access_token":"<redacted>","expires_in":3600,"token_type":"bearer","scope":"","session_id":"<redacted>","refresh_token":"<redacted>","user_id":"<redacted>","loginTime":1716387844.4952009}
```

### Steps to reproduce

Reference #3617

### Expected behavior

Reference #3617 

### Heroic Version

Latest Stable

### System Information

CPU: 16x Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
Memory: 16.63 GB (used: 4.55 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation TU106M [GeForce RTX 2060 Mobile]
    IDs: D=1f15 V=10de SD=3fa9 SV=17aa
    Driver: nvidia
  GPU 1:
    Name: Intel Corporation CometLake-H GT2 [UHD Graphics]
    IDs: D=9bc4 V=8086 SD=3fa9 SV=17aa
    Driver: i915
OS: Arch Linux 6.9.1-arch1-1 (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

**Comment by italoghost** [comment]
I have the same issue!

**Comment by italoghost** [comment]
Here is a hacky workaround: I was able to update by canceling the update, killing all gogdl entries and asking Heroic to repair. It actually downloaded the update and installed it.

**Comment by teriame** [comment]
I have the same issue; it even happens when starting a different game from Steam when using it on a Steam Deck. Draining memory in the background while playing another game.

**Comment by Nocifer** [comment]
Exact same issue with the recent update of Disco Elysium. "Hacky workaround" only worked insofar as it allowed Heroic to restart the update from scratch, but the process failed again at pretty much the exact same point as before. The log has this to say:

```
[GENERIC DOWNLOAD_MANAGER] INFO: Depot version: 2
[V2] INFO: Initialized V2 Download Manager
[V2] INFO: Creating Manifest instance from existing manifest
[V2] INFO: Deleted: 1 New: 1 Changed: 166
[API] INFO: Getting Dependencies repository
(203.75713729858398, 'MB') 213654844
(196.14975833892822, 'MB') 205677929
[PROGRESS] INFO: = Progress: 0.00 0/651287259, Running for: 00:00:00, ETA: 00:00:00
[PROGRESS] INFO: = Downloaded: 0.00 MiB, Written: 0.00 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 0/651287259, Running for: 00:00:01, ETA: 00:00:00
[PROGRESS] INFO: = Downloaded: 0.40 MiB, Written: 0.00 MiB
[PROGRESS] INFO:  + Download	- 0.02 MiB/s (raw) / 0.04 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 0/651287259, Running for: 00:00:02, ETA: 00:00:00
[PROGRESS] INFO: = Downloaded: 1.04 MiB, Written: 0.00 MiB
[PROGRESS] INFO:  + Download	- 0.04 MiB/s (raw) / 0.09 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 0/651287259, Running for: 00:00:03, ETA: 00:00:00
[PROGRESS] INFO: = Downloaded: 1.46 MiB, Written: 0.00 MiB
[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.01 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 0/651287259, Running for: 00:00:04, ETA: 00:00:00
[PROGRESS] INFO: = Downloaded: 14.21 MiB, Written: 0.00 MiB
[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.02 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 0/651287259, Running for: 00:00:05, ETA: 00:00:00
[PROGRESS] INFO: = Downloaded: 22.84 MiB, Written: 0.00 MiB
[PROGRESS] INFO:  + Download	- 0.27 MiB/s (raw) / 0.50 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 0.00 0/651287259, Running for: 00:00:06, ETA: 00:00:00
[PROGRESS] INFO: = Downloaded: 22.84 MiB, Written: 0.00 MiB
[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 1.28 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 6.44 41943040/651287259, Running for: 00:00:07, ETA: 00:01:54
[PROGRESS] INFO: = Downloaded: 61.53 MiB, Written: 40.00 MiB
[PROGRESS] INFO:  + Download	- 6.94 MiB/s (raw) / 12.55 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 23.99 MiB/s (write) / 0.00 MiB/s (read)
[TASK_EXEC] WARNING: No checksum for patched file, unable to push to resume file GalaxyCSharpGlue.dll
[PROGRESS] INFO: = Progress: 19.26 125442519/651287259, Running for: 00:00:08, ETA: 00:00:37
[PROGRESS] INFO: = Downloaded: 76.96 MiB, Written: 119.63 MiB
[PROGRESS] INFO:  + Download	- 64.53 MiB/s (raw) / 95.47 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 43.85 MiB/s (write) / 0.03 MiB/s (read)
[PROGRESS] INFO: = Progress: 20.40 132840665/651287259, Running for: 00:00:10, ETA: 00:00:40
[PROGRESS] INFO: = Downloaded: 81.24 MiB, Written: 126.69 MiB
[PROGRESS] INFO:  + Download	- 2.89 MiB/s (raw) / 6.44 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 26.33 171454514/651287259, Running for: 00:00:11, ETA: 00:00:31
[PROGRESS] INFO: = Downloaded: 81.44 MiB, Written: 163.51 MiB
[PROGRESS] INFO:  + Download	- 7.81 MiB/s (raw) / 7.96 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 54.16 352754599/651287259, Running for: 00:00:12, ETA: 00:00:10
[PROGRESS] INFO: = Downloaded: 85.89 MiB, Written: 336.41 MiB
[PROGRESS] INFO:  + Download	- 10.42 MiB/s (raw) / 10.43 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 54.16 352754599/651287259, Running for: 00:00:13, ETA: 00:00:11
[PROGRESS] INFO: = Downloaded: 94.26 MiB, Written: 336.41 MiB
[PROGRESS] INFO:  + Download	- 11.32 MiB/s (raw) / 11.33 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 54.16 352754599/651287259, Running for: 00:00:14, ETA: 00:00:12
[PROGRESS] INFO: = Downloaded: 103.03 MiB, Written: 336.41 MiB
[PROGRESS] INFO:  + Download	- 11.37 MiB/s (raw) / 11.37 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 54.16 352754599/651287259, Running for: 00:00:15, ETA: 00:00:13
[PROGRESS] INFO: = Downloaded: 106.24 MiB, Written: 336.41 MiB
[PROGRESS] INFO:  + Download	- 9.73 MiB/s (raw) / 9.73 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 54.16 352754599/651287259, Running for: 00:00:16, ETA: 00:00:14
[PROGRESS] INFO: = Downloaded: 116.78 MiB, Written: 336.41 MiB
[PROGRESS] INFO:  + Download	- 11.48 MiB/s (raw) / 11.48 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 72.71 473550651/651287259, Running for: 00:00:17, ETA: 00:00:06
[PROGRESS] INFO: = Downloaded: 131.25 MiB, Written: 451.61 MiB
[PROGRESS] INFO:  + Download	- 10.33 MiB/s (raw) / 10.33 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 72.71 473550651/651287259, Running for: 00:00:18, ETA: 00:00:06
[PROGRESS] INFO: = Downloaded: 138.70 MiB, Written: 451.61 MiB
[PROGRESS] INFO:  + Download	- 11.91 MiB/s (raw) / 11.91 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[TASK_EXEC] CRITICAL: Task writer failed
[PROGRESS] INFO: = Progress: 76.82 500318659/651287259, Running for: 00:00:19, ETA: 00:00:05
[PROGRESS] INFO: = Downloaded: 165.34 MiB, Written: 477.14 MiB
[PROGRESS] INFO:  + Download	- 10.81 MiB/s (raw) / 10.81 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 76.82 500318659/651287259, Running for: 00:00:20, ETA: 00:00:06
[PROGRESS] INFO: = Downloaded: 169.10 MiB, Written: 477.14 MiB
[PROGRESS] INFO:  + Download	- 4.53 MiB/s (raw) / 4.53 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "multiprocessing/popen_fork.py", line 27, in poll
  File "gogdl/dl/managers/task_executor.py", line 463, in handle_sig
  File "gogdl/dl/managers/task_executor.py", line 524, in interrupt_shutdown
  File "multiprocessing/queues.py", line 135, in get_nowait
  File "multiprocessing/queues.py", line 100, in get
ValueError: Queue <multiprocessing.queues.Queue object at 0x70e5d5bdfd30> is closed
```

**Comment by Mistakesos** [comment]
> Here is a hacky workaround: I was able to update by canceling the update, killing all gogdl entries and asking Heroic to repair. It actually downloaded the update and installed it.

Sorry for taking so long to reply, I tried your method. It's unbelievable that this actually works. I can't imagine how long it took you to discover this method. You are such a helpful nice man who is willing to share your methods even after success. Thank you very much!

**Comment by finem4n** [comment]
Same issue with recent Slay the Princess update

**Comment by imLinguin** [comment]
Hey, sorry it took so long. I finally got arround to properly fix these issues.
The new algorithm uses xdelta3 library called through C module, which should be faster and more stable.

https://github.com/Heroic-Games-Launcher/heroic-gogdl/pull/65
