### ISSUE TITLE
GOG Library not available to download any game

### ISSUE THREAD

**Issue by salvirosales99** [Heroic-Games-Launcher/HeroicGamesLauncher#3784]
### Describe the bug

Once you log into GOG,the games from GOG are not available to download. Two weeks ago was a couple of games,now its every GOG game

### Add logs

```text
(00:29:40) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(00:29:40) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(00:29:40) INFO:    [Connection]:       Connectivity: check-online
(00:29:40) INFO:    [Connection]:       Pinging external endpoints
(00:29:40) INFO:    [Gog]:              Checking for existing gog manifests
(00:29:40) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(00:29:40) WARNING: [Backend]:          Protocol already registered.
(00:29:40) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/salvi/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(00:29:40) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/salvi/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/salvi/.config/heroic/gog_store/auth.json --version
(00:29:40) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/salvi/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(00:29:40) INFO:    [Backend]:          
System Information:
CPU: 32x 13th Gen Intel(R) Core(TM) i9-13950HX
Memory: 33.33 GB (used: 4.03 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation AD107M [GeForce RTX 4060 Max-Q / Mobile]
    IDs: D=28a0 V=10de SD=13cc SV=1462
    Driver: nvidia
  GPU 1:
    Name: Intel Corporation Raptor Lake-S UHD Graphics
    IDs: D=a788 V=8086 SD=13cc SV=1462
    Driver: i915
OS: EndeavourOS 6.9.1-zen1-2-zen (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(00:29:40) INFO:    [Frontend]:         Refreshing undefined Library
(00:29:40) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(00:29:40) INFO:    [Legendary]:        Refreshing library...
(00:29:40) INFO:    [Legendary]:        Refreshing Epic Games...
(00:29:40) INFO:    [Backend]:          Frontend Ready
(00:29:40) INFO:    [Backend]:          Checking for new Heroic Updates
(00:29:40) INFO:    [Backend]:          Checking for current version changelog
(00:29:41) INFO:    [Connection]:       Connectivity: online
(00:29:41) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/salvi/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/salvi/.config/heroic/gog_store/auth.json auth
(00:29:41) INFO:    [Gog]:              Checking if login is valid
(00:29:41) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/salvi/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/salvi/.config/heroic/gog_store/auth.json auth
(00:29:41) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(00:29:42) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/salvi/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(00:29:43) INFO:    [Winetricks]:       Downloading Winetricks
(00:29:45) INFO:    [Gog]:              Saved username to config file
(00:29:45) INFO:    [WineDownloader]:   Updating wine versions info
(00:29:45) INFO:    [WineDownloader]:   Fetching upstream information...
(00:29:45) INFO:    [Backend]:          Starting the Download Queue
(00:29:47) INFO:    [WineDownloader]:   wine versions updated
(00:29:47) INFO:    [Legendary]:        Game list updated, got 147 games & DLCs
(00:29:47) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(00:29:47) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/salvi/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/salvi/.config/heroic/gog_store/auth.json auth
(00:29:47) INFO:    [Gog]:              Found 0 game(s) to update
(00:29:48) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/salvi/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(00:29:52) WARNING: [Legendary]:        Failed to parse games from /home/salvi/.config/heroic/legendaryConfig/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/home/salvi/.config/heroic/legendaryConfig/legendary/installed.json'
    at Object.readFileUtf8 (node:internal/fs/sync:25:18)
    at Object.readFileSync (node:fs:441:19)
    at t.readFileSync (node:electron/js2c/node_init:2:9771)
    at Module.listUpdateableGames (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:114:4090)
    at async /opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:235:3193
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)
(00:29:52) INFO:    [Legendary]:        Found 0 games to update
(00:32:43) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/salvi/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(00:32:43) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/salvi/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/salvi/.config/heroic/gog_store/auth.json --version
(00:32:43) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/salvi/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
```

### Steps to reproduce

1. Open Heroic Launcher
2. Log Into GOG Account
3. Open Library
4. All GOG-related are marked as "not installable"

### Expected behavior

Most of the games (if not all of them) are available for download

### Screenshots

![imagen](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/50347848/36e545cc-5275-4deb-9060-403821d22490)

### Heroic Version

Latest Stable

### System Information

CPU: 32x 13th Gen Intel(R) Core(TM) i9-13950HX
Memory: 33.33 GB (used: 5.65 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation AD107M [GeForce RTX 4060 Max-Q / Mobile]
    IDs: D=28a0 V=10de SD=13cc SV=1462
    Driver: nvidia
  GPU 1:
    Name: Intel Corporation Raptor Lake-S UHD Graphics
    IDs: D=a788 V=8086 SD=13cc SV=1462
    Driver: i915
OS: EndeavourOS 6.9.1-zen1-2-zen (linux)

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

### Additional information

- AUR version of the software
- Only happens with GOG games,all of the games are available (not counting Fortnite and Star Wars Battlefront)

**Comment by hardpenguin** [comment]
I can confirm it, this is the same issue that was reported few times already:

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3636

**Comment by arielj** [comment]
it will be fixed in the next release, a PR was already merged in the main branch

you can download a build from https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/9237161855 in the mean time
