### ISSUE TITLE
Can't log in with epic games

### ISSUE THREAD

**Issue by Bertow** [Heroic-Games-Launcher/HeroicGamesLauncher#3785]
### Describe the bug

When I try to log in, I get an error. Even when I try with the alternative connection method. With the direct log in I get : A 

uncaught exception occured:
Error: spawn free EACCES
Report the exception on our Github repository.

With the alternative method I get : 

An error has occurred! Try to Logout and Login on your Epic account.
Traceback (most recent call last):
File "legendary/cli.py", line 3149, in <module>
File "legendary/cli.py", line 3033, in main
File "legendary/cli.py", line 48, in setup_threaded_logging
File "multiprocessing/context.py", line 103, in Queue
File "multiprocessing/queues.py", line 43, in __init__
File "multiprocessing/context.py", line 68, in Lock
File "multiprocessing/synchronize.py", line 162, in __init__
File "multiprocessing/synchronize.py", line 57, in __init__PermissionError: [Errno 13] Permission denied
[9979] Failed to execute script 'cli' due to unhandled exception!

I'm running it a snap if it can help you.

### Add logs

```text

[26/05/2024 15:29:33] /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
Traceback (most recent call last):
  File "legendary/cli.py", line 3149, in <module>
  File "legendary/cli.py", line 3033, in main
  File "legendary/cli.py", line 48, in setup_threaded_logging
  File "multiprocessing/context.py", line 103, in Queue
  File "multiprocessing/queues.py", line 43, in __init__
  File "multiprocessing/context.py", line 68, in Lock
  File "multiprocessing/synchronize.py", line 162, in __init__
  File "multiprocessing/synchronize.py", line 57, in __init__
PermissionError: [Errno 13] Permission denied
[8838] Failed to execute script 'cli' due to unhandled exception!
[26/05/2024 15:31:20] /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
Traceback (most recent call last):
  File "legendary/cli.py", line 3149, in <module>
  File "legendary/cli.py", line 3033, in main
  File "legendary/cli.py", line 48, in setup_threaded_logging
  File "multiprocessing/context.py", line 103, in Queue
  File "multiprocessing/queues.py", line 43, in __init__
  File "multiprocessing/context.py", line 68, in Lock
  File "multiprocessing/synchronize.py", line 162, in __init__
  File "multiprocessing/synchronize.py", line 57, in __init__
PermissionError: [Errno 13] Permission denied
[9690] Failed to execute script 'cli' due to unhandled exception!
[26/05/2024 15:31:44] /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
Traceback (most recent call last):
  File "legendary/cli.py", line 3149, in <module>
  File "legendary/cli.py", line 3033, in main
  File "legendary/cli.py", line 48, in setup_threaded_logging
  File "multiprocessing/context.py", line 103, in Queue
  File "multiprocessing/queues.py", line 43, in __init__
  File "multiprocessing/context.py", line 68, in Lock
  File "multiprocessing/synchronize.py", line 162, in __init__
  File "multiprocessing/synchronize.py", line 57, in __init__
PermissionError: [Errno 13] Permission denied
[9906] Failed to execute script 'cli' due to unhandled exception!
[26/05/2024 15:32:37] /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
Traceback (most recent call last):
  File "legendary/cli.py", line 3149, in <module>
  File "legendary/cli.py", line 3033, in main
  File "legendary/cli.py", line 48, in setup_threaded_logging
  File "multiprocessing/context.py", line 103, in Queue
  File "multiprocessing/queues.py", line 43, in __init__
  File "multiprocessing/context.py", line 68, in Lock
  File "multiprocessing/synchronize.py", line 162, in __init__
  File "multiprocessing/synchronize.py", line 57, in __init__
PermissionError: [Errno 13] Permission denied
[9979] Failed to execute script 'cli' due to unhandled exception!
[26/05/2024 15:38:52] /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
Traceback (most recent call last):
  File "legendary/cli.py", line 3149, in <module>
  File "legendary/cli.py", line 3033, in main
  File "legendary/cli.py", line 48, in setup_threaded_logging
  File "multiprocessing/context.py", line 103, in Queue
  File "multiprocessing/queues.py", line 43, in __init__
  File "multiprocessing/context.py", line 68, in Lock
  File "multiprocessing/synchronize.py", line 162, in __init__
  File "multiprocessing/synchronize.py", line 57, in __init__
PermissionError: [Errno 13] Permission denied
[10291] Failed to execute script 'cli' due to unhandled exception!

(15:28:47) INFO:    [Legendary]:        Legendary location: /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary
(15:28:47) INFO:    [Gog]:              GOGDL location: /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:28:47) INFO:    [Connection]:       Connectivity: check-online
(15:28:47) INFO:    [Connection]:       Pinging external endpoints
(15:28:47) ERROR:   [Backend]:          Error: spawn free EACCES
(15:28:47) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(15:28:47) WARNING: [Backend]:          Failed to register protocol with OS.
(15:28:47) INFO:    [Connection]:       Connectivity: online
(15:28:47) INFO:    [Backend]:          User Not Found, removing it from Store
(15:28:47) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(15:28:47) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(15:28:47) INFO:    [Backend]:          Frontend Ready
(15:28:48) INFO:    [Backend]:          Checking for new Heroic Updates
(15:28:48) INFO:    [Backend]:          Checking for current version changelog
(15:28:49) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(15:28:49) WARNING: [DXVKInstaller]:    No GPU with Vulkan 1.1 support found, VKD3D will not work
(15:28:49) WARNING: [DXVKInstaller]:    No GPU with Vulkan 1.1 support found, DXVK will not work
(15:28:49) INFO:    [Winetricks]:       Downloading Winetricks
(15:28:52) INFO:    [WineDownloader]:   Updating wine versions info
(15:28:52) INFO:    [WineDownloader]:   Fetching upstream information...
(15:28:52) INFO:    [Backend]:          Starting the Download Queue
(15:28:53) INFO:    [WineDownloader]:   wine versions updated
(15:29:14) INFO:    [WineDownloader]:   Removed wine version Wine-GE-Proton8-26 succesfully.
(15:29:20) INFO:    [WineDownloader]:   Start installation of wine version Wine-GE-Proton8-26
(15:29:22) INFO:    [Backend]:          Downloaded: 24.44 MB / 222.76 MB  @16.05 MB/s (10.97%)
(15:29:23) INFO:    [Backend]:          Downloaded: 63.75 MB / 222.76 MB  @33.03 MB/s (28.62%)
(15:29:24) ERROR:   [Backend]:          Error: spawn free EACCES
(15:29:25) INFO:    [Backend]:          Downloaded: 108.69 MB / 222.76 MB  @31.1 MB/s (48.79%)
(15:29:26) INFO:    [Backend]:          Downloaded: 185.56 MB / 222.76 MB  @69.32 MB/s (83.30%)
(15:29:27) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-26/wine-lutris-GE-Proton8-26-x86_64.tar.xz
(15:29:28) INFO:    [Backend]:          Extracting /home/calixte/snap/heroic/357/.config/heroic/tools/wine/wine-lutris-GE-Proton8-26-x86_64.tar.xz to /home/calixte/snap/heroic/357/.config/heroic/tools/wine/Wine-GE-Proton8-26 using decompress
(15:29:33) INFO:    [Legendary]:        Logging in: /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(15:29:34) INFO:    [Frontend]:         Refreshing legendary Library
(15:29:34) INFO:    [Legendary]:        Refreshing library...
(15:29:34) ERROR:   [Backend]:          Error: spawn free EACCES
(15:30:26) INFO:    [WineDownloader]:   Finished installation of wine version Wine-GE-Proton8-26
(15:31:20) INFO:    [Frontend]:         Called Epic Login
(15:31:20) INFO:    [Legendary]:        Logging in: /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(15:31:21) INFO:    [Frontend]:         Refreshing legendary Library
(15:31:21) INFO:    [Legendary]:        Refreshing library...
(15:31:30) ERROR:   [Backend]:          Error: spawn free EACCES
(15:31:44) INFO:    [Frontend]:         Called Epic Login
(15:31:44) INFO:    [Legendary]:        Logging in: /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(15:31:44) INFO:    [Frontend]:         Refreshing legendary Library
(15:31:44) INFO:    [Legendary]:        Refreshing library...
(15:32:37) INFO:    [Frontend]:         Called Epic Login
(15:32:37) INFO:    [Legendary]:        Logging in: /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(15:32:37) INFO:    [Frontend]:         Refreshing legendary Library
(15:32:37) INFO:    [Legendary]:        Refreshing library...
(15:36:02) INFO:    [Backend]:          Heroic: Setting autoUpdateGames to true (previous value: false)
(15:37:11) ERROR:   [Backend]:          Error: spawn free EACCES
(15:38:52) INFO:    [Frontend]:         Called Epic Login
(15:38:52) INFO:    [Legendary]:        Logging in: /snap/heroic/357/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(15:38:52) INFO:    [Frontend]:         Refreshing legendary Library
(15:38:52) INFO:    [Legendary]:        Refreshing library...
(15:40:14) ERROR:   [Backend]:          Error: spawn free EACCES
(15:40:17) INFO:    [Backend]:          Changing Language to: en
```

### Steps to reproduce

1. Click to log in
2. Try to log in
3. Maybe get the error

### Expected behavior

1. Click to log in
2. Log in

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/170870355/a8bc67fb-c8c7-4a2f-8269-db12985761fd)
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/170870355/f3bf5f64-9f18-472b-9159-f7a7ac121721)

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: 22.04

**Comment by arielj** [comment]
Don't use the snap package from the Ubuntu store, it's broken.

Use flatpak, or .deb, or AppImage, that will make the error go away
