### ISSUE TITLE
Getting Error When trying to Log into GOG on M1 Mac mini macOS Sonoma

### ISSUE THREAD

**Issue by BilingualAtom97** [Heroic-Games-Launcher/HeroicGamesLauncher#3811]
### Describe the bug

Can't Log into GOG on macOS, with an M1 chip. Tried the command for the terminal that is recommended on the download page, but it didn't do anything. When I very first launched Heroic, I got some error that I don't have saved, that said Legendary wasn't working. Then when I try to log into GOG, this error pops up: (See Log Below)

### Add logs

```text
Error running command "GOGDL_CONFIG_PATH="/Users/roryhankel/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/roryhankel/Library/Application Support/heroic/gog_store/auth.json" auth --code <redacted>": Error: spawn Unknown system error -86
at ChildProcess.spawn (node:internal/child_process:421:11)
at Object.spawn (node:child_process:776:9)
at /Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.159a68a5.js:110:246
at new Promise (<anonymous>)
at callRunner (/Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.159a68a5.js:110:204)
at runRunnerCommand$3 (/Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.159a68a5.js:27:38874)
at GOGUser.login (/Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.159a68a5.js:3:132)
at /Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.159a68a5.js:235:5874
at WebContents.<anonymous> (node:electron/js2c/browser_init:2:79420)
at WebContents.emit (node:events:514:28)
```

### Steps to reproduce

1. Go to 'GOG Login'
2. Type in 'Username and Password'

### Expected behavior

I thought I'd be able to log into my GOG account and sync my games in order to play them on my M1 Mac, like how I do on my Linux.

### Screenshots

Not needed, just the Log.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: macOS Sonoma, M1 Mac mini, 2020. 8GB RAM.

### Additional information

Nada.

**Comment by CommandMC** [comment]
Install Rosetta by running `softwareupdate --install-rosetta` inside the Terminal
