### ISSUE TITLE
GOG: Darkest Dungeon fails to install on Linux

### ISSUE THREAD

**Issue by LoneFenris** [Heroic-Games-Launcher/HeroicGamesLauncher#3812]
### Describe the bug

There seems to be an issue with the install for Darkest Dungeon from GOG on Linux. Errors shown in log below include:
`
(08:15:02) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://raw.githubusercontent.com/Heroic-Games-Launcher/known-fixes/main/gog/1450711444-gog.json.`

`(08:15:09) ERROR:   [DownloadManager]:  Installation of 1450711444 failed with: Error: ENOENT: no such file or directory, lstat '/mnt/wally/GOGLinux/Darkest Dungeon'`

and

```
Traceback (most recent call last):

  File "gogdl/cli.py", line 67, in <module>

  File "gogdl/cli.py", line 62, in main

  File "gogdl/dl/managers/manager.py", line 67, in download

  File "gogdl/dl/managers/linux.py", line 178, in download

AttributeError: 'InstallerHandler' object has no attribute 'central_directory'

[225] Failed to execute script 'cli' due to unhandled exception!
```

### Add logs

```text
Heroic:

(08:15:02) INFO:    [DownloadManager]:  Darkest Dungeon®  was added to the download queue.

(08:15:02) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/lonefenris/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/lonefenris/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth

(08:15:02) INFO:    [Backend]:          Preventing machine to sleep

(08:15:02) INFO:    [Gog]:              Got install info from cache for 1450711444 on linux platform

(08:15:02) INFO:    [Gog]:              Got install info from cache for 1450711444 on linux platform

(08:15:02) INFO:    [Gog]:              Got install info from cache for 1450711444 on linux platform

(08:15:02) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://raw.githubusercontent.com/Heroic-Games-Launcher/known-fixes/main/gog/1450711444-gog.json. 

Error: Error: Request failed with status code 404

(08:15:02) INFO:    [Gog]:              Installing 1450711444: GOGDL_CONFIG_PATH=/home/lonefenris/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/lonefenris/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json download 1450711444 --platform linux --path /mnt/wally/GOGLinux --support /home/lonefenris/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig/heroic_gogdl/gog-support/1450711444 --with-dlcs --dlcs 1405492047,1957260232,1128594953,1946270261 --lang en

(08:15:02) DEBUG:   [Gog]:              Logging to file "/home/lonefenris/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/1450711444.log"

(08:15:09) INFO:    [Gog]:              Got install info from cache for 1450711444 on linux platform

(08:15:09) ERROR:   [DownloadManager]:  Installation of 1450711444 failed with: Error: ENOENT: no such file or directory, lstat '/mnt/wally/GOGLinux/Darkest Dungeon'

(08:15:09) WARNING: [DownloadManager]:  Installation of 1450711444 failed!

(08:15:09) INFO:    [DownloadManager]:  1450711444 added to download manager finished.

(08:15:09) INFO:    [DownloadManager]:  1450711444 removed from download manager.

GOG:

[GENERIC DOWNLOAD_MANAGER] INFO: Platform is Linux, redirecting download to Linux Native installer manager

[LINUX] INFO: Initialized Linux Download Manager

[API] INFO: Getting info from products endpoint for id: 1450711444

Traceback (most recent call last):

  File "gogdl/cli.py", line 67, in <module>

  File "gogdl/cli.py", line 62, in main

  File "gogdl/dl/managers/manager.py", line 67, in download

  File "gogdl/dl/managers/linux.py", line 178, in download

AttributeError: 'InstallerHandler' object has no attribute 'central_directory'

[225] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Go to Library
2. Click on Darkest Dungeon
3. Confirm installation and wait
4. Installation fails

### Expected behavior

Installation completes successfully

### Heroic Version

Latest Stable (Flatpak)

### System Information

- Arch Linux

### Additional information

If the Darkest Dungeon folder is manually created by the user before installation, the install will report as successful, but without actually downloading or installing anything to the folder.

**Comment by LoneFenris** [comment]
Seems fixed in 2.15.1.
