### ISSUE TITLE
Heroic launcher requires exec access to /tmp to launch

### ISSUE THREAD

**Issue by jmccon115** [Heroic-Games-Launcher/HeroicGamesLauncher#3822]
### Describe the bug

After applying OS hardening measures to Ubuntu 22.04 desktop environment, attempting to install and launch the Heroic games launcher resulted in a "failed to map segment from shared object" error.  During investigation, I observed that it was attempting to execute content from the /tmp filsystem, which is configured with the noexec option per CIS compliance recommendations.  After temporarily setting the /tmp filesystem to allow execution, HGL was able to launch.  Can this application be updated so that exec is no longer required for /tmp?

### Add logs

```text
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.1YUL3D: failed to map segment from shared object
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1343:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at load (/opt/Heroic/resources/app.asar/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at /opt/Heroic/resources/app.asar/node_modules/lzma-native/index.js:9:39
```

### Steps to reproduce

1. Edit the /tmp mount point in the /etc/fstab file to include the noexec option.
2. Install and attempt to launch heroic

### Expected behavior

I expected HGL to launch with OS hardening measures applied.  The /tmp noexec limitation appears to be the only conflicting setting, but would recommend this dependency get removed.

### Heroic Version

Latest Stable

### System Information

Ubuntu 22.04
Gigabyte AX370-Gaming-CF
AMD Ryzen 7 1700X
16GiB CMK16GX4M2A2400C16 (Corsair VENGEANCE LPX 16GB (2 x 8GB) DDR4 DRAM 2400MHz C16 Memory Kit)
Sabrent Rocket 4.0 500GB NVMe SSD
AMD/ATI Radeon RX480

**Comment by nitroos-ai** [comment]
You need to type on console

`sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0`

I found the solution here https://github.com/electron/electron/issues/42510#issuecomment-2171583086
