### ISSUE TITLE
Cloud save path input field can't be manually edited still not fixed

### ISSUE THREAD

**Issue by lexxxel** [Heroic-Games-Launcher/HeroicGamesLauncher#3826]
### Describe the bug

please see #3719, its the same issue and PR #3718 did not fix it for me.

### Add logs

```text
(09:46:36) INFO:    [Legendary]:        Legendary location: /opt/heroic-2.14.1/resources/app.asar.unpacked/build/bin/linux/legendary
(09:46:36) INFO:    [Gog]:              GOGDL location: /opt/heroic-2.14.1/resources/app.asar.unpacked/build/bin/linux/gogdl
(09:46:36) INFO:    [Connection]:       Connectivity: check-online
(09:46:36) INFO:    [Connection]:       Pinging external endpoints
(09:46:37) INFO:    [Gog]:              Checking for existing gog manifests
(09:46:37) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(09:46:37) WARNING: [Backend]:          Failed to register protocol with OS.
(09:46:37) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/apit/.config/heroic/legendaryConfig/legendary /opt/heroic-2.14.1/resources/app.asar.unpacked/build/bin/linux/legendary --version
(09:46:37) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/apit/.config/heroic/gogdlConfig /opt/heroic-2.14.1/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/apit/.config/heroic/gog_store/auth.json --version
(09:46:37) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/apit/.config/heroic/nile_config /opt/heroic-2.14.1/resources/app.asar.unpacked/build/bin/linux/nile --version
(09:46:37) INFO:    [Connection]:       Connectivity: online
(09:46:37) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/apit/.config/heroic/gogdlConfig /opt/heroic-2.14.1/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/apit/.config/heroic/gog_store/auth.json auth
(09:46:37) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(09:46:37) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(09:46:37) INFO:    [Backend]:          
System Information:
CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700K
Memory: 67.19 GB (used: 6.49 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT]
    IDs: D=73bf V=1002 SD=2406 SV=148c
    Driver: amdgpu
  GPU 1:
    Name: Intel Corporation AlderLake-S GT1
    IDs: D=4680 V=8086 SD=7d25 SV=1462
    Driver: i915
OS: Gentoo 6.8.12-gentoo (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(09:46:37) INFO:    [Frontend]:         Refreshing undefined Library
(09:46:37) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(09:46:37) INFO:    [Legendary]:        Refreshing library...
(09:46:37) INFO:    [Legendary]:        Refreshing Epic Games...
(09:46:37) INFO:    [Backend]:          Frontend Ready
(09:46:37) INFO:    [Backend]:          Checking for new Heroic Updates
(09:46:37) INFO:    [Backend]:          Checking for current version changelog
(09:46:37) ERROR:   [Backend]:          Error when checking for Heroic updates Error: Request failed with status code 403
    at createError (/opt/heroic-2.14.1/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/heroic-2.14.1/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/heroic-2.14.1/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(09:46:37) ERROR:   [Backend]:          Error when checking for current Heroic changelog
(09:46:37) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/apit/.config/heroic/legendaryConfig/legendary /opt/heroic-2.14.1/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(09:46:39) INFO:    [Winetricks]:       Downloading Winetricks
(09:46:39) INFO:    [Legendary]:        Game list updated, got 203 games & DLCs
(09:46:39) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(09:46:39) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/apit/.config/heroic/legendaryConfig/legendary /opt/heroic-2.14.1/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(09:46:41) INFO:    [Legendary]:        Found 0 games to update
(09:46:42) INFO:    [WineDownloader]:   Updating wine versions info
(09:46:42) INFO:    [WineDownloader]:   Fetching upstream information...
(09:46:42) ERROR:   [WineDownloader]:   Error: Could not fetch available releases from https://api.github.com/repos/GloriousEggroll/wine-ge-custom/releases with error:
 Error: Request failed with status code 403
    at /opt/heroic-2.14.1/resources/app.asar/build/electron/main.159a68a5.js:120:4188
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(09:46:42) ERROR:   [WineDownloader]:   Error: Could not fetch available releases from https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases with error:
 Error: Request failed with status code 403
    at /opt/heroic-2.14.1/resources/app.asar/build/electron/main.159a68a5.js:120:4188
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(09:46:42) INFO:    [WineDownloader]:   wine versions updated
(09:46:42) INFO:    [Backend]:          Starting the Download Queue
```

### Steps to reproduce

1. Go to installed games
1. Click on game settings
1. Go to 'Cloud Saves Sync' tab
1. Try to interact with text box containing the save path. notice that it can't be modified.
1. Try to click on the button to delete the current path. notice that it can't be interacted with.

### Expected behavior

Clicking on the delete button should delete the auto-generated path and allow entering the path manually.

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/5159138/82c20099-73e2-48f2-afec-cc7ceb17bb5e)

the mouse pointer is wrong in the screenshot (because of the tool used) it actually shows a circle with a crossed line.

### Heroic Version

Latest Stable

### System Information

- OS Gentoo Linux

Portage 3.0.63 (python 3.12.3-final-0, default/linux/amd64/23.0/desktop/systemd, gcc-13, glibc-2.39-r6, 6.8.12-gentoo x86_64)
=================================================================
System uname: Linux-6.8.12-gentoo-x86_64-12th_Gen_Intel-R-_Core-TM-_i7-12700K-with-glibc2.39
KiB Mem:    65610400 total,  17404264 free
KiB Swap:          0 total,         0 free
Timestamp of repository gentoo: Mon, 17 Jun 2024 06:20:22 +0000
Head commit of repository gentoo: 6569fd6e23b298454a951f752da5ff5118dd8f17

Timestamp of repository guru: Mon, 17 Jun 2024 01:03:58 +0000
Head commit of repository guru: 4ff76aea97c60f8f2e57eb5848312b27e21d9ae2

Head commit of repository steam-overlay: fc142da83eb4eb440c787e9f1befe5945b09f485

Head commit of repository lexxxel: 145dd98fa0c4ca2a6a71a041ea5deb8903baa230

sh bash 5.1_p16-r11
ld GNU ld (Gentoo 2.42 p3) 2.42.0
ccache version 4.9.1 [disabled]
app-misc/pax-utils:        1.3.7::gentoo
app-shells/bash:           5.1_p16-r11::gentoo
dev-build/autoconf:        2.13-r8::gentoo, 2.71-r7::gentoo
dev-build/automake:        1.16.5-r2::gentoo
dev-build/cmake:           3.28.5::gentoo
dev-build/libtool:         2.4.7-r4::gentoo
dev-build/make:            4.4.1-r1::gentoo
dev-build/meson:           1.4.1::gentoo
dev-java/java-config:      2.3.3-r1::gentoo
dev-lang/perl:             5.38.2-r3::gentoo
dev-lang/python:           3.11.9-r1::gentoo, 3.12.3-r1::gentoo
dev-lang/rust:             1.77.1::gentoo
dev-util/ccache:           4.9.1-r1::gentoo
sys-apps/baselayout:       2.15::gentoo
sys-apps/sandbox:          2.38::gentoo
sys-apps/systemd:          255.7::gentoo
sys-devel/binutils:        2.42-r1::gentoo
sys-devel/binutils-config: 5.5::gentoo
sys-devel/clang:           17.0.6::gentoo
sys-devel/gcc:             13.2.1_p20240210::gentoo
sys-devel/gcc-config:      2.11::gentoo
sys-devel/lld:             17.0.6::gentoo
sys-devel/llvm:            17.0.6::gentoo
sys-kernel/linux-headers:  6.9::gentoo (virtual/os-headers)
sys-libs/glibc:            2.39-r6::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/gentoo.git
    priority: -1000
    volatile: True

guru
    location: /var/db/repos/guru
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/guru.git
    masters: gentoo
    volatile: False

steam-overlay
    location: /usr/local/overlay/steam-overlay
    sync-type: git
    sync-uri: https://github.com/anyc/steam-overlay/
    masters: gentoo
    volatile: True

lexxxel
    location: /usr/local/overlay/lexxxel
    sync-type: git
    sync-uri: ssh://git@git.petermann.dev:2022/linux/lexxxel.git
    masters: gentoo
    priority: 50
    volatile: True

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="@FREE"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe -mtune=alderlake -march=alderlake -mabm -mno-cldemote -mno-kl -mno-sgx -mno-widekl -mshstk --param=l1-cache-line-size=64 --param=l1-cache-size=32 --param=l2-cache-size=25600"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-O2 -pipe -mtune=alderlake -march=alderlake -mabm -mno-cldemote -mno-kl -mno-sgx -mno-widekl -mshstk --param=l1-cache-line-size=64 --param=l1-cache-size=32 --param=l2-cache-size=25600"
DISTDIR="/usr/portage/distfiles"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GDK_PIXBUF_MODULE_FILE GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR XDG_STATE_HOME"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs buildpkg-live config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync merge-wait multilib-strict network-sandbox news parallel-fetch pid-sandbox pkgdir-index-trusted preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="ftp://ftp.halifax.rwth-aachen.de/gentoo/ ftp://ftp.wh2.tu-dresden.de/pub/mirrors/gentoo ftp://ftp.uni-erlangen.de/pub/mirrors/gentoo http://ftp.uni-erlangen.de/pub/mirrors/gentoo"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs"
LEX="flex"
MAKEOPTS="-j18"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/tmp"
SHELL="/bin/bash"
USE="X a52 aac acl acpi alsa amd64 android avahi bash-completion bluetooth branding bzip2 cairo cdda cdr cet cmake crypt cups dbus dri dts dvd dvdr encode exif ffmpeg flac gdbm gif git glamor gphoto2 gpm gtk gui iconv icu ipv6 jpeg keyring kf6compat lcms libnotify libtirpc mad mng mp3 mp4 mpeg multilib ncurses nfs nls ntfs ogg opengl openmp pam pango pcre pdf pipewire png policykit ppds pulseaudio python qt5 qt6 rar readline screenshare sdl seccomp secureboot sound spell ssl startup-notification svg systemd test-rust tiff truetype udev udisks unicode upower usb vaapi vorbis vulkan wayland wxwidgets x264 xattr xcb xft xml xv xvid zeroconf zlib" ABI_X86="64" ADA_TARGET="gcc_12" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_anon authn_dbm authn_file authz_dbm authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir env expires ext_filter file_cache filter headers include info log_config logio mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 ntrip navcom oceanserver oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 tsip tripmate tnt ublox" GRUB_PLATFORMS="efi-64" INPUT_DEVICES="evdev wacom" KERNEL="linux" L10N="en-Gb en en-GB" LCD_DEVICES="bayrad cfontz glk hd44780 lb216 lcdm001 mtxorb text" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PERL_FEATURES="ithreads" PHP_TARGETS="php8-2" POSTGRES_TARGETS="postgres15" PYTHON_SINGLE_TARGET="python3_12" PYTHON_TARGETS="python3_12" RUBY_TARGETS="ruby31 ruby32" VIDEO_CARDS="amdgpu radeonsi" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipp2p iface geoip fuzzy condition tarpit sysrq proto logmark ipmark dhcpmac delude chaos account"
Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CC, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXX, CXXFILT, ELFEDIT, EMERGE_DEFAULT_OPTS, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, INSTALL_MASK, LC_ALL, LD, LFLAGS, LIBTOOL, LINGUAS, MAKE, MAKEFLAGS, NM, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, PYTHONPATH, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS

### Additional information

It looks like that 'isSyncing' is not set/ updated correctly.
If I change:
```
            canEditPath={!isSyncing}
            // if I set it manually to allways true, it works for me. e.g. like
            canEditPath={true}
```

It works and that is how I created the screenshot. I run a local version with `canEditPath={true}`, closed Heroic and started my installed version `2.14.1`

**Comment by DavidRGriswold** [comment]
I also currently have this problem on Steam OS

**Comment by mylesvarns** [comment]
Same issue

**Comment by calvinbull** [comment]
I also have the same issue on steamos.

**Comment by lexxxel** [comment]
> I also have the same issue on steamos.

Yes, I forgot to say, I have a steam deck AND this issue there too.

**Comment by malisipi** [comment]
I am on Garuda OS and I have same issue. I have switched from Wine-GE to Proton-GE (due controller issues on game). And save path is not updated and I can not edit it manually. I must copy save file manually.

**Comment by badgerwithagun** [comment]
Same problem here.

It appears to have been fixed by #3718 on April 27th but the [latest release](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.14.1) was earlier than that.

So just awaiting a release.  Or build from source code.

**Comment by arielj** [comment]
just curious, did this get fixed with the latest release for you all? I understand the PR that was merged fixing one of the issues didn't fix it completely?
