### ISSUE TITLE
Some pages will crash or display incorrectly if user has customized their PowerShell profile.

### ISSUE THREAD

**Issue by zeek-zag** [Heroic-Games-Launcher/HeroicGamesLauncher#3828]
### Describe the bug

This is a weird one. If you use any custom variables, aliases, scripts or fastfetch in your $profile on Windows, you won't be able to display the GOG game info page since it will crash. System info and log pages are also not properly displayed.

Blanking the $profile fixes the problem but it's not really a solution since I need my custom aliases and fastfetch :)

### Add logs

```text
HEROIC:
(17:58:41) INFO:    [Legendary]:        Legendary location: C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(17:58:41) INFO:    [Gog]:              GOGDL location: C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(17:58:41) INFO:    [Connection]:       Connectivity: check-online
(17:58:41) INFO:    [Connection]:       Pinging external endpoints
(17:58:41) INFO:    [Gog]:              Checking for existing gog manifests
(17:58:41) INFO:    [Backend]:          DRM module staus {
  "neifaoindggfcjicffkgpmnlppeffabd": {
    "status": "new",
    "title": "Google Widevine Windows CDM",
    "version": "1.0.2738.0"
  },
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(17:58:41) INFO:    [Legendary]:        installed.json updated, refreshing library
(17:58:41) WARNING: [Backend]:          Protocol already registered.
(17:58:42) INFO:    [Connection]:       Connectivity: online
(17:58:42) INFO:    [Gog]:              Checking if login is valid
(17:58:42) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\zeek\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\Users\zeek\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`""
(17:58:42) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\zeek\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\Users\zeek\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`""
(17:58:42) INFO:    [Gog]:              Updating redist, reason - new buildId
(17:58:42) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\zeek\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\Users\zeek\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`""
(17:58:42) INFO:    [Backend]:          Preventing machine to sleep
(17:58:42) INFO:    [Frontend]:         Refreshing undefined Library
(17:58:42) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(17:58:42) INFO:    [Legendary]:        Refreshing library...
(17:58:42) INFO:    [Legendary]:        Refreshing Epic Games...
(17:58:42) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\zeek\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\Users\zeek\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`""
(17:58:42) INFO:    [Backend]:          Frontend Ready
(17:58:42) INFO:    [Backend]:          VCRuntime is installed
(17:58:42) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\zeek\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"list`"","`"--third-party`""
(17:58:42) INFO:    [Backend]:          Checking for new Heroic Updates
(17:58:42) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\zeek\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"--version`""
(17:58:43) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\zeek\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\Users\zeek\AppData\Roaming\heroic\gog_store\auth.json`"","`"--version`""
(17:58:43) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\zeek\AppData\Roaming\heroic\nile_config powershell Start-Process "`"C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"--version`""
(17:58:44) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for shapez
(17:58:44) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for shapez
(17:58:44) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for shapez
(17:58:44) INFO:    [ExtraGameInfo]:    Getting GamesDB data for shapez
(17:58:44) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:58:44) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for shapez
(17:58:44) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for shapez
(17:58:44) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for shapez
(17:58:44) INFO:    [ExtraGameInfo]:    Getting GamesDB data for shapez
(17:58:44) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:58:44) INFO:    [Legendary]:        Getting more details with 'legendary info'
(17:58:44) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(17:58:44) INFO:    [WineDownloader]:   Updating wine versions info
(17:58:44) INFO:    [WineDownloader]:   Fetching upstream information...
(17:58:44) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\zeek\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"info`"","`"e87a43f695bc409ca8858206678ac7e7`"","`"--json`"","`"--platform`"","`"Windows`""
(17:58:44) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\zeek\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"info`"","`"e87a43f695bc409ca8858206678ac7e7`"","`"--json`"","`"--platform`"","`"Windows`""
(17:58:44) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\zeek\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"info`"","`"e87a43f695bc409ca8858206678ac7e7`"","`"--json`"","`"--platform`"","`"Windows`""
(17:58:44) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar\node_modules\axios\lib\adapters\http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(17:58:45) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar\node_modules\axios\lib\adapters\http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(17:58:45) ERROR:   [Legendary]:        Error Getting Info from Epic API
(17:58:45) INFO:    [Backend]:          
System Information:
CPU: 24x AMD Ryzen 9 5900X 12-Core Processor            
Memory: 34.27 GB (used: 9.7 GB)
GPUs:

OS: Unknown Windows Version 10.0.19045 (win32)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
[24C[0m[1m[33mTerminal[0m: [0mHeroic 2.14.1.321
[24C
[24C[40;30m███[41;31m███[42;32m███[43;33m███[44;34m███[45;35m███[46;36m███[47;37m███[0m
[24C[1;40;30;100;90m███[1;41;31;101;91m███[1;42;32;102;92m███[1;43;33;103;93m███[1;44;34;104;94m███[1;45;35;105;95m███[1;46;36;106;96m███[1;47;37;107;97m███[0m
[?7h[?25h
[0m[?25l[?7l[1m[34m[34m    
lllllllll  lllllllll    
lllllllll  lllllllll    
lllllllll  lllllllll    
lllllllll  lllllllll    
    
lllllllll  lllllllll    
lllllllll  lllllllll    
lllllllll  lllllllll    
lllllllll  lllllllll    
    [0m[9999999D[10A[24C[1m[33mzeek

GOG:
[19/06/2024, 17:58:42] GOGDL_CONFIG_PATH=C:\Users\zeek\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\Users\zeek\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`""
[19/06/2024, 17:58:42] GOGDL_CONFIG_PATH=C:\Users\zeek\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\Users\zeek\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`""
[19/06/2024, 17:58:42] GOGDL_CONFIG_PATH=C:\Users\zeek\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\zeek\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\Users\zeek\AppData\Roaming\heroic\gog_store\auth.json`"","`"auth`""
[0m[?25l[?7l[1m[34m[34m    
lllllllll  lllllllll    
lllllllll  lllllllll    
lllllllll  lllllllll    
lllllllll  lllllllll    
    
lllllllll  lllllllll    
lllllllll  lllllllll    
lllllllll  lllllllll    
lllllllll  lllllllll    
    [0m[9999999D[10A[24C[1m[33mzeek
```

### Steps to reproduce

1. Open your PowerShell profile `nano $profile`
2. Add custom commands and aliases
3. Save your profile
4. Launch Heroic
5. Click on any GOG game
6. Crash the page

### Expected behavior

I should be able to display the pages without crashing them even if I modded my $profile.

### Screenshots

![Screenshot from 2024-06-19 18-00-36](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/130962401/8fec54dc-40e2-4f4a-8624-46253cf1e63d)
![Screenshot from 2024-06-19 18-01-23](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/130962401/e574b644-98b4-4eb4-8f1a-344f2fa9975d)

### Heroic Version

Latest Stable

### System Information

Windows 10 Pro 19045.4170

**Comment by arielj** [comment]
from the description of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4227, we could try using the `-NoProfile` argument when running things with powershell

I don't have a windows machine, but it would be a good first issue for any windows developer that wants to contribute:
- Run Heroic, make sure things work fine (like the settings > system information displays correctly)
- Then add something to your powershell profile
- Then run Heroic and check if the system information is incorrect now
- Add the `-NoProfile` argument here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/src/backend/launcher.ts#L1347
- Check if things work fine now

The change is simple but I can't really test this

**Comment by arielj** [comment]
Closing. The fix for this will be included in the next release.

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/4258
