### ISSUE TITLE
Epic Games don't seem to work on ChromeOS

### ISSUE THREAD

**Issue by jisaf** [Heroic-Games-Launcher/HeroicGamesLauncher#3835]
### Describe the bug

Installed Heroic on ChromeOS with the Linux environment enabled. Connected to Epic Games, downloaded a couple and got variations on this error:

An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Checking for updates...[Core] INFO: Getting authentication token...[cli] INFO: Launching <************************>...Traceback (most recent call last):
File "legendary/cli.py", line 3161, in <module>File "legendary/cli.py", line 3076, in main
File "legendary/cli.py", line 716, in launch_game
File "subprocess.py", line 951, in __init__
File "subprocess.py", line 1837, in _execute_childFileNotFoundError: [Errno 2] No such file or directory: '/home/<user>/.config/heroic/tools/wine/Wine-GE-Proton8-26/bin/wine'
[1518] Failed to execute script 'cli' due to unhandled exception!

### Add logs

```text
Launching "Gloomhaven" (legendary)
Native? No
Installed in: /home/<user>/Games/Heroic/Gloomhaven

System Info:
CPU: 8x Intel(R) Core(TM) i3-N305
Memory: 6.8 GB (used: 233.91 MB)
GPUs:

OS: Debian GNU/Linux 12 (bookworm) (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallDxvkNvapi": false,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableMsync": false,
	"enableFsync": true,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"useGameMode": false,
	"battlEyeRuntime": true,
	"eacRuntime": true,
	"language": "",
	"beforeLaunchScriptPath": "",
	"afterLaunchScriptPath": "",
	"wineVersion": {
		"bin": "/home/<user>/.config/heroic/tools/wine/Wine-GE-Proton8-26/bin/wine",
		"name": "Wine - Wine-GE-Proton8-26",
		"type": "wine",
		"lib": "/home/<user>/.config/heroic/tools/wine/Wine-GE-Proton8-26/lib64",
		"lib32": "/home/<user>/.config/heroic/tools/wine/Wine-GE-Proton8-26/lib",
		"wineserver": "/home/<user>/.config/heroic/tools/wine/Wine-GE-Proton8-26/bin/wineserver"
	},
	"winePrefix": "/home/<user>/Games/Heroic/Prefixes/default/Gloomhaven",
	"wineCrossoverBottle": ""
}

Game launched at: Wed Jun 26 2024 14:47:56 GMT-0700 (Pacific Daylight Time)

Winetricks packages: 

Launch Command: HEROIC_APP_NAME=<**************************> HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic STEAM_COMPAT_INSTALL_PATH=/home/<user>/Games/Heroic/Gloomhaven LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= DOTNET_ROOT= WINEPREFIX=/home/<user>/Games/Heroic/Prefixes/default/Gloomhaven WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 PROTON_EAC_RUNTIME=/home/<user>/.config/heroic/tools/runtimes/eac_runtime PROTON_BATTLEYE_RUNTIME=/home/<user>/.config/heroic/tools/runtimes/battleye_runtime ORIG_LD_LIBRARY_PATH= LD_LIBRARY_PATH=/home/<user>/.config/heroic/tools/wine/Wine-GE-Proton8-26/lib64:/home/<user>/.config/heroic/tools/wine/Wine-GE-Proton8-26/lib GST_PLUGIN_SYSTEM_PATH_1_0=/home/<user>/.config/heroic/tools/wine/Wine-GE-Proton8-26/lib64/gstreamer-1.0:/home/<user>/.config/heroic/tools/wine/Wine-GE-Proton8-26/lib/gstreamer-1.0 WINEDLLPATH=/home/<user>/.config/heroic/tools/wine/Wine-GE-Proton8-26/lib64/wine:/home/<user>/.config/heroic/tools/wine/Wine-GE-Proton8-26/lib/wine /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch <**************************> --wine /home/<user>/.config/heroic/tools/wine/Wine-GE-Proton8-26/bin/wine --language en

Game Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching <**************************>...
Traceback (most recent call last):
  File "legendary/cli.py", line 3161, in <module>
  File "legendary/cli.py", line 3076, in main
  File "legendary/cli.py", line 716, in launch_game
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1837, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/<user>/.config/heroic/tools/wine/Wine-GE-Proton8-26/bin/wine'
[1518] Failed to execute script 'cli' due to unhandled exception!
============= End of log =============
```

### Steps to reproduce

Enable Linux/dev environment on ChromeOS
Install Heroic
Connect Epic Game Store
Download game
Launch game
See error

### Expected behavior

Don't see error

### Heroic Version

Latest Stable

### System Information

ChromeOS [Version 125.0.6422.197 (Official Build) (64-bit)] on Chromebook Plus certified machine [Intel(R) Core(TM) i3-N305 (8 threads, 3.80GHz), 8gb ram]

### Additional information

I have verified that if I open a terminal and run `ls /home/<user>/.config/heroic/tools/wine/Wine-GE-Proton8-26/bin/wine` the file does exist.

Also confirmed that `ls /home/<user>/Games/Heroic/` contains the game files being run

Thanks a bunch in advance!

**Comment by CommandMC** [comment]
ChromeOS is not a supported platform. The Linux subsystem runs inside a virtual machine without GPU acceleration, meaning no games will actually run
