### ISSUE TITLE
Errors after login via steam

### ISSUE THREAD

**Issue by All3xJ** [Heroic-Games-Launcher/HeroicGamesLauncher#3840]
### Describe the bug

I don't know if logging normally (not via Steam) would have worked, but I performed the login via steam and this is the output:

```
An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Testing existing login data if present...Traceback (most recent call last):
File "urllib3/connectionpool.py", line 793, in urlopen
File "urllib3/connectionpool.py", line 537, in _make_request
File "urllib3/connection.py", line 466, in getresponseFile "http/client.py", line 1377, in getresponse
File "http/client.py", line 320, in begin
File "http/client.py", line 281, in _read_status
File "socket.py", line 704, in readintoFile "ssl.py", line 1275, in recv_into
File "ssl.py", line 1133, in readConnectionResetError: [Errno 104] Connection reset by peer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "requests/adapters.py", line 486, in send
File "urllib3/connectionpool.py", line 847, in urlopenFile "urllib3/util/retry.py", line 470, in incrementFile "urllib3/util/util.py", line 38, in reraise
File "urllib3/connectionpool.py", line 793, in urlopenFile "urllib3/connectionpool.py", line 537, in _make_request
File "urllib3/connection.py", line 466, in getresponseFile "http/client.py", line 1377, in getresponseFile "http/client.py", line 320, in beginFile "http/client.py", line 281, in _read_statusFile "socket.py", line 704, in readinto
File "ssl.py", line 1275, in recv_intoFile "ssl.py", line 1133, in readurllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "legendary/cli.py", line 3161, in <module>File "legendary/cli.py", line 3070, in mainFile "legendary/cli.py", line 92, in authFile "legendary/core.py", line 272, in check_for_updatesFile "legendary/api/lgd.py", line 21, in get_version_informationFile "requests/sessions.py", line 602, in get
File "requests/sessions.py", line 589, in request
File "requests/sessions.py", line 703, in sendFile "requests/adapters.py", line 501, in sendrequests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[226] Failed to execute script 'cli' due to unhandled exception!

```

### Add logs

```text
(11:49:17) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(11:49:17) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(11:49:17) INFO:    [Connection]:       Connectivity: check-online
(11:49:17) INFO:    [Connection]:       Pinging external endpoints
(11:49:17) INFO:    [Gog]:              Checking for existing gog manifests
(11:49:17) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(11:49:17) WARNING: [Backend]:          Failed to register protocol with OS.
(11:49:17) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/allexj/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(11:49:17) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/allexj/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/allexj/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(11:49:17) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/allexj/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(11:49:17) INFO:    [Connection]:       Connectivity: online
(11:49:17) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/allexj/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/allexj/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(11:49:17) INFO:    [Backend]:          User Not Found, removing it from Store
(11:49:17) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(11:49:18) INFO:    [Backend]:          Frontend Ready
(11:49:18) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 7 5825U with Radeon Graphics
Memory: 7.63 GB (used: 3.99 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo
    IDs: D=15e7 V=1002 SD=89fc SV=103c
    Driver: amdgpu
OS: Ubuntu 24.04 LTS (Noble Numbat) (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(11:49:18) INFO:    [Backend]:          Checking for current version changelog
(11:49:18) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(11:49:20) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(11:49:20) INFO:    [Winetricks]:       Downloading Winetricks
(11:49:22) INFO:    [WineDownloader]:   Updating wine versions info
(11:49:22) INFO:    [WineDownloader]:   Fetching upstream information...
(11:49:23) INFO:    [Backend]:          Starting the Download Queue
(11:49:24) INFO:    [WineDownloader]:   wine versions updated
(11:49:26) INFO:    [Legendary]:        Logging in: LEGENDARY_CONFIG_PATH=/home/allexj/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(11:49:26) INFO:    [Frontend]:         Refreshing legendary Library
(11:49:26) INFO:    [Legendary]:        Refreshing library...
```

### Steps to reproduce

1. Login via steam
2. See the error

### Expected behavior

I should be able to login

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/20903913/180ddd26-2315-4a1b-98a8-5a44fae86cf8)

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS: Ubuntu 24.04

**Comment by All3xJ** [comment]
UPDATE: I closed the Launcher, then click on Login again and now it works lol. Should I close the bug report?

**Comment by CommandMC** [comment]
Seems like this was a one-time issue with your network connection. Closing this for now.

In case the errors return: if they're still mentioning `urllib3` / `requests`, it's likely your connection is unstable.
