### ISSUE TITLE
Amazon/nile "Cannot get game info" heroic gui message when clicking on Amazon game tile

### ISSUE THREAD

**Issue by Bob837217** [Heroic-Games-Launcher/HeroicGamesLauncher#3843]
### Describe the bug

a) I click on the game "Adios" tile in my Amazon library within Heroic Games Launcher... (really is the same issue for any Amazon game though)
b) The details page for Adios opens up
c) Cannot get game info error is displayed:
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/68859866/777773b0-2640-4bd5-9443-6fa2afb7d766)

I have attached logs for Amazon/nile in the logs section which shows some errors within nile

### Add logs

```text
[30/06/2024, 19:40:00] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
INFO [LIBRARY]:	 Synchronizing library
[30/06/2024, 19:40:01] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
1.0.2 Jonathan Joestar
INFO [LIBRARY]:	 Got next token in response, making next request
[30/06/2024, 19:40:01] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
INFO [LIBRARY]:	 Got next token in response, making next request
INFO [LIBRARY]:	 Successfully synced the library
[30/06/2024, 19:40:12] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.ab888f57-d3f4-4961-a50e-eb891fe27aaa
[30/06/2024, 19:40:12] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.ab888f57-d3f4-4961-a50e-eb891fe27aaa
INFO [CLI]:	 Found: Adios
ERROR [LIBRARY]:	 There was an error getting game manifest
Traceback (most recent call last):
  File "nile/cli.py", line 347, in <module>
  File "nile/cli.py", line 328, in main
  File "nile/cli.py", line 161, in handle_install
  File "nile/downloading/manager.py", line 153, in info
  File "nile/downloading/manager.py", line 31, in get_manifest
TypeError: 'NoneType' object is not subscriptable
[178] Failed to execute script 'cli' due to unhandled exception!
[30/06/2024, 19:40:13] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.ab888f57-d3f4-4961-a50e-eb891fe27aaa
[30/06/2024, 19:40:13] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.ab888f57-d3f4-4961-a50e-eb891fe27aaa
[30/06/2024, 19:40:13] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.ab888f57-d3f4-4961-a50e-eb891fe27aaa
[30/06/2024, 19:40:13] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.ab888f57-d3f4-4961-a50e-eb891fe27aaa
[30/06/2024, 19:40:13] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.ab888f57-d3f4-4961-a50e-eb891fe27aaa
[30/06/2024, 19:40:13] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.ab888f57-d3f4-4961-a50e-eb891fe27aaa
[30/06/2024, 19:40:13] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.ab888f57-d3f4-4961-a50e-eb891fe27aaa
[30/06/2024, 19:40:13] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.ab888f57-d3f4-4961-a50e-eb891fe27aaa
INFO [CLI]:	 Found: Adios
ERROR [LIBRARY]:	 There was an error getting game manifest
Traceback (most recent call last):
  File "nile/cli.py", line 347, in <module>
  File "nile/cli.py", line 328, in main
  File "nile/cli.py", line 161, in handle_install
  File "nile/downloading/manager.py", line 153, in info
  File "nile/downloading/manager.py", line 31, in get_manifest
TypeError: 'NoneType' object is not subscriptable
[183] Failed to execute script 'cli' due to unhandled exception!
[30/06/2024, 19:40:16] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json
ERROR [LIBRARY]:	 There was an error getting versions
[]
[30/06/2024, 19:40:17] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.ab888f57-d3f4-4961-a50e-eb891fe27aaa
[30/06/2024, 19:40:17] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.ab888f57-d3f4-4961-a50e-eb891fe27aaa
INFO [CLI]:	 Found: Adios
ERROR [LIBRARY]:	 There was an error getting game manifest
Traceback (most recent call last):
  File "nile/cli.py", line 347, in <module>
  File "nile/cli.py", line 328, in main
  File "nile/cli.py", line 161, in handle_install
  File "nile/downloading/manager.py", line 153, in info
  File "nile/downloading/manager.py", line 31, in get_manifest
TypeError: 'NoneType' object is not subscriptable
[201] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

a) I click on the game "Adios" tile in my Amazon library within Heroic Games Launcher... (really is the same issue for any Amazon game though)
b) The details page for Adios opens up
c) Cannot get game info error is displayed:
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/68859866/777773b0-2640-4bd5-9443-6fa2afb7d766)

I have attached logs for Amazon/nile in the logs section which shows some errors within nile

### Expected behavior

The details page for Adios should show without error

### Screenshots

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/68859866/777773b0-2640-4bd5-9443-6fa2afb7d766

### Heroic Version

Latest Stable (Flatpak)

### System Information

OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 6.9.3-76060903-generic 
CPU: Intel i5-2500K (4) @ 5.900GHz 
GPU: NVIDIA GeForce GTX 1070 Ti

**Comment by Labsdj** [comment]
Same issue on Windows side app heroic last version

**Comment by segadude** [comment]
I’m having the same issue on macOS.

**Comment by Lariaa** [comment]
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3816#issuecomment-2156766034 describes how to run a fixed version of nile to solve this.

**Comment by Bob837217** [comment]
Closing this for now, as it appears to be a duplicate of recently closed issue:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3816
