### ISSUE TITLE
Can't run Quake 4 from interface.

### ISSUE THREAD

**Issue by thescarydoor1** [Heroic-Games-Launcher/HeroicGamesLauncher#3844]
### Describe the bug

Heroic app can't run Quake 4, probably because the exe needs to be run as administrator.

### Add logs

```text
Launching "Quake 4" (gog)
Native? Yes
Installed in: D:\Heroic\Quake 4

System Info:
CPU: 8x Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Memory: 17.11 GB (used: 8.83 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation TU106 [GeForce RTX 2060 Rev. A]
    IDs: D=1f08 V=10de SD=2167 SV=3842
    Driver: 556.12
OS: Microsoft Windows 10 Home 10.0.19045 (win32)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallDxvkNvapi": false,
	"autoInstallVkd3d": false,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableMsync": false,
	"enableFsync": false,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"targetExe": "D:\\Heroic\\Quake 4\\Quake4.exe",
	"useGameMode": false,
	"battlEyeRuntime": false,
	"eacRuntime": false,
	"language": "",
	"beforeLaunchScriptPath": "",
	"afterLaunchScriptPath": "",
	"gogSaves": [
		{
			"name": "saves",
			"location": "\"D:\\Heroic\\Quake 4\\q4base\\savegames\""
		}
	]
}

Game launched at: Sun Jun 30 2024 13:13:55 GMT-0700 (Pacific Daylight Time)

Launch Command: HEROIC_APP_NAME=1836059896 HEROIC_APP_RUNNER=gog HEROIC_APP_SOURCE=gog C:\Users\myusername\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl launch "D:\Heroic\Quake 4" --override-exe "D:\Heroic\Quake 4\Quake4.exe" 1836059896 --platform windows

Game Log:
Traceback (most recent call last):
  File "gogdl\cli.py", line 67, in <module>
  File "gogdl\cli.py", line 62, in main
  File "gogdl\launch.py", line 174, in launch
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
OSError: [WinError 740] The requested operation requires elevation
[19368] Failed to execute script 'cli' due to unhandled exception!
Launch command: ['D:\\Heroic\\Quake 4\\Quake4.exe']
============= End of log =============
```

### Steps to reproduce

1. Download and install Quake 4 from GOG
2. Run it
3. Nothing will happen

### Expected behavior

Heroic app should let you run Quake 4

### Heroic Version

Latest Stable

### System Information

Windows 10

### Additional information

Quake 4 works if you run the EXE directly.

**Comment by imLinguin** [comment]
Indeed, it seems that it requires admin privileges which aren't triggered when launching from gogdl. I imagine Amazon and Epic aren't affected by this to same extent as GOG
