### ISSUE TITLE
Getting "Error installing DXVK/VKD3D! Please check your connection!" 

### ISSUE THREAD

**Issue by hardpenguin** [Heroic-Games-Launcher/HeroicGamesLauncher#3856]
### Describe the bug

When I start Heroic Games Launcher I see it updating my library (the little round 🔁 icon is spinning) and then once it finishes I get a popup saying:

```
Error installing DXVK/VKD3D! Please check your connection!
```

![Screenshot_20240710_150913](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/20478460/023fd1de-4a08-4d13-8c10-0b13c5c41cb3)

The part in log that I believe is relevant says:

```
(15:07:09) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://github.com/Heroic-Games-Launcher/vkd3d-proton/releases/download/v2.13/vkd3d-proton-2.13.tar.xz. 
Error: Error: timeout of 10000ms exceeded
(15:07:09) WARNING: [DXVKInstaller]:    Error when downloading vkd3d Error: Failed to get headers
    at downloadFile (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:136:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installOrUpdateTool (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:99:198)
```

This is the latest .deb version of the application running on Debian Sid. The issue started occuring a couple weeks ago on its own. It does not stand in the way of using the application in any way but it is very annoying.

I tried both "Clear Cache" and "Reset Heroic" options in Advanced section of Settings but they have not changed a thing.

Happy to supply more info if needed.

### Add logs

```text
(15:06:56) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(15:06:56) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:06:56) INFO:    [Connection]:       Connectivity: check-online
(15:06:56) INFO:    [Connection]:       Pinging external endpoints
(15:06:56) INFO:    [Gog]:              Checking for existing gog manifests
(15:06:56) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(15:06:56) WARNING: [Backend]:          Protocol already registered.
(15:06:57) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/van/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:06:57) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/van/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/van/.config/heroic/gog_store/auth.json --version
(15:06:57) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/van/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(15:06:57) INFO:    [Connection]:       Connectivity: online
(15:06:57) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/van/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/van/.config/heroic/gog_store/auth.json auth
(15:06:57) INFO:    [Gog]:              Checking if login is valid
(15:06:57) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/van/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/van/.config/heroic/gog_store/auth.json auth
(15:06:57) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(15:06:57) INFO:    [Backend]:          
System Information:
CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Memory: 16.71 GB (used: 11.89 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GA103 [GeForce RTX 3060 Ti]
    IDs: D=2414 V=10de SD=6630 SV=19da
    Driver: nvidia
OS: Debian GNU/Linux 6.9.7-amd64 (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(15:06:57) INFO:    [Frontend]:         Refreshing undefined Library
(15:06:57) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(15:06:58) INFO:    [Legendary]:        Refreshing library...
(15:06:58) INFO:    [Legendary]:        Refreshing Epic Games...
(15:06:58) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/van/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/van/.config/heroic/gog_store/auth.json auth
(15:06:58) INFO:    [Backend]:          Frontend Ready
(15:06:58) INFO:    [Gog]:              Saved username to config file
(15:06:58) INFO:    [Backend]:          Checking for new Heroic Updates
(15:06:58) INFO:    [Gog]:              Getting GOG library
(15:06:58) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/van/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/van/.config/heroic/gog_store/auth.json auth
(15:06:58) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/van/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:06:58) INFO:    [Backend]:          Checking for current version changelog
(15:06:59) INFO:    [Winetricks]:       Downloading Winetricks
(15:06:59) INFO:    [DXVKInstaller]:    Updating vkd3d to: vkd3d-proton-2.13
(15:06:59) INFO:    [DXVKInstaller]:    Updating dxvk to: dxvk-2.4
(15:07:00) INFO:    [Legendary]:        Game list updated, got 22 games & DLCs
(15:07:01) INFO:    [WineDownloader]:   Updating wine versions info
(15:07:01) INFO:    [WineDownloader]:   Fetching upstream information...
(15:07:02) INFO:    [WineDownloader]:   wine versions updated
(15:07:03) INFO:    [Backend]:          Starting the Download Queue
(15:07:09) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://github.com/Heroic-Games-Launcher/vkd3d-proton/releases/download/v2.13/vkd3d-proton-2.13.tar.xz. 
Error: Error: timeout of 10000ms exceeded
(15:07:09) WARNING: [DXVKInstaller]:    Error when downloading vkd3d Error: Failed to get headers
    at downloadFile (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:136:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installOrUpdateTool (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:99:198)
(15:07:09) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://github.com/doitsujin/dxvk/releases/download/v2.4/dxvk-2.4.tar.gz. 
Error: Error: timeout of 10000ms exceeded
(15:07:09) WARNING: [DXVKInstaller]:    Error when downloading dxvk Error: Failed to get headers
    at downloadFile (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:136:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installOrUpdateTool (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:99:198)
(15:07:11) INFO:    [Gog]:              Saved games data
(15:07:11) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:07:11) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/van/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/van/.config/heroic/gog_store/auth.json auth
(15:07:11) INFO:    [Gog]:              Found 1 game(s) to update
(15:07:12) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/van/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:07:13) INFO:    [Legendary]:        Found 0 games to update
```

### Steps to reproduce

1. Start the app.
2. Wait until it finished refreshing the library (the round 🔁 icon stops spinning).
3. The popup will appear on its own.

### Expected behavior

The DXVK updates automatically on its own without any issue.

### Screenshots

Screenshot visible in the main description field.

### Heroic Version

Latest Stable

### System Information

CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Memory: 16.71 GB (used: 12.28 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GA103 [GeForce RTX 3060 Ti]
    IDs: D=2414 V=10de SD=6630 SV=19da
    Driver: nvidia
OS: Debian GNU/Linux 6.9.7-amd64 (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

**Comment by arielj** [comment]
Is this still happening? sometimes Github doesn't like that we download many things from there in a short amount of time and some limitation blocks requests.

Is this still an issue after a week?

**Comment by hardpenguin** [comment]
> Is this still happening? sometimes Github doesn't like that we download many things from there in a short amount of time and some limitation blocks requests.
> 
> Is this still an issue after a week?

Just checked and yes it is. It happens pretty much every time I launched the client over the last couple weeks.

**Comment by hartigan43** [comment]
Getting the same issue on my end.  
```
(node:9923) UnhandledPromiseRejectionWarning: Error: timeout of 10000ms exceeded
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:514:28)
    at Timeout.<anonymous> (/opt/Heroic/resources/app.asar/node_modules/follow-redirects/index.js:210:12)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:9923) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 132)
(14:39:36) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://github.com/doitsujin/dxvk/releases/download/v2.4/dxvk-2.4.tar.gz.
Error: Error: timeout of 10000ms exceeded
(14:39:36) WARNING: [DXVKInstaller]:    Error when downloading dxvk Error: Failed to get headers
    at downloadFile (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:136:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installOrUpdateTool (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:99:198)
    ```
    
    I tested it with and without VPN but receive the same result.  I've got no issue manually accessing the failed link for dxvk.

**Comment by hardpenguin** [comment]
I ended up nuking entirety of both Heroic folders $HOME/.config and $HOME/.var/app (I have been experimenting with .deb and flatpak versions of the app in the past) and the issue seems to be gone.

**Comment by kiwidoggie** [comment]
Same issue https://0x0.st/X5Us.log

**Comment by mhill8** [comment]
I just installed HGL on Arch Linux today, and have been getting the same error every time it loads.  I closed the error message and got to the main menu, and was able to login to the Epic Games store (using the alternate method—the main method kept looping on the CloudFlare "click here" attempt).  It shows my games, and lets me install one, but when I try to run it tries to install vkd3d-proton-2.14.tar.xz, dxvk-2.5.2.tar.gz, and dxvk-nvapi-v0.8.0.tar.gz, and fails, so drops back to the menu.
