### ISSUE TITLE
Legendary: HTTP errors in EGS

### ISSUE THREAD

**Issue by Alex0007** [Heroic-Games-Launcher/HeroicGamesLauncher#3878]
### Describe the bug

I have tried to re-login with using both login methods, but it didn't resolved the issue

When application tries to fetch library or run the game error happens:

**Legendary (Epic Games) error**:

```
An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "legendary/cli.py", line 3161, in <module>File "legendary/cli.py", line 3072, in main
File "legendary/cli.py", line 200, in list_games
File "legendary/core.py", line 413, in get_game_and_dlc_listFile "legendary/core.py", line 359, in get_assets
File "legendary/api/egs.py", line 171, in get_game_assetsFile "requests/models.py", line 1021, in raise_for_statusrequests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/public/assets/Mac?label=Live
[40035] Failed to execute script 'cli' due to unhandled exception!```

### Add logs

```text
(19:30:38) INFO:    [Legendary]:        Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary

(19:30:38) INFO:    [Gog]:              GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl

(19:30:38) INFO:    [Connection]:       Connectivity: check-online

(19:30:38) INFO:    [Connection]:       Pinging external endpoints

(19:30:38) INFO:    [Gog]:              Checking for existing gog manifests

(19:30:38) INFO:    [Backend]:          DRM module staus {

  "oimompecagnajdejgnnjijobebaeigek": {

    "status": "new",

    "title": "Widevine Content Decryption Module",

    "version": "4.10.2710.0"

  }

}

(19:30:38) WARNING: [Backend]:          Protocol already registered.

(19:30:38) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version

(19:30:38) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/alex/Library/Application Support/heroic/gog_store/auth.json" --version

(19:30:38) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/nile_config" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/nile --version

(19:30:38) INFO:    [Frontend]:         Refreshing undefined Library

(19:30:38) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(19:30:38) INFO:    [Legendary]:        Refreshing library...

(19:30:38) INFO:    [Backend]:          Frontend Ready

(19:30:38) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(19:30:38) INFO:    [Backend]:          Checking for new Heroic Updates

(19:30:38) INFO:    [Backend]:          Checking for current version changelog

(19:30:38) INFO:    [Connection]:       Connectivity: online

(19:30:38) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/alex/Library/Application Support/heroic/gog_store/auth.json" auth

(19:30:38) INFO:    [Backend]:          User Not Found, removing it from Store

(19:30:38) INFO:    [Gog]:              Checking if login is valid

(19:30:38) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/alex/Library/Application Support/heroic/gog_store/auth.json" auth

(19:30:38) INFO:    [Gog]:              Updating redist, reason - new buildId

(19:30:38) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/alex/Library/Application Support/heroic/gog_store/auth.json" auth

(19:30:38) INFO:    [Backend]:          Preventing machine to sleep

(19:30:38) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded

(19:30:40) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine

(19:30:40) INFO:    [Winetricks]:       Downloading Winetricks

(19:30:43) INFO:    [WineDownloader]:   Updating wine versions info

(19:30:43) INFO:    [WineDownloader]:   Fetching upstream information...

(19:30:43) INFO:    [Backend]:          Starting the Download Queue

(19:30:44) INFO:    [WineDownloader]:   wine versions updated

(19:30:54) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version

(19:30:54) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/alex/Library/Application Support/heroic/gog_store/auth.json" --version

(19:30:54) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/nile_config" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/nile --version

(19:30:59) INFO:    [Legendary]:        Logging out: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --delete

(19:30:59) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/alex/Library/Application Support/heroic/gog_store/auth.json" info gog-redist --os windows

(19:30:59) INFO:    [Gog]:              Saved username to config file

(19:31:07) INFO:    [Backend]:          

System Information:

CPU: 11x Apple M3 Pro

Memory: 19.33 GB (used: 8.78 GB)

GPUs:

OS:  14.5.0 (darwin)

The current system is not a Steam Deck

We are not running inside a Flatpak container

Software Versions:

  Heroic: 2.14.1 Flame Emperor Sabo

  Legendary: 0.20.34 Direct Intervention

  gogdl: 1.0.1

  Nile: 1.0.2 Jonathan Joestar

(19:31:12) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo

(19:31:12) INFO:    [DownloadManager]:  Galaxy Common Redistributables  was added to the download queue.

(19:31:12) INFO:    [Gog]:              Updating GOG redistributables

(19:31:12) INFO:    [Gog]:              GOG REDIST:: GOGDL_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/alex/Library/Application Support/heroic/gog_store/auth.json" redist --ids ISI --path "/Users/alex/Library/Application Support/heroic/tools/redist/gog"

(19:31:12) DEBUG:   [Gog]:              Logging to file "/Users/alex/Library/Application Support/heroic/GamesConfig/gog-redist.log"

(19:31:23) INFO:    [DownloadManager]:  gog-redist added to download manager finished.

(19:31:23) INFO:    [DownloadManager]:  gog-redist removed from download manager.

(19:31:24) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary cleanup

(19:31:24) INFO:    [Frontend]:         Refreshing undefined Library

(19:31:24) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(19:31:24) INFO:    [Legendary]:        Refreshing library...

(19:31:24) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/alex/Library/Application Support/heroic/gog_store/auth.json" auth

(19:31:24) INFO:    [Backend]:          Checking for new Heroic Updates

(19:31:24) INFO:    [Backend]:          Checking for current version changelog

(19:31:35) INFO:    [Gog]:              Getting GOG library

(19:31:35) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/alex/Library/Application Support/heroic/gog_store/auth.json" auth

(19:31:47) INFO:    [Gog]:              Saved games data

(19:31:47) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(19:31:47) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/alex/Library/Application Support/heroic/gog_store/auth.json" auth

(19:31:58) INFO:    [Gog]:              Found 0 game(s) to update

(19:31:58) INFO:    [Legendary]:        Logging in: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --code <redacted>

(19:32:24) INFO:    [Frontend]:         Refreshing legendary Library

(19:32:24) INFO:    [Legendary]:        Refreshing library...

(19:32:24) INFO:    [Legendary]:        Refreshing Epic Games...

(19:32:24) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party

(19:32:49) INFO:    [Legendary]:        Game list updated, got 14 games & DLCs

(19:32:49) INFO:    [Frontend]:         No cache found, getting data from legendary...

(19:32:49) INFO:    [Legendary]:        Refreshing library...

(19:32:49) INFO:    [Legendary]:        Refreshing Epic Games...

(19:32:50) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party

(19:33:16) INFO:    [Legendary]:        Game list updated, got 14 games & DLCs

(19:33:16) INFO:    [Frontend]:         Force Update

(19:33:36) INFO:    [Backend]:          Launching Expeditions: A MudRunner Game (9eae4ea0f5144b91b0186876ed326bbb)

(19:33:36) INFO:    [Backend]:          Preventing display from sleep

(19:33:36) INFO:    [Backend]:          Checking if wine version exists: CrossOver - 24.0.3

(19:33:36) INFO:    [Backend]:          Preventing machine to sleep

(19:33:36) INFO:    [Backend]:          Checking if wine version exists: CrossOver - 24.0.3

(19:33:36) INFO:    [Backend]:          Checking if wine version exists: CrossOver - 24.0.3

(19:33:36) INFO:    [Legendary]:        Launching Expeditions: A MudRunner Game: HEROIC_APP_NAME=9eae4ea0f5144b91b0186876ed326bbb HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= DOTNET_ROOT= CX_BOTTLE=Expeditions WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEMSYNC=1 LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary launch 9eae4ea0f5144b91b0186876ed326bbb --wine /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wine --language en

(19:33:36) INFO:    [Backend]:          Stopping Power Saver Blocker

(19:34:06) INFO:    [Backend]:          Stopping Display Power Saver Blocker

(19:34:06) INFO:    [Frontend]:         Refreshing legendary Library

(19:34:06) INFO:    [Legendary]:        Refreshing library...

(19:34:06) INFO:    [Legendary]:        Refreshing Epic Games...

(19:34:06) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party

(19:34:31) INFO:    [Legendary]:        Game list updated, got 14 games & DLCs

(19:35:23) INFO:    [Backend]:          Launching Expeditions: A MudRunner Game (9eae4ea0f5144b91b0186876ed326bbb)

(19:35:23) INFO:    [Backend]:          Checking if wine version exists: CrossOver - 24.0.3

(19:35:23) INFO:    [Backend]:          Checking if wine version exists: CrossOver - 24.0.3

(19:35:23) INFO:    [Backend]:          Checking if wine version exists: CrossOver - 24.0.3

(19:35:23) INFO:    [Legendary]:        Launching Expeditions: A MudRunner Game: HEROIC_APP_NAME=9eae4ea0f5144b91b0186876ed326bbb HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= DOTNET_ROOT= CX_BOTTLE=Expeditions WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEMSYNC=1 LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary launch 9eae4ea0f5144b91b0186876ed326bbb --wine /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wine --language en

(19:35:23) INFO:    [Backend]:          Stopping Power Saver Blocker

(19:35:48) INFO:    [Backend]:          Stopping Display Power Saver Blocker

(19:35:48) INFO:    [Frontend]:         Refreshing legendary Library

(19:35:48) INFO:    [Legendary]:        Refreshing library...

(19:35:48) INFO:    [Legendary]:        Refreshing Epic Games...

(19:35:48) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party

(19:35:54) INFO:    [Backend]:          9eae4ea0f5144b91b0186876ed326bbb: Setting offlineMode to true

(19:36:04) INFO:    [Backend]:          Launching Expeditions: A MudRunner Game (9eae4ea0f5144b91b0186876ed326bbb)

(19:36:04) INFO:    [Backend]:          Checking if wine version exists: CrossOver - 24.0.3

(19:36:04) WARNING: [Backend]:          Offline Mode is on but the game does not allow offline mode explicitly.

(19:36:04) INFO:    [Backend]:          Checking if wine version exists: CrossOver - 24.0.3

(19:36:04) INFO:    [Backend]:          Checking if wine version exists: CrossOver - 24.0.3

(19:36:04) INFO:    [Legendary]:        Launching Expeditions: A MudRunner Game: HEROIC_APP_NAME=9eae4ea0f5144b91b0186876ed326bbb HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= DOTNET_ROOT= CX_BOTTLE=Expeditions WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEMSYNC=1 LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary launch 9eae4ea0f5144b91b0186876ed326bbb --wine /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wine --language en --offline

(19:36:04) INFO:    [Backend]:          Stopping Power Saver Blocker

(19:36:12) INFO:    [Legendary]:        Game list updated, got 14 games & DLCs

(19:37:06) INFO:    [Backend]:          Stopping Display Power Saver Blocker

(19:37:06) INFO:    [Frontend]:         Refreshing legendary Library

(19:37:06) INFO:    [Legendary]:        Refreshing library...

(19:37:06) INFO:    [Legendary]:        Refreshing Epic Games...

(19:37:06) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party

(19:37:07) INFO:    [Backend]:          9eae4ea0f5144b91b0186876ed326bbb: Setting offlineMode to false

(19:37:14) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine

(19:37:30) INFO:    [Legendary]:        Game list updated, got 14 games & DLCs

(19:37:32) INFO:    [Legendary]:        Logging out: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --delete

(19:37:57) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary cleanup

(19:37:57) INFO:    [Frontend]:         Refreshing undefined Library

(19:37:57) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(19:37:57) INFO:    [Legendary]:        Refreshing library...

(19:37:57) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/alex/Library/Application Support/heroic/gog_store/auth.json" auth

(19:37:57) INFO:    [Backend]:          Checking for new Heroic Updates

(19:37:57) INFO:    [Backend]:          Checking for current version changelog

(19:38:08) INFO:    [Gog]:              Getting GOG library

(19:38:08) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/alex/Library/Application Support/heroic/gog_store/auth.json" auth

(19:38:15) INFO:    [Frontend]:         Called Epic Login

(19:38:15) INFO:    [Legendary]:        Logging in: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --code <redacted>

(19:38:21) INFO:    [Gog]:              Saved games data

(19:38:21) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(19:38:21) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/alex/Library/Application Support/heroic/gog_store/auth.json" auth

(19:38:32) INFO:    [Gog]:              Found 0 game(s) to update

(19:38:32) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party

(19:38:56) DEBUG:   [Legendary]:        Update is available for 9eae4ea0f5144b91b0186876ed326bbb: 519327.EXP_DLC4_RETAIL != 545692.EXP_COOP_RETAIL

(19:38:56) INFO:    [Legendary]:        Found 1 game to update

(19:39:42) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version

(19:39:42) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/alex/Library/Application Support/heroic/gog_store/auth.json" --version

(19:39:42) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/nile_config" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/nile --version

(19:42:00) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version

(19:42:00) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/alex/Library/Application Support/heroic/gog_store/auth.json" --version

(19:42:00) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/nile_config" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/nile --version

(19:42:41) INFO:    [Legendary]:        Logging in: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --code <redacted>

(19:43:05) INFO:    [Frontend]:         Refreshing legendary Library

(19:43:05) INFO:    [Legendary]:        Refreshing library...

(19:43:05) INFO:    [Legendary]:        Refreshing Epic Games...

(19:43:06) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party

(19:43:30) INFO:    [Legendary]:        Game list updated, got 14 games & DLCs

(19:43:30) INFO:    [Frontend]:         No cache found, getting data from legendary...

(19:43:30) INFO:    [Legendary]:        Refreshing library...

(19:43:30) INFO:    [Legendary]:        Refreshing Epic Games...

(19:43:30) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party

(19:43:55) INFO:    [Legendary]:        Game list updated, got 14 games & DLCs

(19:43:55) INFO:    [Frontend]:         Force Update

(19:47:27) INFO:    [Legendary]:        Getting more details with 'legendary info'

(19:47:27) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info 9eae4ea0f5144b91b0186876ed326bbb --json --platform Windows

(19:47:34) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary eos-overlay info

(19:47:34) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Expeditions A MudRunner Game

(19:47:34) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Expeditions A MudRunner Game

(19:47:34) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Expeditions A MudRunner Game

(19:47:34) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Expeditions A MudRunner Game

(19:47:34) INFO:    [ExtraGameInfo]:    Getting AppleGamingWiki data for Expeditions A MudRunner Game

(19:47:34) INFO:    [Legendary]:        Getting more details with 'legendary info'

(19:47:34) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Expeditions A MudRunner Game

(19:47:34) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Expeditions A MudRunner Game

(19:47:34) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Expeditions A MudRunner Game

(19:47:34) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Expeditions A MudRunner Game

(19:47:34) INFO:    [ExtraGameInfo]:    Getting AppleGamingWiki data for Expeditions A MudRunner Game

(19:47:34) INFO:    [Legendary]:        Getting more details with 'legendary info'

(19:47:34) INFO:    [Legendary]:        Getting more details with 'legendary info'

(19:47:35) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info 9eae4ea0f5144b91b0186876ed326bbb --json --platform Windows

(19:47:35) ERROR:   [Backend]:          Failed to get epic service status with Error: getaddrinfo ENOTFOUND status.epicgames.com

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)

(19:47:35) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info 9eae4ea0f5144b91b0186876ed326bbb --json --platform Windows

(19:47:35) ERROR:   [Backend]:          Failed to get epic service status with Error: getaddrinfo ENOTFOUND status.epicgames.com

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)

(19:47:35) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/alex/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info 9eae4ea0f5144b91b0186876ed326bbb --json --platform Windows

(19:47:35) ERROR:   [Legendary]:        Error: Request failed with status code 403

    at createError (/Applications/Heroic.app/Contents/Resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)

    at settle (/Applications/Heroic.app/Contents/Resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)

    at IncomingMessage.handleStreamEnd (/Applications/Heroic.app/Contents/Resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)

    at IncomingMessage.emit (node:events:526:35)

    at endReadableNT (node:internal/streams/readable:1408:12)

    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

(19:47:37) ERROR:   [Legendary]:        Error: Request failed with status code 403

    at createError (/Applications/Heroic.app/Contents/Resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)

    at settle (/Applications/Heroic.app/Contents/Resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)

    at IncomingMessage.handleStreamEnd (/Applications/Heroic.app/Contents/Resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)

    at IncomingMessage.emit (node:events:526:35)

    at endReadableNT (node:internal/streams/readable:1408:12)

    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

(19:47:37) ERROR:   [Legendary]:        Error Getting Info from Epic API

(19:47:51) ERROR:   [Legendary]:        Error: Failed to parse install info for 9eae4ea0f5144b91b0186876ed326bbb with: SyntaxError: Unexpected end of JSON input

    at Module.getInstallInfo (/Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.159a68a5.js:114:3453)

    at async /Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.159a68a5.js:235:5349

    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)

(19:47:51) ERROR:   [Legendary]:        Error: Failed to parse install info for 9eae4ea0f5144b91b0186876ed326bbb with: SyntaxError: Unexpected end of JSON input

    at Module.getInstallInfo (/Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.159a68a5.js:114:3453)

    at async /Applications/Heroic.app/Contents/Resources/app.asar/build/electron/main.159a68a5.js:235:5349

    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)

(19:47:51) ERROR:   [Frontend]:         Cannot get game info

(19:47:51) ERROR:   [Frontend]:         Cannot get game info
```

### Steps to reproduce

1. Go to Library and choose any EGS game
2. Click "run"
3. See error

### Expected behavior

HTTP errors shouldn't happen

### Heroic Version

Latest Stable

### System Information

- MacOS Sonoma 14.5

**Comment by Megalomaniak** [comment]
restarting heroic and/or the system seems to resolve it for me. At least temporarily.
