### ISSUE TITLE
Amazon games doesnt install 

### ISSUE THREAD

**Issue by Alecerzea** [Heroic-Games-Launcher/HeroicGamesLauncher#3887]
### Describe the bug

Amazon games doesnt wanna install in my Fedora 40, I thinked it was a problem with my system but in a fresh install the problem still ocurred

### Add logs

```text
(20:14:12) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(20:14:12) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(20:14:12) INFO:    [Connection]:       Connectivity: check-online
(20:14:12) INFO:    [Connection]:       Pinging external endpoints
(20:14:12) INFO:    [Gog]:              Checking for existing gog manifests
(20:14:12) INFO:    [Nile]:             Refreshing library...
(20:14:12) INFO:    [Nile]:             Refreshing Amazon Games...
(20:14:12) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(20:14:13) INFO:    [Nile]:             Game list updated, got 51 games
(20:14:13) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(20:14:13) WARNING: [Backend]:          Failed to register protocol with OS.
(20:14:13) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(20:14:13) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(20:14:13) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(20:14:13) INFO:    [Connection]:       Connectivity: online
(20:14:13) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(20:14:13) INFO:    [Gog]:              Checking if login is valid
(20:14:13) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(20:14:13) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(20:14:13) INFO:    [Backend]:          
System Information:
CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Memory: 16.6 GB (used: 4 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation TU106M [GeForce RTX 2060 Mobile]
    IDs: D=1f15 V=10de SD=1332 SV=1025
    Driver: nvidia
  GPU 1:
    Name: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]
    IDs: D=3e9b V=8086 SD=1331 SV=1025
    Driver: i915
OS: Fedora Linux 40 (Workstation Edition) (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(20:14:14) INFO:    [Gog]:              Saved username to config file
(20:14:14) INFO:    [Nile]:             Saved user data to config file
(20:14:14) INFO:    [Frontend]:         Refreshing undefined Library
(20:14:14) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(20:14:14) INFO:    [Legendary]:        Refreshing library...
(20:14:14) INFO:    [Legendary]:        Refreshing Epic Games...
(20:14:14) INFO:    [Nile]:             Refreshing library...
(20:14:14) INFO:    [Nile]:             Refreshing Amazon Games...
(20:14:14) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(20:14:14) INFO:    [Nile]:             Game list updated, got 51 games
(20:14:14) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(20:14:14) INFO:    [Backend]:          Frontend Ready
(20:14:14) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(20:14:14) INFO:    [Gog]:              Getting GOG library
(20:14:14) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(20:14:14) INFO:    [Backend]:          Checking for current version changelog
(20:14:15) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(20:14:15) INFO:    [Winetricks]:       Downloading Winetricks
(20:14:16) INFO:    [Legendary]:        Game list updated, got 239 games & DLCs
(20:14:16) INFO:    [Gog]:              Saved games data
(20:14:16) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(20:14:16) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(20:14:17) INFO:    [Gog]:              Found 0 game(s) to update
(20:14:17) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(20:14:18) INFO:    [WineDownloader]:   Updating wine versions info
(20:14:18) INFO:    [WineDownloader]:   Fetching upstream information...
(20:14:19) INFO:    [Legendary]:        Found 0 games to update
(20:14:19) INFO:    [Nile]:             Looking for updates...
(20:14:19) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json
(20:14:19) INFO:    [Backend]:          Starting the Download Queue
(20:14:19) INFO:    [WineDownloader]:   wine versions updated
(20:14:24) INFO:    [Nile]:             Getting more details
(20:14:24) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.6ed13be7-1d52-42b0-af03-9f487492ae93
(20:14:24) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(20:14:25) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Module.getInstallInfo$2 [as getInstallInfo] (/app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:95:5537)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:235:5349
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)
(20:15:39) INFO:    [Nile]:             Getting more details
(20:15:39) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.bc8c2cf6-ded7-42fb-91d9-d0865af9e57a
(20:15:39) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(20:15:40) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Module.getInstallInfo$2 [as getInstallInfo] (/app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:95:5537)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:235:5349
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)
(20:15:58) INFO:    [WineDownloader]:   Removed wine version Proton-GE-latest succesfully.
(20:16:05) INFO:    [WineDownloader]:   Start installation of wine version Wine-GE-latest
(20:16:06) INFO:    [WineDownloader]:   Start installation of wine version Proton-GE-latest
(20:16:08) INFO:    [Backend]:          Downloaded: 52.6 MB / 222.76 MB  @34.22 MB/s (23.61%)
(20:16:09) INFO:    [Backend]:          Downloaded: 113.82 MB / 222.76 MB  @25.95 MB/s (51.10%)
(20:16:10) INFO:    [Backend]:          Downloaded: 20.26 MB / 413.26 MB  @11.42 MB/s (4.90%)
(20:16:10) INFO:    [Backend]:          Downloaded: 151.88 MB / 222.76 MB  @35.98 MB/s (68.18%)
(20:16:11) INFO:    [Backend]:          Downloaded: 50.45 MB / 413.26 MB  @26.2 MB/s (12.21%)
(20:16:12) INFO:    [Backend]:          Downloaded: 192.17 MB / 222.76 MB  @27.44 MB/s (86.27%)
(20:16:12) INFO:    [Backend]:          Downloaded: 82.69 MB / 413.26 MB  @22.42 MB/s (20.01%)
(20:16:13) INFO:    [Backend]:          Downloaded: 222.08 MB / 222.76 MB  @13.9 MB/s (99.70%)
(20:16:13) INFO:    [Backend]:          Downloaded: 143.91 MB / 413.26 MB  @40.39 MB/s (34.82%)
(20:16:14) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-26/wine-lutris-GE-Proton8-26-x86_64.tar.xz
(20:16:15) INFO:    [Backend]:          Extracting /home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/wine-lutris-GE-Proton8-26-x86_64.tar.xz to /home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-latest using native tar
(20:16:15) INFO:    [Backend]:          Downloaded: 167.56 MB / 413.26 MB  @2.73 MB/s (40.54%)
(20:16:16) INFO:    [Backend]:          Downloaded: 229.91 MB / 413.26 MB  @40.76 MB/s (55.63%)
(20:16:17) INFO:    [Backend]:          Downloaded: 277.87 MB / 413.26 MB  @43.56 MB/s (67.24%)
(20:16:18) INFO:    [Backend]:          Downloaded: 317.64 MB / 413.26 MB  @44.22 MB/s (76.86%)
(20:16:19) INFO:    [Backend]:          Downloaded: 365.96 MB / 413.26 MB  @52.14 MB/s (88.55%)
(20:16:20) INFO:    [Backend]:          Downloaded: 410.12 MB / 413.26 MB  @28.26 MB/s (99.24%)
(20:16:22) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton9-10/GE-Proton9-10.tar.gz
(20:16:23) INFO:    [Backend]:          Extracting /home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/proton/GE-Proton9-10.tar.gz to /home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/proton/Proton-GE-latest using native tar
(20:16:36) INFO:    [WineDownloader]:   Finished installation of wine version Proton-GE-latest
(20:16:38) INFO:    [WineDownloader]:   Finished installation of wine version Wine-GE-latest
(20:17:23) INFO:    [Frontend]:         Refreshing undefined Library
(20:17:23) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(20:17:23) INFO:    [Legendary]:        Refreshing library...
(20:17:23) INFO:    [Legendary]:        Refreshing Epic Games...
(20:17:23) INFO:    [Nile]:             Refreshing library...
(20:17:23) INFO:    [Nile]:             Refreshing Amazon Games...
(20:17:23) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(20:17:23) INFO:    [Nile]:             Game list updated, got 51 games
(20:17:23) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(20:17:24) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(20:17:24) INFO:    [Gog]:              Getting GOG library
(20:17:24) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(20:17:25) INFO:    [Gog]:              Saved games data
(20:17:26) INFO:    [Legendary]:        Game list updated, got 239 games & DLCs
(20:17:39) INFO:    [Nile]:             Getting more details
(20:17:39) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/alecerzea/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.78eec9ac-6cd5-4534-854a-47fe4c702d17
(20:17:39) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(20:17:40) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Module.getInstallInfo$2 [as getInstallInfo] (/app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:95:5537)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:235:5349
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)
(20:19:13) INFO:    [Backend]:          Heroic: Setting discordRPC to true (previous value: undefined)
(20:19:18) INFO:    [Backend]:          Heroic: Setting discordRPC to false (previous value: true)
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

It should let me install the games normally, I remember like some months ago I didnt had any issues 

### Screenshots

![image](https://github.com/user-attachments/assets/2eb476f5-9ebf-4e53-9401-5cb1ccec66bf)
![image](https://github.com/user-attachments/assets/3a794189-9d8e-4e42-b3d7-224be2e52c69)

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]:Fedora 40

**Comment by Lariaa** [comment]
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3850
is your place to got to until the next heroic release is tagged.
You need to update your nile-binary.

**Comment by RafaelLinux** [comment]
The same mistake. Will not allow me to install or view game information. If I click on the game cover, for a few seconds, it shows the cover and some information, but immediately shows the window with the options to clear Heroic cache or reset Heroic. Neither option works. I even thought the problem was that I didn't have Wine installed, so I installed it, but nothing changed. Exactly the same problem.

In console, I can see this errors after clicking in the game cover:
```
(00:37:18) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Everdream Valley
(00:37:18) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Everdream Valley
(00:37:18) INFO:    [Nile]:             Getting more details
(00:37:18) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/myuser/.config/heroic/nile_config /tmp/.mount_Heroic2vlKAQ/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.65f323b0-349c-4273-83be-8ac8456173a0
(00:37:18) INFO:    [Nile]:             Getting more details
(00:37:18) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/myuser/.config/heroic/nile_config /tmp/.mount_Heroic2vlKAQ/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.65f323b0-349c-4273-83be-8ac8456173a0
(00:37:19) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Module.getInstallInfo$2 [as getInstallInfo] (/tmp/.mount_Heroic2vlKAQ/resources/app.asar/build/electron/main.159a68a5.js:95:5537)
    at async /tmp/.mount_Heroic2vlKAQ/resources/app.asar/build/electron/main.159a68a5.js:235:5349
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)
(00:37:19) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Module.getInstallInfo$2 [as getInstallInfo] (/tmp/.mount_Heroic2vlKAQ/resources/app.asar/build/electron/main.159a68a5.js:95:5537)
    at async /tmp/.mount_Heroic2vlKAQ/resources/app.asar/build/electron/main.159a68a5.js:235:5349
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)
(00:37:19) ERROR:   [Frontend]:         Cannot get game info
(00:37:19) ERROR:   [Frontend]:         Cannot get game info
(00:37:19) ERROR:   [Frontend]:         Cannot get game info

```


![image](https://github.com/user-attachments/assets/8aa56912-42fb-40cd-8f74-7072c1e35ec5)

![image](https://github.com/user-attachments/assets/1e99d6c6-625c-4147-8e10-451bd8cbfc73)

```

CPU: 24x AMD Ryzen 9 3900X 12-Core Processor
Memory: 33.57 GB (used: 23.26 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 33 [Radeon RX 7600/7600 XT/7600M XT/7600S/7700S / PRO W7600]
    IDs: D=7480 V=1002 SD=7601 SV=1eae
    Driver: amdgpu
OS: openSUSE Tumbleweed 6.9.9-1-default (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar
```
