### ISSUE TITLE
Epic games Legendary error

### ISSUE THREAD

**Issue by akk181** [Heroic-Games-Launcher/HeroicGamesLauncher#3893]
### Describe the bug

<img width="1440" alt="Screenshot 2024-08-02 at 07 22 03" src="https://github.com/user-attachments/assets/6d9ff9cd-92a4-4568-93c9-c01f6a4a4173">

When I open the game this error show up even tho I tried Epic Alternative login method.

### Add logs

```text
An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "urllib3/connection.py", line 198, in _new_connFile "urllib3/util/connection.py", line 85, in create_connection
File "urllib3/util/connection.py", line 73, in create_connection
socket.timeout: timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "urllib3/connectionpool.py", line 793, in urlopen
File "urllib3/connectionpool.py", line 491, in _make_requestFile "urllib3/connectionpool.py", line 467, in _make_request
File "urllib3/connectionpool.py", line 1099, in _validate_conn
File "urllib3/connection.py", line 616, in connect
File "urllib3/connection.py", line 207, in _new_connurllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x1104ba0d0>, 'Connection to launcher-public-service-prod06.ol.epicgames.com timed out. (connect timeout=10)')
The above exception was the direct cause of the following exception:Traceback (most recent call last):
File "requests/adapters.py", line 486, in sendFile "urllib3/connectionpool.py", line 847, in urlopenFile "urllib3/util/retry.py", line 515, in incrementurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Max retries exceeded with url: /launcher/api/public/assets/Mac?label=Live (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1104ba0d0>, 'Connection to launcher-public-service-prod06.ol.epicgames.com timed out. (connect timeout=10)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "legendary/cli.py", line 3161, in <module>File "legendary/cli.py", line 3072, in mainFile "legendary/cli.py", line 200, in list_gamesFile "legendary/core.py", line 413, in get_game_and_dlc_listFile "legendary/core.py", line 359, in get_assetsFile "legendary/api/egs.py", line 169, in get_game_assetsFile "requests/sessions.py", line 602, in getFile "requests/sessions.py", line 589, in requestFile "requests/sessions.py", line 703, in sendFile "requests/adapters.py", line 507, in sendrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Max retries exceeded with url: /launcher/api/public/assets/Mac?label=Live (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1104ba0d0>, 'Connection to launcher-public-service-prod06.ol.epicgames.com timed out. (connect timeout=10)'))
[6412]Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Go to library.
2. Click on Grand Theft Auto V
3. See legendary error
<img width="1440" alt="Screenshot 2024-08-02 at 07 22 03" src="https://github.com/user-attachments/assets/bb0b58f8-aaad-40cb-9fa9-207925fca5f6">

### Expected behavior

no error

### Screenshots

<img width="1440" alt="Screenshot 2024-08-02 at 07 22 03" src="https://github.com/user-attachments/assets/aed822e5-f156-4f40-8115-3f7353eed4b0">

### Heroic Version

Latest Stable

### System Information

Mac OS M1 air Sonoma 14.5

**Comment by akk181** [comment]
Please someone help me.

**Comment by yoshimo** [comment]
The error asks you to logout and login again, did you try that yet?

**Comment by akk181** [comment]
> The error asks you to logout and login again, did you try that yet?
> 
> 

Yes i did that 6 times and still the same error. I think they need to fix Heroic games launcher. This error shown up this morning.

**Comment by akk181** [comment]
Is that only me or someone get the same error like me?

**Comment by akk181** [comment]
I think Heroic games launcher's developers are neglecting their users.

**Comment by CommandMC** [comment]
> I think Heroic games launcher's developers are neglecting their users.

I'm sorry, could you send me your order number for the premium support package?
Oh right, we don't have anything like that. People working on Heroic are doing so in their free time, please be more patient

> `requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Max retries exceeded with url: /launcher/api/public/assets/Mac?label=Live`

Heroic is unable to fetch the games in your account, as it can't connect to this URL. Please make sure you're not behind any system-wide adblocking services (some VPNs also do this)

**Comment by akk181** [comment]
> > I think Heroic games launcher's developers are neglecting their users.
> 
> I'm sorry, could you send me your order number for the premium support package? Oh right, we don't have anything like that. People working on Heroic are doing so in their free time, please be more patient
> 
> > `requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Max retries exceeded with url: /launcher/api/public/assets/Mac?label=Live`
> 
> Heroic is unable to fetch the games in your account, as it can't connect to this URL. Please make sure you're not behind any system-wide adblocking services (some VPNs also do this)

First of all, I want to apologize for my bad behavior. Heroic is working perfectly fine when I connected to VPN. The reas I need to use VPN is I am currently living in Myanmar and also I think because of current situations in Myanmar, the government block something related to internet. Again, I would like to apologize for my behavior.

**Comment by rairay91** [comment]
you live in Myanmar but i live in India, and there is notjing related to site blocking or internet blocking by government or isp provider. But still i am havin that error. Epic game launcher from Lutis as well as Epic games website working just fine. And if there is anything related to net blocking for specific app or service system wide, i would have known.
By the way my system is - Garuda kde (which means arch+kde)

**Comment by akk181** [comment]
> you live in Myanmar but i live in India, and there is nothing related to site blocking or internet blocking by government or isp provider. But still i am having this error. Epic game launcher from Lutis as well as Epic games website working just fine. And if there is anything related to net blocking for specific app or service system wide, i would have known.
> 
> By the way my system is - Garuda kde (which means arch+kde)
> 
> 
> 
> I can't download games, can't play online games, can't access epic gog and amazon prime website(sometime for some reason that works, i mean i can only login to accounts and access websites but no luck at downloading games), also when i try to download game downloading stuck at 0% and some heroic crashes afyer couple of minutes.

Did you try using VPN? When I had that problem, I connected VPN and it's working. My VPN of choice is VPN Buck. It's free tho. So, try using that VPN and it's not available in your region, try different one

**Comment by redglobuli** [comment]
I had basically the same issue. Legendary by itself worked normally, i could log out and login again.

In heroic i always had the error seen above, i logged out of epic, tried to login again but that didn't work. None of the two worked.

So i copied the user.json from legendary over the heroic one and everything started working again.

`cp ~/.config/legendary/user.json ~/.config/heroic/legendaryConfig/legendary/`

**Comment by martinjakl** [comment]
I have the same issue. In legendary it helps me to increase the timeout with -A parameter. Is there some possibility to increase the timeout in heroic?

**Comment by martinjakl** [comment]
Workaround: Create script like

```
#!/bin/bash

/usr/lib/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary -A 100 $@

```
and set it as legendary binary

**Comment by JohnnyBFG** [comment]
Hi, problem is in Legendary itself, which has a timeout set to 10 seconds, which is too short – either because Epic Games responds too slowly or because the user has an extremely large library (which is not a problem when we're talking about Epic giving away free games – I have around 1440).
And there is an open pull request that addresses this issue [#26](https://github.com/Heroic-Games-Launcher/legendary/pull/26)

**Comment by sgghostrider** [comment]
I as well have a massive library and never were able to use this, tried for years... not on my many reinstalls of windows neither now that i migrated to linux.... i still try every so and then and check the issues here to see if it gets actually fixed, but it's always the same error... "An error has occurred! Try to Logout and Login on your Epic account." or a variant of it... would be nice to see it fixed one day...

**Comment by CommandMC** [comment]
We've increased the timeout to 30 seconds with the latest release of Legendary ([relevant commit](<https://github.com/Heroic-Games-Launcher/legendary/commit/e843af741452f5a89cffdc87cce834a945cf4f21>)), shipped with Heroic 2.19. Please try reproducing this issue with the new version. If you are still able to reproduce it, please add your Legendary log file to this issue

**Comment by martinjakl** [comment]
30 is not enough for me. I'm using 100 in my workaround script. Would be nice if it would be configurable.

**Comment by sgghostrider** [comment]
I don't think the timeout function is all the useful at all IMHO, not like it hangs the program, stop other procesess or anything problematic, and it already has done the request so it's not like we are saving resources either, specially if it just errors after surpassing the time limit, it would be good practice to just eliminate the timeout or set it to something really high like 3600 seconds and show a prompt or something to the user with a "Cancel" button to let the user decide how much is "too much" and only cancel it if REALLY long time has passed.

But just setting it to something really high or letting us set it in settings would be more than welcome, for reference it took like 5 min for Lutris to scan and show the list of my games, so i don't think 30 seconds is even close to be enough XD

Edit: BTW, changing the legendary binary workaround worked quite well, it took less time than Lutris, around 3-4 min, but would have been nice a little bit more... **detailed** instructions... in my case the path was different and did not know where or how to set that "binary" until i stumbled on it by chance in settings.

**Comment by JohnnyBFG** [comment]
@CommandMC Hi, thank you for your work.
I tried Heroic 2.19.1 on two computers: Fedora 43 (RPM package) and Windows 10.
Unfortunately, I got the similar error message as before:
```
An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "urllib3\connectionpool.py", line 534, in _make_request
File "urllib3\connection.py", line 571, in getresponse
File "http\client.py", line 1450, in getresponse
File "http\client.py", line 336, in beginFile "http\client.py", line 297, in _read_status
File "socket.py", line 719, in readinto
File "ssl.py", line 1304, in recv_into
File "ssl.py", line 1138, in read
TimeoutError: The read operation timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "requests\adapters.py", line 644, in send
File "urllib3\connectionpool.py", line 841, in urlopen
File "urllib3\util\retry.py", line 490, in increment
File "urllib3\util\util.py", line 39, in reraise
File "urllib3\connectionpool.py", line 787, in urlopen
File "urllib3\connectionpool.py", line 536, in _make_request
File "urllib3\connectionpool.py", line 367, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Read timed out. (read timeout=10)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):File "cli.py", line 3333, in <module>
File "cli.py", line 3242, in main
File "cli.py", line 203, in list_games
File "legendary\core.py", line 415, in get_game_and_dlc_list
File "legendary\core.py", line 361, in get_assets
File "legendary\api\egs.py", line 187, in get_game_assets
File "requests\sessions.py", line 602, in get
File "requests\sessions.py", line 589, in request
File "requests\sessions.py", line 703, in send
File "requests\adapters.py", line 690, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Read timed out. (read timeout=10)[PYI-19724:ERROR] Failed to executescript 'cli'due to unhandled exception!
```
Just out of curiosity, I tried listing my games directly through Legendary using the command "time legendary -A 100 list" (time is used to measure duration), and it took 0m16.531s and listed 1734 items (many of which were Unreal Engine assets).

~~I would like to add that I don't know if there is a workaround for Windows (other than installing Epic).
I tried to enter a bat file or shortcut as a Legendary binary file, but it was always rejected by the text field validation because it is not an exe file. Is it possible to input other types of executable files on Windows?~~

Workaround for Windows is following bat script set as legendary binary:
```
@echo off
"C:\Program Files\Heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary.exe" -A 100 %*
```

**Comment by Lavora82** [comment]
> We've increased the timeout to 30 seconds with the latest release of Legendary ([relevant commit](https://github.com/Heroic-Games-Launcher/legendary/commit/e843af741452f5a89cffdc87cce834a945cf4f21)), shipped with Heroic 2.19. Please try reproducing this issue with the new version. If you are still able to reproduce it, please add your Legendary log file to this issue


(17:43:34) [INFO]:    Running command: LEGENDARY_CONFIG_PATH=/home/lavora/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version 

legendary version "0.20.39", codename "This Vortal Coil (Heroic)"
(17:44:36) [INFO]:    Running command: LEGENDARY_CONFIG_PATH=/home/lavora/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version 

(17:44:36) [INFO]:    Updating EOS Overlay information: LEGENDARY_CONFIG_PATH=/home/lavora/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary status 

legendary version "0.20.39", codename "This Vortal Coil (Heroic)"
Epic account: <not logged in>
Games available: 0
Games installed: 0
EGL Sync enabled: False
Config directory: /home/lavora/.config/heroic/legendaryConfig/legendary
Platform (System): Linux-6.8.0-90-generic-x86_64-with-glibc2.39 (posix)

Legendary version: 0.20.39 - "This Vortal Coil (Heroic)"
Update available: no
(17:48:09) [INFO]:    Logging in: LEGENDARY_CONFIG_PATH=/home/lavora/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary auth --code <redacted> 

[cli] INFO: Testing existing login data if present...
[cli] INFO: Successfully logged in as "Lavora82"
(17:48:10) [INFO]:    Running command: LEGENDARY_CONFIG_PATH=/home/lavora/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party 

[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Getting game list... (this may take a while)
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 534, in _make_request
  File "urllib3/connection.py", line 571, in getresponse
  File "http/client.py", line 1450, in getresponse
  File "http/client.py", line 336, in begin
  File "http/client.py", line 297, in _read_status
  File "socket.py", line 725, in readinto
  File "ssl.py", line 1304, in recv_into
  File "ssl.py", line 1138, in read
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 644, in send
  File "urllib3/connectionpool.py", line 841, in urlopen
  File "urllib3/util/retry.py", line 490, in increment
  File "urllib3/util/util.py", line 39, in reraise
  File "urllib3/connectionpool.py", line 787, in urlopen
  File "urllib3/connectionpool.py", line 536, in _make_request
  File "urllib3/connectionpool.py", line 367, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 3333, in <module>
  File "cli.py", line 3242, in main
  File "cli.py", line 203, in list_games
  File "legendary/core.py", line 415, in get_game_and_dlc_list
  File "legendary/core.py", line 361, in get_assets
  File "legendary/api/egs.py", line 187, in get_game_assets
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 690, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Read timed out. (read timeout=10)
[PYI-36883:ERROR] Failed to execute script 'cli' due to unhandled exception!
(17:48:21) [INFO]:    Running command: LEGENDARY_CONFIG_PATH=/home/lavora/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party 

[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Getting game list... (this may take a while)
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 534, in _make_request
  File "urllib3/connection.py", line 571, in getresponse
  File "http/client.py", line 1450, in getresponse
  File "http/client.py", line 336, in begin
  File "http/client.py", line 297, in _read_status
  File "socket.py", line 725, in readinto
  File "ssl.py", line 1304, in recv_into
  File "ssl.py", line 1138, in read
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 644, in send
  File "urllib3/connectionpool.py", line 841, in urlopen
  File "urllib3/util/retry.py", line 490, in increment
  File "urllib3/util/util.py", line 39, in reraise
  File "urllib3/connectionpool.py", line 787, in urlopen
  File "urllib3/connectionpool.py", line 536, in _make_request
  File "urllib3/connectionpool.py", line 367, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 3333, in <module>
  File "cli.py", line 3242, in main
  File "cli.py", line 203, in list_games
  File "legendary/core.py", line 415, in get_game_and_dlc_list
  File "legendary/core.py", line 361, in get_assets
  File "legendary/api/egs.py", line 187, in get_game_assets
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 690, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Read timed out. (read timeout=10)
[PYI-36887:ERROR] Failed to execute script 'cli' due to unhandled exception!
(17:48:42) [INFO]:    Running command: LEGENDARY_CONFIG_PATH=/home/lavora/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party 

[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Getting game list... (this may take a while)
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 534, in _make_request
  File "urllib3/connection.py", line 571, in getresponse
  File "http/client.py", line 1450, in getresponse
  File "http/client.py", line 336, in begin
  File "http/client.py", line 297, in _read_status
  File "socket.py", line 725, in readinto
  File "ssl.py", line 1304, in recv_into
  File "ssl.py", line 1138, in read
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 644, in send
  File "urllib3/connectionpool.py", line 841, in urlopen
  File "urllib3/util/retry.py", line 490, in increment
  File "urllib3/util/util.py", line 39, in reraise
  File "urllib3/connectionpool.py", line 787, in urlopen
  File "urllib3/connectionpool.py", line 536, in _make_request
  File "urllib3/connectionpool.py", line 367, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 3333, in <module>
  File "cli.py", line 3242, in main
  File "cli.py", line 203, in list_games
  File "legendary/core.py", line 415, in get_game_and_dlc_list
  File "legendary/core.py", line 361, in get_assets
  File "legendary/api/egs.py", line 187, in get_game_assets
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 690, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Read timed out. (read timeout=10)
[PYI-36909:ERROR] Failed to execute script 'cli' due to unhandled exception!
(17:48:54) [INFO]:    Checking for game updates: LEGENDARY_CONFIG_PATH=/home/lavora/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party 

[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Getting game list... (this may take a while)
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 534, in _make_request
  File "urllib3/connection.py", line 571, in getresponse
  File "http/client.py", line 1450, in getresponse
  File "http/client.py", line 336, in begin
  File "http/client.py", line 297, in _read_status
  File "socket.py", line 725, in readinto
  File "ssl.py", line 1304, in recv_into
  File "ssl.py", line 1138, in read
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 644, in send
  File "urllib3/connectionpool.py", line 841, in urlopen
  File "urllib3/util/retry.py", line 490, in increment
  File "urllib3/util/util.py", line 39, in reraise
  File "urllib3/connectionpool.py", line 787, in urlopen
  File "urllib3/connectionpool.py", line 536, in _make_request
  File "urllib3/connectionpool.py", line 367, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 3333, in <module>
  File "cli.py", line 3242, in main
  File "cli.py", line 203, in list_games
  File "legendary/core.py", line 415, in get_game_and_dlc_list
  File "legendary/core.py", line 361, in get_assets
  File "legendary/api/egs.py", line 187, in get_game_assets
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 690, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Read timed out. (read timeout=10)
[PYI-36989:ERROR] Failed to execute script 'cli' due to unhandled exception!
(17:49:06) [INFO]:    Running command: LEGENDARY_CONFIG_PATH=/home/lavora/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party 

[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Getting game list... (this may take a while)
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 534, in _make_request
  File "urllib3/connection.py", line 571, in getresponse
  File "http/client.py", line 1450, in getresponse
  File "http/client.py", line 336, in begin
  File "http/client.py", line 297, in _read_status
  File "socket.py", line 725, in readinto
  File "ssl.py", line 1304, in recv_into
  File "ssl.py", line 1138, in read
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 644, in send
  File "urllib3/connectionpool.py", line 841, in urlopen
  File "urllib3/util/retry.py", line 490, in increment
  File "urllib3/util/util.py", line 39, in reraise
  File "urllib3/connectionpool.py", line 787, in urlopen
  File "urllib3/connectionpool.py", line 536, in _make_request
  File "urllib3/connectionpool.py", line 367, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 3333, in <module>
  File "cli.py", line 3242, in main
  File "cli.py", line 203, in list_games
  File "legendary/core.py", line 415, in get_game_and_dlc_list
  File "legendary/core.py", line 361, in get_assets
  File "legendary/api/egs.py", line 187, in get_game_assets
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 690, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Read timed out. (read timeout=10)
[PYI-37098:ERROR] Failed to execute script 'cli' due to unhandled exception!

**Comment by gassssss** [comment]
This is happening to me too now, Heroic 2.22.3, the script workaround suggested above with 100s api timeout fixes the issue.
```

An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/urllib3/connectionpool.py", line 534, in _make_request
response = conn.getresponse()
File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/urllib3/connection.py", line 571, in getresponse
httplib_response = super().getresponse()
File "/usr/lib/python3.14/http/client.py", line 1478, in getresponse
response.begin()
~~~~~~~~~~~~~~^^
File "/usr/lib/python3.14/http/client.py", line 343, in begin
version, status, reason = self._read_status()
~~~~~~~~~~~~~~~~~^^
File "/usr/lib/python3.14/http/client.py", line 304, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
File "/usr/lib/python3.14/socket.py", line 729, in readinto
return self._sock.recv_into(b)
~~~~~~~~~~~~~~~~~~~~^^^
File "/usr/lib/python3.14/ssl.py", line 1304, in recv_into
return self.read(nbytes, buffer)
~~~~~~~~~^^^^^^^^^^^^^^^^
File "/usr/lib/python3.14/ssl.py", line 1138, in read
return self._sslobj.read(len, buffer)
~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^TimeoutError: The read operation timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/requests/adapters.py", line 645, in send
resp = conn.urlopen(
method=request.method,
...<9 lines>...
chunked=chunked,
)
File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/urllib3/connectionpool.py", line 842, in urlopen
retries = retries.increment(
method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
)
File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/urllib3/util/retry.py", line 498, in increment
raise reraise(type(error), error, _stacktrace)
~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/urllib3/util/util.py", line 39, in reraise
raise value
File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/urllib3/connectionpool.py", line 788, in urlopen
response = self._make_request(
conn,
...<10 lines>...
**response_kw,
)File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/urllib3/connectionpool.py", line 536, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/urllib3/connectionpool.py", line 367, in _raise_timeout
raise ReadTimeoutError(
self, url, f"Read timed out. (read timeout={timeout_value})"
) from err
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Read timed out. (read timeout=10)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):File "<frozen runpy>", line 203, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/__main__.py", line 42, in <module>
legendary.cli.main()
~~~~~~~~~~~~~~~~~~^^
File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/legendary/cli.py", line 3171, in main
cli.list_games(args)
~~~~~~~~~~~~~~^^^^^^
File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/legendary/cli.py", line 221, in list_games
games, dlc_list = self.core.get_game_and_dlc_list(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
platform=args.platform, skip_ue=not args.include_ue,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
force_refresh=args.force_refresh
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)
^
File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/legendary/core.py", line 535, in get_game_and_dlc_list
self.get_assets(update_assets=update_assets, platform=_platform)
~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/legendary/core.py", line 476, in get_assets
self.egs.get_game_assets(platform=platform)
~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/legendary/api/egs.py", line 173, in get_game_assets
r = self.session.get(f'https://{self._launcher_host}/launcher/api/public/assets/{platform}',
params=dict(label=label), timeout=self.request_timeout)
File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/requests/sessions.py", line 605, in get
return self.request("GET", url, **kwargs)
~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/requests/sessions.py", line 592, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/requests/sessions.py", line 706, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/heroic-games-launcher/app.asar.unpacked/build/bin/x64/linux/./legendary/requests/adapters.py", line 691, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='launcher-public-service-prod06.ol.epicgames.com', port=443): Read timed out. (read timeout=10)
```
