### ISSUE TITLE
Heroic always blocks sleep

### ISSUE THREAD

**Issue by Slater91** [Heroic-Games-Launcher/HeroicGamesLauncher#3910]
### Describe the bug

Heroic has started blocking sleep and screen lock/sleep; while this can be useful when a game is being played, Heroic starts blocking sleep as soon as it is launched. This is undesirable as it keeps the computer and the screen(s) awake as long as the program is running.

### Add logs

```text
(12:36:02) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(12:36:02) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(12:36:02) INFO:    [Connection]:       Connectivity: check-online
(12:36:02) INFO:    [Connection]:       Pinging external endpoints
(12:36:02) INFO:    [Gog]:              Checking for existing gog manifests
(12:36:02) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(12:36:03) WARNING: [Backend]:          Protocol already registered.
(12:36:03) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/riccardo/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(12:36:03) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/riccardo/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riccardo/.config/heroic/gog_store/auth.json --version
(12:36:03) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/riccardo/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(12:36:03) INFO:    [Connection]:       Connectivity: online
(12:36:03) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/riccardo/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riccardo/.config/heroic/gog_store/auth.json auth
(12:36:03) INFO:    [Gog]:              Checking if login is valid
(12:36:03) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/riccardo/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riccardo/.config/heroic/gog_store/auth.json auth
(12:36:03) INFO:    [Gog]:              Updating redist, reason - new buildId
(12:36:03) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/riccardo/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riccardo/.config/heroic/gog_store/auth.json auth
(12:36:03) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(12:36:03) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH=/home/riccardo/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riccardo/.config/heroic/gog_store/auth.json info gog-redist --os windows
(12:36:03) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 7 1700X Eight-Core Processor
Memory: 33.58 GB (used: 14.82 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Radeon RX 5600 XT
    IDs: D=731f V=1002 SD=e411 SV=1da2
    Driver: amdgpu
  GPU 1:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Lexa XT [Radeon PRO WX 3100]
    IDs: D=6985 V=1002 SD=0b0c SV=1002
    Driver: amdgpu
OS: KDE neon 5.27 (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(12:36:04) INFO:    [Frontend]:         Refreshing undefined Library
(12:36:04) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(12:36:04) INFO:    [Legendary]:        Refreshing library...
(12:36:04) INFO:    [Legendary]:        Refreshing Epic Games...
(12:36:04) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/riccardo/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riccardo/.config/heroic/gog_store/auth.json auth
(12:36:04) INFO:    [Backend]:          Frontend Ready
(12:36:04) INFO:    [Gog]:              Saved username to config file
(12:36:04) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/riccardo/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(12:36:04) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(12:36:04) INFO:    [DownloadManager]:  Galaxy Common Redistributables  was added to the download queue.
(12:36:04) INFO:    [Backend]:          Preventing machine to sleep
(12:36:04) INFO:    [Gog]:              Updating GOG redistributables
(12:36:04) INFO:    [Gog]:              GOG REDIST:: GOGDL_CONFIG_PATH=/home/riccardo/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riccardo/.config/heroic/gog_store/auth.json redist --ids ISI,DirectX,DOSBox074_2CS --path /home/riccardo/.config/heroic/tools/redist/gog
(12:36:04) DEBUG:   [Gog]:              Logging to file "/home/riccardo/.config/heroic/GamesConfig/gog-redist.log"
(12:36:04) INFO:    [Gog]:              Getting GOG library
(12:36:04) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/riccardo/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riccardo/.config/heroic/gog_store/auth.json auth
(12:36:04) INFO:    [Backend]:          Checking for new Heroic Updates
(12:36:04) INFO:    [Backend]:          Checking for current version changelog
(12:36:05) INFO:    [DownloadManager]:  gog-redist added to download manager finished.
(12:36:05) INFO:    [DownloadManager]:  gog-redist removed from download manager.
(12:36:05) INFO:    [Winetricks]:       Downloading Winetricks
(12:36:05) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1891038081 Release with per platform id: gog_1891038081 not found
(12:36:05) WARNING: [Backend]:          No clientId in goggame-1207659111.info file. Cannot resolve save path
(12:36:05) WARNING: [Backend]:          No clientId in goggame-1207659110.info file. Cannot resolve save path
(12:36:05) WARNING: [Backend]:          No clientId in goggame-1207659139.info file. Cannot resolve save path
(12:36:06) INFO:    [Gog]:              Saved games data
(12:36:06) INFO:    [Legendary]:        Game list updated, got 98 games & DLCs
(12:36:06) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(12:36:06) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/riccardo/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riccardo/.config/heroic/gog_store/auth.json auth
(12:36:07) INFO:    [Gog]:              Found 0 game(s) to update
(12:36:07) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/riccardo/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(12:36:07) INFO:    [WineDownloader]:   Updating wine versions info
(12:36:07) INFO:    [WineDownloader]:   Fetching upstream information...
(12:36:08) DEBUG:   [Legendary]:        Update is available for 9d2d0eb64d5c44529cece33fe2a46482: 1.0.2944.0_v2 != 1.0.3274.0_v2
(12:36:08) INFO:    [Legendary]:        Found 1 game to update
(12:36:09) INFO:    [WineDownloader]:   wine versions updated
(12:36:09) INFO:    [Backend]:          Starting the Download Queue
```

### Steps to reproduce

1. Open Heroic

### Expected behavior

Heroic does not block sleep while no game is running.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: KDE Neon (based on Ubuntu 22.04)

**Comment by arielj** [comment]
is this a consistent issue? I can't reproduce it

From that log I see `Galaxy Common Redistributables  was added to the download queue` and maybe that's blocking the sleep because it's downloading something?

**Comment by Klajan** [comment]
I have the same problem with `2.18.1`. This issue is always present when starting Heroic.

From the logs it appears that the sleep block should have been removed, but it is still present
`(10:27:28) [INFO]:    [Backend]:         Stopping Power Saver Blocker`
<img width="542" height="542" alt="Image" src="https://github.com/user-attachments/assets/aa804f70-a974-428a-9d64-fdd092f76351" />
This is the full log:
```
(10:27:24) [INFO]:    [Backend]:         System Information: CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
Memory: 16.63 GB (used: 5.06 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile]
    IDs: D=1c8d V=10de SD=1128 SV=1025
    Driver: nvidia
  GPU 1:
    Name: Intel Corporation HD Graphics 630
    IDs: D=591b V=8086 SD=1127 SV=1025
    Driver: i915
OS: EndeavourOS 6.16.10-arch1-1 (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.18.1 "Waterfall Beard" Jorul
  Legendary: 0.20.37 Exit 17 (Heroic)
  gogdl: 1.1.2
  comet: comet 0.2.0
  Nile: 1.1.2 Will A. Zeppeli
(10:27:24) [INFO]:    [Connection]:      Connectivity: check-online
(10:27:24) [INFO]:    [Connection]:      Pinging external endpoints
(10:27:24) [INFO]:    [Backend]:         Starting Plausible Analytics
(10:27:24) [INFO]:    [Backend]:         Shared Data: {"version":"2.18.1","gog":true,"epic":true,"amazon":true,"sideloaded":false,"providers":"gog, epic, amazon","OS":"linux","isFlatpak":false,"isAppImage":false,"isSnap":false,"isSteamDeckGameMode":false,"isSteamDeck":false}
(10:27:24) [INFO]:    [Gog]:             Checking for existing gog manifests
(10:27:24) [INFO]:    [Nile]:            Refreshing library...
(10:27:24) [INFO]:    [Nile]:            Refreshing Amazon Games...
(10:27:24) [INFO]:    [Nile]:            Running command: NILE_CONFIG_PATH=~/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
(10:27:24) [INFO]:    [Nile]:            Game list updated, got 432 games
(10:27:24) [WARNING]: [Backend]:         Protocol already registered.
(10:27:24) [DEBUG]:   [Nile]:            Logging to file(s) "~/.local/state/Heroic/logs/runners/nile.log"
(10:27:24) [INFO]:    [Connection]:      Connectivity: online
(10:27:24) [INFO]:    [Gog]:             Running command: GOGDL_CONFIG_PATH=~/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path ~/.config/heroic/gog_store/auth.json auth
(10:27:24) [INFO]:    [Gog]:             Running command: GOGDL_CONFIG_PATH=~/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path ~/.config/heroic/gog_store/auth.json auth
(10:27:24) [INFO]:    [Gog]:             Checking if login is valid
(10:27:24) [INFO]:    [Gog]:             Running command: GOGDL_CONFIG_PATH=~/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path ~/.config/heroic/gog_store/auth.json auth
(10:27:24) [DEBUG]:   [Gog]:             Logging to file(s) "~/.local/state/Heroic/logs/runners/gog.log"
(10:27:24) [DEBUG]:   [Gog]:             Logging to file(s) "~/.local/state/Heroic/logs/runners/gog.log"
(10:27:24) [DEBUG]:   [Gog]:             Logging to file(s) "~/.local/state/Heroic/logs/runners/gog.log"
(10:27:24) [INFO]:    [Backend]:         AreWeAntiCheatYet data downloaded
(10:27:24) [INFO]:    [Gog]:             Updating redist, reason - new buildId
(10:27:24) [INFO]:    [Gog]:             Running command: GOGDL_CONFIG_PATH=~/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path ~/.config/heroic/gog_store/auth.json auth
(10:27:24) [DEBUG]:   [Gog]:             Logging to file(s) "~/.local/state/Heroic/logs/runners/gog.log"
(10:27:25) [INFO]:    [Gog]:             Getting game metadata: GOGDL_CONFIG_PATH=~/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path ~/.config/heroic/gog_store/auth.json info gog-redist --os windows
(10:27:25) [DEBUG]:   [Gog]:             Logging to file(s) "~/.local/state/Heroic/logs/runners/gog.log"
(10:27:25) [INFO]:    [Gog]:             GOG presence set
(10:27:25) [ERROR]:   [Gog]:             stdout = false and res.abort = false in getInstallInfo
(10:27:25) [INFO]:    [DownloadManager]: Galaxy Common Redistributables  was added to the download queue.
(10:27:25) [INFO]:    [Backend]:         Preventing machine to sleep
(10:27:25) [INFO]:    [Gog]:             Updating GOG redistributables
(10:27:25) [INFO]:    [Gog]:             GOG REDIST:: GOGDL_CONFIG_PATH=~/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path ~/.config/heroic/gog_store/auth.json redist --ids ISI,DirectX,MSVC2010_x64,MSVC2015_x64,dotNet4,dotNet45,MSVC2019_x64,MSVC2013 --path ~/.config/heroic/tools/redist/gog
(10:27:25) [DEBUG]:   [Gog]:             Logging to file(s) "~/.config/heroic/GamesConfig/gog-redist.log", "~/.local/state/Heroic/logs/runners/gog.log"
(10:27:25) [INFO]:    [Legendary]:       Running command: LEGENDARY_CONFIG_PATH=~/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version
(10:27:25) [INFO]:    [Gog]:             Running command: GOGDL_CONFIG_PATH=~/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path ~/.config/heroic/gog_store/auth.json --version
(10:27:25) [INFO]:    [Nile]:            Running command: NILE_CONFIG_PATH=~/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
(10:27:25) [DEBUG]:   [Gog]:             Logging to file(s) "~/.local/state/Heroic/logs/runners/gog.log"
(10:27:25) [DEBUG]:   [Nile]:            Logging to file(s) "~/.local/state/Heroic/logs/runners/nile.log"
(10:27:25) [INFO]:    [Nile]:            Saved user data to config file
(10:27:25) [DEBUG]:   [Legendary]:       Logging to file(s) "~/.local/state/Heroic/logs/runners/legendary.log"
(10:27:25) [INFO]:    [Frontend]:        Refreshing undefined Library
(10:27:25) [WARNING]: refresh not implemented on Sideload Library Manager
(10:27:25) [INFO]:    [Legendary]:       Refreshing library...
(10:27:25) [INFO]:    [Legendary]:       Refreshing Epic Games...
(10:27:25) [INFO]:    [Nile]:            Refreshing library...
(10:27:25) [INFO]:    [Nile]:            Refreshing Amazon Games...
(10:27:25) [INFO]:    [Nile]:            Running command: NILE_CONFIG_PATH=~/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
(10:27:25) [INFO]:    [Nile]:            Game list updated, got 432 games
(10:27:25) [INFO]:    [Gog]:             Running command: GOGDL_CONFIG_PATH=~/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path ~/.config/heroic/gog_store/auth.json auth
(10:27:25) [INFO]:    [Backend]:         Frontend Ready
(10:27:25) [INFO]:    [Backend]:         Preventing machine to sleep
(10:27:25) [DEBUG]:   [Nile]:            Logging to file(s) "~/.local/state/Heroic/logs/runners/nile.log"
(10:27:25) [DEBUG]:   [Gog]:             Logging to file(s) "~/.local/state/Heroic/logs/runners/gog.log"
(10:27:25) [INFO]:    [Legendary]:       Running command: LEGENDARY_CONFIG_PATH=~/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party
(10:27:25) [DEBUG]:   [Legendary]:       Logging to file(s) "~/.local/state/Heroic/logs/runners/legendary.log"
(10:27:26) [INFO]:    [Gog]:             Saved username to config file
(10:27:26) [INFO]:    [Gog]:             Getting GOG library
(10:27:26) [INFO]:    [Gog]:             Running command: GOGDL_CONFIG_PATH=~/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path ~/.config/heroic/gog_store/auth.json auth
(10:27:26) [DEBUG]:   [Gog]:             Logging to file(s) "~/.local/state/Heroic/logs/runners/gog.log"
(10:27:26) [INFO]:    [Backend]:         Checking for new Heroic Updates
(10:27:26) [INFO]:    [Backend]:         Checking for current version changelog
(10:27:27) [INFO]:    [Winetricks]:      Downloading Winetricks
(10:27:28) [INFO]:    [Gog]:             Saved games data
(10:27:28) [INFO]:    [Gog]:             Progress for Galaxy Common Redistributables: 50%/0.00MB/00:00:00 Down: 7.12MB/s / Disk: 24.88MB/s
(10:27:28) [INFO]:    [DownloadManager]: gog-redist added to download manager finished.
(10:27:28) [INFO]:    [DownloadManager]: gog-redist removed from download manager.
(10:27:28) [INFO]:    [Backend]:         Stopping Power Saver Blocker
(10:27:29) [INFO]:    [WineDownloader]:  Updating wine versions info
(10:27:29) [INFO]:    [WineDownloader]:  Fetching upstream information...
(10:27:30) [INFO]:    [WineDownloader]:  wine versions updated
(10:27:30) [INFO]:    [Backend]:         Starting the Download Queue
(10:27:36) [INFO]:    [Legendary]:       Game list updated, got 326 games & DLCs
(10:27:36) [WARNING]: listUpdateableGames not implemented on Sideload Library Manager
(10:27:36) [INFO]:    [Gog]:             Running command: GOGDL_CONFIG_PATH=~/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path ~/.config/heroic/gog_store/auth.json auth
(10:27:36) [DEBUG]:   [Gog]:             Logging to file(s) "~/.local/state/Heroic/logs/runners/gog.log"
(10:27:39) [INFO]:    [Gog]:             Found 1 game(s) to update
(10:27:39) [INFO]:    [Legendary]:       Checking for game updates: LEGENDARY_CONFIG_PATH=~/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party
(10:27:39) [DEBUG]:   [Legendary]:       Logging to file(s) "~/.local/state/Heroic/logs/runners/legendary.log"
(10:27:45) [WARNING]: [Legendary]:       Failed to parse games from ~/.config/heroic/legendaryConfig/legendary/installed.json with: Error: ENOENT: no such file or directory, open '~/.config/heroic/legendaryConfig/legendary/installed.json'
    at Object.readFileSync (node:fs:442:20)
    at Object.t.readFileSync (node:electron/js2c/node_init:2:10960)
    at Module.xi (/opt/Heroic/resources/app.asar/build/main/main.js:152:3641)
    at /opt/Heroic/resources/app.asar/build/main/main.js:176:2043
    at Session.<anonymous> (node:electron/js2c/browser_init:2:106823)
(10:27:45) [INFO]:    [Legendary]:       Found 0 games to update
(10:27:45) [INFO]:    [Nile]:            Looking for updates...
(10:27:45) [INFO]:    [Nile]:            Running command: NILE_CONFIG_PATH=~/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile list-updates --json
(10:27:45) [DEBUG]:   [Nile]:            Logging to file(s) "~/.local/state/Heroic/logs/runners/nile.log"
(10:32:25) [INFO]:    [Gog]:             Running command: GOGDL_CONFIG_PATH=~/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path ~/.config/heroic/gog_store/auth.json auth
(10:32:25) [DEBUG]:   [Gog]:             Logging to file(s) "~/.local/state/Heroic/logs/runners/gog.log"
(10:32:25) [INFO]:    [Gog]:             GOG presence set
(10:37:25) [INFO]:    [Gog]:             Running command: GOGDL_CONFIG_PATH=~/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path ~/.config/heroic/gog_store/auth.json auth
(10:37:25) [DEBUG]:   [Gog]:             Logging to file(s) "~/.local/state/Heroic/logs/runners/gog.log"
(10:37:25) [INFO]:    [Gog]:             GOG presence set
```
