### ISSUE TITLE
"Game not available" every time I restart Heroic

### ISSUE THREAD

**Issue by tjkirch** [Heroic-Games-Launcher/HeroicGamesLauncher#3921]
### Describe the bug

After I install a game through Heroic, it works fine, I can play and quit and restart the game, etc.  But when I restart Heroic, it says "game not available" for everything, even though the files haven't been touched.  The pain is that this requires rerunning all setup steps, which can take 10+ minutes for some games with winetricks.

I'm using Heroic through Flatpak on Bazzite, installing to the standard `~/Heroic/Games`.  (The flatpak version, `~/.var/app/com.heroicgameslauncher.hgl/Games/Heroic/`, remains empty.  Is it looking here for some reason?)

The Flatpak has the default permissions, and even if I add permission to read/write all user files, it makes no difference.

I've tried a few games with the same result - Art of Rally (Epic), TMNT: Shredder's Revenge (Epic), and Breach & Clear (Gog).  Breach & Clear also has a Linux native version, and that has the same effect, so it's not related to Wine.

When installing, I see "Warning: path might not be writable." as with issues #1512 and #2072, but obviously it still installs fine.

### Add logs

```text
<details>

<summary>Heroic log:</summary>

(15:27:17) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(15:27:17) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:27:17) INFO:    [Connection]:       Connectivity: check-online
(15:27:17) INFO:    [Connection]:       Pinging external endpoints
(15:27:17) INFO:    [Gog]:              Checking for existing gog manifests
(15:27:17) INFO:    [Nile]:             Refreshing library...
(15:27:17) INFO:    [Nile]:             Refreshing Amazon Games...
(15:27:17) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(15:27:17) INFO:    [Nile]:             Game list updated, got 149 games
(15:27:17) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(15:27:17) WARNING: [Backend]:          Failed to register protocol with OS.
(15:27:17) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:27:17) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(15:27:17) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(15:27:18) INFO:    [Connection]:       Connectivity: online
(15:27:18) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:27:18) INFO:    [Gog]:              Checking if login is valid
(15:27:18) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:27:18) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(15:27:18) INFO:    [Backend]:          
System Information:
CPU: 12x AMD Ryzen 5 3600X 6-Core Processor
Memory: 33.56 GB (used: 9.53 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
    IDs: D=731f V=1002 SD=c810 SV=1462
    Driver: amdgpu
OS: Bazzite 40.20240809.0 (Kinoite) (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(15:27:18) INFO:    [Nile]:             Saved user data to config file
(15:27:18) INFO:    [Frontend]:         Refreshing undefined Library
(15:27:18) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(15:27:18) INFO:    [Legendary]:        Refreshing library...
(15:27:18) INFO:    [Legendary]:        Refreshing Epic Games...
(15:27:18) INFO:    [Nile]:             Refreshing library...
(15:27:18) INFO:    [Nile]:             Refreshing Amazon Games...
(15:27:18) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(15:27:18) INFO:    [Nile]:             Game list updated, got 149 games
(15:27:18) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:27:18) INFO:    [Backend]:          Frontend Ready
(15:27:18) INFO:    [Backend]:          Checking for current version changelog
(15:27:18) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:27:18) INFO:    [Gog]:              Getting GOG library
(15:27:18) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:27:19) INFO:    [Gog]:              Saved username to config file
(15:27:19) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:27:20) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:27:20) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(15:27:20) INFO:    [Winetricks]:       Downloading Winetricks
(15:27:20) INFO:    [Legendary]:        Game list updated, got 315 games & DLCs
(15:27:21) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1891038081 Release with per platform id: gog_1891038081 not found
(15:27:22) INFO:    [Gog]:              Saved games data
(15:27:22) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:27:22) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:27:22) INFO:    [WineDownloader]:   Updating wine versions info
(15:27:22) INFO:    [WineDownloader]:   Fetching upstream information...
(15:27:23) INFO:    [Gog]:              Found 0 game(s) to update
(15:27:23) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:27:23) INFO:    [Backend]:          Starting the Download Queue
(15:27:23) INFO:    [WineDownloader]:   wine versions updated
(15:27:24) INFO:    [Legendary]:        Found 0 games to update
(15:27:24) INFO:    [Nile]:             Looking for updates...
(15:27:24) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/var/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json

</details>

Game logs just show information from the successful launches, nothing about the times they weren't found.
```

### Steps to reproduce

1. Install game.  Play game.
2. Restart Heroic.
3. Heroic now shows "game not available".
4. Press play anyway; game reruns setup steps (e.g. winetricks), which can take 10+ minutes.
5. When setup complete, Heroic says game was removed and asks if I'd like to remove it from the installed list; I say no.  (Of course I did not remove it.)
6. Select "Verify and Repair" for the game; this is quick.
7. Game now plays OK, as long as I don't restart Heroic.

### Expected behavior

Heroic finds the game that it installed before it was restarted, and plays the game without rerunning its setup steps.

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS: Bazzite 40
- DE: KDE 6 on Wayland
- Kernel: 6.9.12

**Comment by tjkirch** [comment]
I tried a few other things:

* Adding to Steam and starting from Steam - this doesn't work; pressing "Add to Steam" says `/home/user/.steam/steam/userdata does not exist. Can't add/remove game to/from Steam!` even though that directory does exist and Heroic's Flatpak permissions are read/write for ~/.steam.
* "Move Game" to another directory - it creates the new directory, updates the game metadata to say that's its new home, but doesn't move anything, and obviously still won't launch.  I "moved game" back afterward.
* "Change install path" - I'm not sure how this differs from "Move Game" but it had the same effect.
* "Verify and repair" before trying to play - this fails with the log below.  I added Flatpak Create permissions for `~/Games` and that made no difference.
```text
An error has occurred! Try to Logout and Login on your Epic account.
[Core] INFO: Trying to re-use existing login session...[cli] INFO: Game has not been verified yet.
[cli] INFO: Loading installed manifest for "16a7b366b94c4cf2843dd0dfda4bbd19"
[cli] ERROR: Install path "/home/user/Games/TMNT" does not exist, make sure all necessary mounts are available. If you previously deleted the game folder without uninstalling, run "legendary uninstall -y 16a7b366b94c4cf2843dd0dfda4bbd19" and reinstall from scratch.
[cli] INFO: Preparing download for "Teenage Mutant Ninja Turtles: Shredder's Revenge" (16a7b366b94c4cf2843dd0dfda4bbd19)...[Core] INFO: Parsing game manifest...Traceback (most recent call last):
File "legendary/cli.py", line 3161, in <module>
File "legendary/cli.py", line 3078, in main
File "legendary/cli.py", line 962, in install_gameFile "legendary/core.py", line 1420, in prepare_download
PermissionError: No write access to "/home/user/Games"
[206] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by T3KPCS7** [comment]
Don't have any additional information or help unfortunately, but I just wanted to add that I have the same issue, also on Bazzite.

**Comment by sricosta** [comment]
Update the app on Discover and see if the problem is fixed... I see you are on 2.14.1 when the app is already on 2.15.1

If it doesn't, reinstall the game(s) in question

**Comment by tjkirch** [comment]
> Update the app on Discover and see if the problem is fixed... I see you are on 2.14.1 when the app is already on 2.15.1

I have the same problem on 2.15.1.

I started Heroic and it says all my games are not available.  I pressed play on one, and it runs through the setup steps, then tells me the game is no longer installed and asks if I'd like to remove it from my list.  I say no.  I verify and repair the game, then it plays fine.  I restart Heroic and it once again says the game is not available.

> If it doesn't, reinstall the game(s) in question

Unfortunately that didn't help.  I uninstalled a game, removing the prefix and logs for a clean start.  I reinstall it, ignoring the warning about the prefix not being writable because that's not true.  I don't change any Wine settings.  The game downloads, installs, and when I press play, it runs through the setup steps and plays fine.  I restart Heroic, and once again it says the game is not available, and it has to run through setup steps and a verify/repair before it's playable.

**Comment by tjkirch** [comment]
> can you do a test using a non-flatpak heroic installation? just to confirm if the issue is flatpak or not

I tried with the 2.15.1 AppImage and didn't have this issue.  I installed a game and it no longer warned me about a non-writable directory.  I restarted Heroic and the game was still listed as available and started fine.  So it seems the issue is with the Flatpak packaging; I hope that can be fixed because I'd like to use the Flatpak version.

**Comment by ObiWanPEZ** [comment]
I have a similar (?) issue with using a solid-state drive as my backup hard drive. I need to access it through the File Manager GUI (navigate to Other Locations, and open up the drive in question), before opening Epic or Steam. Once I do this, I can start up Epic / Steam, and everything has been auto-populated.
This occurs every time I restart the computer.

**Comment by sleepingzzs** [comment]
I'm using the flatpak version and this issue still exists. Temporary solution is to update the install path to the location where it is installed. It was never an issue on the official .deb installation.

**Comment by CritLoren** [comment]
I also have this same issue on 2.16.1, i even gave explicit perms to the flatpak to the games parent folder

**Comment by Alecerzea** [comment]
Its also happening to me in 2.18.1, but mostly with amazon games


<img width="188" height="293" alt="Image" src="https://github.com/user-attachments/assets/ad70e908-a29f-4e28-9235-62d0a06b4090" />

**Comment by jdrozdz** [comment]
> Its also happening to me in 2.18.1, but mostly with amazon games
> 
> <img alt="Image" width="188" height="293" src="https://private-user-images.githubusercontent.com/85199063/478621487-ad70e908-a29f-4e28-9235-62d0a06b4090.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyODQ3MDYsIm5iZiI6MTc1NjI4NDQwNiwicGF0aCI6Ii84NTE5OTA2My80Nzg2MjE0ODctYWQ3MGU5MDgtYTI5Zi00ZTI4LTkyMzUtNjJkMGEwNmI0MDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODI3VDA4NDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZDUyNGM5MTFjZDU2OTZhY2Q2MWZiM2UxZDk3ZTkxODMxNTc5M2Y3Mjk4YjM5ZjI2ZjZiOGMwNGJkODBjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iuJ03mHhR_WEjKNh-4YvK-v_1bEZ81x8mu-dbBwJHsU">

check if data/prefix folder exists (usually in ~/Games/heroic). If not remove it from the list and install again.

**Comment by TheAutistCoder** [comment]
Had the same problem and solved it.
I'm running Kubuntu 25.04 + HGL 2.18.1

Other than the HGL website suggests,  flatpak is not "best experience", at least not on *buntu systems in my experience.

Download the latest release here from GitHub (in my case as .deb file), and install it manually, like:
`sudo apt install Downloads/Heroic-2.18.1-linux-amd64.deb`

Then the problem is gone. At least it was gone for me.

**Comment by Dedga** [comment]
Apparently the install path was changed between reboots. 
I have the game installed on a separate drive.
Real install path: /run/media/system/_mounted_drive_/_installed_game_
Changed to: /run/media/_user_/_mounted_drive_/_installed_game_

Changed the install path of the game to the actual path and then it works! 
No repair or re-install needed.
