### ISSUE TITLE
Amazon/Prime Gaming - Cannot get game info

### ISSUE THREAD

**Issue by Cristobal-M** [Heroic-Games-Launcher/HeroicGamesLauncher#3922]
### Describe the bug

When opening game description of any Prime Gaming from my library an error is shown "Cannot get game info", delete cache doesn't works and the same occurs in my steam deck.

Also, if I try to install any of those games from the "download" button in the library, the install dialog stucks loading

### Add logs

```text
(13:25:47) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary

(13:25:47) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl

(13:25:47) INFO:    [Connection]:       Connectivity: check-online

(13:25:47) INFO:    [Connection]:       Pinging external endpoints

(13:25:47) INFO:    [Gog]:              Checking for existing gog manifests

(13:25:47) INFO:    [Nile]:             Refreshing library...

(13:25:47) INFO:    [Nile]:             Refreshing Amazon Games...

(13:25:47) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync

(13:25:47) INFO:    [Nile]:             Game list updated, got 26 games

(13:25:47) INFO:    [Backend]:          DRM module staus {

  "oimompecagnajdejgnnjijobebaeigek": {

    "status": "new",

    "title": "Widevine Content Decryption Module",

    "version": "4.10.2710.0"

  }

}

(13:25:47) WARNING: [Backend]:          Failed to register protocol with OS.

(13:25:47) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version

(13:25:47) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version

(13:25:47) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version

(13:25:48) INFO:    [Connection]:       Connectivity: online

(13:25:48) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth

(13:25:48) INFO:    [Gog]:              Checking if login is valid

(13:25:48) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth

(13:25:48) INFO:    [Backend]:          

System Information:

CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700F

Memory: 33.5 GB (used: 7.81 GB)

GPUs:

  GPU 0:

    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M]

    IDs: D=73ff V=1002 SD=e448 SV=1da2

    Driver: amdgpu

OS: KDE neon 6.0 (linux)

The current system is not a Steam Deck

We are running inside a Flatpak container

Software Versions:

  Heroic: 2.14.1 Flame Emperor Sabo

  Legendary: 0.20.34 Direct Intervention

  gogdl: 1.0.1

  Nile: 1.0.2 Jonathan Joestar

(13:25:48) INFO:    [Nile]:             Saved user data to config file

(13:25:48) INFO:    [Frontend]:         Refreshing undefined Library

(13:25:48) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(13:25:48) INFO:    [Legendary]:        Refreshing library...

(13:25:48) INFO:    [Legendary]:        Refreshing Epic Games...

(13:25:48) INFO:    [Nile]:             Refreshing library...

(13:25:48) INFO:    [Nile]:             Refreshing Amazon Games...

(13:25:48) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync

(13:25:48) INFO:    [Nile]:             Game list updated, got 26 games

(13:25:48) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth

(13:25:48) INFO:    [Backend]:          Frontend Ready

(13:25:48) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded

(13:25:48) INFO:    [Gog]:              Getting GOG library

(13:25:48) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth

(13:25:48) INFO:    [Backend]:          Checking for current version changelog

(13:25:48) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party

(13:25:48) INFO:    [Gog]:              Saved username to config file

(13:25:49) INFO:    [Gog]:              Saved games data

(13:25:49) INFO:    [Legendary]:        Game list updated, got 82 games & DLCs

(13:25:49) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(13:25:49) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth

(13:25:50) INFO:    [Winetricks]:       Downloading Winetricks

(13:25:50) INFO:    [Gog]:              Found 2 game(s) to update

(13:25:50) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party

(13:25:52) WARNING: [Legendary]:        Failed to parse games from /home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json'

    at Object.readFileUtf8 (node:internal/fs/sync:25:18)

    at Object.readFileSync (node:fs:441:19)

    at t.readFileSync (node:electron/js2c/node_init:2:9771)

    at Module.listUpdateableGames (/app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:114:4090)

    at async /app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:235:3193

    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)

(13:25:52) INFO:    [Legendary]:        Found 0 games to update

(13:25:52) INFO:    [Nile]:             Looking for updates...

(13:25:52) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json

(13:25:52) INFO:    [WineDownloader]:   Updating wine versions info

(13:25:52) INFO:    [WineDownloader]:   Fetching upstream information...

(13:25:53) INFO:    [Backend]:          Starting the Download Queue

(13:25:54) INFO:    [WineDownloader]:   wine versions updated

(13:26:15) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Metal Slug 2

(13:26:15) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Metal Slug 2

(13:26:15) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Metal Slug 2

(13:26:15) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Metal Slug 2

(13:26:15) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Metal Slug 2

(13:26:15) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Metal Slug 2

(13:26:15) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Metal Slug 2

(13:26:15) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Metal Slug 2

(13:26:15) INFO:    [Nile]:             Getting more details

(13:26:15) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json fbcc4aaa-a6f1-469c-b34e-dc65756f7141

(13:26:15) INFO:    [Nile]:             Getting more details

(13:26:15) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json fbcc4aaa-a6f1-469c-b34e-dc65756f7141

(13:26:16) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input

    at JSON.parse (<anonymous>)

    at Module.getInstallInfo$2 [as getInstallInfo] (/app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:95:5537)

    at async /app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:235:5349

    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)

(13:26:16) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input

    at JSON.parse (<anonymous>)

    at Module.getInstallInfo$2 [as getInstallInfo] (/app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:95:5537)

    at async /app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:235:5349

    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)

(13:26:16) ERROR:   [Frontend]:         Cannot get game info

(13:26:16) ERROR:   [Frontend]:         Cannot get game info

(13:26:16) ERROR:   [Frontend]:         Cannot get game info

(13:26:16) ERROR:   [ExtraGameInfo]:    Got AxiosError when sending HowLongToBeat request for Metal Slug 2: {

  "message": "Request failed with status code 404",

  "name": "Error",

  "stack": "Error: Request failed with status code 404\n    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1408:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",

  "config": {

    "transitional": {

      "silentJSONParsing": true,

      "forcedJSONParsing": true,

      "clarifyTimeoutError": false

    },

    "transformRequest": [

      null

    ],

    "transformResponse": [

      null

    ],

    "timeout": 0,

    "xsrfCookieName": "XSRF-TOKEN",

    "xsrfHeaderName": "X-XSRF-TOKEN",

    "maxContentLength": -1,

    "maxBodyLength": -1,

    "headers": {

      "Accept": "*/*",

      "Content-Type": "application/json",

      "User-Agent": "HeroicGamesLauncher/2.14.1",

      "Referer": "https://howlongtobeat.com/",

      "Content-Length": 351

    },

    "method": "post",

    "url": "https://www.howlongtobeat.com/api/search",

    "data": "{\"searchType\":\"games\",\"searchTerms\":[\"Metal\",\"Slug\",\"2\"],\"searchPage\":1,\"size\":20,\"searchOptions\":{\"games\":{\"userId\":0,\"platform\":\"\",\"sortCategory\":\"popular\",\"rangeCategory\":\"main\",\"rangeTime\":{\"min\":0,\"max\":0},\"gameplay\":{\"perspective\":\"\",\"flow\":\"\",\"genre\":\"\"},\"modifier\":\"\"},\"users\":{\"sortCategory\":\"postcount\"},\"filter\":\"\",\"sort\":0,\"randomizer\":0}}"

  },

  "status": 404

}

(13:26:16) ERROR:   [ExtraGameInfo]:    Got AxiosError when sending HowLongToBeat request for Metal Slug 2: {

  "message": "Request failed with status code 404",

  "name": "Error",

  "stack": "Error: Request failed with status code 404\n    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1408:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",

  "config": {

    "transitional": {

      "silentJSONParsing": true,

      "forcedJSONParsing": true,

      "clarifyTimeoutError": false

    },

    "transformRequest": [

      null

    ],

    "transformResponse": [

      null

    ],

    "timeout": 0,

    "xsrfCookieName": "XSRF-TOKEN",

    "xsrfHeaderName": "X-XSRF-TOKEN",

    "maxContentLength": -1,

    "maxBodyLength": -1,

    "headers": {

      "Accept": "*/*",

      "Content-Type": "application/json",

      "User-Agent": "HeroicGamesLauncher/2.14.1",

      "Referer": "https://howlongtobeat.com/",

      "Content-Length": 351

    },

    "method": "post",

    "url": "https://www.howlongtobeat.com/api/search",

    "data": "{\"searchType\":\"games\",\"searchTerms\":[\"Metal\",\"Slug\",\"2\"],\"searchPage\":1,\"size\":20,\"searchOptions\":{\"games\":{\"userId\":0,\"platform\":\"\",\"sortCategory\":\"popular\",\"rangeCategory\":\"main\",\"rangeTime\":{\"min\":0,\"max\":0},\"gameplay\":{\"perspective\":\"\",\"flow\":\"\",\"genre\":\"\"},\"modifier\":\"\"},\"users\":{\"sortCategory\":\"postcount\"},\"filter\":\"\",\"sort\":0,\"randomizer\":0}}"

  },

  "status": 404

}

(13:26:17) DEBUG:   [Backend]:          SteamDeck data for 366260 {"success":1,"results":{"appid":366260,"resolved_category":1,"resolved_items":[{"display_type":2,"loc_token":"#SteamDeckVerified_TestResult_SteamOSDoesNotSupport"}],"steam_deck_blog_url":"","search_id":null}}

(13:26:17) DEBUG:   [Backend]:          ProtonDB data for 366260 {"bestReportedTier":"platinum","confidence":"good","score":0.22,"tier":"silver","total":18,"trendingTier":"gold"}

(13:26:17) DEBUG:   [Backend]:          SteamDeck data for 366260 {"success":1,"results":{"appid":366260,"resolved_category":1,"resolved_items":[{"display_type":2,"loc_token":"#SteamDeckVerified_TestResult_SteamOSDoesNotSupport"}],"steam_deck_blog_url":"","search_id":null}}

(13:26:17) DEBUG:   [Backend]:          ProtonDB data for 366260 {"bestReportedTier":"platinum","confidence":"good","score":0.22,"tier":"silver","total":18,"trendingTier":"gold"}

(13:26:17) ERROR:   [Frontend]:         Cannot get game info

(13:26:30) INFO:    [Nile]:             Getting more details

(13:26:30) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/cristobal/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json fbcc4aaa-a6f1-469c-b34e-dc65756f7141

(13:26:30) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input

    at JSON.parse (<anonymous>)

    at Module.getInstallInfo$2 [as getInstallInfo] (/app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:95:5537)

    at async /app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:235:5349

    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)
```

### Steps to reproduce

1. Go to 'Library'
2. Click on any Prime Gaming game
3. Game info shown, next instant is replaced by error page

### Expected behavior

Game description page shown

### Screenshots

![imagen](https://github.com/user-attachments/assets/7a6a9f58-3dab-4465-a445-6c4e429230a3)
![imagen](https://github.com/user-attachments/assets/61c2b45d-663f-4454-b335-c936dd34ff2d)

### Heroic Version

Latest Stable

### System Information

Happens on my PC and Steam deck:
PC:

    CPU: i7-12700F
    Memory: 32GB
    SO: KDE neon 6.0 - 6.5.0-44-generic
    Flatpak

Steam deck:

    OS: default, last version
    Flatpak

**Comment by Cristobal-M** [comment]
It seems that using the latest nile executable works without problems.

**Comment by arielj** [comment]
closing as this will be solved in the next release
