### ISSUE TITLE
2.15/.1 - Windows - Amazon+Epic+GOG - Cannot get game info

### ISSUE THREAD

**Issue by Aloekior** [Heroic-Games-Launcher/HeroicGamesLauncher#3938]
### Describe the bug

Similar to #3922 , just with all stores now happening on Windows 10 with 2.15/.1.
Windows version does not seem to suffer from #3932 and can load library just fine after logging into accounts, but game info loading/installing won't work. Happens with both update from 2.14.1 as well as clean installation of 2.15/.1.

Downloading games from Library view instead of game detail view also doesn't work. Heroic will not gather download/install size.

Most notable in logs, it appears to be related to HowLongToBeat:
ERROR:   [ExtraGameInfo]:    Got AxiosError when sending HowLongToBeat request for Baldurs Gate 3: {
  "message": "Request failed with status code 404"

### Add logs

```text
Software Versions:
  Heroic: 2.15.1 Emeth
  Legendary: 0.20.35 Lowlife (Heroic)
  gogdl: 1.1.1
  comet: comet 0.1.2

  Nile: 1.1.1 Will A. Zeppeli

(00:44:06) INFO:    [Legendary]:        Game list updated, got 80 games & DLCs
(00:44:06) INFO:    [WineDownloader]:   Updating wine versions info
(00:44:06) INFO:    [WineDownloader]:   Fetching upstream information...
(00:44:07) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=D:\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\USER\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"D:\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""
(00:44:07) INFO:    [WineDownloader]:   wine versions updated
(00:44:07) ERROR:   [Backend]:          Could not find default wine version
(00:44:10) INFO:    [Backend]:          Starting the Download Queue
(00:44:25) INFO:    [Gog]:              Saved games data
(00:44:25) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(00:44:25) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=D:\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\USER\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"D:\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""
(00:44:26) INFO:    [Gog]:              Found 0 game(s) to update
(00:44:27) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=D:\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\USER\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"list`"","`"--third-party`""
(00:44:28) INFO:    [Legendary]:        Found 0 games to update
(00:44:28) INFO:    [Nile]:             Looking for updates...
(00:44:28) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=D:\AppData\Roaming\heroic\nile_config powershell Start-Process "`"C:\Users\USER\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"list-updates`"","`"--json`""
(00:44:29) INFO:    [Frontend]:         No cache found, getting data from nile...
(00:44:29) INFO:    [Nile]:             Refreshing library...
(00:44:29) INFO:    [Nile]:             Refreshing Amazon Games...
(00:44:29) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=D:\AppData\Roaming\heroic\nile_config powershell Start-Process "`"C:\Users\USER\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"library`"","`"sync`""
(00:44:29) INFO:    [Nile]:             Game list updated, got 216 games
(00:44:48) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Baldurs Gate 3
(00:44:48) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Baldurs Gate 3
(00:44:48) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Baldurs Gate 3
(00:44:48) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Baldurs Gate 3
(00:44:48) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Baldurs Gate 3
(00:44:48) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Baldurs Gate 3
(00:44:48) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Baldurs Gate 3
(00:44:48) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Baldurs Gate 3
(00:44:48) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=D:\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\USER\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"D:\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""
(00:44:48) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=D:\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\USER\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"D:\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""
(00:44:48) ERROR:   [ExtraGameInfo]:    Got AxiosError when sending HowLongToBeat request for Baldurs Gate 3: {
  "message": "Request failed with status code 404",
  "name": "Error",
  "stack": "Error: Request failed with status code 404\n    at createError (C:\\Users\\USER\\AppData\\Local\\Programs\\heroic\\resources\\app.asar\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (C:\\Users\\USER\\AppData\\Local\\Programs\\heroic\\resources\\app.asar\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\USER\\AppData\\Local\\Programs\\heroic\\resources\\app.asar\\node_modules\\axios\\lib\\adapters\\http.js:322:11)\n    at IncomingMessage.emit (node:events:531:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "headers": {
      "Accept": "*/*",
      "Content-Type": "application/json",
      "User-Agent": "HeroicGamesLauncher/2.15.1",
      "Referer": "https://howlongtobeat.com/",
      "Content-Length": 353
    },
    "method": "post",
    "url": "https://www.howlongtobeat.com/api/search",
    "data": "{\"searchType\":\"games\",\"searchTerms\":[\"Baldurs\",\"Gate\",\"3\"],\"searchPage\":1,\"size\":20,\"searchOptions\":{\"games\":{\"userId\":0,\"platform\":\"\",\"sortCategory\":\"popular\",\"rangeCategory\":\"main\",\"rangeTime\":{\"min\":0,\"max\":0},\"gameplay\":{\"perspective\":\"\",\"flow\":\"\",\"genre\":\"\"},\"modifier\":\"\"},\"users\":{\"sortCategory\":\"postcount\"},\"filter\":\"\",\"sort\":0,\"randomizer\":0}}"
  },
  "status": 404
}
```

### Steps to reproduce

1. Install Heroic 2.15/.1
2. Log in with any of the three accounts
3. Select any game from library

### Expected behavior

Display game information/allow installation.

### Screenshots

See #3922

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Windows 10 22H2 

### Additional information

Works fine with 2.14.1 (except Amazon due to #3922 )

**Comment by arielj** [comment]
can you share the complete log after you get the error? the failure to fetch the extra info shouldn't cause the page to crash

also share the corresponding log of the store (in the example you shared it would be the gog log)

**Comment by Aloekior** [comment]
Happened due to user error.
Log now was different from yesterday with Heroic not being able to refresh login information - which made me wonder if it's something firewall related - paths for legendary, nile and gogdl changed and needed to be allowed internet access again.
Sorry for lack of proper research before posting.
