### ISSUE TITLE
Adding game to steam error with message "userdata does not exist. Can't add/remove game to/from Steam"

### ISSUE THREAD

**Issue by chenhx37** [Heroic-Games-Launcher/HeroicGamesLauncher#3949]
### Describe the bug

I'm using steam deck lcd with heroic version 2.14.1, and SteamOS 3.5.19, KDE Plasma version 5.27.5. The error occurs everytime & every game.
The function works well in the previous version, before I updated heroic/SteamOS. Not sure which part goes wrong

### Add logs

```text
(12:56:01) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(12:56:01) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(12:56:01) INFO:    [Connection]:       Connectivity: check-online
(12:56:01) INFO:    [Connection]:       Pinging external endpoints
(12:56:01) INFO:    [Gog]:              Checking for existing gog manifests
(12:56:01) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(12:56:01) WARNING: [Backend]:          Failed to register protocol with OS.
(12:56:01) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(12:56:01) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(12:56:01) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(12:56:02) INFO:    [Backend]:
System Information:
CPU: 8x AMD Custom APU 0405
Memory: 15.53 GB (used: 5.49 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] VanGogh [AMD Custom GPU 0405]
    IDs: D=163f V=1002 SD=0123 SV=1002
    Driver: amdgpu
OS: SteamOS 3.5.19 holo (linux)

The current system is a Steam Deck (model: LCD) in desktop mode
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(12:56:02) INFO:    [Frontend]:         Refreshing undefined Library
(12:56:02) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(12:56:02) INFO:    [Legendary]:        Refreshing library...
(12:56:02) INFO:    [Legendary]:        Refreshing Epic Games...
(12:56:02) INFO:    [Backend]:          Frontend Ready
(12:56:02) INFO:    [Connection]:       Connectivity: online
(12:56:02) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:56:02) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(12:56:02) INFO:    [Backend]:          Checking for current version changelog
(12:56:04) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(12:56:04) INFO:    [Winetricks]:       Downloading Winetricks
(12:56:05) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/home/deck/Games/Heroic/Prefixes/default/Defense Grid The Awakening"
(12:56:05) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Defense Grid The Awakening
(12:56:05) INFO:    [Legendary]:        Getting more details with 'legendary info'
(12:56:05) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Defense Grid The Awakening
(12:56:05) INFO:    [Backend]:          Launching Defense Grid: The Awakening (a434dcb20f0d439b93aaa31dac9e3210)
(12:56:06) INFO:    [Backend]:          Preventing display from sleep
(12:56:06) INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-latest
(12:56:06) INFO:    [Legendary]:        Getting more details with 'legendary info'
(12:56:06) INFO:    [Backend]:          Preventing machine to sleep
(12:56:06) INFO:    [Legendary]:        Getting more details with 'legendary info'
(12:56:06) INFO:    [Legendary]:        Getting more details with 'legendary info'
(12:56:06) INFO:    [Legendary]:        Abort command "LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/home/deck/Games/Heroic/Prefixes/default/Defense Grid The Awakening""
(12:56:06) INFO:    [WineDownloader]:   Updating wine versions info
(12:56:06) INFO:    [WineDownloader]:   Fetching upstream information...
(12:56:07) INFO:    [Backend]:          Starting the Download Queue
(12:56:09) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/home/deck/Games/Heroic/Prefixes/default/Defense Grid The Awakening"
(12:56:09) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Defense Grid The Awakening
(12:56:09) INFO:    [Legendary]:        Getting more details with 'legendary info'
(12:56:09) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Defense Grid The Awakening
(12:56:09) INFO:    [Legendary]:        Getting more details with 'legendary info'
(12:56:09) INFO:    [Legendary]:        Getting more details with 'legendary info'
(12:56:09) INFO:    [Legendary]:        Abort command "LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/home/deck/Games/Heroic/Prefixes/default/Defense Grid The Awakening""
(12:56:11) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Defense Grid The Awakening
(12:56:11) ERROR:   [Shortcuts]:        userdata does not exist. Can't add/remove game to/from Steam!
(12:56:12) ERROR:   [Backend]:          Failed to get epic service status with Error: timeout of 10000ms exceeded
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:514:28)
    at Timeout.<anonymous> (/app/bin/heroic/resources/app.asar/node_modules/follow-redirects/index.js:210:12)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
(12:56:12) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(12:56:12) WARNING: [Backend]:          Failed download of AreWeAntiCheatYet data: Error: timeout of 10000ms exceeded
(12:56:14) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info a434dcb20f0d439b93aaa31dac9e3210 --json --platform Windows
(12:56:14) INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-latest
(12:56:14) INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-latest
(12:56:14) INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-latest
(12:56:14) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(12:56:14) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info a434dcb20f0d439b93aaa31dac9e3210 --json --platform Windows
(12:56:14) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info a434dcb20f0d439b93aaa31dac9e3210 --json --platform Windows
(12:56:16) ERROR:   [Backend]:          Failed to get epic service status with Error: timeout of 10000ms exceeded
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:514:28)
    at Timeout.<anonymous> (/app/bin/heroic/resources/app.asar/node_modules/follow-redirects/index.js:210:12)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
(12:56:16) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info a434dcb20f0d439b93aaa31dac9e3210 --json --platform Windows
(12:56:16) INFO:    [DXVKInstaller]:    installing dxvk on... /home/deck/Games/Heroic/Prefixes/default/Defense Grid The Awakening
(12:56:16) INFO:    [DXVKInstaller]:    dxvk already installed!
(12:56:16) INFO:    [DXVKInstaller]:    installing vkd3d on... /home/deck/Games/Heroic/Prefixes/default/Defense Grid The Awakening
(12:56:16) INFO:    [DXVKInstaller]:    vkd3d already installed!
(12:56:16) INFO:    [Legendary]:        Launching Defense Grid: The Awakening: LD_LIBRARY_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-latest/lib64:/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-latest/lib:/usr/lib/extensions/vulkan/gamescope/lib HEROIC_APP_NAME=a434dcb20f0d439b93aaa31dac9e3210 HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic STEAM_COMPAT_INSTALL_PATH=/home/deck/Games/Heroic/DefenseGrid LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= DOTNET_ROOT= WINEPREFIX="/home/deck/Games/Heroic/Prefixes/default/Defense Grid The Awakening" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 PROTON_EAC_RUNTIME=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/eac_runtime PROTON_BATTLEYE_RUNTIME=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/battleye_runtime ORIG_LD_LIBRARY_PATH=/usr/lib/extensions/vulkan/gamescope/lib GST_PLUGIN_SYSTEM_PATH_1_0=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-latest/lib64/gstreamer-1.0:/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-latest/lib/gstreamer-1.0 WINEDLLPATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-latest/lib64/wine:/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-latest/lib/wine LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch a434dcb20f0d439b93aaa31dac9e3210 --wine /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-latest/bin/wine --wrapper /app/bin/gamemoderun --language zh_Hans
(12:56:16) INFO:    [Backend]:          Stopping Power Saver Blocker
(12:56:16) INFO:    [Legendary]:        Getting more details with 'legendary info'
(12:56:16) INFO:    [Legendary]:        Getting more details with 'legendary info'
(12:56:16) ERROR:   [WineDownloader]:   Error: Could not fetch available releases from https://api.github.com/repos/GloriousEggroll/wine-ge-custom/releases with error:
 Error: timeout of 10000ms exceeded
    at /app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:120:4188
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(12:56:16) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info a434dcb20f0d439b93aaa31dac9e3210 --json --platform Windows
(12:56:16) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info a434dcb20f0d439b93aaa31dac9e3210 --json --platform Windows
(12:56:17) INFO:    [WineDownloader]:   wine versions updated
(12:56:17) INFO:    [Legendary]:        Game list updated, got 106 games & DLCs
(12:56:17) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(12:56:18) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(12:56:19) ERROR:   [Backend]:          Failed to get epic service status with Error: timeout of 10000ms exceeded
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:514:28)
    at Timeout.<anonymous> (/app/bin/heroic/resources/app.asar/node_modules/follow-redirects/index.js:210:12)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
(12:56:19) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info a434dcb20f0d439b93aaa31dac9e3210 --json --platform Windows
(12:56:19) ERROR:   [Backend]:          Failed to get epic service status with Error: timeout of 10000ms exceeded
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:514:28)
    at Timeout.<anonymous> (/app/bin/heroic/resources/app.asar/node_modules/follow-redirects/index.js:210:12)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
(12:56:19) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info a434dcb20f0d439b93aaa31dac9e3210 --json --platform Windows
(12:56:19) ERROR:   [Backend]:          Failed to get epic service status with Error: timeout of 10000ms exceeded
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:514:28)
    at Timeout.<anonymous> (/app/bin/heroic/resources/app.asar/node_modules/follow-redirects/index.js:210:12)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
(12:56:19) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info a434dcb20f0d439b93aaa31dac9e3210 --json --platform Windows
(12:56:20) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(12:56:20) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(12:56:20) DEBUG:   [Legendary]:        Using cached install info
(12:56:20) DEBUG:   [Legendary]:        Update is available for 499f085e442048aa854d6250b21c42fb: 1.0.1.1b1 != 1.0.2.0_d
(12:56:20) INFO:    [Legendary]:        Found 1 game to update
(12:56:20) DEBUG:   [Legendary]:        Using cached install info
(12:56:20) DEBUG:   [Legendary]:        Using cached install info
(12:56:20) DEBUG:   [Legendary]:        Using cached install info
(12:56:21) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(12:56:21) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(12:56:23) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(12:56:23) ERROR:   [Legendary]:        Error Getting Info from Epic API
(12:56:23) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(12:57:27) ERROR:   [Legendary]:        Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
(12:57:27) ERROR:   [Legendary]:        Error Getting Info from Epic API
(12:57:30) ERROR:   [Legendary]:        Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
(12:57:30) ERROR:   [Legendary]:        Error Getting Info from Epic API
(12:57:31) ERROR:   [Legendary]:        Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
(12:57:31) ERROR:   [Legendary]:        Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
(12:57:34) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(12:57:34) ERROR:   [Legendary]:        Error Getting Info from Epic API
(12:57:34) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(12:57:34) ERROR:   [Legendary]:        Error Getting Info from Epic API
(12:57:35) ERROR:   [Legendary]:        Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
(12:57:35) ERROR:   [Legendary]:        Error Getting Info from Epic API
(13:02:31) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Defense Grid The Awakening
(13:02:31) ERROR:   [Shortcuts]:        userdata does not exist. Can't add/remove game to/from Steam!
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Add games to steam successfully

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]:

**Comment by arielj** [comment]
is this still an issue?
