### ISSUE TITLE
There are pending operations, are you sure? every time I quit

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Heroic-Games-Launcher/HeroicGamesLauncher#3954]
### Describe the bug

Every time I quit the launcher after updating I get `There are pending operations, are you sure?`

### Add logs

```text
(13:41:39) INFO:    [Legendary]:        Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/arm64/darwin/legendary
(13:41:39) INFO:    [Gog]:              GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/arm64/darwin/gogdl
(13:41:39) INFO:    [Connection]:       Connectivity: check-online
(13:41:39) INFO:    [Connection]:       Pinging external endpoints
(13:41:39) INFO:    [Gog]:              Checking for existing gog manifests
(13:41:39) WARNING: [Backend]:          Protocol already registered.
(13:41:39) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/****/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/arm64/darwin/legendary --version
(13:41:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/****/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/arm64/darwin/gogdl --auth-config-path "/Users/****/Library/Application Support/heroic/gog_store/auth.json" --version
(13:41:39) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="/Users/****/Library/Application Support/heroic/nile_config" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/arm64/darwin/nile --version
(13:41:39) INFO:    [Connection]:       Connectivity: online
(13:41:39) INFO:    [Gog]:              Checking if login is valid
(13:41:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/****/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/arm64/darwin/gogdl --auth-config-path "/Users/****/Library/Application Support/heroic/gog_store/auth.json" auth
(13:41:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/****/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/arm64/darwin/gogdl --auth-config-path "/Users/****/Library/Application Support/heroic/gog_store/auth.json" auth
(13:41:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/****/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/arm64/darwin/gogdl --auth-config-path "/Users/****/Library/Application Support/heroic/gog_store/auth.json" auth
(13:41:39) INFO:    [Frontend]:         Refreshing undefined Library
(13:41:39) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(13:41:39) INFO:    [Legendary]:        Refreshing library...
(13:41:39) INFO:    [Legendary]:        Refreshing Epic Games...
(13:41:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/****/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/arm64/darwin/gogdl --auth-config-path "/Users/****/Library/Application Support/heroic/gog_store/auth.json" auth
(13:41:39) INFO:    [Backend]:          Frontend Ready
(13:41:39) INFO:    [Backend]:          Checking for new Heroic Updates
(13:41:39) INFO:    [Backend]:          Checking for current version changelog
(13:41:39) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(13:41:39) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/****/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/arm64/darwin/legendary list --third-party
(13:41:41) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine
(13:41:41) INFO:    [Winetricks]:       Downloading Winetricks
(13:41:44) INFO:    [WineDownloader]:   Updating wine versions info
(13:41:44) INFO:    [WineDownloader]:   Fetching upstream information...
(13:41:44) INFO:    [Backend]:          Starting the Download Queue
(13:41:45) INFO:    [WineDownloader]:   wine versions updated
(13:42:19) INFO:    [Gog]:              Getting GOG library
(13:42:19) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/****/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/arm64/darwin/gogdl --auth-config-path "/Users/****/Library/Application Support/heroic/gog_store/auth.json" auth
(13:42:19) INFO:    [Gog]:              GOG presence set
(13:42:20) INFO:    [Gog]:              Saved username to config file
(13:42:31) INFO:    [Backend]:          
System Information:
CPU: 10x Apple M1 Pro
Memory: 17.18 GB (used: 7.11 GB)
GPUs:

OS:  12.7.6 (darwin)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.15.1 Emeth
  Legendary: 0.20.35 Lowlife (Heroic)
  gogdl: 1.1.1
  comet: comet 0.1.2

  Nile: 1.1.1 Will A. Zeppeli

(13:42:38) WARNING: [Backend]:          No clientId in goggame-1442910587.info file. Cannot resolve save path
(13:42:38) INFO:    [Legendary]:        Game list updated, got 3 games & DLCs
(13:42:39) INFO:    [Gog]:              Saved games data
(13:42:39) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(13:42:39) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/****/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/arm64/darwin/gogdl --auth-config-path "/Users/****/Library/Application Support/heroic/gog_store/auth.json" auth
(13:42:48) INFO:    [Gog]:              Found 1 game(s) to update
(13:42:48) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH="/Users/****/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/arm64/darwin/legendary list --third-party
(13:43:04) WARNING: [Legendary]:        Failed to parse games from /Users/****/Library/Application Support/heroic/legendaryConfig/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/Users/****/Library/Application Support/heroic/legendaryConfig/legendary/installed.json'
    at Object.readFileSync (node:fs:448:20)
    at Object.t.readFileSync (node:electron/js2c/node_init:2:10245)
    at Module.Ka (/Applications/Heroic.app/Contents/Resources/app.asar/build/main/main.js:114:3340)
    at /Applications/Heroic.app/Contents/Resources/app.asar/build/main/main.js:184:2384
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537)
(13:43:04) INFO:    [Legendary]:        Found 0 games to update
(13:44:05) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH="/Users/****/Library/Application Support/heroic/gogdlConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/arm64/darwin/gogdl --auth-config-path "/Users/****/Library/Application Support/heroic/gog_store/auth.json" auth
(13:44:12) INFO:    [Gog]:              GOG presence deleted
```

### Steps to reproduce

1. Open
2. try to quit
3. get message `There are pending operations, are you sure?`

### Expected behavior

Quits without issue

### Heroic Version

Latest Stable

### System Information

- macOS: 12.7.6

**Comment by AuDagger** [comment]
I've had the same issue with the same log warnings since the update

**Comment by eachtime** [comment]
Same issue here.

**Comment by arielj** [comment]
For the OP, check if you have this file `/Users/****/Library/Application Support/heroic/GamesConfig/lock`

If the file is there, close heroic, delete that file, and the issue should be gone.

(for anyone else, you can find that path checking your logs)

**Comment by eachtime** [comment]
Same issue here.

> For the OP, check if you have this file `/Users/****/Library/Application Support/heroic/GamesConfig/lock`
> 
> If the file is there, close heroic, delete that file, and the issue should be gone.
> 
> (for anyone else, you can find that path checking your logs)

Thanks @arielj, issue solved. In linux/flatpak the path would be `~/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/lock`

**Comment by Aces-and-Jacks** [comment]
> For the OP, check if you have this file `/Users/****/Library/Application Support/heroic/GamesConfig/lock`
> 
> If the file is there, close heroic, delete that file, and the issue should be gone.
> 
> (for anyone else, you can find that path checking your logs)

Thank you. This solved my issue

**Comment by bobzurad** [comment]
Thanks, this solved my issue. For anyone that installed Heroic with yay, the lock file is in `~/.config/heroic/GamesConfig`
