### ISSUE TITLE
Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data. Retrying.

### ISSUE THREAD

**Issue by MTRNord** [Heroic-Games-Launcher/HeroicGamesLauncher#3981]
### Describe the bug

Prerelease Games for Epic Games crash the game's Overview page when the game is not yet released but already bought (preordered).

### Add logs

```text
(23:01:21) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary
(23:01:21) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl
(23:01:21) INFO:    [Connection]:       Connectivity: check-online
(23:01:21) INFO:    [Connection]:       Pinging external endpoints
(23:01:21) INFO:    [Gog]:              Checking for existing gog manifests
(23:01:21) WARNING: [Backend]:          Protocol already registered.
(23:01:21) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version
(23:01:21) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/marcel/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/marcel/.config/heroic/gog_store/auth.json --version
(23:01:21) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/marcel/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
(23:01:21) INFO:    [Connection]:       Connectivity: online
(23:01:21) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(23:01:21) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/marcel/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/marcel/.config/heroic/gog_store/auth.json auth
(23:01:21) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 7 3700X 8-Core Processor
Memory: 67.34 GB (used: 38.2 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT]
    IDs: D=73bf V=1002 SD=440e SV=1da2
    Driver: amdgpu
OS: Fedora Linux 40 (KDE Plasma) (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.15.1 Emeth
  Legendary: 0.20.35 Lowlife (Heroic)
  gogdl: 1.1.1
  comet: comet 0.1.2

  Nile: 1.1.1 Will A. Zeppeli

(23:01:21) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(23:01:21) INFO:    [Frontend]:         Refreshing undefined Library
(23:01:21) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(23:01:21) INFO:    [Legendary]:        Refreshing library...
(23:01:21) INFO:    [Legendary]:        Refreshing Epic Games...
(23:01:21) INFO:    [Backend]:          Frontend Ready
(23:01:21) INFO:    [Backend]:          Checking for new Heroic Updates
(23:01:22) INFO:    [Backend]:          Checking for current version changelog
(23:01:22) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party
(23:01:23) INFO:    [Winetricks]:       Downloading Winetricks
(23:01:23) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Star Wars Outlaws
(23:01:23) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Star Wars Outlaws
(23:01:23) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:23) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:23) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:24) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:24) INFO:    [Legendary]:        Game list updated, got 93 games & DLCs
(23:01:24) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(23:01:24) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party
(23:01:25) WARNING: [Backend]:          Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data. Retrying.
(23:01:25) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:25) WARNING: [Backend]:          Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data. Retrying.
(23:01:25) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:25) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:25) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:26) WARNING: [Backend]:          Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data. Retrying.
(23:01:26) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:26) WARNING: [Backend]:          Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data. Retrying.
(23:01:26) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:26) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:26) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:26) INFO:    [WineDownloader]:   Updating wine versions info
(23:01:26) INFO:    [WineDownloader]:   Fetching upstream information...
(23:01:26) INFO:    [Legendary]:        Found 0 games to update
(23:01:26) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:26) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:26) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:26) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:26) INFO:    [Backend]:          Starting the Download Queue
(23:01:26) INFO:    [WineDownloader]:   wine versions updated
(23:01:27) WARNING: [Backend]:          Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data. Retrying.
(23:01:27) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:27) WARNING: [Backend]:          Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data. Retrying.
(23:01:27) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:27) WARNING: [Backend]:          Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data. Retrying.
(23:01:27) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:27) WARNING: [Backend]:          Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data. Retrying.
(23:01:27) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:27) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:27) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:27) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:27) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:28) WARNING: [Backend]:          Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data. Retrying.
(23:01:28) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:28) WARNING: [Backend]:          Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data. Retrying.
(23:01:28) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:28) ERROR:   [Legendary]:        Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data after 3 retries.
    at Module.En (/opt/Heroic/resources/app.asar/build/main/main.js:114:2826)
    at /opt/Heroic/resources/app.asar/build/main/main.js:184:4032
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537)
(23:01:28) ERROR:   [Legendary]:        Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data after 3 retries.
    at Module.En (/opt/Heroic/resources/app.asar/build/main/main.js:114:2826)
    at /opt/Heroic/resources/app.asar/build/main/main.js:184:4032
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537)
(23:01:28) ERROR:   [Frontend]:         Cannot get game info
(23:01:28) ERROR:   [Frontend]:         Cannot get game info
(23:01:28) ERROR:   [Frontend]:         Cannot get game info
(23:01:28) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:28) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:29) WARNING: [Backend]:          Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data. Retrying.
(23:01:29) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:29) WARNING: [Backend]:          Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data. Retrying.
(23:01:29) INFO:    [Legendary]:        Getting more details with 'legendary info'
(23:01:29) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:29) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/marcel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 02636c0284e8474f8c0b066ac7d9807f --json --platform Windows
(23:01:30) ERROR:   [Legendary]:        Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data after 3 retries.
    at Module.En (/opt/Heroic/resources/app.asar/build/main/main.js:114:2826)
    at /opt/Heroic/resources/app.asar/build/main/main.js:184:4032
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537)
(23:01:30) ERROR:   [Legendary]:        Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Failed to parse install info for 02636c0284e8474f8c0b066ac7d9807f with: Error: Install info for 02636c0284e8474f8c0b066ac7d9807f does not include manifest data after 3 retries.
    at Module.En (/opt/Heroic/resources/app.asar/build/main/main.js:114:2826)
    at /opt/Heroic/resources/app.asar/build/main/main.js:184:4032
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537)
(23:01:30) ERROR:   [Frontend]:         Cannot get game info
(23:01:30) ERROR:   [Frontend]:         Cannot get game info
(23:01:30) ERROR:   [Frontend]:         Cannot get game info
(23:01:32) ERROR:   [Frontend]:         Cannot get game info
```

### Steps to reproduce

1. Preorder a game
2. Go to Library
3. Open the Game Details
4. Wait a few seconds -> Crashed view

### Expected behavior

It should either say its not available or show 0 but not crash/error out

### Screenshots

![grafik](https://github.com/user-attachments/assets/93c401a1-d754-4675-92d0-f6a814d85648)

### Heroic Version

Latest Stable

### System Information

- OS: Fedora 40

**Comment by arielj** [comment]
is this still a problem?
