### ISSUE TITLE
Amazon Games not showing after login

### ISSUE THREAD

**Issue by Tedeskio** [Heroic-Games-Launcher/HeroicGamesLauncher#4005]
### Describe the bug

I can login with my amazon account but no games are showed in library.

### Add logs

```text
[09/09/2024, 18:01:19] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
[09/09/2024, 18:01:19] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
INFO [LIBRARY]:	 Synchronizing library
1.1.1 Will A. Zeppeli
[09/09/2024, 18:01:19] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
Traceback (most recent call last):
  File "requests/models.py", line 974, in json
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nile/cli.py", line 354, in <module>
  File "nile/cli.py", line 333, in main
  File "nile/cli.py", line 140, in handle_library
  File "nile/api/library.py", line 109, in sync
  File "requests/models.py", line 978, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[12934] Failed to execute script 'cli' due to unhandled exception!
[09/09/2024, 18:01:28] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile list-updates --json
ERROR [CLI]:	 No games installed
[]
[09/09/2024, 18:01:29] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
INFO [LIBRARY]:	 Synchronizing library
Traceback (most recent call last):
  File "requests/models.py", line 974, in json
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nile/cli.py", line 354, in <module>
  File "nile/cli.py", line 333, in main
  File "nile/cli.py", line 140, in handle_library
  File "nile/api/library.py", line 109, in sync
  File "requests/models.py", line 978, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[13180] Failed to execute script 'cli' due to unhandled exception!
[09/09/2024, 18:04:01] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
INFO [LIBRARY]:	 Synchronizing library
[09/09/2024, 18:04:05] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
Traceback (most recent call last):
  File "requests/models.py", line 974, in json
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nile/cli.py", line 354, in <module>
  File "nile/cli.py", line 333, in main
  File "nile/cli.py", line 140, in handle_library
  File "nile/api/library.py", line 109, in sync
  File "requests/models.py", line 978, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[13381] Failed to execute script 'cli' due to unhandled exception!
[09/09/2024, 18:04:29] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile auth --logout
INFO [AUTH_MANAGER]:	 Successfully deregistered a device
[09/09/2024, 18:04:32] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile auth --login --non-interactive
{"client_id":"<redacted>","code_verifier":"<redacted>","serial":"<redacted>","url":"<redacted>"}
[09/09/2024, 18:04:51] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile register --code <redacted> --code-verifier sxdMZR5GSkmKKiHpjjSPuEgdJWjXeKK3jp41gnTtGok --serial 33BE78206EC511EFB2169C6B000A11E3 --client-id 3333424537383230364543353131454642323136394336423030304131314533234132554d56484f58375550345637
INFO [AUTH_MANAGER]:	 Registerring a device. ID: 3333424537383230364543353131454642323136394336423030304131314533234132554d56484f58375550345637
INFO [AUTH_MANAGER]:	 Succesfully registered a device
INFO [AUTH_MANAGER]:	 Written data to the config
INFO [LIBRARY]:	 Synchronizing library
Traceback (most recent call last):
  File "requests/models.py", line 974, in json
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nile/cli.py", line 354, in <module>
  File "nile/cli.py", line 331, in main
  File "nile/cli.py", line 94, in handle_register
  File "nile/api/authorization.py", line 188, in handle_login
  File "nile/api/library.py", line 109, in sync
  File "requests/models.py", line 978, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[13450] Failed to execute script 'cli' due to unhandled exception!
[09/09/2024, 18:04:58] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
[09/09/2024, 18:04:58] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
INFO [LIBRARY]:	 Synchronizing library
[09/09/2024, 18:05:02] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
Traceback (most recent call last):
  File "requests/models.py", line 974, in json
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nile/cli.py", line 354, in <module>
  File "nile/cli.py", line 333, in main
  File "nile/cli.py", line 140, in handle_library
  File "nile/api/library.py", line 109, in sync
  File "requests/models.py", line 978, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[13463] Failed to execute script 'cli' due to unhandled exception!
[09/09/2024, 18:05:07] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
INFO [LIBRARY]:	 Synchronizing library
Traceback (most recent call last):
  File "requests/models.py", line 974, in json
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nile/cli.py", line 354, in <module>
  File "nile/cli.py", line 333, in main
  File "nile/cli.py", line 140, in handle_library
  File "nile/api/library.py", line 109, in sync
  File "requests/models.py", line 978, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[13477] Failed to execute script 'cli' due to unhandled exception!
[09/09/2024, 18:05:23] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
INFO [LIBRARY]:	 Synchronizing library
Traceback (most recent call last):
  File "requests/models.py", line 974, in json
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nile/cli.py", line 354, in <module>
  File "nile/cli.py", line 333, in main
  File "nile/cli.py", line 140, in handle_library
  File "nile/api/library.py", line 109, in sync
  File "requests/models.py", line 978, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[13483] Failed to execute script 'cli' due to unhandled exception!
[09/09/2024, 18:05:31] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile list-updates --json
ERROR [CLI]:	 No games installed
[]
[09/09/2024, 18:05:31] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
INFO [LIBRARY]:	 Synchronizing library
Traceback (most recent call last):
  File "requests/models.py", line 974, in json
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nile/cli.py", line 354, in <module>
  File "nile/cli.py", line 333, in main
  File "nile/cli.py", line 140, in handle_library
  File "nile/api/library.py", line 109, in sync
  File "requests/models.py", line 978, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[13505] Failed to execute script 'cli' due to unhandled exception!
[09/09/2024, 18:05:54] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
1.1.1 Will A. Zeppeli
[09/09/2024, 18:06:15] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
1.1.1 Will A. Zeppeli
[09/09/2024, 18:06:18] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
INFO [LIBRARY]:	 Synchronizing library
[09/09/2024, 18:06:23] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
Traceback (most recent call last):
  File "requests/models.py", line 974, in json
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nile/cli.py", line 354, in <module>
  File "nile/cli.py", line 333, in main
  File "nile/cli.py", line 140, in handle_library
  File "nile/api/library.py", line 109, in sync
  File "requests/models.py", line 978, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[13551] Failed to execute script 'cli' due to unhandled exception!
[09/09/2024, 18:15:27] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
1.1.1 Will A. Zeppeli
[09/09/2024, 18:15:28] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
1.1.1 Will A. Zeppeli
[09/09/2024, 18:15:50] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
1.1.1 Will A. Zeppeli
[09/09/2024, 18:17:41] NILE_CONFIG_PATH=/home/nykos/.config/heroic/nile_config /opt/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
1.1.1 Will A. Zeppeli
```

### Steps to reproduce

1. Login with Amazon Account
2. Click on Library

### Expected behavior

Showing up my Amazon Games in Library

### Screenshots

![Schermata_20240909_182546](https://github.com/user-attachments/assets/5156702e-576f-4f78-842b-adc243df6a6e)

### Heroic Version

Latest Stable

### System Information

- OS CachyOS Linux

**Comment by Scorp48** [comment]
I have the same error "requests.exceptions.JSONDecodeError" and looking in the nile issues i see this https://github.com/imLinguin/nile/issues/50#issuecomment-2333404405

**Comment by circlesmiler** [comment]
I tried the "Ubuntu Build" of `nile` on my steam deck but it couldn't read the binary. Is there a instruction on how to get this work on Steam Deck?

**Comment by circlesmiler** [comment]
You can find build for the latest commit of `nile` here:

https://github.com/imLinguin/nile/commits/main/

![image](https://github.com/user-attachments/assets/17c343de-aa63-4e8b-857e-4d402a8013f1)

**Comment by circlesmiler** [comment]
There is a new `nile` version `1.1.2` available:

https://github.com/imLinguin/nile/releases/tag/v1.1.2

**Comment by Terminykos** [comment]
> There is a new `nile` version `1.1.2` available:
> 
> https://github.com/imLinguin/nile/releases/tag/v1.1.2

This fixed the problem, thank you!
