### ISSUE TITLE
Can't Install Cities Skylines

### ISSUE THREAD

**Issue by 0bsidianFox** [Heroic-Games-Launcher/HeroicGamesLauncher#4015]
### Describe the bug

Downloaded the game but it wont install

### Add logs

```text
Legendary (Epic Games)
Error:
An error has occurred! Try to Logout and Login on your Epic account.
[Core] INFO: Trying to re-use existing login session...[cli] INFO: Preparing download for "Cities Skylines" (bcbc03d8812a44c18f41cf7d5f849265)...[Core] INFO: Parsing game manifest...[Core] INFO: Install path: E:\Epic Games Library\CitiesSkylines[Core] INFO: Selected CDN: download.epicgames.com (https)[DLM] INFO: Found previously interrupted download. Download will be resumed if possible.[DLM] INFO: Skipping 2005 files based on resume data.[cli] INFO: Download size is 0, the game is either already up to date or has not changed. Exiting...
Traceback (most recent call last):
File "legendary\cli.py", line 3161, in <module>File "legendary\cli.py", line 3078, in mainFile "legendary\cli.py", line 1002, in install_gameAttributeError: 'NoneType' object has no attribute 'install_tags'
[15440] Failed to execute script 'cli' dueto unhandled exception!
```

### Steps to reproduce

Try Installing the game on an external hdd with dlc selected

### Expected behavior

the game should have installed

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Windows 10 22H2

**Comment by arielj** [comment]
Closing as this is likely solved after all this time. If it's still an issue we can reopen it.
