### ISSUE TITLE
Custom WINE not Being Found

### ISSUE THREAD

**Issue by ArsThaumaturgis** [Heroic-Games-Launcher/HeroicGamesLauncher#4026]
### Describe the bug

First, let me say that it's entirely possible that I'm doing something wrong; if so, please direct me aright!

That said: I'm trying to run a game, and to do so specifically with a development version of WINE, and I can't seem to get Heroic to recognise that version.

I've tried going to Settings->Custom Wine/Proton Paths and adding it there. It appears to do so, but on going to select that version in the game's settings, I'm presented with a different path; trying it anyway, I get a "Wine not found!" error.

I've also tried manually adding the path to the development version of WINE to the configuration file. This at least produces the expected path. However, that path is deemed "invalid", and is likewise met with "Wine not found!". :/

To explain:

The game is not working with the default version of WINE that comes with Heroic. This is not entirely unexpected--I've had trouble with this game.

However, it's been suggested to me that I try a development version of WINE, and I have indeed had some success with such, albeit in a different launcher.

Now it's been suggested to me that I try Heroic, primarily in the hopes of getting past the last issue that I'm facing with running the game.

And... I'm struggling to get Heroic to recognise the development version of WINE.

### Add logs

```text
(17:44:19) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary
(17:44:19) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl
(17:44:19) INFO:    [Connection]:       Connectivity: check-online
(17:44:19) INFO:    [Connection]:       Pinging external endpoints
(17:44:19) INFO:    [Gog]:              Checking for existing gog manifests
(17:44:19) WARNING: [Backend]:          Failed to register protocol with OS.
(17:44:20) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/thaumaturge/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version
(17:44:20) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/thaumaturge/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/thaumaturge/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(17:44:20) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/thaumaturge/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
(17:44:20) INFO:    [Connection]:       Connectivity: online
(17:44:20) INFO:    [Backend]:          User Not Found, removing it from Store
(17:44:20) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(17:44:20) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/thaumaturge/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/thaumaturge/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(17:44:20) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(17:44:20) INFO:    [Backend]:          
System Information:
CPU: 4x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
Memory: 8.23 GB (used: 5.06 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GM108M [GeForce 840M]
    IDs: D=1341 V=10de SD=0656 SV=1028
    Driver: nvidia
  GPU 1:
    Name: Intel Corporation HD Graphics 5500
    IDs: D=1616 V=8086 SD=0656 SV=1028
    Driver: i915
OS: Ubuntu 22.04.5 LTS (Jammy Jellyfish) (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.15.2 Emeth
  Legendary: 0.20.36 Urban Flight (Heroic)
  gogdl: 1.1.2
  comet: comet 0.1.2

  Nile: 1.1.2 Will A. Zeppeli

(17:44:21) INFO:    [Backend]:          Frontend Ready
(17:44:21) INFO:    [Backend]:          Checking for current version changelog
(17:44:22) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(17:44:22) INFO:    [Winetricks]:       Downloading Winetricks
(17:44:23) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(17:44:24) INFO:    [WineDownloader]:   Updating wine versions info
(17:44:24) INFO:    [WineDownloader]:   Fetching upstream information...
(17:44:26) INFO:    [Backend]:          Starting the Download Queue
(17:44:26) INFO:    [WineDownloader]:   wine versions updated
(17:44:26) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(17:44:28) INFO:    [Backend]:          7G89BLnHgadNhbGLwFXyjK: Setting wineVersion to {"bin":"/opt/wine-devel/bin/wine","name":"Custom Wine - /opt/wine-devel/bin/wine","type":"wine","wineserver":""}
(17:45:24) INFO:    [Backend]:          Launching 9 Years of Shadows (7G89BLnHgadNhbGLwFXyjK)
(17:45:24) INFO:    [Backend]:          Preventing display from sleep
(17:45:24) INFO:    [Backend]:          Checking if wine version exists: Custom Wine - /opt/wine-devel/bin/wine
(17:45:24) ERROR:   [Backend]:          Wine version Custom Wine - /opt/wine-devel/bin/wine is not valid, trying another one.
(17:45:24) INFO:    [Backend]:          Checking if wine version exists: Default Wine - Not Found
(17:45:24) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(17:45:24) INFO:    [Backend]:          Checking if wine version exists: Wine - wine-ge-8-26-x86_64
(17:45:24) INFO:    [Backend]:          Preventing machine to sleep
(17:45:32) INFO:    [Backend]:          User canceled the launch
(17:45:32) ERROR:   [Backend]:          Was not possible to launch using Custom Wine - /opt/wine-devel/bin/wine
(17:45:32) INFO:    [Frontend]:         Refreshing sideload Library
(17:45:32) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(17:45:32) INFO:    [Backend]:          Stopping Power Saver Blocker
(17:45:37) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for 9 Years of Shadows
(17:45:37) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for 9 Years of Shadows
(17:45:37) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for 9 Years of Shadows
(17:45:37) INFO:    [ExtraGameInfo]:    Getting GamesDB data for 9 Years of Shadows
(17:45:37) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for 9 Years of Shadows
(17:45:37) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for 9 Years of Shadows
(17:45:37) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for 9 Years of Shadows
(17:45:37) INFO:    [ExtraGameInfo]:    Getting GamesDB data for 9 Years of Shadows
(17:45:37) WARNING: [Backend]:          getExtraInfo not implemented on Sideload Game Manager. called for appName = 7G89BLnHgadNhbGLwFXyjK
(17:45:37) ERROR:   [ExtraGameInfo]:    Got AxiosError when sending HowLongToBeat request for 9 Years of Shadows: {
  "message": "Request failed with status code 404",
  "name": "Error",
  "stack": "Error: Request failed with status code 404\n    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)\n    at IncomingMessage.emit (node:events:531:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "headers": {
      "Accept": "*/*",
      "Content-Type": "application/json",
      "User-Agent": "HeroicGamesLauncher/2.15.2",
      "Referer": "https://howlongtobeat.com/",
      "Content-Length": 359
    },
    "method": "post",
    "url": "https://www.howlongtobeat.com/api/search",
    "data": "{\"searchType\":\"games\",\"searchTerms\":[\"9\",\"Years\",\"of\",\"Shadows\"],\"searchPage\":1,\"size\":20,\"searchOptions\":{\"games\":{\"userId\":0,\"platform\":\"\",\"sortCategory\":\"popular\",\"rangeCategory\":\"main\",\"rangeTime\":{\"min\":0,\"max\":0},\"gameplay\":{\"perspective\":\"\",\"flow\":\"\",\"genre\":\"\"},\"modifier\":\"\"},\"users\":{\"sortCategory\":\"postcount\"},\"filter\":\"\",\"sort\":0,\"randomizer\":0}}"
  },
  "status": 404
}
(17:45:37) ERROR:   [ExtraGameInfo]:    Got AxiosError when sending HowLongToBeat request for 9 Years of Shadows: {
  "message": "Request failed with status code 404",
  "name": "Error",
  "stack": "Error: Request failed with status code 404\n    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)\n    at IncomingMessage.emit (node:events:531:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "headers": {
      "Accept": "*/*",
      "Content-Type": "application/json",
      "User-Agent": "HeroicGamesLauncher/2.15.2",
      "Referer": "https://howlongtobeat.com/",
      "Content-Length": 359
    },
    "method": "post",
    "url": "https://www.howlongtobeat.com/api/search",
    "data": "{\"searchType\":\"games\",\"searchTerms\":[\"9\",\"Years\",\"of\",\"Shadows\"],\"searchPage\":1,\"size\":20,\"searchOptions\":{\"games\":{\"userId\":0,\"platform\":\"\",\"sortCategory\":\"popular\",\"rangeCategory\":\"main\",\"rangeTime\":{\"min\":0,\"max\":0},\"gameplay\":{\"perspective\":\"\",\"flow\":\"\",\"genre\":\"\"},\"modifier\":\"\"},\"users\":{\"sortCategory\":\"postcount\"},\"filter\":\"\",\"sort\":0,\"randomizer\":0}}"
  },
  "status": 404
}
(17:45:39) ERROR:   [ExtraGameInfo]:    Was not able to get ProtonDB data for 1402120 undefined
(17:45:39) DEBUG:   [Backend]:          No response when getting ProtonDB info
(17:45:39) DEBUG:   [Backend]:          SteamDeck data for 1402120 {"success":1,"results":{"appid":1402120,"resolved_category":2,"resolved_items":[{"display_type":3,"loc_token":"#SteamDeckVerified_TestResult_InterfaceTextIsNotLegible"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultControllerConfigFullyFunctional"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_ControllerGlyphsMatchDeckDevice"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultConfigurationIsPerformant"},{"display_type":1,"loc_token":"#SteamDeckVerified_TestResult_ExternalControllersNotSupportedPrimaryPlayer"}],"steam_deck_blog_url":"","search_id":null}}
(17:45:39) DEBUG:   [Backend]:          SteamDeck data for 1402120 {"success":1,"results":{"appid":1402120,"resolved_category":2,"resolved_items":[{"display_type":3,"loc_token":"#SteamDeckVerified_TestResult_InterfaceTextIsNotLegible"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultControllerConfigFullyFunctional"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_ControllerGlyphsMatchDeckDevice"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultConfigurationIsPerformant"},{"display_type":1,"loc_token":"#SteamDeckVerified_TestResult_ExternalControllersNotSupportedPrimaryPlayer"}],"steam_deck_blog_url":"","search_id":null}}
(17:45:39) ERROR:   [ExtraGameInfo]:    Was not able to get ProtonDB data for 1402120 undefined
(17:45:39) DEBUG:   [Backend]:          No response when getting ProtonDB info
(17:45:41) INFO:    [Backend]:          Launching 9 Years of Shadows (7G89BLnHgadNhbGLwFXyjK)
(17:45:41) INFO:    [Backend]:          Preventing display from sleep
(17:45:41) INFO:    [Backend]:          Checking if wine version exists: Custom Wine - /opt/wine-devel/bin/wine
(17:45:41) ERROR:   [Backend]:          Wine version Custom Wine - /opt/wine-devel/bin/wine is not valid, trying another one.
(17:45:41) INFO:    [Backend]:          Checking if wine version exists: Default Wine - Not Found
(17:45:41) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(17:45:41) INFO:    [Backend]:          Checking if wine version exists: Wine - wine-ge-8-26-x86_64
(17:45:41) INFO:    [Backend]:          Preventing machine to sleep
(17:45:41) WARNING: [Backend]:          getExtraInfo not implemented on Sideload Game Manager. called for appName = 7G89BLnHgadNhbGLwFXyjK
(17:48:13) INFO:    [Backend]:          User canceled the launch
(17:48:13) ERROR:   [Backend]:          Was not possible to launch using Custom Wine - /opt/wine-devel/bin/wine
(17:48:13) INFO:    [Frontend]:         Refreshing sideload Library
(17:48:13) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(17:48:13) INFO:    [Backend]:          Stopping Power Saver Blocker
(17:48:13) WARNING: [Backend]:          getExtraInfo not implemented on Sideload Game Manager. called for appName = 7G89BLnHgadNhbGLwFXyjK
(17:48:13) WARNING: [Backend]:          getExtraInfo not implemented on Sideload Game Manager. called for appName = 7G89BLnHgadNhbGLwFXyjK
(17:48:18) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(17:49:45) INFO:    [Backend]:          Heroic: Setting customWinePaths to ["/opt/wine-devel/bin/wine","/run/user/1000/doc/3ea161b3/wine"] (previous value: ["/opt/wine-devel/bin/wine"])
(17:49:55) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(17:49:59) INFO:    [Backend]:          7G89BLnHgadNhbGLwFXyjK: Setting wineVersion to {"bin":"/run/user/1000/doc/3ea161b3/wine","name":"Custom Wine - /run/user/1000/doc/3ea161b3/wine","type":"wine","wineserver":""}
(17:50:02) INFO:    [Backend]:          Launching 9 Years of Shadows (7G89BLnHgadNhbGLwFXyjK)
(17:50:02) INFO:    [Backend]:          Checking if wine version exists: Custom Wine - /run/user/1000/doc/3ea161b3/wine
(17:50:02) ERROR:   [Backend]:          Wine version Custom Wine - /run/user/1000/doc/3ea161b3/wine is not valid, trying another one.
(17:50:02) INFO:    [Backend]:          Checking if wine version exists: Default Wine - Not Found
(17:50:02) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(17:50:02) INFO:    [Backend]:          Checking if wine version exists: Wine - wine-ge-8-26-x86_64
(17:50:02) INFO:    [Backend]:          Preventing machine to sleep
(17:50:04) INFO:    [Backend]:          User canceled the launch
(17:50:04) ERROR:   [Backend]:          Was not possible to launch using Custom Wine - /run/user/1000/doc/3ea161b3/wine
(17:50:04) INFO:    [Frontend]:         Refreshing sideload Library
(17:50:04) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(17:50:04) INFO:    [Backend]:          Stopping Power Saver Blocker
(17:50:06) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(17:52:40) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(17:52:47) INFO:    [Backend]:          Checking if wine version exists: Custom Wine - /run/user/1000/doc/3ea161b3/wine
(17:52:47) INFO:    [Backend]:          Checking if wine version exists: Default Wine - Not Found
(17:52:47) INFO:    [Backend]:          Checking if wine version exists: Custom Wine - /run/user/1000/doc/3ea161b3/wine
(17:53:22) INFO:    [Backend]:          Checking if wine version exists: Custom Wine - /run/user/1000/doc/3ea161b3/wine
(17:53:22) INFO:    [Backend]:          Checking if wine version exists: Default Wine - Not Found
(17:53:22) INFO:    [Backend]:          Checking if wine version exists: Custom Wine - /run/user/1000/doc/3ea161b3/wine
(18:00:17) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(18:01:20) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(18:01:27) INFO:    [Backend]:          Launching 9 Years of Shadows (7G89BLnHgadNhbGLwFXyjK)
(18:01:27) INFO:    [Backend]:          Checking if wine version exists: Custom Wine - /run/user/1000/doc/3ea161b3/wine
(18:01:27) ERROR:   [Backend]:          Wine version Custom Wine - /run/user/1000/doc/3ea161b3/wine is not valid, trying another one.
(18:01:27) INFO:    [Backend]:          Checking if wine version exists: Default Wine - Not Found
(18:01:27) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(18:01:27) INFO:    [Backend]:          Checking if wine version exists: Wine - wine-ge-8-26-x86_64
(18:01:27) INFO:    [Backend]:          Preventing machine to sleep
(18:01:42) INFO:    [Backend]:          User canceled the launch
(18:01:42) ERROR:   [Backend]:          Was not possible to launch using Custom Wine - /run/user/1000/doc/3ea161b3/wine
(18:01:42) INFO:    [Frontend]:         Refreshing sideload Library
(18:01:42) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(18:01:42) INFO:    [Backend]:          Stopping Power Saver Blocker
(18:01:44) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(18:01:47) INFO:    [Backend]:          7G89BLnHgadNhbGLwFXyjK: Setting wineVersion to {"bin":"/opt/wine-devel/bin/wine","name":"Custom Wine - /opt/wine-devel/bin/wine","type":"wine","wineserver":""}
(18:02:38) INFO:    [Backend]:          Launching 9 Years of Shadows (7G89BLnHgadNhbGLwFXyjK)
(18:02:38) INFO:    [Backend]:          Checking if wine version exists: Custom Wine - /opt/wine-devel/bin/wine
(18:02:38) ERROR:   [Backend]:          Wine version Custom Wine - /opt/wine-devel/bin/wine is not valid, trying another one.
(18:02:38) INFO:    [Backend]:          Checking if wine version exists: Default Wine - Not Found
(18:02:38) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(18:02:38) INFO:    [Backend]:          Checking if wine version exists: Wine - wine-ge-8-26-x86_64
(18:02:38) INFO:    [Backend]:          Preventing machine to sleep
(18:03:05) INFO:    [Backend]:          User canceled the launch
(18:03:05) ERROR:   [Backend]:          Was not possible to launch using Custom Wine - /opt/wine-devel/bin/wine
(18:03:05) INFO:    [Frontend]:         Refreshing sideload Library
(18:03:05) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(18:03:05) INFO:    [Backend]:          Stopping Power Saver Blocker
(18:03:17) INFO:    [Backend]:          Launching 9 Years of Shadows (7G89BLnHgadNhbGLwFXyjK)
(18:03:17) INFO:    [Backend]:          Checking if wine version exists: Custom Wine - /opt/wine-devel/bin/wine
(18:03:17) ERROR:   [Backend]:          Wine version Custom Wine - /opt/wine-devel/bin/wine is not valid, trying another one.
(18:03:17) INFO:    [Backend]:          Checking if wine version exists: Default Wine - Not Found
(18:03:17) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(18:03:17) INFO:    [Backend]:          Checking if wine version exists: Wine - wine-ge-8-26-x86_64
(18:03:17) INFO:    [Backend]:          Preventing machine to sleep
(18:03:38) INFO:    [Backend]:          User canceled the launch
(18:03:38) ERROR:   [Backend]:          Was not possible to launch using Custom Wine - /opt/wine-devel/bin/wine
(18:03:38) INFO:    [Frontend]:         Refreshing sideload Library
(18:03:38) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(18:03:38) INFO:    [Backend]:          Stopping Power Saver Blocker
```

### Steps to reproduce

(At least on my machine)

* Go to Settings->Custom Wine/Proton Paths
* Add a development version of WINE there, specifically from opt/wine-devel/bin/wine
* Go to a game and select a custom WINE version there
* Attempt to run the game

### Expected behavior

That the development version of WINE would be recognised and used to run the game.

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS: Ubuntu Linux 22.04.5
- wine-devel version:  wine-9.18

**Comment by mbtns** [comment]
For me the add custom wine functionality is also not working on Fedora Silverblue 40 with both Heroic and Steam as flatpaks.

1) I expected the function to take a path to the wine folder rather than forcing me to select a file.  
2) Adding the custom wine folder to the wine folder in the [tools folder](https://github-wiki-see.page/m/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/How-To%3A-Wine-and-Proton 
) manually does work.

**Comment by arielj** [comment]
Make sure the selected folder is accessible by the flatpak container, you can use flatseal to configure what heroic can access.

**Comment by ArsThaumaturgis** [comment]
In my case, as far as I recall I'm not using Flatpak. I think that I just used the old "apt install" approach.
