### ISSUE TITLE
unable to install ark dev kit

### ISSUE THREAD

**Issue by Ninjastorm380** [Heroic-Games-Launcher/HeroicGamesLauncher#4054]
### Describe the bug

Heroic fails to begin installing the ark ascended devkit. Latest legendary binary (installed from AUR) also can reproduce this. Applying `--max-shared-memory 7249` to legendary solves the issue for legendary, and should also solve for heroic.

### Add logs

heroic log provides nothing useful. see the legendary log instead.

### Heroic:
```text
(18:42:42) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/prydaran/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party

(18:42:43) INFO:    [Legendary]:        Game list updated, got 8 games & DLCs

(22:00:49) INFO:    [Backend]:          Heroic: Setting maxWorkers to 1 (previous value: 0)

(08:07:25) INFO:    [Legendary]:        Getting more details with 'legendary info'

(08:07:26) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/prydaran/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info fb67ca3f5de74da880ab96bdc668118d --json --platform Windows

(08:08:03) INFO:    [Backend]:          Writing config for fb67ca3f5de74da880ab96bdc668118d

(08:08:03) INFO:    [Backend]:          Changed config: winePrefix from /home/prydaran/Games/Heroic/Prefixes/default to /mnt/storage/heroic/Prefixes/default/ARK DevKit

(08:08:03) INFO:    [Backend]:          Changed config: wineCrossoverBottle from undefined to 

(08:08:03) DEBUG:   [Legendary]:        Using cached install info

(08:08:03) INFO:    [DownloadManager]:  ARK DevKit  was added to the download queue.

(08:08:03) DEBUG:   [Legendary]:        Using cached install info

(08:08:03) INFO:    [Legendary]:        Installing fb67ca3f5de74da880ab96bdc668118d: LEGENDARY_CONFIG_PATH=/home/prydaran/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary install fb67ca3f5de74da880ab96bdc668118d --platform Windows --base-path /mnt/storage/heroic --skip-dlcs -y --max-workers 1 --skip-sdl

(08:08:03) DEBUG:   [Legendary]:        Logging to file "/home/prydaran/.config/heroic/GamesConfig/fb67ca3f5de74da880ab96bdc668118d.log"

(08:08:03) INFO:    [Backend]:          Preventing machine to sleep

(08:08:53) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/prydaran/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary install fb67ca3f5de74da880ab96bdc668118d --platform Windows --base-path /mnt/storage/heroic --skip-dlcs -y --max-workers 1 --skip-sdl --max-shared-memory 5000

(08:08:53) DEBUG:   [Legendary]:        Logging to file "/home/prydaran/.config/heroic/GamesConfig/fb67ca3f5de74da880ab96bdc668118d.log"

(08:09:22) INFO:    [Backend]:          Adding shortcuts for ARK DevKit

(08:09:22) INFO:    [DownloadManager]:  Finished Installation of fb67ca3f5de74da880ab96bdc668118d

(08:09:22) INFO:    [DownloadManager]:  fb67ca3f5de74da880ab96bdc668118d added to download manager finished.

(08:09:22) INFO:    [DownloadManager]:  fb67ca3f5de74da880ab96bdc668118d removed from download manager.

(08:09:22) INFO:    [Frontend]:         Refreshing legendary Library

(08:09:22) INFO:    [Legendary]:        Refreshing library...

(08:09:22) INFO:    [Legendary]:        Refreshing Epic Games...

(08:09:22) INFO:    [Backend]:          Stopping Power Saver Blocker

(08:09:22) INFO:    [Backend]:          Shortcut saved on /home/prydaran/.local/share/applications/ARK DevKit.desktop

(08:09:23) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/prydaran/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party

(08:09:24) INFO:    [DownloadManager]:  Downloader: Finished downloading https://cdn1.epicgames.com/item/dae80c0d4e3b4d648498b48af609b8bb/EGS_ARKDevKit_StudioWildcard_S2_1200x1600-768b5c1d5bab2da1d6cf825647d431e6

(08:09:24) INFO:    [Legendary]:        Game list updated, got 8 games & DLCs
```

### Legendary (Built in):
```
[10/11/2024, 8:07:26 AM] LEGENDARY_CONFIG_PATH=/home/prydaran/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info fb67ca3f5de74da880ab96bdc668118d --json --platform Windows

[Core] INFO: Logging in...

{"game": {"app_name": "fb67ca3f5de74da880ab96bdc668118d", "title": "ARK DevKit", "version": "53.9.138.582884", "platform_versions": {"Windows": "53.9.138.582884"}, "cloud_saves_supported": false, "cloud_save_folder": null, "cloud_save_folder_mac": null, "is_dlc": false, "external_activation": null, "launch_options": [], "command_line": null, "owned_dlc": []}, "install": null, "manifest": {"size": 98634325, "type": "binary", "version": 21, "feature_level": 21, "app_name": "13f4dacea37e4f99be9def349405de22", "launch_exe": "Engine/Binaries/Win64/ShooterGameEditor.exe", "launch_command": "ShooterGame/ShooterGame.uproject -Installed -log -DontBuildEditorGrass -AllowPCG -NetDriverOverrides=/Script/OnlineSubsystemUtils.IpNetDriver", "build_version": "53.9.138.582884", "build_id": "_sbweLfaXEyqDfdOHywuWA", "prerequisites": null, "uninstaller": null, "install_tags": [""], "num_files": 593734, "num_chunks": 696518, "disk_size": 747135408243, "download_size": 648943627722, "tag_disk_size": [], "tag_download_size": []}}

[10/11/2024, 8:08:03 AM] LEGENDARY_CONFIG_PATH=/home/prydaran/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary install fb67ca3f5de74da880ab96bdc668118d --platform Windows --base-path /mnt/storage/heroic --skip-dlcs -y --max-workers 1 --skip-sdl

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Preparing download for "ARK DevKit" (fb67ca3f5de74da880ab96bdc668118d)...

[Core] WARNING: Unable to download manifest from "fastly-download.epicgames.com" (Exception: ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='fastly-download.epicgames.com', port=443): Max retries exceeded with url: /Builds/Org/o-usvfbmlqdt678vrp36qvm2d5cz2cpr/985dc4d67ff142588b6393c46b1dff84/default/r0YZjGGI7d27tJDAnEC-YhQ79uws0Q.manifest?f_token=1728648784_b7ecd56f511cd672c98287a6471a55f3ffd60e97 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x784dd34556a0>, 'Connection to fastly-download.epicgames.com timed out. (connect timeout=10.0)'))"))), trying next URL...

[Core] INFO: Parsing game manifest...

[Core] INFO: Install path: /mnt/storage/heroic/ARKDevkit

[Core] INFO: Selected CDN: fastly-download.epicgames.com (https)

[DLM] INFO: Found 0 missing files.

Traceback (most recent call last):

  File "legendary/cli.py", line 3224, in <module>

  File "legendary/cli.py", line 3139, in main

  File "legendary/cli.py", line 964, in install_game

  File "legendary/core.py", line 1504, in prepare_download

  File "legendary/downloader/mp/manager.py", line 416, in run_analysis

MemoryError: Current shared memory cache is smaller than required: 2048.0 MiB < 7217.0 MiB. Try running legendary with "--enable-reordering" to reduce memory usage, or use "--max-shared-memory 7249" to increase the limit.

[PYI-94247:ERROR] Failed to execute script 'cli' due to unhandled exception!

[10/11/2024, 8:08:53 AM] LEGENDARY_CONFIG_PATH=/home/prydaran/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary install fb67ca3f5de74da880ab96bdc668118d --platform Windows --base-path /mnt/storage/heroic --skip-dlcs -y --max-workers 1 --skip-sdl --max-shared-memory 5000

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Preparing download for "ARK DevKit" (fb67ca3f5de74da880ab96bdc668118d)...

[Core] INFO: Parsing game manifest...

[Core] INFO: Install path: /mnt/storage/heroic/ARKDevkit

[Core] INFO: Selected CDN: download.epicgames.com (https)

[DLM] INFO: Found 0 missing files.

Traceback (most recent call last):

  File "legendary/cli.py", line 3224, in <module>

  File "legendary/cli.py", line 3139, in main

  File "legendary/cli.py", line 964, in install_game

  File "legendary/core.py", line 1504, in prepare_download

  File "legendary/downloader/mp/manager.py", line 416, in run_analysis

MemoryError: Current shared memory cache is smaller than required: 5000.0 MiB < 7217.0 MiB. Try running legendary with "--enable-reordering" to reduce memory usage, or use "--max-shared-memory 7249" to increase the limit.

[PYI-94282:ERROR] Failed to execute script 'cli' due to unhandled exception!

[10/11/2024, 8:09:23 AM] LEGENDARY_CONFIG_PATH=/home/prydaran/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party

[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Getting game list... (this may take a while)

Available games:

 * ARK DevKit (App name: fb67ca3f5de74da880ab96bdc668118d | Version: 53.9.138.582884)

 * ARK DevKit Beta (App name: 95dc9c76e91041279de1f72f64d65f28 | Version: 53.9.138.582884)

 * ARK ModKit (UE4) (App name: ARKDevKit | Version: 358.2)

 * Dauntless (App name: Jackal | Version: 1.14.7.647472)

 * Ghost Recon Breakpoint Demo (App name: 4d7c1e25955644e9afe7054071f39603 | Version: 1.0.0.0.3)

  - This game can be activated directly on your Ubisoft account and does not require legendary to install/run. This game requires Ubisoft Connect to be installed. Use "legendary activate --uplay" and follow the instructions.

 * RAGE 2 (App name: ad3d0f08dd0841d8a1ba77d94ded4773 | Version: 1.21)

 * Rocket League® (App name: Sugar | Version: BC2_Update52+459935)

 * Warframe (App name: 398965b67f314d31b0683b8ea11c93a4 | Version: 2024.03.28.14.05-21293)

Total: 8
```
```


### Steps to reproduce

attempt to install the ark ascended devkit.

### Expected behavior

ark ascended devkit installs properly

### Screenshots

_No response_

### Heroic Version

Latest Stable

### System Information

OS: EndeavourOS (Arch derivative)

### Additional information

From what I read in other issues, heroic is supposed to retry with the correct amount of memory using '--max-shared-memory 7249'. Perhaps this feature is broken?

**Comment by sibradzic** [comment]
Same happens with STASIS: Bone Totem:

```
user@monolith:~$ LEGENDARY_CONFIG_PATH=/home/user/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary install 4e4e5473a79b40a1a4aee3bb0f612718 --platform Windows --base-path /home/user/Games/Heroic --skip-dlcs -y --skip-sdl --max-shared-memory 5000
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Preparing download for "STASIS : BONE TOTEM" (4e4e5473a79b40a1a4aee3bb0f612718)...
[Core] INFO: Parsing game manifest...
[Core] INFO: Install path: /home/user/Games/Heroic/STASISBONETOTEM
[Core] INFO: Selected CDN: cloudflare.epicgamescdn.com (https)
[DLM] INFO: Found 0 missing files.
Traceback (most recent call last):
  File "legendary/cli.py", line 3224, in <module>
  File "legendary/cli.py", line 3139, in main
  File "legendary/cli.py", line 964, in install_game
  File "legendary/core.py", line 1504, in prepare_download
  File "legendary/downloader/mp/manager.py", line 416, in run_analysis
MemoryError: Current shared memory cache is smaller than required: 5000.0 MiB < 16312.0 MiB. Try running legendary with "--enable-reordering" to reduce memory usage, or use "--max-shared-memory 16344" to increase the limit.
[PYI-26133:ERROR] Failed to execute script 'cli' due to unhandled exception!
```

Installs fine with `--max-shared-memory 16344`.

**Comment by Friedrich-S** [comment]
Hi, any update on this? It would be great to have a solution or workaround. Importing the DevKit from a windows-managed installation works, but it is cumbersome having to boot into windows just to update the DevKit.
I can confirm that this issue happens on my end as well, even after adding `--max-shared-memory 32768`.
OS: Fedora 42
Launcher version: 2.16.1

**Comment by arielj** [comment]
you can use the build from our fork of legendary that solves the issue with the memory https://github.com/Heroic-Games-Launcher/legendary

it was not included in the last release of heroic but you can use it in settings > advanced > alternative legendary binary

**Comment by Friedrich-S** [comment]
Thanks, that seems to be working.

**Comment by arielj** [comment]
closing as the legendary binary shipped with heroic solves the issue
