### ISSUE TITLE
Amazon/nile Heroic "KeyError: 'downloadUrls'" unhandled exception in logs when importing existing game folder

### ISSUE THREAD

**Issue by Bob837217** [Heroic-Games-Launcher/HeroicGamesLauncher#4055]
### Describe the bug

I copy my existing Amazon/nile game folder to my SSD.  Then I Install..., Import the game and select the folder on the SSD.
UI does something, then reverts back to "uninstalled" status for the game.  After checking the "Amazon/Nile" log entries in Heroic, I can see an error reported upon performing the Import of the existing game folder on my SSD.

### Add logs

```text
[12/10/2024, 09:00:38] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
[12/10/2024, 09:00:39] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
INFO [AUTH_MANAGER]:	 Refreshing token
INFO [LIBRARY]:	 Synchronizing library
1.1.2 Will A. Zeppeli
INFO [LIBRARY]:	 Successfully synced the library
[12/10/2024, 09:00:41] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
INFO [LIBRARY]:	 Synchronizing library
INFO [LIBRARY]:	 Successfully synced the library
[12/10/2024, 09:01:24] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile list-updates --json
["amzn1.adg.product.43251731-1ef4-4c83-8318-c16f7cf5fe8e"]
[12/10/2024, 19:40:02] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile install --info --json amzn1.adg.product.c25c2ac3-b318-4192-96b7-bafef73060b9
INFO [AUTH_MANAGER]:	 Refreshing token
INFO [CLI]:	 Found: Wall World
{"download_size": 2039236053}
[12/10/2024, 19:40:17] NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile import --path "/media/user/DataSSD/Games/Wall World" amzn1.adg.product.c25c2ac3-b318-4192-96b7-bafef73060b9
INFO [CLI]:	 Searching for amzn1.adg.product.c25c2ac3-b318-4192-96b7-bafef73060b9
INFO [IMPORT]:	 	Verifying local files
Traceback (most recent call last):
  File "nile/cli.py", line 354, in <module>
  File "nile/cli.py", line 343, in main
  File "nile/cli.py", line 302, in handle_import
  File "nile/utils/importer.py", line 76, in import_game
  File "nile/utils/importer.py", line 44, in verify_integrity
  File "nile/utils/importer.py", line 25, in get_patchmanifest
KeyError: 'downloadUrls'
[PYI-1290:ERROR] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Find the Amazon game tile for "Wall World" (in this example)
2. Click on Install arrow button
3. Popup shows up, now click on "Import" button and select the existing folder where the game files are located
4. Game tile reverts status back to uninstalled with no indication of what went wrong.

### Expected behavior

The game should Import successfully and be ready to play.

### Heroic Version

Latest Stable (Flatpak)

### System Information

CPU: 4x Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
Memory: 16.75 GB (used: 9.66 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GP104 [GeForce GTX 1070 Ti]
    IDs: D=1b82 V=10de SD=8623 SV=1043
    Driver: nvidia
OS: Pop!_OS 22.04 LTS (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.15.2 Emeth
  Legendary: 0.20.36 Urban Flight (Heroic)
  gogdl: 1.1.2
  comet: comet 0.1.2

  Nile: 1.1.2 Will A. Zeppeli

**Comment by Bob837217** [comment]
I debugged the issue in Nile 1.1.2 and reported on it here: https://github.com/imLinguin/nile/issues/60
This is also resolved with a quick test of the main branch.
There needs to be a new release of nile incorporated into a build of Heroic.
