### ISSUE TITLE
Heroic-Game-Launcher not launching on Fedora 40

### ISSUE THREAD

**Issue by Skiski** [Heroic-Games-Launcher/HeroicGamesLauncher#4071]
### Describe the bug

I've installed Heroic-Game-Launcher from Flatpak and from rpm, and in both cases, nothing happens. In both cases, if I launch `heroic` from a terminal, I get:
```
$ heroic 
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: The "path" argument must be of type string. Received undefined
    at Object.join (node:path:1175:7)
    at Module.<anonymous> (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/main/main.js:182:5800)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at Function.c._load (node:electron/js2c/node_init:2:17025)
    at node:electron/js2c/browser_init:2:126921
    at node:electron/js2c/browser_init:2:127130
    at node:electron/js2c/browser_init:2:127134
src/gbm_drv_common.c:131: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:131: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:131: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:131: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:131: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000
```
This is the message from the rpm version (`heroic-games-launcher-bin-2.15.2-1.fc40.x86_64`). It's the same from the flatpak version.

I have to kill it after that. I haven't found any log file.

Except for the messages, there is nothing shown or appearing. I've never used Heroic-Game-Launcher, so I don't know what to expect.

### Add logs

```text
No log found
```

### Steps to reproduce

1. Install Heroic-Game-Launcher from flatpak or from rpm on Fedora 40
2. Launch heroic from a terminal to see the messages

### Expected behavior

I assume it should work or show something.

### Heroic Version

Latest Stable

### System Information

- OS: Fedora 40 64bit
- Kernel: 6.11.3-200.fc40.x86_64
- CPU: AMD Ryzen 5 3600
- GPU: GeForce RTX 3070 Ti

**Comment by arielj** [comment]
Closing, this should work fine in the latest Heroic 2.20.0, we could reopen if not.

**Comment by Skiski** [comment]
Hi,

I've just tried 2.20.0 Appimage and it's the same:
```
$ ./Heroic-2.20.0-linux-x86_64.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: The "path" argument must be of type string. Received undefined
    at Object.join (node:path:1354:7)
    at Module.<anonymous> (/tmp/.mount_Heroic8i4Rya/resources/app.asar/build/main/main.js:7:6881)
    at Module._compile (node:internal/modules/cjs/loader:1714:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1848:10)
    at Module.load (node:internal/modules/cjs/loader:1448:32)
    at Module._load (node:internal/modules/cjs/loader:1270:12)
    at Module.c._load (node:electron/js2c/node_init:2:17993)
    at node:electron/js2c/browser_init:2:135786
    at node:electron/js2c/browser_init:2:135995
    at node:electron/js2c/browser_init:2:135999
[173105:0222/195527.655765:ERROR:media/gpu/vaapi/vaapi_wrapper.cc:1631] vaInitialize failed: unknown libva error
```
I should try with a fresh user profile to see if it's because I've messed up with something in my .bashrc or another config file.

I've tried deleting the `heroic` dir in `.config`, but it does not change anything.

I'm on Fedora 42 by the way. Heroic was one of the first app I tried after upgrading. But it still does not work.

**Comment by arielj** [comment]
do you have the `$HOME` environment variable set in your system?

I traced the error and it comes from this line https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/src/backend/constants/paths.ts#L32 `userHome` is undefined and we get it from Node's `homedir` method of the `os` module that uses `$HOME` for this https://nodejs.org/api/os.html#oshomedir

or maybe you have a `SNAP` environment variable?

do you see any of those if you run `printenv`?

**Comment by Skiski** [comment]
I have both variables set:
```
$ echo $HOME
/home/fedoski
$ echo $SNAP
/snap
```

**Comment by arielj** [comment]
ok, I think I see what's happening, that `$SNAP` env variable is taking precedence over the `homedir()` call

you do NOT have `$SNAP_REAL_HOME`, right?

**Comment by arielj** [comment]
try running heroic from a terminal with `SNAP="" ./Heroic-2.20.0-linux-x86_64.AppImage `

**Comment by arielj** [comment]
I don't really know why you have that env variable though, in general it shouldn't be global, not even ubuntu has that global by default, it should be passed only for snap apps and it's done automatically by the snap runner https://snapcraft.io/docs/reference/development/environment-variables/#heading--snap

(just to be clear, I don't know if you can simply remove it from your system, I don't know why it was added)

**Comment by Skiski** [comment]
That's it. That was the `SNAP` variable. Awesome. It's in my `.bashrc`. I think I've put it there for some obscure reason and I don't think I need it.

Thank you very much for looking.
