### ISSUE TITLE
Download for #DRIVE Rally stucks at 8.35% [189.56MB]

### ISSUE THREAD

**Issue by Alexander88207** [Heroic-Games-Launcher/HeroicGamesLauncher#4075]
### Describe the bug

Hello,

when i try download the game "#DRIVE Rally" the game download stucks at 8.35% [189.56MB] everytime.

As a workaround i do import the game using the standalone gog installer.

### Add logs

```text
[PROGRESS] INFO: = Progress: 0.00 0/3394202874, Running for: 00:00:00, ETA: 00:00:00

[PROGRESS] INFO: = Downloaded: 0.00 MiB, Written: 0.00 MiB

[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 0.02 670720/3394202874, Running for: 00:00:01, ETA: 01:57:39

[PROGRESS] INFO: = Downloaded: 3.48 MiB, Written: 0.64 MiB

[PROGRESS] INFO:  + Download	- 0.10 MiB/s (raw) / 0.51 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 1.30 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 0.68 23059968/3394202874, Running for: 00:00:02, ETA: 00:06:27

[PROGRESS] INFO: = Downloaded: 11.92 MiB, Written: 21.99 MiB

[PROGRESS] INFO:  + Download	- 6.27 MiB/s (raw) / 17.71 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 17.32 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.27 43175008/3394202874, Running for: 00:00:04, ETA: 00:05:59

[PROGRESS] INFO: = Downloaded: 16.37 MiB, Written: 41.17 MiB

[PROGRESS] INFO:  + Download	- 4.08 MiB/s (raw) / 10.71 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 9.20 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.27 43175008/3394202874, Running for: 00:00:05, ETA: 00:07:16

[PROGRESS] INFO: = Downloaded: 20.92 MiB, Written: 41.17 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 1.85 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.27 43175008/3394202874, Running for: 00:00:06, ETA: 00:08:34

[PROGRESS] INFO: = Downloaded: 20.92 MiB, Written: 41.17 MiB

[PROGRESS] INFO:  + Download	- 0.32 MiB/s (raw) / 1.12 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.41 47896911/3394202874, Running for: 00:00:08, ETA: 00:09:19

[PROGRESS] INFO: = Downloaded: 28.32 MiB, Written: 45.68 MiB

[PROGRESS] INFO:  + Download	- 1.13 MiB/s (raw) / 3.97 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 4.01 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.82 61819191/3394202874, Running for: 00:00:09, ETA: 00:08:05

[PROGRESS] INFO: = Downloaded: 28.32 MiB, Written: 58.96 MiB

[PROGRESS] INFO:  + Download	- 4.42 MiB/s (raw) / 9.91 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 12.21 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.82 61819191/3394202874, Running for: 00:00:10, ETA: 00:08:59

[PROGRESS] INFO: = Downloaded: 35.75 MiB, Written: 58.96 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 1.12 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.82 61819191/3394202874, Running for: 00:00:11, ETA: 00:09:53

[PROGRESS] INFO: = Downloaded: 45.05 MiB, Written: 58.96 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 1.92 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.82 61819191/3394202874, Running for: 00:00:12, ETA: 00:10:47

[PROGRESS] INFO: = Downloaded: 49.01 MiB, Written: 58.96 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.58 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.82 61819191/3394202874, Running for: 00:00:13, ETA: 00:11:41

[PROGRESS] INFO: = Downloaded: 49.01 MiB, Written: 58.96 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 1.04 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.82 61819191/3394202874, Running for: 00:00:14, ETA: 00:12:35

[PROGRESS] INFO: = Downloaded: 49.01 MiB, Written: 58.96 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.58 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.82 61819191/3394202874, Running for: 00:00:15, ETA: 00:13:29

[PROGRESS] INFO: = Downloaded: 55.32 MiB, Written: 58.96 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 1.59 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.82 61819191/3394202874, Running for: 00:00:16, ETA: 00:14:23

[PROGRESS] INFO: = Downloaded: 71.44 MiB, Written: 58.96 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 1.05 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.82 61819191/3394202874, Running for: 00:00:17, ETA: 00:15:17

[PROGRESS] INFO: = Downloaded: 91.90 MiB, Written: 58.96 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.58 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.82 61819191/3394202874, Running for: 00:00:18, ETA: 00:16:11

[PROGRESS] INFO: = Downloaded: 91.91 MiB, Written: 58.96 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.59 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.82 61819191/3394202874, Running for: 00:00:19, ETA: 00:17:04

[PROGRESS] INFO: = Downloaded: 91.91 MiB, Written: 58.96 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.60 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.82 61819191/3394202874, Running for: 00:00:20, ETA: 00:17:58

[PROGRESS] INFO: = Downloaded: 99.58 MiB, Written: 58.96 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 1.38 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.82 61819191/3394202874, Running for: 00:00:21, ETA: 00:18:52

[PROGRESS] INFO: = Downloaded: 103.93 MiB, Written: 58.96 MiB

[PROGRESS] INFO:  + Download	- 0.05 MiB/s (raw) / 0.21 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 1.82 61819191/3394202874, Running for: 00:00:22, ETA: 00:19:46

[PROGRESS] INFO: = Downloaded: 119.32 MiB, Written: 58.96 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.60 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 6.75 229136588/3394202874, Running for: 00:00:23, ETA: 00:05:29

[PROGRESS] INFO: = Downloaded: 143.87 MiB, Written: 218.52 MiB

[PROGRESS] INFO:  + Download	- 50.19 MiB/s (raw) / 62.50 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 95.17 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 6.75 229136588/3394202874, Running for: 00:00:24, ETA: 00:05:43

[PROGRESS] INFO: = Downloaded: 147.53 MiB, Written: 218.52 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.60 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 7.01 238083289/3394202874, Running for: 00:00:25, ETA: 00:05:44

[PROGRESS] INFO: = Downloaded: 158.16 MiB, Written: 227.05 MiB

[PROGRESS] INFO:  + Download	- 4.19 MiB/s (raw) / 4.96 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 7.65 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 7.01 238083289/3394202874, Running for: 00:00:26, ETA: 00:05:57

[PROGRESS] INFO: = Downloaded: 162.06 MiB, Written: 227.05 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.55 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 7.01 238083289/3394202874, Running for: 00:00:27, ETA: 00:06:10

[PROGRESS] INFO: = Downloaded: 168.61 MiB, Written: 227.05 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.66 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283257355/3394202874, Running for: 00:00:28, ETA: 00:05:18

[PROGRESS] INFO: = Downloaded: 189.44 MiB, Written: 270.14 MiB

[PROGRESS] INFO:  + Download	- 22.23 MiB/s (raw) / 28.86 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 43.09 MiB/s (write) / 0.00 MiB/s (read)

Exception in thread Thread-3:

Traceback (most recent call last):

  File "threading.py", line 980, in _bootstrap_inner

  File "threading.py", line 917, in run

  File "gogdl\dl\managers\task_executor.py", line 772, in process_writer_task_results

  File "encodings\cp1252.py", line 19, in encode

UnicodeEncodeError: 'charmap' codec can't encode characters in position 123-129: character maps to <undefined>

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:30, ETA: 00:05:29

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 15.61 MiB/s (raw) / 19.06 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.65 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:31, ETA: 00:05:40

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:32, ETA: 00:05:51

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.44 MiB/s (raw) / 0.56 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:33, ETA: 00:06:02

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.68 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:34, ETA: 00:06:13

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.50 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:35, ETA: 00:06:24

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:36, ETA: 00:06:35

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:37, ETA: 00:06:46

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:38, ETA: 00:06:57

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.56 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:39, ETA: 00:07:08

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.57 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:40, ETA: 00:07:19

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.64 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:41, ETA: 00:07:30

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.50 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:42, ETA: 00:07:41

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.50 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:43, ETA: 00:07:52

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:45, ETA: 00:08:14

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:46, ETA: 00:08:25

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:47, ETA: 00:08:36

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.19 MiB/s (raw) / 0.22 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:48, ETA: 00:08:47

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.02 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:49, ETA: 00:08:58

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:50, ETA: 00:09:09

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:51, ETA: 00:09:20

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.50 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:52, ETA: 00:09:31

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.50 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:53, ETA: 00:09:42

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:54, ETA: 00:09:53

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:55, ETA: 00:10:04

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:56, ETA: 00:10:15

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:57, ETA: 00:10:26

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:58, ETA: 00:10:37

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.55 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:00:59, ETA: 00:10:48

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:01:00, ETA: 00:10:59

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.50 MiB/s (raw) / 0.50 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:01:01, ETA: 00:11:10

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB

[PROGRESS] INFO:  + Download	- 0.01 MiB/s (raw) / 0.01 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

[PROGRESS] INFO: = Progress: 8.35 283298033/3394202874, Running for: 00:01:02, ETA: 00:11:21

[PROGRESS] INFO: = Downloaded: 189.56 MiB, Written: 270.17 MiB
```

### Steps to reproduce

1. Run Heroic Games in Wine
2. Start download of #DRIVE Rallty [GOG]

### Expected behavior

The game downloads and installs as other games normally do.

### Screenshots

![image](https://github.com/user-attachments/assets/6522d5bc-ef4c-4516-b113-0bd74e3c6832)

### Heroic Version

Latest Stable

### System Information

I do use FreeBSD so i do run it through Wine.

I dont have an native Windows or Linux machine.

If this makes this bug report invalid then i do apologize deeply for the noise.

**Comment by maste9** [comment]
I would suspect that to be the same bug as https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3695 which seems to be agnostic to OS.

So despite BSD not officially supported you would probably profit if that annoying bug would be fixed at any time 🙂 

Btw. there are reports that sometimes it might help to stop and remove the blocked download, stop any gogdl jobs in the background (`sudo killall gogdl`) and then let Heroic repair that game. 
That didn't work out for my games lately but at least I could play the games in old version after being repaired 🤷

**Comment by arielj** [comment]
This looks like it should be in the gogdl tracker https://github.com/Heroic-Games-Launcher/heroic-gogdl
