### ISSUE TITLE
Unable to view new GoG games, logged in and can view store

### ISSUE THREAD

**Issue by ReverendRetro** [Heroic-Games-Launcher/HeroicGamesLauncher#4095]
### Describe the bug

I go to my Library and I am unable to see new purchases, however the Store works, and Manage Accounts shows me logged into GoG

### Add logs

```text
(20:29:27) INFO:    [Frontend]:         Refreshing undefined Library
(20:29:27) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(20:29:27) INFO:    [Legendary]:        Refreshing library...
(20:29:27) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/tyler/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/tyler/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(20:29:27) INFO:    [Backend]:          Frontend Ready
(20:29:27) INFO:    [Gog]:              Getting GOG library
(20:29:27) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/tyler/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/tyler/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(20:29:27) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 7 2700 Eight-Core Processor
Memory: 33.56 GB (used: 14.74 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M]
    IDs: D=73ff V=1002 SD=e447 SV=1da2
    Driver: amdgpu
OS: openSUSE Tumbleweed 6.11.5-1-vanilla (linux)
The current system is not a Steam Deck
We are running inside a Flatpak container
Software Versions:
  Heroic: 2.15.2 Emeth
  Legendary: 0.20.36 Urban Flight (Heroic)
  gogdl: 1.1.2
  comet: comet 0.1.2
  Nile: 1.1.2 Will A. Zeppeli
(20:29:27) INFO:    [Gog]:              GOG presence set
(20:29:27) INFO:    [Gog]:              Saved games data
(20:29:27) INFO:    [Backend]:          Checking for current version changelog
(20:29:27) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(20:29:27) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/tyler/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/tyler/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(20:29:28) INFO:    [Gog]:              Found 0 game(s) to update
(20:29:29) INFO:    [Winetricks]:       Downloading Winetricks
(20:29:29) ERROR:   [Gog]:              Error getting login information Error: Request failed with status code 503
    at createError (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/bin/heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
(20:29:31) INFO:    [WineDownloader]:   Updating wine versions info
(20:29:31) INFO:    [WineDownloader]:   Fetching upstream information...
(20:29:32) INFO:    [Backend]:          Starting the Download Queue
(20:29:32) INFO:    [WineDownloader]:   wine versions updated
```

### Steps to reproduce

1. Launch Heroic
2. Go to Library if logged in (Login if not logged in)
3. New games aren't showing

### Expected behavior

See newly purchased games and download them.

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS OpenSUSE Tumbleweed
- Latest Flatpak
- System fully up to date

**Comment by Loceka** [comment]
Same here,

I just redeemed a free GOG game (Diggles: The Myth of Fenris) and it doesn't show up in my Library, even after closing and reopening Heroic Game Launcher (v 2.15.2 from flatpak).

**Comment by arielj** [comment]
Is this still an issue?

**Comment by RavenX8** [comment]
I have the same issue. I just bought a few GOG games and the launcher will not refresh my library. I have repeatedly exited the launcher. I am not running the flatpak version (v2.15.2)

**Comment by ricketyboo** [comment]
Same issue on Steam Deck running 2.18.1
I had 55 games
Bought 3
They are visible in the store account but not Heroic Library.
I tried logging out, clearing cache and resetting heroic.
Library showed 0.
Logged in, it auto checked and eventually repopulatd, resulted to 55 again. The 3 new games still missing


Looking at the gog logs where it fetches the updated game list, it's getting the old games. The new ones are not in the output 

I tried changing network and playing with system time in case there was some sort of cache at network level or based on last fetch time but no luck.

Will check again in a few hours as it seems likely some sort of caching mechanism in place given previous people seem to have eventually had games trickle in

---
Update 
An hour or so after purchase they still didn't show up. Trying again this morning about 11hours after purchase they have showed up.

Random thought, is there some sort of UTC vs local timezone factor? I'm +10.
