### ISSUE TITLE
Error popup logging into Epic

### ISSUE THREAD

**Issue by mxdpeep** [Heroic-Games-Launcher/HeroicGamesLauncher#4099]
### Describe the bug

An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[Core] WARNING: Resuming failed for unknown reason: ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'account-public-service-prod03.ol.epicgames.com\', port=443): Max retries exceeded with url: /account/api/oauth/verify (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7bb6b3115430>: Failed to resolve \'account-public-service-prod03.ol.epicgames.com\' ([Errno -3] Temporary failure in name resolution)"))'))
[Core] INFO: Falling back to using refresh token...[Core] INFO: Logging in...Traceback (most recent call last):
File "urllib3/connectionpool.py", line 466, in _make_requestFile "urllib3/connectionpool.py", line 1095, in _validate_conn
File "urllib3/connection.py", line 730, in connect
File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socketFile "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
File "ssl.py", line 501, in wrap_socket
File "ssl.py", line 1074, in _create
File "ssl.py", line 1343, in do_handshakesocket.timeout: _ssl.c:1116: The handshake operation timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "requests/adapters.py", line 667, in send
File "urllib3/connectionpool.py", line 843, in urlopenFile "urllib3/util/retry.py", line 474, in increment
File "urllib3/util/util.py", line 39, in reraise
File "urllib3/connectionpool.py", line 789, in urlopenFile "urllib3/connectionpool.py", line 490, in _make_request
File "urllib3/connectionpool.py", line 468, in _make_requestFile "urllib3/connectionpool.py", line 369, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='account-public-service-prod03.ol.epicgames.com', port=443): Read timed out. (read timeout=10)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):File "legendary/cli.py", line 3224, in <module>
File "legendary/cli.py", line 3133, in main
File "legendary/cli.py", line 192, in list_games
File "legendary/core.py", line 256, in loginFile "legendary/core.py", line 241, in _loginFile "legendary/api/egs.py", line 117, in start_session
File "requests/sessions.py", line 637, in postFile "requests/sessions.py", line 589, in requestFile "requests/sessions.py", line 703, in send
File "requests/adapters.py", line 713, in sendrequests.exceptions.ReadTimeout: HTTPSConnectionPool(host='account-public-service-prod03.ol.epicgames.com', port=443): Read timed out. (read timeout=10)[PYI-82564:ERROR] Failed to execute script 'cli' due to unhandled exception!

### Add logs

```text
(07:57:45) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary

(07:57:45) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl

(07:57:45) INFO:    [Connection]:       Connectivity: check-online

(07:57:45) INFO:    [Connection]:       Pinging external endpoints

(07:57:45) INFO:    [Gog]:              Checking for existing gog manifests

(07:57:46) WARNING: [Backend]:          Protocol already registered.

(07:57:46) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/mxdpeep/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version

(07:57:46) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/mxdpeep/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/mxdpeep/.config/heroic/gog_store/auth.json --version

(07:57:46) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/mxdpeep/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version

(07:57:46) INFO:    [Connection]:       Connectivity: online

(07:57:46) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present

(07:57:46) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/mxdpeep/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/mxdpeep/.config/heroic/gog_store/auth.json auth

(07:57:46) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded

(07:57:46) INFO:    [Backend]:          

System Information:

CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

Memory: 16.71 GB (used: 1.63 GB)

GPUs:

  GPU 0:

    Name: NVIDIA Corporation GP106 [GeForce GTX 1060 3GB]

    IDs: D=1c02 V=10de SD=2438 SV=174b

    Driver: nvidia

OS: Ubuntu 22.04.5 LTS (Jammy Jellyfish) (linux)

The current system is not a Steam Deck

We are not running inside a Flatpak container

Software Versions:

  Heroic: 2.15.2 Emeth

  Legendary: 0.20.36 Urban Flight (Heroic)

  gogdl: 1.1.2

  comet: comet 0.1.2

  Nile: 1.1.2 Will A. Zeppeli

(07:57:47) INFO:    [Frontend]:         Refreshing undefined Library

(07:57:47) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(07:57:47) INFO:    [Legendary]:        Refreshing library...

(07:57:47) INFO:    [Legendary]:        Refreshing Epic Games...

(07:57:47) INFO:    [Backend]:          Frontend Ready

(07:57:47) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/mxdpeep/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party

(07:57:48) INFO:    [Winetricks]:       Downloading Winetricks

(07:57:51) INFO:    [WineDownloader]:   Updating wine versions info

(07:57:51) INFO:    [WineDownloader]:   Fetching upstream information...

(07:57:51) INFO:    [Legendary]:        Game list updated, got 246 games & DLCs

(07:57:51) INFO:    [WineDownloader]:   wine versions updated

(07:57:51) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(07:57:52) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/mxdpeep/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party

(07:57:52) INFO:    [Backend]:          Starting the Download Queue

(07:57:53) INFO:    [Legendary]:        Found 0 games to update

(07:58:08) INFO:    [Backend]:          Writing config for cDNErLkWaF5i5Pj2Cr6pQH

(07:58:08) INFO:    [Backend]:          Changed config: winePrefix from /home/mxdpeep/.wine to /home/mxdpeep/Games/Heroic/Prefixes/Dave the Diver

(07:58:08) WARNING: [Backend]:          Required prefix files are missing, running `verifyWinePrefix` to create prefix

(07:58:08) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-latest

(07:58:08) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-latest

(07:58:08) DEBUG:   [Backend]:          Running Wine command: run wineboot --init

(07:58:13) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-latest

(07:58:13) DEBUG:   [Backend]:          Running Wine command: runinprefix /home/mxdpeep/1TB/DS3/dave the diver/setup.exe

(08:33:23) INFO:    [Backend]:          Adding shortcuts for Dave the Diver

(08:33:23) INFO:    [Backend]:          Shortcut saved on /home/mxdpeep/Desktop/Dave the Diver.desktop

(08:33:23) INFO:    [Backend]:          Writing config for cDNErLkWaF5i5Pj2Cr6pQH

(08:33:23) INFO:    [Backend]:          Changed config: wineCrossoverBottle from undefined to 

(08:33:23) INFO:    [Frontend]:         Refreshing sideload Library

(08:33:23) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(08:33:24) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(08:33:24) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/mxdpeep/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party

(08:33:26) INFO:    [DownloadManager]:  Downloader: Finished downloading https://cdn2.steamgriddb.com/file/sgdb-cdn/grid/eb33b351770666081fdc91005f536f9f.png

(08:33:26) INFO:    [Legendary]:        Found 0 games to update

(08:49:54) INFO:    [Backend]:          Writing config for x2SuYUMeSM49zQP3U2838Q

(08:49:54) INFO:    [Backend]:          Changed config: winePrefix from /home/mxdpeep/.wine to /home/mxdpeep/Games/Heroic/Prefixes/Dredge

(08:49:54) WARNING: [Backend]:          Required prefix files are missing, running `verifyWinePrefix` to create prefix

(08:49:54) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-latest

(08:49:54) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-latest

(08:49:54) DEBUG:   [Backend]:          Running Wine command: run wineboot --init

(08:49:58) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-latest

(08:49:58) DEBUG:   [Backend]:          Running Wine command: runinprefix /home/mxdpeep/1TB/DS3/dredge/setup.exe

(09:26:35) INFO:    [Backend]:          Adding shortcuts for Dredge

(09:26:35) INFO:    [Backend]:          Shortcut saved on /home/mxdpeep/Desktop/Dredge.desktop

(09:26:35) INFO:    [Backend]:          Writing config for x2SuYUMeSM49zQP3U2838Q

(09:26:35) INFO:    [Backend]:          Changed config: wineCrossoverBottle from undefined to 

(09:26:35) INFO:    [Frontend]:         Refreshing sideload Library

(09:26:35) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(09:26:35) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(09:26:45) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://cdn2.steamgriddb.com/file/sgdb-cdn/grid/8acfa9f115e0586c27db3edc6857942c.png. 

Error: Error: timeout of 10000ms exceeded

(09:26:45) ERROR:   [Backend]:          Failed to get epic service status with Error: timeout of 10000ms exceeded

    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)

    at RedirectableRequest.handleRequestTimeout (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)

    at RedirectableRequest.emit (node:events:519:28)

    at Timeout.<anonymous> (/opt/Heroic/resources/app.asar/node_modules/follow-redirects/index.js:210:12)

    at listOnTimeout (node:internal/timers:573:17)

    at processTimers (node:internal/timers:514:7)

(09:26:45) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/mxdpeep/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party

(09:28:03) INFO:    [Legendary]:        Found 0 games to update

(09:33:09) INFO:    [Frontend]:         Refreshing undefined Library

(09:33:09) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(09:33:09) INFO:    [Legendary]:        Refreshing library...

(09:33:09) INFO:    [Legendary]:        Refreshing Epic Games...

(09:33:19) ERROR:   [Backend]:          Failed to get epic service status with Error: timeout of 10000ms exceeded

    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)

    at RedirectableRequest.handleRequestTimeout (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)

    at RedirectableRequest.emit (node:events:519:28)

    at Timeout.<anonymous> (/opt/Heroic/resources/app.asar/node_modules/follow-redirects/index.js:210:12)

    at listOnTimeout (node:internal/timers:573:17)

    at processTimers (node:internal/timers:514:7)

(09:33:19) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/mxdpeep/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party

(09:33:40) INFO:    [Legendary]:        Logging out: LEGENDARY_CONFIG_PATH=/home/mxdpeep/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary auth --delete

(09:33:42) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/mxdpeep/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary cleanup

(09:34:11) INFO:    [Legendary]:        Game list updated, got 246 games & DLCs

(09:34:27) INFO:    [Frontend]:         Called Epic Login

(09:34:27) INFO:    [Legendary]:        Logging in: LEGENDARY_CONFIG_PATH=/home/mxdpeep/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary auth --code <redacted>

(09:34:58) INFO:    [Frontend]:         Refreshing legendary Library

(09:34:58) INFO:    [Legendary]:        Refreshing library...

(09:34:58) INFO:    [Legendary]:        Refreshing Epic Games...

(09:35:08) ERROR:   [Backend]:          Failed to get epic service status with Error: timeout of 10000ms exceeded

    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)

    at RedirectableRequest.handleRequestTimeout (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)

    at RedirectableRequest.emit (node:events:519:28)

    at Timeout.<anonymous> (/opt/Heroic/resources/app.asar/node_modules/follow-redirects/index.js:210:12)

    at listOnTimeout (node:internal/timers:573:17)

    at processTimers (node:internal/timers:514:7)

(09:35:08) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/mxdpeep/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party

(09:36:12) INFO:    [Legendary]:        Game list updated, got 246 games & DLCs

(09:36:12) INFO:    [Frontend]:         No cache found, getting data from legendary...

(09:36:12) INFO:    [Legendary]:        Refreshing library...

(09:36:12) INFO:    [Legendary]:        Refreshing Epic Games...

(09:36:22) ERROR:   [Backend]:          Failed to get epic service status with Error: timeout of 10000ms exceeded

    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)

    at RedirectableRequest.handleRequestTimeout (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:369:16)

    at RedirectableRequest.emit (node:events:519:28)

    at Timeout.<anonymous> (/opt/Heroic/resources/app.asar/node_modules/follow-redirects/index.js:210:12)

    at listOnTimeout (node:internal/timers:573:17)

    at processTimers (node:internal/timers:514:7)

(09:36:22) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/mxdpeep/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party

(09:37:44) INFO:    [Legendary]:        Game list updated, got 246 games & DLCs

(09:37:44) INFO:    [Frontend]:         Force Update
```

### Steps to reproduce

pops automatically

### Expected behavior

no popup / no Python errors

### Heroic Version

Latest Stable

### System Information

Ubuntu 22.04.5

**Comment by arielj** [comment]
seems like connectivity problems

can you try using legendary directly and see if it can connect? https://github.com/derrod/legendary this is what we use internally to connect to epic stuff

**Comment by Ayanashi** [comment]
Same issue here and cannot login via legendary too..i have urlib3 already installed (heroic launcher 2.15.2 on ArchLinux 6.11.7)

**Comment by sigmavirus24** [comment]
Came here from the urllib3 bug. These aren't the same issue. 

The OP here is having issues resolving the DNS for the Epic host in their stack trace. The other issue here is that DNS has been resolved but your operating system can't figure out how to route traffic to that address. It may be any number of problems but it's an issue with your environment (ISP, computer, home network, etc) not with the software, thus it's not easy for anyone to help you debug this. 

As for the DNS resolution error, it's likely a different environmental issue (DNS configuration, DNS server error, etc.)

Neither of these are bugs in the software aside from this software likely wanting to retry the DNS error and make the unreachable network error clearer

**Comment by nolddor** [comment]
Same issue here, all websites works well but cannot reach `api.legendary.gl` because it uses IPv6
@Ayanashi in my case problem was at my router, same PC connected to my mobile data worked but not while on WiFi.
