### ISSUE TITLE
MangoHud config not being detected with Flatpak Heroic 2.15.2 update, possibly misconfigured filesystem permission

### ISSUE THREAD

**Issue by CosmicHeron** [Heroic-Games-Launcher/HeroicGamesLauncher#4105]
### Describe the bug

With the latest 2.15.2 update the following filesystem permission was added to the Flatpak `~/.config/MangoHud:ro` which should pick up the user's local MangoHud config file, however when running games with MangoHud enabled in Heroic it appears to not read it and use the default settings as if the config file was not present.

The fix/workaround is to instead add the filesystem permission `xdg-config/MangoHud:ro`, which does make it possible for MangoHud to use the config file.

I'm not sure why `~/.config` fails but `xdg-config` works since they should both resolve to the same path but using the latter one fixes the problem.

### Add logs

```text
(10:56:32) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary
(10:56:32) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl
(10:56:32) INFO:    [Connection]:       Connectivity: check-online
(10:56:32) INFO:    [Connection]:       Pinging external endpoints
(10:56:32) INFO:    [Gog]:              Checking for existing gog manifests
(10:56:32) INFO:    [Nile]:             Refreshing library...
(10:56:32) INFO:    [Nile]:             Refreshing Amazon Games...
(10:56:32) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
(10:56:32) INFO:    [Nile]:             Game list updated, got 316 games
(10:56:32) WARNING: [Backend]:          Failed to register protocol with OS.
(10:56:32) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version
(10:56:32) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(10:56:32) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
(10:56:32) INFO:    [Connection]:       Connectivity: online
(10:56:32) INFO:    [Gog]:              Checking if login is valid
(10:56:32) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:56:32) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:56:32) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:56:32) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(10:56:32) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 7 5800X3D 8-Core Processor
Memory: 33.58 GB (used: 6.26 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] NITRO+ RX 7900 XTX Vapor-X
    IDs: D=744c V=1002 SD=e471 SV=1da2
    Driver: amdgpu
OS: Arch Linux 6.11.6-zen1-1-zen (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.15.2 Emeth
  Legendary: 0.20.36 Urban Flight (Heroic)
  gogdl: 1.1.2
  comet: comet 0.1.2

  Nile: 1.1.2 Will A. Zeppeli

(10:56:32) INFO:    [Nile]:             Saved user data to config file
(10:56:32) INFO:    [Frontend]:         Refreshing undefined Library
(10:56:32) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(10:56:32) INFO:    [Legendary]:        Refreshing library...
(10:56:32) INFO:    [Legendary]:        Refreshing Epic Games...
(10:56:32) INFO:    [Nile]:             Refreshing library...
(10:56:32) INFO:    [Nile]:             Refreshing Amazon Games...
(10:56:32) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile library sync
(10:56:32) INFO:    [Nile]:             Game list updated, got 316 games
(10:56:32) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:56:32) INFO:    [Gog]:              Getting GOG library
(10:56:32) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:56:32) INFO:    [Backend]:          Frontend Ready
(10:56:33) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party
(10:56:33) INFO:    [Gog]:              GOG presence set
(10:56:33) INFO:    [Backend]:          Checking for current version changelog
(10:56:33) INFO:    [Gog]:              Saved username to config file
(10:56:33) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:56:34) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:56:34) INFO:    [Legendary]:        Game list updated, got 57 games & DLCs
(10:56:34) INFO:    [Winetricks]:       Downloading Winetricks
(10:56:35) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:56:35) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:56:36) INFO:    [Gog]:              Saved games data
(10:56:36) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(10:56:36) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:56:37) INFO:    [WineDownloader]:   Updating wine versions info
(10:56:37) INFO:    [WineDownloader]:   Fetching upstream information...
(10:56:37) INFO:    [WineDownloader]:   wine versions updated
(10:56:37) INFO:    [Backend]:          Starting the Download Queue
(10:56:38) INFO:    [Gog]:              Found 0 game(s) to update
(10:56:38) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party
(10:56:39) WARNING: [Legendary]:        Failed to parse games from /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json'
    at Object.readFileSync (node:fs:448:20)
    at Object.t.readFileSync (node:electron/js2c/node_init:2:10245)
    at Module.Xa (/app/bin/heroic/resources/app.asar/build/main/main.js:114:3340)
    at /app/bin/heroic/resources/app.asar/build/main/main.js:184:2385
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537)
(10:56:39) INFO:    [Legendary]:        Found 0 games to update
(10:56:39) INFO:    [Nile]:             Looking for updates...
(10:56:39) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile list-updates --json
(10:57:26) INFO:    [Backend]:          Launching Tomb Raider I-III Remastered Starring Lara Croft (1407750955)
(10:57:26) INFO:    [Backend]:          Downloading saves for Tomb Raider I-III Remastered Starring Lara Croft
(10:57:26) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:57:26) INFO:    [Gog]:              Syncing saves for Tomb Raider I-III Remastered Starring Lara Croft
(10:57:26) INFO:    [Gog]:              Syncing saves for Tomb Raider I-III Remastered Starring Lara Croft: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json save-sync "/home/user/Games/Heroic/Prefixes/default/Tomb Raider I-III Remastered Starring Lara Croft/pfx/dosdevices/c:/users/steamuser/AppData/Roaming/TRX" 1407750955 --os windows --ts 1731315775.20818 --name saves --skip-upload
(10:57:26) INFO:    [Backend]:          Preventing machine to sleep
(10:57:33) INFO:    [Backend]:          Saves for Tomb Raider I-III Remastered Starring Lara Croft downloaded
(10:57:33) INFO:    [Backend]:          Preventing display from sleep
(10:57:33) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-latest
(10:57:33) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:57:33) INFO:    [Backend]:          Started Discord Rich Presence
(10:57:33) INFO:    [Backend]:          Preventing machine to sleep
(10:57:33) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-latest
(10:57:33) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-latest
(10:57:33) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-latest
(10:57:33) DEBUG:   [Backend]:          Running Wine command: createprefix
(10:57:33) INFO:    [Gog]:              GOG presence set
(10:57:40) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-latest
(10:57:40) DEBUG:   [Backend]:          Running Wine command: cmd /c winepath -u C:\ProgramData\GOG.com\Galaxy\redists\GalaxyCommunication.exe
(10:57:43) INFO:    [Gog]:              Launching Comet!
(10:57:43) INFO:    [Gog]:              Launching Tomb Raider I-III Remastered Starring Lara Croft: HEROIC_APP_NAME=1407750955 HEROIC_APP_RUNNER=gog GAMEID=umu-2478970 HEROIC_APP_SOURCE=gog STORE=gog STEAM_COMPAT_INSTALL_PATH="/home/user/Games/Heroic/Tomb Raider I-III Remastered" LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/.steam/steam WINEPREFIX="/home/user/Games/Heroic/Prefixes/default/Tomb Raider I-III Remastered Starring Lara Croft" STEAM_COMPAT_DATA_PATH="/home/user/Games/Heroic/Prefixes/default/Tomb Raider I-III Remastered Starring Lara Croft" PROTONPATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/proton/Proton-GE-latest WINE_FULLSCREEN_FSR=0 PROTON_DISABLE_NVAPI=1 PROTON_EAC_RUNTIME=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/eac_runtime PROTON_BATTLEYE_RUNTIME=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/battleye_runtime STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId="heroic-Tomb Raider I-III Remastered" PROTON_LOG_DIR=/home/user/.var/app/com.heroicgameslauncher.hgl GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json launch "/home/user/Games/Heroic/Tomb Raider I-III Remastered" 1407750955 --no-wine --wrapper "/usr/lib/extensions/vulkan/MangoHud/bin/mangohud --dlsym /app/bin/gamemoderun "/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/umu/umu_run.py"" --platform windows
(10:57:43) INFO:    [Backend]:          Preventing display to sleep
(10:57:58) INFO:    [Gog]:              Killing Comet!
(10:57:58) INFO:    [Backend]:          Stopped Discord Rich Presence
(10:57:58) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:57:59) INFO:    [Gog]:              GOG presence set
(10:57:59) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(10:57:59) INFO:    [Backend]:          Uploading saves for Tomb Raider I-III Remastered Starring Lara Croft
(10:57:59) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:57:59) INFO:    [Frontend]:         Refreshing gog Library
(10:57:59) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:57:59) INFO:    [Backend]:          Stopping Power Saver Blocker
(10:57:59) INFO:    [Backend]:          Stopping Display Sleep Blocker
(10:57:59) INFO:    [Gog]:              Syncing saves for Tomb Raider I-III Remastered Starring Lara Croft
(10:57:59) INFO:    [Gog]:              Syncing saves for Tomb Raider I-III Remastered Starring Lara Croft: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json save-sync "/home/user/Games/Heroic/Prefixes/default/Tomb Raider I-III Remastered Starring Lara Croft/pfx/dosdevices/c:/users/steamuser/AppData/Roaming/TRX" 1407750955 --os windows --ts 1731322653.311041 --name saves --skip-download
(10:57:59) INFO:    [Gog]:              Getting GOG library
(10:57:59) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:58:00) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:58:00) INFO:    [Backend]:          Saves uploaded for Tomb Raider I-III Remastered Starring Lara Croft
(10:58:00) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:58:01) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:58:02) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:58:02) INFO:    [Gog]:              Saved games data
(10:59:24) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
```

### Steps to reproduce

1. Have Heroic 2.15.2 Flatpak installed with all permissions set to default, have an existing MangoHud config file at `~/.config/MangoHud/MangoHud.conf`, making sure it has some something changed to differentiate it from the default settings
2. Run a game with MangoHud enabled in Heroic, note it will use the default settings
3. Add `xdg-config/MangoHud:ro` to the Heroic filesystem permissions (using something like [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal))
4. Re-run the same game, note MangoHud is now able to use the config file

### Expected behavior

Flatpak filesystem permissions are configured so the config files can be read.

### Heroic Version

Latest Stable (Flatpak)

### System Information

ArchLinux

**Comment by regs01** [comment]
Runtime updated to 24.08. So you need to install MangoHud for 24.08
The one that is `runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/24.08`
```
# flatpak install mangohud
Looking for matches…
Similar refs found for ‘mangohud’ in remote ‘flathub’ (system):

   1) runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/24.08
   2) runtime/com.valvesoftware.Steam.Utility.MangoHud/x86_64/stable
   3) runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/21.08
   4) runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/22.08
   5) runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/23.08
   6) runtime/com.valvesoftware.Steam.VulkanLayer.MangoHud/x86_64/stable

Which do you want to use (0 to abort)? [0-6]: 1


        ID                                                        Branch             Op             Remote             Download
 1. [✓] org.freedesktop.Platform.VulkanLayer.MangoHud             24.08              i              flathub            11.6 MB / 11.9 MB
```


It really needs some simplification. Like automated check and offer to install proper version for MangoHud, Gamescope etc.

**Comment by Etaash-mathamsetty** [comment]
fixed here: <https://github.com/flathub/com.heroicgameslauncher.hgl/pull/167>

**Comment by Etaash-mathamsetty** [comment]
nvm flatpak doesn't let us do this, removing it entirely
