### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by Ayanashi** [Heroic-Games-Launcher/HeroicGamesLauncher#4130]
### Describe the bug

cannot login, python3.12 already installed and urlib3 too

### Add logs

```text
`❯ legendary auth
[cli] INFO: Testing existing login data if present...
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1061, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.12/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x79f33aaa44d0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.legendary.gl', port=443): Max retries exceeded with url: /v1/version.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79f33aaa44d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sbin/legendary", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/legendary/cli.py", line 3058, in main
    cli.auth(args)
  File "/usr/lib/python3.12/site-packages/legendary/cli.py", line 92, in auth
    self.core.check_for_updates(force=True)
  File "/usr/lib/python3.12/site-packages/legendary/core.py", line 272, in check_for_updates
    version_info = self.lgdapi.get_version_information()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/legendary/api/lgd.py", line 21, in get_version_information
    r = self.session.get(f'https://{self._api_host}/v1/version.json',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.legendary.gl', port=443): Max retries exceeded with url: /v1/version.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79f33aaa44d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))`
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Before heroic works optimal and load login page and login auth keys perfectly

### Screenshots

![captura-2024-11-18-1731951257](https://github.com/user-attachments/assets/15c4d8d2-4a2a-4bc1-81e2-db2d91b72d93)

### Heroic Version

Latest Stable

### System Information

**Archlinux 6.11.9**
**heroic 2.15.2** ### (aur)
**legendary 0.20.34** ### (aur)

### Additional information

Cannot login via legendary last version and heroic last stable version

**Comment by PadTrick** [comment]
Same issue for me with Epic. Gog works, but loggin into Epic account presents this error.
I can browse the store (and it shows that i'm logged in) but as soon that i enter my library this error pops up and it doesnt list any Epic games from my account.

**Comment by nolddor** [comment]
Same here, tried Heroic Games for the first time in Flatpak.

Login loop on Epic, cannot use the software...

**Comment by PadTrick** [comment]
Issue is still NOT FIXED
