### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'binascii' on macOS M1

### ISSUE THREAD

**Issue by Darknight92228** [Heroic-Games-Launcher/HeroicGamesLauncher#4155]
### Describe the bug

I’m encountering an issue with the Heroic Game Launcher on my MacBook Air (M1). When attempting to run the application, it fails with the following error:

### Add logs

```text
Legendary (Epic Games)

Error:
An error has occurred! Try to Logout and Login on your Epic account.

[cli] INFO: Cleanup complete! Removed 4.70 MiB.Traceback (most recent call last):
File "legendary/cli.py", line 22, in <module>
File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_moduleFile "legendary/core.py", line 7, in <module>
File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
File "base64.py", line 11, in <module>
ModuleNotFoundError: No module named 'binascii'

[PYI-25502:ERROR] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1.	Open Heroic Game Launcher on macOS 15.1 (24B83) on an M1 MacBook Air.
	2.	Log in to your Epic Games account through the launcher.
	3.	Perform any operation involving the Legendary CLI (e.g., attempting to clean cache or manage game installs).
	4.	Observe the error message popup with ModuleNotFoundError: No module named 'binascii'.

### Expected behavior

The Heroic Game Launcher should seamlessly integrate with Legendary CLI and allow users to log in and manage their Epic Games library without errors.

### Screenshots

![image](https://github.com/user-attachments/assets/8ad85148-68c1-4bc7-bdcd-86c28d00077f)

### Heroic Version

Latest Stable

### System Information

MacBook Air M1, 2020
Memory - 16 GB
macOS - 15.1.1 (24B91)

### Additional information

The application crashes or displays the error:
ModuleNotFoundError: No module named 'binascii'
[PYI-25502:ERROR] Failed to execute script 'cli' due to unhandled exception!

Additional Context:
	•	I’ve attempted logging out and back into the Epic Games account, but the issue persists.
	•	It appears the error originates from a missing Python module, binascii, which might not be properly bundled in the PyInstaller package used for Legendary.

Please let me know if you need more details or logs to diagnose this issue. Thank you!

**Comment by arielj** [comment]
I wonder if this is still happening with the latest Heroic 2.18, can you test again and report?

**Comment by arielj** [comment]
This still happens, but it's caused by legendary, not by heroic (we just print the error thrown by legendary).

So I'm closing it here since it's not something we can fix in heroic, it needs to be fixed by legendary.
