### ISSUE TITLE
Epic games do not run

### ISSUE THREAD

**Issue by gcala** [Heroic-Games-Launcher/HeroicGamesLauncher#4165]
### Describe the bug

Hi, today I installed two games from my Epic library and both fail to start (Path of Exile and Sunless Skies). I'm using HGM v. 2.15.2 from flathub and games are installed in a different partition '/Games/Heroic'. No issues with GOG games.

### Add logs

```text
Launching "Path of Exile" (legendary)
Native? No
Installed in: /Games/Heroic/PathOfExile

System Info:
CPU: 4x AMD A8-6500 APU with Radeon(tm) HD Graphics
Memory: 8.24 GB (used: 3.52 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation TU116 [GeForce GTX 1660 SUPER]
    IDs: D=21c4 V=10de SD=8752 SV=1043
    Driver: nvidia
OS: Arch Linux 6.12.1-arch1-1 (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.15.2 Emeth
  Legendary: 0.20.36 Urban Flight (Heroic)
  gogdl: 1.1.2
  comet: comet 0.1.2

  Nile: 1.1.2 Will A. Zeppeli

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallDxvkNvapi": false,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableMsync": false,
	"enableFsync": true,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"useGameMode": false,
	"battlEyeRuntime": true,
	"eacRuntime": true,
	"language": "",
	"beforeLaunchScriptPath": "",
	"afterLaunchScriptPath": "",
	"wineVersion": {
		"bin": "/home/gcala/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-26/bin/wine",
		"name": "Wine - Wine-GE-Proton8-26",
		"type": "wine",
		"lib": "/home/gcala/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-26/lib64",
		"lib32": "/home/gcala/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-26/lib",
		"wineserver": "/home/gcala/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-26/bin/wineserver"
	},
	"winePrefix": "/run/user/1000/doc/fd278851/Prefixes/Path of Exile",
	"wineCrossoverBottle": ""
}

Game launched at: Sun Dec 08 2024 11:08:55 GMT+0100 (Ora standard dell’Europa centrale)

An exception occurred when launching the game:
Error: EPERM: operation not permitted, mkdir '/run/user/1000/doc/fd278851/Prefixes/Path of Exile'
    at Object.mkdirSync (node:fs:1372:26)
    at nr (/app/bin/heroic/resources/app.asar/build/main/main.js:106:656)
    at En (/app/bin/heroic/resources/app.asar/build/main/main.js:104:908)
    at Module.Kd [as launch] (/app/bin/heroic/resources/app.asar/build/main/main.js:91:6895)
    at /app/bin/heroic/resources/app.asar/build/main/main.js:184:8140
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537)============= End of log =============
```

### Steps to reproduce

1. Install an Epic Store game
2. Click on Play Now

### Expected behavior

The game launches

### Heroic Version

Latest Stable (Flatpak)

### System Information

Operating System: Arch Linux 
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.0
Kernel Version: 6.12.1-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 4 × AMD A8-6500 APU with Radeon(tm) HD Graphics
Memory: 7.7 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2

**Comment by arielj** [comment]
Use the `#-support` area of our discord to get help running games. Github issues are for issues with heroic itself and your case seems to be a permissions problem
