### ISSUE TITLE
Cyberpunk Redmod: Enabling an emtpy list of mods prevents the game from running

### ISSUE THREAD

**Issue by MattSturgeon** [Heroic-Games-Launcher/HeroicGamesLauncher#4176]
### Describe the bug

On a fresh install of Cyberpunk 2077, with the Redmod DLC installed, the game is unable to start while "enable mods" is enabled but no mods are installed.

### Add logs

```text
(00:14:52) INFO:    [Legendary]:        Legendary location: /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/bin/x64/linux/legendary
(00:14:52) INFO:    [Gog]:              GOGDL location: /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/bin/x64/linux/gogdl
(00:14:52) INFO:    [Connection]:       Connectivity: check-online
(00:14:52) INFO:    [Connection]:       Pinging external endpoints
(00:14:52) DEBUG:   [Backend]:          Skipping playtime sync queue upload - playtime sync disabled
(00:14:52) INFO:    [Gog]:              Checking for existing gog manifests
(00:14:52) WARNING: [Backend]:          Failed to register protocol with OS.
(00:14:52) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/matt/.config/heroic/legendaryConfig/legendary /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/bin/x64/linux/legendary --version
(00:14:52) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/matt/.config/heroic/gogdlConfig /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/bin/x64/linux/gogdl --auth-config-path /home/matt/.config/heroic/gog_store/auth.json --version
(00:14:52) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/matt/.config/heroic/nile_config /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/bin/x64/linux/nile --version
(00:14:52) INFO:    [Connection]:       Connectivity: online
(00:14:52) INFO:    [Gog]:              Checking if login is valid
(00:14:52) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/matt/.config/heroic/gogdlConfig /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/bin/x64/linux/gogdl --auth-config-path /home/matt/.config/heroic/gog_store/auth.json auth
(00:14:52) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/matt/.config/heroic/gogdlConfig /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/bin/x64/linux/gogdl --auth-config-path /home/matt/.config/heroic/gog_store/auth.json auth
(00:14:52) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(00:14:53) INFO:    [Frontend]:         Refreshing undefined Library
(00:14:53) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(00:14:53) INFO:    [Legendary]:        Refreshing library...
(00:14:53) INFO:    [Legendary]:        Refreshing Epic Games...
(00:14:53) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/matt/.config/heroic/gogdlConfig /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/bin/x64/linux/gogdl --auth-config-path /home/matt/.config/heroic/gog_store/auth.json auth
(00:14:53) INFO:    [Backend]:          Frontend Ready
(00:14:53) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 7 3700X 8-Core Processor
Memory: 67.34 GB (used: 5.88 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900 GRE/7900M]
    IDs: D=744c V=1002 SD=undefined SV=undefined
    Driver: undefined
OS: NixOS 25.05 (Warbler) (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.15.2 Emeth
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.1.2
  comet: comet 0.2.0

  Nile: 1.1.2 Will A. Zeppeli

(00:14:53) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/matt/.config/heroic/legendaryConfig/legendary /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/bin/x64/linux/legendary list --third-party
(00:14:53) INFO:    [Backend]:          Checking for current version changelog
(00:14:53) INFO:    [Gog]:              Getting GOG library
(00:14:53) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/matt/.config/heroic/gogdlConfig /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/bin/x64/linux/gogdl --auth-config-path /home/matt/.config/heroic/gog_store/auth.json auth
(00:14:53) INFO:    [Gog]:              Saved username to config file
(00:14:53) INFO:    [Gog]:              Saved games data
(00:14:54) INFO:    [Legendary]:        Game list updated, got 9 games & DLCs
(00:14:54) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(00:14:54) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/matt/.config/heroic/gogdlConfig /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/bin/x64/linux/gogdl --auth-config-path /home/matt/.config/heroic/gog_store/auth.json auth
(00:14:54) WARNING: [Gog]:              Game 1491728574 has pinned version, update check skipped
(00:14:54) WARNING: [Gog]:              Game 1998527297 has pinned version, update check skipped
(00:14:54) WARNING: [Gog]:              Game 1423049311 has pinned version, update check skipped
(00:14:54) INFO:    [Gog]:              Found 0 game(s) to update
(00:14:54) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/matt/.config/heroic/legendaryConfig/legendary /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/bin/x64/linux/legendary list --third-party
(00:14:55) INFO:    [Winetricks]:       Downloading Winetricks
(00:14:55) WARNING: [Legendary]:        Failed to parse games from /home/matt/.config/heroic/legendaryConfig/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/home/matt/.config/heroic/legendaryConfig/legendary/installed.json'
    at Object.readFileSync (node:fs:448:20)
    at Object.t.readFileSync (node:electron/js2c/node_init:2:10175)
    at Module.Xa (/nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/main/main.js:114:3340)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/main/main.js:184:2385
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83724)
(00:14:55) INFO:    [Legendary]:        Found 0 games to update
(00:14:57) INFO:    [WineDownloader]:   Updating wine versions info
(00:14:57) INFO:    [WineDownloader]:   Fetching upstream information...
(00:14:58) INFO:    [Backend]:          Starting the Download Queue
(00:14:58) INFO:    [WineDownloader]:   wine versions updated
(00:15:23) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Cyberpunk 2077
(00:15:23) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Cyberpunk 2077
(00:15:23) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(00:15:23) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(00:15:26) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(00:15:30) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(00:15:30) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(00:15:30) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(00:15:32) INFO:    [Backend]:          Launching Cyberpunk 2077 (1423049311)
(00:15:32) INFO:    [Backend]:          Preventing display from sleep
(00:15:32) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-Proton9-21
(00:15:32) INFO:    [Backend]:          Preventing machine to sleep
(00:15:32) INFO:    [Backend]:          Started Discord Rich Presence
(00:15:32) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(00:15:32) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(00:15:32) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-Proton9-21
(00:15:32) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-Proton9-21
(00:15:32) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-Proton9-21
(00:15:32) DEBUG:   [Backend]:          Running Wine command: createprefix
(00:15:35) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-Proton9-21
(00:15:35) DEBUG:   [Backend]:          Running Wine command: cmd /c winepath -u C:\ProgramData\GOG.com\Galaxy\redists\GalaxyCommunication.exe
(00:15:39) ERROR:   [Backend]:          Failed to install GalaxyCommunication dummy into the prefix
(00:15:39) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-Proton9-21
(00:15:39) DEBUG:   [Backend]:          Running Wine command: cmd /c winepath -w /home/matt/Games/Heroic/Cyberpunk 2077
(00:15:42) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-Proton9-21
(00:15:42) DEBUG:   [Backend]:          Running Wine command: redMod.exe deploy -reportProgress -root U:\Games\Heroic\Cyberpunk 2077
(00:15:46) INFO:    [Gog]:              
(00:15:46) INFO:    [Gog]:              Launching Comet!
(00:15:46) INFO:    [Gog]:              Launching Cyberpunk 2077: HEROIC_APP_NAME=1423049311 HEROIC_APP_RUNNER=gog GAMEID=umu-1091500 HEROIC_APP_SOURCE=gog STORE=gog STEAM_COMPAT_INSTALL_PATH="/home/matt/Games/Heroic/Cyberpunk 2077" WINEDLLOVERRIDES=winmm,version=n,b LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/matt/.local/share/.steam/steam WINEPREFIX="/home/matt/Games/Heroic/Prefixes/Cyberpunk 2077 - proton" STEAM_COMPAT_DATA_PATH="/home/matt/Games/Heroic/Prefixes/Cyberpunk 2077 - proton" PROTONPATH=/home/matt/.config/heroic/tools/proton/Proton-GE-Proton9-21 WINE_FULLSCREEN_FSR=0 PROTON_DISABLE_NVAPI=1 PROTON_EAC_RUNTIME=/home/matt/.config/heroic/tools/runtimes/eac_runtime PROTON_BATTLEYE_RUNTIME=/home/matt/.config/heroic/tools/runtimes/battleye_runtime STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId="heroic-Cyberpunk 2077" PROTON_LOG_DIR=/home/matt/.local/share GOGDL_CONFIG_PATH=/home/matt/.config/heroic/gogdlConfig /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/bin/x64/linux/gogdl --auth-config-path /home/matt/.config/heroic/gog_store/auth.json launch "/home/matt/Games/Heroic/Cyberpunk 2077" 1597316373 --no-wine --wrapper "/usr/bin/mangohud --dlsym "/run/current-system/sw/bin/umu-run"" --platform windows --launcher-skip --prefer-task 0
(00:15:46) INFO:    [Backend]:          Preventing display to sleep
(00:15:46) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(00:15:46) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(00:15:46) INFO:    [Gog]:              Killing Comet!
(00:15:46) INFO:    [Backend]:          Stopped Discord Rich Presence
(00:15:46) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(00:15:46) WARNING: [Backend]:          Posting playtime session to server skipped - playtime sync disabled
(00:15:46) INFO:    [Frontend]:         Refreshing gog Library
(00:15:46) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/matt/.config/heroic/gogdlConfig /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/bin/x64/linux/gogdl --auth-config-path /home/matt/.config/heroic/gog_store/auth.json auth
(00:15:46) INFO:    [Backend]:          Stopping Power Saver Blocker
(00:15:46) INFO:    [Backend]:          Stopping Display Sleep Blocker
(00:15:46) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(00:15:46) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(00:15:46) INFO:    [Gog]:              Getting GOG library
(00:15:46) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/matt/.config/heroic/gogdlConfig /nix/store/4pd6r8rd9hvlmcm0nwhg8jg3filqn4ql-heroic-unwrapped-2.15.2/share/heroic/build/bin/x64/linux/gogdl --auth-config-path /home/matt/.config/heroic/gog_store/auth.json auth
(00:15:47) INFO:    [Gog]:              Saved games data
(00:15:47) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(00:15:47) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
```

### Steps to reproduce

1. Install Cyberpunk 2077 with Redmod DLC
2. Go to Modify Installation -> Redmod Integration
3. Tick "Enable mods"
4. Apply
5. Play Now
6. Game does not start

1. Go to Modify Installation -> Redmod Integration
2. Untick "Enable mods"
3. Apply
4. Play Now
5. Game now starts

### Expected behavior

Game to start

### Screenshots

![image](https://github.com/user-attachments/assets/492d4bb5-be54-4a50-acf0-2ce508a928da)

### Heroic Version

Latest Stable

### System Information

- OS: NixOS 25.05 Unstable
- Heroic: 2.15.2 HOTFIX #2

### Additional information

- Heroic logs: [2024-12-15T00_14_52-heroic.log](https://github.com/user-attachments/files/18138269/2024-12-15T00_14_52-heroic.log)
- GOG logs: [2024-12-15T00_14_52-gogdl.log](https://github.com/user-attachments/files/18138270/2024-12-15T00_14_52-gogdl.log)
- Cyberpunk logs: [1423049311-lastPlay.log](https://github.com/user-attachments/files/18138271/1423049311-lastPlay.log)

**Comment by phazer-11** [comment]
Can confirm that this is an issue.

**Comment by phazer-11** [comment]
Same issue on Steam Deck. Lutris with RedMod works. Adding Lutris install files to Heroic exhibits the same behavior.

**Comment by arielj** [comment]
@imLinguin do you know if this is a problem with gogdl? or maybe a problem when combining different tools and how heroic passes arguments to the different commands?

**Comment by SushiByte-beep** [comment]
I am in the same boat on Arch.  Modded Cyberpunk works better then expected but the moment i enable RedMod nothing starts. 

I am unable to try the toggle in the launcher on account of the launcher itself runs as a black screen. I have to use an argument to skip the launcher to start my game.

**Comment by MattSturgeon** [comment]
> I am in the same boat on Arch.  Cyberpunk works better then expected but the moment i enable RedMod nothing starts.
> 
> I am unable to try the toggle in the launcher on account of the launcher itself runs as a black screen. I have to use an argument to skip the launcher to start my game. 

This issue is specifically about enabling mods with an **empty** redmod list. A non-empty redmod list does not reproduce _this_ issue.

It sounds like you have a different issue that should be reported separately.

**Comment by SushiByte-beep** [comment]
> > I am in the same boat on Arch.  Cyberpunk works better then expected but the moment i enable RedMod nothing starts.
> > I am unable to try the toggle in the launcher on account of the launcher itself runs as a black screen. I have to use an argument to skip the launcher to start my game.
> 
> This issue is specifically about enabling mods with an **empty** redmod list. A non-empty redmod list does not reproduce _this_ issue.
> 
> It sounds like you have a different issue that should be reported separately.

My issue involved both an empty and a non empty mod list. 

However i actually came back because i found something of a workaround.

First is that you can set the argument "-modded " which i believe is similar to having redmod enabled but still requires "deployment" 

I got  deployment working on accident earlier today and could not replicate. I have since found a command that may do it. Further testing recommended. 

`WINEPREFIX="/path_to_WinePrefix_folder/Cyberpunk 2077" wine redMod.exe deploy
`
