### ISSUE TITLE
Heroic no longer starts with latest update 1.10.0-rc1

### ISSUE THREAD

**Issue by lucifertdark** [Heroic-Games-Launcher/HeroicGamesLauncher#684]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
Heroic is no longer starting with the latest update

**To Reproduce**

1. install
2. Click on desktop icon (or run from terminal)
5. Uncaught Exception:
Error: App version is not a valid semver version: "1.10.0rc1"
    at Object.newError (/opt/Heroic/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:47:19)
    at new AppUpdater (/opt/Heroic/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:87:42)
    at new BaseUpdater (/opt/Heroic/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:7:9)
    at new AppImageUpdater (/opt/Heroic/resources/app.asar/node_modules/electron-updater/out/AppImageUpdater.js:15:9)
    at doLoadAutoUpdater (/opt/Heroic/resources/app.asar/node_modules/electron-updater/out/main.js:28:24)
    at Object.get [as autoUpdater] (/opt/Heroic/resources/app.asar/node_modules/electron-updater/out/main.js:35:32)
    at Object.<anonymous> (/opt/Heroic/resources/app.asar/build/updater.js:6:20)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)

**Expected behavior**
normal startup of Heroic client

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu
- Version 20.04.3
- Game:
- Wine/Proton version:6.19
- Hardware specs (RAM, CPU, GPU):

**Additional context**

**Comment by lucifertdark** [comment]
PS the above error is from the deb install, but I get the exact same message from the appimage.

**Comment by flavioislima** [comment]
Yes. I'm aware of that and I'll release a fix for that soon.
