### ISSUE TITLE
Crash at start on GNU/Linux

### ISSUE THREAD

**Issue by Fef0** [Heroic-Games-Launcher/HeroicGamesLauncher#771]
**Describe the bug**
Hi, I just installed Heroic from the AUR but it crashes at start.

**Add Logs**
I launched Heroic from the terminal, then it hangs there with the following error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Function.get (/opt/Heroic/resources/app.asar/build/config.js:36:28)
    at Object.<anonymous> (/opt/Heroic/resources/app.asar/build/main.js:60:27)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (node:electron/js2c/browser_init:197:3197)
    at Object../lib/browser/init.ts (node:electron/js2c/browser_init:197:3401)
```

**Desktop:**
- OS: Arch Linux (kernel 5.15.6-zen2-1-zen)
- DE: GNOME 41.1
- Heroic Version: 1.10.3 (AUR)

**Comment by flavioislima** [comment]
Try to remove all files under `.config/heroic` and try again.
Some file seems to be corrupted somehow.

**Comment by Fef0** [comment]
I confirm that deleting ```.config/heroic``` worked like a charm, thank you!
