### ISSUE TITLE
User permissions confusion

### ISSUE THREAD

**Issue by tfaehse** [Heroic-Games-Launcher/HeroicGamesLauncher#782]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
The Heroic GUI does not show up, the title bar appears however.

The logs already show the issue, Heroic can't access my user folder - however, even resetting user permissions (via repairHomePermissions in recovery) didn't change this for me. Considering no one else had this issue it must be an issue with my installation, but any help would be appreciated really, I don't know what else I could try.
Funnily enough, Heroic launches just fine with sudo, but that's probably not a very safe solution.

**Add Logs**
INFO: Trying to get user information
(node:58951) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/Users/myuser/.config/heroic/GamesConfig/'
    at Object.mkdirSync (node:fs:1324:3)
    at GlobalConfigV0.getSettings (/Applications/Heroic.app/Contents/Resources/app.asar/build/config.js:245:27)
    at GlobalConfigV0.load (/Applications/Heroic.app/Contents/Resources/app.asar/build/config.js:227:38)
    at new GlobalConfigV0 (/Applications/Heroic.app/Contents/Resources/app.asar/build/config.js:236:14)
    at Function.reload (/Applications/Heroic.app/Contents/Resources/app.asar/build/config.js:57:47)
    at Function.get (/Applications/Heroic.app/Contents/Resources/app.asar/build/config.js:43:26)
    at Object.<anonymous> (/Applications/Heroic.app/Contents/Resources/app.asar/build/main.js:60:27)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
(Use `Heroic --trace-warnings ...` to show where the warning was created)
(node:58951) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:58951) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/myuser/.config/heroic/config.json'
    at Object.openSync (node:fs:582:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1800)
    at Object.writeFileSync (node:fs:2143:35)
    at GlobalConfigV0.writeToFile (/Applications/Heroic.app/Contents/Resources/app.asar/build/config.js:208:30)
    at GlobalConfigV0.flush (/Applications/Heroic.app/Contents/Resources/app.asar/build/config.js:307:21)
    at GlobalConfigV0.resetToDefaults (/Applications/Heroic.app/Contents/Resources/app.asar/build/config.js:304:27)
(node:58951) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:58951) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/Users/myuser/.config/heroic/GamesConfig/'
    at Object.mkdirSync (node:fs:1324:3)
    at GlobalConfigV0.getSettings (/Applications/Heroic.app/Contents/Resources/app.asar/build/config.js:245:27)
    at /Applications/Heroic.app/Contents/Resources/app.asar/build/main.js:230:78
(node:58951) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)

**To Reproduce**

1. Launch Heroic

**Expected behavior**
The GUI shows up

**Desktop (please complete the following information):**

- OS: macOS 12.0.1
- Heroic Version: 1.11.0 alpha
- Game: -
- Wine/Proton version: -
- Hardware specs (RAM, CPU, GPU): 32GB RAM, M1 Max

**Additional context**

**Comment by flavioislima** [comment]
probably you have used some app with sudo that wrote the .config folder and now only root owns it.
So try to run this command:
`sudo chown -Rfv user.name .config` replace user.name with your username.
this should fix it.

**Comment by flavioislima** [comment]
but I'm closing this issue since it's not with heroic. Go to our Discord if you need further help.
