### ISSUE TITLE
No Games Found

### ISSUE THREAD

**Issue by redromnon** [Heroic-Games-Launcher/HeroicGamesLauncher#839]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
Heroic doesn't detect any of my games after a successful login.
Looks like a Python bug related to Legendary.

**Add Logs**

```
INFO: Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
[20787:1230/215714.470925:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
INFO: 
  Heroic Version: 2.0.0 Roronoa Zoro
  Legendary Version:  0.20.22 Anticitizen One (hotfix #3)
  OS: Pop KERNEL: 5.15.8-76051508-generic ARCH: x64
  CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx @2.1 GOVERNOR: conservative
  RAM: Total: 6.2 GB Available: 4.04 GB
  GRAPHICS: GPU0: Picasso VRAM: 512MB DRIVER:  
  PROTOCOL: x11
  
ERROR: Failed to register protocol with OS.
[20753:1230/215715.247346:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[20753:1230/215715.247572:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[20753:1230/215715.247743:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
WARNING: python command not found
INFO: Command 'python3' found. Version: '3.8.10'
INFO: Frontend: Refreshing Library
INFO: Refreshing library...
INFO: Legendary: Refreshing Epic Games...
INFO: Refreshing Epic Games...
[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Getting game list... (this may take a while)

INFO: checking for heroic updates
Traceback (most recent call last):
  File "legendary/cli.py", line 2317, in <module>

  File "legendary/cli.py", line 2240, in main
  File "legendary/cli.py", line 197, in list_games
  File "legendary/core.py", line 387, in get_game_and_dlc_list
  File "legendary/core.py", line 335, in get_assets
  File "legendary/api/egs.py", line 134, in get_game_assets
  File "requests/models.py", line 953, in raise_for_status
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/public/assets/Windows?label=Live
[20934] Failed to execute script 'cli' due to unhandled exception!

INFO: Updating game list
INFO: Game List Updated
INFO: Frontend: No cache found, getting data from legendary...
INFO: Refreshing library...
INFO: Updating game list
INFO: Game List Updated
INFO: Checking for game updates
INFO: Found 0 game(s) to update
```

Check on how to [run Heroic from Terminal or Powershell](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#running-heroic-from-terminalpowershell-to-debug-errors) and put some logs here

**To Reproduce**
Just login into Epic Games after opening Heroic for the first time.

**Expected behavior**
Display game library

**Screenshots**
None

**Desktop (please complete the following information):**

- OS: Pop OS 20.04
- Heroic Version 2.0.0

**Additional context**
None

**Comment by redromnon** [comment]
Looks like Epic Games servers are facing issues right now, especially related to Login.
