### ISSUE TITLE
Unable to launch - Fedora 35

### ISSUE THREAD

**Issue by IvoryJam** [Heroic-Games-Launcher/HeroicGamesLauncher#901]
Heroic fails to launch, installed via the copr repo.

OS: Fedora 35
Display: X11
DE: XFCE
Kernel: 5.15.13-200.fc35.x86_64
Arch: 64 bit

Heroic Version: heroic-games-launcher-bin-2.0.2-1.fc35.x86_64

```INFO: Legendary location: /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/linux/legendary
(node:35059) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.get (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/config.js:36:28)
    at getLegendaryVersion (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/utils.js:63:61)
    at getSystemInfo (/usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/utils.js:140:68)
    at /usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/main.js:185:60
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:35059) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by flavioislima** [comment]
It seems some config file might be corrupted.
Try to rename/delete `$home/.config/heroic` folder.

**Comment by IvoryJam** [comment]
Removing that holder worked, thank you!
