### ISSUE TITLE
Wine executable existence is only checked when opening settings, not when launching game

### ISSUE THREAD

**Issue by CommandMC** [Heroic-Games-Launcher/HeroicGamesLauncher#941]
**Describe the bug**
When launching a game, if the Wine version set for the game is missing, Legendary throws an error behind the scenes. For the user, the Play button will briefly show "Playing", then return back to "Play" with no visible error.  
Once the settings for the game are accessed, the version is checked & set to the default if the executable is missing.

**Add Logs**

Log of latest release:
<details>

```
INFO: [Legendary]: Launch Command:     WINEESYNC=1 WINEFSYNC=1        /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Quail   --wine '/home/commandmc/.config/heroic/tools/wine/wine-ge-7.0rc3-1-x86_64/bin/wine64' --wine-prefix '/home/commandmc/Wine/Prefixes/20xx'  
INFO: [Legendary]: Getting More details with Legendary info command... 
ERROR: [Backend]: TypeError - convertToStringArray(...).join is not a function
INFO: [Legendary]: Getting More details with Legendary info command...
```
</details>

Log of [latest master](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/1768786311):
<details>

```
(23:11:14) INFO:    [Legendary]:       Launch Command:     WINEESYNC=1 WINEFSYNC=1        /tmp/.mount_HeroicDkfrFW/resources/app.asar.unpacked/build/bin/linux/legendary launch Quail   --wine '/home/commandmc/.config/heroic/tools/wine/wine-ge-7.0rc3-1-x86_64/bin/wine64' --wine-prefix '/home/commandmc/Wine/Prefixes/20xx'  
(23:11:14) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(23:11:15) ERROR:   [Legendary]:       Error: Command failed:     WINEESYNC=1 WINEFSYNC=1        /tmp/.mount_HeroicDkfrFW/resources/app.asar.unpacked/build/bin/linux/legendary launch Quail   --wine '/home/commandmc/.config/heroic/tools/wine/wine-ge-7.0rc3-1-x86_64/bin/wine64' --wine-prefix '/home/commandmc/Wine/Prefixes/20xx'  
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Quail...
[cli] DEBUG: Launch parameters: /home/commandmc/.config/heroic/tools/wine/wine-ge-7.0rc3-1-x86_64/bin/wine64 /home/commandmc/Games/Legendary/TwentyXX/20XX.exe -AUTH_LOGIN=unused -AUTH_PASSWORD=<redacted> -AUTH_TYPE=exchangecode -epicapp=Quail -epicenv=Prod -EpicPortal -epicusername=CommandMC -epicuserid=fc96b362d51c4c2b8ed0684e9403062a -epiclocale=en -epicsandboxid=4c7117cadb714722950338f02850fd8d
[cli] DEBUG: Working directory: /home/commandmc/Games/Legendary/TwentyXX
[cli] DEBUG: Environment overrides: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/commandmc/.steam/steam, WINEPREFIX=/home/commandmc/Wine/Prefixes/20xx
Traceback (most recent call last):
  File "legendary/cli.py", line 3004, in <module>
  File "legendary/cli.py", line 2919, in main
  File "legendary/cli.py", line 685, in launch_game
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1704, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/commandmc/.config/heroic/tools/wine/wine-ge-7.0rc3-1-x86_64/bin/wine64'
[25611] Failed to execute script 'cli' due to unhandled exception!
```
</details>

**To Reproduce**

1. Install a Wine version
2. Set this Wine version for a game
3. Delete the files for this Wine version manually
4. Try to launch the game

**Expected behavior**
The Wine version's existence should be checked when launching the game as well. Simply running the same check the settings run before launching a game would be the easiest solution.  
Note that some kind of warning message would be ideal, à la "The Wine version selected for this game does not exist anymore" -> "Cancel launch" / "Continue with default Wine version"

**Desktop (please complete the following information):**

- OS: Arch Linux
- Heroic Version 2.1.0, but master was also tested
- Game: N/A
- Wine/Proton version: N/A
- 
  <details>
  <summary>Hardware specs (RAM, CPU, GPU)</summary>

  ```
  $ inxi -cSGM
  System:
    Host: Arch Kernel: 5.16.3-arch1-1 x86_64 bits: 64
      Desktop: KDE Plasma 5.23.5 Distro: EndeavourOS
  Machine:
    Type: Desktop Mobo: ASUSTeK model: ROG STRIX X570-E GAMING v: Rev X.0x
      serial: <superuser required> UEFI: American Megatrends v: 2606
      date: 08/13/2020
  Graphics:
    Device-1: NVIDIA GA104 [GeForce RTX 3070] driver: nvidia v: 495.46
    Display: x11 server: X.Org 1.21.1.3 driver: loaded: nvidia resolution:
      1: 1920x1080~60Hz 2: 1920x1080~60Hz
    OpenGL: renderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
      v: 4.6.0 NVIDIA 495.46
  ```
  </details>

**Comment by CommandMC** [comment]
Actually, it looks like this is more of an issue than I thought. Somehow, I now have a desync between what's displayed in the settings and what's actually done:  
![image](https://user-images.githubusercontent.com/34034631/151723801-8da624e0-21d1-4f3e-a125-8e837d1fd401.png)  
![image](https://user-images.githubusercontent.com/34034631/151723818-624f3419-d936-41c2-8a5d-287caaf1e777.png)

**Comment by flavioislima** [comment]
Its not a sync issue, the thing is that the Game settings is stored into a JSON file and this file is only updated if you change some settings. What would be the purpose of updating the settings when not changing them?
So the game was using a wine that was removed from your machine, there is no way Heroic to know that right now.
I remember that I added an Error dialog if the wine was not found but probably is not checking the path correctly.

I think the best Heroic can do is to, when running a game, if wine binary wasn't found, show a warning and update the setting to use the default wine.
The problem is that, if the game is running Proton, and then Heroic uses Wine, the prefix will be different, so the game saves and settings will be missing.

I think showing an error message and then asking the user to update the settings is the best way to handle that.

**Comment by flavioislima** [comment]
So yes, like you said. A dialog with Cancel or Run with default wine should work just fine 👍🏽

**Comment by Nocccer** [comment]
Legendary has the error message. We just need to catch it and print error. If the user chooses default wine restart launch command

**Comment by flavioislima** [comment]
> Legendary has the error message. We just need to catch it and show error dialog. If the user chooses to restart with default wine, just restart the launch command

I think it's more complicated that way. Use `existAsync` to check if Wine binary exists or not is better.
I also would like to not rely on parsing a String for Errors since if Legendary changes the error message, it will break on our end.

**Comment by Nocccer** [comment]
Good point. Then let's insert a existSync

**Comment by CommandMC** [comment]
> the thing is that the Game settings is stored into a JSON file and this file is only updated if you change some settings

Well, in this case a setting *is* changed, but not by the user. So the file should still get updated IMO

**Comment by flavioislima** [comment]
> > the thing is that the Game settings is stored into a JSON file and this file is only updated if you change some settings
> 
> Well, in this case a setting _is_ changed, but not by the user. So the file should still get updated IMO

Yes but updated how? After the user try to launch the game you mean? 
Because if we do that automatically, we would override using the default wine. And that might be an issue.

**Comment by CommandMC** [comment]
Seems like this was fixed in 3176d2e

**Comment by flavioislima** [comment]
Yes forgot to close this issue.
